### ISSUE TITLE
502 Error on IRC -> Mattermost Post

### ISSUE THREAD

**Issue by RangerRick** [42wim/matterbridge#1]
I'm not sure if this is matterbridge or mattermost's doing, but I've just configured matterbridge and while everything is working perfectly mattermost -> irc, irc -> mattermost is throwing errors: https://gist.github.com/RangerRick/d9cbb4c28dea78ae396f#file-mattermost-log

The only output I get in matterbridge.log is:
```2015/11/03 14:50:46 unexpected status code: 502```

**Comment by 42wim** [comment]
90% sure it's mattermost's doing ;-)
But can you reproduce it? specific messages that trigger it ? or random ?

**Comment by RangerRick** [comment]
It happens every single time someone writes something in the IRC channel.

**Comment by 42wim** [comment]
Strange. Can you reproduce it using curl ? using the same url as specified in your matterbridge.conf

```
curl -i -X POST -d 'payload={"text": "random text"}' http://mattermost.yourdomain.com/hooks/incomingwebhookkey
```

**Comment by RangerRick** [comment]
Hm, yup, same failure.  I guess I should go open an issue to mattermost, then.  :)

**Comment by RangerRick** [comment]
It was because of a database issue from doing surgery on the database.  I just rebuilt my team and everything's working now.  Sorry for the noise.
