### ISSUE TITLE
make the format of the posted messages configurable

### ISSUE THREAD

**Issue by RangerRick** [42wim/matterbridge#10]
I'm running a fork right now that changes the output to match the way slack does it:

```
diff --git a/matterbridge.go b/matterbridge.go
index a07ab30..3369ae8 100644
--- a/matterbridge.go
+++ b/matterbridge.go
@@ -116,7 +116,7 @@ func (b *Bridge) handleMatter() {
                }
                texts := strings.Split(message.Text, "\n")
                for _, text := range texts {
-                       b.i.Privmsg(b.getIRCChannel(message.Token), message.UserName+": "+text)
+                       b.i.Privmsg(b.getIRCChannel(message.Token), "<" + message.UserName+"> "+text)
                }
        }
 }
```

I tried implementing this in a configurable manner but I don't know go at all and couldn't figure out how to do "default" values in config files that differentiate between wanting empty string and whatever go's equivalent of "null" would be.  :)

**Comment by 42wim** [comment]
I just added a UseSlackCircumfix option ;-)
If set to true, you'll get the <nick>

**Comment by RangerRick** [comment]
Oh, nice!   Thanks!
