### ISSUE TITLE
Config not clear

### ISSUE THREAD

**Issue by InFerYes** [42wim/matterbridge#100]
I'm using Matterbridge version: 0.9.1-dev, and Mattermost is version: 3.4.0 with database: mysql

What I'm trying to do is make a connection between Mattermost and Slack.
Matterbridge is built on the same server as Mattermost. Mattermost is working and people are able to chat.

I'm thoroughly confused by the config of Matterbridge. There are 2 files that are seemingly the same but different (config and toml). There is an API option and a webhook option. 

Webhooks: I'm not sure what to replace the BindAddress with (0.0.0.0:9999). I've created incoming hooks easily, since it produces a URL, but I'm not sure if the outgoing webhooks are OK. In Slack, are trigger words required? I want all messages exchanged. In Mattermost outgoing webhooks it asks for a callback URL, what URL is this?

API: Where do I get the tokens for Slack? Slack generated a client ID and a client secret. I'm guessing it's the secret I need to use?

Do I have to configure both Mattermost and Slack in the configs, or only Slack (because Matterbridge is running on the same server)?

Thank you

**Comment by ishitatsuyuki** [comment]
Asking questions in issue tracker is not ideal, but I will answer anyway.

- Use TOML (it changed in 0.7+)
- Bind to 127.0.0.1 for same host setup
- Tokens: maybe create an app for Slack (consult [here](https://api.slack.com/web))
- Configure `inout` for both
  Although this project first started for Mattermost, it's now pluggable and general-purpose.

**Comment by InFerYes** [comment]
This can be taken as an "issue" to update the configuration files and better explain how these things work since it's probably outdated and confusing to say the least. I'd happily contribute to the effort to make the documentation better.

- Ok I will use TOML
- So bind address 0.0.0.0:9999 should be 127.0.01:9999?
- I have created an app but it gave me a Client ID and Client Secret, is the secret the token?
- What do you mean it's general purpose? Is `inout` a setting or do you mean "configure both incoming and outgoing webhooks? If the latter, it's unclear how to configure outgoing webhooks. Also, if you suggest using an API token, then webhooks are disabled, which is adding to the confusion.

**Comment by ishitatsuyuki** [comment]
https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample

Please read the sample. It answers all your questions.

**Comment by InFerYes** [comment]
I wouldn't have asked if it answered all of my questions.

**Comment by ishitatsuyuki** [comment]
Here's some line markers in the case you're a newbie.

https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample#L309
https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample#L498

Additionally, you have two choices Slack/Mattermost, dedicated user or API.

**Comment by InFerYes** [comment]
I'm using API on both Mattermost and Slack. I can see messages from Slack in Matterbridge debug output, but they're not displayed in Mattermost. I've confirmed that the username and password are correct (and when starting Matterbridge with the debug flag it does not show any login errors).

```DEBU[2016-12-14T11:54:16+01:00] trying login bitstorm slackbot 127.0.0.1:8065  module=matterclient
DEBU[2016-12-14T11:54:16+01:00] initUser(): found our team bitstorm (id: removed)  module=matterclient
DEBU[2016-12-14T11:54:16+01:00] WsClient: making connection                   module=matterclient
INFO[2016-12-14T11:54:16+01:00] Connection succeeded                          module=mattermost
```

I'm using a test-api token on Slack, but now I'm not sure why messages go from Mattermost to Slack, but not the other way around.

I've tried `inout` and `samechannelgateway`.

I'm not sure if it's a Mattermost or Matterbridge problem.
