### ISSUE TITLE
No description in Discord embed causes duplicate separator

### ISSUE THREAD

**Issue by haykam821** [42wim/matterbridge#1008]
If an embed with no description is sent, the separator in the embed will duplicate.

## Reproduction Steps

* Receive a Discord embed without a description on another location.

## Expected Behavior

There should only be one separator between the embed’s title and URL when it has no description. Instead of `Title - - https://example.org`, it should be just `Title - https://example.org`.

## Screenshots / Logs

![Embed with no description](https://user-images.githubusercontent.com/24855774/74166323-619cf080-4bf4-11ea-8beb-c866ca2de409.png)

## Environment

* **OS:** linux
* **Matterbridge version:** 1.16.5 4be00bbe

## Additional Context

The bug occurs here:

https://github.com/42wim/matterbridge/blob/4c44515f9df8eb0eb67116f05cb50820d800f961/bridge/discord/handlers.go#L106

```toml
```

**Comment by burner1024** [comment]
Huh, does matterbridge actually pass hook messages from Discord? In #1027, I'm not seeing this.
