### ISSUE TITLE
Failure to Get Mattermost Channel ID

### ISSUE THREAD

**Issue by jgalvez** [42wim/matterbridge#1010]
**Describe the bug**
Using an install of mattermost version: 5.18.0 and matterbridge (c0be3e585a5ef6c6dc4d517e891fd10bc053c195) fails to start the gateway when connecting to the mattermost channel. I executed with -debug and found that the channel ID was coming back empty. The mattermost instance reported the ID so I copied that into the src, built + installed resulting in matterbridge starting and joining the mattermost channel without issue. 

**To Reproduce**

Please see the above description.

**Expected behavior**

Matterbridge should successfully retrieve the channel ID for a mattermost channel.

**Screenshots/debug logs**
Use logs from running `matterbridge -debug` if possible.

```
[0001]  INFO mattermost:   Connection succeeded
[0001]  INFO mattermost:   mattermost.snc: joining https://<mattermost-install>/<team>/channels/<channel> (ID: https://<mattermost-install>/<team>/channels/<channel>mattermost.snc)
[0001] FATAL main:         Starting gateway failed: Bridge mattermost.snc failed to join channel: Could not find channel ID for channel https://<mattermost-install>/<team>/channels/<channel>
```

**Environment (please complete the following information):**
 - OS: [e.g. linux]: 
`Ubuntu 18.04.4 LTS`

 - Matterbridge version: output of  `matterbridge -version`
```
juanjose@mattermost:~/go/src/github.com/42wim/matterbridge$ ~/go/bin/matterbridge version
[2020-02-15T03:55:10Z]  INFO main:         Running version 1.16.6-dev
[2020-02-15T03:55:10Z]  INFO main:         WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
[2020-02-15T03:55:10Z] FATAL config:       Failed to read configuration file: &os.PathError{Op:"open", Path:"matterbridge.toml", Err:0x2}
```
 - If self compiled: output of `git rev-parse HEAD`
```
juanjose@mattermost:~/go/src/github.com/42wim/matterbridge$ git rev-parse HEAD
da0c2601abfd8c06904170d74a559cea81275435
```

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))

```
[irc]
    [irc.oftcnet]
    Server="irc.oftc.net:6697"
    Nick="<bot-irc-user>"
    UseTLS=true
    SkipTLSVerify=false
    RunCommands=["PRIVMSG nickserv :IDENTIFY <bot-irc-user> <bot-irc-pass>"]
    ColorNicks=true

[mattermost]
    [mattermost.snc]
    Server="<mattermost-install>:443"
    Team="<team>"
    Login="<bot name>"
    Token="<bot token>"
    PrefixMessagesWithNick=true

[general]
RemoteNickFormat="[{PROTOCOL}/{BRANCH}] <{NICK}> "

[[gateway]]
name="scattered-gateway"
enable=true

    [[gateway.out]]
    account="mattermost.snc"
    channel="https://<mattermost-install>/<team>/channels/<mattermost-channel>"

    [[gateway.in]]
    account="irc.oftcnet"
    channel="<irc-channel>"
```

**Comment by 42wim** [comment]
Your config is wrong, should be

```
    [[gateway.out]]
    account="mattermost.snc"
    channel="<mattermost-channel>"
```

**Comment by jgalvez** [comment]
Thanks for taking the time to look this over and reply. I've confirmed my problem and closed this out.
