### ISSUE TITLE
Incorrect protocol msteams specified in gateway configuration msteams.teams, exiting.

### ISSUE THREAD

**Issue by Maxence** [42wim/matterbridge#1014]
Hi there,

Someone know if Microsoft Teams is still supported ?

If I add this to my conf :

```
[msteams.teams]
TenantID="my tenant ID"
ClientID="my client ID"
TeamID="my team ID"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway.inout]]
                account="msteams.teams"
                channel="19:817f0e433d1e41e0a69c1a9f64363bc3@thread.skype"
```

I got this error : 

> "Incorrect protocol msteams specified in gateway configuration msteams.teams, exiting."

I followed this setyp config :
https://github.com/42wim/matterbridge/wiki/MS-Teams-setup

**Comment by 42wim** [comment]
Hi, msteams hasn't been merged yet. Will be soon.
You can find the PR to test with here: https://github.com/42wim/matterbridge/pull/967
