### ISSUE TITLE
Setting Remotenick on a gateway basis

### ISSUE THREAD

**Issue by Weneg** [42wim/matterbridge#1016]
First of all: Sorry if its already asked but i couldn't find anything!

I would like to know if its possible to set RemoteNick or PrefixMessagesWithNick on a gateway basis for the same account.

We want to connect multiple Telegram Channels to our Mattermost but only 2 of them are supposed to have the Nick in the messages relayed from mattermost. 

I tried to just configure 2 accounts for the same telegram bot but it didn't work right. It didn't relay messages correctly anymore.

I could solve this by using two different telegram bots but i would like to avoid that

As an example i would like to configure it something like this (It doesnt contain a telegram account but it shouldn't matter in this example):

```
[irc]
    [irc.freenode]
    Server="irc.freenode.net:6667"
    Nick="yourbotname"

[mattermost]
    [mattermost.work]
    Server="yourmattermostserver.tld"
    Team="yourteam"
    Login="yourlogin"
    Password="yourpass"

[[gateway]]
name="mygateway"
enable=true
    [[gateway.inout]]
    account="irc.freenode"
    channel="#testing"
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

    [[gateway.inout]]
    account="mattermost.work"
    channel="off-topic"

[[gateway]]
name="mygateway2"
enable=true
    [[gateway.inout]]
    account="irc.freenode"
    channel="#testing2"
    RemoteNickFormat=""

    [[gateway.inout]]
    account="mattermost.work"
    channel="off-topic2"
```

**Comment by 42wim** [comment]
You can probably get this behaviour by using tengo 

You can find more tengo examples here:
https://github.com/42wim/matterbridge/issues?q=is%3Aissue+tengo+label%3Atengo+is%3Aclosed

here:
https://github.com/42wim/matterbridge/tree/master/internal/tengo

and here:
https://github.com/42wim/matterbridge/tree/master/contrib

The tengo documentation can be found here:
https://github.com/d5/tengo/tree/master/docs

**Comment by Weneg** [comment]
I'll look at this on the weekend!
Thanks for the information. 
I will report if it works :)

**Comment by 42wim** [comment]
If you got it working,  please report or contribute a PR with your tengo script.
Thanks!
