### ISSUE TITLE
Messages to Matrix get markdown formatted

### ISSUE THREAD

**Issue by Mikaela** [42wim/matterbridge#1022]
**Describe the bug**

When a message is sent from e.g. XMPP or IRC that is accidentally markdown, Matrix receives the message markdownified. This is especially distruptive when sending code or links that happen to contain underscores.

**To Reproduce**

Demo instance: Send a message beginning with `# ` on https://t.me/Matterbridge and watch it become a `<h1>` on [`#matterbridge:matrix.org`](https://view.matrix.org/room/!zySiFNhIBsCmRSzryo:matrix.org/).

**Expected behavior**

I expect the message to leave and arrive as plaintext without getting strangely interpreted as markdown making the message difficult to read.

**Screenshots/debug logs**

![Telegram](https://user-images.githubusercontent.com/831184/75803503-2de26000-5d87-11ea-9745-9cced209b889.png)

![Matrix](https://user-images.githubusercontent.com/831184/75803577-566a5a00-5d87-11ea-8350-830371a152a0.png)

Debug log: not applicable

**Environment (please complete the following information):**
 - OS: Debian GNU/Linux 9.12 (stretch)
 - Matterbridge version: 1.16.5 4be00bbe

**Additional context**

Config file has two IRC networks, one Matrix server, one XMPP server and

```
[general]
RemoteNickFormat="[{LABEL}] <{NICK}> "
IgnoreFailureOnStart=false
MessageSplit=true
```

more information available on request, but the configuration or gateways don't seem relevant as I can reproduce this on the support group/room matterbridge.

**Comment by qaisjp** [comment]
If you sent a message starting with `#` as a normal user on Matrix, would it render as a `<h1>`? If so, then imo I this should be kept as default behaviour with "`no-markdown-rendering`" kept behind a setting.

i.e. imo someone saying `One **two** three four` should render on other Markdown-supporting platforms as "One **two** three four"

**Comment by Mikaela** [comment]
> If you sent a message starting with # as a normal user on Matrix, would it render as a \<h1\>?

Yes and if I send 

> testing https://www.reddit.com/r/gaming/comments/fcvmfo/can_we_all_agree_the_tiger_knee_position_is_the/ top of /r/all

it will be

> testing https://www.reddit.com/r/gaming/comments/fcvmfo/can_we_all_agree_the_tiger_knee_position_is_the/ top of /r/all

but if it's send through matterbridge it's suddenly

> testing https://www.reddit.com/r/gaming/comments/fcvmfo/canweallagreethetigerkneepositionis_the/ top of /r/all

Reddit is a bid bad example as it recognises that ID `fcvmfo` causing the link to still work, but I imagine it would break in many other situations.

**Comment by 42wim** [comment]
@Mikaela your last issue with the underscores is already fixed in master a while ago.
Could you run matterbridge dev build? https://bintray.com/beta/#/42wim/nightly/Matterbridge/v1.16.5-30-g6b4b191?tab=files

**Comment by 42wim** [comment]
@Mikaela or run v1.17.0 which is now out

**Comment by Mikaela** [comment]
Sorry, I missed your previous comment 9 days ago, but yes, link handling seems to now be fixed.

I still wish I could disable the rest of the markdown though.

**Comment by Mikaela** [comment]
Some issues I have noticed today and that have caused headscratching:

* XMPP sending e.g. `</sarcasm>` to Matrix results an empty message unless the Matrix user looks into message source.
* Sending a list of things to do from IRC:

```
1. have more caffeine
2. do something
3. do something more
```

results into Matrix having everything labeled as `1.` as matterbridge converts plaintext-IRC to markdown unexpectedly.

**Comment by Mikaela** [comment]
Mathematics from Telegram to Matrix are also interesting.

![https://t.me/Piraattinuoret/15904](https://user-images.githubusercontent.com/831184/81851710-93f71a80-9562-11ea-827a-a871302de8c1.png)

![photo_2020-05-13_21-42-20](https://user-images.githubusercontent.com/831184/81851761-a83b1780-9562-11ea-8d00-d845e592d937.jpg)

**Comment by 42wim** [comment]
HTMLDisable option is now available in master.

**Comment by bkil** [comment]
Thanks for the feature. I wanted to enable just this, but I've ran into an issue:
- #1382 _HTMLDisable for Matrix adds empty `format` and `formatted_body` fields_
