### ISSUE TITLE
One-way gateways

### ISSUE THREAD

**Issue by glazzara** [42wim/matterbridge#1023]
**Is your feature request related to a problem? Please describe.**

I would like to be able to send messages on both Slack and Whatsapp. I want to send them from Slack but I don't want to get answers from whatsapp. Like broadcasting on several channels/services.

**Describe the solution you'd like**
Something like : 
```
[[gateway]]
name="gateway1"
enable=true

[[gateway.out]]
account="whatsapp.account"
channel="xxxxxxxxxxx@g.us"

[[gateway.in]]
account="slack.account"
channel="my-channel"
```

What do you think?

**Comment by glazzara** [comment]
It already exists. Sorry...

**Comment by jtagcat** [comment]
Could you please describe the solution?
