### ISSUE TITLE
Telegram: Markdown V2 doc

### ISSUE THREAD

**Issue by burner1024** [42wim/matterbridge#1032]
Please add [Markdown V2](https://core.telegram.org/bots/api#markdownv2-style) to doc/examples.
The original markdown [isn't parsing underscores in links correctly](https://github.com/42wim/matterbridge/issues/444#issuecomment-397072900).
I tried setting `MessageFormat="MarkdownV2"` in `matterbridge.toml`, and surprisingly, I think it just works? At least, underscores aren't swallowed by the parser. Not yet sure if there are any side effects.

**Comment by 42wim** [comment]
Thanks! Seems to be a recent feature, december 2019
Could you make a PR with an updated `matterbridge.toml.sample`  ?
Also feel free to edit the wiki on https://github.com/42wim/matterbridge/wiki/Settings#telegram

**Comment by burner1024** [comment]
Made, edited.

**Comment by 42wim** [comment]
Thanks for your help! 👍
