### ISSUE TITLE
Telegram channels cannot be bridged due to different ID format

### ISSUE THREAD

**Issue by haykam821** [42wim/matterbridge#1033]
**Describe the bug**
Telegram channels, which have the ID format `@link_text`, are not supported because they are non-numeric.

**To Reproduce**
* Send a message in a bridged Telegram channel.

**Expected behavior**
It mirrors like groups that have numeric IDs.

**Screenshots/debug logs**
```
level=error msg="SendMessage failed: strconv.ParseInt: parsing "@channel_name": invalid syntax" prefix=gateway
```

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: 1.16.5 4be00bbe

**Comment by 42wim** [comment]
According to the documentation telegram channels have an `int` ID
See https://core.telegram.org/constructor/channel
Where do you find the `@link_text` ?

**Comment by haykam821** [comment]
Sorry, to clarify, when I try to use `@link_text`, it will reject the ID despite the Telegram ID supporting it as the channel ID. It comes from the share link set in the channel settings; if the share link was `https://t.me/[link]`, the channel ID would be `@[link]`.

**Comment by 42wim** [comment]
This doesn't seem to be exposed by the telegram API, so we can't support that.
