### ISSUE TITLE
About the location of the whatsapp session file

### ISSUE THREAD

**Issue by stillnaughty** [42wim/matterbridge#1034]
Hi...
Would you mind asking where's the whatsapp session file reside as I can't it after scanning the QR code running inside the docker.

I've called `docker exec -it <docker> sh` to go inside docker daemon but I just can't find the corresponding file.

Would anyone could help guide me through?
Thank you so much

**Comment by qaisjp** [comment]
Where did you find it?

**Comment by stillnaughty** [comment]
Nope really.... I found out seems if SessionFile is set the next time the docker restart no need to scan the QR code again.

However, turn out I believe I still need to know the location of the session file and backup in case any problems on the docker that need to be reinstalled

So, would anybody help this thro? Thanks

**Comment by qaisjp** [comment]
See [whatsapp config](https://github.com/42wim/matterbridge/blob/6b4b19194ec40c79569bc692a6557e78f338ded9/matterbridge.toml.sample#L1282-L1307
) in `matterbridge.toml.sample`, specifically

```toml
# First time that you login you will need to scan QR code, then credentials willl be saved in a session file
# If you won't set SessionFile then you will need to scan QR code on every restart
# optional (by default the session is stored only in memory, till restarting matterbridge)
SessionFile="session-48111222333.gob"
```

So assuming you are setting the session filename, it will be relative to the current working directory inside docker. Can we see your Dockerfile or docker-compose file?

**Comment by stillnaughty** [comment]
seems solved... yup... in the root directory once it scan... great~
