### ISSUE TITLE
Logging in with bearer token to mattermost

### ISSUE THREAD

**Issue by GCHQ77703** [42wim/matterbridge#1038]
**Describe the bug**
Unable to login to a mattermost instance via bearer token.

**To Reproduce**
- Generate a bearer token for mattermost
- Attempt to login

**Expected behavior**
- If you put it in the 'password' field, it errors out.

**Comment by qaisjp** [comment]
Please can you share your config file? (don't forget to remove passwords/tokens)

Also could you run with `-debug` and put the log somewhere (for example in [pastebin](https://pastebin.com))?

**Comment by 42wim** [comment]
What is a "bearer token", do you mean a personal access token?
Then you have to use Token. See https://github.com/42wim/matterbridge/wiki/Settings#token-1

**Comment by 42wim** [comment]
Closing because no feedback.
