### ISSUE TITLE
Discord embed looks dodgy

### ISSUE THREAD

**Issue by qaisjp** [42wim/matterbridge#1049]
**Describe the bug**

Sending a series of links on Discord causes output on Slack that seems to miss a leading newline.

**To Reproduce**

1. Send `https://youtube.com/ https://google.com/ https://discordapp.com/` on Discord
2. Look at Slack
3. If it doesn't work, send `https://youtube.com/ https://google.com/ https://discordapp.com/` on Discord again
4. Look at slack

You might have to do it a second time because I think Discord unfurling is late. 

Note that the first time those link appear in Slack, you will see [Slack's unfurling] — Slack's unfurling won't appear the second time because they only unfurl once per "recent conversation" (to prevent embeds spamming up your screen). To get around Slack's unfurl "spam protection", you can _cache bust_ by appending something to the query string: `https://youtube.com/?1`

[Slack's unfurling]: https://user-images.githubusercontent.com/923242/77235564-b5650700-6bae-11ea-824a-96a67ba65da4.png

**Expected behavior**

Either have a newline, or don't send Discord embeds if they are only unfurl embeds.

**Screenshots/debug logs**

![image](https://user-images.githubusercontent.com/923242/77235539-6e771180-6bae-11ea-8548-c8ea312120ad.png)

**Environment (please complete the following information):**

e9edbfc0, macOS

**Additional context**

Nothing of significance other than `ShowEmbeds`:

```
[discord]
[discord.mta]
Token="..."
Server="..."
RemoteNickFormat="{NICK}"
WebhookURL="..."
ShowEmbeds=true

[slack]
[slack.mta]
Token="..."
RemoteNickFormat="{NICK}"
```

**Comment by 42wim** [comment]
Hm tried to reproduce this, but nothing happens on the slack side, tried sending multiple times.

![image](https://user-images.githubusercontent.com/1810977/77852327-620e3c80-71de-11ea-8ac0-2d1163ec7523.png)

**Comment by 42wim** [comment]
@qaisjp still an issue ?

**Comment by qaisjp** [comment]
Um let me try and reproduce on latest master (can't now though)

To confirm you've tried cache busting, right?

**Comment by 42wim** [comment]
No I haven't, but I couldn't produce it on the first message.

**Comment by qaisjp** [comment]
I can definitely reproduce this on 2d8f749

it only works _after_ the first message (because discord has the embed cached)
