### ISSUE TITLE
go get fails wtih errors

### ISSUE THREAD

**Issue by teadur** [42wim/matterbridge#105]
Please answer the following questions. 

### Which version of matterbridge are you using?
latest from github

### Please describe the expected behavior.
no errors is thrown

#### Use logs from running ```matterbridge -debug``` if possible.

matterbridge@mattermost:~/go$ go get github.com/42wim/matterbridge
# golang.org/x/crypto/poly1305
src/golang.org/x/crypto/poly1305/sum_amd64.s:8 6a: No such file or directory: textflag.h
# github.com/gorilla/websocket
src/github.com/gorilla/websocket/client.go:406: unknown tls.Config field 'GetCertificate' in struct literal
src/github.com/gorilla/websocket/compression.go:33: undefined: flate.Resetter
# github.com/42wim/matterbridge/bridge/gitter
src/github.com/42wim/matterbridge/bridge/gitter/gitter.go:62: b.c.GetUsersInRoom undefined (type *gitter.Gitter has no field or method GetUsersInRoom)

**Comment by 42wim** [comment]
output of ```go version``` ?

**Comment by teadur** [comment]
go version go1.3.3 linux/amd64

**Comment by 42wim** [comment]
the requirements are go1.6+ as stated in the readme

**Comment by teadur** [comment]
you are right, thank you for pointing it out, sorry for my ignorance.
