### ISSUE TITLE
Matterbridge prints random stuff on screen and crashes

### ISSUE THREAD

**Issue by niansa** [42wim/matterbridge#1058]
**Describe the bug**
Matterbridge prints random stuff on screen and crashes while starting up

**To Reproduce**
1. download current release
2. configure both telegram and IRC

**Expected behavior**
The bot should simply... work

**Screenshots/debug logs**
Use logs from running `matterbridge -debug` if possible.
https://del.dog/amomesodan.txt

**Environment (please complete the following information):**
 - OS: Linux; Ubuntu 19.10 Server (arm64)
 - Matterbridge version: version: 1.17.0 cca1ea24

**Additional context**
Config: https://del.dog/modellytha.toml

**Comment by 42wim** [comment]
Are you using qemu? Looks like a qemu error?
I don't have access to arm64 to test myself.
Please try building the binary yourself from source and see if you can reproduce it.

**Comment by 42wim** [comment]
Also 1.17.1 is released, if still an issue please reopen
