### ISSUE TITLE
Matrix -> Discord resize image that are too big for upload

### ISSUE THREAD

**Issue by t-my** [42wim/matterbridge#1060]
**Is your feature request related to a problem? Please describe.**
If you upload over 1000000 bytes image to Matrix, it will show up as a error message in Discord like ```<system> file Screenshot_20200327_092811.png too big to download (1009941 > allowed size: 1000000)
<user> Screenshot_20200327_092811.png```

**Describe the solution you'd like**
Downsample / compress / resize the image until it is uder 1000000 bytes

**Comment by qaisjp** [comment]
> 1000000 bytes

this is different per guild so we would want to get this number dynamically, probably at time of upload (it can change at any time since it's based on nitro boosts)

**Comment by 42wim** [comment]
According to what I find on google the limit should be 8MB
So strange that it blocks on 1MB?

**Comment by nathanaelhoun** [comment]
Had the same error message with a mattermost → discord bridge.
Fixed by setting the variable [`MediaDownloadSize=8000000`](https://github.com/42wim/matterbridge/wiki/Settings#mediadownloadsize) in the `matterbridge.toml` file.

A downsampling/compressing/resizing of the image would still be very useful for images over 8Mb

**Comment by vpzomtrrfrt** [comment]
I tried changing MediaDownloadSize, but now larger images still don't work and log "net/http: request canceled (Client.Timeout exceeded while awaiting headers)"

**Comment by 42wim** [comment]
resizing is out-of-scope for me. PR's are still accepted though.

**Comment by poVoq** [comment]
I get the same with Matrix -> IRC, which makes no sense at all as it should just share the html link from Matrix regardless of the size.
