### ISSUE TITLE
Bridge failed to connect to Freenode

### ISSUE THREAD

**Issue by elimisteve** [42wim/matterbridge#107]
Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```

running version 0.9.1-dev

### If you're having problems with mattermost please specify mattermost version. 

mattermost almost certainly isn't the issue, but just in case:

```
Version: 3.5.0  (3.5.1)
Database: mysql
```

### Please describe the expected behavior.

Bridge should successfully connect to Freenode

#### Use logs from running ```matterbridge -debug``` if possible.

```
INFO[2017-01-05T16:03:00Z] Starting bridge: irc.freenode                
INFO[2017-01-05T16:03:00Z] Connecting irc.freenode.net:6667              module=irc
FATA[2017-01-05T16:03:20Z] starting gateway failed &errors.errorString{s:"Bridge irc.freenode failed to start: dial tcp: lookup irc.freenode.net on 8.8.4.4:53: read udp 172.17.0.3:45089->8.8.4.4:53: i/o timeout"}
```

### Any steps to reproduce the behavior?

> sudo docker run -ti -v /home/ubuntu/matterbridge.toml:/matterbridge.toml 42wim/matterbridge

#### (be sure to exclude or anonymize private data (tokens/passwords))

```
[irc]
    [irc.freenode]
    Server="irc.freenode.net:6667"
    Nick="swborders_bridge"

[mattermost]
    [mattermost.work]
    useAPI=true
    Server="chat.securitywithoutborders.org"
    Team="securitywithoutborders"
    Login="swborders_bridge"
    Password="..."
    PrefixMessagesWithNick=true

[[gateway]]
name="gateway1"
enable=true
    [[gateway.in]]
    account="irc.freenode"
    channel="#securitywithoutborders"

    [[gateway.out]]
    account="irc.freenode"
    channel="#securitywithoutborders"

    [[gateway.in]]
    account="mattermost.work"
    channel="town-square"
    
    [[gateway.out]]
    account="mattermost.work"
    channel="town-square"
```

**Comment by 42wim** [comment]
Looks like your docker container couldn't do a DNS lookup.
strict firewall?
