### ISSUE TITLE
Media upload not working anymore Slack <=> Whatsapp

### ISSUE THREAD

**Issue by glazzara** [42wim/matterbridge#1074]
**Describe the bug**
I have a link between a whatsapp group and a Slack channel.
In version 1.16.5 media uploaded on Slack are not sent to Whatsapp.
Since version 1.17.1, When I upload a file to Slack, nothing appears in Whatsapp and I got this message in syslog : 
`level=error msg="SendMessage failed: image upload failed: upload responsed with %!d(float64=404)" prefix=gateway`

From Whatsapp, Jpeg images are uploaded to Slack but it does not work for PDF files. 

**To Reproduce**
Upload media files (images or pdf) on a Slack channel which should be synchronized with a Whatsapp group.
Upload a PDF from whatsapp, it is not uploaded to Slack.

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: 1.17.1 (official release)

**Additional context**
`[general]
PreserveThreading=true
ShowUserTyping=true
ShowJoinPart=false
NoSendJoinPart=false
IgnoreNicks="XXXX"
IconURL="https://github.com/identicons/{NICK}.png"

MediaDownloadSize=50000000
MediaDownloadPath="/var/www/matterbridge"
MediaServerDownload="https://__url__"
MediaDownloadBlacklist=[".html$",".htm$", ".js$", ".css$", ".php$"]
verbose=true

[slack]
[slack.mine]
Token="xoxb-XXXXXXXXX"
RemoteNickFormat="{NICK}"
verbose=true

[whatsapp.mine]
Number="+33XXXXXX"
SessionFile="session-XXXXXXX.gob"
RemoteNickFormat="#{NICK} : "
verbose=true

[[gateway]]
enable=true

[[gateway.inout]]
account="whatsapp.mine"
channel="XXXXXXXXXX@g.us"

[[gateway.inout]]
account="slack.mine"
`

**Comment by 42wim** [comment]
Could you test if it still happens with this version: https://bintray.com/beta/#/42wim/nightly/Matterbridge/v1.17.1-9-ga2cd5ac?tab=files 

This has an updated upstream Rhymen/go-whatsapp library

**Comment by glazzara** [comment]
Thanks but I get the same issues.

**Comment by 42wim** [comment]
This is fixed in https://github.com/Rhymen/go-whatsapp/pull/317
Have to wait until it get merged in upstream go-whatsapp before I can get it in here.

**Comment by 42wim** [comment]
@glazzara could you try: https://bintray.com/beta/#/42wim/nightly/Matterbridge/v1.17.1-9-g8f0e6e3?tab=files and let me know if it's ok ? this has the upstream fix.

**Comment by glazzara** [comment]
Yes it works ! Thank you !

**Comment by Piyushhbhutoria** [comment]
I am still facing this issue. i am using the latest code.
