### ISSUE TITLE
Confusing documentation / XMPP MUC and XMPP MUC server don't have to be the same

### ISSUE THREAD

**Issue by Mikaela** [42wim/matterbridge#1075]
**Describe the bug**

The documentation tells me to have `Muc="conference.blesmrt.net"` in the `[xmpp.myaccount]` block instead of asking it in the`[gateway]`s as `channel=` or `mucserver=`.

In reality by having an account on blesmrt.net I can join [any other XMPP MUC](https://search.jabber.network/rooms/1) and I expect Matterbridge to be capable of it too.

**To Reproduce**

Read  the following:

* https://github.com/42wim/matterbridge/wiki/Section-XMPP-%28basic%29
* https://github.com/42wim/matterbridge/blob/v1.17.1/matterbridge.toml.sample#L180-L203

**Expected behavior**

Clearly get the instructions how to connect a matterbridge using a blesmrt.net account to a conference.example.net MUC like any other MUC capable XMPP client can do.

**Screenshots/debug logs**

N/A

**Environment (please complete the following information):**
 - OS: N/A but Debian 9
 - Matterbridge version: N/A but 1.17.1 148f7d2a

**Additional context**

For now this is a hypothetical question for me.

**Comment by poVoq** [comment]
I disagree, this works as it should.

You are specifying the server to connect to (can be multiple) and you are **also** specifying the XMPP bot account to do it with. They can be different and I believe multiple bot accounts for different servers are possible.

Changing this would also make if more confusing compared to configuring other type of bridges.

**Comment by Mikaela** [comment]
I don't think I understand your comment, how do I use a single bot account `mikaela.matterbridge@blesmrt.net` to join multiple MUCs on different servers such as `conference.blesmrt.net`, `chat.disroot.org` and `rooms.dismail.de`?

**Comment by poVoq** [comment]
Like with other bridges:
```
[xmpp]
[xmpp.myxmpp1]
Server="jabber.example.com:5222"
#Jid your userid
Jid="user@example.com"
Password="yourpass"
Muc="conference.jabber1.example.com"
Nick="xmppbot"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
[xmpp.myxmpp2]
Server="jabber.example.com:5222"
#Jid your userid
Jid="user@example.com"
Password="yourpass"
Muc="conference.jabber2.example.com"
Nick="xmppbot"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
```

**Comment by Mikaela** [comment]
So to have multiple XMPP MUC servers, one has to duplicate the Jids and Passwords?

Wouldn't it be easier to merge `Channel` and `Muc` like is done in XMPP clients also?

**Comment by poVoq** [comment]
There are of course many other ways to do it theoretically, but this one is consistent with the overall configuration system in Matterbridge. Changing that would just make it confusing to new users like you and I don't see what one would win from it? Save to lines of digital text? What for?

**Comment by Mikaela** [comment]
While I was a new Matterbridge user, I was more confused of the conference server requiring specification separately and having to search config file examples on this issue tracker to see that it's actually configured that weird way. Active XMPP user I have been a couple of years now.

I guess being able to specify the same account multiple times is good enough, while I have to wonder how many times the same host can connect to an XMPP server and does it really make sense that changing a password has to be done with "find and replace all" style.
