### ISSUE TITLE
XMPP doc update: use different account

### ISSUE THREAD

**Issue by weeman1337** [42wim/matterbridge#1076]
I found out that bridging XMPP doesn't work if you use your regular account.

The docs should be updated like the Matrix one:
https://github.com/42wim/matterbridge/wiki/Section-Matrix-%28basic%29

Especially 

> Create a dedicated user first. It will not relay messages from yourself if you use your account

**Comment by weeman1337** [comment]
done , thanks

https://github.com/42wim/matterbridge/wiki/Section-XMPP-(basic)/_compare/231007596282aa4a03313ebc4bce77c773937716...75707006bf23fd6d94a37a5b2fa66639355f2c1e

**Comment by qaisjp** [comment]
thank you!

**Comment by 42wim** [comment]
thanks!
