### ISSUE TITLE
Feature - Rocket Chat websocket support

### ISSUE THREAD

**Issue by ibigpapa** [42wim/matterbridge#108]
Please answer the following questions. 

### Which version of matter bridge are you using?
run ```matter bridge -version```
9.0

### If you're having problems with matter most please specify matter most version. 
n/a

### Please describe the expected behavior.
Feature request - instead of using web hooks for rocket i'd like to see web sockets.   This allows us to bridge matter most and rocket when we have matter most not externally accessible but rocket is.

They've already got a Huebot for rocket that uses web sockets so integration shouldn't be too hard to wire the 2 up and wrap it with some config logic.
MIT licence as well.
https://github.com/RocketChat/hubot-rocketchat

**Comment by 42wim** [comment]
The problem is that rocketchat uses meteor for this and there isn't a meteor (https://www.meteor.com/) go library,  (and I don't have the motivation to write one myself).

I'm open for someone to implement this, but this won't be me (for now)
