### ISSUE TITLE
Add a space between caption text and the colon from telegram messages on the irc side

### ISSUE THREAD

**Issue by derram** [42wim/matterbridge#1089]
If a URL is used as a caption on telegram, the colon breaks the URL on irc side. 

![Selection_400](https://user-images.githubusercontent.com/5730335/79282121-e41b8800-7ea3-11ea-9662-ba0d5241a064.png)

**Comment by 42wim** [comment]
Please paste debug logs reproducing this issue.  
I don't use telegram and need the debug logs.

**Comment by derram** [comment]
[teletoircdebug.txt](https://github.com/42wim/matterbridge/files/4499075/teletoircdebug.txt)

Pretty sure I included the relevant bits, hopefully I didn't exclude or censor something important.

**Comment by 42wim** [comment]
Thanks, fixed in master now.

**Comment by derram** [comment]
Thanks again!
