### ISSUE TITLE
Failed reconnect to Mattermost

### ISSUE THREAD

**Issue by jurgenhaas** [42wim/matterbridge#109]
Not sure if this should be addressed but I'm still reporting it so that it can be discussed. I've had similar issues before and you've fixed them all, this one is slightly different:

Last Friday I did a distro update on he host where Mattermost is installed and that took a couple of hours due to an issue with a database. Eventually all got sorted and Mattermost ran properly again. However, Matterbridge did not try to reconnect after a while anymore. From the attached log it seems that it gave up after 10 minutes.

[matterbridge.log.txt](https://github.com/42wim/matterbridge/files/692915/matterbridge.log.txt)

That may be reasonable, so I'm not sure if I should ask for a longer or even infinite period. What do you guys think?

**Comment by 42wim** [comment]
Is this the complete log ?  I only see 2 reconnects

**Comment by jurgenhaas** [comment]
That's been the tail of the log, after that no logs available anymore.

**Comment by 42wim** [comment]
Ok, that's strange. It should try to reconnect indefinitely but with an increasing reconnect time (max 5 minutes). I also can't reproduce it.

**Comment by 42wim** [comment]
Could you try again with latest version and reopen this issue if it still happens ?
