### ISSUE TITLE
XMPP Avatar Spoofing Broken 

### ISSUE THREAD

**Issue by Polynomdivision** [42wim/matterbridge#1097]
With the new version of matterbridge/go-xmpp, it seems that I broke avatars. Avatar data get's requested but not returned.

I am already working on fixing it and should have it ready by tomorrow.

**EDIT**: Got this working earlier than expected. [This PR](https://github.com/matterbridge/go-xmpp/pull/7) is my fix. This is quite embarassing for me :sweat_smile: ...

**Comment by 42wim** [comment]
No worries :)
Will merge the fix in master soon.
