### ISSUE TITLE
matterbridge doesn't handle disconnection well

### ISSUE THREAD

**Issue by RangerRick** [42wim/matterbridge#11]
When freenode disconnects, matterbridge doesn't reconnect and it leaves the bot in a state where it's still running, but not actually bridging anymore.  If it at least exited cleanly when it got disconnected, my systemd script would restart it, but instead it gets stuck.

**Comment by 42wim** [comment]
Are you using the binary or build from master ?

**Comment by RangerRick** [comment]
Hm, you know, it's a build from master and it's probably a bit behind, I'll reopen this if I can reproduce after updating.
