### ISSUE TITLE
MSTeams integration panic's in long running service

### ISSUE THREAD

**Issue by avrono** [42wim/matterbridge#1104]
**Describe the bug**
The MS Teams integration panics, if leaving the server to run for a number of hours
There are 2 places in the code base, which do not correctly handle errors

**To Reproduce**
Leave the server running for an extended period of time

**Expected behavior**
Server should never panic !

**Screenshots/debug logs**
panic: 400 Bad Request: {"error":{"code":"AuthenticationError","message":"Error authenticating with resource.","innerError":{"date":"2020-04-20T10:14:42","request-id":"a1260b43-0acc-4ca5-9a9b-3e7af7cf0644"}}}

goroutine 12 [running]:
github.com/42wim/matterbridge/bridge/msteams.(*Bmsteams).poll(0xc000321230, 0xc0000ab080, 0x30)
        /go/src/github.com/42wim/matterbridge/bridge/msteams/msteams.go:141 +0xbe7
created by github.com/42wim/matterbridge/bridge/msteams.(*Bmsteams).JoinChannel
        /go/src/github.com/42wim/matterbridge/bridge/msteams/msteams.go:74 +0x53

**Environment (please complete the following information):**
 - Ubuntu 18.04
 - Matterbridge version: 1.17.2 d97b077e

**Additional context**
Seems like might be this line https://github.com/42wim/matterbridge/blob/308a1100006e6e5b3d6cb5dcea90ac7a9d95b594/bridge/msteams/msteams.go#L141

**Comment by 42wim** [comment]
Yes, seems like I didn't remove those :)
Thanks for reporting.

I've made a PR that retries when the polling fails instead of panicing. You can find it here https://bintray.com/beta/#/42wim/nightly/Matterbridge/v1.17.3-2-g098b40e?tab=files

Not sure yet if it needs reauthentication/reconnecting too as you're getting a 400.
The session should still be valid.

**Comment by 42wim** [comment]
Tested and fixed in master.

**Comment by avrono** [comment]
Thanks for the prompt fix !
