### ISSUE TITLE
PGP signature

### ISSUE THREAD

**Issue by wget** [42wim/matterbridge#111]
Could you please sign your tags and releases using GPG?

This is now a requirement for Arch Linux: https://www.archlinux.org/todo/use-gpg-signatures-and-https-sources/

Thanks in advance!

**Comment by jleclanche** [comment]
@42wim let me know if you need help figuring this out.

**Comment by 42wim** [comment]
The latest release has been signed.
New ones will too,  you can add it to archlinux now ;-)

**Comment by Mikaela** [comment]
@42wim Could you upload your public key at https://keys.openpgp.org/upload and confirm your email address there?

Otherwise people using it receive your key without UIDs and cannot use it to verify your signatures and it's very popular keyserver since the PGP signature flooding attacks begun.

**Comment by 42wim** [comment]
@Mikaela 
My public key can be found here https://keybase.io/42wim
https://keybase.io/42wim/pgp_keys.asc?fingerprint=cc7d978417c1aea1e4cdd7240e41ab4bf4c610b4

Isn't that good enough?

**Comment by Mikaela** [comment]
That would require knowing that Keybase exists and finding your key there (or tracking you and being logged in to Keybase on the same host the user is running Matterbridge on and running `keybase pgp pull`), while I think what generally happens is:

1. user downloads the `checksums.asc` 
2. user `gpg --verify checksums.asc`
3. gpg throws:

```
gpg: assuming signed data in 'checksums.txt'
gpg: Signature made Mon Dec 16 00:57:01 2019 EET
gpg:                using RSA key 0E41AB4BF4C610B4
gpg: Can't check signature: No public key
```

4. user attempts to `gpg --recv-keys 0E41AB4BF4C610B4`  where gpg replies

```
gpg: key 0E41AB4BF4C610B4: new key but contains no user ID - skipped
gpg: Total number processed: 1
gpg:           w/o user IDs: 1
``` 

resulting to step 3.

I am on Debian 10, gpg 2.2.12 and did this with empty config file.

According to their [3 months after launch news item](https://keys.openpgp.org/about/news#2019-09-12-three-months-later) this is also the case with at least *GPGTools, Enigmail, OpenKeychain, GPGSync, Debian, NixOS, and others.*

**Comment by 42wim** [comment]
@Mikaela thanks for explaining. 👍 
I just added the key.

**Comment by Mikaela** [comment]
Thanks :purple_heart:
