### ISSUE TITLE
Try reconnecting with IgnoreFailureOnStart=true (with exponential backoff?)

### ISSUE THREAD

**Issue by Mikaela** [42wim/matterbridge#1113]
**Describe the bug**

When the bot starts with `IgnoreFailureOnStart=true` and fails to connect somewhere, it won't attempt reconnecting there at all and the admin will have to notice or get notified about some protocol being down and restart the bot in hopes that it will connect this time.

**To Reproduce**

Encounter a connection problem with `IgnoreFailureOnStart=true`.

**Expected behavior**

I wish matterbridge tried reconnecting again after maybe a few seconds and if it failed connecting, it would exponentially increase the time to wait before reconnecting. I don't know what would be a good maximum time.

**Screenshots/debug logs**

I am not sure it's applicable.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Matterbridge version: 1.17.3 4f406b2c (I am aware of it not being the latest version, but I understood from the support chat that that doesn't matter in this case)

**Additional context**

I don't think config file is applicable.

**Comment by Mikaela** [comment]
GItHub suggests https://github.com/42wim/matterbridge/issues/267 as a similar issue and this could be a duplicate of it, but my problem inspiring me to open this was with Mattermost timing out rather than IRC and I can see this issue happening with any protocol.

**Comment by 42wim** [comment]
No sorry, I'm not in favor of implementing this.

There are two options now: continue on failure or fail on failure.

If you want to do retries on failure, you can use systemd for that which will retry (also no exponential backoff: https://github.com/systemd/systemd/issues/6129) until it succeeds.

You can also make an own script that does the exponential backoff.

That said, if someone makes a PR, it's still open for discussion.
