### ISSUE TITLE
reply only works from MM to MSTeams and not from MSTeams to MM

### ISSUE THREAD

**Issue by avrono** [42wim/matterbridge#1114]
**Describe the bug**
Reply to a thread does not work from MSTeams, I am not sure if this is due to a bug or a limitation in the MSTeams API. Unfortuantly there are no logs to trace as the message is simply not picked up.

**To Reproduce**
Connect MSTeams to Mattermost and write message from MM to MSTeams and hit reply.

**Expected behavior**
Reply is displayed in MM

**Screenshots/debug logs**
No useful logs to show

**Environment (please complete the following information):**
 - Ubuntu 18.04
 - 1.17.3-2

**Comment by 42wim** [comment]
No, that's due to a bug in the microsoft API.
See https://github.com/microsoftgraph/microsoft-graph-docs/issues/6693

It's very hard to actually file bugs with microsoft.

**Comment by avrono** [comment]
Thanks again !

**Comment by alkanna** [comment]
I am also experiencing this issue. It's a slack/teams setup. If I write anything in slack it is properly forwarded to the teams channel. If I however type anything whether it's in a thread or not in teams, I don't see anything in slack.

It works one way bot not the other way around.

**Comment by alkanna** [comment]
@avrono Did you ever fix this?

**Comment by malewis5** [comment]
Hi @avrono was there ever a fix for this?

**Comment by DenisBessa** [comment]
Would appreciate if someone could help to solve this.
