### ISSUE TITLE
Support backreferences in ReplaceMessages

### ISSUE THREAD

**Issue by akorn** [42wim/matterbridge#1115]
I'm bridging IRC and RocketChat.

It would be nice to be able to do something like

`ReplaceMessages=[ [ "^([^[:space:]]+):", "@\1" ] ]`

which would cause IRC-style "nick: yo" and "all: hiya" style messages to be converted to RocketChat `@mentions`.

The reverse would also be useful but is less important as IRC clients tend to have more flexible highlighting rules.

Unfortunately, RE2 doesn't do backreferences.

Maybe you could use libpcre instead?

**Describe alternatives you've considered**

Alternative: enumerate all nicks in individual replacement tuples, lol.

**Comment by 42wim** [comment]
I think you could get this working with tengo using `re_find` and `re_replace`
https://github.com/d5/tengo/blob/master/docs/stdlib-text.md

**Comment by akorn** [comment]
I was under the impression Tengo would use the same regex library and would thus be similarly limited.

If not, then indeed Tengo might be a viable workaround (I may even try it), but it would certainly be more convenient to just have backrefs in `ReplaceMessages`. :)

**Comment by 42wim** [comment]
It uses the same library but you can do multistage replacement, first matching and then replacing.

**Comment by 42wim** [comment]
Going to close this, if you got this working with tengo please make a PR with your script so other people can use it too. Thanks!
