### ISSUE TITLE
mattermost: enable gitlab login

### ISSUE THREAD

**Issue by L0ric0** [42wim/matterbridge#1116]
**Is your feature request related to a problem? Please describe.**
The Mattermost servres of some universitys only allow the login to the mattermost over gitlab. To be able to use the matterbridge without webhooks it would be nice to be able to login to the mattermost-server with gitlab

**Describe the solution you'd like**
some config field

**Describe alternatives you've considered**
using webhooks, but this is tedious as one has to add a webhook per chanel

**Comment by 42wim** [comment]
You could use personal tokens: https://docs.mattermost.com/developer/personal-access-tokens.html

**Comment by L0ric0** [comment]
for which i need to be a system admin which i am not

**Comment by 42wim** [comment]
You don't need to be an admin to use personal tokens.
You do need to be an admin to enable it, if that's the case, contact your admin to enable it.
