### ISSUE TITLE
Problem with accents from IRC to Matrix and Discord

### ISSUE THREAD

**Issue by P0ME** [42wim/matterbridge#1118]
Accents are kind of buggy since the last update.

Example, when you type "ça dépend" in IRC you will receive "Ã§a dÃ©pend" in Matrix and Discord.
Sometimes accents will work, sometimes it won't.

It does it from Rizon and I tried on the official bridge with freenode and I observed the same issue.

**Comment by P0ME** [comment]
Fixed by setting charset https://github.com/42wim/matterbridge/wiki/Settings#charset
to Charset="utf-8"

**Comment by Mikaela** [comment]
Also \`:smile_cat:\` from IRC without specifying `Charset="utf8"` becomes `№И`.

What would be the best place to document this? Or could matterbridge just stop attempting whatever it's doing and instead default to `Charset="utf8"` unless otherwise specified?

**Comment by PeGaSuS-Coder** [comment]
I believe that UTF-8 should be default. it's probably the standard in every IRC clients and IRCd servers (or at least I assume so).
