### ISSUE TITLE
Whatsapp-Bridge cannot join channel; empty b.conn.Store.Contacts?

### ISSUE THREAD

**Issue by steBracKa** [42wim/matterbridge#1122]
The problem first occured with stabel binary v1.17.4 on CentOS, downloading and building 
2d8f749e361eeca5da698138a42e182fdfea4713
didn't change anything.

Most time I start matterbridge it ends up with
`[0001]  INFO router:       Starting bridge: whatsapp.fachschaft 
[0001] DEBUG whatsapp:     Connecting to WhatsApp..
[0001] DEBUG whatsapp:     WhatsApp connection successful
[0001] DEBUG whatsapp:     Restoring WhatsApp session..
[0001] DEBUG whatsapp:     Session restored successfully!
[0003]  INFO whatsapp:     whatsapp.fachschaft: joining 4916092123064-1588093217@g.us (ID: 4916092123064-1588093217@g.uswhatsapp.fachschaft)
map[]
[0003] FATAL main:         Starting gateway failed: Bridge whatsapp.fachschaft failed to join channel: account doesn't belong to group with jid 4916092123064-1588093217@g.us`

I'm sure, in principle the configuration is ok, as sometimes it just works.

To find the problem I added into /bridge/whatsapp/whatsapp.go around as line 200:
`return fmt.Errorf("%+v\n", b.conn.Store.Contacts)`

This results in
`[0020] FATAL main:         Starting gateway failed: Bridge whatsapp.fachschaft failed to join channel: map[]`

Is it that under certain circumstances b.conn.Store.Contacts is empty?
Is there anyone who can give a hint for further debugging?

**Comment by 42wim** [comment]
Is this still an issue on latest matterbridge?

**Comment by steBracKa** [comment]
Yes, unfortunately it's still an issue.

In https://github.com/42wim/matterbridge/blob/master/bridge/whatsapp/whatsapp.go

If I trigger this code
`func (b *Bwhatsapp) JoinChannel(channel config.ChannelInfo) error {
	byJid := isGroupJid(channel.Name)

...
		case 0:
			// didn't match any group - print out possibilites
			// TODO sort
			// copy b;
			//sort.Slice(people, func(i, j int) bool {
			//	return people[i].Age > people[j].Age
			//})
			for id, contact := range b.conn.Store.Contacts {
				if isGroupJid(id) {
					b.Log.Infof("%s %s", contact.Jid, contact.Name)
				}
			}`

No contact is shown at all.

**Comment by steBracKa** [comment]
I found the problem, see [here](https://github.com/Rhymen/go-whatsapp/issues/137#issuecomment-480316013).

**Comment by 42wim** [comment]
@steBracKa is it fixed for when you add a delay?
We do an explicit `conn.Contacts()` on connect.

**Comment by steBracKa** [comment]
I fixed the problem by waiting until b.conn.Store.Contacts is filled:
In https://github.com/42wim/matterbridge/blob/master/bridge/whatsapp/whatsapp.go:

```
func (b *Bwhatsapp) JoinChannel(channel config.ChannelInfo) error {

	byJid := isGroupJid(channel.Name)
#---------additional code------------#
	for len(b.conn.Store.Contacts) == 0 {
		// fmt.Println("Contacts list not yet ready, waiting a second")
		b.conn.Contacts()
		<-time.After(1 * time.Second)
	}
#---------end of additional code------#
	// verify if we are member of the given group
	if byJid {
		// channel.Name specifies static group jID, not the name
		if _, exists := b.conn.Store.Contacts[channel.Name]; !exists {
			return fmt.Errorf("account doesn't belong to group with jid %s", channel.Name)
		}
	} else {
```


I had to add the same in `func (b *Bwhatsapp) Connect()`:
```
        // login to a new session
	if b.session == nil {
		err = b.Login()
		if err != nil {
			return err
		}
	}
	b.startedAt = uint64(time.Now().Unix())

	_, err = b.conn.Contacts()
	if err != nil {
		return fmt.Errorf("error on update of contacts: %v", err)
	}
#---------additional code------------#
	for len(b.conn.Store.Contacts) == 0 {
		// fmt.Println("Contacts list not yet ready, waiting a second")
		b.conn.Contacts()
		<-time.After(1 * time.Second)
	}
#---------end of additional code------#
	for id, contact := range b.conn.Store.Contacts {
		if !isGroupJid(id) && id != "status@broadcast" {
			// it is user
			b.users[id] = contact
		}
	}
```

This fixes the error reliably (tested on different machines with different Whatsapp accounts).
Uncommenting the Println-statements shows that the time / number of approaches needed to get a filled b.conn.Store.Contacts changes a lot even in the same setup.

**Comment by ardyln** [comment]
I have tested @steBracKa's fix (with a 10 seconds delay instead of 1 just to be sure), can confirm that it fixes the error
I have a guess that the chances of matterbridge giving a fatal error after failing to join groups increases with each new whatsapp group, because I only started to have this problem (taking 15-20 tries to successfully boot up) after around 35-40 groups

**Comment by 42wim** [comment]
Thanks for testing and confirming, applied to master now
