### ISSUE TITLE
relay every channel of mattermost

### ISSUE THREAD

**Issue by AdronTech** [42wim/matterbridge#1126]
**Is your feature request related to a problem? Please describe.**
I would like to relay every message of every channel I am joined on mattermost to my telegram chat

**Describe the solution you'd like**
Define a gateway.out where it is possible to say that I would like to subscribe to every channel
maybe  "@all"

**Describe alternatives you've considered**
Yeah, i could add a gateway for each channel, but then I would have to update every time I get added to a new channel.

**Additional context**

**Comment by aconitumnapellus** [comment]
Please look into matterircd, from the same developer. 
Its a bridge between your mattermost account and IRC, sadly not telegram.

**Comment by 42wim** [comment]
Not going to implement this.
