### ISSUE TITLE
IRC Emotes do not appear on Discord

### ISSUE THREAD

**Issue by Maeyanie** [42wim/matterbridge#1132]
**Is your feature request related to a problem? Please describe.**
Currently, IRC emotes (/me does whatever.) seem to not be bridged. Presumably because they use CTCP ACTION rather than PRIVMSG, which Matterbridge doesn't yet support.

**Describe the solution you'd like**
It would be nice if they were bridged into whatever passes for an emote on other services, or a message where that isn't supported.

**Describe alternatives you've considered**
Other than changing from Matterbridge to something different, or trying to teach everyone not to use them, I don't see any alternatives.

**Additional context**
I'm not actually sure whether this should be considered a bug or feature request, so feel free to relabel it if I guessed incorrectly.

**Comment by qaisjp** [comment]
Just tested - they are bridged to Slack, but not Discord. I will try and fix that for Discord now. What are you bridging to?

**Comment by Maeyanie** [comment]
The one I noticed it was Discord. Thanks for the fix.

**Comment by Mikaela** [comment]
This also affects XMPP

**Comment by Mikaela** [comment]
And now I notice that it also affects Telegram
