### ISSUE TITLE
Discord embed > Telegram/IRC: markdown not displayed properly

### ISSUE THREAD

**Issue by burner1024** [42wim/matterbridge#1138]
**Describe the bug**
Discord embed content is passed as raw to Telegram and IRC:

![Captura de pantalla de 2020-05-15 16-44-40](https://user-images.githubusercontent.com/1279852/82036701-6a0d3780-96cb-11ea-9cae-779956f1f4ff.png)
![Captura de pantalla de 2020-05-15 16-45-24](https://user-images.githubusercontent.com/1279852/82036777-81e4bb80-96cb-11ea-9fee-425a4a5af197.png)
![Captura de pantalla de 2020-05-15 16-47-14](https://user-images.githubusercontent.com/1279852/82037292-1f3fef80-96cc-11ea-8c8e-c7e1220eb7fc.png)

**To Reproduce**
Set up a bridge between Telegram, Discord, IRC. For Telegram, use `MessageFormat="MarkdownV2"`, for Discord `ShowEmbeds=true`.

**Expected behavior**
- Markdown parsed properly inside Telegram.
- For IRC, most clients probably won't display markdown? Not sure what's possible, but very likely it can be improved to [_some extent_](https://modern.ircdocs.horse/formatting.html).

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - `version: 1.17.4 6c442e23`

**Comment by 42wim** [comment]
A `StripMarkdown` option has been added in master for irc, so you can strip markdown for irc.
Wrt telegram, better to open an issue with telegram to support full markdown.

**Comment by qaisjp** [comment]
> For IRC, most clients probably won't display markdown?

Btw, irccloud does convert these four lines:

````
<qaisjp> Example:
<qaisjp> ```
<qaisjp> something()
<qaisjp> ```
````

To look like this

![image](https://user-images.githubusercontent.com/923242/82741108-d8df3600-9d46-11ea-878e-58dfa03de730.png)

**Comment by burner1024** [comment]
> A `StripMarkdown` option has been added in master for irc, so you can strip markdown for irc.

OK, what's it going to do? Leave plain text only?

> Wrt telegram, better to open an issue with telegram to support full markdown.

It supports links, code, formatting, etc. What else is needed?

> Btw, irccloud does convert these four lines:

Putting aside other clients, I guess that's a regular message, not an embed?

**Comment by burner1024** [comment]
@42wim @qaisjp could you respond?
