### ISSUE TITLE
Tag latest stable version on Docker HUB

### ISSUE THREAD

**Issue by SuperSandro2000** [42wim/matterbridge#1139]
**Is your feature request related to a problem? Please describe.**
I can't use the ``latest`` tag as I do not want dev builds running in production and updating the tag for every update is annoying.

**Describe the solution you'd like**
Tags like ``stable``, ``1`` or ``1.17`` could be added to catch smaller updates or track stable when you pull your docker images without changing the tag with every update.

**Describe alternatives you've considered**
Writing a script which fetches the latest release and puts that into my docker-compose.yml file.

**Additional context**

**Comment by 42wim** [comment]
Thanks, good idea, next release will have `stable` and `1` tag, I don't see an option to tag current release as stable in dockerhub.

**Comment by SuperSandro2000** [comment]
You can pull the image, add an additional tag like ``docker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]`` and push the new tag to the repository.
