### ISSUE TITLE
Add support for EditSuffix in Matrix gateway

### ISSUE THREAD

**Issue by SuperSandro2000** [42wim/matterbridge#1140]
**Is your feature request related to a problem? Please describe.**
I couldn't get the EditSuffix setting to work with a matrix xmpp bridge and I think it is not implemented for matrix.

**Describe the solution you'd like**
That support for EditSuffix is added to matrix gateway.

**Describe alternatives you've considered**

**Additional context**

**Comment by 42wim** [comment]
Not necessary anymore now we have native editing in #1286
