### ISSUE TITLE
RocketChat Websocket Bad Status

### ISSUE THREAD

**Issue by sissieadmin** [42wim/matterbridge#1142]
**Describe the bug**
The RocketChat component to MatterBridge fails on its websocket connection when using personal tokens or user email and password.

**To Reproduce**
Run Ubuntu 18.04 LTS with Matterbridge and RocketChat Installed.

Construct bridge with following settings for the account:

        [rocketchat.rocketchat]
        Server="https://rocketchat.domain.com:443"
        RemoteNickFormat="[{PROTOCOL}] <{NICK}>"
        Login="<random-userID-string>"
        Token="<random-token-string>"

The token and user ID was created within a dedicated user for matterbridge's connection to Rocket Chat

**Expected behavior**
MatterBridge will successfully connect to that dedicated account be able to relay messages normally.

**Screenshots/debug logs**
[0000]  INFO router:       Starting bridge: rocketchat.myrocketchat 
[0000]  INFO rocketchat:   Connecting using login/password (sending and receiving)
[0000] DEBUG rocketchat:   handling apiLogin()
2020/05/20 19:58:50 Dial error websocket.Dial wss://rocketchat.domain.com:443/websocket: bad status
[0000] FATAL main:         Starting gateway failed: Bridge rocketchat.rocketchat failed to start: websocket.Dial wss://rocketchat.domain.com:443/websocket: bad status

**Environment (please complete the following information):**
 - OS: [e.g. linux]
 - Matterbridge version: 1.17.4 6c442e23

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))

        [discord.discordtest]
        Server="discordserver"
        Token="<random-token-string"
        RemoteNickFormat="[{PROTOCOL}] <{NICK}>"

        [rocketchat.myrocketchat]
        Server="https://rocketchat.domain.com:443"
        RemoteNickFormat="[{PROTOCOL}] <{NICK}>"
        Login="<random-userID-string>"
        Token="<random-token-string>"

        [mattermost.mattermosttest]
        Server="mattermost.domain.com:443"
        Team="mattermost-team"
        Login="<username>"
        Token="<random-token-string>"
        PrefixMessagesWithNick=true
        RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[samechannelgateway]]
name="SameChannelGateway"
enable=true

accounts=["discord.discord","rocketchat.rocketchat","mattermost.mattermost"]
channels=["general","general2"]

**Comment by 42wim** [comment]
If you do on the same host you're running matterbridge on a `telnet rocketchat.domain.com 443` does it connect ?

**Comment by powerpaul17** [comment]
Hello, I experience the same problem, telnet works fine.
