### ISSUE TITLE
Support Salesforce Chatter

### ISSUE THREAD

**Issue by franklesniak** [42wim/matterbridge#1153]
It'd be great if Matterbridge supported message cross-posting with Salesforce Chatter to better enable remote sales people to collaborate with others in the business.

For example, if my remote sales people are using the Salesforce mobile app on their iPad and collaborating on an opportunity or account, it'd be cool to have the ability to cross-post with a related MS Teams _team_.

**Comment by 42wim** [comment]
As salesforce now bought slack I don't think this will be needed anymore :)
