### ISSUE TITLE
Update to new SteamKit Version

### ISSUE THREAD

**Issue by zuberlan** [42wim/matterbridge#1154]
It looks like support for the new Steam does not yet work for matterbridge.

The library that matterbridge uses (https://github.com/Philipp15b/go-steam) needs to be updated with the current SteamKit version.

Updating go-steam to a new SteamKit version:

Go source code is generated with code in the generator directory. Look at generator/README.md for more information on how to use the generator.

Then, after generating new Go source files, update go-steam as necessary.

The most recent SteamKit version is: https://github.com/SteamRE/SteamKit/releases/tag/2.3.0-beta.2

This was released only 11 days ago!

**Comment by 42wim** [comment]
I can't update as upstream go-steam is broken currently

```
./social.go:159:38: undefined: EMsg_ClientChatGetFriendMessageHistoryForOfflineMessages
./social.go:159:97: undefined: CMsgClientChatGetFriendMessageHistoryForOfflineMessages
./social.go:311:18: cannot use avatar (type []byte) as type string in argument to protocol.ValidAvatar
./social.go:323:19: cannot use avatar (type []byte) as type string in argument to protocol.ValidAvatar
./social.go:324:25: cannot use avatar (type []byte) as type string in argument to s.Friends.SetAvatar
./social.go:342:19: cannot use avatar (type []byte) as type string in argument to protocol.ValidAvatar
./social.go:343:24: cannot use avatar (type []byte) as type string in argument to s.Groups.SetAvatar
./social.go:415:47: cannot use info.GetShaAvatar() (type []byte) as type string in argument to s.Groups.SetAvatar
./social.go:601:14: undefined: CMsgClientChatGetFriendMessageHistoryResponse
```

**Comment by 42wim** [comment]
Feel free to report this issue on go-steam. Going to close this for now.
