### ISSUE TITLE
Gateway failed bridge mattermost

### ISSUE THREAD

**Issue by Pablossi** [42wim/matterbridge#1156]
**Describe the bug**
failed to start bridge mattermost

**To Reproduce**

**Expected behavior**
Bridge between channel 1 and channel 2.

**Screenshots/debug logs**

[0000]  INFO main:         [setupLogger:matterbridge.go:97] Enabling debug logging.
[0000]  INFO main:         [main:matterbridge.go:46] Running version 1.17.6-dev
[0000]  INFO main:         [main:matterbridge.go:48] WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
[0000]  INFO router:       [Start:gateway/router.go:66] Parsing gateway gateway
[0000]  INFO router:       [Start:gateway/router.go:75] Starting bridge: mattermost.io
[0000]  INFO mattermost:   [Connect:bridge/mattermost/mattermost.go:62] Connecting using login/password (sending and receiving)
[0000]  INFO mattermost:   [apiLogin:bridge/mattermost/helpers.go:75] Connecting matterbridge (team: io) on mattermost.io.org
[0004] FATAL main:         [main:matterbridge.go:59] Starting gateway failed: Bridge mattermost.io failed to start: "http://mattermost.io.org/api/v4/users/logout: model.client.connecting.app_error, Post \"http://mattermost.io.org/api/v4/users/logout\": EOF"

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Matterbridge version: 1.17.6-dev
 
**Additional context**

[mattermost]
[mattermost.io]
Server="mattermost.io.org"

Team="io"

Login= "matterbridge_user"
Password="matterBridge_password"

NoTLS=true

RemoteNickFormat="<{NICK}> "
SkipVersionCheck=true

[[gateway]]
name="gateway"
enable=true

[[gateway.inout]]
account="mattermost.io"
channel="matterbridge1"

[[gateway.inout]]
account="mattermost.io"
channel="matterbridge2"

**Comment by 42wim** [comment]
Are you sure the matterbridge server isn't running on https ? It's very rare these days to have this running on http

**Comment by Pablossi** [comment]
Correct is like "http", but even if I change it to "https" I can't get it to work.

**Comment by 42wim** [comment]
Try `telnet mattermost.io.org 80` and `telnet mattermost.io.org 443`

Paste results

**Comment by Pablossi** [comment]
Telnet no escucha en ninguno puerto, es necesario que lo habilite?

**Comment by Pablossi** [comment]
telnet only works on port 23


netstat -nat | grep LISTEN

tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:8065          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 :::23                   :::*                    LISTEN

telnet mattermost.ioorg 23
Trying XXX.XXX.XXX.XXX...
Connected to mattermost.io.org.
Escape character is '^]'.

User Access Verification

telnet mattermost.io.org 80
Trying XXX.XXX.XXX.XXX...
Connected to mattermost.io.org.
Escape character is '^]'.
Connection closed by foreign host.

telnet mattermost.io.org 443
Trying XXX.XXX.XXX.XXX...
Connected to mattermost.io.org.
Escape character is '^]'.

**Comment by 42wim** [comment]
Are you running matterbridge on the same host as mattermost?

**Comment by Pablossi** [comment]
yes, both are running on the same server

**Comment by 42wim** [comment]
Set 
```
Server="127.0.0.1:8065"
NoTLS=true
```

**Comment by Pablossi** [comment]
Quizás quisiste decir: PERFECTO, con eso conecta correctamente. Voy a continuar con mis pruebas. Muchas gracias! Aprovecho para hacer una pregunta extra. Como hago para que quede corriendo cuando salgo Ctrl+C.
187/5000
PERFECT, with that connects correctly. I will continue my tests. Thank you!

I take this opportunity to ask an extra question. How do I make it run when I exit Ctrl + C.

**Comment by Pablossi** [comment]
PERFECT, with that connects correctly. I will continue my tests. Thank you!
