### ISSUE TITLE
Stream API loses messages from (at least) irc

### ISSUE THREAD

**Issue by Corion** [42wim/matterbridge#1158]
**Describe the bug**
The Matterbridge API ( `/api/stream` ) loses messages from at least irc.

**To Reproduce**

Launch matterbridge with the attached config

[matterbridge.toml.txt](https://github.com/42wim/matterbridge/files/4757465/matterbridge.toml.txt)

Launch curl:

    curl -i http://localhost:4242/api/stream

Join the irc channel with another irc client and type some messages.

**Expected behavior**
All messages typed into the irc channel also appear on the Matterbridge API.

**Screenshots/debug logs**

See the log. After some tries, the log entry 374 is received (text "2", text "3", text "4") but never seen by the curl client on the other side.

**Environment (please complete the following information):**
 - OS: Linux (Debian 10 "Buster")
 - Matterbridge version: `version: 1.17.5 8eb5e3cb`

**Additional context**
[matterbridge-irc-api-20200610-losing-messages.txt](https://github.com/42wim/matterbridge/files/4757439/matterbridge-irc-api-20200610-losing-messages.txt)

**Comment by 42wim** [comment]
I can not reproduce this, is this something you can always reproduce?

**Comment by 42wim** [comment]
Closed because of inactivity
