### ISSUE TITLE
IRC - show message works - but not sending from user

### ISSUE THREAD

**Issue by gamersalpha** [42wim/matterbridge#1159]
Hello there, i m just install matterbridge, and looks works if someone talk in irc i get the message on my mattermost, but if i talk in my mattermos i can"t see message on IRC :

From my mattermost : 

![image](https://user-images.githubusercontent.com/32466950/84317934-eaf60c80-ab6d-11ea-9ae3-bc5de137c02b.png)

on irc, i see i m connect but i can"t see my message mattermost to IRC
![image](https://user-images.githubusercontent.com/32466950/84318060-1b3dab00-ab6e-11ea-83bf-97db3bb989a6.png)

this is my config files : 

```
[irc]
    [irc.freenode]
    Server="irc.freenode.net:6667"
    UseSASL=true
    SkipTLSVerify=false
    Nick="issa"
    NickServNick="issa"
    NickServPassword="password"
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[mattermost]
    [mattermost.work]
    Server="192.168.1.4"
    Team="home"
    NoTLS=true
    Login="issa"
    Password="password!"
    PrefixMessagesWithNick=true
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="mygateway"
enable=true
    [[gateway.inout]]
    account="irc.freenode"
    channel="#e.fr"

    [[gateway.inout]]
    account="mattermost.work"
    channel="efr"


[[gateway]]
name="mygateway2"
enable=true
    [[gateway.inout]]
    account="irc.freenode"
    channel="#ubuntu-fr"

    [[gateway.inout]]
    account="mattermost.work"
    channel="ubuntufr"

```

thanks to all

**Comment by 42wim** [comment]
Also did you use a separate account on mattermost?
You can't use your own account as bridge AND talk with it at the same time.

**Comment by 42wim** [comment]
closed because of inactivity
