### ISSUE TITLE
Private chat on a bridge between Mattermost and WhatsApp.

### ISSUE THREAD

**Issue by Pablossi** [42wim/matterbridge#1162]
This is not a problem but a question.

Using a bridge between Mattermost and WhatsApp. Establish a private chat between two people.

it's possible?

**Comment by qaisjp** [comment]
- On Mattermost: have a channel with MatterPerson and a bot.
- On WhatsApp: have a group chat with just two people (WhatsAppPerson and the bot user).

**Comment by Pablossi** [comment]
I'm looking for supporting information about what you tell me but I can't find anything yet.
Do you know if there is published documentation about it?

**Comment by qaisjp** [comment]
Are you asking how to set up a bridge so that two people can communicate on different platforms, or whether you can have two people communicate privately (a private a message) on an existing bridge setup?

**Comment by Pablossi** [comment]
The second option.
I already have a working bridge between a WhatsApp group and a Mattermost channel. And I want to have a private conversation about the WhatsApp-Mattermost bridge

**Comment by 42wim** [comment]
This is not possible, related to #191
