### ISSUE TITLE
Telegram - Profile Pictures and Images not loading properly (Stable Branch)

### ISSUE THREAD

**Issue by cangurellobello** [42wim/matterbridge#1165]
here's a **log** of the error :
`Jun 25 12:27:54 user bridge[10950]: time="2020-06-25T12:27:54Z" level=error msg="File "373893399.png" to large to download (9948). MediaDownloadSize is -339607552" prefix=telegram`

**MediaDownloadSize** configuration inside **matterbridge.toml**
`[general]
MediaDownloadSize=51200000000`

**Comment by 42wim** [comment]
Use a normal MediaDownloadSize, 51200000000 is 51 Gigabytes.
Try  `MediaDownloadSize=100000000` which is 100Megabytes
