### ISSUE TITLE
[IRC->discord] Map users to random profile avatars

### ISSUE THREAD

**Issue by bluddy** [42wim/matterbridge#1166]
The IRC -> discord bridge works great. One thing our users complain about, however, is the inability to tell apart different IRC users.

It would be really neat if random avatars (from some source) could be mapped onto user names to allow telling them apart. Discord is really strongly built around avatars.

An alternative would be to color code the names, but I'm not sure discord supports that since colors are reserved for roles.

**Comment by qaisjp** [comment]
Yep, I recommend [adorable avatars](https://github.com/qaisjp/go-discord-irc/blob/380a4b3845e07acdf3dee5ede6985ccc21557061/bridge/bridge.go#L352-L355), been using it for three years, and reactiflux/discord-irc uses it too.

**Comment by Jaykul** [comment]
You can set an `IconURL` in the `[general]` config, like:

```
[general]
RemoteNickFormat="{NICK} ({LABEL}) "
EditSuffix=" (edited)"
IconURL="https://api.adorable.io/avatars/128/{Nick}"
```

Or use cats, instead:
```
[general]
IconURL="https://robohash.org/{NICK}.png?set=set4"
```

**Comment by qaisjp** [comment]
@Jaykul's suggestion seems to work great! If this approach doesn't work great for you, just leave a comment and we can re-open this :)

**Comment by bluddy** [comment]
Great solution, guys. Thanks!
