### ISSUE TITLE
Bug: panic: send on closed channel

### ISSUE THREAD

**Issue by elimisteve** [42wim/matterbridge#117]
Please answer the following questions. 

### Which version of matterbridge are you using?

version: 0.9.2-dev

### Please describe the expected behavior.

matterbridge keeps running

### Please describe the actual behavior. 

```
panic: send on closed channel

goroutine 14 [running]:
panic(0x92aea0, 0xc42289eb40)
        /home/ubuntu/go/src/runtime/panic.go:500 +0x1a1
github.com/42wim/matterbridge/vendor/github.com/thoj/go-ircevent.(*Connection).Privmsg(0xc42007dce0, 0xc4201846e0, 0x17, 0xc420444320, 0x4b)
        /home/ubuntu/gocode/src/github.com/42wim/matterbridge/vendor/github.com/thoj/go-ircevent/irc.go:256 +0x172
github.com/42wim/matterbridge/bridge/irc.(*Birc).doSend(0xc420051400)
        /home/ubuntu/gocode/src/github.com/42wim/matterbridge/bridge/irc/irc.go:126 +0x197
created by github.com/42wim/matterbridge/bridge/irc.(*Birc).Connect
        /home/ubuntu/gocode/src/github.com/42wim/matterbridge/bridge/irc/irc.go:90 +0x45e
```

### Any steps to reproduce the behavior?

Just leave matterbridge running for a while.

### Please add your configuration file 

Same as before: https://github.com/42wim/matterbridge/issues/113

**Comment by 42wim** [comment]
Crash is in vendored irc library, are you maybe on an unstable connection ?

**Comment by 42wim** [comment]
I've updated the vendored library. (has some fixes relevant to your case). 
Feel free to reopen if irc crashes again :-)

**Comment by elimisteve** [comment]
@42wim Thanks I'll give it a try :-)
