### ISSUE TITLE
Telegram - All users "unknown"

### ISSUE THREAD

**Issue by mrplow** [42wim/matterbridge#1172]
**Describe the bug**
I've recently setup a matterbridge to bridge a slack channel and a telegram channel. Installation via docker-compose on my linux server was quite straightforward (except getting the telegram channel id, what the heck telegram).

The sync is working but all messages coming into slack from telegram are showing the username as unknown. Going from slack to telegram is populating the usernames correctly.

**Screenshots/debug logs**
I can provide logs if this is indeed an issue

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04, docker-compose
 - Matterbridge version: 1.17.6-dev a94fe558

**Additional context**
I've played around with MessageFormat and UseFirstName settings in the telegram section but that didn't help

I reviewed issues related to telegram and I see a mention in #875 that telegram channels don't return usernames, if that is true then wouldn't the telegram bridge always return unknown - that seems contradictory to other issues I've reviewed.

Configuration file:
```
[slack]
[slack.test]
Token="xoxb-[redacted]"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[telegram]
[telegram.test]
Token="[redacted]"
RemoteNickFormat="<{NICK}> "

[general]
PrefixMessagesWithNick=true

[[gateway]]
    name = "mygateway"
    enable=true

    [[gateway.inout]]
    account = "telegram.test"
    channel = "[redacted]"

    [[gateway.inout]]
    account = "slack.test"
    channel = "[redacted]"
```

**Comment by mrplow** [comment]
I found that usernames are working properly when using telegram groups instead of telegram channels

I don't know if I missed that in the documentation but I believe it solves my problem.

**Comment by 42wim** [comment]
Added extra info about this in the wiki on https://github.com/42wim/matterbridge/wiki/Gateway-config-(channel-rules)
