### ISSUE TITLE
Update needed to discord dependency

### ISSUE THREAD

**Issue by aquila12** [42wim/matterbridge#1174]
Discord is deprecating the domain name `discordapp.com` for most purposes, and are standardizing on `discord.com`.  Code using `discordapp.com` (except for their CDN) will stop working in October 2020.

Matterbridge's dependency for discord is a fork of bwmarrin/discordgo (which has been updated to use the new domain) but the fork hasn't been updated in a couple of years.  Please could you consider whether you still need the fork and either switch to upstream or update the fork?

**Comment by 42wim** [comment]
I don't know which matterbridge fork you're using but matterbridge is following the stable discord tree (we're on v0.20.2) and a new v0.21 release just happened  27 days ago.

**Comment by aquila12** [comment]
Thanks for the quick response; I must have misread the code in that case; I found a reference to the old fork in https://github.com/42wim/matterbridge/blob/master/bridge/discord/discord.go, but I'm not particularly familiar with Go so I guess I've misunderstood how the dependencies are resolved.
