### ISSUE TITLE
Output to private Slack channel is not possible

### ISSUE THREAD

**Issue by jurgenhaas** [42wim/matterbridge#118]
We have a Slack gateway with a private channel and an API token from the Bots plugin on Slack.

When the destination channel is public, matterbridge properly writes to that channel. However, if the destination channel on Slack is private, then the debug output from matterbridge states `slack.name: channel serverfeed not found`

Is that a limitation of matterbridge? I'm asking because the API documentation from Slack states, that the API can also access private channels.

**Comment by jurgenhaas** [comment]
I should add that when starting matterbridge, there is a message that it joins the channel: `level=info msg="slack.name: joining serverfeed"` even when the channel is private.

**Comment by 42wim** [comment]
Fixed in master

**Comment by jurgenhaas** [comment]
Thanks for the quick turnaround.

**Comment by xenoguy** [comment]
I'm having issues with private channels in 0.9.2.  matterbridge outputs to them ok, but doesn't listen correctly.  other connected protocols are sending and receiving fine.

I am using a dedicated bot token, and public channels seem to work fine.  just not private ones.

**Comment by 42wim** [comment]
@xenoguy could you try master ? Your issue should be fixed now

**Comment by 42wim** [comment]
@xenoguy glad to hear. 
And yes you should look into Go, you'll not regret it :)
