### ISSUE TITLE
Whatsapp authentication fails every 30 days (approx)

### ISSUE THREAD

**Issue by wryun** [42wim/matterbridge#1181]
**Describe the bug**
Every month, matterbridge stop authenticating with whatsapp.

If I regenerate the QR code it works fine. Presumably this is an issue with the upstream library, but I haven't looked into it. I'm mostly raising this issue in case someone else has it.

**To Reproduce**
Get a QR code for whatsapp, run for a month, ...

**Expected behavior**
Secret should not expire (it doesn't for whatsapp web? Or does it? I don't use Whatsapp).

**Screenshots/debug logs**
Either:
```
[2020-07-27T12:29:04+10:00] FATAL main:         Starting gateway failed: Bridge whatsapp.**** failed to start: failed to restore session: admin login responded with 419
```
OR
```
[2020-07-27T12:29:11+10:00] FATAL main:         Starting gateway failed: Bridge discord.**** failed to start: websocket: close 4004: Authentication failed.
```
On starting.

**Environment (please complete the following information):**
 - OS: Linux
 - Matterbridge version: 1.17.4 6c442e23

**Additional context**

```
[whatsapp.****]
Label="****"
Number="+****"
SessionFile="whatsapp-****.gob"
QrOnWhiteTerminal=false
RemoteNickFormat="[{PROTOCOL}] @{NICK}: "

```

**Comment by nathanaelhoun** [comment]
Just run into the same issue today.
Looks related to https://github.com/Rhymen/go-whatsapp/issues/268

**Comment by 42wim** [comment]
going to close this as is upstream issue and the fix will flow back in to matterbridge when the library updates

**Comment by ciroiriarte** [comment]
Doesn't seem to go anywhere. I'm on the latest official container image, each month religiously I get "failed to restore serssion: admin login responded with 419"
