### ISSUE TITLE
Echo back from slack when using webhooks

### ISSUE THREAD

**Issue by xenoguy** [42wim/matterbridge#119]
Please answer the following questions. 

### Which version of matterbridge are you using?
0.9.2 (windows)

### Please describe the expected behavior.
bi-directional messages between slack work correctly.

#### Use logs from running ```matterbridge -debug``` if possible.
bi-directional link between slack and discord echos.  message from discord is written by matterbridge to slack, and then read by matterbridge on slack and written to discord again.

### Any steps to reproduce the behavior?
this is happening when bridging between discord and slack using webhooks.
when i attempt to bridge with slack api test token, the messages only succeed one way, discord -> slack.

#### (be sure to exclude or anonymize private data (tokens/passwords))

[slack]
	[slack.ottenl]
	#useAPI=true
	#Token="***"
	BindAddress="0.0.0.0:9999"
	URL="***"
	RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[discord]
	[discord.ottenl]
	Token="***"
	Server="***"
	RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="gateway1"
enable=true
	[[gateway.inout]]
	account="discord.ottenl"
	channel="testing123"

	[[gateway.inout]]
	account="slack.ottenl"
	channel="testing123"

**Comment by 42wim** [comment]
Nice avatar ;-)

Quick fix for your issue is to use slack API with a token like you tried.
My guess is that the reason you won't get messages from slack => discord with is because you didn't create a dedicated bot user in slack ?

I'll look into the webhook issue later this week

**Comment by xenoguy** [comment]
Thanks!
and you're right, I got slack working a little bit after this with a dedicated bot user.
