### ISSUE TITLE
[IRC <> Telegram] Print /me messages from IRC as * ${nick} ${message} in Telegram so they are able to be distinguished.

### ISSUE THREAD

**Issue by Justinzobel** [42wim/matterbridge#1193]
[IRC <> Telegram] Bridge

Currently /me messages from IRC to Telegram are printed the same as any other message.

/me messages from IRC are an action

* Justin slaps bob with a trout

It would be better if we could rint /me messages from IRC as * ${nick} ${message} in Telegram so they are able to be distinguished.

**Comment by Mikaela** [comment]
Duplicate of https://github.com/42wim/matterbridge/issues/1136?

**Comment by Justinzobel** [comment]
My apologies, it is.
