### ISSUE TITLE
Discord->Telegram RemoteNick bug

### ISSUE THREAD

**Issue by Dav-Edward** [42wim/matterbridge#1196]
**Describe the bug**
When defining on gateway settings a remote like such as:
RemoteNickFormat="<{NICK}>({PROTOCOL}): "
or
RemoteNickFormat="({NICK})({PROTOCOL}): "

Telegram to Discord messages work fine, but Discord to Telegram messages fail to go through giving these errors respectively:
[0029] ERROR gateway:      SendMessage failed: Bad Request: can't parse entities: Character '>' is reserved and must be escaped with the preceding '\'
or
[0029] ERROR gateway:      SendMessage failed: Bad Request: can't parse entities: Character '(' is reserved and must be escaped with the preceding '\'

**To Reproduce**
Use remote nicks containing ( ) or < >

**Expected behavior**
Messages with these remote nicks should work, they are even in the examples

**Environment (please complete the following information):**
 - OS: Ubuntu Linux
 - Matterbridge version: version: 1.18.0 e3d8fe4f

**Comment by bd808** [comment]
Is this the same issue as #285?

**Comment by Dav-Edward** [comment]
> Is this the same issue as #285?

It might be related, but this is happening in the RemoteNickname field of gateway configuration settings even using the provided example config.

**Comment by Dav-Edward** [comment]
With the great help of wim, the issue was solved, however documentation needs to be updated.

Could someone please update: https://github.com/42wim/matterbridge/wiki/Section-Telegram-%28basic%29
The value `RemoteNickFormat="[{PROTOCOL}] <{NICK}> "`   is not valid
You either need to add `MessageFormat="HTMLNick"` and RemoteNickFormat to `RemoteNickFormat="({PROTOCOL}) &lt;{NICK}&gt; "`
-or-
`MessageFormat="MarkdownV2"`
`RemoteNickFormat="{PROTOCOL} {NICK} "`   without any special characters such as < > ( ) - and so forth

Otherwise this is resolved
