### ISSUE TITLE
How to remove [whatsapp] tag when the message from Whatsapp comes into the MM channel. 

### ISSUE THREAD

**Issue by dishanksaxena** [42wim/matterbridge#1198]
Hi @42wim ,

Thanks for giving us such an amazing utility, really appreciate it.
Is there a way where we can actually remove or modify the tag which comes into the MM channel if we type in a message in WA group and it appears into MM channel as :
[whatsapp] <Dishank> This is a test message .
Is it possible to remove/modify this [whatsapp] tag.

**Comment by Mikaela** [comment]
Responded at chat.

* https://github.com/42wim/matterbridge/wiki/Settings#remotenickformat
* >the answer to your question should be simple: `RemoteNickFormat="<{NICK}> "`
  > I would put it in `[general]`, but it works in either

**Comment by 42wim** [comment]
Fixed by @Mikaela  👍 :)
