### ISSUE TITLE
How to remove [whatsapp] tag when the message from Whatsapp comes into the MM channel. 

### ISSUE THREAD

**Issue by dishanksaxena** [42wim/matterbridge#1199]
Hi @42wim ,

Thanks for giving us such an amazing utility, really appreciate it.
Is there a way where we can actually remove or modify the tag which comes into the MM channel if we type in a message in WA group and it appears into MM channel as :
[whatsapp] This is a test message .
Is it possible to remove/modify this [whatsapp] tag.

**Comment by 42wim** [comment]
See #1198
