### ISSUE TITLE
Rocketchat API

### ISSUE THREAD

**Issue by Frankstar** [42wim/matterbridge#120]
any plans to add the rocket.chat api like for mattermost ?
[Rocket.Chat API](https://rocket.chat/docs/developer-guides/rest-api/)
like

>  useAPI=true
    Server="yourrocketchatserver.domain"
    Login="yourlogin"
    Password="yourpass"

**Comment by 42wim** [comment]
See #108 for explanation

**Comment by 42wim** [comment]
fixed in #707 (in master)
