### ISSUE TITLE
How to get all group chats or one-to-one chats synced from Whatsapp to MM

### ISSUE THREAD

**Issue by dishanksaxena** [42wim/matterbridge#1200]
Hi @42wim,

I've successfully integrated WA with MM via matterbridge. 
Currently i'm getting messages synced for 1 WA group.

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="mattermost.mymattermost"
channel="channelname"

[[gateway.inout]]
account="whatsapp.mywhatsapp"
channel="chatid@g.us"

What if i want to get the messages from all groups in my whatsapp and also all one-to-one chats which i have in whatsapp.
Question 1 - Do i have to add a new gateway for each whatsapp group that i want to integrate with MM? 
Question 2 - How to get the one-to-one chats from WA to MM
Question 3 - if it is possible using gateway then how do we add mutiple gateways? [is the below one correct?]

[[gateway]]
name="gateway2"
enable=true

[[gateway.inout]]
account="mattermost.mymattermost"
channel="channelname"

[[gateway.inout]]
account="whatsapp.mywhatsapp"
channel="groupjid2@g.us

**Comment by 42wim** [comment]
> Question 1 - Do i have to add a new gateway for each whatsapp group that i want to integrate with MM?
Yes

> Question 2 - How to get the one-to-one chats from WA to MM
This is not possible

> Question 3 - if it is possible using gateway then how do we add mutiple gateways? [is the below one correct?]
Should be, yes

**Comment by 42wim** [comment]
No, no idea
