### ISSUE TITLE
Matrix: having 5 bridged rooms results to M_LIMIT_EXCEEDED: Too Many Requests and failing bridge / potentially incompatible with Matrix Synapse 1.19.0

### ISSUE THREAD

**Issue by Mikaela** [42wim/matterbridge#1201]
**Describe the bug**

I have 5 rooms that are bridged to Matrix. When I start matterbridge, it will fail to connect to Matrix due to

`time="2020-08-20T07:24:39Z" level=error msg="Bridge matrix.feneas failed to join channel: contents=[123 34 101 114 114 99 111 100 101 34 58 34 77 95 76 73 77 73 84 95 69 88 67 69 69 68 69 68 34 44 34 101 114 114 111 114 34 58 34 84 111 111 32 77 97 110 121 32 82 101 113 117 101 115 116 115 34 44 34 114 101 116 114 121 95 97 102 116 101 114 95 109 115 34 58 57 55 50 56 125] msg=Failed to POST JSON to /_matrix/client/r0/join/!REDACTED:matrix.org code=429 wrapped=M_LIMIT_EXCEEDED: Too Many Requests" func=disableBridge file="gateway/router.go:111" prefix=router`

I think this is related to homeserver having recently updated to [Synapse 1.19.0](https://github.com/matrix-org/synapse/releases/tag/v1.19.0)

**To Reproduce**

1. Configure 5 channels.
2. Start matterbridge

**Expected behavior**

Matterbridge starts normally.

**Screenshots/debug logs**

`time="2020-08-20T07:24:39Z" level=error msg="Bridge matrix.feneas failed to join channel: contents=[123 34 101 114 114 99 111 100 101 34 58 34 77 95 76 73 77 73 84 95 69 88 67 69 69 68 69 68 34 44 34 101 114 114 111 114 34 58 34 84 111 111 32 77 97 110 121 32 82 101 113 117 101 115 116 115 34 44 34 114 101 116 114 121 95 97 102 116 101 114 95 109 115 34 58 57 55 50 56 125] msg=Failed to POST JSON to /_matrix/client/r0/join/!REDACTED:matrix.org code=429 wrapped=M_LIMIT_EXCEEDED: Too Many Requests" func=disableBridge file="gateway/router.go:111" prefix=router`

**Environment (please complete the following information):**
 - OS: Debian 9.13
 - Matterbridge version: 1.18.0 e3d8fe4f

**Additional context**

* The homeserver was recently updated to [Synapse 1.19.0](https://github.com/matrix-org/synapse/releases/tag/v1.19.0)
  * Edit: https://github.com/matrix-org/synapse/issues/8008 introduces ratelimiting
    * which matterbridge should probably start handling and retrying later
* I don't have config file on this machine, please ask if it's really needed.
* I think Matterbridge may be misbehaving by attempting to join the 5 rooms on start while you only need to join rooms once (unless you leave or get kicked), so it should just detect that it has joined those rooms already rather than trying to rejoin every start?

**Comment by 42wim** [comment]
Thanks for the debugging info 👍

It also needs to join the rooms to get the id's back to have the channel mapping.

Could you try putting a `time.Sleep(time.Second)` above this line https://github.com/42wim/matterbridge/blob/master/bridge/matrix/matrix.go#L63 to see if this slowdown fixes it?

**Comment by Mikaela** [comment]
> It also needs to join the rooms to get the id's back to have the channel mapping.

Shouldn't it just perform a sync and get list of the rooms where it's already in? https://matrix.org/docs/guides/client-server-api#getting-all-state

> Could you try putting a `time.Sleep(time.Second)` above this line https://github.com/42wim/matterbridge/blob/master/bridge/matrix/matrix.go#L63 to see if this slowdown fixes it?

I am not sure, I haven't managed to compile Matterbridge before and my server definitely isn't capable of it. I will need to take a look later.

**Comment by 42wim** [comment]
Is this change already rolled out on matrix.org?

**Comment by fire219** [comment]
> Is this change already rolled out on matrix.org?

Yes it is. I just ran into this issue after having to restart matterbridge. My deployment of it probably one of the larger ones (for Pine64; 8 channels spread across 4 platforms each), so I just had to custom-compile matterbridge with the `time.Sleep(10 * time.Second)` workaround.

The workaround works, but having to wait an additional 80 seconds for the bridge to come up is not ideal. It's better than our network being broken, though. 😅

**Comment by 42wim** [comment]
sigh, that really sucks that they roll this out so quickly and don't have their own libraries support the rate-limiting

**Comment by fire219** [comment]
From personal experience, I can say that the general consensus in that community is that the matrix-appservice bots should used for any sort of bridging. Most of those appservice bots use the Node libraries, which probably have gotten updates to match Synapse v1.19.

I've gotten plenty of complaints from my use of Matterbridge, but running 4 discrete bridges sounds like a nightmare to me...

**Comment by 42wim** [comment]
it's not just bridging, any "normal" client that just joins rooms will get issues.

**Comment by Sorunome** [comment]
"normal" clients won't try to join rooms they are already in at startup. Which is why soru suggested querying joined_rooms first, to know which ones you are already in.

Rate limits are server-dependant: stricter rate limits on matrix.org have nothing to do with a synapse update.

gomatrix is probably just a thin spec wrapper, making rate limit handling out-of-scope

**Comment by Sorunome** [comment]
Sorry, soru missed that they added rate limits to /join. There are rate limits on other endpoints, too, and it is generally a good idea to handle them. The part about querying joined_rooms and gomatrix being a thin wrapper still apply.

**Comment by 42wim** [comment]
@Sorunome yes, well guess what if I query joined_rooms I get ID's and not the room aliases :)

So now I have to query  GET /_matrix/client/r0/rooms/{roomId}/aliases (which isn't supported in the gomatrix library) and also is rate-limited.

So the netto result is that I'll have to do even an extra query to get the same information.

I don't understand that they also limit the joining rooms you're already a member of, that shouldn't take that much resources.

**Comment by 42wim** [comment]
released v1.18.1 with contains this fix.
