### ISSUE TITLE
Slack outgoing webhook not working

### ISSUE THREAD

**Issue by Sir-Will** [42wim/matterbridge#121]
hey,
I did just setup matterbridge with docker but the outgoing webhook doesn't want to work.
I also can't reach the address in the browser although it shows 
`2017/02/06 22:48:45 Listening on http://0.0.0.0:9999...`

**Comment by Sir-Will** [comment]
Just tried it with useAPI and this worked.
Leaving this issue open as this seems to be an issue with dockerfile and the port.

**Comment by 42wim** [comment]
This is a docker issue, you'll have to add -p 9999:9999 to relay the external port to your internal docker.
But use API where possible, webhooks are a pain.
