### ISSUE TITLE
MatterBridge uses oudated fields and has no `identifier` support when connecting to Matrix.

### ISSUE THREAD

**Issue by kworr** [42wim/matterbridge#1217]
I filed original ticker for conduit but they say it's not their fault:

https://git.koesters.xyz/timo/conduit/issues/199

    Deserialization(RequestDeserializationError { inner: Json(Error(“missing field identifier”, line: 1, column: 81)), http_request: Request { method: POST, uri: /_matrix/client/r0/login, version: HTTP/1.1, headers: {“x-forwarded-for”: “37.57.97.118”, “host”: “b1t.name”, “connection”: “close”, “content-length”: “82”, “content-type”: “application/json”, “accept-encoding”: “gzip”, “user-agent”: “Go-http-client/2.0”}, body: [...] } })

Generally this means MatterBridge works ok with Synapse, official server, but fails to work with conduit. Also it will eventually stop working when Synapse would make `identifier` default.

**Comment by 42wim** [comment]
@kworr i'm going to tell you it's not matterbridge's fault ;-)
We're using the official matrix library on https://github.com/matrix-org/gomatrix/

Seems a PR is waiting there with that fix, https://github.com/matrix-org/gomatrix/pull/73

**Comment by 42wim** [comment]
I'm also looking into changing the matrix library to https://github.com/tulir/mautrix-go (which has that fix, so it could be resolved that way soon)

**Comment by 42wim** [comment]
@kworr Thanks to #1219  the fix is now in master, so you should be able to connect to your server.
