### ISSUE TITLE
whatsapp disconnect when turn off my phone

### ISSUE THREAD

**Issue by supmyhava** [42wim/matterbridge#1218]
i am using matterbridge to bridge irc to whatsapp
i buy a new sim card for the whatsapp account
its all set and all work just great
but when i turn off my phone with the matterbridge whatsapp account the bot is unable to send messages anymore
there is something to do with it?

**Comment by poVoq** [comment]
Yes this is sadly the way WhatsApp web works and the WhatsApp web api is the only way to reliably interact with the WhatsApp service outside of the app.

**Comment by supmyhava** [comment]
> Yes this is sadly the way WhatsApp web works and the WhatsApp web api is the only way to reliably interact with the WhatsApp service outside of the official Android/iOS app.

so what can i do with that?
there is some option?

**Comment by poVoq** [comment]
Put the main WhatsApp app on an old Android phone and run that 27/4.

Anternatively you can try running an Android VM (or maybe Anbox?) on a server and install the official WhatsApp app there.

**Comment by supmyhava** [comment]
> Put the main WhatsApp app on an old Android phone and run that 27/4.
> 
> Alternatively you can try running an Android VM (or maybe Anbox?) on a server and install the official WhatsApp app there.

"Put the main WhatsApp app on an old Android phone and run that 27/4."
ok i just did it (:
i will try this for something like 3 days and i will see what is going on with that
if it not will work i will try the secont thing that you gave me
thank you!!
