### ISSUE TITLE
[Discord] Forward Nick instead of Name

### ISSUE THREAD

**Issue by Sir-Will** [42wim/matterbridge#122]
If you change your nick on a discord server it will forward the name and not the nick you have changed to.
Would it be possible to add an option so it forwards the current nick?

**Comment by 42wim** [comment]
This is the information I'm getting from the API https://discordapp.com/developers/docs/resources/user#user-object
I'm only getting a username, not a nick.

Could you possible add some examples or screenshots of the issue ?

**Comment by Sir-Will** [comment]
![](http://i.imgur.com/LJjGvCS.jpg)
---
![](http://i.imgur.com/ASufGoQ.jpg)

**Comment by 42wim** [comment]
This should be fixed in master now. 
Seems like every guild has members, which have a nick and a link to the user object. I'm checking now to use the nick when it's set, otherwise use the username.

**Comment by Sir-Will** [comment]
Thanks.

Hm, I'm using docker, how do I update it there?

**Comment by 42wim** [comment]
docker has been updated also. ```docker pull 42wim/matterbridge``` and restart

**Comment by Sir-Will** [comment]
Thanks, works now.
