### ISSUE TITLE
Link to Bencey's Blog has rotted. It now links to a 404ed page.

### ISSUE THREAD

**Issue by placeybordeaux** [42wim/matterbridge#1224]
**Describe the bug**
Link to Bencey's Blog has rotted. It now links to a 404ed page.

**To Reproduce**
Click on link to https://bencey.co.nz/2018/09/17/bridge/

**Expected behavior**
A blog post about matterbridge

**Screenshots/debug logs**
```
[peter@nixos:~]$ curl -I https://bencey.co.nz/2018/09/17/bridge/
HTTP/2 404
cache-control: public, max-age=0, must-revalidate
content-length: 0
content-type: text/html; charset=utf-8
date: Tue, 01 Sep 2020 17:24:32 GMT
etag: 1597363184-ssl
age: 0
server: Netlify
x-nf-request-id: b5a6d901-4d30-4f5e-b73d-73bf6f8d2771-4401783
```

**Environment (please complete the following information):**

**Additional context**

**Comment by 42wim** [comment]
thanks!
