### ISSUE TITLE
Mattermost moving to API version 4

### ISSUE THREAD

**Issue by jasonblais** [42wim/matterbridge#123]
Hey @42wim !

Cross-posting my note in https://github.com/42wim/csm/issues/2 over here too. :)

----

I wanted to let you know about our plans moving to API v4: 

To make the Mattermost API web service easier to use and to offer more powerful options for these integrations, Mattermost will be moving to a [new API version](https://docs.google.com/document/d/197JwEBMnK8okFilTfGSpbsrXPY5RZOJ4gG2DXwcbwYE/edit) soon.  Highlights include:  

* Fully documented API endpoints 
* More in-depth access to server functionality 
* Wider use of established HTTP verbs 
* Consistent endpoint structures 
* A new and improved Go driver  

We plan to release API version 4 on March 16th, with Mattermost server 3.7.  While the current API version 3 will be supported until September 16th, we recommend you begin using API version 4 soon after its release.

#### Contributing  

API version 4 is an active and on-going project. If you're interested in helping contribute, [please join our Mattermost community instance](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) and the [APIv4 channel](https://pre-release.mattermost.com/core/channels/apiv4). 

We've prepared a [contribution process for APIv4](https://docs.mattermost.com/developer/api4.html) and a [progress tracker for new APIv4 enpoints](https://docs.google.com/spreadsheets/d/1nPoLgwh_9zRFECpqRUZAKIWihCmX27pnDtFGLtG_WnY/edit#gid=0) to help you get started.

We're also open for suggestions on adding new API endpoints to help with your integration.

**Comment by 42wim** [comment]
Took a while but finally happened ;)
