### ISSUE TITLE
Join IRC channels on invite

### ISSUE THREAD

**Issue by tari** [42wim/matterbridge#1231]
**Is your feature request related to a problem? Please describe.**

I want to bridge an IRC channel that's configured as invite-only (`+i`).

**Describe the solution you'd like**

matterbridge should be able to join IRC channels that are configured in a gateway when it is invited to them.

**Describe alternatives you've considered**

 * Channel mode `+I <hostmask>`, which doesn't seem to work on this network.
 * Set the channel `+k`. Doesn't seem to work on this network either (setting the channel `+ik` doesn't allow matterbridge to join with the key).

**Comment by Mikaela** [comment]
I think you can do this by a autocommand CHANSERV INVITE #channel and then JOIN #channel. I don't have the exact syntax at hand on mobile.

Regardless I ageee that joining configured channels would be better solution in a scenario you described.

**Comment by tari** [comment]
Chanserv doesn't exist on this network (how tedious!) so that won't work either.
