### ISSUE TITLE
[NCTalk] stops relaying messages after a few minutes

### ISSUE THREAD

**Issue by eneiluj** [42wim/matterbridge#1235]
@gary-kim Hi!
I don't know if the problem is on my side or if there is a bug in nctalk matterbridge backend. As my Nextcloud setup is a clean local test instance, I doubt the problem comes from there.

After having started a matterbridge process (official matterbridge-1.18.3-linux-64bit binary) linking a Talk room and a Matrix channel. Every works fine for a while and after a few minutes (less than 10) messages are not relayed anymore. Log is silent when I write in the Talk room. But I get that when writing in the Matrix channel:

```
time="2020-09-08T16:09:16+02:00" level=info msg="Gateway(s) started succesfully. Now relaying messages" prefix=main
time="2020-09-08T16:16:39+02:00" level=error msg="Could not send message to room qbd3pth9 from [matrix] <eneiluj> : unexpected return code" prefix=nctalk
```

I get nothing in the Nextcloud logs (maximum detail level).

Matterbridge config is very basic:
```
[matrix.0]
    Server = "https://matrix.org"
    Login = "xxxx"
    Password = "xxxx"
    PrefixMessagesWithNick = true
    NoHomeServerSuffix = true
    RemoteNickFormat = "[{PROTOCOL}] <{NICK}> "

[nctalk.1]
    Server = "http://xxxxxx/dev/server"
    Login = "xxxx"
    Password = "xxxxx"
    PrefixMessagesWithNick = true
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
    name = "myGateway"
    enable = true

[[gateway.inout]]
    account = "matrix.0"
    channel = "!xxxxx:matrix.org"

[[gateway.inout]]
    account = "nctalk.1"
    channel = "qbd3pth9"
```

**Comment by gary-kim** [comment]
I have no idea how it is you're so much better at finding these edge cases than I am so thank you very much for reporting.

**Comment by eneiluj** [comment]
Well let me answer with a compliment too: nctalk backend is just amazing!

**Comment by gary-kim** [comment]
I'm trying to reproduce the issue but I'm having some trouble. Let me get in contact with you directly, @eneiluj

**Comment by 42wim** [comment]
@gary-kim any news about this?

**Comment by gary-kim** [comment]
I didn't manage to reproduce it but didn't manage to. Seems to have been a setup specific issue. @eneiluj could we consider this fixed or am I forgetting something?

**Comment by 42wim** [comment]
No feedback, closing it. Reopen if still issue
