### ISSUE TITLE
Keybase: invalid whoami JSON "No help topic for 'whoami'\n": invalid character 'N' looking for beginning of value

### ISSUE THREAD

**Issue by kaotisk-hund** [42wim/matterbridge#1241]
**Describe the bug**
Keybase problem with matterbridge
`bot failed to start: invalid whoami JSON "No help topic for 'whoami'\n": invalid character 'N' looking for beginning of value`

**To Reproduce/Additional context**
I guess the configuration comes into this
```
[keybase.user_bot]
Team="team"
RemoteNickFormat="[{PROTOCOL}/{BRIDGE}] <{NICK}> "

[irc]
        [irc.server]
        Server="someircserver:6667"
        Nick="keybaseBridge"
        RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
        ColorNicks=true

[[gateway]]
name="gateway-key-irc"
enable=true
        [[gateway.inout]]
        account="irc.server"
        channel="#channel"

        [[gateway.inout]]
        account="keybase.user_bot"
        channel="#channel"
```

**Expected behavior**
Just bridge between keybase and IRC

**Screenshots/debug logs**
```
% ./matterbridge --debug
[0000]  INFO main:         [setupLogger:matterbridge.go:106] Enabling debug logging.
[0000]  INFO main:         [main:matterbridge.go:46] Running version 1.18.3 8b26e42a
[0000]  INFO router:       [Start:gateway/router.go:66] Parsing gateway gateway-key-irc-ed12
[0000]  INFO router:       [Start:gateway/router.go:75] Starting bridge: keybase.kaotisk_bot
[0000]  INFO keybase:      [Connect:bridge/keybase/keybase.go:33] Connecting cjdns
[0000] FATAL main:         [main:matterbridge.go:68] Starting gateway failed: Bridge keybase.kaotisk_bot failed to start: invalid whoami JSON "No help topic for 'whoami'\n": invalid character 'N' looking for beginning of value

```

**Environment (please complete the following information):**
 - OS: ArchLinux
 - Matterbridge version: version: 1.18.3 8b26e42a

**Comment by qaisjp** [comment]
We probably need to update whatever vendor library we're using.

(There are probably updates since we last vendored the library, but probably no *recent* updates due to Zoom's acquisition of Keybase.)

**Comment by 42wim** [comment]
We're actually on the latest vendor library :/ 
What version of keybase are you using?
What do you get when you manually run `keybase whoami -json` ?

**Comment by kaotisk-hund** [comment]
Oh, I just checked and I saw that I was on an old repository for unknown reason. I am updating rn and retesting.

And yes, it does work with current version.

Now turns to other problem, I can get message from Irc to keybase but not the opposite way.

**Comment by kaotisk-hund** [comment]
Oh, I just checked and I saw that I was on an old repository for unknown reason. I am updating rn and retesting.

And yes, it does work with current version.

Now turns to other problem, I can get message from Irc to keybase but not the opposite way.

**Comment by kaotisk-hund** [comment]
Should I close this one and open a new one?

**Comment by 42wim** [comment]
@kaotisk-hund I'm guessing you're not using a separate user to send messages from keybase to irc.
You can't do it with your own account.
If this is not the case and didn't fix it, please reopen another issue.
