### ISSUE TITLE
WhatsApp join channel fails and doesn

### ISSUE THREAD

**Issue by theophanemayaud** [42wim/matterbridge#1246]
**Describe the bug**
First I setup WhatsApp with the conversation name :
```
[[gateway.inout]]
account="whatsapp.webWhatsApp"
channel="MTE Classe 2020-2022"
```
Then it complains "file to join"... use JID provided above. At first (or sometime, I haven't figured out a pattern), the JID is indeed suggested. Then I use it : 
```
 [[gateway.inout]]
account="whatsapp.webWhatsApp"
channel="393315...-159912...@g.us"
```
And it works, but only once. On the next reconnect, it again complains that it "fails to join" but not providing a new (updated ?) JID. Also, it seems to fail because : 
_[main:matterbridge.go:68] Starting gateway failed: Bridge whatsapp.webWhatsApp failed to join channel: account doesn't belong to group with jid 393315600618-1599123922@g.us_

Then, when I set the channel to the name like at first, it doesn't suggest the JID anymore...

**To Reproduce**
Set WhatsApp channel to name of group : get JID, use JID, connect to it once, disconnect. Connect to it again : it doesn't work anymore, but it doesn't suggest a new JID, even when setting the channel back to the name of the group.

**Expected behavior**
I expect, after a JID is provided correctly, for it to work every time in the future. And when setting the channel to the name of the group, to suggest the JID every time.

**Screenshots/debug logs**
Trying to connect with the name of the group as channel, after it has worked once and now doesn't work and doesn't suggest the JID : 
```
[0001] DEBUG whatsapp:     [Connect:bridge/whatsapp/whatsapp.go:68] Connecting to WhatsApp..
[0001] DEBUG whatsapp:     [Connect:bridge/whatsapp/whatsapp.go:78] WhatsApp connection successful
[0001] DEBUG whatsapp:     [Connect:bridge/whatsapp/whatsapp.go:86] Restoring WhatsApp session..
[0002] DEBUG whatsapp:     [Connect:bridge/whatsapp/whatsapp.go:97] Session restored successfully!
[0003]  INFO whatsapp:     [joinChannels:bridge/bridge.go:77] whatsapp.webWhatsApp: joining MTE Class 2020-2022 (ID: MTE Class 2020-2022whatsapp.webWhatsApp)
[0003] DEBUG whatsapp:     [func1:bridge/whatsapp/whatsapp.go:127] Getting user avatars..
[0003] DEBUG whatsapp:     [func1:bridge/whatsapp/whatsapp.go:139] Finished getting avatars..
[0003] FATAL main:         [main:matterbridge.go:68] Starting gateway failed: Bridge whatsapp.webWhatsApp failed to join channel: please specify group's JID from the list above instead of the name 'MTE Class 2020-2022'
```

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: version: 1.18.3 8b26e42a
 - If self compiled: NA, used matterbridge-1.18.3-linux-64bit binaries

**Additional context**

[discord.testDiscord]
	Token=""
	Server=""
	RemoteNickFormat="[@{NICK} from {BRIDGE}] "

[discord.mteDiscord]
	Token=""
	Server=""
	RemoteNickFormat="[@{NICK} from {BRIDGE}] "

[discord.pofDiscord]
	Token=""
	Server=""
	RemoteNickFormat="[@{NICK} from {BRIDGE}] "

[whatsapp.webWhatsApp]
	Number=""
	SessionFile=""
	QrOnWhiteTerminal=false
	RemoteNickFormat="[@{NICK} from {BRIDGE}] "

[api.FBmessenger]
	BindAddress="127.0.0.1:4242"
	Buffer=1000
	RemoteNickFormat="[@{NICK} from {BRIDGE}] "

# ----------------------End of provider configurations ---------------------------------
# --------------------------------------------------------------------------------------

#---------------------------------------------------------------------------------------
#--------------------------Beginning of Bridges ----------------------------------------

# -------------------------- MTE WhatsApp Discord bridging -----------------------------
[[gateway]]
name="mte-whatsapp-discord"
enable=true

[[gateway.inout]]
account="discord.mteDiscord"
channel="general"

[[gateway.inout]]
account="whatsapp.webWhatsApp"
channel="3933[...]-15991[...]@g.us"
# --------------------------------------------------------------------------------------

# --------------------------Principles of finance messenger and discord link------------
[[gateway]]
name="pof"
enable=true

[[gateway.inout]]
account="discord.pofDiscord"
channel="general"

[[gateway.inout]]
account="api.FBmessenger"
channel="pof"
# --------------------------------------------------------------------------------------

# ----------------------Matterbridge FB messenger debug & config gateway :-------------
[[gateway]]
name="FBgateway"
enable=true

[[gateway.inout]]
account="discord.testDiscord"
channel="general"

[[gateway.inout]]
account="api.FBmessenger"
channel="api"
# --------------------------------------------------------------------------------------

# ------------------------ End of bridges-----------------------------------------------
# --------------------------------------------------------------------------------------

**Comment by theophanemayaud** [comment]
I'm wondering if it's maybe to do with WhatsApp not being connected to the phone anymore... Does it complain about that specifically when that is the problem ?

**Comment by supmyhava** [comment]
after you scan the code and connect the matterbridge you need to leave the phone on non-stop

**Comment by theophanemayaud** [comment]
Hmmm yes that might be it... I'll check if this problem happens again, whether when I re-open WhatsApp on my phone it fixes it or not.

**Comment by schapira** [comment]
sorry if that might be obvious but "non-stop" mod is that leave the phone connected or are you talking about somethings else?
I have the same issue and try to resolved it. running on win10.

**Comment by theophanemayaud** [comment]
It does seem like the problem was that the phone was not connected anymore. I'll close this, maybe the error message could have been more precise, but that's probably upstream ... ?
