### ISSUE TITLE
One way sync between messaging systems?

### ISSUE THREAD

**Issue by aloneagainor** [42wim/matterbridge#1248]
**Describe the bug**
Apologies if this has been asked before but I couldn't see anything related in the FAQ or in other issues that were raised. Is it possible to configure the gateway to sync messages from one system to another but not the other way around? In this particular case, I would like all messages posted in Telegram to appear in Mattermost but not the other way around.

**To Reproduce**

Start Matterbridge with the following config file:

[telegram.mytelegram]
Token="_redacted_"
RemoteNickFormat="({PROTOCOL}) &lt;{NICK}&gt; "
MessageFormat="HTMLNick"

[mattermost.mymattermost]
Server="172.20.6.149:8065"
Team="mbtest"
Login="mbsync"
Password="_redacted_"
NoTLS=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
PrefixMessagesWithNick=true

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="telegram.mytelegram"
channel="-_redacted_"

[[gateway.inout]]
account="mattermost.mymattermost"
channel="matterbridge"

**Expected behavior**
I expected a two way sync between Telegram and Mattermost, which is what currently happens. However I would like that only Telegram messages are synced to Mattermost, and not from Mattermost to Telegram.

**Environment (please complete the following information):**
 - OS: Debian 10
 - Matterbridge version: 1.18.3 8b26e42a

**Comment by aloneagainor** [comment]
Does anyone have any ideas? If there's no official solution is there a way to stop the messages being sent to Telegram by deliberately configuring something incorrectly instead?

**Comment by aloneagainor** [comment]
This is possible by changing the gateway config from gateway.inout for both services to gateway.in for Telegram and gateway.out for Matterbridge.

**Comment by reloxx13** [comment]
this .in and .out should be better documented somewhere. i earched alot now and found it here in an issue.

**Comment by 42wim** [comment]
Well, where did you look? As it is in the sample config:

https://github.com/42wim/matterbridge/blob/a79e632cdc26f3870b0d8b37f9a94bdcf6f47711/matterbridge.toml.sample#L1830-L1838

**Comment by reloxx13** [comment]
r u serious line 1800+ ? how should a new user find this without knowing what to search for.

ur wiki is leading to a small basic setting, that to all settings. https://github.com/42wim/matterbridge/wiki/Settings

https://github.com/42wim/matterbridge/wiki/How-to-create-your-config

**Comment by 42wim** [comment]
@reloxx13 thanks, feel free to improve, the wiki is editable for everyone.
