### ISSUE TITLE
Incoming webhook sockets from mattermost to bridge seem to be left open permanently

### ISSUE THREAD

**Issue by Thracky** [42wim/matterbridge#125]
Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
0.9.2 linux 64 bit
### If you're having problems with mattermost please specify mattermost version. 
3.6.2
### Please describe the expected behavior.
When receiving a webhook message from mattermost, the socket should be closed upon completion of the message, as mattermost will open a new socket upon each message. 

While it would be preferred to re-use the same socket, mattermost does not seem to follow this behaviour.

#### Use logs from running ```matterbridge -debug``` if possible.
Outgoing webhook messages from mattermost to matterbridge appear to leave the socket open permanently.

I noticed this because I have mattermost and matterbridge running as the same user and I ran out of available file descriptors due to the fact that each message in mattermost appears to leave a socket open to matterbridge.

### Any steps to reproduce the behavior?
Set up an IRC <> Mattermost bridge using outgoing/incoming webhooks as opposed to the API.

### Please add your configuration file 
[irc]
[irc.foo]
Server="ircserverhere"
UseTLS=true
Nick="matterbot"
[mattermost]
[mattermost.work]
URL=incomingwebhookurl
BindAddress=127.0.0.1:9999

[[gateway]]
name="gateway1"
enable=true

[[gateway.in]]
account="irc.foo"
channel="#somechannel"
[[gateway.out]]
account="irc.foo"
channel="#somechannel"
[[gateway.in]]
account="mattermost.work"
channel="town-square"
[[gateway.out]]
account="mattermost.work"
channel="town-square"

**Comment by 42wim** [comment]
Can't seem to reproduce this, the matterbot on #matterbridge also use webhooks and has no lingering connections.

Could you run ```lsof -n -p $(pgrep matterbridge)| wc -l``` ?

```
ubuntu$ lsof -n -p $(pgrep matterbridge)|wc -l
15
```

**Comment by Thracky** [comment]
At the moment this is the output

root@mm:/opt/matterbridge# lsof -n -p $(pgrep matterbridge)| wc -l
25

For each message sent in mattermost that number will increase by 1

**Comment by 42wim** [comment]
Ok, reproduced. It's only mattermost => matterbridge, not the other way around.
I've fixed it in master. (connections go away after 5 seconds). 
Could you try and let me know if it's fixed for you also ?

**Comment by Thracky** [comment]
That's definitely resolved it. Thank you very much for the quick patch!
