### ISSUE TITLE
Couldn't configure steam

### ISSUE THREAD

**Issue by KebabLord** [42wim/matterbridge#1254]
i generally succeed using matterbridge with irc,telegram,whatsapp and discord. But can't get it work when it comes to steam. Both receiving and sending doesn't work with no error.
Here is my steam&irc configuration
```
[irc.poop]
Server="irc.blahblah.net:6697"
Nick="bottobotto"
UseTLS=true
SkipTLSVerify=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "


[steam.poop]
Login="blahblah"
Password="blahblah"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
        name="irc_steam"
        enable=true

        [[gateway.inout]]
        account="steam.poop"
        channel="10358279144054XXXX"

        [[gateway.inout]]
        account="irc.poop"
        channel="#pooptest"
```
After the latest update of steam chat there are also channels came into groups. But since we can only specify the group id, i suspect the problem might be my channel configuration. Anyone also get it work? I'm simply pulling my groupID64 from visiting there https://steamcommunity.com/groups/*******/memberslistxml/?xml=1 
anything i'm missing?

**Comment by GabeIggy** [comment]
This is caused because of https://github.com/42wim/matterbridge/issues/457.

**Comment by KebabLord** [comment]
so matterbridge with steam officially doesn't work

**Comment by 42wim** [comment]
@KebabLord could you try the latest dev build on https://github.com/42wim/matterbridge/actions/runs/316454337
Select the artifact for your OS, unzip and run.
Let me know if this makes any difference

**Comment by KebabLord** [comment]
didn't work either.
it successfully logon, the profile status gets "online". But it couldn't join group chat, just the same errors.
```
[0109] DEBUG steam:        [handleEvents:matterbridge/bridge/steam/handlers.go:81] unknown event &steam.ClanStateEvent{ClanId:0x170000000660dbe, AccountFlags:3, ClanName:"", Avatar:[]uint8(nil), MemberTotalCount:0xbc, MemberOnlineCount:0x2d, MemberChattingCount:0x0, MemberInGameCount:0x3, Events:[]steam.ClanEventDetails(nil), Announcements:[]steam.ClanEventDetails(nil)}
``` 

![2020-10-21_17-28](https://user-images.githubusercontent.com/24779257/96734975-bd468d00-13c3-11eb-9d7e-ea270f4b7adf.png)

i also tried to join to my group chat with bot manually and run script after that, it didn't work either.

**Comment by KebabLord** [comment]
let me try it on my debian machine

**Comment by 42wim** [comment]
could you try with the recent released version 1.19.0 ? it has updated steam dependencies

**Comment by KebabLord** [comment]
> let me try it on my debian machine

no luck.

**Comment by InvalidArgument3** [comment]
Could you please update the wiki about the current incompatibility with the new steam chat? Currently it says that it functions as long as you spent 5$ to remove the "limited" account status.

**Comment by 42wim** [comment]
@InvalidArgument3 thanks, I've modified in the wiki that steam is not working at the moment.

**Comment by 42wim** [comment]
Closing in favor #457
