### ISSUE TITLE
Stop using strings.ReplaceAll() and use strings.Replace("aa", "bb", -1) instead, please!

### ISSUE THREAD

**Issue by shizeeg** [42wim/matterbridge#1256]
https://github.com/42wim/matterbridge/blob/219a5453f9edaa87aa7aa4b9d5f9c3de9c75b38f/bridge/matrix/matrix.go#L429

strings.ReplaceAll() was introduced as a simple wrapper around strings.Replace() in Go 1.14! Why to use it if there is Replace() available since Go 1.0?

**Comment by qaisjp** [comment]
Why not use it?

**Comment by shizeeg** [comment]
> Why not use it?

the function provides no additional functionality and was introduced relatively recently. So the function prevents compilation with older Go compilers.

**Comment by 42wim** [comment]
Documentation says clearly go1.12+ required.. I should update this to go 1.14 actually. https://github.com/42wim/matterbridge#building 

Go only supports the two latest versions, older versions aren't supported anymore and can have security issues.

Furthermore ReplaceAll() is more readable and recommended by various linters.
