### ISSUE TITLE
[Slack->Discord] Msg edit sends new message

### ISSUE THREAD

**Issue by irgolic** [42wim/matterbridge#1259]
Looking through the issues, this sounds related to #588, but the issue insinuates that Slack message edits still sometimes get through. Did this break recently, with the new Slack API changes?

**Describe the bug**
On a Slack<->Discord bridge, edited Slack->Discord message are resent (1 message -> 2 messages). 
Meanwhile, when a Discord->Slack message is edited, it is edited on Slack (1 message -> 1 message).

**To Reproduce**
On a Slack<->Discord bridge,
- send a message on Slack
- edit the Slack message
- observe both the original and edited message on Discord

**Expected behavior**
Having sent (and edited) one message on Slack, there shouldn't be two messages on Discord. The original message should be replaced by the edited message on Discord.

**Environment (please complete the following information):**
 - OS: linux 64bit
 - Matterbridge version: 1.17.5 8eb5e3cb

**Additional context**
(please tell me if you can't reproduce this and I'll attach more info)

**Comment by qaisjp** [comment]
This was a technical limitation because webhooks couldn't be edited. There is a new API for this, which is used in #1287
