### ISSUE TITLE
Backslash to Telegram escape character issue

### ISSUE THREAD

**Issue by xenoguy** [42wim/matterbridge#126]
Please answer the following questions. 

### Which version of matterbridge are you using?
0.9.3-dev

### Please describe the expected behavior.
the shrug ascii `¯\_(ツ)_/¯` should be in tact when crossing a running bridge between slack->tg.  Also tested discord->tg

### Please describe the actual behavior. 
`¯\_(ツ)_/¯`
is missing his left arm "\\" when sent across a bridge between slack->tg (also discord->tg)

### Any steps to reproduce the behavior?

I suspect this is an escape character difference specific to Telegram.

**Comment by 42wim** [comment]
Nice one.
It's because of HTML rendering module (github.com/russross/blackfriday) that's used in telegram. If you send ```¯\\_(ツ)_/¯``` it should work ;-)
I'm going to make sending html an option and disable it by default.

**Comment by xenoguy** [comment]
would this have an impact on slack->tg emoji as well?  I just noticed `:slightly_smiling_face:` comes across to TG as the text, and doesn't get converted to emoji.  seems to work tg->slack.

**Comment by 42wim** [comment]
Maybe, I'm not sure. (can't test right now)
You can test yourself with changing the lines here:

https://github.com/42wim/matterbridge/blob/master/bridge/telegram/telegram.go#L125-L126
to

```
m := tgbotapi.NewMessage(chatid, msg.Username+msg.Text)
```
(so removing line126 :)

This disables html and should make your shrug work

**Comment by xenoguy** [comment]
This is confirmed fixed.  I think Emoji to TG isn't working for whatever reason though.  I'll open a separate issue for that though.

Thanks for the quick turnaround!
