### ISSUE TITLE
Discord permission issue (recent change on Discord side?)

### ISSUE THREAD

**Issue by poVoq** [42wim/matterbridge#1264]
**Describe the bug**
Discord stopped accepting my previously working (>1yr) bot with the following error message:

```
time="2020-10-19T21:16:11Z" level=info msg=Connecting prefix=discord
time="2020-10-19T21:16:11Z" level=info msg="Connecting using webhookurl (for posting) and token" prefix=discord
time="2020-10-19T21:16:11Z" level=info msg="Connection succeeded" prefix=discord
time="2020-10-19T21:16:14Z" level=info msg="Can manage webhooks; will edit channel for global webhook on send" prefix=discord
time="2020-10-19T21:16:14Z" level=error msg="Error obtaining server members: HTTP 403 Forbidden, {"message": "Missing Access", "code": 50001}" prefix=discord
time="2020-10-19T21:16:14Z" level=fatal msg="Starting gateway failed: Bridge discord.fgd failed to start: HTTP 403 Forbidden, {"message": "Missing Access", "code": 50001}" prefix=main
```
I already checked all the access permissions, but I can't seem to find anything that might be the issue. And it was working fine before. I also tried going back to older versions of Matterbridge (0.18.1/2) that ran fine previously, but the error remains, thus I am assuming this is something that changed on the side of Discord.

**Environment (please complete the following information):**
 - OS: [e.g. linux] Official docker image
 - Matterbridge version: output of  `matterbridge -version` 0.18.1/2/3

**Comment by 42wim** [comment]
See https://github.com/42wim/matterbridge/wiki/FAQ#error-obtaining-server-members-http-403-forbidden for a solution.
