### ISSUE TITLE
Telegram messages from other bots not sending

### ISSUE THREAD

**Issue by Publish3r** [42wim/matterbridge#1267]
Hello.
I have a matterbrige bot and another bot in my telegram group.
I would like to send the news from my other bot to my whatsapp group, but it's not working.
The matterbridge bot sends messages from human accounts only.
Is it possible to send messages from my "newsbot" too?
Thanks.

**Comment by Mikaela** [comment]
This is sadly a Telegram API limitation so Matterbridge can do nothing to receive messages from bots. See https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots

**Comment by 42wim** [comment]
Closing this as @Mikaela gave the correct answer :)
