### ISSUE TITLE
Slack to Telegram emoji doesn't translate correctly.

### ISSUE THREAD

**Issue by xenoguy** [42wim/matterbridge#127]
Please answer the following questions. 

### Which version of matterbridge are you using?
0.10.0-dev

### Please describe the expected behavior.
Emoji should be translated between protocols when possible.

### Please describe the actual behavior. 
Emoji from slack to telegram is not translated correctly.
`:slightly_smiling_face:` comes across the bridge as the text string.
Discord to Telegram seems to translate correctly.

### Any steps to reproduce the behavior?
Connect a slack to Telegram bridge, and test that emjoi are being correctly translated.

**Comment by 42wim** [comment]
Sorry, this isn't something that I can fix.
Slack gives ```:slightly_smiling_face:``` back and discord gives the real unicode deal ``` 🙂``` back.
You can also see this, when running with ```-debug```

**Comment by 42wim** [comment]
@xenoguy  surprise, I did just fix this now! ;-)
All :emoji: from any bridge will be translated to unicode, so this should fix the telegram issue too.
