### ISSUE TITLE
Embeded images and files bridge fine from Discord to Rocket.Chat, but not the other way around

### ISSUE THREAD

**Issue by unfa** [42wim/matterbridge#1275]
If a user embeds an image or a file into a Discord message, the image or file is accessible on Rocket.Chat.

However if a user posts an image or a file on Rocket.Chat - it's completely invisible to the Discord users.

Is there a way to make the files be posted to Discord a s well? Could Matterbridge post links to Rocket.Chat-hosted images at least?

My Rocket.Chat server provides public links to embeded image and files - would it be possible to send these links to Disocrd, so Discord users can view the contents?

**Comment by 42wim** [comment]
This is not supported  yet, there is a PR for that (https://github.com/42wim/matterbridge/pull/756) but it's stale, feel free to work on it.
Closing in favor of #774
