### ISSUE TITLE
Mattermost Bot or regular / dedicated user?

### ISSUE THREAD

**Issue by ylluminate** [42wim/matterbridge#1277]
[In the instructions](https://github.com/42wim/matterbridge/wiki/Section-Mattermost-(basic)) it mentions creating a "dedicated user":
> Create a dedicated user (a new account specifically for matterbridge) first.
> It will not relay messages from yourself if you use your account

But there are also BOT users within Mattermost now (eg, `mattermost_server.domain.tld/TEAM/integrations/bots`). Is there a way to use this instead of a regular dedicated user via a token or is the user + password still required?

**Comment by zjoasan** [comment]
You have to have administrator privileges on that matter most server, enable bit user https://docs.mattermost.com/administration/config-settings.html#bot-accounts

**Comment by ylluminate** [comment]
I do have this enabled and I created a bot as per the above example URL.  What I didn't see was that I can use a token instead of username + password:
https://github.com/42wim/matterbridge/wiki/Settings#token-1
