### ISSUE TITLE
Bridge whatsapp.mywhatsapp failed to join channel: account doesn't belong to group with jid xxxx-xxxx@g.us

### ISSUE THREAD

**Issue by devloic** [42wim/matterbridge#1278]
**Describe the bug**
My matterbridge config files defines a gateway between a mattermost channel and a whatsapp group.
mattermost crashes and prints:
[0004] FATAL main:         Starting gateway failed: Bridge whatsapp.mywhatsapp failed to join channel: account doesn't belong to group with jid xxxx-xxx@g.us 

**To Reproduce**
configure a mattermost<->whatsapp gateway, start mattermost version: 1.19.1-dev ( 1.19.0 has the same problem)

**Expected behavior**
I expect to have a working gateway between mattermost and whatsapp with the following message:
[0005]  INFO main:         Gateway(s) started succesfully. Now relaying messages

**Screenshots/debug logs**

/home/lolo/bin/go_build_github_com_42wim_matterbridge
[0000]  INFO main:         Running version 1.19.1-dev 
[0000]  INFO main:         WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
[0000]  INFO router:       Parsing gateway mygateway2
[0000]  INFO router:       Starting bridge: whatsapp.mywhatsapp 
[0001]  INFO whatsapp:     whatsapp.mywhatsapp: joining  thisisarealnumber-thisisarealgroupnumber@g.us (ID:  thisisarealnumber-thisisarealgroupnumber@g.uswhatsapp.mywhatsapp)
[0001] FATAL main:         Starting gateway failed: Bridge whatsapp.mywhatsapp failed to join channel: account doesn't belong to group with jid thisisarealnumber-thisisarealgroupnumber@g.us 

**Environment (please complete the following information):**
 - OS: linux zorin os (ubuntu) , heroku (alpine ?)
 - Matterbridge version: version: 1.19.1-dev
 - If self compiled: output of `git rev-parse HEAD` : 0d99766686c2fb25bd31b099a8b03172b99dad96

**Additional context**

I commented line 199 matterbridge/bridge/whatsapp/whatsapp.go 
if _, exists := b.conn.Store.Contacts[channel.Name]; !exists {
//return fmt.Errorf("account doesn't belong to group with jid %s", channel.Name)
and the gateway started working, so there must be a problem in Store.Contacts or so, will investigate further

matterbridge.toml:

[irc]
    [irc.myirc]
    Server="chat.freenode.net:6697"
    Nick="matterbotmynick"
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
    NickServNick="matterbotbot"
    NickServPassword="password"
    UseTLS=true
    UseSASL=true
    SkipTLSVerify=false
    IgnoreNicks=""
    
    
[telegram.mytelegram]
#See https://core.telegram.org/bots#6-botfather 
#and https://www.linkedin.com/pulse/telegram-bots-beginners-marco-frau
Token=""
RemoteNickFormat="({PROTOCOL}) &lt;{NICK}&gt; "
MessageFormat="HTMLNick"

[whatsapp.mywhatsapp]

Number="+mynumber"

SessionFile="session-+mynumber.gob"

QrOnWhiteTerminal=false

RemoteNickFormat="[{PROTOCOL}] @{NICK}: "
    
[mattermost]
  [mattermost.work]
      Server="myherokumattermostapp.herokuapp.com"
      Team="myteam"
      Login="robot-ofmine"
      Password="somepassword"
      NoTLS=false
      SkipTLSVerify=false
      ShowJoinPart=false
      PrefixMessagesWithNick=false
      RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
      NickFormatter="plain"
      NicksPerRow=4
      IgnoreNicks=""

[[gateway]]
name="mygateway"
enable=false
    [[gateway.inout]]
    account="irc.myirc"
    channel="#irc_to_mattermost"

    [[gateway.inout]]
    account="mattermost.work"
    channel="test_matterbridge"

[[gateway]]
name="mygateway2"
enable=true
   [[gateway.inout]]
    account="whatsapp.mywhatsapp"
    channel="mynumber-mygroupname@g.us"

    [[gateway.inout]]
    account="mattermost.work"
    channel="test_matterbridge"

[general]

Plus=true

**Comment by devloic** [comment]
duplicate of : https://github.com/42wim/matterbridge/issues/1122

and https://github.com/Rhymen/go-whatsapp/issues/137#issuecomment-480316013 ( for the Rhymen/go-whatsapp/ part )

You can use their ugly fix 
or if you are sure of your group id just bypass the check because it's useless 
        if _, exists := b.conn.Store.Contacts[channel.Name]; !exists {

**Comment by 42wim** [comment]
closing as it's duplicate
