### ISSUE TITLE
Build/pipeline gitlab messages badly transmitted over irc bridge

### ISSUE THREAD

**Issue by bnjbvr** [42wim/matterbridge#128]
### Which version of matterbridge are you using?
run ```matterbridge -version```

Latest docker image.

### If you're having problems with mattermost please specify mattermost version. 

3.6.0  (3.6.2)

### Any steps to reproduce the behavior?

- set up a gitlab instance.
- create one repository on this instance.
- enable mattermost integration from one gitlab repository.
- use an mattermost <-> irc bridge on the same channel that receives the gitlab notifications.

### Please describe the expected behavior.

Build and pipeline messages should be correctly sent through the irc bridge.

#### Use logs from running ```matterbridge -debug``` if possible.

Empty messages are sent through the bridge for build and pipeline messages. That is, on irc we just see messages of the form "<nickname>".

Perhaps there should just be a rule in matterbridge to **not** transmit empty messages? (I am pretty sure the gitlab notifications may be empty, since they're using a different form of integration there)

Please let me know if you need further information.

#### (be sure to exclude or anonymize private data (tokens/passwords))

I don't think this is relevant here.

**Comment by 42wim** [comment]
I thought this was already fixed, but it seems not :-)
Empty messages from any bridge should now be dropped. 
(docker image is being updated)

**Comment by bnjbvr** [comment]
Thank you!
