### ISSUE TITLE
ReplaceNicks bug in rewrite algorithm?

### ISSUE THREAD

**Issue by ylluminate** [42wim/matterbridge#1280]
I have a scenario where the following is the case:

Two Discord users:
1. username: `mynickname`
2. username: `anothernickname`

Two Mattermost users:
1. username: `john` ; nickname: `John`
2. username: `john2` ; nickname: `John II`

I am attempting to map the following:
For Discord config, I have:
```
ReplaceNicks=[ ["mynickname","John"], ["anothernickname","John II"] ]
```

For Mattermost config, I have:
```
ReplaceNicks=[ ["John","mynickname"], ["John II","anothernickname"] ]
```
Whenever we send messages from Discord to Mattermost the nickname translation works fine, for example: `anothernickname` shows up as `John II` in Mattermost.

Whenever we send messages from Mattermost to Discord, we have a problem.  In this error case `John II` is rendered as `mynickname II` in Discord!

This is a rather confusing situation and it appears that something must be off algorithmically in the translation of these two from Mattermost to Discord.

Any ideas about this problem?

**Comment by 42wim** [comment]
The is sequential and first match will win
So `ReplaceNicks=[ ["John","mynickname"], ["John II","anothernickname"] ]` will replace `John` => `mynickname` and `II` remains `II`, so you'll get `mynickname II`.

For this specific case, probably just changing it to `ReplaceNicks=[ ["John II","anothernickname"], ["John","mynickname"] ]` will fix it.

**Comment by ylluminate** [comment]
Still having some trouble here with this - but it seems to be a bit more twisted than I initially believed it to be. Going to try to document this further and really put all the brass tacks to it in order to isolate the issue.

**Comment by ylluminate** [comment]
Alright so let's ask an intermediary question perhaps or at least something else that is going on: Can MatterBridge translate nicknames that are in messages? So if there is a `Hey @mynickname how are you?` is there a way to get it to show up as `Hey @John how are you?` in Mattermost?

**Comment by 42wim** [comment]
You can use replacemessages for that: https://github.com/42wim/matterbridge/wiki/Settings#replacemessages
