### ISSUE TITLE
Connecting to Mattermost with the WebhookURL option doesn't seem to allow traffic from Webhook to other app (IRC in my case)

### ISSUE THREAD

**Issue by data-dude** [42wim/matterbridge#1285]
**Is your feature request related to a problem? Please describe.**

I've setup Matterbridge with IRC and Mattermost, whereas Mattermost is configured using the WebhookURL.  It works sending data from IRC to Mattermost, but not the other way.

**Describe the solution you'd like**

I'd like to send data from Mattermost to IRC using the WebhookURL configuration option (not username and password).
Also, I don't have the option to use anything other than the WebhookURL.

**Comment by 42wim** [comment]
No it can't work the other way because it's only an incoming webhook.
For the other way you need an outgoing webhook from mattermost and the config here https://github.com/42wim/matterbridge/wiki/Settings#webhookbindaddress or username/password or token login.
