### ISSUE TITLE
Same channel gateway requires # prefix for IRC channels, but breaks Slack with #

### ISSUE THREAD

**Issue by lukespragg** [42wim/matterbridge#129]
### Which version of matterbridge are you using?
0.10.0-dev

### Please describe the expected behavior.
In/out communication between same named channels.

### Please describe the actual behavior. 
When using [[samechannelgateway]], the IRC channel will only work if prefixed with #, but if you prefix the channel with #, it breaks communication with Slack.

### Any steps to reproduce the behavior?
Setup [[samechannelgateway]] with IRC and Slack. #name required for IRC, name for Slack using Slack API, not webhooks.

### Please add your configuration file 
```
[[samechannelgateway]]
    name = "IRC Esper"
    enable = true
    accounts = [ "irc.esper", "slack.wulf" ]
    channels = [ "flow" ]
```

**Comment by 42wim** [comment]
Yes good point, but as stated in the "documentation" (matterbridge.toml.sample) it only works for bridges where the channelnames are the same.  (eg mattermost/slack)

I'll see if I can fix this by also allowing irc channels to be specified without "#"-prefix

But as a workaround you could use
```
[[gateway]]
name="IRC Esper"
enable=true
    [[gateway.inout]]
    account="irc.esper"
    channel="#flow"
    [[gateway.inout]]
    account="slack.wulf"
    channel="flow"
```

Ofcourse for lots of channels this is some more config.

**Comment by lukespragg** [comment]
Thanks @42wim, that's what I'm using right now as the same channel didn't work.

**Comment by 42wim** [comment]
Requires too much extra complexity.
Not going to be implemented by me.
