### ISSUE TITLE
Signal-messenger integration

### ISSUE THREAD

**Issue by osm-frasch** [42wim/matterbridge#1290]
Hello , short question in the round. 
Is it planned or even possible to integrate/bridge the signal messenger into Matterbridge? 

The signal messenger is becoming more and more popular, is open source, enjoys the highest level of trust, end-to-end encryption, easy to use and offers almost the same features as Whatsapp

It would be great if this could be done

**Comment by 42wim** [comment]
Not planned, PR's welcome.
See https://github.com/42wim/matterbridge/issues/28 for more info.
