### ISSUE TITLE
Getting 403 Forbidden from Azzure while trying to connect to teams

### ISSUE THREAD

**Issue by thacool** [42wim/matterbridge#1291]
When Launching the matterbidge up it connects to mattermost and try get and send messages to Teams gettig 403 Forbidden

I get this messages in journald

Nov 13 19:55:51 mattermost matterbridge[13071]: time="2020-11-13T19:55:51Z" level=error msg="SendMessage failed: 403 Forbidden: {"error":{"code":"Forbidden","message":"Forbidden","innerError":{"client-request-id":"...","date":"2020-11-13T19:55:51","request-id":"...
Nov 13 19:55:53 mattermost matterbridge[13071]: time="2020-11-13T19:55:53Z" level=error msg="polling failed for ...@thread.skype: 403 Forbidden: {"error":{"code":"Forbidden","message":"Forbidden","innerError":{"client-request-id":"...","date":"2020-11-1

 - OS: Ubuntu 20.04
 - Matterbridge version: version: 1.19.0 2bb21262

Config looks like 

[msteams.teams]
TenantID="..."
ClientID="..."
TeamID="..."
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[mattermost.mymattermost]
#The mattermost hostname. (do not prefix it with http or https)
Server="server_fqdn:443"

#the team name as can be seen in the mattermost webinterface URL
#in lowercase, without spaces
Team="someteam"

#login/pass of your bot.
#Use a dedicated user for this and not your own!
Login="bot.somebot"
Password="password"

RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
PrefixMessagesWithNick=true

[[gateway]]
name="gw"
enable=true

[[gateway.inout]]
account = "mattermost.mymattermost"
channel = "mm-channel"

[[gateway.inout]]
account="msteams.teams"

**Comment by 42wim** [comment]
You must follow the instructions exactly on https://github.com/42wim/matterbridge/wiki/MS-Teams-setup

**Comment by tmotyl** [comment]
@42wim  its not possible to follow instructions exactly, as the azure interface looks different, then it's shown on the screens.
E.g. you can't put redirect uri directly on the "authentication" page, but first you need to select the application type.

**Comment by 42wim** [comment]
@tmotyl you could run with `-debug`

Seems like the `@thread.tavc2` are newer ones, but it's not hardcoded in matterbridge so should work also.

You also got this popup with exact the same permissions?
https://user-images.githubusercontent.com/1810977/71424430-b5c63280-2691-11ea-8aa9-ababae5b7a6a.png

**Comment by tmotyl** [comment]
@42wim ive added debug setting to the msteams config section, but it did not yeald anything useful. I will try with -debug

When approving permissinons (on admin account) there was no popup afair they just went „green” after clicking approve button.

**Comment by tmotyl** [comment]
Would it be possible to get a paid support /debugging session from you to get this issue solved?

**Comment by tmotyl** [comment]
@42wim I've checked again, and I do not get any popup when approving permissions on azure (using admin account). But all permissions are "green" and "granted".

**Comment by chessmonster** [comment]
I'm also encountering this error. In my case the only discrepancy is that this page is not seen anymore: https://github.com/42wim/matterbridge/wiki/MS-Teams-setup#set-application-as-public-client

Closest option for this is the option in Advanced settings. I just assumed this is the same thing, but is it?
![image](https://user-images.githubusercontent.com/4256454/105769711-2e847600-5f99-11eb-9cce-a36dd0d46d0d.png)

**Comment by 42wim** [comment]
I've finally found some time to try and start a teams environment from scratch.

The multitenant option isn't usable anymore for non-businesses since November 9th 2020.

![image](https://user-images.githubusercontent.com/1810977/106069211-5f33ef00-6102-11eb-8c8f-1f1d2a6f13ef.png) which links to [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/publisher-verification-overview).

So I've created a new tenant and signed up for teams, create the application for that single tenant and granted permissions.
And I can now reproduce your issue, but with another error for me:

```
polling failed for 19:8baf567xxxxxxxxxxxxxxxxxxxx82794@thread.tacv2: 403 Forbidden: {"error":{"code":"Forbidden","message":"Failed to get license information for the user. Ensure user has a valid Office365 license assigned to them.","innerError":{"client-request-id":"3fe3254a-2683-4578-bc1a-8584c68fc137","date":"2021-01-27T23:37:44","request-id":"3fe3254a-2683-4578-bc1a-8584c68fc137"}}}.
```

So it seems like as I don't have a office 365 license or setup, I can't get any further in debugging this.


It also seems they changed the needed permissions for reading messages/channels, one thing that you could try is to add these permissions:
`ChannelMessage.Read.All`
`ChannelMessage.Send`
`Channel.ReadBasic.All`
`ChannelSettings.Read.All`

If this has no result, I think you should contact your domain admin and/or microsoft to help you debug the permission issue, this is not something I can help you any further with.

**Comment by chessmonster** [comment]
alright thank you @42wim. I will request additional permissions from our admin and update here if it worked,

**Comment by sep76** [comment]
hello 

i notice your configuration do not have a channel definition. I installed mine today by following the instructions, and it works.
the gateway part looks like 

[[gateway.inout]]
account="msteams.teams"
channel="19:**********************f@thread.tacv2"

you get the link of the channel the same way you get the link of the team.

**Comment by sep76** [comment]
another tripwire is that  if you grab the link via copy link on the 3 dots, and not via the address bar in the browser
you get it with the format 19%3a29 instead of 19:29   This can be an issue for both the team and the channel.

**Comment by chessmonster** [comment]
@42wim after the permissions were provided I'm still getting the same error. I'll review the steps that I did to set this up. @sep76 thanks for letting me know. I think I do have some issues with my setup (described in [1373](https://github.com/42wim/matterbridge/issues/1373#issuecomment-768653029)) if it does work for you.

**Comment by am1ru1** [comment]
> hello
> 
> i notice your configuration do not have a channel definition. I installed mine today by following the instructions, and it works.
> the gateway part looks like
> 
> [[gateway.inout]]
> account="msteams.teams"
> channel="19:**********************f@thread.tacv2"
> 
> you get the link of the channel the same way you get the link of the team.

is your MSTeams integration still works today?
@tmotyl @chessmonster @sep76

**Comment by VA2XJM** [comment]
Here is the solution I used to solve the "bug" and makes it work. I can confirm you it is not on the Microsoft side.

1. Setup everything like it is indicated in the docs including permissions (https://github.com/42wim/matterbridge/wiki/MS-Teams-setup)
2. Just after "ClientID and TenantID", create a new user dedicated for Matterbridge. Note the password
3. Assign the new user as owner of the API.
4. Start Matterbridge. Register your API with URL and key indicated by Matterbridge. Use your matterbridge dedicated user to register the API. You will see an error in Matterbridge indicating forbidden OR no office365 license) 
5. Log into Teams with the Matterbridge dedicated user (web based version is OK). Set the profile information.
6. Now get to office.com and log with the Matterbridge dedicated user to obtain Office365 license.
7. Restart Matterbridge and it should works!

Enjoy!
