### ISSUE TITLE
IconURL doesn't seem to support redirects

### ISSUE THREAD

**Issue by lukespragg** [42wim/matterbridge#130]
### Which version of matterbridge are you using?
0.10.0-dev

### Please describe the expected behavior.
Icon to be obtained from the URL, which works in a browser.

### Please describe the actual behavior. 
When using a URL such as https://github.com/{NICK}.png?size=32 for IconURL, the icon never is obtained. I believe this is from the URL being redirected in this case to a domain such as https://avatars0.githubusercontent.com/u/123456?v=3&s=32.

### Any steps to reproduce the behavior?
Set IconURL to https://github.com/{NICK}.png?size=32 and test using any gateway.

### Please add your configuration file 
IconURL="https://github.com/{NICK}.png?size=32"

**Comment by lukespragg** [comment]
Found a URL doesn't redirect and works, so no rush. ;)

https://avatars.githubusercontent.com/{NICK}?size=32

**Comment by 42wim** [comment]
Matterbridge gives the url as-is to the backends.
It's the application itself (slack, mattermost, discord) which should do the redirecting.
