### ISSUE TITLE
Two Matrix users can use the same display name and Matterbridge makes no distinguishion

### ISSUE THREAD

**Issue by Mikaela** [42wim/matterbridge#1302]
**Describe the bug**

Two users at Matrix set the same display name and Matterbridge shows them both the same way.

**To Reproduce**

1. Join a Matterbridged room using two accounts.
2. Run `/myroomnick Nick` as both.
3. Send messages to the room using both accounts.

**Expected behavior**

Generally Matrix clients (Element) resolve this by showing the MXID in brackets after duplciate display names:

* Nick (@account2:example.net)
* Nick (@account1:example.com)

**Screenshots/debug logs**

* ![image](https://user-images.githubusercontent.com/831184/99910948-cfd12080-2cf9-11eb-930b-86f3f82e8e33.png)
  * This screenshot could be a bit better as one Element didn't yet notice the other using the same name while clearing cache would likely bring out the brackets due to collision.
* ![image](https://user-images.githubusercontent.com/831184/99910953-db244c00-2cf9-11eb-9a1b-d4b524626020.png)
* Debug log: N/A

**Environment (please complete the following information):**
 - OS: Linux
 - Matterbridge version: v1.20.0

**Additional context**

I think this was introduced by https://github.com/42wim/matterbridge/pull/1282, CC: @nightmared. Otherwise thank you for making Matrix users more readable through Matterbridge, this has been waited for 👍🏻

**Comment by nightmared** [comment]
Hmm you're right, that's definitely a big problem. I should be able to make a fix in a day or two. Thanks for CC-ing me ;)
