### ISSUE TITLE
Feature Request : reply from mattermost to IRC and maybe other bridge

### ISSUE THREAD

**Issue by valvin1** [42wim/matterbridge#131]
Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
version: 0.9.3 cd0a2be 

### Desciption of the request
When we reply on a message on Mattermost side there is no effect on IRC side. It sends only the message as it. 

On some other bridge system it exists a feature which sends the message on which we are replying in quotes then the message we are sending. When the origin message is too it can be shorten with `...` 

This feature should be interesting what do you think of it ?

**Comment by 42wim** [comment]
Yes, sounds interesting.
What other bridge system uses it?

**Comment by varod** [comment]
seems to be this one : https://github.com/FruitieX/teleirc
i'm not using it, just see people who are using it on #pepper&carrot channel

**Comment by 42wim** [comment]
This is unfortunately too expensive to do, mattermost doesn't give the message you're replying on to the bot. That means that for every message we would need to do a call to mattermost to find the parent of the message.

**Comment by valvin1** [comment]
thank you :)

**Comment by 42wim** [comment]
implemented
