### ISSUE TITLE
Rocketchat: irc timeout after receiving x amount of messages from IRC

### ISSUE THREAD

**Issue by kimmoal** [42wim/matterbridge#1312]
**Describe the bug**
RocketChat integration is crashing matterbridge when the RocketChat SDK has processed enough IRC messages. I am now testing whether this is due to RocketChat SDK generating poor random ids for messages with duplicate ids.

Example of a poor random id generated by Matterbridge seen in the direct link to a message:
`https://rocketchat.example.com/group/testing?msg=0.609882`

Native client generated "true" random id:
`https://rocketchat.example.com//group/testing?msg=xffqwMDvqdgpfe38F`

Unfortunately this is a vendor run matterbridge instance so I cannot provide any debug output at this time. Maybe later.

Thank you!

**To Reproduce**
- Bridge RocketChat channel to an IRC channel
- Send x amount of messages from IRC to RocketChat
- Matterbridge crashes (disconnects  from IRC)

**Expected behavior**
No crashes / disconnects

**Comment by 42wim** [comment]
Disconnect from irc is not a crash though.

Without debug logs I can't really do much, in another issue we traced irc disconnects to a discord bridge getting ratelimited which caused the irc bridge blocking and got a ping timeout because of that. See #1255 and #1300

**Comment by kimmoal** [comment]
This is the only log I can observe, and it is apparently a crash of the binary, not a ping timeout. The bot is clearly restarting the connection and joining back:
```
12:19 -!- rocket [~rocket@rocketchat.com] has quit [Read error: Input/output error]
12:19 -!- rocket [~rocket@rocketchat.com] has joined #channel
```
Sorry for not providing proper debug logs!

**Comment by kimmoal** [comment]
Okay got some logs now, looks to be the same as #992 but we can manage to have the bot connected for 1 - n messages, it is not crashing straight away.
```
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 141 [running]:
github.com/matterbridge/Rocket.Chat.Go.SDK/realtime.(*Client).SendMessage(0xb029560, 0xaeae1e0, 0x16, 0x0, 0x0)
/go/pkg/mod/github.com/matterbridge/!rocket.!chat.!go.!s!d!k@v0.0.0-20200411204219-d5c18ce75048/realtime/messages.go:44 +0x198
github.com/42wim/matterbridge/bridge/rocketchat.(*Brocketchat).Send(0xb032b40, 0xaf68000, 0x8a, 0xafd16b0, 0x6, 0xae72d00, 0x11, 0xae8e240, 0x25, 0x0, ...)
/go/src/github.com/42wim/matterbridge/bridge/rocketchat/rocketchat.go:176 +0x44c
github.com/42wim/matterbridge/gateway.(*Gateway).SendMessage(0xad53d70, 0xaf89030, 0xb032ac0, 0xad4b1c0, 0x0, 0x0, 0xc, 0xade9520, 0x17, 0xade9520)
/go/src/github.com/42wim/matterbridge/gateway/gateway.go:457 +0x586
github.com/42wim/matterbridge/gateway.(*Gateway).handleMessage(0xad53d70, 0xaf89030, 0xb032ac0, 0x5d9, 0xa782d00, 0x0)
/go/src/github.com/42wim/matterbridge/gateway/handlers.go:226 +0x1e3
github.com/42wim/matterbridge/gateway.(*Router).handleReceive(0xb0329c0)
/go/src/github.com/42wim/matterbridge/gateway/router.go:152 +0x1a1
created by github.com/42wim/matterbridge/gateway.(*Router).Start
/go/src/github.com/42wim/matterbridge/gateway/router.go:102 +0x76f

main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by 42wim** [comment]
Should be fixed in master (together with your random ID patch).

**Comment by kimmoal** [comment]
Yes seems like it is working, thanks!
