### ISSUE TITLE
Integrating Matterbabble (Discourse support)

### ISSUE THREAD

**Issue by sunjam** [42wim/matterbridge#1334]
Wondering on if Matterbabble / Discourse post integration could be added into Matterbridge itself.  Currently resides at https://github.com/DeclanHoare/matterbabble

Thanks for considering!

**Comment by qaisjp** [comment]
Not without rewriting, as matterbabble is written in Python, and matterbridge is written in Go.

Also, as far as I know, Discourse doesn't really have any realtime chat, and I don't think matterbridge usually integrates non-chat things (but wim can say whether or not that's okay 🙂).

**Comment by DeclanHoare** [comment]
FWIW Discourse does update topics live while you're on the page, even though it's normally formatted like a bulletin board.  I made the plugin to use with Discourse Babble, which adds a shoutbox that is just a reformatted topic.

**Comment by sunjam** [comment]
Nice. Unfortunately, babble has gone unmaintained and is now considered
broken on meta discourse due to unresolved bugs.

https://meta.discourse.org/t/babble-a-chat-plugin/87297/124

**Comment by 42wim** [comment]
Going to close this, as the babble plugin on discourse itself is broken/unmaintained. 
Ofcourse, this issue can be reopened if it gets fixed.

**Comment by sunjam** [comment]
Update, the Babble plugin has been fixed.  [Community is still in the process of finding a new maintainer](https://meta.discourse.org/t/babble-a-chat-plugin/87297/124).  I'll post here once someone volunteers (fixing issues on Babble is a paid job).
