### ISSUE TITLE
Unable to find gitter roomID

### ISSUE THREAD

**Issue by jck** [42wim/matterbridge#135]
Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
version: 0.9.3 cd0a2be

#### Use logs from running ```matterbridge -debug``` if possible.
ERRO[2017-03-15T22:29:16-04:00] Could not find roomID for myhdl/myhdl         module=gitter

#### (be sure to exclude or anonymize private data (tokens/passwords))
[irc]
    [irc.freenode]
    Server="irc.freenode.net:6667"
    Nick="myhdl-bot"

[gitter]
    [gitter.myhdl]
    Token="REDACTED"

[[gateway]]
name="mygateway"
enable=true
    [gateway.inout]]
    account="irc.freenode"
    channel="#myhdl"

    [[gateway.inout]]
    account="gitter.myhdl"
    channel="myhdl/myhdl"

**Comment by 42wim** [comment]
The room has to exist before you can join it. Create it on gitter.im
I've fixed this in master so that it bails out now when it tries to join a channel that doesn't exist.

**Comment by jck** [comment]
The room does exist!
https://gitter.im/myhdl/myhdl

**Comment by 42wim** [comment]
Hm, that's strange. I just succesfully connected my bridge to your channel.
Going to retry with 0.9.3

**Comment by 42wim** [comment]
Also ok with v0.9.3
You do use the token from https://developer.gitter.im/apps ?

**Comment by jck** [comment]
Yes, I use the token from that page.

```
INFO[2017-03-16T21:11:38-04:00] Starting bridge: gitter.myhdl                
INFO[2017-03-16T21:11:38-04:00] Connecting                                    module=gitter
INFO[2017-03-16T21:11:39-04:00] Connection succeeded                          module=gitter
```
But it can never find the room. I will try building it from source instead of using the binary.

**Comment by jck** [comment]
This is what I get after `go get` ing.

```
INFO[2017-03-16T21:15:26-04:00] gitter.myhdl: joining myhdl/myhdl            
FATA[2017-03-16T21:15:26-04:00] Starting gateway failed &errors.errorString{s:"Bridge gitter.myhdl failed to join channel: Could not find roomID for myhdl/myhdl. Please create the room on gitter.im"} 
```

**Comment by 42wim** [comment]
@jck found the issue. You couldn't join a room that wasn't joined already by the bot :/
Should be fixed now, if you do a ```go get -u``` in your repo

**Comment by jck** [comment]
On v0.10.1, I'm indefinitely stuck on `joining channel`

**Comment by 42wim** [comment]
could you please:
* run with ```--debug```
* try saying something on the bridged IRC channel (after you see the message ```joining channel```
* paste the output here

**Comment by jck** [comment]
My bad, seems like I needed to wait longer. It works now.

Thank you so much for fixing this!

**Comment by 42wim** [comment]
Great to hear!
