### ISSUE TITLE
Allow changing or disabling the "\<clipped message\>" message on long lines

### ISSUE THREAD

**Issue by Mikaela** [42wim/matterbridge#1359]
**Is your feature request related to a problem? Please describe.**

I don't like seeing the "\<clipped message\>" message as I think it can mostly be figured out from context and it's so long as opposed to something like `…`.

**Describe the solution you'd like**

I would like to be able to change or disable the "\<clipped message\>" message like changing the edit message is possible with the `EditSuffix` option.

**Describe alternatives you've considered**

I haven't thought of other alternatives.

**Additional context**

This might also be regression of `MessageSplit=true` having broken at some point judging by https://github.com/42wim/matterbridge/issues/281#issuecomment-346903684.

I am running Matterbridge 1.21.0 cf13fff7 and am also using `EditSuffix=" ✏️"` (which inspires me to try to change it).

**Comment by jzvi12** [comment]
Any updates on this? My users usually send long messages and this is a bit annoying
