### ISSUE TITLE
Does not find its configuration file

### ISSUE THREAD

**Issue by probonopd** [42wim/matterbridge#136]
### Which version of matterbridge are you using?

0.10.1 936bccc

### Please describe the expected behavior.

Launches

> Copy the matterbridge.toml.sample to matterbridge.toml in the same directory as the matterbridge binary.

### Please describe the actual behavior. 

```
$ ./bin/matterbridge-linux64 
INFO[2017-03-22T00:57:49+01:00] Running version 0.10.1 936bccc               
2017/03/22 00:57:49 open matterbridge.toml: no such file or directory
```

### Any steps to reproduce the behavior?

Put matterbridge-linux64 and matterbridge.toml into a bin/ directory and run the binary from outside of that directory

**Comment by 42wim** [comment]
I think it's normal that it should look in the CWD, not in the directory where the binary is launched.
Most programs I know work like this. Do you have examples that do otherwise ?

**Comment by probonopd** [comment]
When I launch this matterbridge using a launcher, then I don't even know what cwd is...

**Comment by 42wim** [comment]
You specify the full path with ```-conf /path/to/yourconfig/matterbridge.toml ```

**Comment by probonopd** [comment]
...which means that I'd have to write a launcher script for it, oh well.

**Comment by 42wim** [comment]
AFAIK this is normal behaviour for applications with config files. Any examples that doesn't follow this rule ?

**Comment by probonopd** [comment]
The issue is fixed for me by having written a wrapper script. Still the README.md reads differently.
