### ISSUE TITLE
Matterbridge not working (kind of)

### ISSUE THREAD

**Issue by borjita2019** [42wim/matterbridge#1369]
**Describe the bug**
Whatsapp sends to telegram works, but in discord doesn't appear, then when i try sending a message on whatsapp or discord, it doesn't send it to any gateway

**To Reproduce**
idk

**Expected behavior**
Discord, whatsapp and telegram received and sended mesagges fine

**Screenshots/debug logs**
![image](https://user-images.githubusercontent.com/63255187/105562960-2effe100-5cfb-11eb-9c66-b477886cecee.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Matterbridge version: 1.21.0 cf13fff7
 - If self compiled: No.

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))
https://pastebin.com/raw/zVHKWG8Q
Already edited 'public/general' to 'general'

**Comment by 42wim** [comment]
```
[[gateway.inout]]
account="discord.mydiscord"
channel_name="public/general"
```

`channel_name` is incorrect, must be `channel`

Also are you sure it should be public? did you create a category public?

**Comment by borjita2019** [comment]
now it works!, but another issue i have is that when i send something from whatsapp to discord and telegram, it doesn't work

**Comment by borjita2019** [comment]
looks like its the message type not implemented error...

**Comment by borjita2019** [comment]
and the post was writed badly, i am not that english

**Comment by borjita2019** [comment]
in the whatsapp to telegram works, i was meaning telegram to whatsapp works

**Comment by borjita2019** [comment]
but whatsapp to telegram and discord doesn't work

**Comment by 42wim** [comment]
Can you try a dev build from here: https://github.com/42wim/matterbridge/actions/runs/506061796#artifacts ?
Or click here for a windows 64-bit dev build: https://github.com/42wim/matterbridge/suites/1886212919/artifacts/36864225

**Comment by borjita2019** [comment]
already tried that build before

**Comment by 42wim** [comment]
You can not have tried that build, it only exists since an hour ago ..

**Comment by borjita2019** [comment]
yeah i have tried that before, i checked the actions tab because there's some projects that in the actions tab they upload the dev version of the project, but before that i checked the pull requests, it was at 6, when i comed back to check it was at 7, so i checked it and then checked the actions tab, btw this is the log https://pastebin.com/raw/8hPiM3yt sended some messages and didnt appear in the log

**Comment by 42wim** [comment]
can you try this version: https://github.com/42wim/matterbridge/actions/runs/506180640#artifacts it should dump the whole message that causes the " message type not implemented"

**Comment by borjita2019** [comment]
https://pastebin.com/raw/yuqYvciy

**Comment by 42wim** [comment]
welp, no idea. Can you try to disable "auto-delete" as suggested in https://github.com/42wim/matterbridge/issues/1337#issuecomment-749488299 ?
Any difference?

**Comment by 42wim** [comment]
closing this in favor of #1337 as we're talking about the same, feel free to paste response on my latest question here, but for further follow-up do it in the other issue.

**Comment by borjita2019** [comment]
IT WAS SO SIMPLE, JUST SEND A MESSAGE IN ANOTHER PHONE WITH A DIFERRENT NUMBER, and i think you made this so there's no loop
