### ISSUE TITLE
Feature request i think...

### ISSUE THREAD

**Issue by borjita2019** [42wim/matterbridge#1371]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the feature**
Is it possible for some dev to create a phone linker for matter bridge?, and add calls for the platforms that support group call (or at least discord for test)

**Describe alternatives you've considered**
Link whatsapp to call people on whatsapp (not possible i think)

**Additional context**
If someone adds this, i will thank him A LOT, because i want to call my whatsapp friend (he has a phone number so i can call him by phone too), but when he registered on discord he heared us but he cant unmute mic

**Comment by 42wim** [comment]
out of scope for matterbridge
