### ISSUE TITLE
how grant security

### ISSUE THREAD

**Issue by DoctorSubtilis** [42wim/matterbridge#1375]
### Environment
 KDE Neon
 Mattermost Running version 1.21.0 cf13fff7

Operating system:
KDE Neon

I wonder how to keep my privacy avoiding to give my matrix user and password: how can I do?

**Comment by qaisjp** [comment]
You should create a new account for the bridge.

**Comment by DoctorSubtilis** [comment]
Yes, so I did. Thanks.
