### ISSUE TITLE
when matterbridge is working?

### ISSUE THREAD

**Issue by DoctorSubtilis** [42wim/matterbridge#1377]
This i s a newbie question: I need a PC active to get matterbridge active?  
When I switch off the PC, matterbridge doesn't work any more?

**Environment (please complete the following information):**
 - Linux KDE Neon 
 - Matterbridge version: 1.2

**Comment by qaisjp** [comment]
Correct, if you're running matterbridge on your personal computer, your PC needs to be running for the bridge to work.

People often have a VPS or something and run matterbridge on there.

$5/month on DigitalOcean: https://www.digitalocean.com/pricing/

**Comment by DoctorSubtilis** [comment]
Yes, thank you.
