### ISSUE TITLE
how avoid to show the bot username?

### ISSUE THREAD

**Issue by DoctorSubtilis** [42wim/matterbridge#1379]
how avoid, when I reply to someone whatsapp user (within matrix), to show in whatsapp this ugly code `<@my-bot:matrix.org>`?  

**To Reproduce**
- replay to someone in whatsapp group within (bridged) matrix  
- your answer appears prefixed with an ugly `<@my-bot:matrix.org>`

**Expected behavior**
Only my nick should appear (as happen when a _post_ something)

**Environment (please complete the following information):**
 - OS: KDE Neon (Linux)
 - Matterbridge version: 1.2

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))
   `RemoteNickFormat="<{NICK}>" `  
   `ReplaceNicks=[ ["<@my-bot:matrix.org>","[myname]"] ]`  
   `NoHomeServerSuffix=true`

**Comment by Vetgans** [comment]
I'm using the same bridge, matrix <-> whatsapp, with
`RemoteNickFormat="MyNameIsNick via Element.io/Matrix/WhateverYouWant: \r\n \r\n"`
in the [whatsapp.mywhatsapp]-part (as in https://github.com/42wim/matterbridge/wiki/Section-WhatsApp-%28basic%29)

The ` \r\n \r\n`-part is to create a line-break and make things (in my opinion) look better.
No ReplaceNicks- or NoHomeServerSuffix-line is used.

**Comment by DoctorSubtilis** [comment]
No, doesn't work. When I replay, appears always this annoying <@my-bot:matrix.org>

**Comment by 42wim** [comment]
please add your complete config file (be sure to exclude or anonymize private data (tokens/passwords))

**Comment by DoctorSubtilis** [comment]
Here you are:  

`[matrix.mymatrix]
#Server is your homeserver (eg https://matrix.org)
Server="https://matrix.org"

#login/pass of your bot.
#Use a dedicated user for this and not your own!
#Messages sent from this user will not be relayed to avoid loops.
Login="my-bot"
Password="[mypsw]"

#RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
RemoteNickFormat="<{NICK}>"
#ReplaceNicks=[ ["<@duns-bot:matrix.org>","Francesco"] ]
PrefixMessagesWithNick=false
StripNick=true
UseUserName=true

#Whether to send the homeserver suffix. eg ":matrix.org" in @username:matrix.org
#to other bridges, or only send "username".(true only sends username)
#OPTIONAL (default false)
NoHomeServerSuffix=true

[whatsapp.main]
#Number you will use as a relay bot. Tip: Get some disposable sim card, don't rely on 
#your own number.
Number="+[mynumber]"

#First time that you login you will need to scan QR code, then credentials will be saved in 
#a session file. 
#If you won't set SessionFile then you will need to scan QR code on every restart.
#optional (by default the session is stored only in memory, till restarting matterbridge)
SessionFile="session-[number].gob"

#If your terminal is white we need to invert QR code in order for it to be scanned properly
#optional (default false)
QrOnWhiteTerminal=false
#Messages will be seen by other WhatsApp contacts as coming from the bridge. Original nick will be part of the message.
#RemoteNickFormat=" "
RemoteNickFormat="<{NICK}>"

#name1n
[[gateway]]
name="name1n"
enable=true

[[gateway.inout]]
account="whatsapp.main"
channel="[channel1]@g.us"

[[gateway.inout]]
account="matrix.mymatrix"
channel="#[name1]:matrix.org"

#[name2n]
[[gateway]]
name="[name2n]"
enable=true

[[gateway.inout]]
account="whatsapp.main"
channel="[channel2]@g.us"

[[gateway.inout]]
account="matrix.mymatrix"
channel="#[name2]:matrix.org"

#SdC Terzi
[[gateway]]
name="name3n"
enable=true

[[gateway.inout]]
account="whatsapp.main"
channel="[channel3]@g.us"

[[gateway.inout]]
account="matrix.mymatrix"
channel="#[name3]:matrix.org"

#coro
[[gateway]]
name="[name4n]"
enable=true

[[gateway.inout]]
account="whatsapp.main"
channel="[channel4]@g.us"

[[gateway.inout]]
account="matrix.mymatrix"
channel="#[name4]:matrix.org"

#dottorandi
[[gateway]]
name="name5n"
enable=true

[[gateway.inout]]
account="whatsapp.main"
channel="[channel5]@g.us"

[[gateway.inout]]
account="matrix.mymatrix"
channel="#[name5]:matrix.org"
`

**Comment by 42wim** [comment]
Can you please upgrade to latest version ? 
Matterbridge 1.2 is very old

**Comment by DoctorSubtilis** [comment]
Today I upgraded to the 1.22 release. But I was inaccurate: I said 1.2, but in fact it was the 1.21.

**Comment by Vetgans** [comment]
> #ReplaceNicks=[ ["<@duns-bot:matrix.org>","Francesco"] ]

Did you copy-paste the configuration file? `ReplaceNicks` is commented out here...

**Comment by DoctorSubtilis** [comment]
> > #ReplaceNicks=[ ["<@duns-bot:matrix.org>","Francesco"] ]
> 
> Did you copy-paste the configuration file? `ReplaceNicks` is commented out here...

Thanks, I will try

**Comment by 42wim** [comment]
Did this work?

**Comment by DoctorSubtilis** [comment]
> Did this work?

Unfortunately no :(

**Comment by fossgeek** [comment]
I suggest you create a new config. This should get you going, paste it in a new matterbridge.toml file:

```
[matrix.mymatrix]
Server="https://matrix.org"
Login="USERNAME BOT"
Password="PASSWORD BOT"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
NoHomeServerSuffix=true

[whatsapp.mywhatsapp]
Number="YOUR PHONE NUMBER"
SessionFile="session-48111222333.gob"
QrOnWhiteTerminal=false

[[gateway]]
name="matrix <-> whatsapp"
enable=true

[[gateway.inout]]
account="matrix.mymatrix"
channel="YOUR ROOM"

[[gateway.inout]]
account="whatsapp.mywhatsapp"
channel="YOUR JID CODE"
```

This should eliminate the ugly codes in whatsapp, yet keep them in Matrix so that you know from whom the messages sent to you come.
Let me know if this doesn't work.

**Comment by steadfasterX** [comment]
the above example code still showing 

~~~
> <@botname:homeserver.org>
here comes the content I quoted
~~~

The following fixed that for me (matrix section in config):

`ReplaceMessages=[ ["<@botname:homeserver.org>",""] ]`
