### ISSUE TITLE
HTMLDisable for Matrix adds empty `format` and `formatted_body` fields

### ISSUE THREAD

**Issue by bkil** [42wim/matterbridge#1382]
**Describe the bug**
If we enable HTMLDisable, messages will not be visible for the miniVector Android Matrix client. Upon closer inspection of the event JSON, the text message is encapsulated in `body`, but the pruned `format` and `formatted_body` fields are not removed, they are included with an empty string value.

**To Reproduce**

- Set up a bridge between Matrix and something else (like IRC)
- Join the Matrix room using miniVector (may also affect other clients)
- Enable HTMDisable on the matrix gateway
- Send a message from IRC
- Observe that miniVector shows a message without text, can also be verified when clicking `... -> View Source` on the message in Element Web

**Expected behavior**
If we disable HTML formatting, the fields `format` and `formatted_body` should be removed completely.

- See: https://matrix.org/docs/spec/client_server/r0.5.0#m-text

**Environment (please complete the following information):**
 - OS: Linux
 - Matterbridge version: 1.21.0 cf13fff7

**Additional context**
```
[irc.myirc]
Server="chat.freenode.net:6697"
Nick="nick"
UseTLS=true

[matrix.mymatrix]
Server="https://matrix.org"
Login="nick"
Password="password"
HTMLDisable=true #### ####

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="irc.myirc"
channel="#htmldisabletest"

[[gateway.inout]]
account="matrix.mymatrix"
channel="#htmldisabletest:matrix.org"
```

**Comment by rgegvre** [comment]
Could be related to #1671 ?!
