### ISSUE TITLE
lost messages

### ISSUE THREAD

**Issue by DoctorSubtilis** [42wim/matterbridge#1392]
**Describe the bug**
I'm not sure if it is my fault, but so far I didn't manage to have whatsapp's messages sent when matterbridge is inactive (between my PC connections).  
There is a way to get that messages?  

**To Reproduce**
When for any reason matterbridge becomes inactive, you loss all the messages sent by others whatsapp members (in that period).  

**Expected behavior**
I wish to get all whatsapp messages, even sent in periods of (my) matterbridge inactivity.  

**Environment (please complete the following information):**
 - OS: Linux KDE Neon
 - Matterbridge version: 1.22

**Comment by 42wim** [comment]
This is not possible

**Comment by DoctorSubtilis** [comment]
> This is not possible

but is _real_, unfortunately. _It happens_ to me.  
How should I do to avoid it?  
My config file is already posted  in [another post](https://github.com/42wim/matterbridge/issues/1379#issuecomment-771331572).  
Thank you!

**Comment by 42wim** [comment]
I mean matterbridge doesn't support this, you need to have matterbridge running, it only supports realtime messages.

**Comment by DoctorSubtilis** [comment]
Ah, ok. I see. Thanks.
