### ISSUE TITLE
IRC channel name parsing

### ISSUE THREAD

**Issue by waelk10** [42wim/matterbridge#1400]
Bug Description:
Any IRC channel name given to the bot is parsed in all lower-case chars, thus making the bot unable to join channels that have uppercase chars in their name.

Can be reproduced by configuring channels whose names contain uppercase chars.

Expected behavior is having the bot attempt to join the channel with the name given in the config file left as is.

As for the environment:
GNU/Linux, Kernel: 5.10.6
Matterbridge version: 1.22.0

**Comment by 42wim** [comment]
irc channels are case insensitive

**Comment by qaisjp** [comment]
The below lines were added #348:

https://github.com/42wim/matterbridge/blob/858cdc86f58a4be0f8aca2ed325ad57398fb8339/gateway/gateway.go#L171-L174

**Comment by 42wim** [comment]
I'm curious what ircd is causing this @waelk10 ?
@qaisjp depending on the reasons it could be a bug report yes :)

**Comment by waelk10** [comment]
ngircd that is, version 26.

**Comment by 42wim** [comment]
Sorry not going to add case-sensitive parsing, going to cause issues with existing setups
