### ISSUE TITLE
Telegram edits are not sent properly

### ISSUE THREAD

**Issue by dbrgn** [42wim/matterbridge#141]
Please answer the following questions. 

### Which version of matterbridge are you using?

Docker 42wim/matterbridge:0.10.2

## Problem

I set up a Mattermost - Telegram bridge.

When someone edits a message in Telegram, the original message arrives twice in Mattermost. The edited message never appears.

This is what matterbridge should receive from Telegram.

```json
{
    "update_id": XXX,
        "message": {
            "message_id": 18,
            "from": {
                "id": XXX,
                "first_name": "User X",
                "username": "usrx"
            },
            "chat": {
                "id": -XXX,
                "title": "Bot Dev",
                "type": "group",
                "all_members_are_administrators": true
            },
            "date": 1490651580,
            "text": "Test"
        }
},
{
    "update_id": XXX,
    "edited_message": {
        "message_id": 18,
        "from": {
            "id": XXX,
            "first_name": "User X",
            "username": "usrx"
        },
        "chat": {
            "id": -XXX,
            "title": "Bot Dev",
            "type": "group",
            "all_members_are_administrators": true
        },
        "date": 1490651580,
        "edit_date": 1490651586,
        "text": "Test edited again"
    }
}
```

**Comment by 42wim** [comment]
I've made some changes for this, but I can't test telegram myself.
I see you're using docker, could you try running with 42wim/matterbridge:latest and let me know if it's fixed for you ?
Thanks!

**Comment by dbrgn** [comment]
@42wim thanks, editing now sends a new message to IRC and Mattermost!

Would it also be possible to actually apply the edit as an edit in supported chat systems (e.g. Mattermost)? Or to mark it as edited with some text prefix?

**Comment by 42wim** [comment]
Yes, that's something I'm planning on looking into.
For the short-term it'll work like this, I'll see if I can add a parameter to have EditedPrefix in the config so you can choose your prefix message.

**Comment by 42wim** [comment]
@dbrgn Actually applying the edit unfortunately doesn't seem feasible. Matterbridge would have to keep state and would only be able to edit messages that are created when it runs.

So I've chosen to make edits compatible for all protocols by appending a suffix to the edited text.
For this I've add 2 new keywords, ```EditDisable``` and ```EditSuffix```. 
By default edited messages are sent, but can be disabled by sending ```EditDisable=true```
By default edited messages are not appended, but you can set ```EditSuffix=" (edited)"``` to add (edited) at the end of the message

```
#Disable sending of edits to other bridges
#OPTIONAL (default false)
EditDisable=false

#Message to be appended to every edited message
#OPTIONAL (default empty)
EditSuffix=" (edited)"
```
Pushing now als to 42wim/matterbridge:latest on dockerhub

**Comment by dbrgn** [comment]
Seems to work nicely.
