### ISSUE TITLE
Is there a way to specify the timeout of messages being relayed?

### ISSUE THREAD

**Issue by JEK58** [42wim/matterbridge#1411]
I'm using matterbridge for relaying WhatsApp to telegram. 

If the WA device is in flight mode for some time and brought back online it does not relay the new messages to telegram. Any idea? I did look through the code but di not find something timeout related…

**Comment by 42wim** [comment]
No, you need to keep the bridge running.

**Comment by JEK58** [comment]
Hm, the bridge is of course running all the time. But the device not.
