### ISSUE TITLE
Extra space between nick and message

### ISSUE THREAD

**Issue by ExTechOp** [42wim/matterbridge#142]
### Which version of matterbridge are you using?
version: 0.10.2 4a25e66

### Please describe the expected behavior.
Setting RemoteNickFormat in the configuration file to have one trailing space is expected to produce just one space between nick and relayed message.

### Please describe the actual behavior. 
Messages relayed between irc and xmpp work fine, with one space between nick and relayed message.
Messages relayed from Mattermost to irc and xmpp work fine, also with one space.
Messages relayed from either irc or xmpp to Mattermost have two spaces between the nick and relayed message, in this case the bridge seems to be inserting an extra space.

### Please add your configuration file
I believe the only relevant configuration item is setting RemoteNickFormat:
`RemoteNickFormat="[{NICK}] "`

**Comment by 42wim** [comment]
Good catch, fixed in master. (and will be in 0.11.0-beta1)
