### ISSUE TITLE
[Keybase -> Discord] Edited Messages Not Showing

### ISSUE THREAD

**Issue by goyle** [42wim/matterbridge#1420]
**Describe the bug**
Edited messages in Keybase are not shown in Discord.

**To Reproduce**
I have Discord bridged to Keybase.
I have set EditDisable to `false` and EditSuffix to `" (edited")` in the settings.

**Comment by 42wim** [comment]
It's not supported by the library we use, feel free to open an issue there (https://github.com/keybase/go-keybase-chat-bot/)
I've added it also to the FAQ  https://github.com/42wim/matterbridge/wiki/FAQ#keybase
