### ISSUE TITLE
XMPP --> Telegram 

### ISSUE THREAD

**Issue by dossidr** [42wim/matterbridge#1421]
**Describe the bug**
[0040] ERROR Gateway: 

**To Reproduce**
Send an Messages from Gajim or Conversations to Telegram.
Using XMPP User and XMPP MUC.

Send an Message from Telegeram to XMPP.
Using Group and BOT attached to be handle.

Telegram --> XMPP is working well

**Expected behavior**
no transfer from XMPP --> Telegram. It sticks inside Matterbridge.
Debug Information set an tag failure. See Log Description.

**Screenshots/debug logs**
Debug log:
`[0064] ERROR gateway:      [handleMessage:gateway/handlers.go:228] SendMessage failed: Bad Request: can't parse entities: Unsupported start tag **"mb"** at byte offset 7`

**Environment (please complete the following information):**
 - OS: Debian Buster 
 - Matterbridge version: matterbridge-1.22.0-linux-64bit
 - matterbrdige.toml.....
`[telegram.mytelegram]
Token="xxxxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
MessageFormat="HTMLNick"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
[xmpp.myxmpp]
Server="rohland-home.de:5222"
Jid="**mb**@rohland-home.de"
Password="xxxxxxx"
Muc="conference.rohland-home.de"
Nick="mbBOT"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
############################################################################
[general]
LogFile="/tmp/matterbridge.log"
################################################################################
[[gateway]]
name="gateway1"
enable=true
[[gateway.inout]]
account="xmpp.myxmpp"
channel="matterbridge"
[[gateway.inout]]
account="telegram.mytelegram"
channel="-xxxxxxxxxxx`

**Additional context**

**Comment by Humorhenker** [comment]
I have experienced the same problem. The cause was the "<" in RemoteNickFormat for Telegram from the default config.
The bug is probably in the way the telegram handler encodes the nick.
But for a quick workaround you should be able to just change the RemoteNickFormat for Telegram an you should be fine.

**Comment by MrDrache333** [comment]
The thing is that the encoding of the Message is HTML and HTML Tags are decoded by the `<` and '>' Symbols. Just leave them out or use some other symbols solved the Problem for me.

**Comment by Humorhenker** [comment]
I updated the telegram wiki entry to avoid this error in the future.
Think this issue can be closed now.

**Comment by 42wim** [comment]
@Humorhenker thanks!

**Comment by dykstranet** [comment]
I also encountered this problem. Removing `<...>` solved it. I think it is better if Matterbridge enforces that there is no `<...>` in `RemoteNickFormat` when using Telegram.
