### ISSUE TITLE
Discord id channel

### ISSUE THREAD

**Issue by mentalisit** [42wim/matterbridge#1422]
**Is your feature request related to a problem? Please describe.**
discord channels only in Latin 

**Describe the solution you'd like**
Use channel id instead of channel name

**Comment by qaisjp** [comment]
Please could you elaborate? It's already possible to specify channel by ID, just prefix with `ID:`

**Comment by mentalisit** [comment]
SendMessage failed: Could not find channelID for

**Comment by mentalisit** [comment]
> Please could you elaborate? It's already possible to specify channel by ID, just prefix with `ID:`

tried it, it doesn't work

**Comment by mentalisit** [comment]
channel="ID:1234567890" 
working
