### ISSUE TITLE
Telegram: Animated sticker conversion assumes linux

### ISSUE THREAD

**Issue by BenWiederhake** [42wim/matterbridge#1423]
**Describe the bug**

Running on any platform where `/dev/stdout` is not available causes lottie to fail. This will happen on Windows, probably MacOS, and locked-down Linuxes (e.g. Android, as I learned today).

**To Reproduce**

- Install Matterbridge on Android
- Configure it to convert Tgs to PNG
- Run
- Send an animated sticker across the bridge

**Expected behavior**

Converted sticker arrives on the other end

**Screenshots/debug logs**

"Exit code: 1"

**Environment (please complete the following information):**
 - OS: Android (apparently uses SELinux/AppArmor/whatever to deny any access to `/dev`)
 - Matterbridge version: doesn't matter

**Comment by BenWiederhake** [comment]
!assign: self

**Comment by mentalisit** [comment]
thanks for your fix.  your version works on my device without problems
