### ISSUE TITLE
WhatsApp audio message panik

### ISSUE THREAD

**Issue by mentalisit** [42wim/matterbridge#1427]
**Describe the bug**
bridge crash when sending audio message

**To Reproduce**
Audio message 

**Expected behavior**
Audio transmission file

**Screenshots/debug logs**
panic: runtime error: index out of range [0] with length 0

goroutine 1048 [running]:
github.com/42wim/matterbridge/bridge/whatsapp.(*Bwhatsapp).HandleAudioMessage(0x40006cc300, 0x4002c01860, 0x20, 0x4002c01840, 0x1c, 0x4002c018e0, 0x1b, 0x0, 0x6050d4fd, 0x0, ...)
        /data/data/com.termux/files/home/matterbridge/bridge/whatsapp/handlers.go:292 +0x654
created by github.com/Rhymen/go-whatsapp.(*Conn).handleWithCustomHandlers
        /data/data/com.termux/files/home/matterbridge/vendor/github.com/Rhymen/go-whatsapp/handler.go:248 +0x578

**Environment (please complete the following information):**
 - OS: android /termux
 - Matterbridge version: 1.22

**Comment by 42wim** [comment]
This should be fixed in master now
