### ISSUE TITLE
Message from IRC to Discord got truncated

### ISSUE THREAD

**Issue by mangblekok** [42wim/matterbridge#143]
Please answer the following questions. 

### Which version of matterbridge are you using?
version: 0.10.3 02d7e2d

### Please describe the expected behavior.
The message from IRC to Discord is get cut, so not all characters get delivered to DIscord.

### Please describe the actual behavior. 
The username length is 10 characters.
This user send 1 long message from IRC, 468 characters.
In Discord side, we can only read 435 characters.
If including the username length, the message received in DIscord will be 449 characters.
--> <0123456789>: message....449

### Please add your configuration file
[discord.myserver]
Server="ServerName"
RemoteNickFormat="<{NICK}>: "
ShowJoinPart=false

[irc]
[irc.freenode]
Server="irc.freenode.net:6667"
RemoteNickFormat="<{NICK}>: "

In the Gateway, I use both channel as "inout".

**Comment by 42wim** [comment]
Nice catch, this doesn't get checked anywhere.
I'll have to find out the limits for every bridge and see that it get chopped up in newlines if it exceeds the limit.

**Comment by 42wim** [comment]
@mangblekok It seems that discord has a 2000 character limit. IRC has a much smaller limit though. So you are probably experiencing the IRC limit, and not the discord limit.
