### ISSUE TITLE
Whatsapp / message type not implemented on "ephemeral messages"

### ISSUE THREAD

**Issue by proceau** [42wim/matterbridge#1432]
The message on ephemeral channel, it's see with "message type not implemented"

Create Channel
Activate ephemeral option on channel ( ex: 7 day )
Add bridge normaly
When Message it's sent Matterbridge: "message type not implemented"

On debug:
ERROR whatsapp:     [HandleError:bridge/whatsapp/handlers.go:40] message type not implemented

 - OS: linux/debian
 - Matterbridge version: 1.22.0

**Comment by 42wim** [comment]
Take a look #1337 and https://github.com/42wim/matterbridge/issues/1337#issuecomment-779475072
I'm getting mixed messages from people, some say it works, other say it doesn't work

**Comment by proceau** [comment]
I'm look all issues on whatsapp :)
when the feature it's disable, bridge works, reenable stop relay ( whatsapps => matterbrigde ), if need more information, tell me, or grow debug information ( what methode ) ?

**Comment by 42wim** [comment]
@proceau this is not something I can fix, we're using the https://github.com/Rhymen/go-whatsapp library, and apparently it doesn't understand/support those messages. Can you open an issue there about adding support for ephemeral messages?

Thanks
