### ISSUE TITLE
[Matrix -> Whatsapp] Place sender above image  

### ISSUE THREAD

**Issue by Vetgans** [42wim/matterbridge#1434]
Not a big problem, but perhaps easy to fix:

When sending an image from Whatsapp to Matrix, the sender is mentioned first and the image is placed underneath, as is customary in most apps.

When sending an image from Matrix to Whatsapp however, the image is posted first and the sender is mentioned underneath/afterwards. Of course this is not a big problem, but it doesn't look as nice and can be confusing sometimes. 

Edit:
I can't change the label from 'bug' to 'enhancement'...

**Comment by 42wim** [comment]
This can't be fixed in matterbridge, we're using the underlying whatsapp library to upload those images.
