### ISSUE TITLE
Join/Parts from Mumble

### ISSUE THREAD

**Issue by s3m1s0n1c** [42wim/matterbridge#1435]
Is it possible to add Join/Part messages from mumble to any bridge system?

Eg> From Mumble -> Telegram?

Thanks
Sonic

**Comment by xnaas** [comment]
Would be awesome for this info to get passed through with `ShowJoinPart=true` like several other bridges.

**Comment by xnaas** [comment]
I was looking at the code that the IRC module uses: https://github.com/42wim/matterbridge/blob/44d182e2f93b5652a3e7595030a2f61f1453fdc5/bridge/irc/handlers.go#L84-L135 )

Unfortunately, I don't think that would immediately translate for Mumble. Would have to be something a little more complex written, I think. I don't really know/understand golang at all, though, so. 😢

**Comment by s3m1s0n1c** [comment]
Yeah you would have to look @ gumble and see if u can get the same functions from it..

I had a quick look but couldn't make heads or tails of it..

**Comment by s3m1s0n1c** [comment]
*Boop* 

Any ideas? 

I can't for the life of me work it out..

something to do with

```func (b *Bmumble) handleDisconnect(event *gumble.DisconnectEvent) { ```

How do I sent to whatever bridge is active?

I'm trying to send it to telegram so I can see if a user joins/parts server/channel

**Comment by s3m1s0n1c** [comment]
@s3lph Hey Man,

Any chance you can add so when someone join/parts mumble it notifies on Telegram?

Thanks
Sonic

**Comment by s3lph** [comment]
Implemented in #1915.

I've only tested this between Mumble and IRC, not with Telegram. But since join/part messages are bridge-agnostic and are handled and forwarded by the gateway, this should work as long as the Telegram bridge can shows join/part messages at all.
