### ISSUE TITLE
IRC Bold or Colorize Nick

### ISSUE THREAD

**Issue by peylight** [42wim/matterbridge#1439]
**Describe the bug**
I want to Bold or Colorize Nick in IRC.
I try to add ASCII code like `\x02{NICK}\x02` to the `RemoteNickFormat` but it is not working

**To Reproduce**
try to add ASCII code like `\x02{NICK}\x02` to the `RemoteNickFormat`

**Expected behavior**
I except for IRC nickname should be Bold

**Environment (please complete the following information):**
 - OS: [linux]
 - Matterbridge version: latest docker version

**Additional context**

**Comment by qaisjp** [comment]
Try pasting the exact symbol into RemoteNickFormat, instead of using escape codes.

**Comment by peylight** [comment]
@qaisjp 
I test all of these type:
```
x02{NICK}x02
\x02{NICK}\x02
\\x02{NICK}\\x02
```
None of it works.

**Comment by peylight** [comment]
I found it.
`\u0002{NICK}\u0002`

**Comment by 42wim** [comment]
Also there is a `ColorNicks` option: https://github.com/42wim/matterbridge/wiki/settings#colornicks
