### ISSUE TITLE
From discord to telegram but not telegram to discord

### ISSUE THREAD

**Issue by borjita2019** [42wim/matterbridge#1443]
**Is your feature request related to a problem? Please describe.**
No

**Describe the function you'd like**
I want a option so i can send from discord to telegram but not viceversa

**Comment by 42wim** [comment]
This already exists, instead of using ```[[gateway.inout]]``` use ```[[gateway.in]]``` to only receive from this gateway or ```[[gateway.out]]``` to only send to this gateway.
