### ISSUE TITLE
IRC -> Discord mentions are not working

### ISSUE THREAD

**Issue by barbequesauce** [42wim/matterbridge#1445]
**Describe the bug**
Seems similar to #460. @username strings sent from IRC are not converted to mentions in Discord.

**To Reproduce**
Running 1.22.0 Linux armv6.

**Expected behavior**
String comes through as text.

**Screenshots/debug logs**
<img width="385" alt="Screen Shot 2021-04-03 at 8 29 48 AM" src="https://user-images.githubusercontent.com/25070944/113478426-c483c380-9456-11eb-90c4-61f357320230.png">
https://shrimpandgrits.net/linx/26jkat9m.log

**Environment (please complete the following information):**
 - OS: Raspbian Jessie
 - Matterbridge version: version: 1.22.0 afcd362c

**Additional context**
https://shrimpandgrits.net/linx/u6txfnvz.toml

**Comment by qaisjp** [comment]
What is the username of "offspring" on the Discord side?

**Comment by barbequesauce** [comment]
His username is Offspring. I can confirm that it's not working when the case sensitive version is used as well.

**Comment by 42wim** [comment]
I can not reproduce this, also your log file doesn't exist anymore.
