### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by mentalisit** [42wim/matterbridge#1449]
Sending custom emoji over Discord Bridge

**Comment by mentalisit** [comment]
@c0ncord2  help me

**Comment by qaisjp** [comment]
over discord to which platform?

**Comment by mentalisit** [comment]
> из-за разногласий к какой платформе?

to any (telegram, Watsapp) Even on discord comes this :
:emoji_1: :emoji_11: :emoji_17:

**Comment by qaisjp** [comment]
WhatsApp doesn't have custom emoji. What kind of behaviour are you looking for?

**Comment by mentalisit** [comment]
> WhatsApp doesn't have custom emoji. What kind of behaviour are you looking for?

i use a lot of discord bridges and would like to be able to send custom emoji over the bridge

**Comment by mentalisit** [comment]
if I understand the logic of the script correctly, then it says that url images will be sent instead of emoji

**Comment by mentalisit** [comment]
https://github.com/42wim/matterbridge/blob/master/contrib/outmessage-discordemoji.tengo

**Comment by qaisjp** [comment]
That script should work for the functionality you're looking for. What kind of other behaviour are you looking for?

**Comment by mentalisit** [comment]
> That script should work for the functionality you're looking for. What kind of other behaviour are you looking for?

I cannot find the function of the variable $ 1. either it is missing or faulty

**Comment by qaisjp** [comment]
Have you tested the script? What kind of error message are you getting? What do you expect to see, and what do you actually get?

**Comment by mentalisit** [comment]
I was confident in the settings, so I started looking for problems in the code by version. Downloaded 5 different versions.
Bottom line: in version matterbridge-1.17.0

**Comment by mentalisit** [comment]
![IMG_20210411_012642](https://user-images.githubusercontent.com/64618228/114286200-58601b80-9a65-11eb-8d2a-da26219e2572.jpg)
![IMG_20210411_012533](https://user-images.githubusercontent.com/64618228/114286202-59914880-9a65-11eb-96e0-e2007a5c17bb.jpg)

**Comment by mentalisit** [comment]
@qaisjp  help me

**Comment by computeronix** [comment]
Although this request is generic, to be more specific, Discord allows you to create custom emojis

I would like to +1 this to be able to send custom emojis over the bridge to lets say TG

for example, when a custom emoji is sent would it be possible to upload it as a PNG and send over a picture where it would more supported?

**Comment by 42wim** [comment]
@computeronix you could use/modify the script to do whatever you want wrt to emoji replacement.

For more info, read here: https://github.com/42wim/matterbridge/wiki/tengo
