### ISSUE TITLE
Matterbridge not replacing icon or username on MatterMost

### ISSUE THREAD

**Issue by Infernoman** [42wim/matterbridge#145]
Please answer the following questions. 

### Which version of matterbridge are you using?
version: 0.9.3 cd0a2be

### Please describe the expected behavior.
Matterbridge should replace the Icon and Username for the person speaking from IRC or slack when using the API for mattermost.

### Please describe the actual behavior. 
When i connect matterbridge to mattermost in API mode, it doesnt replace the username of the bot, or the icon. When I connect matterbridge to mattermost in webhook mode to a single channel it replaces the username but not the icon.

### Please add your configuration file 
```
[irc]
    [irc.freenode]
    Server="irc.freenode.net:6667"
    Nick="CRW-MatterBridge"
    PrefixMessagesWithNick=true
    IgnoreNicks="travis-ci"

[mattermost]
    [mattermost.work]
        useAPI=true
        Server="SERVER"
        Team="TEAM"
        Login="LOGIN"
        Password="PASSWORD"
        IconURL="https://robohash.org/{NICK}.png?size=48x48"

    [mattermost.webhook]
        BindAddress="0.0.0.0:9999"
        IconURL="https://robohash.org/{NICK}.png?size=48x48"
        URL="WEBHOOK"

[slack]
    [slack.hobby]
    useAPI=true
    Token="TOKEN"
    IconURL="https://robohash.org/{NICK}.png?size=48x48"

[general]
RemoteNickFormat="{NICK}<{PROTOCOL}>"

# General Channels
[[gateway]]
name="mygateway"
enable=true
    [[gateway.inout]]
    account="irc.freenode"
    channel="#crowncoin"

    [[gateway.inout]]
    account="mattermost.webhook"
    channel="town-square"

    [[gateway.inout]]
    account="slack.hobby"
    channel="general"

# Slack / Mattermost Gateways
[[samechannelgateway]]
   enable = true
   accounts = [ "mattermost.work","slack.hobby" ]
   channels = [ "altcoins","core-dev-team","developer-general","developer-marketing","github-latest","help","random","testing"]
```

**Comment by 42wim** [comment]
That's a limitation in mattermost, using the API cannot change username or iconurl (with slack this is possible). 

Using the webhook replaces username and iconurl. But there is a bug there, I just found out, it actually always uses this ```https://robohash.org/%7BNICK%7D.png?size=48x48``` as image (NICK substitution doesn't work). Is this what you're seeing also ?

**Comment by Infernoman** [comment]
Currently the iconURL even with webhook isnt changing the icon of the user at all just using the default.

http://prntscr.com/eta1tu

Also is there any way to use the outgoing webhook in more than one channel, without having a trigger word?

**Comment by 42wim** [comment]
About the iconURL, did you follow the docs on https://docs.mattermost.com/developer/webhooks-incoming.html#creating-integrations-using-incoming-webhooks ? 

specifically: ```With Enable integrations to override profile picture icons turned on, you can similarly change the icon the message posts with by providing a link to an image in the icon_url parameter of your payload. ``` 
If the admin doesn't enable this in the system console the iconurl can't be overridden.

About the outgoing webhook, don't know. 
The webhook sends the channel to matterbridge, so if you can use the outgoing webhook in mattermost in more than one channel. Matterbridge should be able to handle this. 

Test it out :-) try running matterbridge with ```-debug``` to see what happens.

**Comment by 42wim** [comment]
Fixed the nick substitution bug in master. Please reopen if you still have the issue after enabling the "override profile picture" in my previous message and the latest code. This fix will be in the next 0.11.0-beta3 release.

**Comment by Infernoman** [comment]
just wondering if you may be able to provide some insight to adding discord into the mix. icons are added correctly going from discord->slack and discord->mattermost. but slack->discord and mattermost->discord show as a bot user.

[discord]
    [discord.game]
    Token="API-TOKEN"
    IconURL="https://robohash.org/{NICK}.png?size=48x48"
    Server="Crown"

The bot has an administrator role with the ability to manage roles. but still shows the messages coming from slack and mattermost as a "bot" user.

Screenshot for reference.
http://prntscr.com/f4q5xz

**Comment by Infernoman** [comment]
and one more thing, that i've noticed that could be a bug or just possibly not the correct support needed from mattermost. when messaging from mattermost -> slack using the webhook. slack does not display the users profile picture but the iconUrl assigned even when the user has a profile picture assigned.
http://prntscr.com/f4qa0d

I remember you mentioning that mattermost didnt have the support needed to change the iconurl and username using the api. so i figured it may be another limitation from mattermost?
