### ISSUE TITLE
Allow using mattermost channel ids

### ISSUE THREAD

**Issue by steBracKa** [42wim/matterbridge#1454]
**Is your feature request related to a problem? Please describe.**
Changing the link of a channel in Mattermost breaks the bridge configuration.

**Describe the solution you'd like**
change `func (b *Bmattermost) JoinChannel(channel config.ChannelInfo)` in matterbridge/bridge/mattermost/mattermost.go to allow to use channel id in matterbridge.toml

**Describe alternatives you've considered**
Always changing matterbridge.toml.
This is very annoying if users are allowed to change channel urls in mattermost and thus break all bridges.

**Additional context**
This could alleviate the problem: https://github.com/42wim/matterbridge/issues/1455

**Comment by 42wim** [comment]
> change func (b *Bmattermost) JoinChannel(channel config.ChannelInfo) in matterbridge/bridge/mattermost/mattermost.go to allow to use channel id in matterbridge.toml

if it is that easy, please do it :-)
