### ISSUE TITLE
IRC Reconnect on channel kick

### ISSUE THREAD

**Issue by elberfeld** [42wim/matterbridge#146]
If the Bridge is kicked from an IRC channel, IRC stays disconnected until the bridge is restarted.
It would be nice if the bridge could reconnect automaticly (perhaps after a specified backoff time).

**Comment by ExTechOp** [comment]
A similar issue is that Matterbridge won't reconnect to Mattermost if gets thrown out. For example we set our "Session length AD/LDAP and email" parameter to be one day, but Matterbridge doesn't understand its been kicked and never reconnects. Our solution is to daily restart it by cron in the early morning hours.

**Comment by 42wim** [comment]
@ExTechOp I don't have an enterprise mattermost, but I just added a commit that restarts connection when  mattermost isn't responding to PINGs anymore. I think this should fix your issue.

**Comment by 42wim** [comment]
@elberfeld Just added a commit so that bot rejoins the channel when kicked. I'll be releasing v0.11.0-beta3 which contains that commit. Please test out and re-open when still an issue.
