### ISSUE TITLE
.jpe images from WhatsApp dont show in Discord

### ISSUE THREAD

**Issue by adanielvv** [42wim/matterbridge#1463]
**Describe the bug**
.jpe images (default from WhatsApp) don't show inline in the Discord app, they are shown as .jpe attachments.

**To Reproduce**
Send a .jpe file from any other bridged application (WhatsApp sends images as .jpe by default)

**Expected behavior**
Images from WhatsApp show inline in Discord

**Possible fix**
Rename every .jpe file to .jpg incoming into Discord, or rename every outgoing image file from WhatsApp
Like done here https://github.com/42wim/matterbridge/issues/906#issuecomment-741793512 and here https://github.com/42wim/matterbridge/issues/1292

**Comment by 42wim** [comment]
fixed in master
