### ISSUE TITLE
Suppress join messages from Mattermost

### ISSUE THREAD

**Issue by ExTechOp** [42wim/matterbridge#147]
### Which version of matterbridge are you using?
version: 0.11.0-dev 33dffd5

### Please describe the expected behavior.
Please add a configurable parameter to suppress join messages from the Mattermost end.

### Please describe the actual behavior. 
Bot relays messages like "bot: [username] username has joined the channel." to irc/xmpp when a new user logs in to Mattermost.

**Comment by 42wim** [comment]
Fixed in master. 
By default join/leave messages from mattermost are now hidden. To enable use ```showjoinpart=true``` on the receiving bridge config.
