### ISSUE TITLE
Support Bot Tokens/Identifiers for Multiple Gateways

### ISSUE THREAD

**Issue by computeronix** [42wim/matterbridge#1474]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When creating multiple gateways, it would be ideal to reference the same Discord/Telegram config, but selecting different bot tokens/identifiers so each channel that is bridged by its own gateway has its own bot doing this work.

**Describe alternatives you've considered**
In the meantime creating a whole separate config for Telegram/Discord and referencing it per Gateway in the config.

**Comment by 42wim** [comment]
Sorry, not going to implement this
