### ISSUE TITLE
Nickserv join delay too fast for liberachat

### ISSUE THREAD

**Issue by dbrgn** [42wim/matterbridge#1478]
**Describe the bug**

Right now, the IRC bridge waits 5 seconds after registering with nickserv.

https://github.com/42wim/matterbridge/blob/714a2ad7303f0d7b51b8b7f6c5f86f02a99c3524/bridge/irc/handlers.go#L147

Unfortunately it seems that libera.chat - which is currently under high load due to lots of registrations and many spambots - is sometimes too slow to reply. A join request to a `+r` channel will then fail silently, the bridge never joins.

**To Reproduce**

Maybe you can reproduce this by bridging a `+r` channel on irc.libera.chat.

If that works (because the load was reduced), set the delay to 0 in the IRC code and try again.

**Expected behavior**

Joining after auth should work. The "join success" detection should probably be more intelligent.

If joining a channel fails, an error should be logged. (Currently there's none.)

**Possible solutions**

- Quickfix: Increase delay to 10 seconds
- Perma-temporary fix: Make nickserv delay configurable
- Clean fix: Detect the success message by nickserv, and only join the channels once that succeeded (instead of using a fixed delay)

Independently:

- If joining a channel fails (due to any reason), log a message.
- If joining a channel fails (due to any reason), retry using exponential backoff (or a similar algorithm)

**Comment by DarthGandalf** [comment]
No, clean fix is to login using SASL instead of messaging Nickserv

**Comment by anthonylavado** [comment]
I agree with using SASL.

I just had to enable it because if the originating IP address where Matterbridge is hosted, but it has solved my issues regarding authentication and identifying to LC.

**Comment by dbrgn** [comment]
When I tried, SASL didn't work, but that may have been fixed in the meantime.

**Comment by anthonylavado** [comment]
They seemed to start doing it yesterday, so definitely things are moving fast: https://libera.chat/guides/sasl

**Comment by 42wim** [comment]
As SASL seems to be working now on liberachat, I suggest using this.
PR's to improve this as suggested by @dbrgn are welcome.

**Comment by dbrgn** [comment]
Yep, SASL auth works now!
