### ISSUE TITLE
Disabling Threading On Slack

### ISSUE THREAD

**Issue by shoeplexben** [42wim/matterbridge#1479]
Would like to request adding a complete disabling of thread posts from slack to discord and vice versa. Would this be possible?

**Comment by 42wim** [comment]
you mean like https://github.com/42wim/matterbridge/wiki/Settings#preservethreading ?

**Comment by shoeplexben** [comment]
> you mean like https://github.com/42wim/matterbridge/wiki/Settings#preservethreading ?

No, when I set preserve threading to false, it does nothing except post thread replies as [thread]: 

I want it to completely disable threads. I don't want it to post them at all. Is this possible?

**Comment by 42wim** [comment]
It's not in matterbridge at the moment, but you could fix this using tengo :-) 
https://github.com/42wim/matterbridge/wiki/tengo

Using something like below (not tested)

```
[tengo]
OutMessage="yourscript.tengo"
```

yourscript.tengo containing:

```
text := import("text")
if inProtocol == "slack" {
    if contains(msgText,"[thread]") {
       msgDrop=true
   }
}
```

**Comment by shoeplexben** [comment]
> It's not in matterbridge at the moment, but you could fix this using tengo :-)
> https://github.com/42wim/matterbridge/wiki/tengo
> 
> Using something like below (not tested)
> 
> ```
> [tengo]
> OutMessage="yourscript.tengo"
> ```
> 
> yourscript.tengo containing:
> 
> ```
> text := import("text")
> if inProtocol == "slack" {
>     if contains(msgText,"[thread]") {
>        msgDrop=true
>    }
> }
> ```

Says  modifySendMessageTengo: Compile Error: unresolved reference 'contains' at (main):3:8

Tried all the other configs in https://github.com/42wim/matterbridge/wiki/tengo

Doesn't seem to work

**Comment by shoeplexben** [comment]
any update on this?

**Comment by 42wim** [comment]
try `text.contains`

**Comment by shoeplexben** [comment]
> try `text.contains`

Doesn't filter it out
