### ISSUE TITLE
Custom Discord emotes are not transliterated correctly

### ISSUE THREAD

**Issue by jleclanche** [42wim/matterbridge#148]
Here's an example:

```
[discord] <Buckethead> writing bash scripts on windows <:LUL:229765547787550720>
```

What it should probably look like instead:

```
[discord] <Buckethead> writing bash scripts on windows :LUL:
```

It's a best effort and all, but at least removing the ID is probably worth it :)

**Comment by 42wim** [comment]
Damn, just too late for the 0.11.0 release :-)
I'll take a look

**Comment by jleclanche** [comment]
hahaha sorry, I've been meaning to file this issue for ages ;)

**Comment by jleclanche** [comment]
2017-04-11T19:51:15Z
2017-04-11T19:51:23Z

Wow you weren't kidding huh.

**Comment by 42wim** [comment]
Fixed in master, you know the drill :)
