### ISSUE TITLE
Support appending text to Discord chat message

### ISSUE THREAD

**Issue by computeronix** [42wim/matterbridge#1482]
**Describe the solution you'd like**
Add support for appending text to a Discord message as part of the bridge.  For example, if I have the bot listening on an announcement channel, every Telegram message that comes in through the bridge to Discord, I would like Discord to append "@everyone" to flag everyone in the server.

**Describe alternatives you've considered**
I attempted to append @everyone to RemoteNick but it gets ignored

**Comment by 42wim** [comment]
Tengo script can solve this for you, look at tengo:
- https://github.com/42wim/matterbridge/wiki/Tengo
- https://github.com/42wim/matterbridge/issues?q=label%3Atengo+is%3Aclosed
