### ISSUE TITLE
Keybase bridge doesn't work.

### ISSUE THREAD

**Issue by JayDoubleu** [42wim/matterbridge#1484]
Sometimes it works but other time it throws `Starting gateway failed: Bridge keybase.team1 failed to start: invalid whoami JSON "": unexpected end of JSON input`
Looks like even keybase bridge for #matterbridge doesnt work either.

On top of this, it does not seem to support multiple channels.

**Comment by 42wim** [comment]
I can not reproduce this, I'm running at the moment against keybase-5.6.1 and it works fine.

**Comment by 42wim** [comment]
Closing in favor of #982 982

**Comment by JayDoubleu** [comment]
I don't believe these are the same issues tbh. Yesterday I was on matrix and it didn't replicate messages to keybase it feels like that interface to keybase is not stable (or keybase itself)

**Comment by 42wim** [comment]
> it feels like that interface to keybase is not stable (or keybase itself)

The keybase bridge is using the https://github.com/keybase/go-keybase-chat-bot library, but basically it uses the `keybase` command to send/receive messages.
