### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by MijoHuer** [42wim/matterbridge#1495]
**Is your feature request related to a problem? Please describe.**

I want to run Matterbridge 24/7 in Android. My computer fan don't let me sleep

**Describe the solution you'd like**

I would like to install and run Matterbridge like an app (apk)

**Describe alternatives you've considered**

I tried to use Termux to run Matterbridge, i am a noob, I don't know how to do it (lack of knowledge), i think most of those errors i got surely was for it. If someone could help me i will be pleased

**Additional context**
![Screenshot_20210527-190726_Termux](https://user-images.githubusercontent.com/78889806/119903479-232d6100-bf1f-11eb-83ae-152d3fff792b.png)

**Comment by mentalisit** [comment]
@MijoHuer I am using android.  I am using Termux, but to use the mother bridge I need to compile it on my phone, install golang and compile it myself.

**Comment by MijoHuer** [comment]
@mentalisit So to get it working I have to
1) Compile from the phone (matterbridge)
2) Compile and install Golang?

**Comment by mentalisit** [comment]
> @mentalisit Итак, чтобы он заработал, мне нужно
> 
> 1. Компиляция с телефона (материальный мост)
> 2. Скомпилировать и установить Golang?

https://github.com/42wim/matterbridge#building

**Comment by mentalisit** [comment]
I could not run the finished binary, so only do my own

**Comment by MijoHuer** [comment]
I couldn't make the binary either. Anyway I thank you for helping me with this, i appreciate you 😁

**Comment by Wandrius** [comment]
I'm trying to do it on my android, but I'm not getting anyone to help me?

**Comment by Wandrius** [comment]
> > Estou tentando fazer no meu android, mas não estou conseguindo ninguém para me ajudar?
> 
> Como posso ajudá-lo ?

You could call me on the telegram. I'll explain better https://t.me/wandrius

**Comment by ahmadi-111534** [comment]
So what was the solution? I tried to build on my phone but the binary seem not working.

`~/matterbridge $ ./matterbridge-termux -conf mb.toml
[0000]  INFO main:         Running version 1.25.2
[0000]  INFO router:       Parsing gateway kuro-kepompong
[0000]  INFO router:       Parsing gateway t.me/halamanBelakang
[0000]  INFO router:       Starting bridge: whatsapp.mywhatsapp
[0000] FATAL main:         Starting gateway failed: Bridge whatsapp.mywhatsapp failed to start: failed to connect to WhatsApp: couldn't dial whatsapp web websocket: dial tcp: lookup web.whatsapp.com on [::1]:53: read udp [::1]:55518->[::1]:53: read: connection refused`

**Comment by mentalisit** [comment]
problem with old version 
use go install -tags whatsappmulti github.com/42wim/matterbridge@master

**Comment by ahmadi-111534** [comment]
> problem with old version. use go install -tags whatsappmulti github.com/42wim/matterbridge@master

It worked. Thanks!
