### ISSUE TITLE
slack hook name_taken error in private channels

### ISSUE THREAD

**Issue by uetam** [42wim/matterbridge#150]
### Which version of matterbridge are you using?
0.12.0-dev

### Please describe the actual behavior. 
INFO[2017-04-16T18:51:40Z] slack.hobby: joining forumowisko (forumowiskoslack.hobby)
INFO[2017-04-16T18:51:40Z] slack.hobby: joining projekt (projektslack.hobby)
INFO[2017-04-16T18:51:40Z] slack.hobby: joining grr (grrslack.hobby)
INFO[2017-04-16T18:51:40Z] slack.hobby: joining channel2 (channel2slack.hobby)
FATA[2017-04-16T18:51:40Z] Starting gateway failed: Bridge slack.hobby failed to join channel: name_taken

### Any steps to reproduce the behavior?

My channel is private on both slack and mattermost servers and the right api user is present on both channels. 
I have problem only with private channels, regular ones work fine.

#### (be sure to exclude or anonymize private data (tokens/passwords))
 My config file:
[[samechannelgateway]]
   name="samechannel2"
   enable = true
    accounts = [ "slack.hobby", "mattermost.work" ]
   channels = [ "channel" ]

**Comment by 42wim** [comment]
Should be fixed now in master.
