### ISSUE TITLE
Matterbridge Hangs on Backlog of Requests - Telegram To Discord

### ISSUE THREAD

**Issue by computeronix** [42wim/matterbridge#1508]
**Describe the bug**
I have a telegram to Discord gateway setup and if this channel gets really busy (10k+ users) chatting, sometimes the gateway gets backed up and if that is the case, once the gateway gets backup, it takes multiple restarts of the gateway to get it caught back up.  Otherwise it just hangs.

**To Reproduce**
Setup a telegram to Discord gateway

I have three channels setup with lots of chatter

**Expected behavior**
The gateway should handle messages properly

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version:  1.22.1 b979aff2

**Additional context**
Setup three channels with lots of chatter going from TG to Discord

Workaround: setup a script to reboot the service every night

**Comment by 42wim** [comment]
Discord ratelimits you, so matterbridge has to wait for the ratelimit to end before it can send new messages.

If you add `debuglevel=1` to your `[discord.yourdiscord]` config and run `matterbridge --debug` you can see every message being sent to discord with the ratelimit limits + waiting time.

Warning this gives you a lot of output and also outputs your tokens.

**Comment by computeronix** [comment]
If this were the case though, why does immediately stopping and restarting the app work?

So if I start the bridge, it starts to catch up on backlog and then stops, then I stop the program and immediately start it, then it continues on the backlog, and I keep cycling like this until backlog cleared

if I don't do the above, the process hangs and never catches up

**Comment by 42wim** [comment]
Did you do the discord debug as I proposed above?

**Comment by computeronix** [comment]
I did not this, resolves the issue as a workaround -- in the docker file I force a restart every 15 mins or so

  && printf "*/15 * * * * reboot now >/dev/null 2>&1" > /etc/crontabs/matterbridge \
  && chmod 0644 /etc/crontabs/matterbridge \
  && crontab /etc/crontabs/matterbridge
ENTRYPOINT ["/bin/sh", "-c", "crond && /bin/matterbridge -conf /etc/matterbridge/matterbridge.toml"]
