### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by dbrgn** [42wim/matterbridge#151]
Please answer the following questions. 

### Which version of matterbridge are you using?

42wim/matterbridge:latest (27f616e0b7a7)

### Please describe the expected behavior.

We set up a bridge between Mattermost, IRC and Telegram.

When sending an IRC message with non-UTF8-encoding (e.g. latin1), it should arrive everywhere.

### Please describe the actual behavior. 

Messages from IRC containing umlauts are sent to Mattermost, with "bad encoding" marks:

![img1](https://tmp.dbrgn.ch/screenshots/20170418161043-t0z8inb9.png)

This is fine I think (as long as it's not possible to detect the encoding used in IRC). But the messages aren't delivered to Telegram at all.

**Comment by 42wim** [comment]
Sorry for the delay in answering.
I'll see if it can be easily fixed

**Comment by 42wim** [comment]
Using utf-8 isn't an option ? This seems to work fine everywhere

**Comment by dbrgn** [comment]
Well, I can't change it if someone else uses a misconfigured IRC client :) Isn't there a way to force-encode to UTF8 with replacement chars for invalid codepoints, or something like that?

**Comment by 42wim** [comment]
Can not be easily done, and fixing non-uncode to unicode is beyond the scope of matterbridge.
Most of the irc clients now support utf-8. 
I'm sorry but the only option is to ask your users to enable/use utf-8 on their irc client

**Comment by 42wim** [comment]
@dbrgn Just pushed a commit into master, which maybe fixes this too
