### ISSUE TITLE
[linux-armv7] Where is build for linux-armv7

### ISSUE THREAD

**Issue by kasru** [42wim/matterbridge#1511]
$ matterbridge-1.22.2-linux-armv6
Illegal instruction (core dumped)
```
$ uname -a
Linux XiaoQiang 2.6.36 #3 MiWiFi-R1D-2.25.213 SMP PREEMPT Tue Oct 16 11:44:14 UTC 2018 armv7l GNU/Linux
```

**Comment by 42wim** [comment]
It's been added to the goreleaser config. Next release will have support for armv7 https://github.com/42wim/matterbridge/commit/66b6f9749d0a51d87d6264b61ebc41e769770601
