### ISSUE TITLE
Process kills itself after some minutes of runtime

### ISSUE THREAD

**Issue by thisven** [42wim/matterbridge#1514]
First of all thanks for this complete solution. Goog job. =)

I'm running [matterbridge 1.22.2 binary for linux 64bit](https://github.com/42wim/matterbridge/releases/download/v1.22.2/matterbridge-1.22.2-linux-64bit) on [Uberspace](https://uberspace.de) to bridge my IRC account on [Libera.chat](https://libera.chat) with my [Matrix](https://matrix.org) homeserver (Synapse), but it seems to kill itself after some minutes of runtime.

I already checked the resource usage of the process with [this bash script](https://knoxxs.github.io/programming/linux/ops/2015/08/31/linux-find-out-how-the-process-got-killed/) and record my own investigation in the [pull request for the lab guide](https://github.com/Uberspace/lab/pull/1044).

**How to reproduce**
- [Join](https://dashboard.uberspace.de/register) Uberspace (free to try for one month), if you don't have an account already
- Setup [Synapse](https://lab.uberspace.de/guide_synapse.html) and [get Element](https://element.io/get-started) as client
- Install matterbridge according to [my lab guide](https://github.com/thisven/lab/blob/main/source/guide_matterbridge.rst)
- For debugging use `DebugLevel=2` inside `[matrix.mymatrix]` as well as `[irc.myirc]` section and append `--debug` parameter to Test run command

**Debug logs**
The debug logs doesn't seem to provide any useful information, anyway the last 10 lines are:
```
time="2021-06-13T09:19:01+02:00" level=info msg="debug:09:19:01 handler.go:232: [1/1] done OzAOmjeUDekNrSMeLZnr == 1.234µs" prefix=irc
time="2021-06-13T09:20:01+02:00" level=info msg="debug:09:20:01 client.go:782: > PING 1623568801794783380" prefix=irc
time="2021-06-13T09:20:01+02:00" level=info msg="debug:09:20:01 handler.go:29: < :tin.libera.chat PONG tin.libera.chat 1623568801794783380" prefix=irc
time="2021-06-13T09:20:01+02:00" level=info msg="debug:09:20:01 handler.go:211: [2/2] exec HdFHnmRfWjpfQHVebkel => *" prefix=irc
time="2021-06-13T09:20:01+02:00" level=debug msg="":tin.libera.chat PONG tin.libera.chat 1623568801794783380"" func=handleOther file="bridge/irc/handlers.go:171" prefix=irc
time="2021-06-13T09:20:01+02:00" level=info msg="debug:09:20:01 handler.go:232: [2/2] done HdFHnmRfWjpfQHVebkel == 175.188µs" prefix=irc
time="2021-06-13T09:20:01+02:00" level=info msg="debug:09:20:01 handler.go:211: [1/2] exec cfAXOhoHSkNUnDyrCwGl => *" prefix=irc
time="2021-06-13T09:20:01+02:00" level=info msg="debug:09:20:01 handler.go:232: [1/2] done cfAXOhoHSkNUnDyrCwGl == 2.735µs" prefix=irc
time="2021-06-13T09:20:01+02:00" level=info msg="debug:09:20:01 handler.go:211: [1/1] exec OzAOmjeUDekNrSMeLZnr => PONG" prefix=irc
time="2021-06-13T09:20:01+02:00" level=info msg="debug:09:20:01 handler.go:232: [1/1] done OzAOmjeUDekNrSMeLZnr == 2.153µs" prefix=irc
```

**Environment:**
 - OS: x86_64 Linux, Kernel: 3.10.0-1160.21.1.e17.x86_64
 - Matterbridge version: 1.22.2 641ed187
 - Go version: go1.16.4 linux/amd64

**Additional context**
My redacted `matterbridge.toml` configuration file looks like this:
```
[matrix.mymatrix]
DebugLevel=2
Server="https://exmaple.org"
NoHomeServerSuffix=false
Login="matterbridge"
Password="Matrix-p4$$w0rd"
RemoteNickFormat="{NICK}[i] "

[irc.liberachat]
DebugLevel=2
Nick="example-nick"
NickServNick="example-nick"
NickServPassword="IRC-p4$$w0rd"
Server="irc.libera.chat:6697"
UseTLS=true
UseSASL=true
SkipTLSVerify=false
RemoteNickFormat="{NICK}[m] "

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="irc.liberachat"
channel="#example-channel"

[[gateway.inout]]
account="matrix.mymatrix"
channel="#example-channel:example.org"
```

**Comment by 42wim** [comment]
There is no way for it to kill itself unless you see a panic in the logs.
So if you don't see that panic message and it got killed, it is because you, an external process or the kernel killed it.

Look in dmesg to see if the kernel killed it.
As it get killed in a few minutes, do not run it as a daemon but just as in your shell, if it panics or get killed you can see it exists message.

**Comment by thisven** [comment]
Thanks for explanation. I just test ran matterbridge again and displayed the exit code:
```
$ ./matterbridge -conf matterbridge.toml --debug &> matterbridge.log
Killed
$ echo $?
137
```
I can't find any information on that exit code. It's neither listed in [reserved exit codes](https://tldp.org/LDP/abs/html/exitcodes.html), nor found (by its number) in this repository.

**Comment by 42wim** [comment]
> Look in dmesg to see if the kernel killed it.

**Comment by thisven** [comment]
I don't think so. The process uses about 23 MB (refering to [this approach for measurement](https://stackoverflow.com/a/20277787)) and each Uberspace can use up to 1.5 GB. I am using 178 MB (including the matterbridge process) refering to another `ps` analysis method taken from [here](https://unix.stackexchange.com/a/286759).

When using the latest version (1.22.3), the error code has been 130 once and is now 137 again. I tried to compile from sources, but this is getting killed either:
> 
> $ go get github.com/42wim/matterbridge
> go: downloading github.com/42wim/matterbridge v1.22.3
> [...]
> go build github.com/yaegashi/msgraph.go/beta: /opt/golang/pkg/tool/linux_amd64/compile: signal: killed

**Comment by 42wim** [comment]
Compiling the source needs a lot of memory > 1.5GB

**Comment by 42wim** [comment]
I'm going to close this as this isn't a matterbridge issue, but an Uberspace issue
Try running it on something like digitalocean, it runs fine on a 5$/month server.

**Comment by qaisjp** [comment]
You can use build tags to bring down the memory usage: `go get github.com/42wim/matterbridge -tags noapi,nodiscord,nogitter,noirc,nokeybase,nomatrix,nomattermost,nomsteams,nomumble,nonctalk,norocketchat,noslack,nosshchat,nosteam,notelegram,novk,nowhatsapp,noxmpp,nozulip`.

Just take out the tags for the bridges that you need.

**Comment by thisven** [comment]
Thanks for that hint. I had to change the order, but compiling at Uberspace seems to work with:
`go get -tags noapi,nogitter,nokeybase,nomsteams,nosshchat,nosteam,novk,nowhatsapp,nozulip github.com/42wim/matterbridge`
Now let's see if a self-built binary runs stable...

**Comment by thisven** [comment]
It's still getting killed with exit code 137. -_-

**Comment by hamoid** [comment]
I have the same issue in Uberspace and the worst part was that it would not restart automatically until I changed the ini script to this:

```
$ cat ~/etc/services.d/matterbridge.ini 
[program:matterbridge]
command=%(ENV_HOME)s/matterbridge/matterbridge-1.23.1-linux-64bit
autostart=true
autorestart=true
directory=%(ENV_HOME)s/matterbridge
startsecs=150
priority=1600
```

It seems like with the larger value for `startsecs` it does restart automatically.

I do see lines like this in the logs every 20 minutes:

```
2021-11-02 23:50:05,782 INFO exited: matterbridge (terminated by SIGKILL; not expected
)
```

Why can this be happening?

**Comment by thisven** [comment]
Any luck? I see you are using version 1.23.1. I just tried the same setup with [1.23.2](https://github.com/42wim/matterbridge/releases/tag/v1.23.2), but the process still gets killed after a few minutes. Do you know alternates that might run on Uberspace?

**Comment by hamoid** [comment]
Hi! They replied from Uberspace and said it doesn't seem to be the system killing the process. That it's one of my own programs doing that. I have no idea what it could be. I run Mattermost, Nextcloud, Matterbridge, Etherpad, postgresql, isso and redis.

I have noticed that it happens in random intervals of 15 or 20 minutes (one of those two). Something like 20 20 15 20 15 20 20 15 ...

The only cron job I have is cron.php for Nextcloud, set at 5 minutes. 

Since I figured out how to make it restart reliably, I guess it's not the end of the world. Only annoying not to know why.

**Comment by thisven** [comment]
I see. It's very annoying for other users in IRC when you're constantly disconnecting every 15 or 20 minutes. I can confirm that the process gets killed in that intervals, but there's no way that another process is killing it. So you're using it (with constant restarts) anyway?

**Comment by hamoid** [comment]
Right... I don't know how it is from the users perspective. I should ask them. Mine connects to Telegram, Discord and Mattermost.
I guess users don't need to log in again because they do stay connected to one of those three platforms (I assume). And yes, I'm still using it like that, although I hope to find a fix for this.

**Comment by hamoid** [comment]
In case it helps, the error log showing the SIGKILL is `logs/supervisord.log`

```
2021-11-08 13:22:35,487 INFO success: matterbridge entered RUNNING state, process has stayed up for > than 150 seconds (startsecs)
2021-11-08 13:35:06,686 DEBG fd 17 closed, stopped monitoring <POutputDispatcher at 140341641298936 for <Subprocess at 140341641088032 with name matterbridge in state RUNNING> (stdout)>
2021-11-08 13:35:06,686 DEBG fd 25 closed, stopped monitoring <POutputDispatcher at 140341640801096 for <Subprocess at 140341641088032 with name matterbridge in state RUNNING> (stderr)>
2021-11-08 13:35:06,687 INFO exited: matterbridge (terminated by SIGKILL; not expected)
2021-11-08 13:35:06,687 DEBG received SIGCLD indicating a child quit
2021-11-08 13:35:07,692 INFO spawned: 'matterbridge' with pid 1408
2021-11-08 13:35:07,785 DEBG 'matterbridge' stdout output:
time="2021-11-08T13:35:07+01:00" level=info msg="Running version 1.23.2 73ec02ab" prefix=main
```

**Comment by hamoid** [comment]
@thisven Does it use less ram after you compiled it yourself?

**Comment by thisven** [comment]
Using the tags _noapi,nogitter,nokeybase,nomsteams,nosshchat,nosteam,novk,nowhatsapp,nozulip_ the self-compiled one is taking about 15 MB in contrast to 25 MB (binary release) when measuring with the same approach as above:
```
mem()
{                                                                                                      
    ps -eo rss,pid,euser,args:100 --sort %mem | grep -v grep | grep -i $@ | awk '{printf $1/1024 "MB"; $1=""; print }'
}
mem matterbridge
```
from [Stackoverflow](https://stackoverflow.com/questions/3853655/in-linux-how-to-tell-how-much-memory-processes-are-using/20277787#20277787).

**Comment by thisven** [comment]
> In case it helps, the error log showing the SIGKILL is `logs/supervisord.log`

Yeah, I'm getting the same messages there, but I still haven't any clue why it gets killed (or kills itself) and how to prevent that... :disappointed:

**Comment by hamoid** [comment]
I don't know what, but something changed (probably in Uberspace). After months of continuous matterbridge restarts every few minutes, it has run continuously since 10 days ago.

**Comment by thisven** [comment]
Yeah, it seems to be running fine now. Thanks @hamoid  for your hint. I had paused using it to keep free resources and to avoid annoying bridged IRC groups by constant reconnections. :sweat_smile:

I'll monitor it for the next days and report here.

**Comment by thisven** [comment]
Oh, I'm mistaken. It crashed again a few minutes ago. Which version are you using? And are there any specific changes to the configuration I've provided in the [first post above](#issue-919753993)?

**Comment by thisven** [comment]
BTW: I'm starting the process using the following supervisor service:
```
[program:matterbridge]
command=%(ENV_HOME)s/matterbridge/matterbridge -conf %(ENV_HOME)s/matterbridge/matterbridge.toml
autostart=yes
autorestart=yes
startsecs=150
priority=1600
```

**Comment by thisven** [comment]
OK, since three automatic restarts it's now running for 16 minutes. Let's see how this works out... :thinking:

**Comment by hamoid** [comment]
I have this:
```
$ cat matterbridge.ini 
[program:matterbridge]
command=%(ENV_HOME)s/matterbridge/matterbridge-1.23.2-linux-64bit
autostart=true
autorestart=true
startretries=5
directory=%(ENV_HOME)s/matterbridge
startsecs=300
priority=3300
```

**Comment by hamoid** [comment]
BTW. I haven't change my configuration in a very long time.

**Comment by thisven** [comment]
I've copied your service configuration and I'm using the same binary release, but the process is killed very regularly every 20 minutes:
```
[...]
time="2021-12-29T12:00:17+01:00" level=info msg="Running version 1.23.2 73ec02ab" prefix=main
[...]
time="2021-12-29T12:00:26+01:00" level=info msg="Gateway(s) started succesfully. Now relaying messages" prefix=main
time="2021-12-29T12:20:14+01:00" level=info msg="Running version 1.23.2 73ec02ab" prefix=main
[...]
time="2021-12-29T12:20:21+01:00" level=info msg="Gateway(s) started succesfully. Now relaying messages" prefix=main
time="2021-12-29T12:40:14+01:00" level=info msg="Running version 1.23.2 73ec02ab" prefix=main
[...]
time="2021-12-29T12:40:26+01:00" level=info msg="Gateway(s) started succesfully. Now relaying messages" prefix=main
time="2021-12-29T13:00:15+01:00" level=info msg="Running version 1.23.2 73ec02ab" prefix=main
[...]
time="2021-12-29T13:00:23+01:00" level=info msg="Gateway(s) started succesfully. Now relaying messages" prefix=main
```

**Comment by hamoid** [comment]
Oh sad to hear. I don't know why it stopped restarting in my case :(

**Comment by thisven** [comment]
Recently it was running two days and now it's back to restarting about every 20 minutes. :disappointed:

**Comment by hamoid** [comment]
I wonder if the behavior depends on how loaded the server is? Mine was last restarted 17 days ago.

**Comment by thisven** [comment]
Mine has been running since 131 days. Maybe there's a connection...

**Comment by simonSlamka** [comment]
@42wim 
Yo! This started happening to me, too. The same exit code. Runs for about 5 - 10 minutes and then terminates. I only use a bridge between Talk and Discord. There's no reason for OOM kills since I got 64 gigs of memory.

**Comment by hamoid** [comment]
Might it depend on the server? Mine has been running for weeks, same version. Server is devico.ub...

**Comment by thisven** [comment]
Maybe. I'll reach out to Uberspace support.
