### ISSUE TITLE
Docker - TGS to PNG fails with Lottie Error

### ISSUE THREAD

**Issue by computeronix** [42wim/matterbridge#1515]
**Describe the bug**
When attempting to run the default docker image of  42wim/matterbridge with the command to convert TGS to PNG the following error occurs

/etc/matterbridge$ &exec.Error{Name:"lottie_convert.py", Err:(*errors.errorString)(0xc00010a6f0)}

**To Reproduce**
Setup an AWS workstation with Docker

Have the toml file set to convert TGS to PNG

Run this command
docker run -ti --mount "type=bind,source=$(pwd)/matterbridge,target=/etc/matterbridge" 42wim/matterbridge

**Expected behavior**

Lottie should run and work properly

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Matterbridge version: 1.22.3-dev 6a12f9ff

**Comment by computeronix** [comment]
I found the following packages need to be installed for it to be fully working

`pip3 install lottie cairosvg`

`sudo apt-get install libcairo2-dev libpangocairo-1.0-0`

**Comment by 42wim** [comment]
The matterbridge docker image is using alpine, not ubuntu.
Are you sure this dockerfile doesn't work? https://github.com/42wim/matterbridge/blob/master/tgs.Dockerfile

**Comment by computeronix** [comment]
Aww makes sense, but yes does not work, when enabled, returns the error mentioned above
