### ISSUE TITLE
Conflicting use of NickServNick in the documentation

### ISSUE THREAD

**Issue by GNUtoo** [42wim/matterbridge#1516]
**Describe the bug**

In the NickServNick documentation we have:
>  Note: if you want do to quakenet auth, set NickServNick="Q@CServe.quakenet.org"
And:
> Example: On freenode nickserv is called nickserv"

But in "Section IRC (basic)"[2] we have:
> NickServNick="yournick" # <== change this if necessary (your nick registered with nickserv)
for both OFTC and Freenode.

The NickServNick="yournick" seems to be the right one as because with our configuration[3], without NickServNick or with NickServNick="NickServ" the bot cannot login.

References:
[1]https://github.com/42wim/matterbridge/wiki/Settings#nickservnick
[2]https://github.com/42wim/matterbridge/wiki/Section-IRC-%28basic%29
[3]https://git.replicant.us/infrastructure/matterbridge/plain/matterbridge.toml.example?id=37288be7fe66472f8d44d10b51a8a74d121325b0

**Comment by 42wim** [comment]
Yes, it's used for multiple (mutual exclusive) things, it also says there[1] that's also used for SASL (which you use in [3]), so if you go there: https://github.com/42wim/matterbridge/wiki/Settings#usesasl you see the nickservnick/nickservpassword is used there.

So your configuration is correct :-)

**Comment by cuihaoleo** [comment]
I also found this very confusing. We migrated our IRC channel from Freenode to OFTC. At first I just copied freenode section in the config and changed `UseSASL` to `false`, and didn't touch original `NickServNick="botname"` setting. Later I found the bot doesn't get verified.

After digging into the code I realized `NickServNick` should be the nickname of the IRC server's nick service bot. I changed it and now it works. The final working config is like this:

    [irc.oftc]
    Server="irc.oftc.net:6697"
    UseSASL=false
    Nick="botname"
    NickServNick="NickServ"
    NickServPassword="<PASSWORD>"
    ...

I think it's better to separate the setting to two things (e.g. `SASLUserName` and `NickServNick` ).

BTW, I just realized there is a [wiki section](https://github.com/42wim/matterbridge/wiki/Section-IRC-%28basic%29#oftc-nickserv-identify-nickname) about OFTC config. But it uses a different config than mine. I believe `NickServNick` setting there is basically useless and it hacks `RunCommands` to do verification.

@42wim what do you think? I would like to replace the wiki section if my way look correct and cleaner.

**Comment by 42wim** [comment]
@cuihaoleo yes, your setting is cleaner, please feel free to update the wiki! thanks!
