### ISSUE TITLE
[Whatsapp] Login/Restore session broken; solution available

### ISSUE THREAD

**Issue by Vetgans** [42wim/matterbridge#1517]
**Describe the bug**
Thrown out of the connection to Whatsapp. Impossible to login again or restore old session

**Screenshots/debug logs**
```
[0000]  WARN whatsapp:     failed to restore session: error decoding login connResp: json: cannot unmarshal array into Go value of type map[string]interface {}

[0000]  WARN whatsapp:     Failed to log in: error writing login: error writing to websocket: websocket: close sent

[0000] FATAL main:         Starting gateway failed: Bridge whatsapp.mywhatsapp failed to start: error writing login: error writing to websocket: websocket: close sent
```

See https://github.com/Rhymen/go-whatsapp/issues/571 for further explanation and solution.

**Comment by mgechev123** [comment]
@nathanaelhoun Many thanks, my friend!

**Comment by Vetgans** [comment]
Many thanks for acting so swiftly!
I cannot test it yet because development releases don't provide a linux-armv6 version.

**Comment by nathanaelhoun** [comment]
Heads up that after a few hours, the connection seems to be down again.

Version : Built from https://github.com/42wim/matterbridge/pull/1518/commits/cd942f7bafc6e88c04e8607b168766d9945b522e

<details>
<summary>Logs</summary>

At runtime
```
time="2021-06-16T07:25:51Z" level=info msg=Reconnecting... prefix=whatsapp
time="2021-06-16T07:25:47Z" level=error msg="SendMessage failed: sending message timed out" prefix=gateway
time="2021-06-16T07:25:27Z" level=error msg="SendMessage failed: sending message timed out" prefix=gateway
time="2021-06-16T07:23:11Z" level=info msg="Waiting 5m0s..." prefix=whatsapp
time="2021-06-16T07:23:11Z" level=error msg="Connection failed, underlying error: connection to WhatsApp servers failed: read tcp [REDACTED]:60132->31.13.92.52:443: read: connection reset by peer" prefix=whatsapp
```

When restarted
```
time="2021-06-16T07:56:38Z" level=info msg="Starting bridge: whatsapp.relay " prefix=router
time="2021-06-16T07:56:58Z" level=warning msg="failed to restore session: restore session connection timed out" prefix=whatsapp
time="2021-06-16T07:56:58Z" level=warning msg="Failed to log in: error decoding login resp: invalid resp['ref']" prefix=whatsapp
level=fatal msg="Starting gateway failed: Bridge whatsapp.relay failed to start: error decoding login resp: invalid resp['ref']" prefix=main
```
</details>

**Comment by zeroone82** [comment]
> Hum, after a few hours, the connection seems to be down again.
> 
> Version : Built from [cd942f7](https://github.com/42wim/matterbridge/commit/cd942f7bafc6e88c04e8607b168766d9945b522e)
> 
> Logs

I tried a manual build and I get the same errors

**Comment by jzvi12** [comment]
@zeroone82 Is your binary compatible with Linux 64-bit? If so, is there a way you can share it?

I have tried compiling myself from @nathanaelhoun's updated repo but my VPS keeps giving me this error:
```
$ go build matterbridge.go
go build github.com/yaegashi/msgraph.go/beta: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
```

**Comment by mgechev123** [comment]
> Hum, after a few hours, the connection seems to be down again.

@nathanaelhoun my connection is fine. I'm using your build for like 11 hours straight now and haven't had any issues so far.

**Comment by zeroone82** [comment]
@jzvi12 you're probably running oom. What I did was clone the repo, modify the files and then build the container instead of using the hub image.

**Comment by ciroiriarte** [comment]
will this hit 42wim/matterbridge:stable docker image?

**Comment by nathanaelhoun** [comment]
> @nathanaelhoun my connection is fine. I'm using your build for like 11 hours straight now and haven't had any issues so far.

@mgechev123 Nice! Mine is also fine after a few days, I think it was another connection problem with my local ISP.
