### ISSUE TITLE
Unsupported mattermost version

### ISSUE THREAD

**Issue by TortuePatate** [42wim/matterbridge#152]
Please answer the following questions. 

### Which version of matterbridge are you using?
Matterbridge version 0.12.0-dev  

### If you're having problems with mattermost please specify mattermost version. 
Mattermost version 3.7.3

### Please describe the expected behavior.
Launch of matterbridge 

### Please describe the actual behavior. 

INFO[2017-04-19T20:34:49+02:00] Enabling debug                               
INFO[2017-04-19T20:34:49+02:00] Running version 0.12.0-dev                   
INFO[2017-04-19T20:34:49+02:00] WARNING: THIS IS A DEVELOPMENT VERSION. Things may break. 
INFO[2017-04-19T20:34:49+02:00] Starting gateway: mygateway                  
INFO[2017-04-19T20:34:49+02:00] Starting bridge: mattermost.lidn             
INFO[2017-04-19T20:34:49+02:00] Connecting nonolerobot (team: LIDN) on https://chat.lidn.fr/  module=mattermost
FATA[2017-04-19T20:34:49+02:00] Starting gateway failed: Bridge mattermost.lidn failed to start: unsupported mattermost version:

### Please add your configuration file 

[mattermost]
  [mattermost.lidn]
  useAPI=true
  Server="hidden"
  Team="LIDN"
  Login="nonolerobot"
  Password="hidden"
  PrefixMessagesWithNick=true

[slack]
  [slack.reseaulidn]
  useAPI=true
  Token="hidden"
  PrefixMessagesWithNick=true

[general]
RemoteNickFormat="[{PROTOCOL}/{BRIDGE}] <{NICK}> "

[[gateway]]
    name="mygateway"
    enable=true

    [[gateway.inout]]
    account="mattermost.lidn"
    channel="general"

    [[gateway.inout]]
    account ="slack.reseaulidn"
    channel = "-general"

Hello everyone,
First of all thank you very much for matterbridge I think it's awesome. My computer skills are not up to the challenge of having it running on my yunohost (debian jessie) linux server though. 
If anyone can help that would be much appreciated !
Max

**Comment by 42wim** [comment]
In the debug log it says ```https://chat.lidn.fr/```, this should be chat.lidn.fr
So your config for mattermost.lidn should be

```
[mattermost.lidn]
useAPI=true
Server="chat.lidn.fr"
Team="LIDN"
Login="nonolerobot"
Password="hidden"
PrefixMessagesWithNick=true
```

**Comment by TortuePatate** [comment]
It works! Thank you so much for your quick reply. This is making my day you rock! 
A great day to you,
Max
