### ISSUE TITLE
Clarify if/how puppeting on matrix works

### ISSUE THREAD

**Issue by micw** [42wim/matterbridge#1523]
This is an issue to the documentation, so the bug template does not match very well. Please excuse that I don't use it completely

**Describe the bug**

The example configuration for matrix tells about how to configure the bridge to use the sender username (aka "puppeting"):
https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample#L1287-L1292

The setting seems to have no effect. Looking at the code, I could find nothing that implies that this feature is actually implemented. The username is always prepend to each message and that's hard-coded (e.g. https://github.com/42wim/matterbridge/blob/master/bridge/matrix/matrix.go#L285).

The documentation also states `Useful if username overrides for incoming webhooks isn't enabled on the matrix server` - I could not find any reference for "username overrides" in the matrix synapse documentation.

**Comment by 42wim** [comment]
Hi, the documentation is incorrect, it seems like it copy/pasted a bit too much from mattermost for matrix.
There is no support for username overrides in matrix, so what you're asking is not possible (unless with something like the matrix appservice thingy, but that's not something matterbridge supports)
