### ISSUE TITLE
Connect to Slack connect channels (connect from MM to other companies' Slacks)

### ISSUE THREAD

**Issue by alexander-potemkin** [42wim/matterbridge#1530]
**Is your feature request related to a problem? Please describe.**
I'm wondering, if I can setup my paid Slack instance with myself only and setup a matterbridge to my working mattermost, where all of my team mates.
I will then create a channel inside Slack, that I will connect from my team A to other team B (channel a2b-connect) via Slack's connect.
Will this channel be replicated back to my mattermost, so that everyone from team A would be able to chat to team B, without paying for every user in team A (and paying just for me, as a 'hosting' user).

**Describe the solution you'd like**
Ideally, I would like to keep Slack instance with connects to other Slack connects, to make sure we can communicate - the guys living in Slack, will keep living in Slack; and myself and my team will remain in Mattermost.

**Describe alternatives you've considered**
N/A as far as I'm aware.

**Additional context**
Guess that's pretty much it

**Comment by 42wim** [comment]
I've no experience with slack connect.
Did you try it ?

**Comment by alexander-potemkin** [comment]
Yep. You create a regular Slack channel, then you connect it to other company Slack channel and everyone you will add to it, can speak to another company.
You can regulate access to the channel (private/public), just like to any other channel.
Does it makes sense?

**Comment by 42wim** [comment]
Ok, i'm not following, do you say you tested it with matterbridge and mattermost and it works? So this issue can be closed?

**Comment by alexander-potemkin** [comment]
No, I didn’t yet - wondering if this kind of connection could be done.
I have separate Slack & Mattermost instances running for a different teams would love to unify things inside Mattermost.

**Comment by 42wim** [comment]
Well, that's why I said just try :-)
If it doesn't work, run with `--debug`

**Comment by 42wim** [comment]
Closed because no further feedback
