### ISSUE TITLE
Whatsapp: mark messages as read after they are relayed

### ISSUE THREAD

**Issue by micw** [42wim/matterbridge#1531]
**Is your feature request related to a problem? Please describe.**
On the primary device, messages remains unread after they are read by matterbridge.

**Describe the solution you'd like**
The messages should be (maybe optional) marked as read, similar like the web client does it.

**Comment by efelon** [comment]
I think in this context I get the following error message

`time="2021-11-19T14:35:57+01:00" level=error msg="couldn't mark message as read contents=[123 34 101 114 114 99 111 100 101 34 58 34 77 95 78 79 84 95 74 83 79 78 34 44 34 101 114 114 111 114 34 58 34 67 111 110 116 101 110 116 32 110 111 116 32 74 83 79 78 46 34 125] msg=Failed to POST JSON to /_matrix/client/r0/rooms/!***********:mydomain.com/receipt/m.read/$**************** code=400 wrapped=M_NOT_JSON: Content not JSON." prefix=matrix`

My first reaction was, that the messages didn't get through to WA, but they did.

**Comment by SuperSandro2000** [comment]
Having the same error. I think that is on matrix sides.

**Comment by hardcore-sushi** [comment]
Same error for me:
`
ERROR matrix:       couldn't mark message as read contents=[123 34 101 114 114 99 111 100 101 34 58 34 77 95 78 79 84 95 74 83 79 78 34 44 34 101 114 114 111 114 34 58 34 67 111 110 116 101 110 116 32 110 111 116 32 74 83 79 78 46 34 125] msg=Failed to POST JSON to /_matrix/client/r0/rooms/!*****receipt/m.read/$***** code=400 wrapped=M_NOT_JSON: Content not JSON.
`

**Comment by BenWiederhake** [comment]
I run into the same problem with 1.22.1, and the changelog entries since then don't seem to be relevant. It's definitely Matrix, not Whatsapp. The "only" side-effect seems to be that the matrix-account doesn't mark the incoming messages as read. Example log:

```
time="2022-02-23T22:14:59+01:00" level=error msg="couldn't mark message as read contents=[123 34 101 114 114 99 111 100 101 34 58 34 77 95 78 79 84 95 74 83 79 78 34 44 34 101 114 114 111 114 34 58 34 67 111 110 116 101 110 116 32 110 111 116 32 74 83 79 78 46 34 125] msg=Failed to POST JSON to /_matrix/client/r0/rooms/!<REDACTED>:matrix.org/receipt/m.read/$<REDACTED> code=400 wrapped=M_NOT_JSON: Content not JSON." func=handleEvent file="bridge/matrix/matrix.go:405" prefix=matrix
```

**Comment by 42wim** [comment]
The matrix issue should be fixed since https://github.com/42wim/matterbridge/commit/d7cad3b40456ddbc0db7935b6340298d885c2af1
