### ISSUE TITLE
Whatsapp disconnected and fails to reconnect

### ISSUE THREAD

**Issue by micw** [42wim/matterbridge#1536]
**Describe the bug**
This is a follow-up to #987. I had it multiple times that after a few hours or days, whatsapp fails to reconnect:

```
connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpected EOF
```

It tries to reconnect every 5 mins and got no messages. After restarting the service, it workes again.

**To Reproduce**
Not 100% reproducible, happens randomly.

**Expected behavior**
Reconnect should work properly. If not, the program should terminate after a given number of retries.

**Screenshots/debug logs**
```
connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpected EOF
```

**Environment (please complete the following information):**
 - linux / docker
 - 1.22.3

**Additional context**

https://github.com/Rhymen/go-whatsapp/issues/560 may be related. It might be that the reconnect fails if the whatsapp web version changes. (Edited, original message contained link to wrong issue)

**Comment by 42wim** [comment]
going to close this, we switched to a newer library.
More info on https://github.com/42wim/matterbridge#building-with-whatsapp-beta-multidevice-support

**Comment by micw** [comment]
That's OK to me. Unfortunately I cannot test it since I don't use whatsapp anymore.
