### ISSUE TITLE
selfdestruction if irc can't connect

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [42wim/matterbridge#1539]
**Describe the bug**
matterbridge quits terminates itself if connection a single irc can't connect.  #1486

matterbridge-1.22.3

**Screenshots/debug logs**
```
[0075] ERROR irc:          [doConnect:bridge/irc/irc.go:189] disconnect: error: EOF
[0075] FATAL main:         [main:matterbridge.go:68] Starting gateway failed: Bridge irc.1 failed to start: connection failed EOF
```
**Environment (please complete the following information):**
 - OS: x64
 - Matterbridge version: output of  `matterbridge -version` version: 1.22.3 e45bbe45

**Comment by 42wim** [comment]
See https://github.com/42wim/matterbridge/wiki/Settings#ignorefailureonstart

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
I read the configuration documentation previously to opening the issue.

Ignoring the gateway for connection issues is no solution for this issue, it should reconnect instead.

If I need restart mb for a single connection failure it gets really spammy on for all the other already established connections that need to be closed for no reason.
