### ISSUE TITLE
NilPointer exception on irc bridge startup

### ISSUE THREAD

**Issue by skortchmark9** [42wim/matterbridge#155]
Please answer the following questions. 

### Which version of matterbridge are you using?
0.11.0

#### Use logs from running ```matterbridge -debug``` if possible.
```
time="2017-05-01T11:48:23-07:00" level=info msg="Running version 0.11.0 6ea8be5" 
time="2017-05-01T11:48:23-07:00" level=info msg="Starting gateway: mygateway" 
time="2017-05-01T11:48:23-07:00" level=info msg="Starting bridge: my.irc " 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x941110]

goroutine 1 [running]:
github.com/42wim/matterbridge/gateway.(*Gateway).AddBridge(0xc420019d60, 0xc42017dd20, 0x2, 0x2)
	/go/src/github.com/42wim/matterbridge/gateway/gateway.go:50 +0x200
github.com/42wim/matterbridge/gateway.(*Gateway).AddConfig(0xc420019d60, 0xc4200234a0, 0x1, 0x1)
	/go/src/github.com/42wim/matterbridge/gateway/gateway.go:74 +0x370
main.main()
	/go/src/github.com/42wim/matterbridge/matterbridge.go:55 +0x4a6

```

### Any steps to reproduce the behavior?
```./matterbridge-linux64```

### Please add your configuration file 
[irc]
    [my.irc]
    Server="irc.my.domain:6697"
    Nick="mattermost-bot"

[mattermost]
    [mattermost.work]
    useAPI=true
    Server="mattermost.my.domain:8065"
    Team="TeamName"
    Login="ircbot"
    Password="***"
    PrefixMessagesWithNick=true
    NoTLS=true

[[gateway]]
name="mygateway"
enable=true
    [[gateway.inout]]
    account="irc"
    channel="#channel"

    [[gateway.inout]]
    account="mattermost.work"
    channel="irc-bot"

**Comment by 42wim** [comment]
Hi,
2 issues I think:

```
[irc]
[my.irc]
Server="irc.my.domain:6697"
Nick="mattermost-bot"
```
should be

```
[irc]
[irc.my]
Server="irc.my.domain:6697"
Nick="mattermost-bot"
```

And 

```
[[gateway.inout]]
account="irc"
channel="#channel"
```

should be

```
[[gateway.inout]]
account="irc.my"
channel="#channel"
```

**Comment by skortchmark9** [comment]
Thanks for the quick response! I messed up my config file a little when I was anonymizing it. I'm all set now! The key problem was that I didn't realize it needed do be `[namespace.account]` inside of `[namespace]`. Maybe that's just part of the TOML format I didn't know.
