### ISSUE TITLE
Cannot build from source due to broken dependency

### ISSUE THREAD

**Issue by southerntofu** [42wim/matterbridge#1551]
At least since yesterday matterbridge can't build from source.

```
foo@bar:~$ go get github.com/42wim/matterbridge
go/src/github.com/42wim/matterbridge/bridge/vk/vk.go:15:2: found import comments "github.com/SevereCloud/vksdk/v2/api" (account.go) and "github.com/SevereCloud/vksdk/api" (store.go) in /home/foo/go/src/github.com/42wim/matterbridge/vendor/github.com/SevereCloud/vksdk/v2/api
```

It used to work fine a few months ago. I tried and it fails to build on several systems of mine, so i don't think the problem is on my side.

**Comment by 42wim** [comment]
What go version are you using?

**Comment by kkremitzki** [comment]
I just ran into the same problem on Debian 11, which uses go 1.15.9.

**Comment by 42wim** [comment]
Seems a bug in go < 1.16, I can reproduce it in 1.15.9 but can't fix it because it's a vendored dependency.

Upgrade to go1.16.x, OR do a `git clone https://github.com/42wim/matterbridge && cd matterbridge && go build` with 1.15.9
