### ISSUE TITLE
Ability to set outgoing IP address

### ISSUE THREAD

**Issue by singpolyma** [42wim/matterbridge#1553]
Especially for IRC, the outgoing IP address can matter a lot.  Need some way to set which one to use on a box that has many.

**Comment by 42wim** [comment]
Good idea.
This should be an easy PR if anyone is up to it.
By using the `Bind` option from https://github.com/lrstanley/girc/blob/2cb73c37725553fc472a3b8050cddc28f2989c4b/client.go#L96 and putting it here https://github.com/42wim/matterbridge/blob/44f3e2557dad86129419ed098c29e67638519f4f/bridge/irc/irc.go#L296

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Would prefer Ability to set outgoing interface, if you want to use ipv6 privacy extensions, setting manually would become very hard or impossible for dhcp clients

**Comment by 42wim** [comment]
@4-FLOSS-Free-Libre-Open-Source-Software then you should open an issue at girc (https://github.com/lrstanley/girc), the library that matterbridge uses.

It has only support for binding to an IP address.

**Comment by 42wim** [comment]
fixed in #1640
