### ISSUE TITLE
Discord -> IRC url pasting spams multiple urls

### ISSUE THREAD

**Issue by opless** [42wim/matterbridge#1563]
**Describe the bug**
Discord user pastes URL into a bridged channel, three urls are spammed

**To Reproduce**
In discord paste (just) the following url : https://twitter.com/jaroso7811/status/1422074117814112257

**Expected behavior**
On IRC
<oPless>  https://twitter.com/jaroso7811/status/1422074117814112257

**Actual behavior**
On IRC
<oPless> https://twitter.com/jaroso7811/status/1422074117814112257 embed: https://t.co/tUhGl3pZxc - 
              https://twitter.com/jaroso7811/status/1422074117814112257

**Screenshots/debug logs**
Use logs from running `matterbridge -debug` if possible.

**Environment (please complete the following information):**
 - OS: [e.g. linux]
 Linix
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial

 - Matterbridge version: output of  `matterbridge -version`
 version: 1.22.2 641ed187

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))

**Comment by halian** [comment]
Can confirm that it's equally egregious when posting e.g. a YouTube link, especially if, like me, you can't figure out how or if to stop the bot pinging you on IRC every time you say something on Discord, lol.

**Comment by 42wim** [comment]
I can not reproduce this anymore, reopen if you can :)
