### ISSUE TITLE
Message edits break formatting in matrix

### ISSUE THREAD

**Issue by AgathaSorceress** [42wim/matterbridge#1571]
**Describe the bug**
When a message sent from another chat is edited, the relayed message loses all html tags. Happens both with `EditSuffix` enabled and disabled. Doesn't seem to create any errors/warnings in the log.

**To Reproduce**
1. Bridge from discord to matrix (though, I assume it happens when any other chat is bridged to matrix too).
2. Have matrix `RemoteNickFormat` set to something like:
    ```toml
     RemoteNickFormat="<font color=\"#4f3e56\">{PROTOCOL}</font> • <b><font color=\"#c293d6\">{NICK}</font></b> » "
    ```
3. Send a message and then edit it.
4. Check the matrix side and see the message without formatting.

**Expected behavior**
The matrix message formatting should stay the same as it was originally.

**Screenshots/debug logs**
![chat screenshot](https://user-images.githubusercontent.com/53269550/130268976-5d9d7182-a73f-4d04-a21c-43b253743f01.png)

**Environment (please complete the following information):**
 - OS: Archlinux, 5.13.4-arch1-1
 - Matterbridge version: 1.22.3

**Additional context**
[Configuration file](https://paste.ee/p/efhTx)

**Comment by 42wim** [comment]
Fixed in master
