### ISSUE TITLE
[Matrix] Files uploaded from Sailtrix are sent as plain message "sailtrix-file.png" instead of a link to the file

### ISSUE THREAD

**Issue by Mikaela** [42wim/matterbridge#1575]
**Describe the bug**

When I upload a picture from Sailtrix Matrix client, matterbridge sends a message `sailtrix-file.png` to other protocols instead of downloading and linking to the file itself.

**To Reproduce**

* Upload a file from Sailtrix. However this can be tricky as it's for SailfishOS which isn't so common mobile OS.
* Observe matterbridge.

**Expected behavior**

Link to media repostiory is provided.

**Screenshots/debug logs**

I am not sure either is necessary.

**Environment (please complete the following information):**
 - OS: Debian 11
 - Matterbridge version: 1.22.2 641ed187

**Additional context**

Non-working event source (Sailtrix):

```json
{
  "type": "m.room.message",
  "sender": "@mikaela:feneas.org",
  "content": {
    "body": "sailtrix-file.png",
    "msgtype": "m.image",
    "url": "mxc://matrix.feneas.org/17addca646e8167dd88e80b92b804e71cf02ce19"
  },
  "origin_server_ts": 1629970406976,
  "unsigned": {
    "age": 7255
  },
  "event_id": "$RptGxdCco3P-CTrdWsf2VSb8EaITwFfAMZhzYH9-xWQ",
  "room_id": "!ZFnQcqwxcebAepncKr:feneas.org"
}
```

Working event source (develop.element.io):

```json
{
  "type": "m.room.message",
  "sender": "@mikaela:feneas.org",
  "content": {
    "body": "image.png",
    "info": {
      "size": 242542,
      "mimetype": "image/png",
      "thumbnail_info": {
        "w": 737,
        "h": 600,
        "mimetype": "image/png",
        "size": 140712
      },
      "w": 1248,
      "h": 1015,
      "xyz.amorgan.blurhash": "L45hP$~E-qRjEKInNFofI:InNFof",
      "thumbnail_url": "mxc://matrix.feneas.org/7ff8deafed136f893dab7b750e759f59b9c90988"
    },
    "msgtype": "m.image",
    "url": "mxc://matrix.feneas.org/f4c2deb09e765bcf001e1bdb29ad9acbf2816637"
  },
  "origin_server_ts": 1629970817676,
  "unsigned": {
    "age": 8307,
    "transaction_id": "m1629970817374.12"
  },
  "event_id": "$kd3dAUle5zu1od-K3NIi8w_z3o2N2yyOmchHR2Z7Cmg",
  "room_id": "!ZFnQcqwxcebAepncKr:feneas.org"
}
```

* Recent Element Web Development version regression on the same subject: https://github.com/vector-im/element-web/issues/18702
  * Possibly relevant quote: "the problem is that sailtrix doesn't send the info object, but that object isn't required by the spec"

**Comment by Mikaela** [comment]
While I understand this to be issue on Matterbridge side, [Sailtrix has a matterbridge compatibility issue](https://gitlab.com/HengYeDev/harbour-sailtrix/-/issues/28).

**Comment by Mikaela** [comment]
Sorry for long response time, I have updated Sailtrix on my SailfishOS and can confirm that the new version resolves this and media uploads are getting Matterbridged when sent from it

**Comment by HengYeDev** [comment]
@Mikaela Thanks. Sailtrix gitlab issue closed as well.
