### ISSUE TITLE
Refuse to run if config file has insecure permissions

### ISSUE THREAD

**Issue by vext01** [42wim/matterbridge#158]
Since the config file may contain passwords, perhaps it would be good to refuse to run if the file is accessible to the world (i.e. if 'other' users could see it).

P.S.

Just found this project, and now using it to bridge and IRC channel(from a network not yet officially bridged by matrix-irc-appservice) to matrix. Thanks so much, this is really useful and so much easier to setup than the nodejs bridge.

**Comment by 42wim** [comment]
I'm not sure yet about refusing to run completely, but giving a warning is a good idea.
Thanks for the feedback, I want it to be as easy as possible (and it could still be a lot easier).

**Comment by 42wim** [comment]
I'm not going to add this check. (is user responsibility)
I've made a note about it in the sample and simple configuration files though.
