### ISSUE TITLE
Can't block someone accurately

### ISSUE THREAD

**Issue by liqsliu** [42wim/matterbridge#1581]
**Describe the bug**
somebidy's nick contains space, how to ignore his messages? 
`ingoreNocks="abc 123"`
Entering a space directly may block other people’s messages at the same time

**To Reproduce**

**Expected behavior**

**Screenshots/debug logs**

**Environment (please complete the following information):**

**Additional context**
https://t.me/Matterbridge/16033

**Comment by 42wim** [comment]
You can do this with tengo scripting.
See more information here: https://github.com/42wim/matterbridge/wiki/Tengo
