### ISSUE TITLE
Relay messages from IRC only if they contain the bot's nick

### ISSUE THREAD

**Issue by tkasci** [42wim/matterbridge#1585]
**Is your feature request related to a problem? Please describe.**
I have Telegram messages relayed to IRC and vice versa. However, some users of these channels are annoyed by the additional messages. On IRC, the bot can simple be ignored. On Telegram, users on groups cannot be ignored, so it is impossible to block unwanted messages from IRC. 

**Describe the solution you'd like**
I would like the IRC to Telegram transport to only relay messages that contain the bot's nick. For example, if the bot's nick on IRC was "bridge": 

<tim> bridge: send this to Telegram <- this would get relayed
<tim> send this to Telegram <- this would not

**Describe alternatives you've considered**
It was suggested that I write a Tengo script, but it is not clear if Tengo supports filtering messages.

**Comment by mahdi1234** [comment]
I know it's not straightforward solution, but for now you can use IgnoreMessages directive, I guess your IRC users could learn that.

btw are you talking about real messages or some "service messages"? for the latter the IgnoreMessages can be used as well.
