### ISSUE TITLE
Bridging IRC to Matrix where you have the same username on both causes excessive highlighting.

### ISSUE THREAD

**Issue by vext01** [42wim/matterbridge#159]
I'm not sure there's much you can do about this, but I though I would raise it anyway.

I have the same username on a matrix channel and an IRC channel which I am bridging. I prefix the bridgre messages with the sender nick. This means when I type into the IRC session (using weechat), all my matrix clients ping.

Any thoughts? Thanks

**Comment by 42wim** [comment]
Don't have really any good ideas to solve this with matterbridge, besides something like mangling specific nicks :-) 

I think this is something that should be solved client-side (by scripts that filter specific notifications). (or don't be at the 2 sides of the bridge at the same time ;-)

So I'm going to close this, if you have any good ideas how this could be solved with matterbridge, feel free to reopen.
