### ISSUE TITLE
Ability to omit matrix network from nick.

### ISSUE THREAD

**Issue by vext01** [42wim/matterbridge#160]
When you have a line like this in your config:

```
RemoteNickFormat="<{NICK}> "
```

This will expand remote usernames to (for example):

```
<jim:matrix.org>
```

i.e. the network name is part of the username. It would be nice to be able to omit the network part, and just have:

```
<jim>
```

for example.

How about having a `{NICK_SHORT}` macro in addition to `{NICK}`

Thanks

**Comment by 42wim** [comment]
This seems like a matrix specific issue.
I'll add a matrix specific option for this, maybe NoHomeserverSuffix or something like that.

**Comment by 42wim** [comment]
Ok, I've added this feature in master.
