### ISSUE TITLE
manage XMPP Pings (direct messages)

### ISSUE THREAD

**Issue by zino73** [42wim/matterbridge#161]
hello,

Im trying to get pings from a Xmpp server to discord channel using matterbridge. i already can get channel (groupchat) XMPP message, but unable to do the same with the XMPP pings probably because they are sended to everyone and no in a channel.

so i looked in xmpp.go file and i noticed that matterbridge catch only the type "groupchat":

`if v.Type == "groupchat" `

Is it planned to manage other type?

**Comment by 42wim** [comment]
What exactly do you mean with XMPP ping ? Do you mean https://xmpp.org/extensions/xep-0199.html ?

**Comment by zino73** [comment]
yeah i thuink but im not sure but i already see the message in the command window but he is not routed to discord. this a sample of the message called "ping" :
`<message to="name@domain.com/id" type="chat" xml:lang="en" from="botname@domain.com/NAME"><body>The body messsafe</body></message>`

**Comment by 42wim** [comment]
Ok, that looks like a private message, that will not be bridged 
Matterbridge only relays public channel messages at this time.

**Comment by zino73** [comment]
ok thanks ill try to updade the code soon to manage chat message too

**Comment by 42wim** [comment]
I'm going to close this, more general issue in #191
