### ISSUE TITLE
Revolt Chat Bridge

### ISSUE THREAD

**Issue by Aikatsui** [42wim/matterbridge#1619]
**Revolt** - Communication is critical. Privacy is essential
The best and first opensource alternative to discord platform

Resources:
https://revolt.chat/
https://github.com/revoltchat
https://gitlab.insrt.uk/revolt
https://developers.revolt.chat/api/
https://github.com/revoltchat/revolt.js

**Comment by EpicLPer** [comment]
Definitely second this!
