### ISSUE TITLE
Wiki doesn't document how to use new libtgsconverter

### ISSUE THREAD

**Issue by BenWiederhake** [42wim/matterbridge#1638]
**Describe the bug**

I've seen #1569, but by reading the code I don't understand how to make sure that the new `libtgsconverter` is used.

**To Reproduce**
- Open and read https://github.com/42wim/matterbridge/wiki/Settings#mediaConverttgs

**Expected behavior**
- Text appears that says something like ``To choose the backend, use either `LottieBackend=lottie_convert` or `LottieBackend=libtgsconvert`.``

**Additional context**
Thank you very much for #1569, I just don't grok how to switch backends :D

CC @Benau

**Comment by 42wim** [comment]
This has recently changed in master, use `go build -tags cgolottie` it'll automatically use the libtgsconvert
