### ISSUE TITLE
!messages do not go through bridge

### ISSUE THREAD

**Issue by bhanderson** [42wim/matterbridge#164]
Please answer the following questions. 

### Which version of matterbridge are you using?
0.12.0-dev

### If you're having problems with mattermost please specify mattermost version. 
Version: 3.8.0  (3.8.2)

### Please describe the expected behavior.
When sending a message from mattermost to irc using the message '!<any message here>' It sends the message

#### Use logs from running ```matterbridge -debug``` if possible.
It does not send the message

DEBU[2017-05-08T09:42:13-07:00] WsReceiver: model.WebSocketEvent{Event:"typing", Data:map[string]interface {}{"parent_id":"", "user_id":"xxx"}, Broadcast:(*model.WebsocketBroadcast)(0xc8202ef240), PreComputeJson:[]uint8(nil)}  module=matterclient
DEBU[2017-05-08T09:42:13-07:00] map[string]interface {}{"parent_id":"", "user_id":"xxx"}  module=mattermost
DEBU[2017-05-08T09:42:14-07:00] WsReceiver: model.WebSocketEvent{Event:"posted", Data:map[string]interface {}{"channel_display_name":"xxx", "channel_name":"xxx", "channel_type":"P", "post":"{\"id\":\"xxx\",\"create_at\":1494261734878,\"update_at\":1494261734878,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"xxx\",\"channel_id\":\"xxx\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"!test\",\"type\":\"\",\"props\":{},\"hashtags\":\"\",\"pending_post_id\":\"xxx:xxx\"}", "sender_name":"xxx", "team_id":"xxx"}, Broadcast:(*model.WebsocketBroadcast)(0xc82033d880), PreComputeJson:[]uint8(nil)}  module=matterclient
DEBU[2017-05-08T09:42:14-07:00] map[string]interface {}{"channel_display_name":"xxx", "channel_name":"xxx", "channel_type":"P", "post":"{\"id\":\"xxx\",\"create_at\":1494261734878,\"update_at\":1494261734878,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"xxx\",\"channel_id\":\"xxx\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"!test\",\"type\":\"\",\"props\":{},\"hashtags\":\"\",\"pending_post_id\":\"xxx:xxx\"}", "sender_name":"xxx", "team_id":"xxx"}  module=mattermost
DEBU[2017-05-08T09:42:14-07:00] Receiving from matterclient &matterclient.Message{Raw:(*model.WebSocketEvent)(0xc82033d840), Post:(*model.Post)(0xc820516400), Team:"xxx", Channel:"xxx", Username:"xxx", Text:"!test", Type:""}  module=mattermost
DEBU[2017-05-08T09:42:14-07:00] Sending message from xxx on mattermost.xxx to gateway  module=mattermost
DEBU[2017-05-08T09:42:14-07:00] Sending config.Message{Text:"!test", Channel:"xxx", Username:"xxx", Avatar:"", Account:"mattermost.xxx", Event:"", Protocol:"", Timestamp:time.Time{sec:63629858534, nsec:884939936, loc:(*time.Location)(0x1075ee0)}} from mattermost.xxx (xxx) to irc.xxx (#xxx)
DEBU[2017-05-08T09:42:14-07:00] Receiving config.Message{Text:"!test", Channel:"#xxx", Username:"", Avatar:"", Account:"mattermost.xxx", Event:"", Protocol:"mattermost", Timestamp:time.Time{sec:63629858534, nsec:884939936, loc:(*time.Location)(0x1075ee0)}}  module=irc

### Any steps to reproduce the behavior?
set up irc-mattermost bridge, send from mattermost to irc "!test"

#### (be sure to exclude or anonymize private data (tokens/passwords))
[irc]
 [irc.xxx]
  Server="xxx:6697"
  Nick="matterbot"
  UseTLS=true
  SkipTLSVerify=true
  NickServPassword="xxx"

[mattermost]
 [mattermost.xxx]
  useAPI=true
  Server="xxx"
  Team="xxx"
  Login="xxx"
  Password="xxx"
  PrefixMessagesWithNick=true
  RemoteNickFormat="{NICK}: "

[[gateway]]
 name="mygateway"
 enable=true
  [[gateway.inout]]
   account="irc.xxx"
   channel="#xxx"

  [[gateway.inout]]
   account="mattermost.xxx"
   channel="xxx"

**Comment by 42wim** [comment]
Ok, just fixed in master.
Let me know if you still have issues.

**Comment by bhanderson** [comment]
Fixed! Thank you!
