### ISSUE TITLE
Any willingness to port this to whatsmeow

### ISSUE THREAD

**Issue by XP-Fan** [42wim/matterbridge#1642]
Hey friends, first of all thank you for this mega amazing project and sorry if this has a doublicate but I couldn't find it yet, which I think is a bit weird considering how many people write issues in here. Anyway: Currently you're using gowhatsapp, which requires a persistent connection to a phone. So, basically a phone is a single point of failure for the whatsapp-bridge. I wonder whether you'd be willing to port this to whatsmeow (https://github.com/tulir/whatsmeow) which is also a go-library to interact directly with whatsapp's new multi device API, so the phone is no longer permanently needed?

**Comment by 42wim** [comment]
it's on my todo, but no time yet.
I'm of course willing to accept PRs also.

**Comment by XP-Fan** [comment]
Well perfect! So far I guess we still have around 6 months till the websocket-API will be deprecated, so it's awesome to know that whatsapp in matterbridge will still have a future afterwards. Unfortunately I personally cannot help you because I never worked with highlevel languages, I'm a hardcore pure assembly-guy.

**Comment by XP-Fan** [comment]
So, since I just realized that I cannot scan a QR-code with Android on a raspberrypi by any means, I wouldn't know of any stationary device one could use to run a bridge bot permanently. I mean you cannot leave a phone connected to a charger for years as this would destroy the battery which might then just blow up and explode. This way I guess that thing is rather urgent, so can anyone give me a timeframe till when this will be implemented? I could also donate a bit, or I'll have to try to find and hire some coder to do it or make an alternative.

**Comment by qaisjp** [comment]
You can run a VM, as documented on wiki: https://github.com/42wim/matterbridge/wiki/Section-WhatsApp-%28basic%29#is-it-possible-to-run-wa-on-virtual-android-vm

**Comment by XP-Fan** [comment]
Well I wonder how this could be considered practical given that V4L2 only supports a single data stream, which is a problem for QR-readers. This was also why I wasn't able to scan the code on the raspberrypi. Besides the AVD-thing is super complex to do, it requires you install Java and other trash, so one would have to buy a dedicated computer (probably at least a gaming-grade one) to get this to work performantly.

**Comment by XP-Fan** [comment]
BTW: WhatsApp for KaiOS doesn't support WhatsApp Web.

**Comment by webmeister** [comment]
> So far I guess we still have around 6 months till the websocket-API will be deprecated

Rhymen/go-whatsapp has already been effectively discontinued, see https://github.com/Rhymen/go-whatsapp/issues/622.

Porting to whatsmeow might also fix other WhatsApp issues like https://github.com/42wim/matterbridge/issues/1363.

**Comment by 42wim** [comment]
There is now PR #1702 can anyone test this and report back? I don't have/use whatsapp, so it's blind ported :)
You can also find artifacts below on: https://github.com/42wim/matterbridge/actions/runs/1770089248

**Comment by XP-Fan** [comment]
Yo sorry I've been real busy these days, however now I cannot seem to download the binary. I can see it in the table of the artifacts but it's not clickable. No clue what to do here. Could you please direct-link me to the macos binary?

-----Original Message-----

**Comment by 42wim** [comment]
Updated artifacts at https://github.com/42wim/matterbridge/actions/runs/1974831353

- darwin/macos: https://github.com/42wim/matterbridge/suites/5637461002/artifacts/184027922
- linux: https://github.com/42wim/matterbridge/suites/5637461002/artifacts/184027923
- windows: https://github.com/42wim/matterbridge/suites/5637461002/artifacts/184027924
