### ISSUE TITLE
Use one IRC connection per Mattermost user

### ISSUE THREAD

**Issue by jmallach** [42wim/matterbridge#165]
I am trying to integrate matterbridge in my new Mattermost instance to ease the transition from our private IRC instance to Mattermost.

The Mattermost part of the integration is good enough: via incoming/outgoing hooks, users on IRC are relayed on Mattermost and their nick is impersonated, etc. Just as it should.

However, the IRC part is not so great: my matterbot IRC user just relays messages from Mattermost by appending the name of the user there:

`<matterbot> <joe> hello from mattermost`

I see how Matrix connects to IRC by providing a IRC connection per Matrix user, so you end up having multiple [m] users that are participating in IRC via Matrix: joe[m], jordi[m], paula[m], etc. The obvious result is:

`<joe[m]> hello from mattermost`

which is a lot more readable. Matrix connects every [m] user via a unique IPv6 for each, which helps avoiding server limits, etc.

Is this something that could be considered in the future?

### Please add your configuration file 

[irc]
    [irc.company]
    Server="irc.company.com:6687"
    UseTLS=true
    SkipTLSVerify=false
    Nick="matterbot"
    Password="supersecret"
    PrefixMessagesWithNick=true
    RemoteNickFormat="<{NICK}[MM]> "

[mattermost]
    [mattermost.company]
    URL="https://mm.company.com/hooks/xxx"
    BindAddress="127.0.0.1:9900"
    useAPI=false
    PrefixMessagesWithNick=false
    RemoteNickFormat="{NICK}"

[[gateway]]
name="gateway1"
enable=true
inout = [
    { account="irc.company", channel="#secrettest" },
    { account="mattermost.company", channel="town-square" },
]

**Comment by 42wim** [comment]
I'll have to think about this, because the next question is probably going to be that private messages should also work ? ;-)

The current version only works for public chat. Private chat is something I'm willing to implement, but I can't give you any promises or dates.

But did you take a look at matterircd ? If the use-case is that some people don't really want to switch to web-based, but want to use irc, you could use matterircd. Matterircd is a stand-alone irc server, multiple users can connect, but can only interact with mattermost users (non-mattermost users aren't visible to each other) (https://github.com/42wim/matterircd)

**Comment by jmallach** [comment]
Hi wim,

I discovered matterircd literally 2 minutes after scribbling this bug report. matterbridge à-la-Matrix would probably suit me better, but I need to give this a try.

Indeed, next on the issue tracker would be privmsgs going across. 😆

My IRC setup relies on individual server passwords for each user, so I'm not sure if that would accommodate at all with mattericd. I understand it has basic auth support though.

I'll let you know, thanks!

**Comment by jmallach** [comment]
Hi Wim,

While I think improvements to matterbridge along the proposed lines would make it better, for my particular usage, matterircd seems to do the job well enough. Thanks for your suggestion. :)

**Comment by NikkyAI** [comment]
most irc networks ban bots that do that though.. or require special whitelisting, so if this is implemented i hope there is going to be a way to use it to old way.. one irc connection for everything

**Comment by 42wim** [comment]
Not going to implement this
