### ISSUE TITLE
Support mattermost 6.2

### ISSUE THREAD

**Issue by mfortini** [42wim/matterbridge#1666]
Mattermost plugin exits with error due to version 6.2 not being recognized.

Ignoring version works.

Only error (maybe unrelated):
`level=error msg="error:websocket: close 1006 (abnormal closure): unexpected EOF" prefix=matterclient`

**Comment by 42wim** [comment]
What plugin are you talking about exactly?

**Comment by mfortini** [comment]
matterclient

**Comment by 42wim** [comment]
Could you please give the output where it actually fails?
You're probably using an outdated matterbridge version, there are no version checks anymore since v1.23.1

**Comment by mfortini** [comment]
nevermind, thank you. It was a problem stemming from certificate issues.
