### ISSUE TITLE
Mattermost private to Gitter?

### ISSUE THREAD

**Issue by jcw** [42wim/matterbridge#167]
Hello - is there a way to bridge messages from a _private_ MM room **TO** a _private_ Gitter room?

I've succeeded in linking up things from G to MM, using MB version 0.12.0 8c7549a:

The config file is currently more or less as follows:

```
[mattermost.blah]
URL="http://..."
BindAddress="0.0.0.0:9999"
SkipTLSVerify=true

[gitter]
[gitter.blah]
Token="..."

[[samechannelgateway]]
   name="mysamechannel"
   enable = true
   accounts = [ "mattermost.blah","gitter.blah" ]
   channels = [ "foobar" ]
```

**Comment by 42wim** [comment]
Yes this should work, but not using samechannelgateway, because channel names aren't the same on gitter as on mattermost (user/room and channel).

So
```
[[gateway]]
    name = "mygateway"
    enable=true

    [[gateway.inout]]
    account = "mattermost.blah"
    channel = "foobar"

    [[gateway.inout]]
    account = "gitter.blah"
    channel = "user/foobar"
```

**Comment by jcw** [comment]
Thanks, but the example I posted does work one way already. I'm bridging to the default channel associated with an organisation. It seems to me that it's not a naming issue (I tried aaa/bbb naming, but that  generated a connect error), but a problem of not being able to send out the Mattermost channel messages - the _private_ room I want to send from isn't shown in the Channel pop-up list for outbound web hooks.

**Comment by 42wim** [comment]
Ok, seems like I didn't read it correctly :-)

If you're using mattermost with webhooks then private channels don't work, mattermost doesn't support this. You'll need to use the API for this (and create a dedicated user that is joined in the private channel).

I'm curious about the gitter naming though, I've just created an organisation to test this, but I need to specify ```organisation/lobby``` just  ```organisation``` doesn't work.

**Comment by jcw** [comment]
Aha, thanks - I'll try the API approach.

Not sure why/how, but it really works here (G=>MM). There may have been changes to Gitter after I set this up, I have some vague recollection of that. Maybe the single-path version is no longer offered? Other rooms work as you describe: orgname/roomname.
