### ISSUE TITLE
Discord Slack bridge - Embedded Discord messages are not shown in Slack

### ISSUE THREAD

**Issue by antonionardella** [42wim/matterbridge#1680]
**Is your feature request related to a problem? Please describe.**
Embedded Discord messages are not shown in Slack

This is how it looks like in Discord
![image](https://user-images.githubusercontent.com/7383572/149617994-9900244c-2082-4324-9b5b-9427f52399cf.png)

This is what Slack shows
![image](https://user-images.githubusercontent.com/7383572/149618011-93bcb56b-e927-423b-8a0c-d59cfdc52af1.png)

**Describe the solution you'd like**
Support the bridging of Discord embeds as messages in Slack

**Describe alternatives you've considered**

**Additional context**
Embeds Discord API description: https://v12.discordjs.guide/popular-topics/embeds.html

**Comment by 42wim** [comment]
Enable `showEmbeds=true` in your discord config.
See https://github.com/42wim/matterbridge/wiki/Settings#showembeds
