### ISSUE TITLE
can we add a one way bridge to a text file

### ISSUE THREAD

**Issue by KingPin** [42wim/matterbridge#1688]
**Is your feature request related to a problem? Please describe.**
we have a support channel bridged to multiple apps for our OSS project, and we get plenty of repeat questions and I would like a solution to people asking the same questions over and over when they could possibly search old chat. (yeah right.... I'm allowed to dream....)

**Describe the solution you'd like**
I would like to log one of the bridges to text file(s) or a db(?)

**Describe alternatives you've considered**
not sure what alternatives I could use tbh.

thank you.

**Comment by haykam821** [comment]
You can poll the API in another process directly into another file.

**Comment by KingPin** [comment]
thank you, I will look at the API.

**Comment by 42wim** [comment]
or look into tengo scripts - https://github.com/42wim/matterbridge/wiki/Tengo
