### ISSUE TITLE
Messages from Discord to Mumble

### ISSUE THREAD

**Issue by timon49** [42wim/matterbridge#1689]
Thank you for your work! The question arose : Is the output of messages from Discord in Mumble not implemented yet , or am I doing something wrong ? ... P.S. Messages from Mumble to Discord come perfectly, but not back =/ Thanks in advance for the help..

**Comment by Lucifer1590** [comment]
can you post your conf file it may be because of that Remove any PII

**Comment by 42wim** [comment]
Try running with `--debug` when you send a message in discord and paste the output here.

**Comment by 42wim** [comment]
closing because no feedback
