### ISSUE TITLE
Unsupported Version of MatterMost Error

### ISSUE THREAD

**Issue by dg01d** [42wim/matterbridge#169]
Please answer the following questions. 

### Which version of matterbridge are you using?
v ersion: 0.12.0 8c7549a

### If you're having problems with mattermost please specify mattermost version. 
Current version is 3.8.0 (3.8.2/Fri Apr 21 21:30:35 UTC 2017)

### Please describe the expected behavior.
Establishing connection to mattermost, matterbridge should connect to relay information. This connection fails.

### Please describe the actual behavior. 

```
INFO[2017-05-15T12:24:23-04:00] Starting bridge: mattermost.work
INFO[2017-05-15T12:24:23-04:00] Connecting matBot (team: ascraeus) on caconym.ascraeus.org  module=mattermost
DEBU[2017-05-15T12:24:23-04:00] ":irc.server.org 001 matterbot :Welcome to the Internet Relay Chat Network matterbot"  module=irc
FATA[2017-05-15T12:24:23-04:00] Starting gateway failed: Bridge mattermost.work failed to start: unsupported mattermost version:
```

#### (be sure to exclude or anonymize private data (tokens/passwords))

```
[irc]
    [irc.linux]
    Server="irc.server.org:6667"
    Nick="matterbot"

[mattermost]
    [mattermost.work]
    useAPI=true
    #do not prefix it with http:// or https://
    Server="caconym.ascraeus.org"
    Team="hidden"
    Login="matBot"
    Password="hidden"
    PrefixMessagesWithNick=true

[[gateway]]
name="mygateway"
enable=true
    [[gateway.inout]]
    account="irc.linux"
    channel="#channel"

    [[gateway.out]]
    account="mattermost.work"
    channel="linux"
```

**Comment by 42wim** [comment]
caconym.ascraeus.org hasn't https enabled, so you have to specify ```NoTLS=true```

```
#Enable this to make a http connection (instead of https) to your mattermost.
#OPTIONAL (default false)
NoTLS=true
```

**Comment by dg01d** [comment]
Oh wowzers. I read that completely inverted. Thank you.
