### ISSUE TITLE
username is missing in mattermost

### ISSUE THREAD

**Issue by Stiefel1234eu** [42wim/matterbridge#1694]
**Describe the bug**
Idk if I missconfigured something.. but I cannot figure it out why usernames are not displayed in mattermost.
I try to connect Discord with mattermost

mattermost > Discord
discordbot name gets replaced with mattermost username

Discord > mattermost
mattermostbot name gets not replaced with discord name

**To Reproduce**
Setup: Docker containers

**Expected behavior**
mattermostbot name gets replaced with discord name

**Additional context**
[discord.allgemein]
Token="token"
Server="id"
AutoWebhooks=true
RemoteNickFormat="{NICK}"

[mattermost.allgemein]
Server="server.de"
Team="team"
Login="username"
Password="password"
RemoteNickFormat="{NICK}"
PrefixMessagesWithNick=true

[[gateway]]
name="gateway1"
enable=true

   [[gateway.inout]]
   account="discord.allgemein"
   channel="ID:910885936722767897"

   [[gateway.inout]]
   account="mattermost.allgemein"
   channel="town-square"

**Comment by 42wim** [comment]
Mattermost only support impersonation for incoming webhooks, you'll need to create one and add `WebhookURL="https://yourdomain/hooks/yourhookkey"` to your mattermost config.
