### ISSUE TITLE
When encryption is enabled in Matrix room, the bridge doesn't work

### ISSUE THREAD

**Issue by szclsya** [42wim/matterbridge#170]
### Version of matterbridge
0.12.0

### Actual behavior. 
When encryption is enabled in a matrix room, messages can be forwarded from other messaging software by matterbridge, but messages sent in the room using matrix clients are not able to be forwarded to other messaging softwares. (The message sent by matrix client doesn't show in debug mode.)

### Any steps to reproduce the behavior?
Just create an encrpted room, add the matterbridge, and send a message from some other messaging software. (In my case, it is telegram.)

### Configuration file 
```
[telegram]
	[telegram.tggroup]
	Token="BotKey"

MessageFormat="HTML"
EditDisable=false
EditSuffix=""
IgnoreNicks=""
RemoteNickFormat="[<b>{NICK}</b>]"
ShowJoinPart=true

[matrix]
	[matrix.mgroup]
	Server="address"
	Login="username"
	Password="password"

	PrefixMessagesWithNick=true
	IgnoreNicks=""
	RemoteNickFormat="[{NICK}] "
	ShowJoinPart=true


[[gateway]]
	name="test"
	enable=true

	[[gateway.inout]]
	account="telegram.tggroup"
	channel="channelNum"
	
	[[gateway.inout]]
	account="matrix.mgroup"
	channel="#agroup.matrix.org"
```
Thanks for your work!

**Comment by 42wim** [comment]
Hi, thanks for reporting
Unfortunately encrypted rooms aren't supported (not yet implemented) in the library I use. 
See https://github.com/matrix-org/gomatrix/issues/15
I've just added a note about this in matterbridge.toml.sample

**Comment by Mikaela** [comment]
Potential workaround: you could run [Pantalaimon](https://github.com/matrix-org/pantalaimon) in the middle of Matterbridge and the Matrix server like a [IRC bouncer](https://en.wikipedia.org/wiki/BNC_(software)).
