### ISSUE TITLE
UserRequired error when using a token or User/Pass

### ISSUE THREAD

**Issue by nwl** [42wim/matterbridge#1734]
Using Matterbridge between IRC and Mattermost. I get an error of:

[0005] FATAL main:         Starting gateway failed: Bridge mattermost.work failed to start: : Invalid or expired s
ession, please login again.,

Enabling debug on Mattermost, I see:

`{"timestamp":"2022-02-09 17:36:23.866 Z","level":"debug","msg":"Invalid or expired session, please login again.","caller":"web/context.go:101","path":"/mattermost/api/v4/users/logout","request_id":"m631na9ao3yyjqozsufx8wip7c","ip_addr":"127.0.0.1","user_id":"","method":"GET","err_where":"","http_code":401,"err_details":"UserRequired"}`

My config on the Mattermost section is:

    [mattermost.work]
    Server="localhost:8065"
    NoTLS=true
    Team="Test"
    Token="xxxxxxxxxx"

The token is associated with a bot account. I get the same error when using a Token associated with a user account and with a user/pass instead of a token.

 - OS: Ubuntu 20.04
 - Matterbridge version: 1.24.0 65c7ac80

**Comment by 42wim** [comment]
Sorry, I can't help you with that, looks like a mattermost configuration issue.
I suggest you post your message on https://forum.mattermost.org/
