### ISSUE TITLE
UseUsername=true on discord not functioning, still shows bot then nick in message.

### ISSUE THREAD

**Issue by otnooishphoo** [42wim/matterbridge#1735]
### Environment

Version: 1.18.3 8b26e42a

Operating system: ubuntu 20.04

### Please describe the expected behavior.
UserUserName=true 
Should replace the Bot name with the Username

### Please describe the actual behavior. 

Still displays message as coming from the Bot with the nick in the message text.

### Any steps to reproduce the behavior?

It just started happening on a new install.
Previous old docker version works fine.
Is there a specific order the config lines need to be in?

### Please add your configuration file 

`#-------------------------
[discord.bonk]
Token="---"
Server="---" # picked from guilds the bot is connected to
UseUserName=true
AutoWebhooks=true
RemoteNickFormat="[{NICK}] "
ShowEmbeds=true

#-------------------------
[slack]
[slack.bonk]
Token="---"
UseUserName=true
RemoteNickFormat="[{NICK}] "
PreserveThreading=true
ShowUserTyping=true`

**Comment by 42wim** [comment]
version 1.18.3 ? please upgrade to 1.24.0 and if still an issue reopen.

**Comment by otnooishphoo** [comment]
Updated to 1.24 still broken... thanks.

**Comment by 42wim** [comment]
Run with `--debug` send a message from slack and paste logs here.

**Comment by otnooishphoo** [comment]
well.  it was broken.. but suddenly started working.  No explanation.... close this I guess...
