### ISSUE TITLE
Replying to discord messages from matrix not working correctly

### ISSUE THREAD

**Issue by neutralinsomniac** [42wim/matterbridge#1738]
**Describe the bug**
If I reply to a discord message that has been bridged into matrix, from my matrix account, the reply shows up like:

```
[thread]: 
<my reply>
```

in discord instead of including the original message in the reply.

**To Reproduce**
1. Send a message in a discord room that is bridged to a matrix room.
2. Reply to the message from the matrix room.
3. Observe odd `[thread]:` reply context behavior in discord

**Expected behavior**
I expect the reply to look more like a discord-native reply, where the original message is referenced, or at the very least, quoted.

**Screenshots/debug logs**
Use logs from running `matterbridge -debug` if possible.

**Environment (please complete the following information):**
 - OS: Debian 11
 - Matterbridge version: 1.24.0 65c7ac80

**Additional context**
matterbridge.toml:
```
Token="REDACTED"
Server="337985133569114113"
RemoteNickFormat="{NICK}"
AutoWebhooks=true

[matrix.mymatrix]
Server="https://pintobyte.com:8448"
Login="@discord:pintobyte.com"
Password="REDACTED"

RemoteNickFormat="<{NICK}> "
NoHomeServerSuffix=true

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="ID:442816774082134026"

[[gateway.inout]]
account="matrix.mymatrix"
channel="#9fans:pintobyte.com"

[[gateway]]
name="gateway2"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="ID:442816800120504331"

[[gateway.inout]]
account="matrix.mymatrix"
channel="#9fans9:pintobyte.com"

[[gateway]]
name="gateway3"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="ID:624290057389473832"

[[gateway.inout]]
account="matrix.mymatrix"
channel="#9fansinferno:pintobyte.com"
```

**Comment by 42wim** [comment]
See https://github.com/42wim/matterbridge/wiki/Section-Discord-%28basic%29
```
# Map threads from other bridges on discord replies
PreserveThreading=true
```
