### ISSUE TITLE
Replies from matrix come through to discord from the bot user instead of the webhook-faked name/avatar

### ISSUE THREAD

**Issue by neutralinsomniac** [42wim/matterbridge#1739]
**Describe the bug**
Reply to a message on matrix, and on discord, the reply comes from the bot user, with the actual sender of the reply in the message text, followed by the message underneath that.

It looks like this:
```
<Matrix Bot>
sender
Message
```

Instead of like this:
```
<Sender>
Message
```

**To Reproduce**
Reply to a message on matrix, observe the bridged message in discord not appearing to come from the user that sent it, and instead coming from the bot user.

**Expected behavior**
I would expect replies to show as coming from the user that sent them, the same way that normal messages do.

**Environment (please complete the following information):**
 - OS: Debian 11
 - Matterbridge version: 1.24.0 65c7ac80

**Additional context**
```
[discord.mydiscord]
Token="<REDACTED>"
Server="337985133569114113"
RemoteNickFormat="{NICK}"
AutoWebhooks=true
PreserveThreading=true

[matrix.mymatrix]
Server="https://pintobyte.com:8448"
Login="@discord:pintobyte.com"
Password="<REDACTED>"

RemoteNickFormat="<{NICK}> "
NoHomeServerSuffix=true

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="ID:442816774082134026"

[[gateway.inout]]
account="matrix.mymatrix"
channel="#9fans:pintobyte.com"

[[gateway]]
name="gateway2"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="ID:442816800120504331"

[[gateway.inout]]
account="matrix.mymatrix"
channel="#9fans9:pintobyte.com"

[[gateway]]
name="gateway3"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="ID:624290057389473832"

[[gateway.inout]]
account="matrix.mymatrix"
channel="#9fansinferno:pintobyte.com"
```

**Comment by 42wim** [comment]
See https://github.com/42wim/matterbridge/issues/1558#issuecomment-1030713994
