### ISSUE TITLE
Discord API being deocommissioned 

### ISSUE THREAD

**Issue by TheHolyRoger** [42wim/matterbridge#1757]
Discord API v6 & 7 will be decommissioned April 30th, matterbridge uses v6 so it will cease to work with discord, at all :)

https://github.com/discord/discord-api-docs/discussions/4510

**Comment by TheHolyRoger** [comment]
Ha, ok sorry man I thought it was v6 because I looked at this one: https://github.com/42wim/discordgo/blob/master/endpoints.go#L15

**Comment by 42wim** [comment]
we're switching back to upstream in #1759 now they also have file uploading via webhook
