### ISSUE TITLE
Matterbridge doesn't bridge messages from Telegram Bot to WhatsApp

### ISSUE THREAD

**Issue by VEDsamohT** [42wim/matterbridge#1763]
**Describe the bug**
Any bot messages doesn't get bridged to WhatsApp.

**Expected behavior**
I expected that every message in the group was bridged to the Whatsapp.

**Screenshots**
Telegram side:

![Screenshot_1](https://user-images.githubusercontent.com/101485206/158250478-585f219d-cd7c-4684-bc8d-bb7ef37aac44.png)

Whatsapp side:

![image](https://user-images.githubusercontent.com/101485206/158250573-850e659e-286f-47e0-8992-acafd6e2ba64.png)

**Environment**
 - OS: Windows 10, 64 bits
 - Matterbridge version: 1.24.0-windows-64bit

**Additional context**

I have tested with other user on Telegram beside mine and the message arrive succefully. It's just the bot message that can't.

**Configuration file**

[telegram.mytelegram]
Token="MYTBOTID"
RemoteNickFormat=""
MessageFormat="HTMLNick"

[whatsapp.mywhatsapp]
Number="MYNUMBER"
SessionFile="session-MYNUMBER.gob"
QrOnWhiteTerminal=false
RemoteNickFormat=""

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="telegram.mytelegram"
channel="CHATID"

[[gateway.inout]]
account="whatsapp.mywhatsapp"
channel="GROUPID"

**Comment by 42wim** [comment]
https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots

**Comment by VEDsamohT** [comment]
sad.
