### ISSUE TITLE
Version 1.24.1 seems to incorrectly have the dev suffix

### ISSUE THREAD

**Issue by haykam821** [42wim/matterbridge#1769]
As reported by `./matterbridge --version`, the version is `1.24.1-dev 24bc0f12`. Unlike previous versions, the release commit (24bc0f127b0417796298b0b16735b7fec1f90d57) did not change this version to remove the `-dev` suffix.

**Comment by 42wim** [comment]
Good catch, seems I unfortunately forgot a version bump, as this has no other impact I'm not going to release a 1.24.2 just to fix this :)
