### ISSUE TITLE
Newest Telegram video stickers are not being relayed nor converted properly

### ISSUE THREAD

**Issue by King-Mucus** [42wim/matterbridge#1788]
**Describe the bug**
Telegram recently released support for a new kind of video stickers (example: https://t.me/addstickers/tom_jerry_videosticks). Their formate seems to be webm. However, they are not being relayed or converted properly, unlike the older .webp stickers. This happens on official Matterbridge channels, as well as on any other I tested.

**To Reproduce**
Just use some of the stickers from https://t.me/addstickers/tom_jerry_videosticks on any bridged Telegram channel/group.

**Expected behavior**
Said stickers should display properly on the other platforms, or at least have a proper link instead.

**Screenshots/debug logs**
![20220402_17h33m01s_grim](https://user-images.githubusercontent.com/70046572/161400375-c0a8a3ac-b8a8-48b1-9dc9-0716653729a4.png)
![20220402_17h33m36s_grim](https://user-images.githubusercontent.com/70046572/161400378-186fb418-bf85-4e14-b845-869d5b3453d0.png)
![20220402_17h36m23s_grim](https://user-images.githubusercontent.com/70046572/161400379-ecd81555-2018-42f5-b6c9-ded36d634584.png)

**Environment (please complete the following information):**
 - OS: Gentoo Linux
 - Matterbridge version: 1.24.1

**Comment by King-Mucus** [comment]
It would be cool if `MediaConvertTgs` also applied to these new .webm stickers, and/or if there was a new MediaConvertWebMToPNG, MediaConvertWebMToWebP or even MediaConvertWebMToGIF option.

**Comment by 42wim** [comment]
Run with `--debug` and paste logs when posting stickers

**Comment by King-Mucus** [comment]
[telegramstickers.log](https://github.com/42wim/matterbridge/files/8405825/telegramstickers.log)

**Comment by 42wim** [comment]
@King-Mucus can you try PR #1802 ?

**Comment by King-Mucus** [comment]
> @King-Mucus can you try PR #1802 ? It doesn't try to modify the .webm files and sends them as-is

Just tried it. Seems to be working great on Element web. Thank you very much! Very nice job! :)
