### ISSUE TITLE
Request: Limit the length of single line of text for IRC

### ISSUE THREAD

**Issue by Gummikavalier** [42wim/matterbridge#179]
Would it be possible to have a max limit for one line messages, preferably with additional [message clipped] message, or with a custom message in the style of [read more at xxxxx]?

We have a problem that when someone pastes very long one line paragraph, it causes excess flood and kicks matterbridge bot out of the IRC server.

When this happens Matterbridge does get back online, but it doesn't rejoin the channel. Fixing this would be helpful too, of course. However, a simple message about clipping would be tidier and more informative to the people that the message was cut in the first place.

According to [RFC](https://www.ietf.org/rfc/rfc1459.txt) the limit directly in IRC protocol is 512 characters and it must include the command and all parameters for the message. It does not seem to be configurable in any way, at least not in ircd.
In our test case max length of one message (what you get) seemed to be 482 characters. It is likely that lower value was caused by the need of aforementioned command and parameters not visible to the user.

**Comment by 42wim** [comment]
Ok, I've added it to master. Made default length 400, to be on safe side (RemoteNickFormat length can differ).
You can change it yourself by adding ```MessageLength=400``` to your ```[irc.name]``` section.

**Comment by Gummikavalier** [comment]
That was fast. Thank you for this and, of course, Matterbridge. :)
