### ISSUE TITLE
Matterbridge 1.24.1 released as trunk version

### ISSUE THREAD

**Issue by dgilman** [42wim/matterbridge#1790]
**Describe the bug**
The [matterbridge-1.24.1-linux-64bit](https://github.com/42wim/matterbridge/releases/download/v1.24.1/matterbridge-1.24.1-linux-64bit) binary published for the 1.24.1 release is putting a warning in the log file on startup:

```
time="2022-04-03T20:50:40Z" level=info msg="WARNING: THIS IS A DEVELOPMENT VERSION. Things may break." prefix=main
time="2022-04-03T20:50:40Z" level=info msg="Running version 1.24.1-dev 24bc0f12" prefix=main
```

**To Reproduce**
Start the binary

**Expected behavior**
Sounds like a minor CI bug hopefully

**Comment by 42wim** [comment]
Yes unfortunately I've released it without bumping the version.
I've just release 1.25.0 with correct version bump though :)
