### ISSUE TITLE
Messages not being relayed from Matrix anymore

### ISSUE THREAD

**Issue by King-Mucus** [42wim/matterbridge#1798]
Messages stopped being relayed to Matrix at around 15:00 UTC (April 7, 2022). Messages posted on Matrix are being sent just fine to the other platforms.

This affects multiple federations (matrix.org and catgirl.cloud, for instance) and bridging software (like t2bot.io).

**Comment by 42wim** [comment]
Did you try to restart matterbridge ?

**Comment by King-Mucus** [comment]
Closing app.element.io and reopening it solved the issue. Silly me.

Sorry for this and thank you for caring. :)
