### ISSUE TITLE
m.User.TeamId undefined

### ISSUE THREAD

**Issue by guyguy333** [42wim/matterbridge#18]
Hi,

I get a build error when I try to install matterbridge 

> go get github.com/42wim/matterbridge
> src/github.com/42wim/matterbridge-plus/matterclient/matterclient.go:189: m.User.TeamId undefined (type *model.User has no field or method TeamId)

I'm using go1.5 linux/amd64 on CentOS 7. Does Matterbridge require Go 1.6 ?

Thanks

**Comment by 42wim** [comment]
I'm using go 1.6, but go 1.5 should also work if you put  ```export GO15VENDOREXPERIMENT=1``` before compiling, so that the vendor directory is used.

**Comment by guyguy333** [comment]
@42wim Thank you, it solved the issue.
