### ISSUE TITLE
All messages are shown to be send by the same user.

### ISSUE THREAD

**Issue by TomTheDragon** [42wim/matterbridge#181]
### Which version of matterbridge are you using?
0.12.1

### Please describe the expected behavior.
To be able to see different username for different users.

### Please describe the actual behavior. 
All messages are shown to be send by the same user. The username that is shown changes sometimes but its really kind of random.

### Any steps to reproduce the behavior?
Make a bridge between Telegram, Discord and XMPP

### Please add your configuration file 
[xmpp]
[xmpp.1]
Server="xmppserver.com:5222"
Jid="user@xmppserver.com"
Password="thisisaverygoodpassword"
Muc="conference.xmppserver.com"
Nick="#"

[discord]
[discord.1]
Token="M00000000000000000000000000000.A0000000000000000000000000"
Server="300000000000000000"

[telegram]
[telegram.1]
Token="300000000:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
MessageFormat="HTML"
UseFirstName=false

[general]
SkipTLSVerify=true
EditDisable=false
EditSuffix=" (edited)"
ShowJoinPart=false
RemoteNickFormat="{NICK}: "

[[gateway]]
name="gateway1"
enable=true
    [[gateway.inout]]
        account="xmpp.1"
        channel="xmpproomhere"
    [[gateway.inout]]
        account="telegram.1"
        channel="-1000000000000"
    [[gateway.inout]]
        account="discord.1"
	channel="ID:300000000000000000"

**Comment by xenoguy** [comment]
I was just going to log this one, seems specific to Telegram.  I upgraded from 11 to 12.1 to get TG username support.  but now it's printing the same username for every message across the bridge.

**Comment by 42wim** [comment]
Do you get the same issue if enabling / disabling UseFirstName ?

**Comment by 42wim** [comment]
Ok, think I found it, pushed the fix in master. 
Can you try and reopen if still an issue ?

**Comment by TomTheDragon** [comment]
Woah that was fast.. o.-.o
But yeah its working now, thx for the quick fix :)
