### ISSUE TITLE
Segmentation fault during QR code scanning

### ISSUE THREAD

**Issue by jodesp** [42wim/matterbridge#1810]
**Describe the bug**
During the QR code scanning procedure for WhatsApp integration (with Mattermost bridging), I get a segmentation fault error as shown below:

```bash
/usr/bin/matterbridge -conf /etc/matterbridge/matterbridge.toml
[0000]  INFO main:         Running version 1.25.0
[0000]  INFO config:       Opening log file /var/log/matterbridge.log
[2022-04-18T15:58:29+02:00]  INFO matterclient: Found version 6.3.3.6.3.3.b83e80791299407885ef3aa97329813b.false
[...]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x19974a2]

goroutine 1 [running]:
github.com/42wim/matterbridge/bridge/whatsappmulti.(*Bwhatsapp).Connect(0xc000a53100)
        /root/go/pkg/mod/github.com/42wim/matterbridge@v1.25.0/bridge/whatsappmulti/whatsapp.go:118 +0x622
github.com/42wim/matterbridge/gateway.(*Router).Start(0xc00010c5f0)
        /root/go/pkg/mod/github.com/42wim/matterbridge@v1.25.0/gateway/router.go:76 +0x35f
main.main()
        /root/go/pkg/mod/github.com/42wim/matterbridge@v1.25.0/matterbridge.go:65 +0x39e
```

Also some times I don't manage to scan correctly the QR code correctly by the WhatsApp mobile app.

**To Reproduce**
Bridge Mattermost and WhatsApp, then wait for QR code scanning procedure.

**Expected behavior**
The QR code scanning should have proceeded successfully.

**Environment:**
 - OS: Debian Linux (buster)
 - version: 1.25.0

**Comment by 42wim** [comment]
You're using the whatsapp beta version?

**Comment by jodesp** [comment]
Yes, I am using the WhatsApp beta version build, on matterbridge `v.1.25.0`.

@42wim

**Comment by 42wim** [comment]
please reopen if still an issue on master
