### ISSUE TITLE
Mumble Server 1.4.x: warning message about ChannelListener Feature

### ISSUE THREAD

**Issue by cfdisk** [42wim/matterbridge#1817]
**Is your feature request related to a problem? Please describe.**
The following message appears when connecting to mumble server (since 1.4.x): 
> "[WARNING]: This server has the ChannelListener feature enabled but your client version does not support it. This means that users might be listening to what you are saying in your channel without you noticing! You can solve this issue by upgrading to Mumble 1.4.0 or newer."

**Describe the solution you'd like**
matterbridge should report itself as a version 1.4 Client to get rid of the warning.

**Comment by 42wim** [comment]
cc: @s3lph is this something you can take a look at?

**Comment by s3lph** [comment]
This needs to be resolved in gumble, see layeh/gumble#49. For the time being I'd say it's safe to ignore this warning.

**Comment by xnaas** [comment]
FYI for anyone reading, if you want a temporary workaround, you can add something like:

```TOML
IgnoreMessages="^\\*\\*\\[WARNING]\\*\\*:"
```

to your mumble config section in your TOML. If you wanted to perfectly match the message, you could, of course, extend the regex even more, but this seemed adequate as a short-term<sup>1</sup> solution to suppress the message.

---

<sup>1</sup>could end up long-term, but you know :P

**Comment by 42wim** [comment]
@xnaas it's closed because we can't fix it, depending on upstream
