### ISSUE TITLE
Is this an IRC or a Matterbridge issue?

### ISSUE THREAD

**Issue by alecisec** [42wim/matterbridge#182]
I've configured and been using Matterbridge for some time to relay IRC messages into a mattermost channel (one-way bridge)

about 3 weeks ago at some point it just stopped working. I've rebuilt the docker container with just a clean git-clone and docker start and the original config script (pasted below) and still have the same issue. I've also tried a clean binary (12.1) with the same config and have the same issue.

Where it gets weird however is if I move the bot into another channel, it works perfectly. In fact, any other channel, even making up a new channel, works fine. It's only the IRC channel that I actually want to relay that won't do anything. No errors show in the logs (even in debug mode) and the connectivity is still there (I can hop onto the IRC server myself and see the bot idling in the channel).

Please answer the following questions. 

### Which version of matterbridge are you using?
12.1

### Please describe the expected behavior.
Messages should be relayed from IRC

### Please describe the actual behavior. 

Messages are relayed properly from all but one IRC channel

#### Use logs from running ```matterbridge -debug``` if possible.

Can see join/leave events from the IRC channel in the debug logs, however there are no events for messages sent to the channel.

### Any steps to reproduce the behavior?

Join the affected channel

#### (be sure to exclude or anonymize private data (tokens/passwords))

[irc]

[irc.redacted]
Server="redacted.com:443"

Password="redacted"

UseTLS=true

UseSASL=false

SkipTLSVerify=true

Nick="Relay_bot"

NickServNick="nickserv"
NickServPassword="redacted"

MessageDelay=1300

MessageQueue=30

IgnoreNicks="ircspammer1 ircspammer2"

RemoteNickFormat=" <{NICK}> "

ShowJoinPart=false

[mattermost]

[mattermost.work]

useAPI=true

Server="redacted2.com"

Team="teamname-redacted"

Login="redacted@redacted.com"
Password="redacted"

NoTLS=false

SkipTLSVerify=true

NickFormatter="plain"

NicksPerRow=4

PrefixMessagesWithNick=true

IgnoreNicks="ircspammer1 ircspammer2"

RemoteNickFormat="{NICK}"

ShowJoinPart=false

[api]

[api.local]

BindAddress="127.0.0.1:4242"

Buffer=1000

RemoteNickFormat="{NICK}"

[general]

RemoteNickFormat=" <{NICK}> "

[[gateway]]

name="gateway1"
#Enable enables this gateway

enable=true

    [[gateway.in]]

    channel="#redacted_chat"

        [gateway.in.options]

        key="yourkey"

    [[gateway.out]]

     account="mattermost.work"
     channel="redacted-returnbuffer"

        [gateway.out.options]
		
        key="yourkey"

    [[gateway.inout]]
    account="mattermost.work"
    channel="redacted-irc-logs"

        [gateway.inout.options]

        key="yourkey"

[[samechannelgateway]]
   enable = false
   accounts = [ "mattermost.work","slack.hobby" ]
   channels = [ "testing","testing2","testing3"]

**Comment by alecisec** [comment]
Just to confirm - If I'm to change the one line  : 

channel="#redacted_chat"

to say 

channel="#redacted_chat_2" or channel="#redacted_chat_test"
 
then the debug logs will successfully show an event for a message posted in the channel as follows:


time="2017-05-31T02:54:15Z" level=debug msg="map[string]interface {}{"team_id":"qs56d5k793r4d8mpjgnt8apgne", "channel_display_name":"Redacted IRC", "channel_name":"redacted-irc", "channel_type":"P", "post":"{\"id\":\"8k7jig6rgig18bo6f7k9jj8yah\",\"create_at\":1496199255530,\"update_at\":1496199255530,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"wopxbir1o7fzxfr6sk3ct3gq1h\",\"channel_id\":\"qnw1co8z6bbx3fcgqb878m6bzc\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\" \\u003c \\u003cREDACTED_USERID\\u003e \\u003e TEST2\",\"type\":\"\",\"props\":{},\"hashtags\":\"\",\"pending_post_id\":\"\"}", "sender_name":"matterbridge.bot"}" module=mattermost

however with the 'correct' channel name set, no event is created in the debug logs at all.

**Comment by alecisec** [comment]
Have modified the config to exclude the gateway.inout sections (leaving only mattermost as gateway.out and irc as gateway.in)

can see test messages in the debug logs for both a working and non-working channel as follows

The non-working channel's debug logs from matterbridge :
`
time="2017-05-31T07:10:50Z" level=debug msg="":redacted!redacted@1fj.nad.nvpjbn.IP PRIVMSG #redacted_Chat :test on live channel"" module=irc
time="2017-05-31T07:11:00Z" level=debug msg="WS PING" module=matterclient
time="2017-05-31T07:11:00Z" level=debug msg="sendWsRequest &model.WebSocketRequest{Seq:15, Action:"ping", Data:map[string]interface {}(nil), Session:model.Session{Id:"", Token:"", CreateAt:0, ExpiresAt:0, LastActivityAt:0, UserId:"", DeviceId:"", Roles:"", IsOAuth:false, Props:model.StringMap(nil), TeamMembers:[]*model.TeamMember(nil)}, T:(i18n.TranslateFunc)(nil), Locale:""}" module=matterclient
time="2017-05-31T07:11:00Z" level=debug msg="WsReceiver: model.WebSocketResponse{Status:"OK", SeqReply:15, Data:map[string]interface {}{"node_id":"", "server_time":1.496214660677e+12, "text":"pong", "version":"3.9.0"}, Error:(*model.AppError)(nil), PreComputeJson:[]uint8(nil)}" module=matterclient
time="2017-05-31T07:11:00Z" level=debug msg="WS PONG received" module=matterclient
`


a working test ITC channel's logs:
`
time="2017-05-31T07:21:42Z" level=debug msg="Sending message from #redacted_chat_test on irc.redacted to gateway" module=irc
time="2017-05-31T07:21:42Z" level=debug msg="":redacted!redacted@1fj.nad.nvpjbn.IP PRIVMSG #redacted_chat_test :test on test channel"" module=irc
time="2017-05-31T07:21:42Z" level=debug msg="Sending config.Message{Text:"night", Channel:"#redacted_chat_test", Username:"redacted", Avatar:"", Account:"irc.redacted", Event:"", Protocol:"", Timestamp:time.Time{sec:63631812102, nsec:808806841, loc:(*time.Location)(0xdcea60)}} from irc.redacted (#redacted_chat_test) to mattermost.work (redacted-irc)"
time="2017-05-31T07:21:42Z" level=debug msg="Receiving config.Message{Text:"test on test channel", Channel:"redacted-irc", Username:" <redacted> ", Avatar:"http://youricon.png", Account:"irc.redacted", Event:"", Protocol:"irc", Timestamp:time.Time{sec:63631812102, nsec:808806841, loc:(*time.Location)(0xdcea60)}}" module=mattermost
time="2017-05-31T07:21:42Z" level=debug msg="WsReceiver: model.WebSocketEvent{Event:"posted", Data:map[string]interface {}{"post":"{\"id\":\"8j49qrtpki86dj73btntumd1uc\",\"create_at\":1496215302874,\"update_at\":1496215302874,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"wopxbir1o7fzxfr6sk3ct3gq1h\",\"channel_id\":\"qnw1co8z6bbx3fcgqb878m6bzc\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\" \\u003cAlec_SAGOV\\u003e night\",\"type\":\"\",\"props\":{},\"hashtags\":\"\",\"pending_post_id\":\"\"}", "sender_name":"redacted.bot", "team_id":"qs56d5k793r4d8mpsgnt8aphgxe", "channel_display_name":"redacted IRC", "channel_name":"redacted-irc", "channel_type":"P"}, Broadcast:(*model.WebsocketBroadcast)(0xc4203da9c0), PreComputeJson:[]uint8(nil)}" module=matterclient
time="2017-05-31T07:21:42Z" level=debug msg="map[string]interface {}{"channel_type":"P", "post":"{\"id\":\"8j49qrtpki86dj73btntumd1uc\",\"create_at\":1496215302874,\"update_at\":1496215302874,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"wopxbir1o7fzxfr6sk3ct3gq1h\",\"channel_id\":\"qnw1co8z6bbx3fcgqb878m6bzc\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\" \\u003cAlec_SAGOV\\u003e night\",\"type\":\"\",\"props\":{},\"hashtags\":\"\",\"pending_post_id\":\"\"}", "sender_name":"redacted.bot", "team_id":"qs56d5k793r4d8mpsgnt8aphgxe", "channel_display_name":"redacted IRC", "channel_name":"redacted-irc"}" module=mattermost
`

**Comment by 42wim** [comment]
Too much redacted, it's not really readable anymore. Could you perhaps join https://gitter.im/42wim/matterbridge or ```#matterbridgechat``` on irc.freenode.net so you could maybe share the config file a bit less redacted ?

**Comment by alecisec** [comment]
Resolved the issue with a *lot* of troubleshooting.  What it is, the [[gateway.in]] "channel="#Name" declaration is case sensitive.
Having the incorrect case will result in the IRC module connecting to the IRC channel, hearing messages posted in the channel, printing them to the debug logs - i.e "time="2017-06-01T01:46:13Z" level=debug msg="":Username@1fj.nad.nvpjbn.IP PRIVMSG #Channel_Name :This is a message posted in the channel"" module=irc
HOWEVER - the event "time="2017-06-01T01:49:23Z" level=debug msg="Sending config.Message{Text:"This is a message posted in the channel"
Will not occur if the case doesn't match the name of the channel if the case in the config .toml differs from the case used on the IRC server.

**Comment by 42wim** [comment]
Ok, thanks for letting me know. 
For now I'll add a note about case-sensitive channel names in the configuration sample.
