### ISSUE TITLE
Connect to slack without "administrative permissions over the Slack Workspace"

### ISSUE THREAD

**Issue by mstyp** [42wim/matterbridge#1834]
**Is your feature request related to a problem? Please describe.**
Right now to use with slack requires getting permission from admin of a workspace. I cant do this. So I cant use matterbridge. 

**Describe the solution you'd like**
A way of bridging slack without getting permission from admin of workspace. 

https://github.com/42wim/matterbridge/wiki/Slack-bot-setup

> log into an account that has administrative permissions over the Slack Workspace (server) that you want to sync with Matterbridge.

Admin wont allow bridging but I need it anyways.

**Comment by 42wim** [comment]
can't fix
