### ISSUE TITLE
WhatsApp phone numbers format

### ISSUE THREAD

**Issue by tzagim** [42wim/matterbridge#1843]
**Describe the bug**
In order to display the phone number of the author of the message on WhatsApp it seems that {{USERID}} should be used, but the result is `XXXXXX@s.whatsapp.net`, is it possible to display the phone number without `@s.whatsapp.net`?

Maybe something can be done with `{TENGO)`?

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: 1.25.1
 - If self compiled: `go install -tags nomsteams,nogitter,nokeybase,norocketchat,noslack,novk,nozulip,whatsappmulti github.com/42wim/matterbridge@master`

<details><summary>Additional context</summary>

```ruby
[whatsapp.test]
	Number="+1415454545454"
	RemoteNickFormat=""
	SessionFile="session-test.gob"
	QrOnWhiteTerminal=false

[telegram.test]
	Token="64597464:JHJKSDHFKJASDNFCJSDPOKZPLWSDPFCSPCFL"
	RemoteNickFormat="{NICK}\n(+{USERID})\n"
	MessageFormat=""
	DisableWebPagePreview=false

[[gateway]]
	name="test"
	enable=true

	[[gateway.in]]
	account="whatsapp.test"
	channel="5427823473245632452@g.us"

	[[gateway.out]]
	account="telegram.test"
	channel="-568973628952378"
```
</details>

**Comment by tzagim** [comment]
A solution I made for anyone looking:

ADD
```ruby
[tengo]
	InMessage="userid.tengo"
```

userid.tengo:
```ruby
// Remove "@s.whatsapp.net" from whatsapp users & change {NICK} to "NUMBER USERNAME"
text := import("text")
    msgUsername=text.re_replace("@s.whatsapp.net","+" + msgUserID," " + msgUsername)
```

**Comment by david-botelho-mariano** [comment]
I used your code and here the phone number was appearing in duplicate, I solved it with my code:

```
text := import("text")

parts := text.split(msgUserID, "@")
msgUsername = "+" + parts[0]
```
