### ISSUE TITLE
[FR] Forwarding messages provided that certain words

### ISSUE THREAD

**Issue by tzagim** [42wim/matterbridge#1847]
I would be very happy for the possibility that the bridge will only transfer messages that contain certain words, an opposite option of [ignoremessages](https://github.com/42wim/matterbridge/wiki/Settings#ignoremessages)

`ContainMessages="^~~ goodword"`

I didn't find any alternative to the problem.

Many thanks in advance

**Comment by mahdi1234** [comment]
Would be very much appreciated. Use-case is having pretty verbose room with debug logs and want to forward only certain lines to have quick overview what's going on.

**Comment by bkil** [comment]
Well, you could always simulate that by inverting the regexp, but that is not for the faint of heart.

**Comment by 42wim** [comment]
You can do this with tengo scripting.
See more information here: https://github.com/42wim/matterbridge/wiki/Tengo
