### ISSUE TITLE
API: json is not valid

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#185]
Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
version: 0.13.1-dev 

### Please describe the expected behavior.
i expected something like a json array of messages on the endpoint `/api/messages`
instead there is a list of messages in json NOT in any sort of array [,,,] and not seperated by commas

i know it is work in progress, i am attempting to make a bot that can react to all platforms at the same time and does not need to specially parse the remote nick format or such on irc.. or other platforms
in the process of understanding and testing it it would be useful to have a method of getting messages that does not consume them..
also will there be any sort of authentication to the local api ? apart from assuming there is a firewall and  a overcomplicated nginx proxy configuration adding basic auth..

**Comment by NikkyAI** [comment]
another thing that seems impossble to do so far is use multiple gateways / bridges with the api .. it seems to be hardcoded to api and there seems to be no way to specify which channel or bridge a message is meant for ...
i assume it will be eventually in a endpoint structure like `$channel/message` where channel is at the moment hardcoded to api..

**Comment by NikkyAI** [comment]
i guess i will then split the rest of the requests in seperate issues

**Comment by 42wim** [comment]
Yes, please do :-)
It's valid json now, and the gateway is getting logged.

**Comment by 42wim** [comment]
Keys should be lowercase actually, let me fix that too

**Comment by 42wim** [comment]
Are different endpoints really needed ? 
is the /api/messages endpoint not enough and let your own bot/software filter what it needs ?

**Comment by 42wim** [comment]
I'm going to close this issue, we can discuss the rest in other issue you're going to open :)

**Comment by NikkyAI** [comment]
yes one endpoint would be enough.. that was me being slightly tired..

**Comment by 42wim** [comment]
Just added token authentication in master (see matterbridge.toml.sample for more info)
