### ISSUE TITLE
unsupported mattermost version: 7.0.0

### ISSUE THREAD

**Issue by valderaplets** [42wim/matterbridge#1850]
**Describe the bug**
When Mattermost version 7 is installed, Matterbridge is no longer working. It produces an error

```
level=fatal msg="Starting gateway failed: Bridge xxxxxx failed to start: unsupported mattermost version: 7.0.0.7.0.0.edd040ffb1f8cc90e91673758a2f2040.false" prefix=main
```

**To Reproduce**
Install mattermost version 7.0.0

**Expected behavior**
should working

**Screenshots/debug logs**
...

**Environment (please complete the following information):**
 - OS: Debian 11
 - Matterbridge version:  version: 1.25.1 051e6e76

**Comment by sebastianmuell** [comment]
You can try with SkipVersionCheck=true in your mattermost server section

**Comment by valderaplets** [comment]
it's works =)

**Comment by 42wim** [comment]
Yes, but some stuff will break the skipversioncheck will make you use mattermost v5 api again.
I'll be releasing an update soon
