### ISSUE TITLE
Failed to compile Matterbridge without the gcc/c-compiler

### ISSUE THREAD

**Issue by UcioVV** [42wim/matterbridge#1878]
**Describe the bug**
When executing go install a specific error appears related to the WhatsMeow files

**To Reproduce**
1. Use the command: _CGO_ENABLED=0 go install -tags whatsappmulti github.com/42wim/matterbridge@master_

**Screenshots/debug logs**

go: downloading github.com/remyoudompheng/bigfft v0.0.0-20200410134404-eec4a21b6bb0
# github.com/42wim/matterbridge/bridge/whatsappmulti
../go/pkg/mod/github.com/42wim/matterbridge@v1.25.3-0.20220813165121-0482cd191dc5/bridge/whatsappmulti/helpers.go:80:48: not enough arguments in call to b.wc.GetProfilePictureInfo
        have (types.JID, bool)
        want (types.JID, bool, string)
../go/pkg/mod/github.com/42wim/matterbridge@v1.25.3-0.20220813165121-0482cd191dc5/bridge/whatsappmulti/whatsapp.go:237:42: not enough arguments in call to b.wc.SendMessage
        have (types.JID, string, *"go.mau.fi/whatsmeow/binary/proto".Message)
        want (context.Context, types.JID, string, *"go.mau.fi/whatsmeow/binary/proto".Message)
../go/pkg/mod/github.com/42wim/matterbridge@v1.25.3-0.20220813165121-0482cd191dc5/bridge/whatsappmulti/whatsapp.go:271:42: not enough arguments in call to b.wc.SendMessage
        have (types.JID, string, *"go.mau.fi/whatsmeow/binary/proto".Message)
        want (context.Context, types.JID, string, *"go.mau.fi/whatsmeow/binary/proto".Message)
../go/pkg/mod/github.com/42wim/matterbridge@v1.25.3-0.20220813165121-0482cd191dc5/bridge/whatsappmulti/whatsapp.go:330:43: not enough arguments in call to b.wc.SendMessage
        have (types.JID, string, *"go.mau.fi/whatsmeow/binary/proto".Message)
        want (context.Context, types.JID, string, *"go.mau.fi/whatsmeow/binary/proto".Message)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by DaniJohni** [comment]
I have the same problem, did you find a fix for it?

**Comment by UcioVV** [comment]
> I have the same problem, did you find a fix for it?

Here's the command, it's **as simple as putting@latest instead of @master at the end**
`go install -tags whatsappmulti github.com/42wim/matterbridge@latest`

I'm sorry I didn't post the solution, it should work 👍

**Comment by DaniJohni** [comment]
Thanks, ut works like a charm 👍
