### ISSUE TITLE
Error when install whatsapp multi

### ISSUE THREAD

**Issue by gamersindo1223** [42wim/matterbridge#1881]
**Describe the bug**
A clear and concise description of what
Ic you try to install whatsappmulti you will get this error
# github.com/42wim/matterbridge/bridge/whatsappmulti
../go/pkg/mod/github.com/42wim/matterbridge@v1.25.3-0.20220813165121-0482cd191dc5/bridge/whatsappmulti/helpers.go:80:48: not enough arguments in call to b.wc.GetProfilePictureInfo
        have (types.JID, bool)
        want (types.JID, bool, string)
../go/pkg/mod/github.com/42wim/matterbridge@v1.25.3-0.20220813165121-0482cd191dc5/bridge/whatsappmulti/whatsapp.go:237:42: not enough arguments in call to b.wc.SendMessage
        have (types.JID, string, *"go.mau.fi/whatsmeow/binary/proto".Message)
        want (context.Context, types.JID, string, *"go.mau.fi/whatsmeow/binary/proto".Message)
../go/pkg/mod/github.com/42wim/matterbridge@v1.25.3-0.20220813165121-0482cd191dc5/bridge/whatsappmulti/whatsapp.go:271:42: not enough arguments in call to b.wc.SendMessage
        have (types.JID, string, *"go.mau.fi/whatsmeow/binary/proto".Message)
        want (context.Context, types.JID, string, *"go.mau.fi/whatsmeow/binary/proto".Message)
../go/pkg/mod/github.com/42wim/matterbridge@v1.25.3-0.20220813165121-0482cd191dc5/bridge/whatsappmulti/whatsapp.go:330:43: not enough arguments in call to b.wc.SendMessage
        have (types.JID, string, *"go.mau.fi/whatsmeow/binary/proto".Message)
        want (context.Context, types.JID, string, *"go.mau.fi/whatsmeow/binary/proto".Message)

**To Reproduce**
Do this command on ubuntu
CGO_ENABLED=0 go install -tags nomsteams,whatsappmulti github.com/42wim/matterbridge@master

**Expected behavior**
It should install the file without problems

**Screenshots/debug logs**
Use logs from running `matterbridge -debug` if possible.

**Environment (please complete the following information):**
 - OS: ubuntu aws ec2
 - Matterbridge version: output of  `matterbridge -version`
 - If self compiled: output of `git rev-parse HEAD`

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))

**Comment by gamersindo1223** [comment]
Help please

**Comment by gamersindo1223** [comment]
@42wim

**Comment by tareko** [comment]
I'm similarly suffering form this issue. I tried to scale back to an earlier version of 2.5.2, but that didn't work.

**Comment by tareko** [comment]
A bit more information here. I am not fluent in Go Lang, so not sure how best to fix.

4 affected lines are:

https://github.com/42wim/matterbridge/blob/master/bridge/whatsappmulti/helpers.go#L80

https://github.com/42wim/matterbridge/blob/master/bridge/whatsappmulti/whatsapp.go#L237
https://github.com/42wim/matterbridge/blob/master/bridge/whatsappmulti/whatsapp.go#L271
https://github.com/42wim/matterbridge/blob/master/bridge/whatsappmulti/whatsapp.go#L330

There are two solutions here:

1. To pin to an older version of the underlying library (`/vendor/go.mau.fi/whatsmeow/user.go`). I'm not entirely sure how to do this.
2. To upgrade the calls.

For the first line, the solution is to change this line:

```
	info, err := b.wc.GetProfilePictureInfo(pjid, true)
```
to this:
```
	info, err := b.wc.GetProfilePictureInfo(pjid, true, "")
```

The other three lines appear more complex, as it seems the entire way the library works is changing.

**Comment by gamersindo1223** [comment]
I roll back to the older versions and it worked

**Comment by tareko** [comment]
Problem for me is that I'm using MM 7+, so I can't do that.

**Comment by 42wim** [comment]
Current master should work again.

**Comment by tareko** [comment]
Unfortunately this issue does not appear fixed still. While it now compiles and connects again, no messages travel in either direction. This is despite it successfully linking and joining:

```
[0009]  INFO whatsapp:     whatsapp.glia: joining XX@g.us (ID: XX@g.uswhatsapp.glia)
13:34:22.177 [Client INFO] Successfully authenticated
[0010]  INFO whatsapp:     whatsapp.glia: joining XX@g.us (ID: XX@g.uswhatsapp.glia)
[0010]  INFO whatsapp:     whatsapp.glia: joining XX@g.us (ID: XX@g.uswhatsapp.glia)
[0011]  INFO whatsapp:     whatsapp.glia: joining XX@g.us (ID: XX@g.uswhatsapp.glia)
[0011]  INFO whatsapp:     whatsapp.glia: joining XX@g.us (ID: XX@g.uswhatsapp.glia)
```

I assume nothing changed in the configuration file. Is there any way to debug what might be happening?

**Comment by tareko** [comment]
Just noting that this is still an issue and whatsapp multi still does not work as above. Is there anything I can do to help further troubleshoot?

**Comment by rs2152** [comment]
Hi, can you please anyone give me some idea why my project is not working on EC2?

[](https://github.com/tulir/whatsmeow/discussions/603)
[](https://stackoverflow.com/questions/78589867/how-to-deploy-go-application-whatsmeow-on-ec2)
