### ISSUE TITLE
unable to connect to mattermost 7.1 via matterbridge v1.25.2

### ISSUE THREAD

**Issue by SudhirMaddy** [42wim/matterbridge#1885]
**Describe the bug**
Unable to start matterbridge service when connecting to mattermost on version 7.1 failing with Team 'myteam' not found in []

**To Reproduce**
update toml file with the mattermost config and start matterbridge. 

**Expected behavior**
starting of matterbridge service and connecting to mattermost. 

**Screenshots/debug logs**
[0000] FATAL main:         [main:pkg/mod/github.com/42wim/matterbridge@v1.25.2/matterbridge.go:66] Starting gateway failed: Bridge mattermost.work failed to start: Team 'myteam' not found in []

**Environment (please complete the following information):**
 - OS Linux
 - Matterbridge version: [output of  `matterbridge -version`](version: 1.25.2)
 - If self compiled: na

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))

**Comment by 42wim** [comment]
Seems like a wrong configuration .. paste your config
