### ISSUE TITLE
Problem building whatsappmulti docker

### ISSUE THREAD

**Issue by Syntoxr** [42wim/matterbridge#1888]
**Describe the bug**
When trying to build a docker container via `Dockerfile_whatsappmulti` with `docker build -f Dockerfile_whatsappmulti -t matterbridge-wa .`, I'm getting a `not enough arguments error`.
Building with standard Dockerfile works.
@tpxtron As you created the Dockerfile, maybe you could help? Am I using the right build command?

**To Reproduce**
1. clone repo using `git clone https://github.com/42wim/matterbridge.git`
2. navigate into repo
3. build using `docker build -f Dockerfile_whatsappmulti -t matterbridge-wa .`

**Expected behavior**
Docker build succeeds

**Screenshots/debug logs**
![image](https://user-images.githubusercontent.com/63484271/188504974-14ea1188-e0bc-4bd8-a052-0dd73024b7a0.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.0.4 LTS
 - If self compiled: output of `git rev-parse HEAD`: 7abf1a5884bfba9ac19df26495924d86613874f3

**Comment by 42wim** [comment]
current master should work again, do a git pull or clone it again.
