### ISSUE TITLE
Feature Request: Option to hide Matterbridge's own bots on "ShowJoinPart"

### ISSUE THREAD

**Issue by TomTheDragon** [42wim/matterbridge#190]
### Which version of matterbridge are you using?
0.12.1

### Desciption of the request
It would be nice to have a option to hide the Join/Leave message for other connected bots, because i always get a "join" message when ever i restart Matterbridge.

**Comment by 42wim** [comment]
This is actually a bug, the bot shouldn't announce itself. Fixed in master.
