### ISSUE TITLE
Binary builds with executable stack

### ISSUE THREAD

**Issue by tacerus** [42wim/matterbridge#1906]
**Describe the bug**
After building the source using either the instructed `go install github.com/42wim/matterbridge@master` or using `go build`, a binary wanting an executable stack is produced.

```
$ scanelf -e matterbridge
 TYPE   STK/REL/PTL FILE 
ET_EXEC RWX R-- RW- matterbridge
```

Reference: https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart

During build, the following output is observed:

`/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: warning: /tmp/go-link-4017556066/000024.o: missing .note.GNU-stack section implies executable stack`

**To Reproduce**
1. Clone the repository
2. `go build`
3. `scanelf -e matterbridge`

**Expected behavior**
The binary should not demand an executable stack. Building the program under RPM should not cause a warning:
_“The binary declares the stack as executable. Executable stack is usually an error as it is only needed if the code contains GCC trampolines or similar constructs which uses code on the stack. One common source for needlessly executable stack cases are object files built from assembler files which do not define a proper .note.GNU-stack section.”_ 

**Environment (please complete the following information):**
 - OS: openSUSE Tumbleweed 
 - Matterbridge version: 1.25.2
 - Go version: 1.19.2
 - GCC/g++ version: 12.2.1

**Comment by 42wim** [comment]
See https://github.com/42wim/matterbridge#building
it shows you how to build without gcc.

Also the release binaries are built this way

**Comment by tacerus** [comment]
I understand the option to build without GCC. However, a GCC built binary should not show this phenomena without reason.

**Comment by 42wim** [comment]
Any suggestions?

**Comment by tacerus** [comment]
Unfortunately I'm not that proficient with go and gcc myself.

With `-xv` it returns

```
# github.com/42wim/matterbridge
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: warning: /tmp/go-link-1889852138/000024.o: missing .note.GNU-stack section implies executable stack
```
But nothing more helpful, even with `GODEBUG` and `gctrace` or via `strace`.

Possibly there's some way to preserve this transient go-link-* directory in order to inspect the object file?

**Comment by tacerus** [comment]
Seems it is possible to work around the issue using:

```
$ go build -v -x -buildmode=pie -ldflags='-s -w -extldflags -znoexecstack'
$ scanelf -e matterbridge
 TYPE   STK/REL/PTL FILE 
ET_DYN RW- R-- RW- matterbridge
```

But maybe someone else has an idea how to find where in the source code this could be properly resolved.

**Comment by 42wim** [comment]
should be fixed now
