### ISSUE TITLE
Plugin API documentation?

### ISSUE THREAD

**Issue by JsBergbau** [42wim/matterbridge#1910]
Hallo,

I play with the idea developing a Signal Plugin for matterbridge. A simple google search didn't find a documentation for the plugin API. Is there one or must it be read from source code? If the latter that would be a pitty because that would be too much effort for me.

I know there is this pull request https://github.com/42wim/matterbridge/pull/1433 but it was opened for more than 1.5 years ago and still not merged.
I'm also very astonished that so far signal support is missing. There are so many great services that can be briged, but Signal is still missing :(

**Comment by 42wim** [comment]
API: https://github.com/42wim/matterbridge/wiki/API
new bridge: https://github.com/42wim/matterbridge/wiki/Gateway%3A-developing-new-one
