### ISSUE TITLE
How do I set up matterbridge and get it running 

### ISSUE THREAD

**Issue by LittleTimmy52** [42wim/matterbridge#1913]
### Environment

Version: not installed idk how

Operating system: win 10

### Please add your configuration file 

I am new, i figured out just recently how to use IRC kind of, but that's not the point, how does one go about using this, all i ever find is install it, but if i just install it idk how/were to host it, can someone please explain how i can use this to bridge my channel IRC from IRC.ircnet.com and my discord server. Any help is appreciated, thanks.

**Comment by minecraftchest1** [comment]
I wrote a blog post a while back on this topic. 216920

**Comment by 42wim** [comment]
Also see https://github.com/matterbridge/wiki/wiki/How-to-create-your-config
