### ISSUE TITLE
[Telegram] -  Topics (ala channels on discord) 

### ISSUE THREAD

**Issue by kingbrucelee** [42wim/matterbridge#1916]
**Is your feature request related to a problem? Please describe.**
Recently Telegram added support for group topics. This gives opportunity to for example link each of multiple let's say discord channels to individual topics.  Also once it's more widespread feature (currently only groups with 200+ members can do that and few of them catch onto that) it may produce uintended behavior (like missing certain messages or just straight up stop working) 

**Describe the solution you'd like**
I dunno if that's the best approach but the most simple is to Treat each topic sorta as different group.  This would pretty much solve every problem that can arise from this feature. 

**Describe alternatives you've considered**
We can also just don't use topics. 

**Additional context**
![Screenshot_20221106-185058](https://user-images.githubusercontent.com/90533878/200186731-cc5afba9-68b2-4db4-9140-1bbe482c8188.png)
![Screenshot_20221106-185112](https://user-images.githubusercontent.com/90533878/200186751-35d05cbf-c9c0-4eaf-8ab0-54a46146d1e9.png)

**Comment by kingbrucelee** [comment]
Any updates?

**Comment by cosmicboots** [comment]
It doesn't look like the library matterbridge is using supports the telegram api changes that allow the topic functionality yet. 

There is an active merge request to get this fixed though: https://github.com/go-telegram-bot-api/telegram-bot-api/pull/621

**Comment by 42wim** [comment]
Fixed in #1942 by @cosmicboots
