### ISSUE TITLE
Improving Discord Bot Setup to actually work

### ISSUE THREAD

**Issue by Xelfi** [42wim/matterbridge#1917]
### Discussed in https://github.com/42wim/matterbridge/discussions/1907

<div type='discussions-op-text'>

<sup>Originally posted by **Xelfi** October 29, 2022</sup>
Hi there,

I'm just letting you know that this wiki page might be updated (cause it's actually outdated due to new discord bot features):
https://github.com/42wim/matterbridge/wiki/Discord-bot-setup

In fact the section "**Privileged Gateway Intents**" has a missing point:
We also have to **toggle** "Message Content Intent" (which can be pretty obvious) in addition to the "Server Members Intent".
See: http://prntscr.com/NftbbSLjX9it

If the **Message Content Intent** is not enabled, the bridge can no longer get any messages to transfer.</div>

**Comment by qaisjp** [comment]
Thanks for reporting this.

It looks like the guide needs updating to fix all the photos, but for now I've fixed up the **Privileged Gateway Intents** section with your recommendations.

Here's the diff: https://github.com/42wim/matterbridge/wiki/Discord-bot-setup/_compare/a42bca486275fe8ae5862781ca53c347aac9ef7c...88793442d1cd91f735da49d5b8c6d4f1e0c60f15

Feel free to update the wiki yourself if you have anything useful to add! Thanks again.
