### ISSUE TITLE
Feature Request: Links to media content.

### ISSUE THREAD

**Issue by icedtang** [42wim/matterbridge#192]
It would be really slick if the ircd could create links to pictures that people post in the mattermost webui or from the mobile interface. Right now IRC users don't even see that something was pasted.

**Comment by 42wim** [comment]
This has been working since september last year. (https://github.com/42wim/matterbridge/commit/272eef544f7c4c6951b3dc6539120168dcd0996d)

You have to use the API, doesn't work with webhooks
