### ISSUE TITLE
Send captions of "document" attachments to Whatsapp rooms

### ISSUE THREAD

**Issue by ilmaisin** [42wim/matterbridge#1925]
**Describe the bug**
Captions of "document" attachments are not send to Whatsapp rooms. Only the file attachment is sent.

**To Reproduce**
Send a file containing both a video and text to a Telegram room that is bridged with a WA room

**Expected behavior**
Both text and video should appear in the Whatsapp room

**Screenshots/debug logs**
Use logs from running `matterbridge -debug` if possible.

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version:  1.25.3-dev

 - If self compiled: output of `git rev-parse HEAD` While I have built my matterbridge myself per [these](https://github.com/42wim/matterbridge#building-with-whatsapp-beta-multidevice-support) instructions, I cannot find any relevant git repository from my system.

**Additional context**
Image captions are sent just fine.

[This file](../blob/master/bridge/whatsappmulti/whatsapp.go) apparently has specific code to handle captions for "image" messages, but not for "document" messages.

**Comment by ilmaisin** [comment]
https://github.com/42wim/matterbridge/pull/1652 A similar issue was fixed last year but for Discord instead of Whatsapp.

**Comment by 42wim** [comment]
Fixed by your own PR :)
