### ISSUE TITLE
Discord Setup Updates

### ISSUE THREAD

**Issue by kousu** [42wim/matterbridge#1944]
**Describe the bug**
The instructions to setup discord are bitrotting.

https://github.com/42wim/matterbridge/wiki/Discord-bot-setup currently has missing images. The flow also seems to be slightly changed, now.

**To Reproduce**

1. Look at 
https://github.com/42wim/matterbridge/wiki/Discord-bot-setup

**Expected behavior**
Up to date instructions.

**Screenshots/debug logs**

![Screenshot 2023-01-12 at 15-33-06 Discord bot setup · 42wim_matterbridge Wiki](https://user-images.githubusercontent.com/987487/212175267-0bc333d0-e016-4e27-aadf-156b85ec5e7e.png)

**Comment by kousu** [comment]
I took some updated screenshots

<details><summary>Screenshots</summary>

![Screenshot 2023-01-12 at 15-37-15 Discord Developer Portal — API Docs for Bots and Developers](https://user-images.githubusercontent.com/987487/212194339-3d442700-d65e-4e51-adc5-d72852534db8.png)
![Screenshot 2023-01-12 at 15-37-24 Discord Developer Portal — API Docs for Bots and Developers](https://user-images.githubusercontent.com/987487/212194341-b8b7fca2-7b70-422c-b919-09c58a6a0495.png)
![Screenshot 2023-01-12 at 15-37-45 Discord Developer Portal — API Docs for Bots and Developers](https://user-images.githubusercontent.com/987487/212194343-5ca1e46e-8e59-4f5a-8f26-08e4894f42e0.png)
![Screenshot 2023-01-12 at 15-37-52 Discord Developer Portal — API Docs for Bots and Developers](https://user-images.githubusercontent.com/987487/212194345-56c1b9cb-63cb-4216-b705-2ba1baa6d4a6.png)
![Screenshot 2023-01-12 at 15-38-00 Discord Developer Portal — API Docs for Bots and Developers](https://user-images.githubusercontent.com/987487/212194346-86dcb128-4722-4627-acfc-2d18bb8a8ed4.png)
![Screenshot 2023-01-12 at 15-38-31 Discord Developer Portal — API Docs for Bots and Developers](https://user-images.githubusercontent.com/987487/212194347-0c424124-d5c2-4939-8f25-a492a6f6c79b.png)
![Screenshot 2023-01-12 at 15-38-38 Discord Developer Portal — API Docs for Bots and Developers](https://user-images.githubusercontent.com/987487/212194348-d15c249f-d8e7-45ea-b807-ddedaaeb6442.png)
![Screenshot 2023-01-12 at 15-44-44 Discord Developer Portal — API Docs for Bots and Developers](https://user-images.githubusercontent.com/987487/212194349-c2544381-5009-4c90-8d9d-1ce5dcfae855.png)
![Screenshot 2023-01-12 at 15-45-16 Discord Developer Portal — API Docs for Bots and Developers](https://user-images.githubusercontent.com/987487/212194350-88d037a8-e688-4c43-b2ee-ec41a1990b79.png)

![Screenshot 2023-01-12 at 15-45-40 Discord - A New Way to Chat with Friends   Communities](https://user-images.githubusercontent.com/987487/212195690-97e5c675-b34f-4dba-895e-232eedb2f7f7.png)


![2023-01-12-154616_469x552_scrot](https://user-images.githubusercontent.com/987487/212195594-6c709139-38fa-4ea9-a153-95fa55e64363.png)
![2023-01-12-154625_391x451_scrot](https://user-images.githubusercontent.com/987487/212195596-8e52acd6-5873-4c28-8e86-a897b894148d.png)
![2023-01-12-154634_305x441_scrot](https://user-images.githubusercontent.com/987487/212195597-dc4b9a47-87ff-4a03-90b4-b2db034bf606.png)

</details>


The text is slightly wrong in two places I can see:

1. There's no more "Reveal Token" or "Copy to Clipboard" button, now there's just 'Reset Token' and you have to do it the first time to get a token
2. The welcome message for me wasn't "A wild [bot name] appeared!". It was "[bot name] dropped in to say hi", or something like that. Maybe they have a rotation they cycle through.

**Comment by 42wim** [comment]
@kousu thanks a lot for this 🙏
Are you willing to add this to the wiki? (I've had to disable anonymous access because malware urls we're getting spammed)
That's why I'm going to move the wiki to https://github.com/matterbridge/wiki/wiki 
If you're interested I can give you access. Let me know :)

**Comment by kousu** [comment]
Yes sure :)

**Comment by kousu** [comment]
Ah sorry I forgot about this in my inbox. But it's [done now](https://github.com/matterbridge/wiki/wiki/Discord-bot-setup/5ce5a10d0fd9e1a1a5497c7b5e71c505bcbd8f63):

![Screenshot 2023-02-12 at 02-40-37 Discord bot setup](https://user-images.githubusercontent.com/987487/218299016-c2e1394d-ce82-4781-a539-5a38a1d51544.png)

I also tweaked [the main discord page](https://github.com/matterbridge/wiki/wiki/Section-Discord-(basic)/a03ef7c3ccf2b38404e2bc04a0315d1254669fab), mainly to recommend `AutoWebhooks=true` to match the bot setup page.

**Comment by 42wim** [comment]
@kousu thanks! it's now synced to https://github.com/42wim/matterbridge/wiki also
