### ISSUE TITLE
Discord -> IRC: \quit messages when a user disconnects from IRC are not displayed on the Discord side

### ISSUE THREAD

**Issue by jmaeshawn** [42wim/matterbridge#1948]
### Environment

Version: Matterbridge 1.25.2 20f841c5

Operating system: Windows 10 Version 22H2 (OS Build 19045.2486)

### Please describe the expected behavior.
ShowJoinPart is supposed to show when a user disconnects from an IRC server completely (via the \quit command, or simply by closing the IRC client).

### Please describe the actual behavior. 

Instead, it simply shows when users have joined the channel (\join) or parted from the channel (\part). So when a user joins an IRC channel, then disconnects from IRC and then rejoins, the users on the Discord side only see the following:
[https://i.imgur.com/AzsUuva.png](url)

### Any steps to reproduce the behavior?
1) Use matterbridge to connect to the Rizon IRC network through Discord.
2) Have another IRC user disconnect from the network.
3) See that the disconnect doesn't appear on the Discord side of the bridge.

### Please add your configuration file 

```
[irc]

[irc.Rizon]
Nick="*****"
NickServNick="*****"
Server="irc.rizon.net:6697"
UseTLS=true
SkipTLSVerify=false
RunCommands=["PRIVMSG nickserv :IDENTIFY *****"]
RemoteNickFormat="<{NICK}> "
ShowJoinPart=true

[discord]

[discord.Discord]
Token="*****"
Server="*****"
RemoteNickFormat="{NICK}"
ShowJoinPart=true
ShowTopicChange=false
EditDisable=false
EditSuffix="*"


[[gateway]]
name="IRC.to.Discord"
enable=true

[[gateway.in]]
account="irc.Rizon"
channel="#*****"

[[gateway.out]]
account="discord.Discord"
channel="*****"

[gateway.out.options]
WebhookURL="https://discord.com/api/webhooks/*****/*****"
```

**Comment by 42wim** [comment]
Unfortunately it's not possible to show IRC quits as quits are not linked to channels
