### ISSUE TITLE
api: not require hardcoded channel in gateway config

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#195]
at the moment in the api the channel has to be set to `"channel"="api"`
this causes confusion like in #194

I think it will also cause problem with `[[samechannelgateway]]`

better to pass the channel as it gets written in the config and a originalChannel in addition if that is even required.. just seeing which gateway and platform a message comes ffrom should be enough in most cases

**Comment by 42wim** [comment]
The channel name should have no impact, the api bridge doesn't have a channel. (that's why api-channel is hardcoded)

I've changed to code so that matterbridge no longer cares which channel you put in the config for api. You can even remove it.
