### ISSUE TITLE
Mattermost wiki HTTP configuration is incorrect

### ISSUE THREAD

**Issue by unode** [42wim/matterbridge#1950]
**Describe the bug**
Not a but but a documentation mistake.

On [the mattermost wiki page](https://github.com/42wim/matterbridge/wiki/Section-Mattermost-%28basic%29) where it reads `NoTLS=false` should read `NoTLS=true` under `HTTP`, otherwise matterbridge will try to use `HTTPS` anyway.

**Comment by 42wim** [comment]
thanks!
