### ISSUE TITLE
Slack to mattermost - messages in existing slack threads do not send to mattermost

### ISSUE THREAD

**Issue by VadimDobryninFlant** [42wim/matterbridge#1962]
**Describe the bug**
Messages in existing slack threads do not send to mattermost

**To Reproduce**
Send new message in existing slack thread

**Expected behavior**
Receive message in mattermost

**Screenshots/debug logs**
`time="2023-02-08T10:14:07Z" level=debug msg="message from same user as bot, ignoring" func=skipMessage file="bridge/mattermost/helpers.go:221" prefix=mattermost`

**Environment (please complete the following information):**
 - Kubernetes (docker container from hub.docker.com 42wim/matterbridge:1.26)
 - Matterbridge version: 1.26.0 6dafebc
 

**Additional context**
cat matterbridge.toml
```
[api.api]
    BindAddress="0.0.0.0:4242"
    Buffer=1000
    RemoteNickFormat="{NICK}"
[slack]
    [slack.slack]
    Debug="false"
    Token="xxx"
    PrefixMessagesWithNick=true
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
    PreserveThreading=true
    UseFullName=true
[mattermost]
    [mattermost.mattermost]
    Server="xxx:443"
    Team="xxx"
    Token="xxx"
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
    PrefixMessagesWithNick=true
    PreserveThreading=true
    UseUserName=true
[[gateway]]
name="gateway"
enable=true

    [[gateway.inout]]
    account="mattermost.mattermost"
    channel="xxx"

    [[gateway.inout]]
    account="slack.slack"
    channel="xxx"

    [[gateway.inout]]
    account="api.api"
    channel="api"

```

**Comment by 42wim** [comment]
The error message says it:`msg="message from same user as bot, ignoring"` 
You need a dedicated bot user, don't send messages as the bot

**Comment by VadimDobryninFlant** [comment]
Hello! We have reproduced the problem,  new message in existing slack thread does not send to particular mattermost thread, but sends to channel. It happens every time after matterbridge docker container was restarted. May be we need to configure any persistent volumes? Thank you!
