### ISSUE TITLE
Rocket.Chat failed to join channel

### ISSUE THREAD

**Issue by gitwittidbit** [42wim/matterbridge#1963]
**Describe the bug**
Well, probably this is a bug. But I don't know if it's the code or my config...

So this is my config for Rocket.Chat (copied from the examples):

[rocketchat.myrocketchat]
Server="..."
Login="matterbot"
Password="..."
PrefixMessagesWithNick=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="rocketchat.myrocketchat"
channel="#Test"

I created a channel "#Test" in Rocket.Chat and added the user matterbot (which is a bot).

And this is the error I am getting:

time="2023-02-09T18:21:33Z" level=info msg="rocketchat.myrocketchat: joining #Test (ID: #Testrocketchat.myrocketchat)" prefix=rocketchat

time="2023-02-09T18:21:33Z" level=fatal msg="Starting gateway failed: Bridge rocketchat.myrocketchat failed to join channel: {"details":{"method":"getRoomIdByNameOrId"},"error":"error-not-allowed","errorType":"Meteor.Error","isClientSafe":true,"message":"Not allowed [error-not-allowed]","reason":"Not allowed"}" prefix=main

So it looks like Matterbridge is trying to enter the channel #Testrocketchat.myrocketchat which is a combination of the actual channel name #Test and the account name. And a channel of that (combined) name obviously does not exist and so the error message is "not allowed".

Beats me why Matterbridge combines the channel and the account name.

What am I doing wrong?

**To Reproduce**
Create a toml file as described above, start Matterbridge and watch the log.

**Expected behavior**
Success entering the channel.

**Screenshots/debug logs**
Use logs from running `matterbridge -debug` if possible.

**Environment (please complete the following information):**
 - OS: Debian 11
 - Matterbridge version: 1.26
 - If self compiled: n&a

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))

**Comment by 42wim** [comment]
```
time="2023-02-09T18:21:33Z" level=info msg="rocketchat.myrocketchat: joining #Test (ID: #Testrocketchat.myrocketchat)" prefix=rocketchat```

It tries to join #Test, the ID is just and internal ID that combines channel and account.

If you get the not allowed message the bot user isn't allowed. Or maybe the channel name is wrong, try a lowercase channel.
