### ISSUE TITLE
Change receive message log to debug level rather than info level

### ISSUE THREAD

**Issue by yousefmansy1** [42wim/matterbridge#1980]
Is it just me or should this log (line 33) output be a debug level log?
Getting a log output on every message from WhatsApp is quite noisy when not using debug output.

https://github.com/42wim/matterbridge/blob/24f6747516a9a80f82068656df50b3972928ba56/bridge/whatsappmulti/handlers.go#L26-L33

**Comment by 42wim** [comment]
yes, fixed in master now
