### ISSUE TITLE
API endpoint not sending new messages after client disconnects from /api/stream

### ISSUE THREAD

**Issue by adbenitez** [42wim/matterbridge#1983]
**Describe the bug**
unable to receive new messages from the matterbridge API (/api/messages or/api/stream)

**To Reproduce**
1. start matterbridge server
2. curl http://localhost:4242/api/stream
3. send message in some channel, it will be received in the stream
4. Ctrl+C, kill curl
5. curl http://localhost:4242/api/stream
6. send another message in some channel, it doesn't arrive
7. curl http://localhost:4242/api/messages also sends empty list
8. the matterbridge service needs to be restarted

This issue seems also to affect [fbridge-asyncio](https://github.com/powerjungle/fbridge-asyncio) in the README it is mentioned:
```
# With stream matterbridge doesn't seem to repond after the fbridge-asyncio script is restarted, but
# uses normal streaming, the messages mode is a hack sorta, which avoids this problem.
```

**Expected behavior**
the `/api/stream` endpoint can be used reliably without needing to restart the matterbridge server from time to time

**Environment (please complete the following information):**
 - OS: debian/linux
 - Matterbridge version: 1.26.0 6dafebc7
 
**Additional context**
tested with one and two gateways:
gateway1: two irc servers + api, all inout
gateway2: one irc server + api, all inout

**Comment by 42wim** [comment]
Thanks for reporting, fixed in master now
