### ISSUE TITLE
Discord webhook username spoofing suddenly broken

### ISSUE THREAD

**Issue by TheHolyRoger** [42wim/matterbridge#1985]
**Describe the bug**
I'm assuming this must be because discord changed something - the bot previously worked fine for several months.

Very suddenly, the discord webhook messages all share the same username even though they have different avatars.

Each bridged message will change the nickname of ALL previously bridged messages to the last user to speak over the bridge.

Was using version 1.25.3 which worked fine yesterday, broken today. So I updated to latest matterbridge but the issue is still present.

**To Reproduce**
Set up bridge with discord to any other network

**Expected behavior**
Historical messages keep the spoof nickname they were posted with.

**Screenshots/debug logs**
Nothing in logs.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Matterbridge version: 1.25.3-dev and 1.26.1-dev
 - If self compiled: 24f6747516a9a80f82068656df50b3972928ba56

**Comment by BrotherIAmPinnedHere** [comment]
Seems the latest Discord update fixed and broke many things. I'm seeing the same error on 1.26.0, but another error I reported fixed itself.

**Comment by TheHolyRoger** [comment]
@BrotherIAmPinnedHere Do you think it's a discord client side bug then rather than an API change?

**Comment by TheHolyRoger** [comment]
Yeah I don't see this issue on the discord mobile client, only on the desktop client. Very annoying. I guess I'll close this since it isn't a matterbridge issue

**Comment by BrotherIAmPinnedHere** [comment]
I don't know if I'd say it's just a client issue. I had problems with non-image files uploading through the bridge for weeks, and then the new Discord update fixed it. That can't be a client issue.
