### ISSUE TITLE
Links from Slack to Discord come through incorrectly

### ISSUE THREAD

**Issue by greenlighttec** [42wim/matterbridge#1989]
**Describe the bug**
Recently when sending links in Slack to Discord, they come across as a string of "[display name]|(link)"

Generally if you're using a regular string as the link it's not a huge deal however if you're sending a plain link of "https://www.google.com" in slack it comes across as "[https://www.google.com]|(https://www.google.com)" and is seen as one big url that makes it unsuable.

**To Reproduce**

1. Bridge slack and discord channels together
2. Send a link from Slack, e.g "https://www.google.com"
3. Examine Discord channel for the message

**Expected behavior**

Slack API uses the format of [display text]|(url) to receive links in messages. It seems it started using the same format to send it back to the API. This should be converted properly into the format Discord has for posting links into messages.

**Screenshots/debug logs**
Use logs from running `matterbridge -debug` if possible.

**Environment (please complete the following information):**
 - OS: [e.g. linux]
 - Matterbridge version: output of  `matterbridge -version`
 - If self compiled: output of `git rev-parse HEAD`

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))

**Comment by 42wim** [comment]
I can not reproduce.
Please paste your config and your matterbridge version

**Comment by oizyumov** [comment]
@greenlighttec could you share the config and the matterbridge version you're using?

**Comment by 42wim** [comment]
Closed because no response
