### ISSUE TITLE
ACTION not handled properly & Feature Request: customizable action formatting

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#199]
Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
version: 0.13.1-dev

### Please describe the expected behavior.
irc: /me does something
-> discord:  `{RemoteNickFormat} _{Text}_`
-> slack: /me **user**: does something

### Please describe the actual behavior. 
actions are not recognized as special and just transmitted like any other messages

i believe actions ( and /me ) is integrated into almost every platform reasonably well
and can be detected with relative ease (fallbck would be to not display them)
i think discord is the most ambiguous of the platforms i know well, /me just wraps the message in '_'

**Comment by NikkyAI** [comment]
i just tried it again and apparently its actually incorrectly handled
a action from irc is sent as `/me action test`
and getting received as
`bot: <username> username action test`

**Comment by 42wim** [comment]
Yes, that was explicit done like this, so that you know it's an action from irc, because the nick/username is added. So you know that user is performing the "action".

I'm not sure if it's worth all the extra code for something like this, mattermost handles actions with *, discord with _, no idea what telegram etc does.

**Comment by NikkyAI** [comment]
setting a prefix, like you can already 
and a postfix, 
to allow wrapping the message in formatting characters,
setting it to `""` by default is possible though, depending on the bridge

**Comment by TomTheDragon** [comment]
There is also an other problem with ACTION commands:
Some users send actions like this "*does something*" and the client then will sand it over as bold text for example. The problem now is that not every network supports text formatting, so you then cant see any differences between normal and ACTION text, which can get really confusing.

**Comment by NikkyAI** [comment]
at least on irc it is defined as ACTION
on discord a regex `^_(.*)_$` should match all actions send with `/me`
and i think it is similar for slack and matrix, cannot tell if mattermost adapted it the same way .. never used it

**Comment by 42wim** [comment]
@NikkyAI  I've added support for this for slack,mattermost,irc,gitter,matrix,xmpp and discord
You can try a binary from https://bintray.com/42wim/nightly/Matterbridge/_latestVersion (or build it yourself from master)

It's not customizable, it should do the action conversion correctly for the listed protocols.

**Comment by NikkyAI** [comment]
i tested on irc and discord, it works
although i would tweak it on platforms where its possible to not wrap the entire message in cursive
but only the message part
so instead of: _<**Nikky**> message_
you get: <**Nikky**> _message_
on discord

apart from that it works very well

**Comment by 42wim** [comment]
Ok, changed in master.

**Comment by jleclanche** [comment]
@42wim This doesn't look like it's handled correctly right now between irc and discord when using webhooks:

![image](https://user-images.githubusercontent.com/235410/33244881-d7d0b42a-d307-11e7-8912-f185b9e62f2f.png)
