### ISSUE TITLE
Error: "connection failed dial tcp: lookup irc.libera.chat: i/o timeout"

### ISSUE THREAD

**Issue by paulsybrandy** [42wim/matterbridge#1995]
**Describe the bug**
Everytime I try to start the program I get the "connection failed dial tcp: lookup irc.libera.chat: i/o timeout" error but I am not trying to connect through TLS. (see below)

**To Reproduce**
I have the following config set in the matterbridge.toml file:
`[irc.myirc]
Nick="[REDACTED]"
NickServNick="[REDACTED]" 
NickServPassword="[REDACTED]"
Server="irc.libera.chat:6667"
UseTLS=false
UseSASL=false
SkipTLSVerify=true
RunCommands=["PRIVMSG nickserv :IDENTIFY [REDACTED] {REDACTED]"] 
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "`

Then I launch with `./matterbridge -conf matterbridge.toml`

**Expected behavior**
When running the above mentioned command, it should load and start Matterbridge without an issue.

**Screenshots/debug logs**
[0000]  INFO main:         [setupLogger:/home/neocube/go/pkg/mod/github.com/42wim/matterbridge@v1.26.0/matterbridge.go:104] Enabling debug logging.
[0000]  INFO main:         [main:/home/neocube/go/pkg/mod/github.com/42wim/matterbridge@v1.26.0/matterbridge.go:44] Running version 1.26.0 
[0000]  INFO router:       [Start:/home/neocube/go/pkg/mod/github.com/42wim/matterbridge@v1.26.0/gateway/router.go:66] Parsing gateway gateway1
[0000]  INFO router:       [Start:/home/neocube/go/pkg/mod/github.com/42wim/matterbridge@v1.26.0/gateway/router.go:75] Starting bridge: irc.myirc 
[0000]  INFO irc:          [Connect:/home/neocube/go/pkg/mod/github.com/42wim/matterbridge@v1.26.0/bridge/irc/irc.go:81] Connecting irc.libera.chat:6667
[0000] DEBUG irc:          [getClient:/home/neocube/go/pkg/mod/github.com/42wim/matterbridge@v1.26.0/bridge/irc/irc.go:306] setting pingdelay to 1m0s
[0005] ERROR irc:          [doConnect:/home/neocube/go/pkg/mod/github.com/42wim/matterbridge@v1.26.0/bridge/irc/irc.go:194] disconnect: error: dial tcp: lookup irc.libera.chat: i/o timeout
[0005] FATAL main:         [main:/home/neocube/go/pkg/mod/github.com/42wim/matterbridge@v1.26.0/matterbridge.go:66] Starting gateway failed: Bridge irc.myirc failed to start: connection failed dial tcp: lookup irc.libera.chat: i/o timeout

**Environment (please complete the following information):**
 - OS: Kubuntu 22.10 x86_64
 - Matterbridge version: 1.26.0

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))
* tried dragging and dropping my config file in DOCX format but keeps saying that you do not support that file type so I will paste it here.

```
[nctalk.cloud]
# The location of your Nextcloud instance with Talk installed
Server="https://cloud.disroot.org"
Login="paul.neocube"
Password="[REDACTED]"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[whatsapp.mywhatsapp]
# Number you will use as a relay bot. Tip: Get some disposable sim card, don't rely on 
# your own number.
Number="[REDACTED]"

# First time that you login you will need to scan QR code, then credentials will be saved in 
# a session file. 
# If you won't set SessionFile then you will need to scan QR code on every restart.
# optional (by default the session is stored only in memory, till restarting matterbridge)
SessionFile="session-[REDACTED].gob"

# If your terminal is white we need to invert QR code in order for it to be scanned properly
# optional (default false)
QrOnWhiteTerminal=false

# Messages will be seen by other WhatsApp contacts as coming from the bridge. 
# Original nick will be part of the message.
RemoteNickFormat="{TENGO}"

[tengo]
RemoteNickFormat="myremotenickformat.tengo"

[xmpp.myxmpp]
Server="disroot.org:5222"
#Jid your userid
Jid="[REDACTED]"
Password="[REDACTED]"
Muc="conference.jabber.example.com"
Nick="[REDACTED]"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[irc.myirc]
Nick="neocube"
NickServNick="[REDACTED]"
NickServPassword="[REDACTED]"
Server="irc.libera.chat:6667"
UseTLS=false
UseSASL=false
SkipTLSVerify=true
RunCommands=["PRIVMSG nickserv :IDENTIFY [REDACTED] [REDACTED]"] 
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[irc.oftc]
Nick="[REDACTED]"
NickServNick="[REDACTED]"
Server="irc.oftc.net:6697"
UseTLS=false
SkipTLSVerify=true
RunCommands=["PRIVMSG nickserv :IDENTIFY [REDACTED] [REDACTED]"]
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[matrix.mymatrix]
#Server is your homeserver (eg https://matrix.org)
Server="https://matrix.org"

#login/pass of your bot.
#Use a dedicated user for this and not your own!
#Messages sent from this user will not be relayed to avoid loops.
#Login=""
#Password=""

#Alternatively you can use MXID and access token (open https://app.element.io/
#in INCOGNITO mode, open Settings -> lowest tab and above "clear cache and reload"
#you can find the access token. Close the window without logging out
#(or the token gets invalid (if it leaks, it can be removed by logging in and using the sessions menu))
MxID="[REDACTED]"
Token="[REDACTED]"

RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

#Whether to send the homeserver suffix. eg ":matrix.org" in @username:matrix.org
#to other bridges, or only send "username".(true only sends username)
#OPTIONAL (default false)
NoHomeServerSuffix=false

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="irc.myirc"
channel="#briar"

[[gateway.inout]]
account="irc.myirc"
channel="#matrix"
```

**Comment by 42wim** [comment]
It says 'failed to start: connection failed dial tcp: lookup xxx i/o timeout" , that means it can not resolve or connect, something wrong with your DNS server or network.

**Comment by MoralCode** [comment]
could this be related to running in docker somehow?
