### ISSUE TITLE
Matterbridge cannot read embedded Discord messages

### ISSUE THREAD

**Issue by ooglyboogly** [42wim/matterbridge#202]
Please answer the following questions. 

### Which version of matterbridge are you using?
version: 0.15.0 822605c

### If you're having problems with mattermost please specify mattermost version. 
N/A

### Please describe the expected behavior.
When an embedded message is posted in Discord, at the very least the text from the message(s) is delivered to bridged channel. Seems that there could be several DIV in the embedded message, so it may need to be broken up into multiple deliveries. Sending embedded pictures and links would be a plus.

### Please describe the actual behavior. 
Matterbridge does not even recognize the data from what i can tell. It does not show up in -debug as a message at all
#### Use logs from running ```matterbridge -debug``` if possible.
Blank -debug, no lines registered for embedded

### Any steps to reproduce the behavior?
Send an embedded message. I am receiving embedded message from another bot in my channel, so not exactly sure how its being produced.
![image](https://user-images.githubusercontent.com/2380915/27484385-a535c7b0-57ee-11e7-9fbb-e514328056e3.png)

#### (be sure to exclude or anonymize private data (tokens/passwords))
[slack]
[slack.scanner]
useAPI=true
Token="[Redacted]"
PrefixMessagesWithNick=true

[discord]
[discord.[Redacted]]
Token="[Redacted].[Redacted].[Redacted]"
Server="[Redacted]"

[general]
RemoteNickFormat="[{PROTOCOL}/{BRIDGE}] <{NICK}> "

[[gateway]]
    name = "mygateway"
    enable=true

    [[gateway.inout]]
    account = "discord.[Redacted]"
    channel="[Redacted]"

    [[gateway.inout]]
    account ="slack.scanner"
    channel = "[Redacted]"

**Comment by 42wim** [comment]
https://anidiotsguide.gitbooks.io/discord-js-bot-guide/examples/using-embeds-in-messages.html
Embedded fields can be everything. So that's not really feasible.

But relaying the Title / Description and URL of such a embedded message is an option.

**Comment by ooglyboogly** [comment]
I see, that does make it quite impossible to anticipate options. Hopefully you can get something to stick and ill see how much it helps my unique situation.

**Comment by 42wim** [comment]
Added a ShowEmbeds option to master. 
Could you rebuild from master and try this out ?
```
#Shows title, description and URL of embedded messages (sent by other bots)
#OPTIONAL (default false)
ShowEmbeds=true
```

**Comment by ooglyboogly** [comment]
I actually use the .exe version and am not building my own package. would you be able to supply a built exe by chance?

**Comment by 42wim** [comment]
Building is it really easy though. Could you try ?

Download and install the go compiler. https://storage.googleapis.com/golang/go1.8.3.windows-amd64.msi
Then just run ```go get github.com/42wim/matterbridge```, this will download and build your executable.
The resulting exe will be in c:\users\yourusername\go\bin\matterbridge.exe (actually in %USERPROFILE%\go\bin\matterbridge.exe)

**Comment by ooglyboogly** [comment]
Sure. Give me a bit to switch off my work device onto personal then :P 

I will let you know how it works for me! Thanks for your help.

**Comment by ooglyboogly** [comment]
I went ahead and added that line to the start of my toml and rebuilt master (version: 0.16.0-dev)

I ran it with -debug and still am not seeing any line items for the embedded messages in my channel. Lines before and after are showing just fine as expected.

[matterbridge.zip](https://github.com/42wim/matterbridge/files/1100736/matterbridge.zip)

**Comment by 42wim** [comment]
You did add the ```ShowEmbeds=true``` to your discord config?

**Comment by ooglyboogly** [comment]
Correct. It seems to compile just fine. Just does not recognize any embedded messages. If i add it twice it does say the flag is already in place so Id say its "working" but just not working for me?

[discord]
[discord.Kenna]
#Shows title, description and URL of embedded messages (sent by other bots)
#OPTIONAL (default false)
ShowEmbeds=true

**Comment by 42wim** [comment]
Okay, I've pushed a new commit with more discord debugging messages.
Could you rebuild from master again ?

You'll now have to do ```go get -u github.com/42wim/matterbridge``` (-u so it updates the code)

Then run with ```-debug```
You'll see messages like this now:
```
Receiving message &discordgo.Message{ID:"32900313784178", ChannelID:"2272701312", 
Content:"def", Timestamp:"2017-06-26T21:01:00.658000+00:00", EditedTimestamp:"",
MentionRoles:[]string{}, Tts:false, MentionEveryone:false, Author:(*discordgo.User)(0xc42037db20), 
Attachments:[]*discordgo.MessageAttachment{}, Embeds:[]*discordgo.MessageEmbed{},
Mentions:[]*discordgo.User{}, Reactions:[]*discordgo.MessageReactions(nil)}  module=discord
```

Try to reproduce the issue, first a normal message, then a message from the bot, and paste the debug output here.

**Comment by ooglyboogly** [comment]
Still am not seeing any recognition of the embedded message. Below you will see conversation as:
-Me: !filter 218
-Bot: Filter updated. I am now watching for...
-Me: hel
(Missing in conversation is the bot's immediate response)

> [37mDEBU[0m[2017-06-27T19:10:00-05:00] Receiving message &discordgo.Message{ID:"329413091769057282", ChannelID:"327253089302216704", Content:"!filter 218", Timestamp:"2017-06-28T00:10:01.277000+00:00", EditedTimestamp:"", MentionRoles:[]string{}, Tts:false, MentionEveryone:false, Author:(*discordgo.User)(0xc04216b810), Attachments:[]*discordgo.MessageAttachment{}, Embeds:[]*discordgo.MessageEmbed{}, Mentions:[]*discordgo.User{}, Reactions:[]*discordgo.MessageReactions(nil)}  [37mmodule[0m=discord
[37mDEBU[0m[2017-06-27T19:10:00-05:00] Sending message from ooglybooglies on discord.KennaBra to gateway  [37mmodule[0m=discord
[37mDEBU[0m[2017-06-27T19:10:00-05:00] Sending config.Message{Text:"!filter 218", Channel:"pokehuntrkennabra", Username:"ooglybooglies", UserID:"327179669441085441", Avatar:"https://cdn.discordapp.com/avatars/327179669441085441/5db6e8c7191301ba99c7d3704873946b.jpg", Account:"discord.KennaBra", Event:"", Protocol:"", Gateway:"mygateway", Timestamp:time.Time{sec:63634205400, nsec:676102200, loc:(*time.Location)(0x1053320)}} from discord.KennaBra (pokehuntrkennabra) to slack.scanner (pokehuntr)
[37mDEBU[0m[2017-06-27T19:10:00-05:00] Receiving config.Message{Text:"!filter 218", Channel:"pokehuntr", Username:"[discord/KennaBra] <ooglybooglies> ", UserID:"327179669441085441", Avatar:"https://cdn.discordapp.com/avatars/327179669441085441/5db6e8c7191301ba99c7d3704873946b.jpg", Account:"discord.KennaBra", Event:"", Protocol:"discord", Gateway:"mygateway", Timestamp:time.Time{sec:63634205400, nsec:676102200, loc:(*time.Location)(0x1053320)}}  [37mmodule[0m=slack
[37mDEBU[0m[2017-06-27T19:10:00-05:00] Receiving message &discordgo.Message{ID:"329413091919921155", ChannelID:"327253089302216704", Content:"**Filter updated.** I am now watching for the following Pokemon: Slugma", Timestamp:"2017-06-28T00:10:01.313000+00:00", EditedTimestamp:"", MentionRoles:[]string{}, Tts:false, MentionEveryone:false, Author:(*discordgo.User)(0xc0420edc00), Attachments:[]*discordgo.MessageAttachment{}, Embeds:[]*discordgo.MessageEmbed{}, Mentions:[]*discordgo.User{}, Reactions:[]*discordgo.MessageReactions(nil)}  [37mmodule[0m=discord
[37mDEBU[0m[2017-06-27T19:10:00-05:00] Receiving from slackclient &slack.MessageEvent{Msg:slack.Msg{Type:"message", Channel:"G5Y818HCJ", User:"U5YA6TL84", Text:"[discord/KennaBra] &lt;ooglybooglies&gt;  !filter 218", Timestamp:"1498608601.403709", IsStarred:false, PinnedTo:[]string(nil), Attachments:[]slack.Attachment(nil), Edited:(*slack.Edited)(nil), SubType:"", Hidden:false, DeletedTimestamp:"", EventTimestamp:"1498608601.403709", BotID:"B5Y8SM7V0", Username:"", Icons:(*slack.Icon)(nil), Inviter:"", Topic:"", Purpose:"", Name:"", OldName:"", Members:[]string(nil), File:(*slack.File)(nil), Upload:false, Comment:(*slack.Comment)(nil), ItemType:"", ReplyTo:0, Team:"T4P5NN11D", Reactions:[]slack.ItemReaction(nil)}, SubMessage:(*slack.Msg)(nil)}  [37mmodule[0m=slack
[37mDEBU[0m[2017-06-27T19:10:00-05:00] Sending message from HuntrBot on discord.KennaBra to gateway  [37mmodule[0m=discord
[37mDEBU[0m[2017-06-27T19:10:00-05:00] Sending config.Message{Text:"**Filter updated.** I am now watching for the following Pokemon: Slugma", Channel:"pokehuntrkennabra", Username:"HuntrBot", UserID:"295116861920772098", Avatar:"https://cdn.discordapp.com/avatars/295116861920772098/7663868f95a3ca4cc7a1d0ca6e498c27.jpg", Account:"discord.KennaBra", Event:"", Protocol:"", Gateway:"mygateway", Timestamp:time.Time{sec:63634205400, nsec:839753300, loc:(*time.Location)(0x1053320)}} from discord.KennaBra (pokehuntrkennabra) to slack.scanner (pokehuntr)
[37mDEBU[0m[2017-06-27T19:10:00-05:00] Receiving config.Message{Text:"**Filter updated.** I am now watching for the following Pokemon: Slugma", Channel:"pokehuntr", Username:"[discord/KennaBra] <HuntrBot> ", UserID:"295116861920772098", Avatar:"https://cdn.discordapp.com/avatars/295116861920772098/7663868f95a3ca4cc7a1d0ca6e498c27.jpg", Account:"discord.KennaBra", Event:"", Protocol:"discord", Gateway:"mygateway", Timestamp:time.Time{sec:63634205400, nsec:839753300, loc:(*time.Location)(0x1053320)}}  [37mmodule[0m=slack
[37mDEBU[0m[2017-06-27T19:10:00-05:00] Receiving from slackclient &slack.MessageEvent{Msg:slack.Msg{Type:"message", Channel:"G5Y818HCJ", User:"U5YA6TL84", Text:"[discord/KennaBra] &lt;HuntrBot&gt;  **Filter updated.** I am now watching for the following Pokemon: Slugma", Timestamp:"1498608601.403737", IsStarred:false, PinnedTo:[]string(nil), Attachments:[]slack.Attachment(nil), Edited:(*slack.Edited)(nil), SubType:"", Hidden:false, DeletedTimestamp:"", EventTimestamp:"1498608601.403737", BotID:"B5Y8SM7V0", Username:"", Icons:(*slack.Icon)(nil), Inviter:"", Topic:"", Purpose:"", Name:"", OldName:"", Members:[]string(nil), File:(*slack.File)(nil), Upload:false, Comment:(*slack.Comment)(nil), ItemType:"", ReplyTo:0, Team:"T4P5NN11D", Reactions:[]slack.ItemReaction(nil)}, SubMessage:(*slack.Msg)(nil)}  [37mmodule[0m=slack
[37mDEBU[0m[2017-06-27T19:10:01-05:00] Receiving message &discordgo.Message{ID:"329413095539605507", ChannelID:"327253089302216704", Content:"hel", Timestamp:"2017-06-28T00:10:02.176000+00:00", EditedTimestamp:"", MentionRoles:[]string{}, Tts:false, MentionEveryone:false, Author:(*discordgo.User)(0xc0420eca80), Attachments:[]*discordgo.MessageAttachment{}, Embeds:[]*discordgo.MessageEmbed{}, Mentions:[]*discordgo.User{}, Reactions:[]*discordgo.MessageReactions(nil)}  [37mmodule[0m=discord
[37mDEBU[0m[2017-06-27T19:10:01-05:00] Sending message from ooglybooglies on discord.KennaBra to gateway  [37mmodule[0m=discord
[37mDEBU[0m[2017-06-27T19:10:01-05:00] Sending config.Message{Text:"hel", Channel:"pokehuntrkennabra", Username:"ooglybooglies", UserID:"327179669441085441", Avatar:"https://cdn.discordapp.com/avatars/327179669441085441/5db6e8c7191301ba99c7d3704873946b.jpg", Account:"discord.KennaBra", Event:"", Protocol:"", Gateway:"mygateway", Timestamp:time.Time{sec:63634205401, nsec:614358200, loc:(*time.Location)(0x1053320)}} from discord.KennaBra (pokehuntrkennabra) to slack.scanner (pokehuntr)
[37mDEBU[0m[2017-06-27T19:10:01-05:00] Receiving config.Message{Text:"hel", Channel:"pokehuntr", Username:"[discord/KennaBra] <ooglybooglies> ", UserID:"327179669441085441", Avatar:"https://cdn.discordapp.com/avatars/327179669441085441/5db6e8c7191301ba99c7d3704873946b.jpg", Account:"discord.KennaBra", Event:"", Protocol:"discord", Gateway:"mygateway", Timestamp:time.Time{sec:63634205401, nsec:614358200, loc:(*time.Location)(0x1053320)}}  [37mmodule[0m=slack
[37mDEBU[0m[2017-06-27T19:10:01-05:00] Receiving from slackclient &slack.MessageEvent{Msg:slack.Msg{Type:"message", Channel:"G5Y818HCJ", User:"U5YA6TL84", Text:"[discord/KennaBra] &lt;ooglybooglies&gt;  hel", Timestamp:"1498608602.403877", IsStarred:false, PinnedTo:[]string(nil), Attachments:[]slack.Attachment(nil), Edited:(*slack.Edited)(nil), SubType:"", Hidden:false, DeletedTimestamp:"", EventTimestamp:"1498608602.403877", BotID:"B5Y8SM7V0", Username:"", Icons:(*slack.Icon)(nil), Inviter:"", Topic:"", Purpose:"", Name:"", OldName:"", Members:[]string(nil), File:(*slack.File)(nil), Upload:false, Comment:(*slack.Comment)(nil), ItemType:"", ReplyTo:0, Team:"T4P5NN11D", Reactions:[]slack.ItemReaction(nil)}, SubMessage:(*slack.Msg)(nil)}  [37mmodule[0m=slack


======
Attached here is the full HTML object of the message not being seen.
[discordEmbedFullHTML.txt](https://github.com/42wim/matterbridge/files/1107177/discordEmbedFullHTML.txt)

**Comment by 42wim** [comment]
The bot just doesn't get to see that message.
See if https://www.reddit.com/r/discordapp/comments/5ofhol/cannot_see_bot_messages/ helps

**Comment by ooglyboogly** [comment]
Alrighty... I think I figured it out. Dug into your msg handler a bit and got a second opinion.

You have a return in your code if content = "". By default, embedded messages have "" content. So your code cuts out before ever making it to check for embeds.

Need to find a way to either put embeds in front of the content check (like you do for attachments) or find a way to set a flag that continues the code but is used to avoid any errors from an empty content.

Let me know what you think.

**Comment by 42wim** [comment]
Thanks for the input and testing it on the chat :)
