### ISSUE TITLE
[Telegram] broken reply bridging

### ISSUE THREAD

**Issue by oizyumov** [42wim/matterbridge#2021]
**Describe the bug**
The bug appeared on the latest version of a docker image, released few days ago (March 15-16).

The bridge Telegram<->Slack: 
- lost the ability for forward avatars as well as 
- stopped bridging thread replies Telegram->Slack
Thus the Slack->Telegram replies work fine, while the opposite doesn't

**To Reproduce**
Pull the latest docker image 7d5149ae7614
set up `PreserveThreading=true` in .toml config file
Create and start the container.
Sending replies Slack->Telegram work fine, Telegram->Slack - does not

**Expected behavior**
Bridging replies in both directions

**Screenshots/debug logs**
Can provide the logs as well as config, if needed

**Environment (please complete the following information):**
 - OS: docker container
 - Matterbridge version: 1.26.1-dev 60639b6

**Additional context**
Can provide config file, if needed

**Comment by 42wim** [comment]
@cosmicboots could be your PR as that is the only change, is that something you could maybe take a look at ?

**Comment by GEkuL** [comment]
Can anybody confirm this behavior?
I'm not 100% sure that this is not a local issue.

**Comment by cosmicboots** [comment]
I can look into it as soon as I get a chance to set up a Slack testing environment.
@oizyumov could you post the config you used?

**Comment by oizyumov** [comment]
hi, @cosmicboots 

here's my .toml file stripped of comments and with the hidden variables:

```
[telegram]
    [telegram.Telegram]
        Token="*********************************************************"
        MessageFormat="HTML"
        UseFirstName=true
        QuoteLengthLimit=0
        QuoteFormat="```{QUOTEMESSAGE}``` {MESSAGE}"
        EditSuffix="\n\n (edited)"
        RemoteNickFormat="<ins><b>{NICK}</b> on <b>{PROTOCOL}</b></ins> \n"
        PreserveThreading=true
# ==============================================================================

[slack]
    [slack.Slack]
        Token="*********************************************************"
        Debug="true"
        QuoteFormat="re: ```{QUOTEMESSAGE}``` {MESSAGE}"
        EditDisable="true"
        EditSuffix=" (edited)"
        Label=""
        RemoteNickFormat="{NICK} [{PROTOCOL}]"
        PreserveThreading=true
        ShowUserTyping=true
# /
# GATEWAYS
# /
[[gateway]]
name="YourUniqueGateWayName"
enable=true

    [[gateway.inout]]
    account="telegram.Telegram"
    channel="-*************"

    [[gateway.inout]]
    account="slack.Slack"
    channel="general"

###################################################################
#General configuration
###################################################################
# Settings here are defaults that each protocol can override
[general]
StripNick=false
MediaDownloadPath="/path/to/icons"
MediaServerDownload="donload.server.to"
MediaDownloadSize=100000000
MediaDownloadBlacklist=[".html$",".htm$"]
IgnoreFailureOnStart=false
LogFile="/path/to/**.log"
```

**Comment by oizyumov** [comment]
hi, @cosmicboots
Any feedbacks on this bug?
I can share a prepared slack, if needed

**Comment by cosmicboots** [comment]
Sorry it's taken so long to get back. It's been a long week, but hopefully I'll have some time to put towards solving this over the weekend.

I setup a slack, did some initial testing, and found noticed that the replies only break once topics are enabled in the telegram group. My current assumption is that I'm misunderstanding how the changes to the Telegram API handle message replies.

Again, I'll hopefully have a chance to dig into the API over the next couple days and figure out what's going on.

**Comment by GEkuL** [comment]
@cosmicboots I'm not 100% sure I get what you mean, but the problem with replies happens to me on a single tg group, with no topics enabled, only threading is

**Comment by cosmicboots** [comment]
@GEkuL What exactly do you mean by "only threading is"? From what I tested replies still worked between slack and Telegram as long as topics weren't enabled.

**Comment by GEkuL** [comment]
> @GEkuL What exactly do you mean by "only threading is"? From what I tested replies still worked between slack and Telegram as long as topics weren't enabled.

@cosmicboots 
yeah, I mean I have PreserveThreading=true similarly as @oizyumov , and I face the bug despite not having topics in my telegram group ("replies only break once topics are enabled in the telegram group")

**Comment by oizyumov** [comment]
@cosmicboots 
> noticed that the replies only break once topics are enabled in the telegram group

I have troubles even on a simple tg group (with no topics), similarly to @GEkuL . Didn't try matterbridge on a group with topics yet.

**Comment by K3nn3th2** [comment]
having the same described problems as the OP 
in my case its whatsapp <-> telegram

replies done in whatsapp are displayed in the linked telegram group, yet replies sent in the telegram group do not reach the whatsapp group.

might be related to the telegram handling of matterbridge, not the slack/whatsapp handling?

**Comment by oizyumov** [comment]
@K3nn3th2 
> might be related to the telegram handling of matterbridge, not the slack/whatsapp handling?

I think yes, it's relates to telegram most probable, and the explanation is that before the recent update (considering only telegram files), everything was +- ok.

You can also look at the [messenger modules folder](https://github.com/42wim/matterbridge/tree/master/bridge), slack and whatsapp haven't been updated for at least 6 month, so it's on telegram or the matterbridge part itself, but I guess it's telegram.

**Comment by cosmicboots** [comment]
I've taken a crack at this and I think it boils down to some poor logic on my part; however, what I said previously still stands. Threads do still seem to work on groups without threads, **so long as they're not "supergroups"**. The logic for working with how the telegram API handles replies didn't seem to apply too well to supergroups and that slipped through my testing.

With that being said, I think I've found a solution and I'll be opening a PR in a minute.

**Comment by ilmaisin** [comment]
> @K3nn3th2
> You can also look at the [messenger modules folder](https://github.com/42wim/matterbridge/tree/master/bridge), slack and whatsapp haven't been updated for at least 6 month, so it's on telegram or the matterbridge part itself, but I guess it's telegram.

Well, the slack plugin hasn't been updated for a while, but the whatsapp plugin has been under active development. Note that the current plugin is in the "whatsappmulti" directory, the old "whatsapp" module is obsolete.
