### ISSUE TITLE
[Mattermost 🠒 Slack] The message from MM does not get into the Slack thread

### ISSUE THREAD

**Issue by Smacktur** [42wim/matterbridge#2022]
**Describe the bug**
The message from MM does not get into the Slack thread

**To Reproduce**
1. Sending a message from Slack  
2. We write to the thread of this message from MM

**Expected behavior**
The message from MМ is displayed in the Slack thread

**Screenshots/debug logs**
Use logs from running `matterbridge -debug` if possible.

**Environment (please complete the following information):**
 - OS: Red Hat 8.3.1-3
 - Matterbridge version: version: 1.26.0 6dafebc7

**Additional context**
Config:
[mattermost-slack.txt](https://github.com/42wim/matterbridge/files/10999398/mattermost-slack.txt)

MM:
![image](https://user-images.githubusercontent.com/16258894/225854480-0188197b-8dc5-48e7-921b-025c762c4aea.png)

Slack:
![image](https://user-images.githubusercontent.com/16258894/225854549-ddb8c406-0276-4729-837e-6aa51cde3eac.png)

**Comment by GEkuL** [comment]
Hi, did you set up preserve threading?

**Comment by GEkuL** [comment]
Btw, the fix could already be made (here)[https://github.com/42wim/matterbridge/pull/1574]

**Comment by Smacktur** [comment]
@GEkuL I apologize for my inattention. It seemed to me that such a basic function should work by default, out of the box. That's why the questions arose))
Everything works correctly if you add `PreserveThreading=true` to the configuration. Thanks!
