### ISSUE TITLE
Names are not prefixed

### ISSUE THREAD

**Issue by bkeys** [42wim/matterbridge#203]
Please answer the following questions. 

### Which version of matterbridge are you using?
Running version 0.15.0 822605c

### Please describe the expected behavior.
Names to be prefixed

#### (be sure to exclude or anonymize private data (tokens/passwords))
[mattermost]
    [mattermost.work]
    useAPI=true
    #do not prefix it wit http:// or https://
    Server="chat.org"
    Team="bot"
    Login="dbot"
    Password="password"
    PrefixMessagesWithNick=true

**Comment by 42wim** [comment]
It's all in the documentation https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample

Seems like I'll have to update the sample in the README you probably used though

```
#RemoteNickFormat defines how remote users appear on this bridge
#The string "{NICK}" (case sensitive) will be replaced by the actual nick / username.
#The string "{BRIDGE}" (case sensitive) will be replaced by the sending bridge
#The string "{PROTOCOL}" (case sensitive) will be replaced by the protocol used by the bridge
#OPTIONAL (default empty)
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
```
