### ISSUE TITLE
RemoteNickFormat should have a {FULLNAME} option

### ISSUE THREAD

**Issue by FFdhorkin** [42wim/matterbridge#2038]
## **Is your feature request related to a problem? Please describe.**
We just set up Matterbridge to connect some Mattermost and Slack channels. 

On the Mattermost side, we see both first and last name when using {NICK} (arguably, this might be a bug, since a nickname would be the @ handle). 

However, on the Slack side, we see the Mattermost @ handle, not the full name.

## **Describe the solution you'd like**
A new option for RemoteNickFormat that will allow us to display first and last name on Slack when it comes from Mattermost (and falls back on the @ nickname if name is not filled in)

## **Describe alternatives you've considered**
Tengo options don't seem to have access to full name, only nickname.

**Additional context**
nothing comes to mind

**Comment by Mikaela** [comment]
Thia is very similar to https://github.com/42wim/matterbridge/issues/1593 except that requests the names separately.

**Comment by KeiroD** [comment]
This seems to still be an issue. It also seems that the bridge doesn't quite fully support nicknames here. It's inconsistently picking between the actual server name and the displayed first name.

I tried USERID and that grabs the actual Discord ID but in numerical format. Not quite what I was looking for, but I thought that the UseFirstName would work but...
