### ISSUE TITLE
Multiple incomingwebhook URLs for multichannel config

### ISSUE THREAD

**Issue by fjen** [42wim/matterbridge#21]
The sample configuration shows how to configure multiple channels with seperate outgoingwebhook tokens. But there is only one incomingwebhook url in [mattermost]. The problem is, that each channel has it's own URL in Mattermost.

How do we configure seperate URLs?

**Comment by 42wim** [comment]
incoming webhooks can write to every channel, that's why you only need one incoming webhook.
The messages will be send to the MMChannel specified in the multiple channel config

**Comment by fjen** [comment]
thanks, i have found problem. It doesn't like mattermost channel names with a dot in it. removing the dot fixes it.
