### ISSUE TITLE
Funky Unicode causes XMPP to disconnect

### ISSUE THREAD

**Issue by strugee** [42wim/matterbridge#210]
Spin-off from #209, so same config and everything: sending `rel-nofollow (another` to IRC causes the XMPP bridge to disconnect.

**Comment by 42wim** [comment]
sigh, unicode :)
I don't have a XMPP test setup at the moment. 
Could you let me know if it gives the same issue on other unicode like chinese 系列與 or emoji 🙈 ?

**Comment by 42wim** [comment]
Ok, I fixed this master, going to release a v0.16.0-rc2 soon with this fix in.

**Comment by strugee** [comment]
> sigh, unicode :)

Hahahahahaha SO TRUE



> Ok, I fixed this master, going to release a v0.16.0-rc2 soon with this fix in.

Thank you so much! :tada:
