### ISSUE TITLE
We need a Discord moderator in the Discord support chat

### ISSUE THREAD

**Issue by BenWiederhake** [42wim/matterbridge#2118]
**Describe the bug**
There's currently a wave of Discord spammers that are posting malicious messages on Discord.

**To Reproduce**
Read the matterbridge support chat

**Expected behavior**
Malicious accounts and messages are removed within a reasonable time, thus limiting their impact.

**Screenshots/debug logs**
![Bildschirmfoto_2024-02-10_13-08-37](https://github.com/42wim/matterbridge/assets/2690845/5d7a5bd7-b1e3-415c-865d-27bd6739cd96)
![Bildschirmfoto_2024-02-10_13-08-57](https://github.com/42wim/matterbridge/assets/2690845/1178370a-3c2e-4c2a-99cd-8dc0dd627e39)

**Environment (please complete the following information):**
 - This is only about the support chat for matterbridge.
 - This issue is not about the matterbridge code

**Additional context**
I would be happy to take on the role of moderator, since I notice these issues somewhat quickly anyway.

Ping @42wim

**Comment by 42wim** [comment]
@BenWiederhake I've made you moderator on the discord channel, thanks for stepping up!
