### ISSUE TITLE
Consider updating go-xmpp

### ISSUE THREAD

**Issue by Hund** [42wim/matterbridge#2119]
**Is your feature request related to a problem? Please describe.**

Snikket (a modern implementation of XMPP that uses Prosody) recently decided to disable less secure mechanisms entirely. Which means that PLAIN authentication doesn't work anymore. It's now using SCRAM, which requires a newer version of go-xmpp in Matterbridge.

It's currently not possible to login to XMPP in Matterbridge. 

**Describe the solution you'd like**

Update go-xmpp to a newer version that supports SCRAM.

**Comment by mdosch** [comment]
If you update you should update to current master and not tag 0.0.1 as current master has some scram improvements and also Reis xep-0474.

**Comment by 42wim** [comment]
@Hund master now contains updated go-xmpp library, can you test ?

**Comment by Hund** [comment]
> @Hund master now contains updated go-xmpp library, can you test ?

Great! I can't see any new release to download though.

**Comment by Hund** [comment]
Great news! I tried building it myself, but didn't come far with it:

```
$ go install github.com/42wim/matterbridge@master
go: downloading github.com/42wim/matterbridge v1.26.1-0.20240523232832-65d78e38af39
go: github.com/42wim/matterbridge@master (in github.com/42wim/matterbridge@v1.26.1-0.20240523232832-65d78e38af39): go.mod:153: invalid go version '1.22.0': must match format 1.23
```

What's wrong? I know nothing about Go.

**Comment by mdosch** [comment]
I guess you should update golang as your version only does accept version strings in the format 1.23 and not in the format 1.23.4.

**Comment by 42wim** [comment]
Yes you need go 1.22 to build

If you have an older go version you can do:
Make sure ~/go/bin is in your PATH

```
go install golang.org/dl/go1.22.3@latest
go1.22.3 download
```

Now you can run `go1.22.3 install github.com/42wim/matterbridge@master`

**Comment by mdosch** [comment]
If you use debian stable, there is also go1.22 in bookworm-backports.

Am 24. Mai 2024 09:25:12 UTC schrieb Wim ***@***.***>:
>Yes you need go 1.22 to build
>
>If you have an older go version you can do:
>Make sure ~/go/bin is in your PATH
>
>```
>go install ***@***.***
>go1.22.3 download
>```
>
>Now you can run `go1.22.3 install ***@***.***`
>

**Comment by mdosch** [comment]
Ah, seems I got it wrong. There is go1.21 in bookworm-backports.

**Comment by Hund** [comment]
I can't get it to work. I'm probably doing something wrong?

```
time="2024-05-24T12:41:43+02:00" level=fatal msg="Starting gateway failed: Bridge xmpp.linuxkompis failed to start: PLAIN authentication is not an option: [SCRAM-SHA-1 SCRAM-SHA-1-PLUS]" prefix=main
```

```
matterbridge --version
version: 1.26.0 6dafebc7
```

**Comment by mdosch** [comment]
Seems you are running an older version:

> ~/build/go/bin/matterbridge --version
> version: 1.26.1-dev 

That's what I get running `go install 
***@***.***`

**Comment by Hund** [comment]
Oh. So `go install github.com/42wim/matterbridge@master` is not the correct thing to do then?

**Comment by mdosch** [comment]
It is, no idea why github censored that in my previous mail.
Are you sure you are running the matterbridge from your $GOBIN (if set) or $GOPATH/bin? Usually this is ~/go/bin/.

Am 24. Mai 2024 10:58:09 UTC schrieb Hund ***@***.***>:
>Oh. So `go install ***@***.***` is not the correct thing to do then?
>

**Comment by Hund** [comment]
> It is, no idea why github censored that in my previous mail. Are you sure you are running the matterbridge from your $GOBIN (if set) or $GOPATH/bin? Usually this is ~/go/bin/. Am 24. Mai 2024 10:58:09 UTC schrieb Hund ***@***.***>:
> […](#)
> Oh. So `go install ***@***.***` is not the correct thing to do then?

Yes.

```
johan at Atlas in ~/go/bin
$ ./matterbridge --version
version: 1.26.1-dev 
```

**Comment by mdosch** [comment]
Ah, OK. I asked because in <https://github.com/42wim/matterbridge/issues/2119#issuecomment-2129219647> you wrote 

> matterbridge --version
> version: 1.26.0 6dafebc7

No idea then, as I am not using matterbridge. But go-sendxmpp and two bots also using go-xmpp work fine on my server with disabled PLAIN auth.


Am 24. Mai 2024 11:09:29 UTC schrieb Hund ***@***.***>:
>> It is, no idea why github censored that in my previous mail. Are you sure you are running the matterbridge from your $GOBIN (if set) or $GOPATH/bin? Usually this is ~/go/bin/. Am 24. Mai 2024 10:58:09 UTC schrieb Hund ***@***.***>:
>> […](#)
>> Oh. So `go install ***@***.***` is not the correct thing to do then?
>
>Yes.
>
>```
>johan at Atlas in ~/go/bin
>$ ./matterbridge --version
>version: 1.26.1-dev 
>```
>

**Comment by Hund** [comment]
Oh.. I didn't even notice the `dev` at the end. That's fixed now.

It doesn't seem to connect though. The logs says nothing. Is there any way I can debug this?

**Comment by 42wim** [comment]
```--log-level=debug```

**Comment by Hund** [comment]
That didn't say much either. :/

```
root@linuxkompis:/home/johan# matterbridge -debug -conf /usr/local/bin/matterbridge.toml 
[0000]  INFO main:         [setupLogger:/home/johan/go/pkg/mod/github.com/42wim/matterbridge@v1.26.1-0.20240523232832-65d78e38af39/matterbridge.go:104] Enabling debug logging.
[0000]  INFO main:         [main:/home/johan/go/pkg/mod/github.com/42wim/matterbridge@v1.26.1-0.20240523232832-65d78e38af39/matterbridge.go:44] Running version 1.26.1-dev 
[0000]  INFO main:         [main:/home/johan/go/pkg/mod/github.com/42wim/matterbridge@v1.26.1-0.20240523232832-65d78e38af39/matterbridge.go:46] WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
[0000]  INFO config:       [NewConfig:/home/johan/go/pkg/mod/github.com/42wim/matterbridge@v1.26.1-0.20240523232832-65d78e38af39/bridge/config/config.go:275] Opening log file /var/log/matterbridge.log
```

**Comment by mdosch** [comment]
Seems to work with my prosody trunk, so it should also work with snikket.

```
~/build/go/bin/matterbridge -conf ~/matter.toml
[0000]  INFO main:         Running version 1.26.1-dev 
[0000]  INFO main:         WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
[0000]  INFO router:       Parsing gateway gateway1
[0000]  INFO router:       Starting bridge: xmpp.myxmpp 
[0000]  INFO xmpp:         Connecting mdosch.de:5222
[0000]  INFO xmpp:         Connection succeeded
[0000]  INFO xmpp:         xmpp.myxmpp: joining prtocolchannel (ID: prtocolchannelxmpp.myxmpp)
[0000]  INFO main:         Gateway(s) started successfully. Now relaying messages
```

Maybe you could have a look whether the current go-sendxmpp works with your snikket server (or gives a useful error if it doesn't) as it is using the same library.

**Comment by Hund** [comment]
@mdosch I just tried with go-sendxmpp, and it works just fine. :/

**Comment by mdosch** [comment]
Hmm, go-sendxmpp also has some additional logic (afair getting SRV records and trying until one works). Maybe you could check what connection methods are available (e.g. with a tool like xmpp-dns) and try whether it makes a difference when you enforce connecting to a certain endpoint.

Would you mind sharing a test account on your server?

**Comment by Hund** [comment]
Sure! I sent you an invite via e-mail.

**Comment by mdosch** [comment]
@Hund thanks.
So connecting works well as a client with StartTLS and DirectTLS. But I discovered that you have one SRV record for s2s which says it is xmpp*s*-server (DirectTLS) but listens on 5269 which is the port used for StartTLS. Xmpp-dns also fails with s2s:

```
xmpps-server YOURSERVER. 5269
Priority: 5 Weight: 0
IP: YOUR_IP
Connection: [OK]
TLS: [Not OK]
tls: first record does not look like a TLS handshake
```

So I recommend you fixing this by removing the *s* in the server SRV record and use `xmpp-server` instead of `xmpps-server`.

That's probably not your issue as matterbridge connects using c2s and not s2s but you should fix that anyway.

**Comment by mdosch** [comment]
@Hund afair it works now as it was an issue in the snikket server version you used, right?

**Comment by Hund** [comment]
> @Hund afair it works now as it was an issue in the snikket server version you used, right?

It works! It seemed to have been an issue on both ends.
