### ISSUE TITLE
What ports does matterbridge operate on?

### ISSUE THREAD

**Issue by guakamole** [42wim/matterbridge#212]
version: 0.16.0-rc1 e7e1013

Hello, first of, thank you for Matterbridge :)

I use it to create an IRC (inout) <-> XMPP MUC (inout) bridge. It works, except using my own XMPP server.

My XMPP server (prosody) runs in a LXC (Debian Stretch, with ports 5269, 5222, 80 and 443 open). It works, I've got users connected and using MUC.

I installed Matterbridge in the same LXC and while I can connect to other XMPP servers, I cant' get it to connect to my own server (the IRC part works anyway). I suspect it could be a port related issue, what ports does matterbridge operate on?

Here is my config:
```
[irc]

[irc.freenode]
Server="irc.freenode.net:6697"
UseTLS=true
SkipTLSVerify=true
Nick="supernickname"
NickServNick="NickServ"
NickServPassword="superpassword"
MessageDelay=500
MessageQueue=30
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[xmpp]

[xmpp.myserver]
Server="jabber.myserver.tld:5222"
Jid="superid@myserver.tld"
Password="anothersuperpassword"
Muc="conference.jabber.myserver.tld"
Nick="supernickname"
SkipTLSVerify=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[xmpp.foobar]
Server="jabber.foobar.tld:5222"
Jid="superid@jabber.foobar.tld
Password="yetanothersuperpassword"
Muc="conference.jabber.foobar.tld"
Nick="supernickname"
SkipTLSVerify=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]

name="superbridge"
enable=true

    [[gateway.inout]]
    account="irc.freenode"
    channel="#superchannel"

    [[gateway.inout]]
    # xmpp.foobar works, xmpp.myserver does not
    account="xmpp.foobar"
    channel="superchannel"
```
(relevant) Debug log:

```
DEBU[2017-07-05T14:41:06+02:00] &net.OpError{Op:"dial", Net:"tcp", Source:net.Addr(nil), Addr:(*net.TCPAddr)(0xc420217b00), Err:(*os.SyscallError)(0xc4202118c0)}  module=xmpp
FATA[2017-07-05T14:41:06+02:00] Starting gateway failed: Bridge xmpp.myserver failed to start: dial tcp myserverip:5222: getsockopt: connection timed out
```

**Comment by 42wim** [comment]
If it runs in the same lxc, shouldn't it connect to localhost ? (i'm not sure about lxc networking, but when using docker that's the case). 

If you go in the lxc and do a t```telnet jabber.myserver.tld 5222``` does that work ?

I'm pretty sure the issue is lxc networking related. Matterbridge connects to the ports you specified in the config, 5222 in your case and 6697 for irc

**Comment by guakamole** [comment]
> If it runs in the same lxc, shouldn't it connect to localhost ? (i'm not sure about lxc networking, but when using docker that's the case).

Indeed! Using "localhost" fixed the problem:

```
[xmpp.myserver]
Server="localhost:5222"
```

I was afraid that not providing the real IP address would mess with the TLS process (due to some wrong reverse DNS or whatever but that's not the case).

Problem solved, thank you for your help :)
