### ISSUE TITLE
Formatting of Slack messages 

### ISSUE THREAD

**Issue by iojw** [42wim/matterbridge#215]
Please answer the following questions. 

### Which version of matterbridge are you using?
 0.16.0-rc1

### Please describe the expected behavior.

Emojis from Slack are sent using the 'colon' format in text e.g. ': slightly_smiling_face :' for 🙂
They should be translated into their unicode equivalents before being displayed in other platforms.

Special characters "\&amp; \&lt; \&gt;" should also be decoded into "& < >" before being displayed in other platforms.

See: https://api.slack.com/docs/message-formatting#emoji and https://api.slack.com/docs/message-formatting#how_to_escape_characters

### Please describe the actual behavior. 

Emojis sent from Slack are displayed as text e.g. 🙂 displayed as ': slightly_smiling_face :'

Special characters sent from Slack are displayed as their encoded versions e.g.  '&' displayed as '\&amp;'

### Any steps to reproduce the behavior?

Send emojis or the special characters '& < >' from Slack and see how they are displayed in other platforms

**Comment by 42wim** [comment]
Thanks for the report and pointing me to those links.
:emoji: will now be translated to unicode across every bridge.
Both issues fixed in master.  (will be in 0.16.0 release soon)
