### ISSUE TITLE
WhatsApp with Baileys?

### ISSUE THREAD

**Issue by weskerty** [42wim/matterbridge#2168]
Is it in the plans to use baileys as a method to communicate with WhatsApp?
Currently this project does not work well with WhatsApp, could baileys be implemented and make it work? Are there plans for that?

**Comment by 42wim** [comment]
We're using whatsmeow, no plans for baileys

**Comment by weskerty** [comment]
> We're using whatsmeow, no plans for baileys

In that case, using WhatsApp is not recommended. WhatsApp will generate a ban that will affect the number permanently. At least until it is resolved.
3 of my numbers were banned this way with the use of some bot, and once you are banned this way the numbers will not be able to be started on phones without Google Play certification such as Huawei phones among others.
I saw that it happens on iPhone in the same way, but I don't know how it is resolved in those cases.
https://github.com/tulir/whatsmeow/issues/561
