### ISSUE TITLE
telegram whatsapp bridge: [Client ERROR] Client outdated (405) connect failure

### ISSUE THREAD

**Issue by fabio841** [42wim/matterbridge#2175]
0000]  INFO main:         Running version 1.26.0 
[0000]  INFO router:       Parsing gateway gateway1
[0000]  INFO router:       Starting bridge: whatsapp.mywhatsapp 
13:36:59.744 [Client ERROR] Client outdated (405) connect failure
[0003]  INFO whatsapp:     QR channel result: err-client-outdated
[0005]  INFO whatsapp:     WhatsApp connection successful
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12f5042]

goroutine 1 [running]:
github.com/42wim/matterbridge/bridge/whatsappmulti.(*Bwhatsapp).Connect(0xc000358fc0)
	/root/go/pkg/mod/github.com/42wim/matterbridge@v1.26.0/bridge/whatsappmulti/whatsapp.go:119 +0x622
github.com/42wim/matterbridge/gateway.(*Router).Start(0xc000108780)
	/root/go/pkg/mod/github.com/42wim/matterbridge@v1.26.0/gateway/router.go:76 +0x35f
main.main()
	/root/go/pkg/mod/github.com/42wim/matterbridge@v1.26.0/matterbridge.go:65 +0x39e

Why have this error ?
I have launch command ./matterbridge -conf matterbridge.toml

**Comment by fabio841** [comment]
solve incredible need update go!!!!!!
First check version. send command
go version
if is old need update.

use: 

git clone https://github.com/udhos/update-golang
cd update-golang
sudo ./update-golang.sh

restart ubuntu

later send command:
go install -tags nomsteams,whatsappmulti github.com/42wim/matterbridge@master

when finish start command:
./matterbridge-1.23.2-linux-64bit -debug -conf matterbridge.toml

QR CODE IS OK!!!!!

**Comment by mujeebcpy** [comment]
i updated everything but still getting error.
```pp..
10:50:11.337 [Client/Socket ERROR] Error reading from websocket: websocket: close 1006 (abnormal closure): unexpected EOF
[0002]  INFO whatsapp:     [Connect:/home/nivadaily/go/pkg/mod/github.com/42wim/matterbridge@v1.26.1-0.20240524210809-d16645c9527a/bridge/whatsappmulti/whatsapp.go:106] QR channel result: timeout
10:50:11.338 [Client ERROR] Client outdated (405) connect failure (client version: 2.2412.50)
[0003]  INFO whatsapp:     [Connect:/home/nivadaily/go/pkg/mod/github.com/42wim/matterbridge@v1.26.1-0.20240524210809-d16645c9527a/bridge/whatsappmulti/whatsapp.go:123] WhatsApp connection successful
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1477e66]

goroutine 1 [running]:
github.com/42wim/matterbridge/bridge/whatsappmulti.(*Bwhatsapp).Connect(0xc0000b0cc0)
        /home/nivadaily/go/pkg/mod/github.com/42wim/matterbridge@v1.26.1-0.20240524210809-d16645c9527a/bridge/whatsappmulti/whatsapp.go:125 +0x5e6
github.com/42wim/matterbridge/gateway.(*Router).Start(0xc00040ccd0)
        /home/nivadaily/go/pkg/mod/github.com/42wim/matterbridge@v1.26.1-0.20240524210809-d16645c9527a/gateway/router.go:76 +0x345
main.main()
        /home/nivadaily/go/pkg/mod/github.com/42wim/matterbridge@v1.26.1-0.20240524210809-d16645c9527a/matterbridge.go:65 +0x394
```

**Comment by fabio841** [comment]
Try use this format into matterbridge.toml

[telegram.mytelegram]
Token="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
#Create new TG bot and put the API token above.

RemoteNickFormat="<{NICK}> "
MessageFormat="HTMLNick >"

[whatsapp.mywhatsapp]
Number="+XXXXXXXX" #insert mobile number in IDC format
SessionFile="session-XXXXXXX.gob" ###insert mobile number in IDC format
QrOnWhiteTerminal=false


[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="whatsapp.mywhatsapp"
channel="XXXXXXXXXXXXX@g.us"
###Essentially this is the 'ChatID' equivalent to TG. To obtain it is a little convoluted. Follow the steps from the video below
###https://www.youtube.com/watch?v=W-VXISoKtNc

[[gateway.inout]]
account="telegram.mytelegram"
channel="-XXXXXXXXXXXX" #TG Group Chat ID. You will need to create a new Group Chat, assign the TG BOT created above to it and make it an admin of that group too.

**Comment by Vetgans** [comment]
Can confirm what @mujeebcpy experienced. I built the app with updated go as well, but got the same errors as [described](https://github.com/42wim/matterbridge/issues/2175#issuecomment-2306615822).

I'm bridging whatsapp to matrix, and at first sight it looks like [whatsmeow](https://github.com/tulir/whatsmeow) has to be updated.

**Comment by paxaman** [comment]
same problem here. go update not solved the problem

 [Client/Socket ERROR] Error reading from websocket: websocket: close 1006 (abnormal closure): unexpected EOF

**Comment by fabio841** [comment]
check version.
send command:
$ go version
If no have 1.23 there is a problem

**Comment by Vetgans** [comment]
> If no have 1.23 there is a problem

I did exactly as you told, used version 1.23.0, to no success.

**Comment by IntGrah** [comment]
I've made a pr fixing this issue; it's the WhatsApp web client which needs to be bumped.

**Comment by IntGrah** [comment]
I guess this is a dirty fix, the actual solution would be to bump the whatsmeow version. If you need a working binary asap, just clone the repo and bump the number as shown, and run `go install -tags whatsappmulti,nomsteams,nozulip`

**Comment by Vetgans** [comment]
Thanks for your effort! But a problem with the path occurs:

go install -tags nomsteams,nozulip,whatsappmulti github.com/IntGrah/matterbridge@master
go: downloading github.com/IntGrah/matterbridge v0.0.0-20240823131055-5a0dade4652c
go: github.com/IntGrah/matterbridge@master: version constraints conflict:
        github.com/IntGrah/matterbridge@v0.0.0-20240823131055-5a0dade4652c: parsing go.mod:
        module declares its path as: github.com/42wim/matterbridge
                but was required as: github.com/IntGrah/matterbridge
                
Maybe you could change that as well?

**Comment by IntGrah** [comment]
> Thanks for your effort! But a problem with the path occurs:
> 
> go install -tags nomsteams,nozulip,whatsappmulti github.com/IntGrah/matterbridge@master go: downloading github.com/IntGrah/matterbridge v0.0.0-20240823131055-5a0dade4652c go: github.com/IntGrah/matterbridge@master: version constraints conflict: github.com/IntGrah/[matterbridge@v0.0.0-20240823131055-5a0dade4652c](mailto:matterbridge@v0.0.0-20240823131055-5a0dade4652c): parsing go.mod: module declares its path as: github.com/42wim/matterbridge but was required as: github.com/IntGrah/matterbridge
> 
> Maybe you could change that as well?

`go install -tags ... <remote repo>` doesn't seem to work with forks. You have to clone the repo first, and then run `go install -tags ...` without any additional args. Hope this helps.

**Comment by naveenyeluru** [comment]
Getting _import lookup disabled_ error while installing post cloning the repo
![Snip20240823_1](https://github.com/user-attachments/assets/72cc3116-a208-4ca7-9f03-1ae1bb1fecaf)

**Comment by IntGrah** [comment]
> @IntGrah Getting _import lookup disabled_ error while installing post cloning the repo ![Snip20240823_1](https://private-user-images.githubusercontent.com/79347548/360968210-72cc3116-a208-4ca7-9f03-1ae1bb1fecaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjUxMjYsIm5iZiI6MTcyNDQyNDgyNiwicGF0aCI6Ii83OTM0NzU0OC8zNjA5NjgyMTAtNzJjYzMxMTYtYTIwOC00Y2E3LTlmMDMtMWFlMWJiMWZlY2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE0NTM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5YTlhZWVjYjM4YjBlNzhmZWY4MGVkMDc5NWExMmEzYmYzMTc3NDg5OGQ4NTMxZjE1MzNkODgzZmEwODczY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2WJDfpG2aS3xmfGmqPU1rD1mzOuK8NX5ISHxJ_G7IZ4)

My bad, I was messing around with changing the module name. It should work now.

**Comment by Vetgans** [comment]
> My bad, I was messing around with changing the module name. It should work now.

And it does!! Many thanks for your efforts. :+1:

**Comment by naveenyeluru** [comment]
> > @IntGrah Getting _import lookup disabled_ error while installing post cloning the repo ![Snip20240823_1](https://private-user-images.githubusercontent.com/79347548/360968210-72cc3116-a208-4ca7-9f03-1ae1bb1fecaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjUxMjYsIm5iZiI6MTcyNDQyNDgyNiwicGF0aCI6Ii83OTM0NzU0OC8zNjA5NjgyMTAtNzJjYzMxMTYtYTIwOC00Y2E3LTlmMDMtMWFlMWJiMWZlY2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE0NTM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5YTlhZWVjYjM4YjBlNzhmZWY4MGVkMDc5NWExMmEzYmYzMTc3NDg5OGQ4NTMxZjE1MzNkODgzZmEwODczY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2WJDfpG2aS3xmfGmqPU1rD1mzOuK8NX5ISHxJ_G7IZ4)
> 
> My bad, I was messing around with changing the module name. It should work now.

Its working now, thank you :)

**Comment by mujeebcpy** [comment]
@fabio841 Happy to see you are suggesting to view a video made by me :smile: ibcomputing is my channel and i made that tutorial

**Comment by fabio841** [comment]
thanks @mujeebcpy 
Guys, if you have any concerns, the possibility of forwarding messages between a WhatsApp channel instead of a group should be implemented. In this regard, if it can be useful, I found this interesting discussion which allows you to extract the channel JID: https://github.com/WhiskeySockets/Baileys/issues/549

essentially the channel has an ID that can be easily searched via developer console and WhatsApp web and ends with @newslatter.

Do you think this feature could be added? This would make it possible to use a channel instead of a group. I tried replacing the "TG Group Chat ID" of the group that ends in @g.us with ID @newsatter in the matterbridge.toml file but it doesn't work.

**Comment by mujeebcpy** [comment]
@fabio841 ya. sending to channel is must now. i manage telegram channel so if i can use matterbridge to update my whatsapp channel in realtime it will be excellent.

**Comment by fabio841** [comment]
only @42wim can help

**Comment by Draganis** [comment]
I have the exact same problem using Windows with go 1.23
Is there any solution by now?

**Comment by IntGrah** [comment]
> I have the exact same problem using Windows with go 1.23
> Is there any solution by now?

My fork has a temporary fix. Clone it and then run `go install -tags whatsappmulti` in the directory

**Comment by Draganis** [comment]
Thank you. It works now...

**Comment by fabio841** [comment]
@IntGrah you think it's possible adding feature for bridge channel ? (no group) I tried replacing the "TG Group Chat ID" of the group that ends in @g.us with ID https://github.com/newslatter in the matterbridge.toml file but it doesn't work.

**Comment by fabio841** [comment]
it's possible usa https://github.com/pedroslopez/whatsapp-web.js for adding bridge with channel instead whatsmeow ?

**Comment by 42wim** [comment]
Fixed in master now
