### ISSUE TITLE
Support pasted images

### ISSUE THREAD

**Issue by ctron** [42wim/matterbridge#22]
When a link to an image is pasted into mattermost, then the IRC channel will receive the image link and mattremost will show the link and the image.

When an image is pasted into the mattermost channel, then mattermost shows the image (differently) but the IRC channel gets nothing.

**Comment by 42wim** [comment]
Can't add support for this, because mattermost outgoing webhooks don't send the attachment information. 
With https://github.com/42wim/matterbridge-plus I could add support for it though because it uses the API.
