### ISSUE TITLE
Regression in Mattermost webhooks based receiving

### ISSUE THREAD

**Issue by Thracky** [42wim/matterbridge#221]
If you have a configuration problem, please first try to create a basic configuration following the instructions on [the wiki](https://github.com/42wim/matterbridge/wiki/How-to-create-your-config) before filing an issue.

Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
`INFO[2017-07-17T20:43:23Z] Running version 0.16.1 e99532f  `

### If you're having problems with mattermost please specify mattermost version. 
Mattermost 4.0.0

### Please describe the expected behavior.
Should not crash when starting the webhooks based receiving for mattermost module

#### Use logs from running ```matterbridge -debug``` if possible.
Segfaults when starting webhooks handler
```
INFO[2017-07-17T20:43:24Z] Gateway(s) started succesfully. Now relaying messages 
DEBU[2017-07-17T20:43:24Z] Choosing webhooks based receiving             module=mattermost
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8d3a3b]

goroutine 22 [running]:
github.com/42wim/matterbridge/matterhook.(*Client).Receive(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/42wim/matterbridge/matterhook/matterhook.go:138 +0x7b
github.com/42wim/matterbridge/bridge/mattermost.(*Bmattermost).handleMatterHook(0xc42043c1e0, 0xc42063a480)
        /go/src/github.com/42wim/matterbridge/bridge/mattermost/mattermost.go:195 +0x7b
created by github.com/42wim/matterbridge/bridge/mattermost.(*Bmattermost).handleMatter
        /go/src/github.com/42wim/matterbridge/bridge/mattermost/mattermost.go:146 +0xe0

```

### Any steps to reproduce the behavior?
Configure  webhook matterbridge with WebhookURL and WebHookBindAddress. Segfault will happen when handler starts.

Note that this behaviour does not happen on 0.16.0

#### (be sure to exclude or anonymize private data (tokens/passwords))
```
[irc]
[irc.xxx]
Server="ircserver:6697"
Password="somepassword"
UseTLS=true
Nick="matterbot"
NickServNick="nickserv"
NickServPassword="somepassword"

[mattermost]
[mattermost.work]
WebhookURL="https://mattermosthost/hooks/<apitoken>"
WebHookBindAddress="127.0.0.1:9999"

[[gateway]]
name="gateway1"
enable=true
[[gateway.inout]]
account="irc.xxx"
channel="#somechannel"
[[gateway.inout]]
account="mattermost.work"
channel="town-square"

```

**Comment by 42wim** [comment]
Thanks for reporting, seems like I cut & pasted instead of copy & pasted.

**Comment by 42wim** [comment]
You can find devel binaries with this patch in on https://bintray.com/42wim/nightly/Matterbridge/v0.16.1-24-g0302e4d#files
