### ISSUE TITLE
Rejoin to MUC after an XMPP service disruption

### ISSUE THREAD

**Issue by Gummikavalier** [42wim/matterbridge#222]
### Which version of matterbridge are you using?
0.16.0

### Please describe the expected behavior.
After a disruption (network or restart) in the XMPP service (OpenFire in our case), Matterbridge should rejoin to configured rooms (MUCs).

### Please describe the actual behavior. 
Matterbridge does not rejoin rooms.

### Any steps to reproduce the behavior?
Restart the XMPP service. Matterbridge rejoins rooms only after its own service has been restarted.

If this is a bug, I can provide config and logs. (Would require a break in our service so not included now.)

**Comment by 42wim** [comment]
To be honest, xmpp hasn't really been tested that much. 
Bridges are supposed to reconnect on disconnects, so this is definitely a bug.

I'll try to reproduce this and ping you if I need your logs.

**Comment by 42wim** [comment]
Should be fixed in master, you can find binaries here: https://bintray.com/42wim/nightly/Matterbridge/_latestVersion
Feedback welcome :-)

**Comment by Gummikavalier** [comment]
Thanks again! I did couple of restarts to our XMPP server and rejoin seems to work. :)

**Comment by jugendhacker** [comment]
For me this issues still exists if I join Matterbridge with an account on Server A into a group chat on Server B and the connection between them gets disrupted, then matterbridge stops releaying messages... a workaround for me is to join with a Account on the same server but this is not possible in every case...
