### ISSUE TITLE
.in/.out gateway settings possibly not working correctly.

### ISSUE THREAD

**Issue by NeuralMiner** [42wim/matterbridge#224]
### Which version of matterbridge are you using?
**version: 0.16.2 1e2f27c**

### Please describe the expected behavior.
I have 1 account in a gateway as .in and 3 as .out (no .inout). I expect only messages sent from the .in to be forwarded out.

#### Use logs from running ```matterbridge -debug``` if possible.
There are 4 accounts:
1x telegram.in
2x IRC.out
1x Slack.out
I expect only messages sent from the telegram channel to be forwarded to the other 3. 
Currently, a message sent from IRC channel 1 goes to Slack (and only Slack).
A message sent from IRC channel 2 goes to Slack (and only Slack).
A message from Slack goes to both IRC channel 1 and 2, with one of them echoed:

> **IRC channel 1: [slack] <neuralminer> Test Slack
> IRC channel 2: [slack] <[slack] <neuralminer> > Test Slack**

A message from telegram goes to all 3, also with echoes in the IRC channels:

> **IRC channel 1: [telegram] <NeuralMiner> Test TG
> IRC channel 2: [telegram] <[telegram] <NeuralMiner> > Test TG
> Slack: Test TG**

#### (be sure to exclude or anonymize private data (tokens/passwords))

```
[[gateway]]
name="bridge"
enable=true

    [[gateway.in]]
    account="telegram.link"
    channel="-1234567890"
	
    [[gateway.out]]
    account="irc.link"
    channel="#test123"	
	
    [[gateway.out]]
    account="irc.link"
    channel="#test345"
	
    [[gateway.out]]
    account="slack.link"
    channel="irc"	
```

I have a debug file is needed. Thanks.

**Comment by 42wim** [comment]
@NeuralMiner this should be fixed in master now.
You can find binaries here https://bintray.com/42wim/nightly/Matterbridge/v0.16.2-6-gc1c7961#files
Please reopen if it doesn't fix your issue

**Comment by NeuralMiner** [comment]
So far so good. Really appreciate the quick turnaround.
