### ISSUE TITLE
Two gateways getting bridged.

### ISSUE THREAD

**Issue by NeuralMiner** [42wim/matterbridge#225]
### Which version of matterbridge are you using?
**0.16.3-dev c1c7961**

### Please describe the expected behavior.
Messages will only bridge within own gateway.

### Please describe the actual behavior. 
I have 3 gateways. For some reason, two of the gateways are bridging. It only happens with a specific gateway enabled ("announcements") that has .in and .out bridges. It also occurs if I set the "announcements" gateway to false; I have to completely comment it out to stop the issue. 
For example (using "bridge" below), if I send a message from #main on irc.zzz, it should only go to -1111111111111 on TG and "irc" on Slack. Instead, it will also send whatever goes to the "irc" Slack channel to the "general" Slack channel and "-333333333333" on TG  (which are .out bridges in "announcements"). 
It seems as though #main being set as an .inout in "bridge" is overwriting it being set as .out in the "annoucements" gateway? Possibly related to #224?

Expected:
>IRC.#main: NeuralMiner - Test123
TG.-1111111111111: NeuralMiner - Test123
Slack.irc: NeuralMiner - Test123

Occurring:
>IRC.#main: NeuralMiner - Test123
TG.-1111111111111: NeuralMiner - Test123
Slack.irc: NeuralMiner - Test123
**Slack.general: NeuralMiner - Test123**
**TG.-333333333333: NeuralMiner - Test123**

Config:

```
[[gateway]]
name="bridge"
enable=true

    [[gateway.inout]]
    account="irc.zzz"
    channel="#main"		

    [[gateway.inout]]
    account="telegram.zzz"
    channel="-1111111111111"

    [[gateway.inout]]
    account="slack.zzz"
    channel="irc"	
	
[[gateway]]
name="announcements"
enable=false
	
    [[gateway.in]]
    account="telegram.zzz"
    channel="-2222222222222"	
	
    [[gateway.out]]
    account="irc.zzz"
    channel="#main"		
	
    [[gateway.out]]
    account="irc.zzz"
    channel="#main-help"	

    [[gateway.out]]
    account="telegram.zzz"
    channel="--333333333333"	

    [[gateway.out]]
    account="slack.zzz"
    channel="general"		
	
[[gateway]]
name="bridge2"
enable=true

    [[gateway.inout]]
    account="irc.zzz"
    channel="#main-help"	

    [[gateway.inout]]
    account="telegram.zzz"
    channel="--444444444444"	

	
[[gateway]]
name="bridge3"
enable=true

    [[gateway.inout]]
    account="irc.zzz"
    channel="#main-telegram"	

    [[gateway.inout]]
    account="telegram.zzz"
    channel="--333333333333"	
```

Thanks.

**Comment by 42wim** [comment]
Seems like a regression, I've added tests for this now ;-)
Should be fixed in master. You can download binaries on https://bintray.com/42wim/nightly/Matterbridge/v0.16.3-4-g5b191f7#files

**Comment by NeuralMiner** [comment]
Cool, I'll give it a go. Do you have a BTC/ETH donation address? It's deserved.

**Comment by 42wim** [comment]
I did not, but I have now, thanks for the support!

0xb3f9b5387c66ad6be892bcb7bbc67862f3abc16f
1N7cKHj5SfqBHBzDJ6kad4BzeqUBBS2zhs

**Comment by 42wim** [comment]
I'm going to close this for now, if it isn't fixed feel free to reopen.

**Comment by NeuralMiner** [comment]
So far so good; not seeing the issue anymore. Thanks again. 
Sent some BTC your way.
