### ISSUE TITLE
Feature Request: Transient user renaming for messages

### ISSUE THREAD

**Issue by Nihlus** [42wim/matterbridge#226]
EDIT: I'm sorry, this already exists for a number of services (Discord through webhooks, for instance). I hadn't realized. I would, however, like to request it specifically for Gitter (if that's a possibility).

----
I've been using matterbridge for a little while, and I'm very happy with it so far. However, it would be very nice if support for renaming/nicknaming the account on either end could be introduced.

To be more specific, instead of embedding the name of whoever spoke in the message, the bridge would temporarily rename or nickname the account it's using to whoever spoke. This could even be coupled with an avatar change, if it's fast enough. It would vastly improve the visual integration of the software.

Of course, not every protocol would support this, but it should be fairly trivial on Discord, and doable on many others.

**Comment by 42wim** [comment]
Unfortunately gitter doesn't allow this, so I can't add support for this.
