### ISSUE TITLE
IRC Freenode connection failed

### ISSUE THREAD

**Issue by guillaumedc** [42wim/matterbridge#229]
### Which version of matterbridge are you using?
Docker version    
1.0.0-dev 5b191f7 (42wim/matterbridge latest as 2017-07-29)

### If you're having problems with mattermost please specify mattermost version. 
Docker version 
4.0.0  (4.0.2-rc1) (mattermost/mattermost-preview latest as 2017-07-29)

### Please describe the expected behavior.
I expected each message posted on MatterMost to be transferred on IRC and each message posted on IRC to be transferred on MatterMost.

### Please describe the actual behavior. 
I don't see any bot connection, neither on MatterMost and neither on IRC.   
Messages are not transferred.

Docker logs state that connection to IRC has timed out.
<pre><code>
INFO[2017-07-29T16:05:35Z] Running version 1.0.0-dev 5b191f7
INFO[2017-07-29T16:05:35Z] WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
INFO[2017-07-29T16:05:35Z] Starting bridge: irc.freenode
INFO[2017-07-29T16:05:35Z] Connecting irc.freenode.net:6697              module=irc
2017/07/29 16:05:35 Connected to irc.freenode.net:6697 (185.30.166.38:6697)
FATA[2017-07-29T16:06:05Z] Starting gateway failed: Bridge irc.freenode failed to start: connection timed out
</code></pre>

### Any steps to reproduce the behavior?
Each restart produce the same behavior.

### Please add your configuration file 
<pre><code>
[irc]
    [irc.freenode]
    Server="irc.freenode.net:6697"
    Nick="matterbot"
    NickServNick="nickserv"
    NickServPassword="password"

[mattermost]
    [mattermost.xxxx]
    Server="mattermost.mycompany.com"
    Team="team-name"
    Login="matterbot"
    Password="password"
    PrefixMessagesWithNick=true
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="irc_gateway"
enable=true
inout = [
    { account="irc.freenode", channel="#channel", options={key="mykey"}},
    { account="mattermost.xxxx", channel="town-square" },
]
</code></pre>

**Comment by 42wim** [comment]
* 6697 is TLS but you don't have useTLS=true
If that doesn't fix it, it's somewhere getting firewalled on your system.

**Comment by guillaumedc** [comment]
It  works, I can know connect to IRC, thank you :D
I'm stuck further, matterbridge saying me that the team is not found.
It's probably not related.
I checked that the team name is correctly spelled (and it is).
I alos tried without hyphen and without capital letters, it does not change anything.
Do you know what can go wrong?

<pre><code>
INFO[2017-07-31T16:44:21Z] Running version 1.0.0-dev 5b191f7
INFO[2017-07-31T16:44:21Z] WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
INFO[2017-07-31T16:44:21Z] Starting bridge: irc.freenode
INFO[2017-07-31T16:44:21Z] Connecting irc.freenode.net:6697              module=irc
2017/07/31 16:44:21 Connected to irc.freenode.net:6697 (38.229.70.22:6697)
INFO[2017-07-31T16:44:21Z] Connection succeeded                          module=irc
INFO[2017-07-31T16:44:21Z] irc.freenode: joining #channel (#channelirc.freenode)
INFO[2017-07-31T16:44:21Z] Starting bridge: mattermost.xxxx
INFO[2017-07-31T16:44:21Z] Connecting using login/password (sending and receiving)  module=mattermost
INFO[2017-07-31T16:44:21Z] Connecting matterbot (team: team-name) on mattermost.patur.in  module=mattermost
INFO[2017-07-31T16:44:21Z] Found version 4.0.0.4.0.2-rc1.9c9a45ace54639797f8c56a0ae1a9edd.false  module=matterclient
FATA[2017-07-31T16:44:22Z] Starting gateway failed: Bridge mattermost.xxxx failed to start: team not found
</code></pre>

**Comment by 42wim** [comment]
The team name is found in the URL
```https://mattermost.yourcompany.com/teamname/channels/town-square```

Use the exact team name as in the URL

**Comment by guillaumedc** [comment]
Made it work!
The problem was that I didn't add the bot as channel member…
Thank you for the help and the quick response!
