### ISSUE TITLE
rocketchat->hipchat works only if message.UserName != b.Config.Nick

### ISSUE THREAD

**Issue by DenisBY** [42wim/matterbridge#231]
### Which version of matterbridge are you using?
```
# ./matterbridge -version
version: 1.0.0-rc1
```

### Please describe the expected behavior.
Message sent

### Please describe the actual behavior. 
Message doesn't sent

### Any steps to reproduce the behavior?
1. Set `Nick` to real user
2. Sent any message. No message in HipChat
3. Set `Nick` to anything except real user
4. Sent any message. Message appeared in HipChat

I guess this is because of this block:
```
		// do not loop
		if message.UserName == b.Config.Nick {
			continue
		}
```
here:
https://github.com/42wim/matterbridge/blob/master/bridge/rocketchat/rocketchat.go#L80

**Comment by 42wim** [comment]
That check is there so messages don't get looped.

I've just did a setup from scratch with docker, works fine (between gitter/rocketchat)
I'll see if I can test hipchat too.

In the incoming webhook settings, you get a "post as", default ```rocket.cat```

![image](https://user-images.githubusercontent.com/1810977/28793407-2dd88636-7633-11e7-9f8c-dc9030645961.png)

This must be the same setting as ```Nick="rocket.cat"``` in your rocketchat config

:warning: Do NOT set this as your own user, this must be a bot-user not being used for anything else.
