### ISSUE TITLE
[FEATURE REQUEST] Code Documentation

### ISSUE THREAD

**Issue by retiform** [42wim/matterbridge#235]
Could basic comments please be added to the code to explain what does what?  Im trying to see if I can add support for a few features, but reading undocumented code is a bit slow.

**Comment by 42wim** [comment]
Yes, that would be nice :)
In the mean time, feel free to join the matterbridge chat channels (on top of the README) and ask questions there.

**Comment by patcon** [comment]
There's a nice tool that makes workflow diagrams easy to play with. I was trying to read through code and roughly document the code path, in case it's useful to anyone else:

https://hackmd.io/D52mKzlmSIutLOj37pokFA

(if you want to improve, please create a new note and copy my notation in :) )

cc @git-sid
