### ISSUE TITLE
[Feature Request] Quotes on Telegram

### ISSUE THREAD

**Issue by TomTheDragon** [42wim/matterbridge#237]
I am not sure if this is possible but it would be really nice if we could also see the quoted messages, because it's a little bit confusing some times if youre not seeing them.
For example: You can not see if someone answers one of your posts.

**Comment by 42wim** [comment]
Could you give an example, maybe screenshot of what you mean ? I don't use telegram myself

**Comment by TomTheDragon** [comment]
In telegram, you can answer to someone specific by quoting. This is specially useful in bigger chats and gets used a lot. The problem is that when users in Telegram send a quote, users on the other side are just going to see the answer to the text, but not for which post this answer actually was.

![telegram_quote](https://user-images.githubusercontent.com/7361323/29847199-c3287266-8d1a-11e7-88cd-bb288e47da17.png)

**Comment by TomTheDragon** [comment]
In telegram, you can answer to someone specific by quoting. This is specially useful in bigger chats and gets used a lot. The problem is that when users in Telegram send a quote, users on the other side are just going to see the answer to the text, but not for which post this answer actually was.

![telegram_quote](https://user-images.githubusercontent.com/7361323/29847199-c3287266-8d1a-11e7-88cd-bb288e47da17.png)

**Comment by 42wim** [comment]
@TomTheDragon I tried adding this, but I don't use telegram, so it's blind coding ;-)
Could you test it out ?
Binaries on https://bintray.com/42wim/nightly/Matterbridge/v1.2.0-11-g4bda29c#files

**Comment by TomTheDragon** [comment]
I tried it and it seems to work fine so far and its already super useful :)
This is actually the first time ever, i see a bot using this ;)

It outputs like this atm:
botname: [User1] hi
botname: [User2] hey there (re @User1:hi)

I think it would be better to have an output more like this maybe:
botname: [User1] hi
botname: [User2] hey there [@User1: hi]

But it would be "perfect", if we could customize the output of this with some simple tags i think :)

**Comment by 42wim** [comment]
Ok, nice to see it works :)
I'll think about the customization
