### ISSUE TITLE
Broken after uprgade to mattermost 3.1

### ISSUE THREAD

**Issue by ctron** [42wim/matterbridge#24]
It seems that the matterbridge it broken after the upgrade to Mattermost 3.1:

Receiving (from IRC) works. But sending out from MM to IRC causes the following error:

```
Jun 23 14:12:19 ???? matterbridge[????]: 2016/06/23 14:12:19 schema: invalid path "post_id"
```

**Comment by 42wim** [comment]
Thanks for reporting. Fixed in v0.4.2
