### ISSUE TITLE
Username prefix

### ISSUE THREAD

**Issue by overload08** [42wim/matterbridge#241]
### Which version of matterbridge are you using?
1.1.0-dev

### Please describe the expected behavior.
Just a question. Is it possible to add username when we send message from mattermost to IRC ?

**Comment by 42wim** [comment]
Add ```RemoteNickFormat="[{PROTOCOL}] <{NICK}> "```` to your irc config
See https://github.com/42wim/matterbridge/wiki/Section-IRC-(basic)
Or follow https://github.com/42wim/matterbridge/wiki/How-to-create-your-config for the whole config
