### ISSUE TITLE
Using the Matterbridge to create a issue in Redmine

### ISSUE THREAD

**Issue by Unterstrichmoepunterstrich** [42wim/matterbridge#245]
Hello,

I used Matterbridge as a sooner. Now I run it and I have a feature request. 
Is it possible to create with help of the bot new issues or is there maybe  a client which is possible to do it?

I know, that Redmine provide a [https://www.redmine.org/projects/redmine/wiki/Rest_Issues](REST API) and it should be possible. 
Maybe its possible to contact the bot private and handle it like ChanServ in IRC.
The basic function should be, that you can create a new issue in a specific project and assign it to special user(s).

**Comment by 42wim** [comment]
Sorry, matterbridge isn't meant to be a real bot. There are other projects that focus on this kind of thing.
