### ISSUE TITLE
Slack - Disable forwarding of join and leave messages?

### ISSUE THREAD

**Issue by Sir-Will** [42wim/matterbridge#246]
Hey,
is there any way to disable the forwarding of the channel join and leave messages from slack?

**Comment by 42wim** [comment]
There is now, you can find the latest binary on https://bintray.com/42wim/nightly/Matterbridge/_latestVersion or build it yourself.
Slack join/leave messages now will be only visible if you have ```ShowJoinPart=true``` on the destination bridge (default false)

**Comment by Sir-Will** [comment]
Thanks a lot.
