### ISSUE TITLE
Option in config for IRC server encoding

### ISSUE THREAD

**Issue by mizhgan** [42wim/matterbridge#247]
Hello!
Instead of trying to autodetect encoding of text in IRC module and then transcode it to UTF-8 it will be helpful just to add option to irc config section for default IRC server encoding and allways transcode it.

**Comment by 42wim** [comment]
Support added in master, you can download dev binaries on https://bintray.com/42wim/nightly/Matterbridge/_latestVersion

**Comment by mizhgan** [comment]
Dev version works great with transcoding from IRC server to any other UTF-8 module, but reverse transcoding (from i.e. mattermost UTF-8 to IRC windows-1251) does not work.

**Comment by 42wim** [comment]
It should now, if you download latest dev build

**Comment by ZigFisher** [comment]
The feature works fine, I tested it!
Thank you Sir !
