### ISSUE TITLE
Latest build can't connect to Mattermost 4.1

### ISSUE THREAD

**Issue by jurgenhaas** [42wim/matterbridge#248]
Starting last night, matterbridge failed connecting to my mattermost instance with these error messages:

```
Found version 4.1.0.4.1.0.b520a0fd94a7f3f2213ff53c4430d876.false
Starting bridge: mattermost.xyz
Connecting bot@example.com (team: xyz) on mattermost.example.com
Connecting using login/password (sending and receiving)
Starting gateway failed: Bridge mattermost.paragon failed to join channel: failed to join
```

The credentials are correct and they worked OK so far. Maybe the latest GitLab update 9.5.2 which was released yesterday came with a mattermost update too? I hope the version number given above helps explaining that.

**Comment by 42wim** [comment]
Try logging in on the webinterface manually with the bot credentials.
And join the channel defined in your config

Logout again and run matterbridge, it should work now.
Matterbridge can't join channels that doesn't exist

**Comment by jurgenhaas** [comment]
Well, that's what I already did. The bot was already member of both channels matterbridge had to join. And the configuration has not changed for the last 6 months and always worked. It just stopped working last night.

**Comment by 42wim** [comment]
Is it a public or private channel ?

**Comment by jurgenhaas** [comment]
it'S private

**Comment by 42wim** [comment]
Should be fixed now in latest build on https://bintray.com/42wim/nightly/Matterbridge/_latestVersion

**Comment by jurgenhaas** [comment]
Thanks for the quick turnaround. Can you also trigger to docker image please?

**Comment by 42wim** [comment]
Sure, building now

**Comment by jurgenhaas** [comment]
Works like a charm, thanks a lot.
