### ISSUE TITLE
identify the user

### ISSUE THREAD

**Issue by llwp** [42wim/matterbridge#25]
it appears (and perhaps this is config) the bot posts all irc messages as itself - which is fine - but the original author from irc needs to be attributed.  at this time, it doesnt look like this is happening.

**Comment by 42wim** [comment]
See PrefixMessagesWithNick in the matterbridge.conf.sample

**Comment by llwp** [comment]
great thanks! funny, I saw ShowJoinPart but missed that a few lines down.. appreciated.
