### ISSUE TITLE
Slack backend ignores 1st message after boot

### ISSUE THREAD

**Issue by ninja-** [42wim/matterbridge#252]
If you have a configuration problem, please first try to create a basic configuration following the instructions on [the wiki](https://github.com/42wim/matterbridge/wiki/How-to-create-your-config) before filing an issue.

Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```

version: 1.1.1 d2caea7

### Please describe the expected behavior.
All slack messages are forwarded, when matterbridge is running.
### Please describe the actual behavior. 
After application has fully started up, ALWAYS the first slack message will be completely ignored.
Only the 2nd and next messages after start will be forwarded.

#### Use logs from running ```matterbridge -debug``` if possible.
DEBU[2017-09-07T08:18:12+02:00] WsClient: connected                           module=matterclient
INFO[2017-09-07T08:18:12+02:00] Connection succeeded                          module=mattermost
INFO[2017-09-07T08:18:12+02:00] mattermost.work: joining x(x.work) 
DEBU[2017-09-07T08:18:12+02:00] Not joining x already joined.  module=matterclient
INFO[2017-09-07T08:18:12+02:00] Starting bridge: slack.work                  
INFO[2017-09-07T08:18:12+02:00] Connecting using token (sending and receiving)  module=slack
DEBU[2017-09-07T08:18:12+02:00] StatusLoop:<nil>                              module=matterclient
DEBU[2017-09-07T08:18:12+02:00] WS PING                                       module=matterclient
INFO[2017-09-07T08:18:12+02:00] slack.work: joining x(x.work) 
INFO[2017-09-07T08:18:12+02:00] Gateway(s) started succesfully. Now relaying messages 
DEBU[2017-09-07T08:18:12+02:00] Choosing login/password based receiving       module=mattermost
DEBU[2017-09-07T08:18:12+02:00] Choosing token based receiving                module=slack

When the first message from slack should be received, there is nothing in the -debug log.
Only the 2nd and next messages are shown on -debug and properly forwarded.

On the other direction mattermost->slack there is no "first message" problem like this.

### Any steps to reproduce the behavior?
Run slack->mattermost pipe, send 2 messages, the first one would be ignored and the next one would be forwarded.

### Please add your configuration file 
Nothing unusual - the slack account is running on a bot token. The bot is on a channel.

**Comment by 42wim** [comment]
In the past slack would resent the last message of the channel after a reconnect. (that's why I ignore the first message)

Going to do some tests.

**Comment by 42wim** [comment]
fixed in master
