### ISSUE TITLE
[Mattermost] Image not forwarded when message empty

### ISSUE THREAD

**Issue by ninja-** [42wim/matterbridge#254]
If you have a configuration problem, please first try to create a basic configuration following the instructions on [the wiki](https://github.com/42wim/matterbridge/wiki/How-to-create-your-config) before filing an issue.

Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
version: 1.1.1 d2caea7

### If you're having problems with mattermost please specify mattermost version. 
Latest

### Please describe the expected behavior.
1. Setup mattermost<->slack pipe
2. Send an image on mattermost with no comment
3. That image is ignored and not forwarded to slack.

Image is forwarded properly if there is any comment (message) with the uploaded image.

### Please describe the actual behavior. 
Image is ignored.
#### Use logs from running ```matterbridge -debug``` if possible.
```
DEBU[2017-09-07T08:42:24+02:00] WsReceiver event: model.WebSocketEvent{Event:"posted", Data:map[string]interface {}{"channel_name":"x", "channel_type":"O", "image":"true", "otherFile":"true", "post":"{\"id\":\"z16dyrdsmtymxpfj7pod75ushy\",\"create_at\":1504766544123,\"update_at\":1504766544123,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"r964pkki97fj9rf1o1jwzij37r\",\"channel_id\":\"sedzrf1xc7bffrydeo8bmb53zh\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"\",\"type\":\"\",\"props\":{},\"hashtags\":\"\",\"file_ids\":[\"a55xt58ydprafefxu9prgzi1kr\"],\"pending_post_id\":\"r964pkki97fj9rf1o1jwzij37r:1504766543767\"}", "sender_name":"matterbridge", "team_id":"s5zfzk4qb7ry3mtdf3tdiairkr", "channel_display_name":"#x"}, Broadcast:(*model.WebsocketBroadcast)(0xc42005ca40), Sequence:35}  module=matterclient
DEBU[2017-09-07T08:42:24+02:00] WsReceiver event: model.WebSocketEvent{Event:"channel_viewed", Data:map[string]interface {}{"channel_id":"sedzrf1xc7bffrydeo8bmb53zh"}, Broadcast:(*model.WebsocketBroadcast)(0xc42005cac0), Sequence:36}  module=matterclient
```

### Any steps to reproduce the behavior?
Post an image (preferably a cat image 🐈 ) with no message to a mattermost channel.

### Please add your configuration file 
Mattermost running on a bot account.

**Comment by 42wim** [comment]
Fixed in master

![image](https://user-images.githubusercontent.com/1810977/30187897-128530f2-942c-11e7-9863-b119cedc97e0.png)
