### ISSUE TITLE
gitter↛discord (Gitter is not relaying)

### ISSUE THREAD

**Issue by drbloom** [42wim/matterbridge#256]
I followed [How to create your config](https://github.com/42wim/matterbridge/wiki/How-to-create-your-config) step by step...

Messages sent from Discord are relayed successfully to Gitter ✓
Messages sent from Gitter do not show up in Discord or in the matterbridge debug. ✗

```
[discord.mydiscord]
Token="XXX"
Server="XXX"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[gitter.mygitter]
Token="XXX"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="test"

[[gateway.inout]]
account="gitter.mygitter"
channel="XXX/Lobby"
```

I also tried adding the channel specific Discord webhook options, but in both cases the debug never showed any communication in the direction of Gitter→Matterbridge.

```$ ./matterbridge-linux64 -debug
INFO[2017-09-07T13:03:01Z] Enabling debug                               
INFO[2017-09-07T13:03:01Z] Running version 1.1.1 d2caea7                
INFO[2017-09-07T13:03:01Z] Starting bridge: gitter.mygitter             
INFO[2017-09-07T13:03:01Z] Connecting                                    module=gitter
INFO[2017-09-07T13:03:02Z] Connection succeeded                          module=gitter
INFO[2017-09-07T13:03:02Z] gitter.mygitter: joining XXX/Lobby (XXX/Lobbygitter.mygitter) 
INFO[2017-09-07T13:03:03Z] Starting bridge: discord.mydiscord           
INFO[2017-09-07T13:03:03Z] Connecting                                    module=discord
INFO[2017-09-07T13:03:03Z] Connecting using token                        module=discord
INFO[2017-09-07T13:03:03Z] Connection succeeded                          module=discord
INFO[2017-09-07T13:03:04Z] discord.mydiscord: joining test (testdiscord.mydiscord) 
INFO[2017-09-07T13:03:04Z] Gateway(s) started succesfully. Now relaying messages```

**Comment by 42wim** [comment]
Are you running a dedicated bot user for gitter ? Or are you testing with your own gitter account ?

**Comment by drbloom** [comment]
Ah! I'm using my own gitter account.
If I need a gitter-bot to make this work, is there one that you recommend?
Thanks for developing Matterbridge. I'll share my progress.

**Comment by 42wim** [comment]
Hey no sorry I meant you have to create a dedicated user (a new account specifically for the bot/matterbridge) first.   
It will not relay messages from yourself if you use your account.

**Comment by drbloom** [comment]
Thank you!
It's working nicely now. I really like the ability to have multiple routing rules i.e.
- gitter ⇒ discord1 uni-directional  ✓
- gitter ⇄ discord2 bi-directional    ✓

I'm moving on now to try with Slack, Mattermost, ...
