### ISSUE TITLE
Slack Messages in multiple Lines

### ISSUE THREAD

**Issue by chr1syy** [42wim/matterbridge#258]
Hello,

following problem with relaying Slack-Messages:

We've got a ping channel that pings every user like this:

"What:
When:
Where:

SENT BY:"

The relay itself works, but it only shows one line, then editing the message and show the next line etc.
At the End everything in the Discord channel is: "SENT BY:", nothing else.

### Which version of matterbridge are you using?

1.1.1

### Any steps to reproduce the behavior?

Sending Slack messages in multiple Lines.

**Comment by 42wim** [comment]
Ok, seems to be introduced when I added code for actually editing messages.
If you use an older version v1.0.1 it should work.

**Comment by chr1syy** [comment]
Is there an easy way to downgrade?

**Comment by 42wim** [comment]
@chr1syy I just fixed it in master :-)
You can download the binaries on https://bintray.com/42wim/nightly/Matterbridge/v1.1.2-2-g90a61f1#files
