### ISSUE TITLE
UseSlackCircumfix doesn't actually work?

### ISSUE THREAD

**Issue by RangerRick** [42wim/matterbridge#26]
I had been using matterbridge-plus, but I saw that it got merged back into matterbridge so I just switched my install over to use regular matterbridge instead.

The migration docs say that `UseSlackCircumfix` there, but when I try to start, I get:

```
2016/08/09 12:35:59 Failed to parse /opt/mattermost/config/matterbridge.conf:invalid variable: section "IRC" subsection "" variable "UseSlackCircumfix"
```

Did this get lost in the migration back to matterbridge?

**Comment by 42wim** [comment]
Did you read the migration notes? https://github.com/42wim/matterbridge/blob/master/migration.md

**Comment by RangerRick** [comment]
I did!  And apparently I read them wrong, haha.  I saw the bold part as the replacement, and completely missed the text for "use this instead".  :/  Sorry for the noise.
