### ISSUE TITLE
Mattermost: webhooks not properly forwarded

### ISSUE THREAD

**Issue by ninja-** [42wim/matterbridge#260]
If you have a configuration problem, please first try to create a basic configuration following the instructions on [the wiki](https://github.com/42wim/matterbridge/wiki/How-to-create-your-config) before filing an issue.

Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
master :3

### If you're having problems with mattermost please specify mattermost version. 
4.2

### Please describe the expected behavior.
Having a mattermost->slack pipe, when a webhook arrives on mattermost, it should be forwarded with the username being post.props.override_username(i.e. GitLab, Jenkins etc.)

### Please describe the actual behavior. 
The webhook is forwarded to slack, but the username shown is the username of the webhook owner.
(in mattermost, the incoming webhooks get the user id of the owner, with possible visible username override in post.props.override_username of post's json)
Additionally the links and the attachment part is not properly forwarded to slack, it's all mixed up:
1. Attachment is mixed with post's content, instead of being "recreated"
2. Links are not properly forwarded, in slack they are visible as \[ Link to google ](https://google.com) "raw".

### Any steps to reproduce the behavior?
1. Setup a mattermost<-> slack pipe.
2. Post any webhook to mattermost channel, i.e. GitLab/Jenkins

**Comment by 42wim** [comment]
The override username thing is fixed in master. The other stuff probably has to do with gitlab/jenkins using "slack attachments" instead of normal messages.

**Comment by 42wim** [comment]
Should be fixed in master
