### ISSUE TITLE
Feature request: Allow authentication to Q on Quakenet

### ISSUE THREAD

**Issue by heinrich5991** [42wim/matterbridge#263]
Q is the account service of Quakenet. The authentication works by sending a `PRIVMSG` to `Q@CServe.quakenet.org` or by using the custom `AUTH` command.

Direct support for this would be useful, as it could then delay channel joining until after authentication (and possibly cloaking) finished.

**Comment by 42wim** [comment]
If you connect to quakenet and take the nick of a registered user without authing first.
Do you get a notice or a privmsg or something from Q ? (like on freenode) This can be used to trigger the auth command.

If so, could you paste an example of this ?

**Comment by heinrich5991** [comment]
There is no concept of registered nicks on Quakenet. The purpose of accounts is that you can get permissions in channels that know you. You can also cloak your hostname by setting the user mode `+x`: https://www.quakenet.org/help/general/what-user-modes-are-available-on-quakenet.

I suppose that you may start registering directly after you have fully connected to Quakenet (at the point where you'd normally join a channel).

**Comment by heinrich5991** [comment]
```
PRIVMSG Q@CServe.quakenet.org :AUTH <username> <password>
```
or in a client:
```
/msg Q@CServe.quakenet.org AUTH <username> <password>
```

**Comment by 42wim** [comment]
Support added in master.

```
#If you registered your bot with a service like Nickserv on freenode.
#Also being used when UseSASL=true
#
#Note: if you want do to quakenet auth, set NickServNick="Q@CServe.quakenet.org"
#OPTIONAL
NickServNick="nickserv"
NickServPassword="secret"

#OPTIONAL only used for quakenet auth
NickServUsername="username"

```

**Comment by heinrich5991** [comment]
Thanks, works.
