### ISSUE TITLE
Slack leaves empty attachments visible on Android

### ISSUE THREAD

**Issue by ninja-** [42wim/matterbridge#264]
If you have a configuration problem, please first try to create a basic configuration following the instructions on [the wiki](https://github.com/42wim/matterbridge/wiki/How-to-create-your-config) before filing an issue.

Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
version: 1.2.1-dev 

### Please describe the expected behavior.
There should be not empty attachments visible on Android Slack app.

### Please describe the actual behavior. 
For every text message forwarded to slack, empty attachment is visible on the Android app.
It's probably related to this piece of code
```
        np.Attachments = append(np.Attachments, slack.Attachment{CallbackID: "matterbridge"})
        np.Attachments = append(np.Attachments, b.createAttach(msg.Extra)...)
```
But I am not sure if removing it will break detecting "own" messages or something based on the CallbackID in attachment...

### Any steps to reproduce the behavior?
1. Setup mattermost->slack pipe
2. Post something on mattermost
3. Open slack on Android and see empty attachment next to the message

**Comment by 42wim** [comment]
Also see https://github.com/42wim/matterbridge/issues/262#issuecomment-330369260
Yes, removing it will break detection.

**Comment by ninja-** [comment]
@42wim maybe we can request slack to "fix it" on mobile...after all it's not displayed on the web version, so there is some check that blocks display of empty attachments.

**Comment by 42wim** [comment]
ninja-: feel free to do that :)

**Comment by ninja-** [comment]
I sent a ticket with details, I'll let you know if they agree to fix it.

**Comment by ninja-** [comment]
Slack acknowledged this as a bug, it will be fixed but there's no date yet

**Comment by 42wim** [comment]
Cool, is there a link somewhere I can refer to?

**Comment by ninja-** [comment]
sadly no but they will message me when the fix goes live, so I'll forward that information here

**Comment by ninja-** [comment]
![chrome_2017-09-20_23-05-54](https://user-images.githubusercontent.com/5637961/30667569-475bac80-9e58-11e7-87c4-c10a61fcb888.png)

**Comment by ninja-** [comment]
fixed upstream :)

**Comment by 42wim** [comment]
cool! thanks for remembering :)

**Comment by ninja-** [comment]
<img width="462" alt="2017-10-26_22-39-23" src="https://user-images.githubusercontent.com/5637961/32075925-921d1562-ba9e-11e7-88e2-7adc32779912.png">
