### ISSUE TITLE
Slack: link unfurling generates additional message

### ISSUE THREAD

**Issue by ninja-** [42wim/matterbridge#266]
If you have a configuration problem, please first try to create a basic configuration following the instructions on [the wiki](https://github.com/42wim/matterbridge/wiki/How-to-create-your-config) before filing an issue.

Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
1.2.1-dev

### Please describe the expected behavior.
When a youtube link is posted on slack, only one message is generated on Mattermost.

### Please describe the actual behavior. 
The link is posted twice, the second one being generated when slack unfurls the link and creates an attachment.
### Any steps to reproduce the behavior?
1. Setup mattermost->slack pipe
2. Post a youtube link on Slack

**Comment by 42wim** [comment]
You mean like this ? with a second "edited" message ? or something else ?

![image](https://user-images.githubusercontent.com/1810977/30610257-eb1a1608-9d7d-11e7-8a6a-b2566f8903e1.png)

**Comment by 42wim** [comment]
Fixed for me ;-)

**Comment by ninja-** [comment]
I haven't seen any edited though...let me test your fix.

**Comment by ninja-** [comment]
I confirm it's fixed, thanks ^_^

**Comment by ninja-** [comment]
It would be cool if the links were unfurled on the mattermost side too...if that isn't too much :P
