### ISSUE TITLE
[Feature Request] Renaming of nicks and certain words/text parts

### ISSUE THREAD

**Issue by TomTheDragon** [42wim/matterbridge#269]
I have added an welcome bot to one of my Discord chats, so that everyone on the Telegram side can see, if someone new joined. I renamed the bot's name on discord, so that it cant be mistaken for an user.
The problem is now, that the users still see the original name on Telegram. So it would be cool to have some way to add an nick replace rule.

The other feature i want to talk about, is an function to do the same kind of thing for the chat texts themselves. You then could also use this to remove or add special formatting.

**Comment by Sir-Will** [comment]
Regex replace for messages would be great.

**Comment by 42wim** [comment]
Just added support for regex replace messages. (not for nicks yet)

It replaces outgoing messages from the bridge. 
So you need to place it by the sending bridge definition.

Some examples:

This replaces cat => dog and sleep => awake
```
ReplaceMessages=[ ["cat","dog"], ["sleep","awake"] ]
```

Replaces every number with number. 
123 => numbernumbernumber
```
ReplaceMessages=[ ["[0-9]","number"] ]
```

**Comment by 42wim** [comment]
Now also works with nicks by using ```ReplaceNicks```

**Comment by TomTheDragon** [comment]
The nick replacing seem to work fine for Telegram but how can i setup this for Discord? I tried to enter the shown name and the username (with the number) but both dont seem to work.

**Comment by 42wim** [comment]
Works fine here, you should run with -debug first, to be sure you have the correct name. 
Look at `username` in `config.Message{}`

So for discord I add this to my discord section
`ReplaceNicks=[ ["wim#","blah"] ]`

And it replaces `wim#` to `blah`

```
DEBU[2018-01-02T00:17:58+01:00] Sending config.Message{Text:"test", Channel:"general", Username:"wim#", UserID:"227183947686215680", Avatar:"https://cdn.discordapp.com/avatars/227183947686215680/bd0e6c7fe63274597a4684884891b79d.jpg", Account:"discord.test", Event:"", Protocol:"", Gateway:"discordtest", Timestamp:time.Time{wall:0xbe8ace496e26b603, ext:96207453953, loc:(*time.Location)(0x1496700)}, ID:"397528908397936641", Extra:map[string][]interface {}(nil)} from discord.test (general) to matrix.test (#testing:matrix.org)
```
