### ISSUE TITLE
Channel Key's

### ISSUE THREAD

**Issue by wdayjlr** [42wim/matterbridge#27]
When an IRC channel is utilizing channel key's the messages don't forward between IRC and Mattermost. Messages still forward from Mattermost to IRC

Currently I specify the channel key in the IRC channel option. E.g. IRC="#ChannelName ChannelKey"

This allows the Matterbridge user to connect and I can see the messages hit the bridge but nothing seems to forward.

As soon as I remove the channel key from the IRC channel and rerun Matterbot then messages forward again from IRC to Mattermost.

**Comment by chillosu** [comment]
Seeing this as well.

**Comment by 42wim** [comment]
Yes,  this is not possible at the moment. 
I'm not sure yet how to fix this without making the config file and code too complex. 

You can't add the key to the channel, because those channel values are used in the code to know what channel maps to another.

**Comment by dmendyke** [comment]
Can you be more specific?  Why would adding a channel key make the config file and code overly complex?

**Comment by 42wim** [comment]
Code has changed to make it easier (and add generic options)
I'll be adding a commit to allow support for irc channel keys.

It can be specified as in 2 examples below

using inout
```
[[gateway]]
    name = "testing"
    enable=true

    [[gateway.inout]]
    account = "irc.freenode"
    channel = "#testing"

           [gateway.inout.options]
           key = "abc"
```

or specifying in/out explicitly
```
[[gateway]]
    name = "testing"
    enable=true

    [[gateway.in]]
    account = "irc.freenode"
    channel = "#testing"

           [gateway.in.options]
           key = "abc"

    [[gateway.out]]
    account = "irc.freenode"
    channel = "#testing"

           [gateway.out.options]
           key = "abc"

```
