### ISSUE TITLE
Each time Matterbridge joins XMPP MUC room, it gets message with room topic and retranslates it to all linked rooms

### ISSUE THREAD

**Issue by dluciv** [42wim/matterbridge#272]
### Which version of matterbridge are you using?
1.3.0

### Please describe the expected behavior.

I think it should detect those XMPP stanzas and get an option to either drop them or... I do not know. May be either drop them or do as it does now.

### Please describe the actual behavior.

Each time Matterbridge joins XMPP MUC room, it gets message with room topic and retranslates it to all linked rooms. This leads to lots of garbage.

**Comment by 42wim** [comment]
You mean in the console output ? or in messages sent to users ?

**Comment by dluciv** [comment]
Thank you for quick reply! I mean messages to users.

29 сент. 2017 г. 11:05 PM пользователь "Wim" <notifications@github.com>
написал:

**Comment by 42wim** [comment]
Could you give me an example of this output ?

**Comment by dluciv** [comment]
Console output?

**Comment by 42wim** [comment]
The messages to the users (lots of garbage as you say) you see.

**Comment by dluciv** [comment]
OMG, I did told it in a wrong way, so you misunderstood me. No garbage (like wrong encoding, etc.) Everything is ok there. Sorry for confusing you.

I just want to say that each time Matterbridge enters MUC room (and it does this relatively frequently), it gets XMPP message with room topic from server.

Like following:

```
<message from="muc_room_name@my.server" type="groupchat" to="my@jid/my_client">
<subject>Room topic</subject>
<body>topic: Room topic</body>
</message>
```

I guess it is relatively easy to recognize such messages (not from participant, but from room itself) and throw them away when rejoining until room topic really changes.

**Comment by 42wim** [comment]
@dluciv I filter now the subject messages, is your problem solved ?
You can find dev build binaries on https://bintray.com/42wim/nightly/Matterbridge/_latestVersion

**Comment by dluciv** [comment]
Yeah, now it only forwards subject once, when entering room, and then filters them. It is quite ok, thank you!
