### ISSUE TITLE
Forward the Telegram Bots Messages ---> Matrix

### ISSUE THREAD

**Issue by prinzpi** [42wim/matterbridge#277]
### Which version of matterbridge are you using?
**Matterbridge v1.3.1**

### Please describe the expected behavior.
Message from the bot should also  be forwarded to the Matrix Channel.

### Please describe the actual behavior. 
My scenario:
I'm using another bot to post something in a Telegram group, this messages should be forwarded to the Matrix Channel.
It's only working for "normal" user.
I have read, that the messages from the bot will not be forwarded, so I have created an additional bot and are using this key. 

So I have two bots:
Bot1: Is posting something into the Telegram group.
Bot2: Using this API key in my config file and is connected to the Matrix channel.

Isn't it possible, that Bot2 forward the messages from Bot1 - because it's still a bot an every bot messages will not be forwarded?

Thanks in advance for help.

### Please add your configuration file 
```
[telegram.mytelegram]
#See https://core.telegram.org/bots#6-botfather
#and https://www.linkedin.com/pulse/telegram-bots-beginners-marco-frau
Token="THE TOKEN OF BOT2"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[matrix.mymatrix]
#Server is your homeserver (eg https://matrix.org)
Server="serveraddres.com"

#login/pass of your bot.
#Use a dedicated user for this and not your own!
#Messages sent from this user will not be relayed to avoid loops.
Login="bot"
Password="bots_password"

RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="telegram.mytelegram"
channel="-2662xxxx"

[[gateway.inout]]
account="matrix.mymatrix"
channel="#Alias:serveraddress.com"
```

**Comment by 42wim** [comment]
See https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots
Telegram doesn't allow this
