### ISSUE TITLE
Custom media server for bridged content

### ISSUE THREAD

**Issue by BFlorry** [42wim/matterbridge#278]
Primarily for Telegram, but also handy for other bridges too.

The documentation on Telegram-bridge says the following:

`#WARNING! If enabled this will relay GIF/stickers/documents and other attachments as URLs
#Those URLs will contain your bot-token. This may not be what you want.
#For now there is no secure way to relay GIF/stickers/documents without seeing your token.
#OPTIONAL (default false)
UseInsecureURL=false`

Because of this, it is mandatory to handle the bridging of content from Telegram with some sort of media server. If I remember right, https://github.com/FruitieX/teleirc does this already. This way, the bot's token would not be exposed and the content uploaded could be somewhat more manageable.

**Comment by 42wim** [comment]
I'm doing this already for content from slack to mattermost by reuploading the content from slack to mattermost. I guess this could also be done for telegram.

A media server on the other hand needs to be reachable from the internet to work.

**Comment by thrrgilag** [comment]
It would be nice to include matrix in the media passing as well.  

One advantage to a media server is that bridge connections like xmpp or irc which don't handle media necessarily could get a link at least.  Could be an optional thing, or maybe just have a media dumping location which could be served outside of matterbridge.  Just some random thoughts.

**Comment by 42wim** [comment]
@BFlorry Just committed support for reuploading content from telegram to bridges that support file uploads (slack,discord,mattermost,telegram).

I don't use telegram, so any testing would be appreciated, you can download a binary here https://bintray.com/42wim/nightly/Matterbridge/v1.3.1-20-g115c4b1#files

In the december holiday's I'll probably have some time to add a media server for bridges where you can't upload images.

**Comment by 42wim** [comment]
@thrrgilag matrix support has been added in master. Images/videos from telegram and slack are now being uploaded to matrix

**Comment by 42wim** [comment]
I've just added support for sending files to your own "mediaserver". 
This is supported for the irc, xmpp and gitter bridges (who don't support native uploading).

An example of how to setup your own with caddy can be found on https://github.com/42wim/matterbridge/wiki/Mediaserver-setup-%5Badvanced%5D

**Comment by TomTheDragon** [comment]
Is there a way to limit how big this MediaServer upload folder is going to get? Would be cool to have a size limit, so that it automatically removes older files, when the folder comes close to the limit.

**Comment by 42wim** [comment]
@TomTheDragon no, that is out of scope for matterbridge. You could run a script that delete old files
