### ISSUE TITLE
matterbridge crashes on matrix server 503 response

### ISSUE THREAD

**Issue by mrosseel** [42wim/matterbridge#284]
### Which version of matterbridge are you using?
1.3.1 (also tested on 1.2)

### Please describe the expected behavior.
matterbridge doesn't crash when the matrix server is unresponsive, it should disconnect and try again at some later time.

### Please describe the actual behavior. 

Shortly after startup, matterbridge crashes, probably because the matrix server is having connectivity issues

```
DEBU[2017-10-24T07:59:31Z] gomatrix.HTTPError{WrappedError:error(nil), Message:"Failed to POST JSON to /_matrix/client/r0/login: <html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>\n", Code:503}  module=matrix
FATA[2017-10-24T07:59:31Z] Starting gateway failed: Bridge matrix.mymatrix failed to start: msg=Failed to POST JSON to /_matrix/client/r0/login: <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
 code=503 wrapped=
```

### Any steps to reproduce the behavior?
probably any service returning 503 should crash the matrix handling of matterbridge 

### Please add your configuration file 

This configuration has worked perfectly for many weeks so probably not the cause of the issue.

```
[slack]
    [slack.test]
    Token=""
    RemoteNickFormat="[{PROTOCOL}] {NICK} "

[irc]
    [irc.freenode]
    Server=""
    Nick=""
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[telegram.mytelegram]
    Token=""
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
    
[matrix.mymatrix]
    Server="https://matrix.org"
    Login=""
    Password=""
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name = "mygateway"
enable=true
    [[gateway.inout]]
    account = "slack.test"
    channel=""

    [[gateway.inout]]
    account ="irc.freenode"
    channel = ""

    [[gateway.inout]]
    account = "telegram.mytelegram"
    channel = ""

    [[gateway.inout]]
    account = "matrix.mymatrix"
    channel = ""
```

**Comment by mrosseel** [comment]
There was no more bridging going on after that message, but also no stack trace.
I can't recreate it at the moment because the matrix server is working correctly again

**Comment by 42wim** [comment]
That's actually correct behaviour, if at startup one of the bridges isn't available matterbridge refuses to start. You'll get the ```Starting gateway failed``` message, because 90% of the time it's because of wrong configuration.

If matterbridge is started and a service (matrix,slack,discord) disappears, matterbridge would try to reconnect. But the first time on startup it bails out.

Did you get this issue also while the bridge was running ? and it stopped responding ?

**Comment by mrosseel** [comment]
Agreed that at startup it's expected behaviour. 
I noticed the problem when no syncing occurred after a long period of correct behaviour, so I'm pretty sure it stopped during operation. Since it's not reproducible I can't help much beyond that.
It hasn't happened since then, so I propose to close this issue.

**Comment by 42wim** [comment]
Ok, thanks for the feedback
