### ISSUE TITLE
markdown markup characters in irc nicknames are not escaped when bridged to discord

### ISSUE THREAD

**Issue by illwieckz** [42wim/matterbridge#285]
### Which version of matterbridge are you using?

```
version: 0.12.1-dev
```

### Please describe the expected behavior.

Using characters known to be markdown control characters in irc nickname must not be parsed as markdown control character by discord.

### Please describe the actual behavior. 

Using a character known to be a markdown control character in irc nickname makes discord parsing the nickname.

### Any steps to reproduce the behavior?

Join an irc channel bridged to a discord one, and use this nickname:

```
`test
```

Then types this message in irc channel:

```
this is code`
```

You get that on discord side:

> \<`test> this is code`

You must get that:

> \<\`test> this is code

I guess any character known to be a markdown markup one must be escaped when found in irc nickname prior to be sent to discord.

**Comment by 42wim** [comment]
Fixed this by adding a new StripNick parameter, which strips every non-alphanumerical character.
