### ISSUE TITLE
numbers are dropped when following an irc control char while bridged to discord

### ISSUE THREAD

**Issue by illwieckz** [42wim/matterbridge#286]
### Which version of matterbridge are you using?

```
version: 0.12.1-dev
```

### Please describe the expected behavior.

numbers preceded by irc control code while chatting on irc are printed on discord.

### Please describe the actual behavior. 

numbers preceded by irc control code while chatting on irc are not printed on discord.

### Any steps to reproduce the behavior?

Type this in advanced irc client (like [hexchat](https://hexchat.github.io/)) on an irc channel bridged to a discord channel:

```
test <ctrl+b>1<ctrl+b>
<ctrl+b>123
test <ctrl+b>1a<ctrl+b>
<ctrl+b>123<ctrl+b>
```

You get that on irc side:

> \<nickname\> test **1**
> \<nickname\> **123**
> \<nickname\> test **1a**
> \<nickname\> **123**

You expect that on discord side:

> \<nickname\> test 1
> \<nickname\> 123
> \<nickname\> test 1a
> \<nickname\> 123

You get that on discord side:

> \<nickname\> test
> \<nickname\> test a
> \<nickname\>

As seen, typing control character followed by number only without closing control character on irc just makes the message not reported to discord at all. Using a closing control character just makes the message empty on discord side.

**Comment by 42wim** [comment]
Seems like the irc color stripping is too greedy

**Comment by illwieckz** [comment]
Thanks a lot, it fixed the bug at least for the reproduceable test I provided, by the way after upgrading matterbridge (and having verified reproduceable test provided above were fixed) I noticed that the bug is still present in some more complex case I don't figured yet how to reproduce. I'll tell you if I learn something more about the remaining occurence of this bug.

**Comment by illwieckz** [comment]
Typing that in hexchat:

```
<ctrl+k>121 a b
```

Produces that on IRC (in blue, since `<ctrl+k>12` is color code for blue):

```
1 a b
```

But produces that when bridged from IRC to discord:

```
 a b
```

It looks like the first digit after the color code is counted as part of color code but must not be. I guess the right solutions is to strip `<ctrl+k>[:digit:]` or `<ctrl+k>[:digit:][:digit]` (but no more than two digits).

**Comment by illwieckz** [comment]
The bug is still there for background color code too:

Typing that in hexchat:

```
<ctrl+k>12,051 a b
```

Produces that on IRC:

```
1 a b
```

But produces that when bridged from IRC to discord:

```
 a b
```

So, what needs to be filtered out:

- `<ctrl+k>[1 or 2 digit no more]`
- `<ctrl+k>[1 or 2 digit no more],[1 or 2 digit no more]`

**Comment by 42wim** [comment]
Ok, last commit should fix it for real now :)

**Comment by illwieckz** [comment]
Thanks, I tested and it now works flawlessly. Thank you a lot! :+1:

**Comment by lrstanley** [comment]
@42wim the background stripping functionality in girc has also been added, which should be more accurate than what you are currently doing. You could also just snag the regex I'm currently using and modify it slightly to strip everything in one go if wanted, but I've attempted to opt for the safer approach, of only stripping used ascsii escape codes. See [`girc.StripRaw()`](https://godoc.org/github.com/lrstanley/girc#StripRaw) (commit https://github.com/lrstanley/girc/commit/8b36377ce42e07b46c0ca14c89b56b124469d514). May be worth switching over for simplicity.

**Comment by 42wim** [comment]
@lrstanley Thanks for mentioning, too late for the next release, but I'm going to upgrade vendor soon and use more of your stuff, no need to invent wheels multiple times :)
