### ISSUE TITLE
Disable @everyone tag

### ISSUE THREAD

**Issue by Sir-Will** [42wim/matterbridge#289]
hey,

I have the bridge between slack and discord. On Discord the `@everyone` tag is disabled which prevents the notification on discord but the bridge does deliver this message to slack which causes to notify everyone on slack.

Is there currently any way to prevent this?

**Comment by 42wim** [comment]
You can use ```IgnoreMessages``` 
Specify ```IgnoreMessages="@everyone"``` on the sending bridge

**Comment by Sir-Will** [comment]
Thanks, wasn't aware of that option. There is no way to regex replace that instead of ignoring the message right?

**Comment by 42wim** [comment]
At the moment not, you could open a feature request for regex replacing messages though :)

**Comment by Sir-Will** [comment]
I guess this https://github.com/42wim/matterbridge/issues/269 already covers it or do you want a separate one?

**Comment by 42wim** [comment]
oh indeed, sorry :)
