### ISSUE TITLE
Unable to use "<{NICK}> " in RemoteNickFormat for IRC

### ISSUE THREAD

**Issue by alchrabas** [42wim/matterbridge#29]
I'm using matterbridge (0.6.0-beta2) for mattermost <-> IRC. It's working nicely except for one thing.

I wanted to set my own RemoteNickFormat in [IRC] section of matterbridge.conf, but when I've specified my selected format then the messages from mattermost were not shown on IRC.

After some tests I've noticed that when my configuration is:
> RemoteNickFormat="{NICK}: "

then everything works and messages are passed correctly, but when it's:
> RemoteNickFormat="<{NICK}> "

then the messages are not shown.

**Comment by 42wim** [comment]
Hi, I can't reproduce this. (I actually also use ```RemoteNickFormat="<{NICK}> "``` for my own bridge)
Could you paste your complete matterbridge.conf ? (redact servers/logins if necessary)

**Comment by alchrabas** [comment]
Hello.
I feel quite embarrassed, but the problem is my fault and it's completely unrelated to matterbridge. I've once set a quite broad ignore rule for messages in irssi, so they were received correctly but not displayed by the IRC client.
Thanks for your time and sorry for the trouble.
