### ISSUE TITLE
Config won't accept characters like "[" "]" anymore for bot username

### ISSUE THREAD

**Issue by NightKev** [42wim/matterbridge#298]
### Which version of matterbridge are you using?
version: 1.4.0 daac3eb

### Please describe the expected behavior.
Previously, I had set `Nick="[NKBot]"` as the bot's nick on IRC in the config when using version `1.0.1 a5259f5` and it worked with no problems.

### Please describe the actual behavior. 
After updating to 1.4.0 it gives me this error when I try the same nick: `ERRO[2017-11-11T03:08:47Z] error: invalid configuration: bad user/ident specified  module=irc`
It works fine if I remove the brackets from the nick.

#### (be sure to exclude or anonymize private data (tokens/passwords))
````
[discord]
  [discord.rc]
    Token="tokenwashere"
    Server="servernamewashere"
    RemoteNickFormat="{NICK} [{PROTOCOL}]"
    UseUserName=true
    WebhookURL="webhookurlwashere"

[irc]
  [irc.rizon]
    Server="irc.rizon.net:6667"
    Nick="[NKBot]"
    NickServNick="NightKev"
    NickServPassword="passwordwashere"
    RemoteNickFormat="<{NOPINGNICK}> "
    IgnoreNicks="some other bots were here"

[[gateway]]
  name="gateway1"
  enable=true

  [[gateway.inout]]
    account="discord.rc"
    channel="general"

  [[gateway.inout]]
    account="irc.rizon"
    channel="channelwashere"

**Comment by 42wim** [comment]
The new irc library is stricter about the username (is same as nick)
I've just fixed this in master.
You can find a dev build on https://bintray.com/42wim/nightly/Matterbridge/v1.4.0-1-gbcdecda#files

**Comment by lrstanley** [comment]
of note, the latest version of girc no longer enforces the restrictions based on the rfc spec. See commit https://github.com/lrstanley/girc/commit/7ea1eaacde9fd4ca19ef6339380b9b6911eb1207 for specifics (actually pushed that ~15 days ago, hah). If the vendored version of girc is updated, the temporary fix should no longer be necessary.

**Comment by 42wim** [comment]
@lrstanley  will do, thanks :)
