### ISSUE TITLE
Support wire / signal

### ISSUE THREAD

**Issue by fungs** [42wim/matterbridge#301]
I see that matrix.org is supported: that's really cool because I suppose this involves the encryption part which must be more difficult to implement. Any chance to do the same for Wire or Signal. I would really like to bridge these with other services. At least Signal has a command line (maybe even Go) implementation, I believe. Wire has a reference javascript implementation and a good spec, I believe.

**Comment by 42wim** [comment]
No, unfortunately at the moment it doesn't work with encrypted rooms.
the library I use hasn't support for this yet: https://github.com/matrix-org/gomatrix/issues/31

Wire doesn't have a go implementation, and implementing it myself is out of scope for me :(
Signal does have a go library for the protocol https://github.com/RadicalApp/libsignal-protocol-go but I can't seem to find anything about interfacing with the server. PR's / help is welcome!

Please use #28 issue for comments on new bridges

**Comment by agucova** [comment]
It seems there are already Matrix-Signal bridges available ([tulir/mautrix-signal](https://github.com/tulir/mautrix-signal)), maybe that could be a starting point?

**Comment by 42wim** [comment]
@agucova that's written in Python, someone can probably make a bridge using matterbridge API talking to the mautrix-signal. (but that someone isn't me)
