### ISSUE TITLE
1.4.1 not obeying RemoteNickFormat

### ISSUE THREAD

**Issue by alecisec** [42wim/matterbridge#303]
Matterbridge 1.4.1 no longer obeys the config string
RemoteNickFormat=" <{NICK}> "
when presenting messages relayed from IRC>Mattermost

Presentation on previous version (1.2) was:
 ```
<Username> Hello everyone!
```
Current version displays :
```
UsernameHello everyone!

```

Seems the space and brackets aren't being sent to the mattermost server
Messages in the other direction display correctly (Relayed from mattermost>IRC)

**Comment by 42wim** [comment]
Could you paste your complete config please ?
I'm running this setup myself and can not reproduce this.

**Comment by alecisec** [comment]
`###################################################################
#IRC section
###################################################################
#REQUIRED to start IRC section
[irc]

#You can configure multiple servers "[irc.name]" or "[irc.name2]"
#In this example we use [irc.freenode]
#REQUIRED
[irc.xxxxxxxx]
#irc server to connect to.
#REQUIRED
Server="xxxxxxxx.org.au:443"

#Password for irc server (if necessary)
#OPTIONAL (default "")
Password="xxxxxxxxx"

#Enable to use TLS connection to your irc server.
#OPTIONAL (default false)
UseTLS=true

#Enable SASL (PLAIN) authentication. (freenode requires this from eg AWS hosts)
#It uses NickServNick and NickServPassword as login and password
#OPTIONAL (default false)
UseSASL=false

#Enable to not verify the certificate on your irc server. i
#e.g. when using selfsigned certificates
#OPTIONAL (default false)
SkipTLSVerify=true

#Your nick on irc.
#REQUIRED
Nick="MATTERBRIDGEBOT"

#If you registered your bot with a service like Nickserv on freenode.
#Also being used when UseSASL=true
#OPTIONAL
NickServNick="nickserv"
NickServPassword="secret"

#Flood control
#Delay in milliseconds between each message send to the IRC server
#OPTIONAL (default 1300)
MessageDelay=1300

#Maximum amount of messages to hold in queue. If queue is full
#messages will be dropped.
#<clipped> will be add to the message that fills the queue.
#OPTIONAL (default 30)
MessageQueue=30

#Nicks you want to ignore.
#Messages from those users will not be sent to other bridges.
#OPTIONAL
IgnoreNicks="ircspammer1 ircspammer2"

#RemoteNickFormat defines how remote users appear on this bridge
#The string "{NICK}" (case sensitive) will be replaced by the actual nick / username.
#The string "{BRIDGE}" (case sensitive) will be replaced by the sending bridge
#The string "{PROTOCOL}" (case sensitive) will be replaced by the protocol used by the bridge
#OPTIONAL (default empty)
RemoteNickFormat=" <{NICK}> "

#Enable to show users joins/parts from other bridges (only from irc-bridge at the moment)
#OPTIONAL (default false)
ShowJoinPart=false

###################################################################
#mattermost section
###################################################################
[mattermost]
#You can configure multiple servers "[mattermost.name]" or "[mattermost.name2]"
#In this example we use [mattermost.work]
#REQUIRED

[mattermost.work]
#### Settings for webhook matterbridge.
#### These settings will not be used when useAPI is enabled

#Url is your incoming webhook url as specified in mattermost.
#See account settings - integrations - incoming webhooks on mattermost.
#REQUIRED (unless useAPI=true)
#URL="https://mattermost.xxxxxxxxx.com"

#Address to listen on for outgoing webhook requests from mattermost.
#See account settings - integrations - outgoing webhooks on mattermost.
#This setting will not be used when using -plus switch which doesn't use
#webhooks
#REQUIRED (unless useAPI=true)
#BindAddress="0.0.0.0:9999"

#Icon that will be showed in mattermost.
#OPTIONAL
IconURL="http://youricon.png"

#### Settings for matterbridge -plus
#### Thse settings will only be used when using the -plus switch.

#### Settings for using matterbridge API
#OPTIONAL
#useAPI=true

#The mattermost hostname.
#REQUIRED (when useAPI=true)
Server="mattermost.xxxxxxx.com"

#Your team on mattermost.
#REQUIRED (when useAPI=true)
Team="team12"

#login/pass of your bot.
#Use a dedicated user for this and not your own!
#REQUIRED (when useAPI=true)
Login="xxxxxxx@xxxxxx.com"
Password="xxxxxxxxxx"

#Enable this to make a http connection (instead of https) to your mattermost.
#OPTIONAL (default false)
NoTLS=false

#### Shared settings for matterbridge and -plus

#Enable to not verify the certificate on your mattermost server.
#e.g. when using selfsigned certificates
#OPTIONAL (default false)
SkipTLSVerify=true

#how to format the list of IRC nicks when displayed in mattermost.
#Possible options are "table" and "plain"
#OPTIONAL (default plain)
NickFormatter="plain"
#How many nicks to list per row for formatters that support this.
#OPTIONAL (default 4)

#Whether to prefix messages from other bridges to mattermost with the sender's nick.
#Useful if username overrides for incoming webhooks isn't enabled on the
#mattermost server. If you set PrefixMessagesWithNick to true, each message
#from bridge to Mattermost will by default be prefixed by "bridge-" + nick. You can,
#however, modify how the messages appear, by setting (and modifying) RemoteNickFormat
#OPTIONAL (default false)
PrefixMessagesWithNick=true

#Nicks you want to ignore.
#Messages from those users will not be sent to other bridges.
#OPTIONAL
IgnoreNicks="ircspammer1 ircspammer2"

#RemoteNickFormat defines how remote users appear on this bridge
#The string "{NICK}" (case sensitive) will be replaced by the actual nick / username.
#The string "{BRIDGE}" (case sensitive) will be replaced by the sending bridge
#The string "{PROTOCOL}" (case sensitive) will be replaced by the protocol used by the bridge
#OPTIONAL (default empty)
RemoteNickFormat="{NICK}"

#Enable to show users joins/parts from other bridges (only from irc-bridge at the moment)
#OPTIONAL (default false)
ShowJoinPart=false

###################################################################
#General configuration
###################################################################
#Settings here override specific settings for each protocol
[general]
#RemoteNickFormat defines how remote users appear on this bridge
#The string "{NICK}" (case sensitive) will be replaced by the actual nick / username.
#The string "{BRIDGE}" (case sensitive) will be replaced by the sending bridge
#The string "{PROTOCOL}" (case sensitive) will be replaced by the protocol used by the bridge
#OPTIONAL (default empty)
RemoteNickFormat=" <{NICK}> "

###################################################################
#Gateway configuration
###################################################################

#You can specify multiple gateways using [[gateway]]
#Each gateway has a [[gateway.in]] and a [[gateway.out]]
#[[gateway.in]] specifies the account and channels we will receive messages from.
#[[gateway.out]] specifies the account and channels we will send the messages
#from [[gateway.in]] to.
#
#Most of the time [[gateway.in]] and [[gateway.out]] are the same if you
#want bidirectional bridging. You can then use [[gateway.inout]]
#

[[gateway]]
#OPTIONAL (not used for now)
name="gateway1"
#Enable enables this gateway
##OPTIONAL (default false)
enable=true

    #[[gateway.in]] specifies the account and channels we will receive messages from.
    #The following example bridges between mattermost and irc
    [[gateway.inout]]

    #account specified above
    #REQUIRED
    account="irc.auscert"
    #channel to connect on that account
    #How to specify them for the different bridges:
    #
    #irc        - #channel (# is required)
    #mattermost - channel (the channel name as seen in the URL, not the displayname)
    #gitter     - username/room
    #xmpp       - channel
    #slack      - channel (the channel name as seen in the URL, not the displayname)
    #discord    - channel (without the #)
    #           - ID:123456789 (where 123456789 is the channel ID)
    #               (https://github.com/42wim/matterbridge/issues/57)
    #telegram   - chatid (a large negative number, eg -123456789)
    #             see (https://www.linkedin.com/pulse/telegram-bots-beginners-marco-frau)
    #hipchat    - id_channel (see https://www.hipchat.com/account/xmpp for the correct channel)
    #rocketchat - #channel (# is required)
    #matrix     - #channel:server (eg #yourchannel:matrix.org)
    #REQUIRED
    channel="#Chat"

        #OPTIONAL - only used for IRC protocol at the moment
        #[gateway.in.options]
        #OPTIONAL - your irc channel key
        #key="yourkey"


    #[[gateway.out]] specifies the account and channels we will sent messages to.
    #[[gateway.out]]
    #Uncomment to allow output to IRC
    #account="mattermost.work"
    #channel="xxxxx-irc"


        #OPTIONAL - only used for IRC protocol at the moment
        #[gateway.out.options]
        #OPTIONAL - your irc channel key
        #key="yourkey"

    #[[gateway.inout]] can be used when then channel will be used to receive from
    #and send messages to
    [[gateway.inout]]
    account="mattermost.work"
    channel="irc"

        #OPTIONAL - only used for IRC protocol at the moment
        #[gateway.inout.options]
        #OPTIONAL - your irc channel key
        #key="yourkey"

    #API example
    #[[gateway.inout]]
    #account="api.local"
    #channel="api"
    #To send data to the api:
    #curl -XPOST -H 'Content-Type: application/json'  -d '{"text":"test","username":"randomuser"}' http://localhost:4242/api/message

#If you want to do a 1:1 mapping between protocols where the channelnames are the same
#e.g. slack and mattermost you can use the samechannelgateway configuration
#the example configuration below send messages from channel testing on mattermost to
#channel testing on slack and vice versa. (and for the channel testing2 and testing3)

#[[samechannelgateway]]
#   enable = false
#   accounts = [ "mattermost.work","slack.hobby" ]
#   channels = [ "testing","testing2","testing3"]
`

**Comment by 42wim** [comment]
As seen in the changelog :)
```
Breaking changes
general: [general] settings don't override the specific bridge settings```
```

You got in your `[general]` `RemoteNickFormat=" <{NICK}> "` and in the `[mattermost.work]` `RemoteNickFormat="{NICK}"`

If you remove the setting in `[mattermost.work]` OR change it to `RemoteNickFormat=" <{NICK}> "` it will work again.

**Comment by alecisec** [comment]
Thank you :)
