### ISSUE TITLE
Incoming webhooks (even diff speakers) are merged on mobile

### ISSUE THREAD

**Issue by myles** [42wim/matterbridge#304]
This might be a slack mobile issue, but curious your thoughts on whether it could possibly be something in the bridge itself. (this is @patcon btw)

<img width="903" alt="napkin 17-11-25 11 00 53 pm" src="https://user-images.githubusercontent.com/1223/33237007-7e4c9514-d234-11e7-8175-154c4b4db945.png">

**Comment by patcon** [comment]
Heard back from SlackHQ, and this is apparently a bug in the ios app that is on their radar :)

Good to close out

**Comment by 42wim** [comment]
Ok, going to close it as I can't fix it :-)
