### ISSUE TITLE
Regression in matterbridge irc nick, doesn't allow "^"

### ISSUE THREAD

**Issue by lassizci** [42wim/matterbridge#305]
If you have a configuration problem, please first try to create a basic configuration following the instructions on [the wiki](https://github.com/42wim/matterbridge/wiki/How-to-create-your-config) before filing an issue.

Please answer the following questions. 

### Which version of matterbridge are you using?
```version: 1.4.1 962062f ```

### Please describe the expected behavior.
matterbridge used to allow e.g `B^` for irc nickname. The previous version I was running, was ```0.13.0 7811c33```

### Please describe the actual behavior. 
```
ERRO[2017-11-29T22:18:09+00:00] error: invalid configuration: bad nickname specified  module=irc
```

Works if I change that to e.g `B_`

### Please add your configuration file 
[irc.qnet]
Server="irc.se.quakenet.org6667"
Nick='B^'
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

**Comment by 42wim** [comment]
Just fixed this in master, you can use the dev binary https://bintray.com/42wim/nightly/Matterbridge/v1.4.1-16-g1d414cf#files"

**Comment by lrstanley** [comment]
https://github.com/lrstanley/girc/commit/373b4f1c01b812a91dd1b055a708fd4704bca0c7 was merged, per @42wim. Thanks!
