### ISSUE TITLE
[Feature Request] REST API long polling

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#307]
the rest api could (and should imo) use long polling

there seems to be a library for it for golang
https://github.com/jcuga/golongpoll

and its README explains best why it is a better approach than spamming the sebserver asking for new events
https://github.com/jcuga/golongpoll#what-is-longpolling

also a little help / guide for implementing a python client that supports longpolling found here
http://blog.fanout.io/2016/11/21/moving-from-polling-to-long-polling/

**Comment by 42wim** [comment]
I've added a simple long-polling solution for your use case, only 1 listener can get the stream at the moment. If there's a use case for multiple listeners I can expand this.

The streaming is available at `/api/stream`
