### ISSUE TITLE
Nordic characters triggers unneeded <message clipped> string with MessageSplit enabled

### ISSUE THREAD

**Issue by Gummikavalier** [42wim/matterbridge#308]
Version: 1.5.0

This is with message splitting enabled.

We send an UTF-8 message with Nordic characters (ä, ö, å) from Rocket.Chat to Ircd.

All long messages that contain Nordic characters get `<message clipped>` that overwrites parts of the message, just before the split. This does not happen with pure ASCII messages.

We have tried to use `Charset="utf-8"` option with Matterbridge, but it seems to have encoding problems too, often replacing ä with ?-character just before the `<message clipped>`. This is a separate issue but is most likely to have something to do with this other problem.

**Comment by 42wim** [comment]
Fixed in master, 1.5.1 release soon

**Comment by Gummikavalier** [comment]
Excellent! Thanks again :)
