### ISSUE TITLE
Feature request: local custome channel support

### ISSUE THREAD

**Issue by wsdjeg** [42wim/matterbridge#309]
I run this tools on a channel, now it bridge many channels ( irc, gitter, tg, etc.) but I want implement a custom channel.

so I hope, when get a message from the gitter,irc,etc. it can send this message to a local socket address, for exmaple `127.0.0.1:8989`,  and when a message set to `127.0.0.1:8989` it can also relay the message to gitter/irc.

**Comment by wsdjeg** [comment]
hmm, I hope we can config it in config file, such as add:

```
[local]
    [local.custom]
    Server="127.0.0.1:8989"
    Nick="SpaceVimBot"
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="mygateway"
enable=true
    [[gateway.inout]]
    account="local.custom"
    channel="127.0.0.1:8989"

```

**Comment by 42wim** [comment]
@wsdjeg you could use the REST API for this

**Comment by wsdjeg** [comment]
I just search REST inrepo， donot see any doc about it。

**Comment by 42wim** [comment]
The documentation is a bit sparse. See for example
https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample#L1134-L1141

**Comment by wsdjeg** [comment]
this can only send data to a url, but Can not read data from it?

**Comment by 42wim** [comment]
```
 #To read from the api:
    #curl http://localhost:4242/api/messages
```

**Comment by wsdjeg** [comment]
@42wim, I know this feature, but I need to read the message, I hope, when get a message , matterbridge can send a message to an address by itself

**Comment by 42wim** [comment]
No that's not possible at the moment.. it can be implemented with websockets though

**Comment by wsdjeg** [comment]
@42wim I have such config in my vps:

```
[api]
    [api.local]
    BindAddress="127.0.0.1:5564"
    Buffer=1000
    RemoteNickFormat="{NICK}: "
```

```
[[gateway]]
name="SpaceVim-cn"
enable=true
    [[gateway.inout]]
    account="gitter.mygitter"
    channel="SpaceVim/cn"

    [[gateway.inout]]
    account="api.local"
    channel="api"
```

when I start matterbridge, I can use `curl -XPOST -H 'Content-Type: application/json'  -d '{"text":"test","username":"randomuser","gateway":"SpaceVim-cn"}' http://localhost:5564/api/message` to send message,

and I have record my domain for example  `fooooo.org` to the ip of this vps, I can not run this command:

```
curl http://fooooo.org:5564/api/messages
```

**Comment by 42wim** [comment]
because the ip of fooooo.org is not `127.0.0.1` as specified in your `BindAddress`
so set `BindAddress=vpsip:5564` and it should work (if you don't have a firewall)

**Comment by wsdjeg** [comment]
Thanks, I will have a try.

**Comment by 42wim** [comment]
@wsdjeg does it work, or do you still have need for a tcp socket?

**Comment by patcon** [comment]
Sorry, you need to set your actual IP (the numbers and dots), not the string @wim42 used as an example. Alternatively, you could use 0.0.0.0:1234 where 1234 is the port you're using. The zero format means that any IP can bind.

**Comment by wsdjeg** [comment]
Thanks, it works for me now.


---

Shidong Wang

-------- 原始邮件 --------
主题：Re: [42wim/matterbridge] Feature request: local custome channel support (#309)
发件人：Patrick Connolly
收件人：42wim/matterbridge
抄送：Wang Shidong ,Mention


Sorry, you need to set your actual IP (the numbers and dots), not the string @Wim42<https://github.com/Wim42> used as an example. Alternatively, you could use 0.0.0.0:1234 where 1234 is the port you're using. The zero format means that any IP can bind.

―

**Comment by patcon** [comment]
Awesome! Glad to hear :)

Any thoughts on how we could improve the documentation or defaults so that the next person to walk your path doesn't have the same issue? Would totally appreciate feedback on that!
