### ISSUE TITLE
*critical* security flaw

### ISSUE THREAD

**Issue by elisaado** [42wim/matterbridge#310]
Hi, I'm using the bridge to bridge Telegram <-> IRC, and I discovered that the bridge sends the Telegram API bot token when it receives media, this is a huge security flaw, because with the token I can do (almost) everything I want with the bot...

For example, when I send a photo in a group the bot is in, it bridges it to IRC, it sends a message like ```<Eli>  https://api.telegram.org/file/bot<token>/photos/file_1.jpg```

it just sent the token.

Suggested fix:
Download the file and put it inside the directory that an (internal) http server serves.

,
Eli

**Comment by 42wim** [comment]
This is happening without specifying `UseInsecureURL` ?
What version of matterbridge ?
https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample#L694-L698

**Comment by elisaado** [comment]
Hi, thanks for replying
(btw, I don't manage the bot)
I assume `UseInsecureURL` was turned on, because it does relay photos and if it's turned off it will not (and now it does), so yeah, I was all hyped up for nothing.

It might be a very good idea to implement my solution (or upload all photos to imgur)

**Comment by 42wim** [comment]
This also already exists, see https://github.com/42wim/matterbridge/wiki/Mediaserver-setup-%5Badvanced%5D

If you want imgur support please open a feature requests issue

**Comment by elisaado** [comment]
I see, thank you very much, I guess we can close this issue.
(also sorry for me not doing any research lol, I was in a rush)
