### ISSUE TITLE
feature request: localpart option for matrix nicks

### ISSUE THREAD

**Issue by techknowlogick** [42wim/matterbridge#311]
matterbridge version: 1.6.0-dev d30ae19

Right now when I bridge matrix with any other service (IRC/XMPP for example), and I use `{NICK}` as the RemoteNickFormat on the side that isn't matrix NICK comes out as `username:matrix.org`. I would like to propose a new option for RemoteNickFormat that is `LOCALPART` which will only send the local part of a matrix username (trim the `:matrix.org` part).

**Comment by 42wim** [comment]
Did you try this option? #160
```
#Whether to send the homeserver suffix. eg ":matrix.org" in @username:matrix.org
#to other bridges, or only send "username".(true only sends username)
#OPTIONAL (default false)
NoHomeServerSuffix=false
```

**Comment by techknowlogick** [comment]
@42wim ah perfect. I didn't see that in the wiki, let me add that now. Thanks :)
