### ISSUE TITLE
Indicate that a message was forwarded from somewhere else in Telegram

### ISSUE THREAD

**Issue by AlohaAloah** [42wim/matterbridge#313]
### Which version of matterbridge are you using?
**Matterbridge v1.5.1**

### Please describe the expected behavior.
**I'm using Discord <--> Telegram bridge only, don't know how this is on other bridges**
To indicate that a message was forwarded (and from whom/where was it forwarded), when a message is forwarded in telegram to the current chat (where the bot is at), could be from another chat or from within itself, a past message for example.

### Please describe the actual behavior. 
It just shows the forwarded message/media as being sent/uploaded by the person who forwarded it.

### Any steps to reproduce the behavior?
**I'm using Discord <--> Telegram bridge only, don't know how this is on other bridges**
1- (In Telegram) Forward any message/media to current chat (where the bot is at).

In Telegram it shows the message, indicating above it that it was "Forwarded from X".
In Discord it shows the message like it was directly sent by the person who forwarded it.

The "[Message](https://core.telegram.org/bots/api#message)" object in Telegram's API allows to get this info.

**Comment by 42wim** [comment]
Should be fixed in master you can download a dev binary from https://bintray.com/42wim/nightly/Matterbridge/v1.5.0-13-gf561632#files
(I don't use telegram so I can't test it)

**Comment by AlohaAloah** [comment]
Forwarding kinda works now...
It just deletes the entire original message in exchange of "Forward from `(TelegramFirstName)` Forwarded from `(TelegramUsername)`"
I think this is due to line 184 (currently 193) in [telegram.go](https://github.com/42wim/matterbridge/commit/e4a0e0a0e950599be49a88ec254b4bfad0779cf4)
`text = "Forward from " + message.ForwardFrom.FirstName`
which is part of the new function
```
if message.ForwardFrom != nil {
			text = "Forward from " + message.ForwardFrom.FirstName
			usernameForward := ""
			if b.Config.UseFirstName {
				usernameForward = message.ForwardFrom.FirstName
			}
			if usernameForward == "" {
				usernameForward = message.ForwardFrom.UserName
				if usernameForward == "" {
					usernameForward = message.ForwardFrom.FirstName
				}
			}
			if usernameForward == "" {
				usernameForward = "unknown"
			}
			text = "Forwarded from " + usernameForward + ": " + text
		}
```
Removing it probably will make it work properly.

**Comment by 42wim** [comment]
You're right, was something I forgot to remove.
About the forwarded files, they don't get forwarded at all or they still show the wrong user ?
I also don't see anything about forwarded files in the telegram API

**Comment by AlohaAloah** [comment]
After enabling debug, I can see that the Forwarded text is fine in the files and it's sending it fine as well.
So I think the issue is with Discord, I think it doesn't allow text to be attached with a file or something like that, at least not in the normal way?

So yeah, I think it works fine, the problem is in Discord.
The one thing that comes to my mind for this to work, is to change the text of the username rather than the text of the message but I don't think it's worth it or that it makes much sense.
