### ISSUE TITLE
Telegram Audio Files/Voice Notes not relaying to Discord

### ISSUE THREAD

**Issue by AlohaAloah** [42wim/matterbridge#314]
### Which version of matterbridge are you using?
**Matterbridge v1.5.1**

### Please describe the expected behavior.
**I'm using Discord <--> Telegram bridge only, don't know how this is on other bridges**
When an [Audio](https://core.telegram.org/bots/api#audio) or a [Voice](https://core.telegram.org/bots/api#voice) file is sent in telegram, it should show up as a file available to download in Discord with proper extension.

### Please describe the actual behavior. 
When these types of files are sent in Telegram, nothing appears on the Discord side

### Any steps to reproduce the behavior?
**I'm using Discord <--> Telegram bridge only, don't know how this is on other bridges**
1- (In Telegram) Upload/Record any file of the type mentioned to current chat (where the bot is at).

In Telegram the file uploads fine and can be played/downloaded.
In Discord nothing shows up.

Voice Notes should always have .ogg extension I think
I see that both objects are missing from the functions "handleRecv" and "handleDownload" in matterbridge/bridge/telegram/[telegram.go](https://github.com/42wim/matterbridge/blob/master/bridge/telegram/telegram.go)

**Comment by 42wim** [comment]
Should be fixed in master you can download a dev binary from https://bintray.com/42wim/nightly/Matterbridge/v1.5.0-13-gf561632#files
(I don't use telegram so I can't test it)

**Comment by AlohaAloah** [comment]
They work now.
However there seem to be issues with the Audio files, they tend to be incomplete for some reason when they reach Discord, not sure why that is.
No problems with Voice files though!

**Comment by 42wim** [comment]
incomplete as in they don't work at all or they stop playing after x seconds ?
could you run with `-debug` ?
You should see messages like `download OK name number number`, the 2nd number should be equal to the filesize of the original file

**Comment by AlohaAloah** [comment]
They work, but the file size is lower and the file length is shorter or sometimes it has the correct file length but stops midway.
Seems to be pretty inconsistent.
Of course, I'm using a file that's less than 1MB in size because of the size limitation that is set on `handleDownload`

Well... now it works fine... that's odd, it used to have inconsistent file sizes and lengths for the same file every time I tried to upload it, but it works now...
I'm going to assume it had something to do with my internet connection or something with the telegram/discord servers? I don't know.

Would be interesting to see what happens if we could raise that 1MB limit up to the 8MB that Discords allows for free users.
The thing is that this only happened with audio.

I don't have the debug logs when I had the issue, so I know this is completely unreliable but:
If I recall correctly, the debug log said something on the lines of:

```
trying to download "file_000.mp3" fileid "LetTErs4ndNumb3r5" with size 123456
download OK "file_000.mp3" 123000 <- This number would be lower than the original above.
Sending message from User etc.etc.etc.
Message is config.Message etc.etc.etc.
Receiving config.Message etc.etc.etc.
Broadcasting using token (API)
file upload failed: and maybe an error code?
```

And even though it said that the file upload failed, in the Discord chat, an audio file would appear.
This file worked fine but it was shorter (incomplete) and had a lower file size.

I think that was how it worked, maybe sometimes it wouldn't display the `file upload failed` message.
Don't have how to prove it now though.
Audio files are generally over 1MB in size so they just don't relay to Discord anyways.
Kinda awkward that it's working now though.

Thanks anyway! Awesome job with this bridge btw. It's great!

**Comment by 42wim** [comment]
Thanks for the reply :)
I'm going to make the downloadsize a configuration parameter, so you can choose your own size.
I'll ping on this issue again so you can test it out

**Comment by AlohaAloah** [comment]
Fantastic, thanks!

**Comment by 42wim** [comment]
@AlohaAloah 

I added support for specifying the size

Has to be specified under `[general]`
```
#MediaDownloadSize is the maximum size of attachments, videos, images
#matterbridge will download and upload this file to bridges that also support uploading files.
#eg downloading from slack to upload it to mattermost
#
#It will only download from bridges that don't have public links available, which are for the moment
#slack, telegram and matrix
#Optional (default 1000000 (1 megabyte))
MediaDownloadSize=1000000
```

Dev binary available on https://bintray.com/42wim/nightly/Matterbridge/v1.5.0-17-gd0c4fe7#files
