### ISSUE TITLE
{NICK} formatted in HTML in Telegram goes back to normal formatting after an Edit in Discord

### ISSUE THREAD

**Issue by AlohaAloah** [42wim/matterbridge#315]
### Which version of matterbridge are you using?
**Matterbridge v1.5.1**

### Please describe the expected behavior.
**I'm using Discord <--> Telegram bridge only, don't know how this is on other bridges**
After editing a message in Discord it should edit normally in Telegram without screwing the formatting of the Nicknames.
It should look like this after editing:
![image](https://user-images.githubusercontent.com/34383788/33789160-1b7380a6-dc4d-11e7-82b1-1a877e7aab36.png)

### Please describe the actual behavior. 
When a message is edited in Discord, the same message is edited in Telegram, this works fine.
But in my configuration file, I have:
(For Telegram)
`MessageFormat="HTML"`
and
`RemoteNickFormat="<b>{NICK}:</b>\n"`
So a sent message looks like this:
![image](https://user-images.githubusercontent.com/34383788/33789133-f171284e-dc4c-11e7-9acf-0c2bb9d368d8.png)
However, after editing, it looks like this:
![image](https://user-images.githubusercontent.com/34383788/33789146-06a430a8-dc4d-11e7-99e9-cb642bd29933.png)

### Any steps to reproduce the behavior?
1- Add `MessageFormat="HTML"` to a Telegram protocol in the config file
2- In `RemoteNickFormat=` make use of HTML formatting
3- Run (Discord connected to Telegram)
4- Send a message in Discord (Check if it appeared on Telegram)
5- Edit that message in Discord (It should be edited on Telegram with the now non-HTML formatted nickname)

### Please add your configuration file 
```
###################################################################
#discord section
###################################################################
[discord]

[discord.server1]
Token="D_TOKEN1"
Server="Server1Name"
RemoteNickFormat="**{NICK}:** "
ShowEmbeds=true

[discord.server2]
Token="D_TOKEN2"
Server="Server2Name"
RemoteNickFormat="**{NICK}:** "
ShowEmbeds=true

###################################################################
#telegram section
###################################################################
[telegram]

[telegram.group1]
Token="T_TOKEN1"
MessageFormat="HTML"
RemoteNickFormat="<b>{NICK}:</b>\n"
UseFirstName=false

[telegram.group2]
Token="T_TOKEN2"
MessageFormat="HTML"
RemoteNickFormat="<b>{NICK}:</b>\n"
UseFirstName=false

###################################################################
#Gateway configuration
###################################################################

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="discord.server1"
channel="channel"

[[gateway.inout]]
account="telegram.group1"
channel="-123456789"

[[gateway]]
name="gateway2"
enable=true

[[gateway.inout]]
account="discord.server2"
channel="channel"

[[gateway.inout]]
account="telegram.group2"
channel="-123456789"

```

**Comment by AlohaAloah** [comment]
So, this also happens with normal messages that use HTML formatting as well.
If I send this message from discord: `<b> HTML Formatting test </b>`
It shows up like:
![image](https://user-images.githubusercontent.com/34383788/33793899-553f31a0-dc97-11e7-9de5-7371cc3e0c6e.png)
As it should.

But then, after I edit it:
![image](https://user-images.githubusercontent.com/34383788/33793905-794271c0-dc97-11e7-90e6-ce6ee8cffdc4.png)
It shows up like that.

**Comment by 42wim** [comment]
Should be fixed in master you can download a dev binary from https://bintray.com/42wim/nightly/Matterbridge/v1.5.0-13-gf561632#files
(I don't use telegram so I can't test it)

**Comment by AlohaAloah** [comment]
It works now! Great
