### ISSUE TITLE
Feature Request : add public attachment link in IRC message

### ISSUE THREAD

**Issue by varod** [42wim/matterbridge#32]
When you enter a message in mattermost side you can attach picture or things like that.
Today the message sent to IRC doesn't mention this attachment. 
In mattermost (3.3) there is an option to create a public link (quite verbose). 
This link should be attached to the message sent to IRC.
Maybe this feature has to be a setting that can be activated on demand.

What do you think about it ?

**Comment by 42wim** [comment]
Yes, it's on the todo, matterircd already does this.

**Comment by varod** [comment]
it has worked with mattermost 3.4 and matterbridge 0.7 but now it doesn't work with mattermost 3.5 and matterbridge 0.8.1

**Comment by varod** [comment]
i don't understand why i can't reopen issue :-/

**Comment by 42wim** [comment]
Also because of API changes, fixed in master now. I'm not going to fix it in 0.8 anymore. 
Planning on releasing 0.9.0 soon
