### ISSUE TITLE
MatterBridge 'Bot Probably Should Use Message-Type m.notice on Matrix

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [42wim/matterbridge#321]
IIRC for IRC, 'bots are recommended to use `/NOTICE <#channel> <message>` or `/NOTICE <nick'1 nick2…> <message>` by mIRC doc's and maybe RFCs.  I'll try and dig later.  But now, I'll just quote the Matrix spec' `¶`«Make m.notice description a bit harder in its phrasing to try to dissuade the same issues that occurred with IRC [Make m.notice description use stricter language - 750](https://github.com/matrix-org/matrix-doc/pull/750)» •&• `¶`«The m.notice type is primarily intended for responses from automated clients. An m.notice message must be treated the same way as a regular m.text message with two exceptions. Firstly, clients should present m.notice messages to users in a distinct manner, and secondly, m.notice messages must never be automatically responded to. This helps to prevent infinite-loop situations where two automated clients continuously exchange messages.»  [https://matrix.org/docs/spec/client_server/latest.html#m-notice](https://matrix.org/docs/spec/client_server/latest.html#m-notice)

**Comment by 42wim** [comment]
As said on irc, it's better to keep m.text instead of m.notice
