### ISSUE TITLE
Option to stay kicked for timeout from IRC?

### ISSUE THREAD

**Issue by oxinabox** [42wim/matterbridge#322]
Before I get in to this, I love this project. This is so great.
Very useful.

This is an enhancement request:

Our IRC channels tend to get more automated spam than other channels, because no registration required (and we like it that way, low bar to entry).
Often it can be hard to block the spammers, because it is some bot (/botnet) changing its username and IP and rejoining.
Ultimately keeping them out of IRC is beyond the scope for matter-bridge.
What I would like, would be a way to keep them from contaminating them other linked channels.

Looking at my logs I see the IRC admins have tried to kick the matterbidge bot from the channel.
Presumably because they have decided that stopping the spam from hitting the bridged channels is worth the cost of loosing connectivity.
That is their call.
I see it hasn't worked as the matterbridge bot has immediately reconnected.
They should have kick-banned.

What if, there was a config option, that said that If the bot is kicked from IRC, it says kicked for a certain amount of time? Configurable, probably default to 0 -- being the the current behavior.
Most spam lasts less than 5 minutes.

**Comment by 42wim** [comment]
Thanks, nice to hear it's useful :-)

Feature has been added to master, add the following to your `irc` section
```
#Delay in seconds to rejoin a channel when kicked
#OPTIONAL (default 0)
RejoinDelay=0
```
You can find dev binaries on https://bintray.com/42wim/nightly/Matterbridge/v1.5.0-18-g97c944b#files
