### ISSUE TITLE
Display of nicks not longer working

### ISSUE THREAD

**Issue by TomTheDragon** [42wim/matterbridge#323]
### Which version of matterbridge are you using?
1.6.0-dev

### Please describe the actual behavior. 
There are no nick names displayed in front of the posts.

### Any steps to reproduce the behavior?
Use any source after https://github.com/42wim/matterbridge/tree/4a4a29c9f6fe202cf4379c0df2ba313848bb8d11

**Comment by 42wim** [comment]
Thanks for reporting!
Didn't trigger on my test, because I had RemoteNickFormat defined in `[general]` 
Released as 1.6.1
