### ISSUE TITLE
Sync  Message Deletion between Slack and Gitter

### ISSUE THREAD

**Issue by oxinabox** [42wim/matterbridge#324]
When a moderator on gitter deletes a message (e.g because it is spam),
the relayed message should also be deleted on Slack 
(and other channels where possible, but gitter <-> slack is my current concern).

@ChrisRackauckas has been valiantly fighting recent spam floods with deletes,
but it is best if he doesn't have to go and do it for every channel that is bridged.

**Comment by 42wim** [comment]
Unfortunately this isn't something I can't fix.
Just added it to the FAQ, https://github.com/42wim/matterbridge/wiki/FAQ

> Gitter doesn't send delete events to their API, so we can pick those up.   
> When you delete a message on another bridge slack, they will be deleted on gitter though. (matterbridge can delete messages on gitter, but we do not get an event when a message on gitter is deleted)
> 
> So slack <=> gitter bridge, deleting messages when on gitter doesn't get deleted on slack.   
> On the same bridge, deleting messages on slack gets also deleted on gitter.

**Comment by oxinabox** [comment]
Thanks
