### ISSUE TITLE
Supporting Raspberry PI for Dockerfile ?

### ISSUE THREAD

**Issue by fflorent** [42wim/matterbridge#328]
Hi there!

In order to run on Raspberry PI (v2 for me, but maybe v3 also?), I need to make this slight change in the Dockerfile : 
```diff
diff --git a/Dockerfile b/Dockerfile
index bcf173b..002b2fe 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,5 @@
-FROM alpine:edge
+FROM easypi/alpine-arm:edge
 ENTRYPOINT ["/bin/matterbridge"]
 
 COPY . /go/src/github.com/42wim/matterbridge
```

Of course, if anything has to be made on this repo, it would consist in committing another Dockerfile, and pushing a new Docker image.

I don't know what you would prefer: create a new Dockerfile in your repo or just let others (like me) fork your repo to support this platform and push their images to Docker Hub?

Cheers,
Florent

**Comment by 42wim** [comment]
I'm trying to build in on dockerhub, but it seems like it can't be build there ?
https://hub.docker.com/r/42wim/matterbridge/builds/bmndifzl8ckfa8wrkzzg7w7/

Do you have any experience with dockerhub and arm ?

**Comment by fflorent** [comment]
Arf, sounds like only x64 architecture is supported on docker hub automatic build:
 - https://github.com/jwilder/nginx-proxy/issues/315
 - https://github.com/docker/hub-feedback/issues/427

I would be happy to provide the Docker image, I don't know how can I be transparent and let the people be sure that my image doesn't contain more than what the Dockerfile contains.

Florent

**Comment by 42wim** [comment]
https://github.com/cmosh/alpine-arm looks interesting to use for building arm on dockerhub.
If you could get that to work, a PR would be nice :-)

**Comment by fflorent** [comment]
It works like a charm! Should I create a separate dockerfile for this?

**Comment by 42wim** [comment]
Could you make PR against https://github.com/42wim/matterbridge/blob/master/docker/arm/Dockerfile ?
Thanks!

**Comment by fflorent** [comment]
Done! #347

**Comment by 42wim** [comment]
@fflorent It doesn't seem to work though https://hub.docker.com/r/42wim/matterbridge/builds/bthaxctl98zezk38eiz2gjx/ any ideas ?

**Comment by fflorent** [comment]
Well, sorry no idea yet, working on it…

**Comment by 42wim** [comment]
No worries, thanks for your time!

**Comment by lil5** [comment]
```
FROM cmosh/alpine-arm:edge
#FROM alpine:latest
ENTRYPOINT ["/bin/matterbridge"]

RUN apk update && apk add go git gcc musl-dev ca-certificates \
        && mkdir -p /go/src/github.com/42wim/matterbridge \
        && cd /go/src/github.com/42wim/matterbridge \
        && git clone -q -b v1.11.0 --depth=1 https://github.com/42wim/matterbridge.git . \
        && export GOPATH=/go \
        && go get \
        && go build -x -ldflags "-X main.githash=$(git log --pretty=format:'%h' -n 1)" -o /bin/matterbridge \
        && rm -rf /go \
&& apk del --purge git go gcc musl-dev
```
Dockerfile


```
version: '3'

services:
  matterbridge:
    build: ./
    restart: unless-stopped
    volumes:
      - ./matterbridge.toml:/matterbridge.toml
```
docker-compose.yml


This should work will test tomorrow...

**Comment by 42wim** [comment]
Still fails on dockerhub https://hub.docker.com/r/42wim/matterbridge/builds/bpgy629gyhkjdprvwpnybek/

**Comment by lil5** [comment]
> ...ge && rm -rf /go && apk del --purge git go gcc musl-dev' returned a non-zero code: 1 

This could be the `rm -rf` trying to remove `/go/.` And `/go/..` and failing

A hacky `... && rm -rf ... ||: && ...` will work

**Comment by 42wim** [comment]
@lil5 no, that's not the reason, look below in the dockerhub url

```
[91mstandard_init_linux.go:190: exec user process caused "exec format error"
```

**Comment by GrimKriegor** [comment]
Hello everyone.

What's the status on the arm32 image?

Recently tried running it on my arm32v7 cluster and couldn't get it scheduled.

```
"no suitable node (unsupported platform on 4 nodes)"
```

Seems to be a common issue nowadays on 'cross-compiled' images as they report their host architecture on their manifest.

```
[
    {
        "Id": "sha256:bd5a75afd94308bffdc7792bcd7406584bacd41a80ba8eeb440763ec76794787",
        "RepoTags": [
            "42wim/matterbridge:arm32v6-1.12.3"
(...)
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 18861814,
        "VirtualSize": 18861814,
        "GraphDriver": {
            "Data": {
(...)
```

Disabling the querying of supported platforms when deploying with:

```
--resolve-image never
```

allowed it to be scheduled, but I am still getting this, on both `stack deploy` and simple `run`.

```
"starting container failed: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/bin/matterbridge\": permission denied": unknown"
```

Strangely, trying to get a shell on the container has been tricky, as it says `file not found` every time I try to exec a core util, or a shell.

Are the manifest arch and the permission denied issues known? Is someone looking into them currently?

Also, if you allow me, why the choice of a third party base image `cmosh/alpine-arm` instead of an official and well maintained `arm32v6/alpine` or even `arm32v6/golang:1.9-alpine` for instance?

Thank you for your time and effort.

**Comment by fflorent** [comment]
Sorry, I don't use a Raspberry Pi or a server with an ARM CPU anymore.

You may need to build the image on your own on RPI.

> Also, if you allow me, why the choice of a third party base image cmosh/alpine-arm instead of an official and well maintained arm32v6/alpine or even arm32v6/golang:1.9-alpine for instance?

Because you cannot build `arm32v6/alpine` image on Dockerhub. `cmosh/alpine-arm` promised to bypass this.

Florent

**Comment by 42wim** [comment]
@GrimKriegor  Haven't got the build working yet, no time at the moment to work on this.  I'll delete those builds from dockerhub so it doesn't any more confusion.

If anyone gets this working let me know :-)

**Comment by GrimKriegor** [comment]
Thanks for the clarification guys.

I wonder if things have changed, with this push to multi-arch images and the like.

Will investigate and report back.

**Comment by 42wim** [comment]
Going to close this, dockerhub still doesn't support this natively and doesn't seem to be planning it.
