### ISSUE TITLE
IRC colors makes message malformated

### ISSUE THREAD

**Issue by varod** [42wim/matterbridge#33]
In IRC protocol it is possible to specify color : http://www.mirc.com/colors.html
When a message is sent with this kind of command in IRC side. In mattermost side it wrotes the digit code.
For exemple : 
if in IRC i sent  `^C03Hello` it writes Hello in green ; I use `CTRL + K` in order to have the good special char.
in Mattermost it wrotes : `valvin : 03Hello` instead of `valvin: Hello`

I think it can be handled by removing digits after this special char. There are two formats `^Cxx` (foreground) and `^Cxx,yy` (foreground and background)

**Comment by varod** [comment]
Am I right this such feature can be implement in : `bridge.go` ?

```
func (b *Bridge) modifyMessage(msg *config.Message, dest string) {
	switch dest {
	case "irc":
		setNickFormat(msg, b.Config.IRC.RemoteNickFormat)
	case "gitter":
		setNickFormat(msg, b.Config.Gitter.RemoteNickFormat)
	case "xmpp":
		setNickFormat(msg, b.Config.Xmpp.RemoteNickFormat)
	case "mattermost":
		setNickFormat(msg, b.Config.Mattermost.RemoteNickFormat)
                **removeIRCSpecialCommands(msg)**
	case "slack":
		setNickFormat(msg, b.Config.Slack.RemoteNickFormat)
	}
}
```

**Comment by 42wim** [comment]
Yes, it would be implemented there, ```sanitizeMessage``` or something like that but for all destinations, not only mattermost. Not 100% sure yet if we should modify the content of the message though.

**Comment by varod** [comment]
Hi @42wim 
Thanks for this implementation. I am wondering if your regex is complete : 
`[[:cntrl:]]\d+,\d`

it should have also `[[:cntrl:]]\d+`

so maybe this regex is better : `[[:cntrl:]]\d+,\d|[[:cntrl:]]\d+` ?

**Comment by 42wim** [comment]
@varod: thanks, I changed it to ```[[:cntrl:]](\d+,|)\d+``` should be good enough?
