### ISSUE TITLE
Slack server error: 429 Too Many Requests

### ISSUE THREAD

**Issue by Jookly** [42wim/matterbridge#332]
If you have a configuration problem, please first try to create a basic configuration following the instructions on [the wiki](https://github.com/42wim/matterbridge/wiki/How-to-create-your-config) before filing an issue.

Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```

version: 1.7.0-dev

### Please describe the expected behavior.
Expected behavior is stable connection to slack.  It seemed to be working for the first 24 hrs or so.

### Please describe the actual behavior. 
I recieve an error infinitely.  The error is: "ERRO[2018-01-08T21:04:04Z] Connection failed "post: Slack server error: 429 Too Many Requests." &errors.errorString{s:"post: Slack server error: 429 Too Many Requests."}  module=slack"

#### Use logs from running ```matterbridge -debug``` if possible.

INFO[2018-01-08T21:04:01Z] Enabling debug
INFO[2018-01-08T21:04:01Z] Running version 1.7.0-dev
INFO[2018-01-08T21:04:01Z] WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
INFO[2018-01-08T21:04:01Z] Starting bridge: discord.mydiscord
INFO[2018-01-08T21:04:01Z] Connecting                                    module=discord
INFO[2018-01-08T21:04:01Z] Connecting using token                        module=discord
INFO[2018-01-08T21:04:01Z] Connection succeeded                          module=discord
INFO[2018-01-08T21:04:01Z] discord.mydiscord: joining crypto-general (crypto-generaldiscord.mydiscord)
INFO[2018-01-08T21:04:01Z] Starting bridge: slack.myslack
INFO[2018-01-08T21:04:01Z] Connecting using token (sending and receiving)  module=slack
INFO[2018-01-08T21:04:01Z] slack.myslack: joining general (generalslack.myslack)
DEBU[2018-01-08T21:04:01Z] Choosing token based receiving                module=slack
DEBU[2018-01-08T21:04:01Z] Receiving from slackclient &slack.ConnectingEvent{Attempt:1, ConnectionCount:1}  module=slack
DEBU[2018-01-08T21:04:02Z] Receiving from slackclient &slack.ConnectionErrorEvent{Attempt:0, ErrorObj:(*errors.errorString)(0xc420465e50)}  module=slack
ERRO[2018-01-08T21:04:02Z] Connection failed "post: Slack server error: 429 Too Many Requests." &errors.errorString{s:"post: Slack server error: 429 Too Many Requests."}  module=slack

### Any steps to reproduce the behavior?
I'm not certain what changed in the 24 hrs i was using the relay.  I am hoping someone can shed some light on what I might be missing.

### Please add your configuration file 

[discord.mydiscord]
#You can get your token by following the instructions on
#https://github.com/42wim/matterbridge/wiki/Discord-bot-setup
#If you want roles/groups mentions to be shown with names instead of ID,
#you'll need to give your bot the "Manage Roles" permission.
Token=""
Server=""
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
ShowEmbeds=true

[slack.myslack]
#Token to connect with the Slack API
#You'll have to use a test/api-token using a dedicated user and not a bot token.
#See https://github.com/42wim/matterbridge/wiki/Slack-bot-setup for more information
Token=""
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel=""

[[gateway.inout]]
account="slack.myslack"
channel="general"

**Comment by 42wim** [comment]
Could you try a dev build on https://bintray.com/42wim/nightly/Matterbridge/v1.6.0-14-g9f15d38#files ? 
According to a person on the chat it's fixed in that build.
(Seems to happen to random people/connections, I can't reproduce it myself.)

**Comment by Jookly** [comment]
thank you! This seems to be working again.  I truly appreciate your help and this is a really great project.  I just found it the other day and it is just what i needed.  Thanks again.
