### ISSUE TITLE
Telegram relay issue.  strconv.ParseInt: parsing "": invalid syntax

### ISSUE THREAD

**Issue by Jookly** [42wim/matterbridge#334]
If you have a configuration problem, please first try to create a basic configuration following the instructions on [the wiki](https://github.com/42wim/matterbridge/wiki/How-to-create-your-config) before filing an issue.

Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
version: 1.7.0-dev

### Please describe the expected behavior.

Expecting inout relay of telegram messages

#### Use logs from running ```matterbridge -debug``` if possible.

Note: Relay appears to be connected and I believe the bot is out of "privacy mode" on telegram. 

When a message comes in from a bridge to be sent to telegram I get the following output in the console but no message appears in telegram:

DEBU[2018-01-09T21:37:46Z] Sending config.Message{Text:"sometext", Channel:"channel", Username:"Jookly", UserID:"398691266185003019", Avatar:"https://cdn.discordapp.com/avatars/398691266185003019/.jpg", Account:"discord.mydiscord", Event:"", Protocol:"", Gateway:"gateway1", Timestamp:time.Time{wall:0xbe8d6b6a44555527, ext:1323829207406, loc:(*time.Location)(0x14977c0)}, ID:"400402792843313152", Extra:map[string][]interface {}(nil)} from discord.mydiscord (channel) to telegram.mytelegram ()
DEBU[2018-01-09T21:37:46Z] Receiving config.Message{Text:"sometext", Channel:"channel", Username:"[discord] <Jookly> ", UserID:"398691266185003019", Avatar:"https://cdn.discordapp.com/avatars/398691266185003019/.jpg", Account:"discord.mydiscord", Event:"", Protocol:"", Gateway:"gateway1", Timestamp:time.Time{wall:0xbe8d6b6a44555527, ext:1323829207406, loc:(*time.Location)(0x14977c0)}, ID:"", Extra:map[string][]interface {}(nil)}  module=telegram
strconv.ParseInt: parsing "": invalid syntax

when a message is sent from telegram bridge i see the following in the console but the message is never sent to the other bridges

DEBU[2018-01-09T21:13:31Z] Receiving from telegram: &tgbotapi.Message{MessageID:7, From:(*tgbotapi.User)(0xc42049ce10), Date:1515532411, Chat:(*tgbotapi.Chat)(0xc42012b0e0), ForwardFrom:(*tgbotapi.User)(nil), ForwardFromChat:(*tgbotapi.Chat)(nil), ForwardFromMessageID:0, ForwardDate:0, ReplyToMessage:(*tgbotapi.Message)(nil), EditDate:0, Text:"fads", Entities:(*[]tgbotapi.MessageEntity)(nil), Audio:(*tgbotapi.Audio)(nil), Document:(*tgbotapi.Document)(nil), Game:(*tgbotapi.Game)(nil), Photo:(*[]tgbotapi.PhotoSize)(nil), Sticker:(*tgbotapi.Sticker)(nil), Video:(*tgbotapi.Video)(nil), VideoNote:(*tgbotapi.VideoNote)(nil), Voice:(*tgbotapi.Voice)(nil), Caption:"", Contact:(*tgbotapi.Contact)(nil), Location:(*tgbotapi.Location)(nil), Venue:(*tgbotapi.Venue)(nil), NewChatMembers:(*[]tgbotapi.User)(nil), LeftChatMember:(*tgbotapi.User)(nil), NewChatTitle:"", NewChatPhoto:(*[]tgbotapi.PhotoSize)(nil), DeleteChatPhoto:false, GroupChatCreated:false, SuperGroupChatCreated:false, ChannelChatCreated:false, MigrateToChatID:0, MigrateFromChatID:0, PinnedMessage:(*tgbotapi.Message)(nil), Invoice:(*tgbotapi.Invoice)(nil), SuccessfulPayment:(*tgbotapi.SuccessfulPayment)(nil)}  module=telegram
DEBU[2018-01-09T21:13:31Z] Sending message from user on telegram.mytelegram to gateway  module=telegram
DEBU[2018-01-09T21:13:31Z] Message is config.Message{Text:"fads", Channel:"-221704010", Username:"user", UserID:"498945839", Avatar:"", Account:"telegram.mytelegram", Event:"", Protocol:"", Gateway:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"7", Extra:map[string][]interface {}{}}  module=telegram
DEBU[2018-01-09T21:13:32Z] Receiving from telegram: &tgbotapi.Message{MessageID:8, From:(*tgbotapi.User)(0xc42049cf50), Date:1515532411, Chat:(*tgbotapi.Chat)(0xc42012b5f0), ForwardFrom:(*tgbotapi.User)(nil), ForwardFromChat:(*tgbotapi.Chat)(nil), ForwardFromMessageID:0, ForwardDate:0, ReplyToMessage:(*tgbotapi.Message)(nil), EditDate:0, Text:"fasd", Entities:(*[]tgbotapi.MessageEntity)(nil), Audio:(*tgbotapi.Audio)(nil), Document:(*tgbotapi.Document)(nil), Game:(*tgbotapi.Game)(nil), Photo:(*[]tgbotapi.PhotoSize)(nil), Sticker:(*tgbotapi.Sticker)(nil), Video:(*tgbotapi.Video)(nil), VideoNote:(*tgbotapi.VideoNote)(nil), Voice:(*tgbotapi.Voice)(nil), Caption:"", Contact:(*tgbotapi.Contact)(nil), Location:(*tgbotapi.Location)(nil), Venue:(*tgbotapi.Venue)(nil), NewChatMembers:(*[]tgbotapi.User)(nil), LeftChatMember:(*tgbotapi.User)(nil), NewChatTitle:"", NewChatPhoto:(*[]tgbotapi.PhotoSize)(nil), DeleteChatPhoto:false, GroupChatCreated:false, SuperGroupChatCreated:false, ChannelChatCreated:false, MigrateToChatID:0, MigrateFromChatID:0, PinnedMessage:(*tgbotapi.Message)(nil), Invoice:(*tgbotapi.Invoice)(nil), SuccessfulPayment:(*tgbotapi.SuccessfulPayment)(nil)}  module=telegram
DEBU[2018-01-09T21:13:32Z] Sending message from user on telegram.mytelegram to gateway  module=telegram
DEBU[2018-01-09T21:13:32Z] Message is config.Message{Text:"fasd", Channel:"-221704010", Username:"user", UserID:"498945839", Avatar:"", Account:"telegram.mytelegram", Event:"", Protocol:"", Gateway:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"8", Extra:map[string][]interface {}{}}  module=telegram
DEBU[2018-01-09T21:13:33Z] Receiving from telegram: &tgbotapi.Message{MessageID:9, From:(*tgbotapi.User)(0xc42049d090), Date:1515532412, Chat:(*tgbotapi.Chat)(0xc42012be60), ForwardFrom:(*tgbotapi.User)(nil), ForwardFromChat:(*tgbotapi.Chat)(nil), ForwardFromMessageID:0, ForwardDate:0, ReplyToMessage:(*tgbotapi.Message)(nil), EditDate:0, Text:"asfafdas", Entities:(*[]tgbotapi.MessageEntity)(nil), Audio:(*tgbotapi.Audio)(nil), Document:(*tgbotapi.Document)(nil), Game:(*tgbotapi.Game)(nil), Photo:(*[]tgbotapi.PhotoSize)(nil), Sticker:(*tgbotapi.Sticker)(nil), Video:(*tgbotapi.Video)(nil), VideoNote:(*tgbotapi.VideoNote)(nil), Voice:(*tgbotapi.Voice)(nil), Caption:"", Contact:(*tgbotapi.Contact)(nil), Location:(*tgbotapi.Location)(nil), Venue:(*tgbotapi.Venue)(nil), NewChatMembers:(*[]tgbotapi.User)(nil), LeftChatMember:(*tgbotapi.User)(nil), NewChatTitle:"", NewChatPhoto:(*[]tgbotapi.PhotoSize)(nil), DeleteChatPhoto:false, GroupChatCreated:false, SuperGroupChatCreated:false, ChannelChatCreated:false, MigrateToChatID:0, MigrateFromChatID:0, PinnedMessage:(*tgbotapi.Message)(nil), Invoice:(*tgbotapi.Invoice)(nil), SuccessfulPayment:(*tgbotapi.SuccessfulPayment)(nil)}  module=telegram
DEBU[2018-01-09T21:13:33Z] Sending message from user on telegram.mytelegram to gateway  module=telegram
DEBU[2018-01-09T21:13:33Z] Message is config.Message{Text:"asfafdas", Channel:"-221704010", Username:"user", UserID:"498945839", Avatar:"", Account:"telegram.mytelegram", Event:"", Protocol:"", Gateway:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"9", Extra:map[string][]interface {}{}}  module=telegram

### Any steps to reproduce the behavior?
I am not sure.  If my configuration looks good to you I will assume I have something incorrect on the telegram side.  Im apologize for bothering you two days in a row.

#### (be sure to exclude or anonymize private data (tokens/passwords))

[discord.mydiscord]
#You can get your token by following the instructions on
#https://github.com/42wim/matterbridge/wiki/Discord-bot-setup
#If you want roles/groups mentions to be shown with names instead of ID,
#you'll need to give your bot the "Manage Roles" permission.
Token=""
Server=""
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
ShowEmbeds=true

[slack.myslack]
#Token to connect with the Slack API
#You'll have to use a test/api-token using a dedicated user and not a bot token.
#See https://github.com/42wim/matterbridge/wiki/Slack-bot-setup for more information
Token=""
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[irc.myirc]
Server="irc.freenode.net:8000"
UseSASL=true
Nick=""
#OPTIONAL
NickServNick=""
NickServPassword=""
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[matrix.mymatrix]
#Server is your homeserver (eg https://matrix.org)
Server="https://matrix.org"

#login/pass of your bot.
#Use a dedicated user for this and not your own!
#Messages sent from this user will not be relayed to avoid loops.
Login=""
Password=""

RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

#Whether to send the homeserver suffix. eg ":matrix.org" in @username:matrix.org
#to other bridges, or only send "username".(true only sends username)
#OPTIONAL (default false)
NoHomeServerSuffix=false

[telegram.mytelegram]
#See https://core.telegram.org/bots#6-botfather
#and https://www.linkedin.com/pulse/telegram-bots-beginners-marco-frau
Token=""
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="gateway1"
enable=true

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="general"

[[gateway.inout]]
account="slack.myslack"
channel="general"

[[gateway.inout]]
account="matrix.mymatrix"
channel="#channel:matrix.org"

[[gateway.inout]]
account="irc.myirc"
channel="#channel"

[[gateway.inout]]
account="telegram.mytelegram"
chatid="-1217xxxxx"

**Comment by 42wim** [comment]
The ```chatid="-1217xxxx"``` doesn't match your actual channel ```-22170410```
(as seen in your debug message)
```DEBU[2018-01-09T21:13:32Z] Message is config.Message{Text:"fasd", Channel:"-221704010",  ..```

**Comment by Jookly** [comment]
thank you for the quick reply.  Thats because i failed at obfuscating my data in both spots however I dont think its causing the problem.

**Comment by 42wim** [comment]
Ok, in your config file you have 2 times 

```
[[gateway]]
name="gateway1"
enable=true
```
Remove the first one

**Comment by Jookly** [comment]
Thank you again for your quick reply and suggestion.  I still experience the same behavior with the single gateway.

**Comment by 42wim** [comment]
```
[[gateway.inout]]
account="telegram.mytelegram"
chatid="-1217xxxxx"
```
must be

```
[[gateway.inout]]
account="telegram.mytelegram"
channel="-1217xxxxx"
```

so channel instead of chatid

**Comment by Jookly** [comment]
ah you nailed it.  Im embarrassed I didn't think of trying that.  I straight up misinterpreted the directions.  Thank you so much.  I will be sending a bitcoin tip for your help the last two days :)

**Comment by 42wim** [comment]
You're welcome and thanks :-)
