### ISSUE TITLE
`RemoteNickFormat` per gateway

### ISSUE THREAD

**Issue by heinrich5991** [42wim/matterbridge#337]
It would be nice if it were possible to create a custom `RemoteNickFormat` per gateway.

My use case is that we have mainly have an IRC channel on Quakenet and a Discord server that should be linked together, but there's also a pretty empty IRC channel on Freenode. It would be nice if Quakenet ↔ Discord could be done without prefixing `[{BRIDGE}]`, but when a message from or to Freenode is sent, `[{BRIDGE}]` is prefixed.

As far as I can tell, this would be possible using multiple one-way gateways if `RemoteNickFormat` were supported per gateway.

Would you accept a pull request implementing this?

**Comment by 42wim** [comment]
Hm yes, but it would have to work specific as well as general.

This would mean RemoteNickFormat could be configured on 4 levels
- `[bridge]` config eg `[irc.freenode]`
- `[general]` config
- `[[gateway]]` config
- `[[gateway.inout.options]]` config

So the overriding order would be from most specific to general:
`[[gateway.inout.options]]` > `[bridge]`  > `[[gateway]]` > `[general]`

The extra config would look like this
```
[[gateway]]
RemoteNickFormat="[{BRIDGE}]" 
Enable=true

[[gateway.inout]]
account="irc.freenode"
channel="#blah"
[[gateway.inout.options]]
RemoteNickFormat="[{PROTOCOL}]"

...
```

Comments ?

**Comment by jadjay** [comment]
Couldn't it be : 
'''
[[gateway.inout]]
account="irc.freenode"
channel="#blah"
RemoteNickFormat="[{PROTOCOL}]"
'''

**Comment by heinrich5991** [comment]
I turned out just using `[{BRIDGE}]` for all gateways.

**Comment by 42wim** [comment]
This can probably be fixed using the recently introduced tengo scripting option.
See https://github.com/42wim/matterbridge/pull/793
