### ISSUE TITLE
Allow changing the file size limit for attached files

### ISSUE THREAD

**Issue by jheiselman** [42wim/matterbridge#338]
If you have a configuration problem, please first try to create a basic configuration following the instructions on [the wiki](https://github.com/42wim/matterbridge/wiki/How-to-create-your-config) before filing an issue.

Please answer the following questions. 

### Which version of matterbridge are you using?
version: 1.6.2 ecf5669

### Please describe the expected behavior.
Add a configuration option to allow adjusting the file size limit in file attachments from Slack to other bridges. The current 1MB limit is too small for most use cases.

### Please describe the actual behavior. 
Adding a Slack-specific configuration parameter would allow the user to decide what the appropriate limit is. 

### Reference issue
#255

**Comment by 42wim** [comment]
Already possible
https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample#L1051-L1059

**Comment by jheiselman** [comment]
Doh. Missed that option showing up. Thanks.

**Comment by adbenitez** [comment]
> Already possible https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample#L1051-L1059

over time that lines changed and point to different unrelated configurations, permanent link:
https://github.com/42wim/matterbridge/blob/60639b6e5005f216d56b04a499540e0a4689e8d0/matterbridge.toml.sample#L1802-L1810
