### ISSUE TITLE
Twitch support?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [42wim/matterbridge#341]
Hi!

It looks like Matterbridge supports a nigh-absurd number of services (awesome work, guys!); the only one I know of that seems to be missing from the list, is Twitch's channel chat.

(Here's some prior art, just to show that it's possible — not written in Go, though: [DiscordLink](https://github.com/andrejsavikin/DiscordLink/blob/master/main.js) (JavaScript), [DTChatBot](https://github.com/Preston159/DTChatBot) (Java).

I'd love to contribute, except that I don't know any Go! 😭

**Comment by jheiselman** [comment]
Twitch uses IRC as it's backend platform. You can use the following settings:

Server: irc.chat.twitch.tv
Port: 6667

The username and password are oauth based, so you might need to figure that part out.

**Comment by 42wim** [comment]
Twitch is already supported, it's just IRC

Go to https://twitchapps.com/tmi/ this will get you an oauth token "oauth:fkjfsmqkjfsqmj" 

```
[irc.twitch]
name="twitch"
password="oauth:fkjfsmqkjfsqmj"
nick="anick"
server="irc.chat.twitch.tv:6697"
UseTLS=true
```
And just add it to the `[[gateway]]` config

```
[[gateway]]
name="mygateway"
enable=true

    [[gateway.inout]]
    account="irc.twitch"
    channel="#atwitchchannel"
```

Be warned though that twitch gets A LOT OF messages in almost any chatroom and this will be an issue for other bridges that will ratelimit/ban you. So be sure to do this only in rooms with not much users :)
