### ISSUE TITLE
Slack: When unthreading messages, quote previous message

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#343]
Currently, when two Slack teams are connected, threaded message responses are unthreaded into regular messages. This results in lost context.

**I wonder whether we could use quotes in messages to give these messages more context.** I'm unclear if this would be simple to do, or if it would require extra calls to slack API.

This quote could be either the original message of thread, or the one just prior. (The original message might make more sense, and would be possible to CTRL+F through logs and find all the responses.)

This would be particularly useful for responses to older messagemiis, for which unthreading is quite confusing.

Currently, mitigating this issue is only possible with social conventions that are hard to enforce: for example, 1) people avoiding threading, or 2) being explicit about which message you're responding to. That isn't ideal :)

**Comment by 42wim** [comment]
Looked into it, would need lots of changes, extra state keeping. 
This is nothing that can/will be added short-term

**Comment by patcon** [comment]
Thanks for investigating :)

Just to bump a half-formed idea in here -- what if:

1. there was a flag that would cause slack messages to do lookups in the ring cache for original messages on thread replies
    - successful lookup would cause slack messages to be prefixed with

      ```
      > The first ten words of the original thread message so...

      The unthreaded message that currently gets relayed on its own.
      ```
2. as is currently possible, ring cache buffer could be bumped with a protocol-level config for `Buffer=<big number>` in the toml

Would this be a possible path forward, when the time comes. The slight but of context would very helpfully hint the reader to the originated message, and they could use built-in search of the backscrool if they don't recall the rest :)

**Comment by 42wim** [comment]
Well, the ring cache is only used by the api bridge.
The other cache doesn't keep messages text, only IDs. 
Extending it to keep messages could be possible though.

**Comment by 42wim** [comment]
Has been fixed by supporting threading in slack I guess?

**Comment by patcon** [comment]
This was to avoid confusion when cache is lost and unthreads, but fine to close, since I'm not working on it right now :)
