### ISSUE TITLE
configurable output verbosity?

### ISSUE THREAD

**Issue by tomryanx** [42wim/matterbridge#345]
Is there a way to set the log level, other than `-debug`? I see a few mentions in the code, but nothing in config or command-line options. I'd like to reduce output for normal running.

[version: 1.6.3 50ac0fd]

**Comment by 42wim** [comment]
No, only debug level is an option.
It shouldn't output much after startup though, what do you want to suppress ?

**Comment by tomryanx** [comment]
In the last 12h since last rotation I've got about 2000 lines in the logs. The top three things logged are:

* presence info (which is not shared across the bridge) for every join/part
* full message content for every message
* 404 errors for c2s1 pings

I've got matterbridge running as a systemd service and outputting std{out|err} to syslog.

A workaround would be to send logs to /dev/null except when debugging. I don't really want everyone's chat logs clogging up syslog!

**Comment by 42wim** [comment]
full message content for every message ? what bridges are you using ?

**Comment by tomryanx** [comment]
mattermost-xmpp and mattermost-irc

I've just checked, and it's only the mattermost-xmpp bridge that is logging so verbosely.

**Comment by 42wim** [comment]
This should be fixed now.
Could you try a dev build ?
You can find binaries here https://bintray.com/42wim/nightly/Matterbridge/v1.6.0-26-g6a047f8#files

**Comment by tomryanx** [comment]
Nice and quiet now - thanks a lot for the quick fix!
