### ISSUE TITLE
Slack <=> Slack attachment comments don't go through gateway

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#346]
Here's my bug description. I thoughts I recalled this being known behaviour for attachments, but can't find a record of it. Thanks for your consideration!

### Which version of matterbridge are you using?
I'm on a nightly build after v1.6.3: https://bintray.com/42wim/nightly/download_file?file_path=matterbridge-v1.6.0-24-g7c6ce8b-linux-amd64

### Please describe the expected behavior.

I would expect that when I upload an image to one Slack, all subsequent comments on that image would be sent through gateway.

### Please describe the actual behavior. 

Instead, I am seeing the initial comment from the creation of the attachment, but then no further comments are relayed. (Fwiw, the attachement comment messages on the outgoing side are auto-posted to channel on outgoing end, unlike traditional threads which provide a checkbox for toggling that behaviour.)

Outgoing web interfac: https://imgur.com/FnMkn4K
Incoming web interface: https://imgur.com/w01iVBQ

[debug logs](https://gist.github.com/patcon/57b4e1c2cab0568b1e151ca42c0dde7c)

### Any steps to reproduce the behavior?

See above.

[config file](https://github.com/edgi-govdata-archiving/matterbridge-heroku/blob/edgi/config/config-heroku-template.toml)

**Comment by 42wim** [comment]
I didn't even know you could comment on attachments :) (does it show I'm not a slack user)
