### ISSUE TITLE
High bandwidth consumption with Telegram servers

### ISSUE THREAD

**Issue by ValdikSS** [42wim/matterbridge#349]
Matterbridge exchanges anomalously high amount of data with Telegram servers. Usually about 500 Kbit/s - 1.5 Mbit/s, which consumes up to 20 GB of bandwidth per day.
I'm running only a single gateway with single Telegram account.

### Which version of matterbridge are you using?
Matterbridge v1.7.0

**Comment by ValdikSS** [comment]
Most probably you need to set timeout to non-zero value to enable long polling here:
https://github.com/42wim/matterbridge/blob/master/bridge/telegram/telegram.go#L38

**Comment by 42wim** [comment]
I guess this depends on how busy your group is?
It downloads every video, sticker, photo, audio etc.. by default only max 1MB.
Set https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample#L1051-L1060 to 1 to disable any downloads

**Comment by ValdikSS** [comment]
The group is 1 message per hour without any media.

**Comment by 42wim** [comment]
Wtf :)
That's very strange, can't test myself don't use telegram.
There is no longpolling option though.

**Comment by ValdikSS** [comment]
There is, take a look at example at https://github.com/go-telegram-bot-api/telegram-bot-api
Right now I believe Matterbridge constantly sends HTTP requests to Telegram server multiple times per second.

**Comment by ValdikSS** [comment]
https://core.telegram.org/bots/api#getupdates

>Use this method to receive incoming updates using long polling (wiki). An Array of Update objects is returned.
>Timeout in seconds for long polling. Defaults to 0, i.e. usual short polling. Should be positive, short polling should be used for testing purposes only.

https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/helpers.go#L320

```
func NewUpdate(offset int) UpdateConfig {
	return UpdateConfig{
		Offset:  offset,
		Limit:   0,
		Timeout: 0,
	}
}
```

**Comment by ValdikSS** [comment]
Would it require to change Telegram API architecture in Matterbridge or you can just set the timeout value and it works? I never used Go and I don't know if it would lock other goroutines in Matterbridge.

**Comment by 42wim** [comment]
Thanks! I'm on mobile atm, will fix this later

**Comment by 42wim** [comment]
Yes you can just change value, we're using channels there, no locking issues will happen
If you change
	`updates, err := b.c.GetUpdatesChan(tgbotapi.NewUpdate(0))`
To
```
        u := tgbotapi.NewUpdate(0)
	u.Timeout = 60
	updates, err := b.c.GetUpdatesChan(u)
```

It should work just fine, feel free to PR this if it fixes your issue :)

**Comment by ValdikSS** [comment]
Yep, just changed that, Matterbridge doesn't deadlock, and no high bandwidth consumption. I'l make a PR.
