### ISSUE TITLE
Steam bridge needs 5$ purchase

### ISSUE THREAD

**Issue by heinrich5991** [42wim/matterbridge#351]
I tried to create a new Steam account for the bot, but it didn't start working (and didn't give any errors) until I made a purchase. Maybe this could be mentioned somewhere.

**Comment by heinrich5991** [comment]
I just bought something for more than 5$.

**Comment by heinrich5991** [comment]
For some reason, I forgot to post the link in the initial issue: https://support.steampowered.com/kb_article.php?ref=3330-IAGK-7663. The page describes what I saw and also specifies the 5$ limit.

**Comment by 42wim** [comment]
Thanks, I'll add that to the wiki!
