### ISSUE TITLE
Don't send purpose and topic messages through Slack bridge

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#353]
I have a use-case that I expect won't be that uncommon as this tool catches on within communities.

I have created a gateway for connecting the leadership of all civic tech communities in Canada. There are going to be maybe 5 Slack teams in the channel for now.

We try to keep the topic and purpose synchronized between Slack teams. This is where we explain the how the bridge works, and who is present on the other sides.

Right now, when we update the purpose or topic on each slack team, we essentially spam the whole gateway. It would be much more sensible to NOT send these statements through the portal by default, and perhaps allow an option to turn this on (if that's even necessary).

https://imgur.com/WLn7LOb

Thanks! Curious your thoughts!

**Comment by 42wim** [comment]
Sounds reasonable (I didn't even know those messages were sent).
I can make a option for this.

![image](https://user-images.githubusercontent.com/1810977/35635869-b77f638e-06af-11e8-95bb-3ea4f1a76d4a.png)

**Comment by 42wim** [comment]
So, there is now a `ShowTopicChange` option.
Disabled by default

**Comment by patcon** [comment]
Thanks 42wim! Sorry, I've been lazy lately, and you are doing all the work. I really appreciate it though

Before this gets locked into a release, perhaps a small change I'd be curious your thoughts on:

Seems there are lots of channel action messages that would all be undesirable at the same time:
https://api.slack.com/events/message

Specifically:
```
channel_purpose
channel_name
channel_topic
pinned_item
unpinned_item
```

Would it make sense for the setting to be `ShowMetaMessages` or `ShowChannelMeta`, and enable/disable them all at once?

**Comment by patcon** [comment]
Though actually, "channel_name" would be useful, as that seemingly-innocent change will break the bridge on the next restart :) I'd at least be aware it was about to go down if I same the name-change message...!

But all the others are unhelpful noise

**Comment by 42wim** [comment]
oh right, i'll add channel_purpose to the channel_topic switch.
The pinned_items don't deserve a toggle, I'll block those.

The channel_name one are very rare I think? So those can go through.

**Comment by patcon** [comment]
Yep, very rare normally, and should be "never" here :)

You're great!
