### ISSUE TITLE
Mixer (old beam.pro) chat support

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#354]
with twitch support, i would love to see mixer support too, so i can set up matterbridge for all my streamer friends that multistream to both platforms

https://dev.mixer.com/reference/chat/index.html

seems like they have a custom REST based chat system that should allow deleting messages across the bridge too (seems like edit is not in scope for such a chat)

**Comment by jheiselman** [comment]
I did a quick search and couldn't find a go library that implements this.

**Comment by 42wim** [comment]
@NikkyAI you could build support for this yourself using the matterbridge api ?:)

Unfortunately for me, if there isn't a library available, it's way down on the backlog. 
(thanks for the research @jheiselman)

I'll add it to #28 so that people know a PR is welcome
