### ISSUE TITLE
Feature request: allow markdown for mattermost and telegram

### ISSUE THREAD

**Issue by rbenea** [42wim/matterbridge#355]
Both Mattermost and Telegram support markdown markup language. A bridge between them should allow markdown to be passed through.

For messages sent to a telegram server allow only the accepted formatting: https://core.telegram.org/bots/api#markdown-style

**Comment by 42wim** [comment]
Markdown is allowed to pass to mattermost. What markdown doesn't work?

**Comment by rbenea** [comment]
For testing I have a telegram group and a mattermost group connected via matterbridge.

If I write on the telegram group: normal **bold** `code` (in markdown, GitHub si interpreting it)
- in the telegram group I get the formatting right and all telegram clients see it
- in the mattermost group I get plain text

If I write on the mattermost group: normal **bold** `code`
- in the telegram group I get plain text but with the markdown ** and ` in it, no formating
- in the mattermost group I get the formatting right

If I write on the mattermost group an inline URL `[example](http://example.com)`:
- in the telegram group I get plain text but with the markdown in it: `[example](http://example.com)`
- in the mattermost group I get the formating right
I cannot replicate from telegram to mattermost due to the telegram client.

**Comment by 42wim** [comment]
`MessageFormat="Markdown"

**Comment by rbenea** [comment]
I have added MessageFormat="Markdown" all over the place, in the [mattermost] in the [telegram] in the [[gateway]] sections and it has no effect.

**Comment by 42wim** [comment]
Could you please paste your config (don't forget to remove sensitive info) and paste the output of `matterbridge -version` ?

**Comment by rbenea** [comment]
Another finding: I bridged 2 matter most channels in the same server and it seems that the markdown is passed from one channel to another. There is a bug, I send **bold** it comes on the other side as _bold_ (with italics formatting).

If I bridge 2 telegram channels on the same account, the formatting is lost. If I write **bold** in one channel I get bold (plain text without formatting or ** in it) on the other channel. 

Both  [mattermost] and [telegram] entries have MessageFormat="Markdown" defined. 

In your advanced config matterbridge.toml.sample you say:
#Only supported format is "HTML", messages will be sent in html parsemode.
#See https://core.telegram.org/bots/api#html-style
MessageFormat=""

**Comment by 42wim** [comment]
ould you please paste your config (don't forget to remove sensitive info) and paste the output of `matterbridge -version` ?

**Comment by rbenea** [comment]
I use 
```
matterbridge-linux-amd64 -version
version: 1.7.1 0f5274f
```
and this my config:
```
[mattermost]
    [mattermost.chat]
    Server="localhost:8065"
    NoTLS=true
    Team="team"
    Login="user"
    Password="pass"
    PrefixMessagesWithNick=true
    MessageFormat="Markdown"

[telegram.chat]
    Token="123456789:token"
    MessageFormat="Markdown"

[general]
RemoteNickFormat="@{NICK} "

# this must always be [[gateway]], don't use anything else
[[gateway]]
name="town-square"
enable=true

    [[gateway.inout]]
    account="mattermost.chat"
    channel="town-square"

    [[gateway.inout]]
    account="telegram.chat"
    channel="-123456789"
```

**Comment by 42wim** [comment]
Ok, you didn't download the dev build as I asked you to do, so the Markdown doesn't work.

See https://github.com/42wim/matterbridge/issues/355#issuecomment-362860553

**Comment by rbenea** [comment]
You are right, sorry for that. I test now with the new build
```
./matterbridge-v1.7.1-12-ge8b3e9b-linux-amd64 -version                             
version: 1.7.2-dev e8b3e9b
```
I hope that this table is more easy to read. Look at the strange behaviour for italics. 

|Write T|Write M|Output T|Output M|
|----------|-----------|------------|-------------|
|\*\*bold\*\*|       | **bold** | bold |
|       |\*\*bold\*\*| bold |**bold**|
|\`code\`|           |`code`|code|
|           |\`code\`|\`code\`|`code`|
|\_ital\_|             |\_ital\_|_ital_|
|           | \_ital\_ |\_ital\_|_ital_|
|\_\_ital\_\_|         |_ital_|ital|
|           |\_\_ital\_\_ |\_\_ital\_\_|**ital**|

**Comment by rbenea** [comment]
I added api.local to the gateway:
```
[api]                                                                                                                                                                                                                       
    [api.local]                                                                                                                                                                                                             
    BindAddress="127.0.0.1:4242"                                                                                                                                                                                            
    Buffer=1000                                                                                                                                                                                                             
    MessageFormat="MarkDown" 
```

It seems that Telegram is stuck in HTML mode. 
* If I send markdown messages via curl they are ok in Mattermost and in Telegram they get displayed as plaintext with the markdown ex: \*\*bold\*\*
* If I send html messages via curl they get displayed correctly in Telegram and in Mattermost I get the html code ex: \<b\>bold\<\/b\>

**Comment by 42wim** [comment]
I've added a new dev build with more debug output, could you download https://bintray.com/42wim/nightly/Matterbridge/v1.7.1-13-g432cd0f#files

Run with `-debug`
Do your tests again and put the output somewhere (pastebin or so). Look for sensitive information first.

But in those debug logs you'll see a message `Using mode markdown` or `Using mode HTML` so you can be sure that the correct mode is selected.

You'll also what matterbridge exactly receives from mattermost and telegram and what matterbridge exactly sends to mattermost and telegram. 

(There is an replacement with `*` in mattermost, so the bold test isn't reliable https://github.com/42wim/matterbridge/blob/master/bridge/mattermost/mattermost.go#L362-L365)

**Comment by rbenea** [comment]
To make things simpler, I made a config to bridge 2 Telegram chats. The markdown is not transmitted ex: for `code` I get code (plain text without `)

This is the debug log: https://pastebin.com/DiDNcD9B

**Comment by 42wim** [comment]
Ok, so that means telegram is removing those markdown codes for bots. 
Nothing I can do to fix this :(

**Comment by rbenea** [comment]
Thank you for your time :( I'll continue using the latest version that you sent me and
let you know if I have updates related to this subject.

**Comment by wsdjeg** [comment]
so this issue can not be fixed? if we want to bold the nick name?

**Comment by 42wim** [comment]
@wsdjeg try the latest dev binary https://bintray.com/42wim/nightly/Matterbridge/v1.9.0-8-g68fbed9#files

In your telegram config:
Set `RemoteNickFormat="&lt;{NICK}&gt;"`
Set `MessageFormat="HTML"`
