### ISSUE TITLE
Media not getting reuploaded from Telegram to Mattermost and vice versa

### ISSUE THREAD

**Issue by ValdikSS** [42wim/matterbridge#356]
### Which version of matterbridge are you using?
Matterbridge v1.7.1

### Please describe the actual behavior. 
Media (pictures and files) uploaded from Mattermost to Telegram are sent as links, even with MediaServer configured.
Media from Telegram to Mattermost gets uploaded to MediaServer but does not getting sent to Mattermost because of missing uploaded data. Matterbridge just sends text message without any text, for what Mattermost returns HTTP 400.

```
POST /hooks/abcdefabcdefabcdefabcdef HTTP/1.1
Host: 127.0.0.1:8065
User-Agent: Go-http-client/1.1
Content-Length: 144
Content-Type: application/json
Accept-Encoding: gzip

{"channel":"matterbridge-test","icon_url":"https://telegram.org/img/t_logo.png","username":"telegramnickname","text":"","props":{"matterbridge":true}}

HTTP/1.1 400 Bad Request
Content-Type: application/json
X-Request-Id: abcdefabcdefabcdef
X-Version-Id: 4.5.0.4.5.0.32b0bb53a48f169382d6ff60b05062cf.false
Date: Wed, 31 Jan 2018 15:09:42 GMT
Content-Length: 154

{"id":"web.incoming_webhook.text.app_error","message":"No text specified","detailed_error":"","request_id":"abcdefabcdefabcdef","status_code":400}
```

### Any steps to reproduce the behavior?
1. Configure Telegram-Mattermost bridge (Username/password for incoming messages and webhook for outgoing in my case).
2. Try to send any media

I believe the problem is as with XMPP described in https://github.com/42wim/matterbridge/issues/295#issuecomment-360992230, but both Telegram and Mattermost support native media transfer, so Matterbridge should use native media uploading/downloading APIs without external MediaServer.

**Comment by 42wim** [comment]
Well, that's more or less correct behaviour :-) 

* Mattermost (upstream) doesn't support file uploads with webhook. 
* Uploads only happen to bridges that receive messages from bridges that don't have public urls (like slack, telegram,matrix ).

So slack => mattermost or telegram => matrix or matrix => slack will
But mattermost => anything else will not

Seems the bug here is that links to mediaserver when using mattermost webhooks aren't sent.

Any reason you use webhooks for mattermost ? (if not really needed, do not use them :)

**Comment by 42wim** [comment]
I've added a commit to master that adds the URL to the message when using webhooks and an external mediaserver. So this partly fixes your problem.

I'm not convinced to upload files to other bridges if the links are public anyway.

**Comment by ValdikSS** [comment]
As far as I understand you can't spoof user name without webhook, that's why I use them.

>Uploads only happen to bridges that receive messages from bridges that don't have public urls (like slack, telegram,matrix ).

Mattermost don't have public URLs to media either, but Matterbridge does not re-upload Mattermost media to MediaServer. When I try to send media to Mattermost channel, I receive direct URL for it which would not work without authentication.
`http://mattermosthost.com/api/v3/files/somethingsomething/get`

In an ideal scenario I'd like Matterbridge to use native Telegram upload procedure without using MediaServer.

**Comment by 42wim** [comment]
Yes correct, you can't spoof without webhooks.

About public URLS, see https://docs.mattermost.com/administration/config-settings.html#public-links
If this option is disabled, then yes it would be useful to use native upload to bridges that support this.

I'll make a new issue for this :)

Could you test if the URL now works with latest master ? (binaries can be found here: https://bintray.com/42wim/nightly/Matterbridge/v1.7.1-2-g64a20ee#files)

**Comment by 42wim** [comment]
If you really want the feature regardless of the links are public, please open a new issue for this.
I could make it a config parameter.

**Comment by ValdikSS** [comment]
>If this option is disabled, then yes it would be useful to use native upload to bridges that support this.

I see, thanks for the link, I slipped over this option somehow. But it won't help in my situation anyway, since my Mattermost instance is available only with client certificate authentication.

>Could you test if the URL now works with latest master?

It works fine, thanks.

>If you really want the feature regardless of the links are public, please open a new issue for this.
I could make it a config parameter.

That would be great.
