### ISSUE TITLE
Do native uploads (to supported bridges) when mattermost public links are disabled.

### ISSUE THREAD

**Issue by 42wim** [42wim/matterbridge#357]
See #356 

When public links are disabled, it's not useful to sent those links to other bridges. Users can't see them.
Download and upload those images to bridges with natve upload support (or media server)

**Comment by ValdikSS** [comment]
I'd say that using native upload mechanism where available should be preferred over using MediaServer. Not only native uploads looks better in most cases, but, in my opinion, it's better to keep media on others' infrastructure wherever possible than to rely on external MediaServer. You won't need to keep the files and you can run Matterbridge even without routable IP address (behind NAT) that way.

**Comment by 42wim** [comment]
Yes, native upload is preferred over using MediaServer.
Public links > native upload > mediaserver is currently the preference chain.

I agree that mattermost is special here because of non-public links and/or NAT. 

But for example gitter and discord have public links so I wouldn't do a native upload here.

**Comment by ValdikSS** [comment]
I'd prefer native upload where available even with public links, because native uploads usually looks better than linked media, and your client (or server) doesn't need to connect to third-party server to receive the media, hence less bandwidth is required for MediaServer.

I'd vote for a configurable option if it's complies with your vision on this idea.

**Comment by 42wim** [comment]
You sold me on it. (also I don't have to write a check now for public/private links)
Mattermost files get downloaded and native uploaded on bridges that support it. 
Non-supported (like irc, xmpp) still get a link.

Change is in master, feedback is appreciated

**Comment by ValdikSS** [comment]
Works perfectly fine, thanks!
