### ISSUE TITLE
Telegram media description is missing

### ISSUE THREAD

**Issue by ValdikSS** [42wim/matterbridge#358]
### Which version of matterbridge are you using?
Matterbridge v.1.7.1

### Please describe the expected behavior.
I'm using MediaServer with Telegram↔XMPP and Telegram↔Mattermost bridges.
You can add text to uploaded media in Telegram, but it gets discarded by Matterbridge. You'd expect to get both link and description text, but only link is sent to bridged chats.

### Any steps to reproduce the behavior?
1. Configure Telegram↔XMPP or Telegram↔Mattermost bridge with MediaServer (haven't tried without MediaServer)
2. Upload image to Telegram with description text
3. You get only the image to bridged chat, without description text

Here is Telegram API reply for that case:
```
{
  "ok": true,
  "result": [
    {
      "update_id": 796693268,
      "message": {
        "message_id": 3831,
        "from": {
          "id": 454545454545,
          "is_bot": false,
          "first_name": "Firstname",
          "last_name": "Lastname",
          "username": "username"
        },
        "chat": {
          "id": -123456789,
          "title": "Some title",
          "type": "supergroup"
        },
        "date": 1517420133,
        "photo": [
          {
            "file_id": "idididididididididididididididididididididididididididid",
            "file_size": 1793,
            "width": 90,
            "height": 68
          },
          {
            "file_id": "idididididididididididididididididididididididididididid",
            "file_size": 27469,
            "width": 320,
            "height": 241
          },
          {
            "file_id": "idididididididididididididididididididididididididididid",
            "file_size": 85444,
            "width": 700,
            "height": 528
          }
        ],
        "caption": "This is the description"
      }
    }
  ]
}
```

**Comment by ValdikSS** [comment]
Thank you!

Does not build right away:
https://github.com/42wim/matterbridge/commit/7764493298760ec8d33f5387ea2fb6c4705a407e#r27248953

There is no space between colon and URL, the following should look better
`msg.Text += fi.Comment + ": "`

**Comment by 42wim** [comment]
oops build fixed.
Would you mind making a PR with the extra space?
off to bed now.

**Comment by ValdikSS** [comment]
#360

**Comment by TomTheDragon** [comment]
That bug is still present when you use WebhookURL for name/icon spoofing on Discord

**Comment by patcon** [comment]
Oh hey, thanks @TomTheDragon! I don't use discord, but I think it's file upload is handled here:
https://github.com/42wim/matterbridge/blob/8522d8f29cf1625a0d31dab15428600133fe0dba/bridge/discord/discord.go#L287-L306

If you can spot this other bug, and have time to submit a quick PR, we'd be super-grateful :)

**Comment by TomTheDragon** [comment]
I am sorry but i think i am not able to fix this myself, i only wanted to inform you guys, that this is a very annoying bug that is still present.
I only noticed it after i started to use Webhooks recently.

**Comment by patcon** [comment]
ok, no prob! thanks for considering @TomTheDragon. pls do open a new issue for it though, as it's a separate issue that's best tracked on its own :)

**Comment by TomTheDragon** [comment]
> 
> 
> @TomTheDragon try latest dev build: https://bintray.com/42wim/nightly/Matterbridge/v1.12.0-68-g46e2683#files

Works now like it should ;)
