### ISSUE TITLE
Send chat notification if media is too big to be re-uploaded to MediaServer

### ISSUE THREAD

**Issue by ValdikSS** [42wim/matterbridge#359]
### Which version of matterbridge are you using?
Matterbridge v1.7.1

### Please describe the expected behavior.
Sometimes it's convenient to know that new media has been uploaded to bridged chat, even if it's too big to be re-uploaded. It could be confusing when people send some big documents and discuss them, but people over bridge don't understand what others are discussing since the important component of discussion is missing.

If media contains description and is too big to be re-uploaded, the description should be preserved in too-big-to-be-reuploaded chat notification (see #358).

### Please describe the actual behavior. 
Currently, if media exceed MediaDownloadSize it won't be re-uploaded and no notification is sent to bridged chats.

**Comment by 42wim** [comment]
That was a bigger patch than expected. 
Feedback appreciated

**Comment by ValdikSS** [comment]
Works fine, thank you a lot!
