### ISSUE TITLE
Support for avatars/attachments when possible

### ISSUE THREAD

**Issue by akhmerov** [42wim/matterbridge#36]
Matterbridge currently offers the best existing way of creating guest users/publishing a channel. To do this one just needs to create two teams, `internal` and `visitors` on the same server. Then creating private or public channels in `visitors` team and linking them via matterbridge to corresponding channels in the `internal` team offers a decent realization of one of the most popular requested [features]((https://mattermost.uservoice.com/forums/306457-general/suggestions/9982719-add-restricted-users). As of now, on the mattermost side the planned implementation of the feature is partial (right now only single-channel guest users are planned), and only intended for the E10-edition: https://mattermost.atlassian.net/browse/PLT-3636

Therefore improving matterbridge support for single-server bridges would be very useful. As far as I can tell, there are several things that are currently not handled by matterbridge, and that would be nice to handle:
- Modifying the avatars on message
- Handling file attachments
- ¿custom emoji?
- Is there anything else?

**Comment by 42wim** [comment]
At the moment the bridge are very generic, to do what you propose I'll need to add some kind of capability system to know what every bridge can support (beside just text). 
Not committing to this, but I'll think about it.

File attachments are handled already btw, in the way that a download URL is posted.

**Comment by akhmerov** [comment]
BTW just verified that something goes wrong with attachments:

This is what I get with click + copy public link:
`https://our.mattermost.server/api/v3/public/files/get/nh5rs8bpitrxtdr5juit3tdz4r/psbs9a5kmfga5biiho41eer5jy/hbwgxekk8inktn3beng4ewjr8r/oqtntdukobgo9fiwjda9syu8jr/Image Pasted at 2016-10-18 23-53.png?h=N4huqINVMkUc4BdL2ytW6R5-UHFd8qjZ68A9TC_QnFs`

and this is what matterbridge wrote:
`https://our.mattermost.server/api/v3/public/files/get/nh5rs8bpitrxtdr5juit3tdz4r/psbs9a5kmfga5biiho41eer5jy/hbwgxekk8inktn3beng4ewjr8r/oqtntdukobgo9fiwjda9syu8jr/Image%20Pasted%20at%202016-10-18%2023-53.png?h=kJm5rYTmtNz_t6qbsDw6q5C8jRbCyBboDLAtj1oCuIw`

and it results in `{"id":"api.file.get_file.public_invalid.app_error","message":"The public link does not appear to be valid","detailed_error":"","request_id":"bj5jdogatiytzdo1wujzohuq8h","status_code":400}`

**Comment by 42wim** [comment]
I can not reproduce this, works fine for me

**Comment by akhmerov** [comment]
Could it be a bug with mattermost lingering after several subsequent upgrades?

**Comment by akhmerov** [comment]
About the additional things that may be worth including in the bridge similarly to avatars:
* message editing (supported at least by slack, mattermost, and gitter).
* message responses (specific to mattermost I believe)

**Comment by 42wim** [comment]
Message editing (and responses) should now be working. 
They are sent as a normal message so every protocol is supported
