### ISSUE TITLE
[Feature] Allow listing of members across bridges

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#361]
I wonder whether we could create a shorthand for helping people find members across bridges.

An ephemeral slash command might work: (only seen by sending user) 
https://api.slack.com/slash-commands

Feature as imagined is slack-specific, but need not be.

A Slack slash command is just an integration that would be set up in Slack UI to hit an endpoint -- it could run off a "hook", whose precedent was already set up [rocketchat hook integration](https://github.com/42wim/matterbridge/blob/master/hook/rockethook/rockethook.go)

Or does this this seem like scope creep? I could understand that perspective :)

**Comment by 42wim** [comment]
Related to #191 
I want one solution for all bridges, probably will be by talking and sending commands to the bot

**Comment by patcon** [comment]
Ok, I'm grateful that you see it as helpful too! Do you feel it's important that the command/response NOT be public when possible to avoid?

**Comment by Jaykul** [comment]
If you wanted a list, it seems important it should PM you -- but checking to see if someone is "online" could still be really useful and not as spammy ...


> **!whois Jaykul**
> Found Jaykul on Discord (idle) and IRC as well as (here on) Slack

**Comment by patcon** [comment]
cc @valvin1 @guakamole (from other thread)

**Comment by 42wim** [comment]
Closed in favor of #191
