### ISSUE TITLE
Use Telegram users avatars in Mattermost incoming webhook

### ISSUE THREAD

**Issue by ValdikSS** [42wim/matterbridge#362]
It would be useful to use real avatars in "icon_url" parameter for Mattermost. That way you can visually distinguish which user wrote the message.
The avatars should probably follow rules for the media, e.g. get reuploaded to MediaServer if needed.

**Comment by 42wim** [comment]
This is already implemented for mattermost, slack and discord.
I guess you're talking about telegram ?:)

**Comment by ValdikSS** [comment]
Yes, for Telegram→Mattermost messages.

**Comment by 42wim** [comment]
This was a rather big patch, could you please test this and give feedback ?
Thanks!

**Comment by ValdikSS** [comment]
Unfortunately doesn't work as expected. Debug log shows that Telegram avatars are downloaded but in the message the avatar argument is blank, and no avatar is added to Telegram→Mattermost relayed message.
I've send debug log to your email.

**Comment by ValdikSS** [comment]
Sometimes Matterbridge adds avatars to Mattermost message, but `MediaServerUpload` URL is used instead of `MediaServerDownload`.

**Comment by ValdikSS** [comment]
Seems like the first messages are getting relayed without avatar, until the avatar is downloaded, and after it's downloaded, everything work fine if https://github.com/42wim/matterbridge/commit/7886f05e881e45303087a5ae116657f0f6164d81#diff-b113bff04f00d1b657baf156f81621e2R60 is changed to `general.MediaServerDownload`.

**Comment by 42wim** [comment]
Oops, indeed thanks for debugging this!
So after this change it works like you expect it works ? (except the first message of each user)

**Comment by ValdikSS** [comment]
> So after this change it works like you expect it works ? (except the first message of each user)

Yes.
