### ISSUE TITLE
ReplaceMessages RegExp is not allowing to escape *, (, [ etc..

### ISSUE THREAD

**Issue by rbenea** [42wim/matterbridge#363]
If I try to replace `**` with `<b>` using `ReplaceMessages=[ ["\*\*","<b>"] ]` I get:

`invalid escape character '*'; only the following escape characters are allowed: \b, \t, \n, \f, \r, \", \\, \uXXXX, and \UXXXXXXXX`

**Comment by 42wim** [comment]
You need to escape the `\` because of toml
Try `ReplaceMessages=[ ["\\*\\*","<b>"] ]`
