### ISSUE TITLE
Matterbridge crashes at start with discord gateway enabled

### ISSUE THREAD

**Issue by nightbbs** [42wim/matterbridge#367]
### Which version of matterbridge are you using?
run ```matterbridge -version```
1.7.2-dev

#### Use logs from running ```matterbridge -debug``` if possible.
INFO[2018-02-07T16:42:24+03:00] Enabling debug                               
INFO[2018-02-07T16:42:24+03:00] Running version 1.7.2-dev                    
INFO[2018-02-07T16:42:24+03:00] WARNING: THIS IS A DEVELOPMENT VERSION. Things may break. 
DEBU[2018-02-07T16:42:24+03:00] Configuring Discord Incoming Webhook          module=discord
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/42wim/matterbridge/bridge/discord.(*bdiscord).splitURL(0xc420181900, 0xc420015cc0, 0x14, 0x1, 0xc42039ebd0, 0xc4201dda98, 0xc42025a828)
        /home/nightlord/go/src/github.com/42wim/matterbridge/bridge/discord/discord.go:372 +0xa7
github.com/42wim/matterbridge/bridge/discord.New(0xc4203a8840, 0xc42039e210)
        /home/nightlord/go/src/github.com/42wim/matterbridge/bridge/discord/discord.go:41 +0x199
github.com/42wim/matterbridge/bridge.New(0xc420384000, 0xc42037b7c0, 0xc42005c240, 0x0)
        /home/nightlord/go/src/github.com/42wim/matterbridge/bridge/bridge.go:71 +0x10d9
github.com/42wim/matterbridge/gateway.(*Gateway).AddBridge(0xc42037b770, 0xc42037b7c0, 0x0, 0x0)
        /home/nightlord/go/src/github.com/42wim/matterbridge/gateway/gateway.go:49 +0x111
github.com/42wim/matterbridge/gateway.(*Gateway).AddConfig(0xc42037b770, 0xc420250900, 0xc42039e8d0, 0x0)
        /home/nightlord/go/src/github.com/42wim/matterbridge/gateway/gateway.go:61 +0x273
github.com/42wim/matterbridge/gateway.New(0xc420390360, 0x9, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4203a2000, ...)
        /home/nightlord/go/src/github.com/42wim/matterbridge/gateway/gateway.go:42 +0x289
github.com/42wim/matterbridge/gateway.NewRouter(0xc420384000, 0x11, 0xc420384000, 0x4)
        /home/nightlord/go/src/github.com/42wim/matterbridge/gateway/router.go:37 +0x2c3
main.main()
        /home/nightlord/go/src/github.com/42wim/matterbridge/matterbridge.go:47 +0x403

#### (be sure to exclude or anonymize private data (tokens/passwords))
[irc]
[irc.nightbbs]
Server=""
UseTLS=false
UseSASL=false
SkipTLSVerify=true
Charset=""
Nick="matterbot"
NickServNick="nickserv"
NickServPassword="secret"
NickServUsername="username"
MessageDelay=1300
MessageQueue=30
MessageLength=400
MessageSplit=false
IgnoreNicks="ircspammer1 ircspammer2"
IgnoreMessages="^~~ badword"
ReplaceMessages=[ ["cat","dog"] ]
ReplaceNicks=[ ["user--","user"] ]
RemoteNickFormat="<{NICK}> "
ShowJoinPart=true
StripNick=false
[xmpp]
[xmpp.jabber]
Server=":5222"
Jid=""
Password=""
Muc="conference."
Nick=""
SkipTLSVerify=true
IgnoreNicks="ircspammer1 ircspammer2"
IgnoreMessages="^~~ badword"
ReplaceMessages=[ ["cat","dog"] ]
ReplaceNicks=[ ["user--","user"] ]
RemoteNickFormat="<{NICK}> "
ShowJoinPart=true
StripNick=false
[general]
RemoteNickFormat="<{NICK}> "
StripNick=false
MediaServerUpload=""
MediaServerDownload=""
[telegram]
[telegram.mytelegram]
Token=""
UseInsecureURL=false
ReplaceNicks=
RemoteNickFormat="<{NICK}> "
[discord.game]
Token=""
Server=""
ShowEmbeds=false
UseUserName=false
WebhookURL="Yourwebhooktokenhere"
EditDisable=false
EditSuffix=" (edited)"
IgnoreNicks="ircspammer1 ircspammer2"
IgnoreMessages="^~~ badword"
ReplaceNicks=[ ["user--","user"] ]
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
ShowJoinPart=false
StripNick=false
[[gateway]]
name="mygateway"
enable=true
[[gateway.inout]]
account="irc.nightbbs"
channel=""
[[gateway.inout]]
account="xmpp.jabber"
channel=""
[[gateway.inout]]
account="telegram.mytelegram"
channel="****"
[[gateway.inout]]
  account="discord.game"
  channel="general"

**Comment by 42wim** [comment]
It crashes because the `WebhookURL="Yourwebhooktokenhere"` isn't correct .
See https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks
Or remove `WebhookURL` if you have a token

**Comment by 42wim** [comment]
If you create a config from scratch it easier to follow https://github.com/42wim/matterbridge/wiki/How-to-create-your-config which has minimal working configs

**Comment by 42wim** [comment]
Fixed in master
