### ISSUE TITLE
[Feature] Provide better context for shared posts from Slack<=>Slack

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#369]
In the interest of making convo coming through the bridge more transparent, it would be nice if posts that were "shared" from one channel to another on one slack, were hinted at on the other side of bridged slacks:

For example, this was posted to one slack
![screenshot](https://imgur.com/ETjoiRk.png)

And this was how it was seen on the other side
![screenshot](https://imgur.com/QfcPIdQ.png)

Recognizing that the message content is difficult to obtain without prior work (https://github.com/42wim/matterbridge/issues/343#issuecomment-362861546), here are some other possible improvements on the situation:
1. add a simple indicator that a shared post accompanied the message
2. add an external link, pointing to the message within the other slack. (Make a parenthetical caveat that sign-up is required.)

**Comment by patcon** [comment]
Actually! I just realized that a "Fallback" key exists in the message, so perhaps that could be used?
https://gist.github.com/patcon/a2c204926629e2c4ec8ede0bd6438eab

Is this worth my investigating @42wim? Or would it be too special-case for the slack bridge?

**Comment by 42wim** [comment]
Well, slack attachments are supported, but only when the text in the message is empty, because fallback is normally used as a fallback of the text in the attachment self.

I could do a check that if message text != fallback then show them both.
