### ISSUE TITLE
discord mentions are not correctly replaced on outgoing messages

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#370]
### Please describe the expected behavior.

messages like 
test user: @user#1234 test role: @testrole
should be replacing the user with its nickname if he has one and the settings are configured to do so

the code that has to be replaced / changed is https://github.com/42wim/matterbridge/blob/83c28cb857e47e8e2958745eeac7f97448909968/bridge/discord/discord.go#L228

there exists a version of that function to handle role mentions as well
https://github.com/bwmarrin/discordgo/blob/master/message.go#L207
although it might have to be handled manualyl to make use of 
https://github.com/42wim/matterbridge/blob/83c28cb857e47e8e2958745eeac7f97448909968/bridge/discord/discord.go#L276

**Comment by 42wim** [comment]
Fixed in master
