### ISSUE TITLE
toml: type mismatch for config.Protocol: expected table but found string

### ISSUE THREAD

**Issue by fnadde42** [42wim/matterbridge#371]
If you have a configuration problem, please first try to create a basic configuration following the instructions on [the wiki](https://github.com/42wim/matterbridge/wiki/How-to-create-your-config) before filing an issue.

Please answer the following questions. 

### Which version of matterbridge are you using?
version: 1.7.1 0f5274f

### Please describe the expected behavior.
Running a bridge between Discord and IRC.

#### Use logs from running ```matterbridge -debug``` if possible.
Output is just:
```
INFO[2018-02-15T09:41:05+01:00] Enabling debug                               
INFO[2018-02-15T09:41:05+01:00] Running version 1.7.1 0f5274f                
2018/02/15 09:41:05 toml: type mismatch for config.Protocol: expected table but found string
```

### Any steps to reproduce the behavior?
Download go and setup `$GOPATH`. Download and place matterbridge-linux-amd64 (v1.7.1) in `$GOPATH/bin`. Setup Discord bot and run config (with your own token).

### Please add your configuration file 
```
[irc]
Server="irc.server.com:6667"
Charset="utf-8"
Nick="bridge"

[discord]
Server="My Server"
Token="sometoken"

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="irc"
channel="#somechannel"

[[gateway.inout]]
account="discord"
channel="general"
```

**Comment by 42wim** [comment]
Please follow the configuration on https://github.com/42wim/matterbridge/wiki/How-to-create-your-config

The irc, discord and gateway configurations are not correct, should be something like below

```
[irc.myirc]
Server="irc.server.com:6667"
Charset="utf-8"
Nick="bridge"

[discord.mydiscord]
Server="My Server"
Token="sometoken"

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="irc.myirc"
channel="#somechannel"

[[gateway.inout]]
account="discord.mydiscord"
channel="general"
```
