### ISSUE TITLE
Slack join messages sometimes using empty value

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#372]
Related to: https://github.com/42wim/matterbridge/issues/276

Slack recently made some changes where "username" (which was mandatory and unique) is replaced with something called "display name" (which is optional). If display name is not provided, then a the full name is used (for display and for auto-complete).

Seems that the join messages that come from Slack are missing an identifier when display name isn't provided. On the other end of the bridge, the full name would be used there.

![screenshot of empty username](https://imgur.com/2rprWuc.png)

Will dig in later

**Comment by 42wim** [comment]
Should be fixed now in master
