### ISSUE TITLE
cannot sent user_action to api endpoint

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#374]
### Environment

Version: 
`version: 1.7.2-dev`

Operating system:
- Windows 10 LTSB, build 1709
- Manjaro
- archlinux

go version go1.9.4 windows/amd64
f58be0d1c1236a6a07a6917f3258a5608e1364f8

### Please describe the expected behavior.

`curl -XPOST -H 'Content-Type: application/json'  -d '{"text":"test","username":"randomuser","gateway":"gateway1", "event": "user_action"}' http://localhost:4242/api/message`
should sent a /me message

### Please describe the actual behavior. 

the event parameter seems to have no effect, `user_action`  has no effect on the message that is sent,
neither has `join_leave` as a event

### Any steps to reproduce the behavior?

start matterbridge with this sample config (or similar.. it is really just a standard): https://github.com/elytra/MatterLink/blob/master/matterbridge-sample.toml

run 
```
curl -XPOST -H 'Content-Type: application/json'  -d '{"text":"test","username":"randomuser","gateway":"minecraft", "event": "user_action"}' http://localhost:4242/api/message
```

### Please add your configuration file 

https://github.com/elytra/MatterLink/blob/master/matterbridge-sample.toml

**Comment by 42wim** [comment]
Ok this works now.
The output you get back now contains more fields (the same as every other protocol has)

**Comment by NikkyAI** [comment]
what do you mean with 
> the output you get back
containing more fields ?

**Comment by 42wim** [comment]
If you sent a request to the API you'll get a JSON message back.
This message will now have more fields (like an Event and a Timestamp and some others)
