### ISSUE TITLE
2 "parallel" channels only show joins on one of them

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#375]
### Environment

Version: 1.7.2-dev

Operating system: Linux 4.14.11-1-ARCH

go version go1.9.3 linux/amd64
f2efc06d1ffaef74407bcb1bdff33bcaf6c52dfe

### Please describe the expected behavior.

joining on irc channel `#matterlink` and `#ruby`
i expect to see the join messages on discord on both channels

### Please describe the actual behavior. 

only on the ruby channel on discord join messages are shown

https://gist.github.com/NikkyAI/c2ba5ece73a2542c9c608ea9efd2b85e#file-matterbridge_debug-log

### Please add your configuration file 

https://gist.github.com/NikkyAI/c2ba5ece73a2542c9c608ea9efd2b85e#file-matterbridge-toml

**Comment by 42wim** [comment]
Possible a race condition ? gateways didn't start completely before the JOIN_LEAVE event happened.

```
DEBU[2018-02-20T19:52:29+01:00] Sending JOIN_LEAVE event from irc.esper to gateway  module=irc
INFO[2018-02-20T19:52:32+01:00] discord.obsidian: joining ruby (rubydiscord.obsidian)
INFO[2018-02-20T19:52:32+01:00] Gateway(s) started succesfully. Now relaying messages
```

**Comment by NikkyAI** [comment]
i could reproduce it even when waiting a lot longer.. i will do it again to get the log

**Comment by NikkyAI** [comment]
https://gist.github.com/NikkyAI/c2ba5ece73a2542c9c608ea9efd2b85e#file-matterbridge_debug-log
tried again, made sure the gateways sarted before joining

**Comment by NikkyAI** [comment]
maybeit has to do with discord.obsidian that is set to not show join/part

**Comment by 42wim** [comment]
No shouldn't be the issue, I don't see a JOIN message from #matterlink in your log though.

I've added more debugging, so that we can see the complete message that get sent.
Add the option ´DebugLevel=1` to your `[irc]` configs, this will also show the native IRC commands/output

Don't forget to update from master

**Comment by NikkyAI** [comment]
updated to master again and enabled DebugLevel=1 in the irc
https://gist.github.com/NikkyAI/c2ba5ece73a2542c9c608ea9efd2b85e

**Comment by 42wim** [comment]
mixedcase issue for events (sigh) :-)
should be fixed now

**Comment by NikkyAI** [comment]
fix confirmed
