### ISSUE TITLE
samechannelgateway stops working when bridges are n>2

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#376]
Perhaps related to similar issue on regular gateway: https://github.com/42wim/matterbridge/issues/342

Logs: https://gist.github.com/patcon/f2d51b705f3a09397e423e1f585e69fc

Sorry, in a rush, but will try to add more details later! :tada:

**Comment by 42wim** [comment]
Yes, did it ever work, or did it stop working at a specific matterbridge version ?
And what exactly doesn't work :-)

**Comment by patcon** [comment]
haha this is my worst issue. pay no attention yet! i may close it if I figure out issue lies elsewhere

**Comment by 42wim** [comment]
is this still an issue? otherwise I'm going to close this
