### ISSUE TITLE
[Feature] MessageDelay option on other networks then just only IRC

### ISSUE THREAD

**Issue by TomTheDragon** [42wim/matterbridge#377]
I did some experiments with other networks over XMPP transports and i noticed that some of them have problem handling too many messages at once.
So it would be nice if we had the ability to delay them on other networks (like XMPP) as well.

**Comment by 42wim** [comment]
If you want to do ratelimiting like on IRC, this can be done using tengo scripts

```
times := import("times")
times.sleep(times.parse_duration("2s"))
```
You'll need to put this in the `OutMessage`, more info on https://github.com/42wim/matterbridge/wiki/Tengo
