### ISSUE TITLE
Config file lacking closing quotes

### ISSUE THREAD

**Issue by ishitatsuyuki** [42wim/matterbridge#38]
This one:
`RemoteNickFormat="[{BRIDGE}] <{NICK}>`
seems to lack a closing quote.

**Comment by ishitatsuyuki** [comment]
Additionally, making it `{PROTOCOL}` makes the migration smoother.

**Comment by ishitatsuyuki** [comment]
Forgot one more:
Correct: `NickFormatter="plain"`
Invalid TOML: `NickFormatter=plain`

https://github.com/42wim/matterbridge/blob/0d4bad16a349afcfc4fc890098dc19fc3e20de19/matterbridge.toml.sample#L164

**Comment by 42wim** [comment]
Fixed, thanks for reporting and testing btw!
