### ISSUE TITLE
Edits in telegram are posted as new text in discord

### ISSUE THREAD

**Issue by ManuelSchneid3r** [42wim/matterbridge#380]
Sideissue: Shrink your bug report template text.

<hr>

Version: version: 1.7.2-dev
Operating system: Ubuntu 16.04.3 LTS 
go version go1.6.3 linux/amd64

### Please describe the expected behavior.
Editing posts in telegram edits the posts in discord too.

### Please describe the actual behavior. 
Edits in telegram are posted as new text in discord.

### Any steps to reproduce the behavior?
Edit post in telegram.

**Comment by 42wim** [comment]
I don't use telegram myself so I depend on input from you.
Could you run with `-debug`

1) Send a message on telegram
Look for a debug message like below
`[0015] DEBUG telegram:      Receiving message .... ` 

2) Edit the message on telegram
Look again for the same debug message

Paste those 2 messages here

(About the side issue, feel free to post a PR with a better template)
