### ISSUE TITLE
IRC wont receive messages if the name isn't alpha-numeric

### ISSUE THREAD

**Issue by UclCommander** [42wim/matterbridge#381]
### Environment

Version: 1.8 linux-amd64

Operating system: Ubuntu server 16.04

### Please describe the expected behavior.

Messages should relay between Discord and IRC.

### Please describe the actual behavior. 

Discord is getting message from IRC as expected. But messages wont go _from_ Discord _to_ IRC. I've somewhat traced the issue down to _both_ the channel name in the config, _and_ the channel name on IRC must be lowercase/alpha-numeric. This appears to be happening to my engineering channel too, that one is all lowercase, but there's a period in the channel name. Testing it with an all lowercase alpha-numeric channel name works as expected (like `#dev` or `#testing123`). Dropping and re-registering the channels to be all alpha-numeric isn't something I'd prefer to do (or have permission to, in some cases).

### Any steps to reproduce the behavior?

Connect bot to Discord.

Connect bot to an IRC channel with a that isn't lowercase alpha-numeric. (eg. `#Testing`, `#testing.123`)

### Please add your configuration file 

```
[discord]
[discord.mydiscord]
Token=""
Server="The Shed"
RemoteNickFormat="[{NICK}] "
UseUserName=true
ShowJoinPart=true

[irc]
[irc.byteirc]
Server="irc.byteirc.org:6697"
Nick="Discord"
UseTLS=true
MessageSplit=true
RemoteNickFormat="[{NICK}] "

[[gateway]]
name="main"
enable=true
    [[gateway.inout]]
    account="discord.mydiscord"
    channel="ID:230427196915712010"
    [[gateway.inout]]
    account="irc.byteirc"
    channel="#uclcommander"

[[gateway]]
name="engineering"
enable=true
    [[gateway.inout]]
    account="irc.byteirc"
    channel="#ucl.engineering"
    [[gateway.inout]]
    account="discord.mydiscord"
    channel="ID:258686981477892098"


```

**Comment by 42wim** [comment]
Can not reproduce this.
Could you please show output of `matterbridge -version` ?

**Comment by UclCommander** [comment]
`version: 1.8.0 222cccf`

**Comment by 42wim** [comment]
I've almost literally tried your config, even on byteirc
I can not reproduce this with 1.8.0 

Please run with `-debug` and do your test again
Are you sure the channel isn't muted and the bot needs te be voiced ?

**Comment by lrstanley** [comment]
```
17:44:50 Channel mode set to: -m by @ UclCommander
```
Believe that was the issue the other day. Think this can be closed unless @UclCommander is still having issues.

**Comment by 42wim** [comment]
Thanks for the update @lrstanley
