### ISSUE TITLE
[Feature] ability to disable sending join/leave messages to other gateways

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#382]
when your intention is to only see join/leave messages from specific services and display them on eg. irc but do not want to have join/leave messages from irc pollute chat, the current configuration options fall short

i suggest `displayJoinLeave` for  the incoming event (from the gateway)
and `sendJoinLeave` to control sending the event to the gateway

**Comment by 42wim** [comment]
Well, there is already `ShowJoinPart` which does the same as `displayJoinLeave` I think?

**Comment by NikkyAI** [comment]
thzat sounds reasonable and in line with the expected default behaviour, after all its something you only want to touch and disable in special cases

**Comment by 42wim** [comment]
Ok, try master :)

**Comment by NikkyAI** [comment]
works like a charm
