### ISSUE TITLE
[Slack] Regression: Users are shown as machine ID instead of display name

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#384]
Re-ticketed from: https://github.com/42wim/matterbridge/issues/379

Since v1.8.0, there's been a regression that's resulting in this:

![screenshot](https://imgur.com/29Btw12.png)

This is current as of https://bintray.com/42wim/nightly/Matterbridge/v1.8.0-32-g79c4ad5#files

**Comment by patcon** [comment]
Confirmed that nothing in `nlopes/slack` related to profiles or usernames seems to have changed... this is quite confusing

**Comment by patcon** [comment]
When it's later in the day, I'll go through and deploy each nightly, and see where the regression arrived :)

(Just don't want to do it through day when bridge is in high use...!

**Comment by patcon** [comment]
Confirmed that regression arrived in nightly build 26: https://bintray.com/42wim/nightly/Matterbridge/v1.8.0-26-g6a727b9

Not present in build 12: https://bintray.com/42wim/nightly/Matterbridge/v1.8.0-12-g82396e7

https://imgur.com/MEm75Z6

**Comment by patcon** [comment]
Thanks! I'll give it a shot tomorrow from the nightly (I really need to more comfy with go builds!)

You're the best, @42wim! -- fwiw, the change you made is not one that seemed affected in the more generous period of the regression introduction (ie. the earliest commit on feb 24 and last one on feb 27):
https://github.com/42wim/matterbridge/compare/63b88e77f20e2869d3c9bf136a0c9fa84980ca69...20dbd713068347ba9a025e02fb0a101e07e6982c

**Comment by 42wim** [comment]
I've found the issue :)
Maybe the usergroup thing is now also fixed. I was replacing html stuff before the replaceMention/replaceVariables 

Try https://bintray.com/42wim/nightly/Matterbridge/v1.8.0-38-g8d2ce56#files

**Comment by 42wim** [comment]
It was introduced in https://github.com/42wim/matterbridge/commit/1578ebb0e2d8cc90b84a42b90205c5f1a9b69b08 I've refactored a lot

**Comment by patcon** [comment]
Yeeeeeooow! Seems like it's pretty much fixed aside from a rando extra "@" on usergroups -- thanks wim!

![screenshot](https://imgur.com/k2lCaby.png)
