### ISSUE TITLE
[Regression] Slack <=> Slack: ShowJoinPart no longer working as expected

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#389]
:wave: 

Observed: When I invited configured `ShowJoinPart` on both ends, and invited someone into a room, I no longer see that they joined on the other end of the bridge.

Expected: Would expect it to be posted on the other end.

Thoughts? Logs show it went through, so a bit confused.

Deployed commit: https://github.com/42wim/matterbridge/tree/ab94b5ca7af0b5b4ca9bebfa16f80f93a5d6c76c

Log: https://gist.github.com/patcon/48e4f9dc355f6bea2e8285a6a2a6ce0c#file-matterbridge-log-L5

Screenshot
![screenshot](https://i.imgur.com/Jjab11o.png)

config: https://github.com/edgi-govdata-archiving/matterbridge-heroku/blob/edgi/config/config-heroku-template.toml#L28-L50

**Comment by 42wim** [comment]
Should already be fixed in latest master by this commit https://github.com/42wim/matterbridge/commit/a284a228a32185e6b7af7459a2d69eb14d6516d9
I'm going to close it, if I'm wrong feel free to reopen :)

**Comment by patcon** [comment]
Yep, confirmed it's back :) As always, you are a saint, wim!
