### ISSUE TITLE
Slack slash commands that use attachments don't populate the user who initiated the command

### ISSUE THREAD

**Issue by jheiselman** [42wim/matterbridge#393]
### Environment
Version: 1.9.0

Operating system: linux/amd64

### Please describe the expected behavior.
When a Slack user runs a slash command that returns a message with an attachment (i.e. /giphy), the bridge should relay the original user name of the person who ran the command instead of the Slack app's user.

### Please describe the actual behavior. 
When a Slack user runs a slash command that returns a message with an attachment (i.e. /giphy), the Slack message handler determines the user name improperly. It fills in the app name ("giphy" in this case) instead of the user who initiated the command.

### Any steps to reproduce the behavior?
In a bridged Slack/Discord, have a Slack user run "/giphy <anything>". When the message is posted to Discord, observe that the username is reported as "giphy" instead of the user.

### Please add your configuration file 
[general]
MediaDownloadSize=10485760

[discord.dudegroup]
Token=""
Server=""
RemoteNickFormat="{NICK}: "

[slack.dudegroup]
Token=""
RemoteNickFormat="{NICK} ({PROTOCOL})"

[[samechannelgateway]]
name="dg2dg"
enable=true
accounts = ["discord.dudegroup","slack.dudegroup"]
channels = ["dude_group"]

**Comment by 42wim** [comment]
Is merged, so let's close this
