### ISSUE TITLE
[Feature] Option to automatically convert webp files

### ISSUE THREAD

**Issue by TomTheDragon** [42wim/matterbridge#398]
Would be nice to have a option to automatically convert webp (common on Telegram) files to more common file formats before uploading them to the mediaserver/other bridged networks (like Discord). Because its nice to be able to see stuff like stickers on networks like IRC but youre then presented with a webp file, which is still a really uncommon file format + Discord for example usually wants to block them.

**Comment by 42wim** [comment]
What format should it convert too ?

**Comment by TomTheDragon** [comment]
PNG would be the best option with the least loss in quality and it also supports the transparent that's used in Telegram stickers for example but JPG would be nice as well, to save some space.
I guess the best way to do it, would be to add an option to choose between none, PNG and JPG.

**Comment by TomTheDragon** [comment]
Any news to this? It would also help reducing the storage requirement of the media server, since stickers could then (in PNG form) directly uploaded to networks like Discord.

**Comment by 42wim** [comment]
No, not yet. But this feature request may resolve it self as all the major browsers are going to support it (https://www.cnet.com/news/firefox-to-support-googles-webp-image-format-for-a-faster-web/) and discord probably will support it too.

**Comment by TomTheDragon** [comment]
Browser support will get better yes but this is not really a solution to this problem.
Could something like maybe help? https://github.com/pennello/go_webp2png

**Comment by 42wim** [comment]
It has been added in a PR, could you test https://bintray.com/42wim/nightly/Matterbridge/v1.14.0-rc1-7-gd44d2a5#files  ? and give feedback?
