### ISSUE TITLE
[slack] the IRC gw is going to be removed soon

### ISSUE THREAD

**Issue by lazyusername** [42wim/matterbridge#401]
Hello,

according to [this](https://it.slashdot.org/story/18/03/08/2049255/slack-is-shutting-down-its-irc-gateway) article (and [source](https://get.slack.help/hc/en-us/articles/201727913-Connect-to-Slack-over-IRC-and-XMPP)) slack is shutting down its IRC gateway.
I would like to kindly ask if matterbridge relays on this (= uses the IRC GW) for it's functionality or not.

If so, would you drop the slack support? If not, yaaay!

Thx for info. I didn't see any mention of this here so...

**Comment by jheiselman** [comment]
Matterbridge uses the official Slack API, not the IRC gateway. It will be uneffected by this.

**Comment by lazyusername** [comment]
Thx man a lot for SUPER FAST answer!

**Comment by jheiselman** [comment]
You're quite welcome. I really like this project and try to help out when and where I can.
