### ISSUE TITLE
[Feature] Option to msg every channel with a "connection going down" msg on eror

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#403]
I've experienced issues where people are losing faith in the bridge not because of any fault of the software, but because config errors or other app crashed (related to using unstable commit versions).

Would it be within scope, in recognition that the trust of end-users is important to software project success, to add a feature that could notify rooms when an error state is encountered?

In an ideal world, each person would be doing monitoring on the app itself, but I imagine this might not always be done.

Thanks!

**Comment by 42wim** [comment]
Yes, there already such a request #116 
It's not so easy to do (otherwise I already did this), because almost every library handles reconnects itself and don't have a status command.

If the app crashes, please send the stack logs so that those crashes can get fixed.
