### ISSUE TITLE
for Slack connections, RemoteNickFormat should be set to "{NICK}" by default

### ISSUE THREAD

**Issue by danhimalplanet** [42wim/matterbridge#404]
default RemoteNickFormat for Slack connections should be

RemoteNickFormat="{NICK}" 

if you don't set it to anything, the resulting message in Slack is prefaced with "<Slack API Tester>"

**Comment by 42wim** [comment]
It's in the wiki if you follow the create a slack config
https://github.com/42wim/matterbridge/wiki/Section-Slack-%28basic%29

But I'll add it to the FAQ too
Thanks for reporting!
