### ISSUE TITLE
ReplaceNicks is broken after 1.8.0

### ISSUE THREAD

**Issue by iprok** [42wim/matterbridge#407]
I use rocketchat <-> telegram bridge. I have
ReplaceNicks=[ ["iprok","Ivan"] ] in rocketchat section. It normally works in 1.8.0 (I have messages from "[rocketchat] <Ivan>" in telegram) and stop working after upgrading to 1.9.0 or 1.9.1 (I have messages from "[rocketchat] <iprok> in telegram) without any config change.

**Comment by 42wim** [comment]
Fixed in master now, thanks for reporting
