### ISSUE TITLE
telegram channel : panic runtime error

### ISSUE THREAD

**Issue by Kissagram** [42wim/matterbridge#410]
***matterbridge/bridge/telegram/telegram.go:157   rmsg.UserID = strconv.Itoa(message.From.ID)***

**message.From is not tested to be not null (it's tested just a few lines later..) and it seems to happen when the message is from a telegram channel (not a group)**

### Environment

Version: 1.9.1 and 1.9.2 dev

Operating system: windows / linux

### Please describe the expected behavior.
no panic crash :)

### Please describe the actual behavior. 

```
services_1  | 2018-04-29T12:16:13.221787570Z panic: runtime error: invalid memory address or nil pointer dereference
services_1  | 2018-04-29T12:16:13.221841033Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55962373c188]
services_1  | 2018-04-29T12:16:13.221850002Z 
services_1  | 2018-04-29T12:16:13.221856713Z goroutine 23 [running]:
services_1  | 2018-04-29T12:16:13.221878566Z github.com/42wim/matterbridge/bridge/telegram.(*Btelegram).handleRecv(0xc420407620, 0xc42043e5a0)
services_1  | 2018-04-29T12:16:13.221885887Z    /go/src/github.com/42wim/matterbridge/bridge/telegram/telegram.go:157 +0x238
services_1  | 2018-04-29T12:16:13.221892740Z created by github.com/42wim/matterbridge/bridge/telegram.(*Btelegram).Connect
services_1  | 2018-04-29T12:16:13.221899126Z    /go/src/github.com/42wim/matterbridge/bridge/telegram/telegram.go:40 +0x300
services_1  | 2018-04-29T12:35:26.064854891Z time="2018-04-29T12:35:26Z" level=info msg="Running version 1.9.2-dev 99ce68e" prefix=main
services_1  | 2018-04-29T12:35:26.064906561Z time="2018-04-29T12:35:26Z" level=info msg="WARNING: THIS IS A DEVELOPMENT VERSION. Things may break." prefix=main
services_1  | 2018-04-29T12:35:26.065654731Z time="2018-04-29T12:35:26Z" level=info msg="Parsing gateway gateway2" prefix=gateway
services_1  | 2018-04-29T12:35:26.065668839Z time="2018-04-29T12:35:26Z" level=info msg="Parsing gateway gateway1" prefix=gateway
```
### Any steps to reproduce the behavior?
bridging a telegram channel [!!nota group]  (bot is admin of the channel) to a discord channel (only the bot can write in this channel)

### Please add your configuration file 

problem occurs from gateway2, where the gateway.in are channels
```
[discord.mydiscord]
Token="*************************************************************

Server="***********"

RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
EditSuffix=" (edited)"

[telegram.mytelegram]

Token="****************************************"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="telegram"

[[gateway.inout]]
account="telegram.mytelegram"
channel="***********0"


[[gateway]]
name="gateway2"
enable=true

[[gateway.out]]
account="discord.mydiscord"
channel="signals"

[[gateway.in]]
account="telegram.mytelegram"
channel="**********1"

# channel test
[[gateway.in]]
account="telegram.mytelegram"
channel="**********2"
```

**Comment by 42wim** [comment]
Thanks for reporting!
Fixed now, could you retry from master? 
dev binaries will soon be available from https://bintray.com/42wim/nightly/Matterbridge/_latestVersion

**Comment by Kissagram** [comment]
thanks for the quick update !
i don't get the panic anymore but strangely the channel post seems not to be handled ..
i got this error message
```
services_1  | 2018-04-29T16:03:04.274914949Z time="2018-04-29T16:03:04Z" level=error msg="Getting nil messages, this shouldn't happen." prefix=telegram
```
here is the 2 kind of messages i got in updates : 
seems all fine to me when i look at the telegram go api, it should handle the "channel_post" and not display the message above...
```
{"ok":true,"result":[{"update_id":477220834,
"message":{"message_id":17711,"from":{"id":343696465,"is_bot":false,"first_name":"Test","username":"test"},"chat":{"id":-123456789,"title":"Test Group","username":"testgroup","type":"supergroup"},"date":1525027605,"text":"test message group"}},{"update_id":477220835,
"channel_post":{"message_id":22,"chat":{"id":-987654321,"title":"testchannel","type":"channel"},"date":1525027615,"text":"test message channel"}}]}
```

does anyone have already bridge a telegram channel ? :p

**Comment by Kissagram** [comment]
oh wait, i may got this message because i edited some of the messages in the channel.

but the early exit code should not skip the message in those cases
```
if update.Message == nil && update.ChannelPost == nil {
			b.Log.Error("Getting nil messages, this shouldn't happen.")
			continue
		}
```
i would suggest 
```
if update.Message == nil && update.ChannelPost == nil && update.EditedMessage  == nil && update.EditedChannelPost == nil {
```
if you want to test it correctly.

nevertheless, i don't get my channel message to the bridge, this is because ```rmsg.Text````is set only if there is a "From" which does not occur in a channel (as we have previously seen whit the panic crash in the beginning of this thread :D...

my suggestion would be to add it directly here : 
```
		// handle channels
		if update.ChannelPost != nil {
			message = update.ChannelPost
                         rmsg.Text += message.Text // <=== ADD THIS LINE
		}
```

yes i could have made a pull request, but i'm too lazy :D

**Comment by Kissagram** [comment]
@42wim 
there is still a memory crash line 232 where "From" is still accessed.
don't know if you absolutely need an avatar or not, so i guess you will better fix it than me

**Comment by 42wim** [comment]
@Kissagram thanks, fixed in master!
