### ISSUE TITLE
Issue with bridging from Telegram

### ISSUE THREAD

**Issue by CitizenMJ** [42wim/matterbridge#411]
### Environment

Version: 1.9.1

Operating system: Windows 7 Home Premium

### Please describe the expected behavior.
I made two gateways; one that bridges between IRC and discord, and one that _should_ bridge between IRC and Telegram.
 

### Please describe the actual behavior. 

It doesn't bridge from Telegram to IRC.

### Any steps to reproduce the behavior?
See the configuration file

### Please add your configuration file 

[irc]
	[irc.irc1]
	Server="irc.rizon.net:6667"
	Nick="SarahBot"
	RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[discord]
	[discord.discord1]
	Token="blahblah"
	Server="ID:341549110677078016"
	RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[telegram]
	[telegram.telegram1]
	Token="blah"
	RemoteNickFormat="[{PROTOCOL}] <{NICK}> " 

[[gateway]]
	name="gateway1"
	enable=true

[[gateway.inout]]
	account="irc.irc1"
	channel="#channel"

[[gateway.inout]]
	account="discord.discord1"
	channel="ID:360843589930188800"
	
	
[[gateway]]
	name="gateway2"
	enable=true

[[gateway.inout]]
    account="telegram.telegram1"
    channel="-265029826"

[[gateway.inout]]
	account="irc.irc1"
	channel="#channel2"

Thanks in advance.

**Comment by CitizenMJ** [comment]
Telegram bot was configured incorectly. Sorry for spamming

**Comment by gboulard** [comment]
the doc should probably specify the telegram bot option to set :

pm @BotFather
/setprivacy
DISABLE

(i guess it was your problem here ^^)
