### ISSUE TITLE
Add ".rtf" to filenames when sharing a slack post to discord.

### ISSUE THREAD

**Issue by sbrow** [42wim/matterbridge#412]
I write a lot of slack posts, and while they do get shared to discord, the filename doesn't get an rtf extension, even though they are .rtf files. This means that some users need to add the extension themselves after downloading the file before they can open it. Would it be possible to add ".rtf" to filenames of Slack posts when they get shared to discord? I briefly tried to make these modifications myself, but to no avail. Thanks in advance!

**Comment by 42wim** [comment]
So when you upload those files they have a .rtf extension?
Could you run matterbridge with `-debug` and upload such a file and paste the debug output here or on pastebin

**Comment by sbrow** [comment]
They aren't uploaded, per se. You have an option to "make" posts in slack. It's got its own little document creator. The posts get passed to discord as rtf files, but without any extension. I tried adding ".rtf" to the filename when I created a post, but the dot gets replaced with an underscore.

**Comment by 42wim** [comment]
Well, it does not look like rtf files. It's something only slack can read. (consists of json).
(do you have any pointer about those files being rtf files?)
 
So it doesn't seem possible to have discord show these. Except by maybe making a public URL of those and adding the link to discord. I'll have to look into that

**Comment by sbrow** [comment]
Discord links the posts for me automatically when I share them in slack. They show up as files with no extension. Maybe they're not pure rtf, but if you add an rtf extension they work fine.

**Comment by 42wim** [comment]
Well, I just created a post, saved it to disk, gave it a rtf extension and opened it up. Is this the same thing you see ?

![image](https://user-images.githubusercontent.com/1810977/39956291-b2e01936-55dd-11e8-8907-ed31e509cee5.png)

**Comment by sbrow** [comment]
I feel like I'm being gaslighted by slack. I swear those files were in rtf format a few months ago, but I went back and checked discord, and they're now in json format.

In any case, it's clearly a moot point now. Thanks for the responses, and I'm sorry for wasting your time.
