### ISSUE TITLE
[Feature] Include the re:@user when using the QuoteDisable option 

### ISSUE THREAD

**Issue by derram** [42wim/matterbridge#413]
Dropping the quotes has cleaned things up quite a bit (thanks again), but telegram users have a tendency to respond to messages that are hours old so including the username of the person they're responding to would help with context.

Bonus points if you can have it replace the name of the bridge with the actual user who sent the text.

**Comment by 42wim** [comment]
Not going to make this an extra option.
Instead I'm thinking about a QuoteFormat option, so you can specify the quote stuff like you want.

**Comment by derram** [comment]
Working great, thanks again!

Any chance of getting it to replace the bridge name with the username when quoting something from the bridge?

**Comment by 42wim** [comment]
Can't `NickFormat` do that for you ?
Or could you give an example of the issue?

**Comment by derram** [comment]
![selection_304](https://user-images.githubusercontent.com/5730335/39958830-da0f8e8e-55cd-11e8-8f16-8718d63b8637.png)

![selection_305](https://user-images.githubusercontent.com/5730335/39958833-df74cb46-55cd-11e8-9ad2-2702f7b40b04.png)

The bridge's name is being used instead of the username of the person who sent the message.

**Comment by derram** [comment]
Should I open a new feature request for this last bit, it's still nearly impossible to tell who a telegram user is responding to when they quote a message from the bridge.
