### ISSUE TITLE
[Feature] Receiving end muting.

### ISSUE THREAD

**Issue by derram** [42wim/matterbridge#414]
Currently all muting is done on the sending end, this works well enough but is limited.

Someone in my chat set up a bot to grab and post telegram uploads via the discord URL generated by the bridge:

![selection_194](https://user-images.githubusercontent.com/5730335/39656611-c8c78ddc-4fc6-11e8-92be-aa088eaccbd0.png)

It's a decent workaround to prevent the issue with the telegram key, but it has to be muted from sending from IRC to prevent the other bridges from seeing a double post. The downside is, users on platforms such as steam chat don't see the link or the original post.

**Comment by 42wim** [comment]
Can't you use `IgnoreNicks` setting in IRC to not relay messages from this irc-bot?

Another option is using the media-upload server so that it's get uploaded to your own server which can be visible on all bridges (https://github.com/42wim/matterbridge/wiki/Mediaserver-setup-%5Badvanced%5D)

**Comment by derram** [comment]
Yes, and I've already have it muted in that way but I was hoping for a way to still be able to send the messages to some platforms without it being sent to others.

I'll look into the media server, but it adds a bit of risk that I'm not very comfortable with.

**Comment by derram** [comment]
One problem I've run into so far is the bridge isn't relaying the media server links to steam.

**Comment by 42wim** [comment]
Yes, steam didn't get much love from me, so not everything is implemented there.
I just fixed the relaying stuff, so if you rebuild or use the latest dev builds (https://bintray.com/42wim/nightly/Matterbridge/_latestVersion) it should work

**Comment by derram** [comment]
Yep, links are being relayed now. Thanks again.

**Comment by 42wim** [comment]
As your issue is resolved, I'm going to close this
