### ISSUE TITLE
[Feature] Colored nicks on irc.

### ISSUE THREAD

**Issue by derram** [42wim/matterbridge#415]
Colored nicks on irc are a good way to distinguish different users at a glance since it breaks up walls of plain white text and just all around increases readability.

![selection_195](https://user-images.githubusercontent.com/5730335/39657034-d794e744-4fc9-11e8-91b3-2f2fca54f4f6.png)

This irc -> discord bridge has the option, but it's node so I dunno if that'll help: https://github.com/reactiflux/discord-irc

https://github.com/myano/jenni/wiki/IRC-String-Formatting

**Comment by 42wim** [comment]
Not a bad idea, but not high priority :)

**Comment by 42wim** [comment]
See #423
