### ISSUE TITLE
replace spaces in generated urls of filepaths to uploaded media with underscores

### ISSUE THREAD

**Issue by danhimalplanet** [42wim/matterbridge#416]
I have an image "Screenshot 1.png"

If I upload the image into a gateway, "Screenshot 1.png" is successfully uploaded to the media server I have specified in my matterbridge settings.

in the irc end of the gateway, for example, the generated url is

https://uploadserver/Screenshot 1.png

The space in the URL causes the entire URL to not be parsed correctly by some terminals, like Iterm2 on a mac.

It would be correctly parsed if the generated url was:

https://uploadserver/Screenshot_1.png

**Comment by 42wim** [comment]
Good catch! thanks for reporting. 
Fixed in master
