### ISSUE TITLE
Telegram messages lose text notes when passing media server links

### ISSUE THREAD

**Issue by derram** [42wim/matterbridge#420]
**Describe the bug**
Only the image link is passed through.

**To Reproduce**
Include text when uploading an image via telegram

**Expected behavior**
Both image link and text message should be passed

**Screenshots/debug logs**
Use logs from running `matterbridge -debug` if possible.

![selection_297](https://user-images.githubusercontent.com/5730335/39718763-e44dbada-51fc-11e8-8168-137bc83e3e42.png)

![selection_299](https://user-images.githubusercontent.com/5730335/39718887-40004d7a-51fd-11e8-9d05-bf6238637bff.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Matterbridge version: version: 1.9.2-dev 346a728

**Comment by 42wim** [comment]
To fix this I'll need a `-debug` log when you're uploading an image and adding a note, so that I know which field is used for the note. 
Don't forget to remove your token in the log.

**Comment by 42wim** [comment]
Hm, ok this has already been fixed in a newer commit than the one you're using :)
https://github.com/42wim/matterbridge/commit/72ce7f06e9bfc2a665f034f4099ed6eb79637f5c

Please upgrade to latest master.

**Comment by derram** [comment]
Yep, that got it. Thanks again!
