### ISSUE TITLE
Sync Avatars

### ISSUE THREAD

**Issue by benrob0329** [42wim/matterbridge#422]
**Is your feature request related to a problem? Please describe.**
Currently, Avatars are not synced between platforms. For example, getting the avatar from Matrix/XMPP and applying it to the webhook in Discord, or vice versa (For Matrix this would mean having many bot users, and XMPP woudl probably mean having to host the MUC as a transport)

**Describe the solution you'd like**
Avatars to be gotten from the host platform, and applied where supported on the bridged platform.

**Additional context**
XMPP has a few XEPs for Avatar Support, the most common being [Vcard Based Avatars](https://xmpp.org/extensions/xep-0153.html) which is generally synced with the newer [XEP-084](https://xmpp.org/extensions/xep-0084.html) by the server. Anonymous rooms would be best as bot users can just be nicks with avatars as far as the clients know. Matrix would need to use the Appservice API (talked about in another issue).

**Comment by 42wim** [comment]
Wel avatars syncing is done for bridges that have support for it.
See https://github.com/42wim/matterbridge/wiki/Features#username-and-avatar-spoofing
But XMPP and matrix are not supported.

About XMPP, I think you can better open a feature or PR for this upstream at https://github.com/mattn/go-xmpp

**Comment by ValdikSS** [comment]
Multiple MUC usernames from a single JID won't allow you to use different avatars, since vcard queries are (AFAIK) proxied to the JID, not to exact nickname.

**Comment by 42wim** [comment]
Going to close this as this should be fixed in the xmpp library.
