### ISSUE TITLE
Join non own server [Discord]

### ISSUE THREAD

**Issue by thundergreen** [42wim/matterbridge#426]
Dear all,

i am trying to connect to a server / channel I am actually in. I want to bridge this discord channel to a muc but it does not work. Is it possible to connect to a server which is not mine?

**Comment by derram** [comment]
You need permissions on the server to be able to join the bot, if you're allowed to here's how you do it:

Click on the bot here: https://discordapp.com/developers/applications/me

Click the "Generate OAUTH" button, copy the URL and paste it into your address bar, open the page and you'll see the drop down menu for adding the bot to any server you have permissions on.

**Comment by 42wim** [comment]
@derram thanks for the answer, I've added it to the [FAQ](https://github.com/42wim/matterbridge/wiki/FAQ#can-i-join-the-bot-to-a-server-i-dont-own-)
