### ISSUE TITLE
[REQUEST] Dynamic IconURL

### ISSUE THREAD

**Issue by hipio** [42wim/matterbridge#43]
I would like to be able to have a dynamic IconURL like the Slack-IRC bot has (https://github.com/ekmartin/slack-irc, `"avatarUrl": "https://robohash.org/$username.png?size=48x48"`). I use this function to grab custom avatars of users that are on IRC. 

I didn't see anything that suggests that this feature already exists so I'm hereby requesting it. I would be more than enough if I could use the `{NICK}` syntax in the `IconURL` variable.

**Comment by 42wim** [comment]
For slack you can now use eg
```IconURL="https://robohash.org/{NICK}.png?size=48x48"``` but ```PrefixMessagesWithNick``` has to be false otherwise it won't work.

**Comment by hipio** [comment]
Thanks a lot @42wim!
