### ISSUE TITLE
IRC lost connection without reconnect or any log

### ISSUE THREAD

**Issue by envsh** [42wim/matterbridge#431]
**Describe the bug**
After running hours, IRC lost connection without reconnect or any log.
I have 17 irc connection when startup. one night later, there are only 10 connection.
I'am use matterbridge to connect to znc-1.7, connect login and receive/send message are all fine when startup.

**To Reproduce**
Here I startup and only wait hours, it can always reproduced.

**Expected behavior**
1. reconnect and keep connection
2. or leave some log if any other problem

**Screenshots/debug logs**
Enabled debug, but don't find any related logs, I think.

**Environment (please complete the following information):**
 - OS: [linux]
 - Matterbridge version: 1.9-1.10, a month or more
 - If self compiled: yes

**Additional context**
 
[general]
RemoteNickFormat="[{NICK}@{PROTOCOL}] "
StripNick=false
DebugLevel=9

[irc]
    [irc.freenode00]
    Nick="mynick00"
    Password="xxxxxx"
    Server="127.0.0.1:16667"
    ShowJoinPart=true

**Comment by envsh** [comment]
another info:
before update to 1.9-1.10, I use 1.3-dev before switch to girc, it's works fine. not this problem.
and I tested every commit, and found the switch to girc commit cause this problem. maybe the switch not keep all previous feature, but bring out new problem.

**Comment by 42wim** [comment]
You've got 17 irc bridges ? on 17 different networks/servers  ?
Could you try the latest matterbridge from master ? 
I've updated the vendored girc 14 days ago and let me know if the problem still exists ?

**Comment by envsh** [comment]
think as 17 accounts, 17 connections, not so many different networks/servers

**Comment by 42wim** [comment]
any updates ? is it more stable now?

**Comment by envsh** [comment]
I'am updated to upstream code base(a week ago, not this 1.10.1), but still has the same problem.
Thinking make a standalone test environment.

**Comment by 42wim** [comment]
maybe @lrstanley can help? :)

**Comment by lrstanley** [comment]
@envsh does matterbridge actually print `reconnecting in 30 seconds...`? If not, then it could be two different things.

   1. There is a bug in girc, in which it would be useful to get the exact debug logs from right before it stopped functioning (maybe some kind of network related issue, where girc doesn't properly know the network has been disconnected).
   2. Something on the network side is telling girc to disconnect. From looking at your matterbridge config, I see the server address you're using is `127.0.0.1:16667`. Is this some local proxy software? Some kind of network tunneling? As, the name is freenode, but that's clearly not freenode. :smile: 

For the latter, @42wim can you add logging here? Something to the extent of `Client requested close` or similar:

https://github.com/42wim/matterbridge/blob/91db63294ced789fbcd73cad07b592ec03812f1f/bridge/irc/irc.go#L127

@envsh FWIW, I have hundreds of girc-based instances running with over 100 days of uptime. The only potentially concerning stuff, @42wim, is this logic that should probably be handled within the other function handling reconnect logic (i.e. If a `QUIT` happens, `Client.Connect()` should in theory return `nil`):

https://github.com/42wim/matterbridge/blob/91db63294ced789fbcd73cad07b592ec03812f1f/bridge/irc/irc.go#L314-L318

**Comment by envsh** [comment]
`127.0.0.1:16667` is a znc-1.7 bouncer, no ssl for znc's clients, here is matterbridge.
I recheck the znc's log, the lost connection's account receive messages fine.
But because my network is very not stable, znc's connections will often reconnect when timeout or other else error. And znc can always success reconnect to freenode server and keep connection count I configured.

For matterbridge's logs, I found several lines of logs from this line: https://github.com/42wim/matterbridge/blob/91db63294ced789fbcd73cad07b592ec03812f1f/bridge/irc/irc.go#L315. And these connections(accounts) works fine. (It's say, some cases reconnect is worked.)
But, for the lost connections(accounts), I found nothing log info. It's just disappeared.

**Comment by envsh** [comment]
`127.0.0.1:16667` is a znc-1.7 bouncer, no ssl for znc's clients, here is matterbridge.
I recheck the znc's log, the lost connection's account receive messages fine.
But because my network is very not stable, znc's connections will often reconnect when timeout or other else error. And znc can always success reconnect to freenode server and keep connection count I configured.

For matterbridge's logs, I found several lines of logs from this line: https://github.com/42wim/matterbridge/blob/91db63294ced789fbcd73cad07b592ec03812f1f/bridge/irc/irc.go#L315. And these connections(accounts) works fine. (It's say, some cases reconnect is worked.)
But, for the lost connections(accounts), I found nothing log info. It's just disappeared.

**Comment by lrstanley** [comment]
I suspect then that it is something specific to znc, because of the types of events it intercepts, and the types of mocked events it sends back to connected clients. I don't remember exactly, but znc may send a `QUIT` when the connection to `znc<->real irc server` fails. I can do some testing just in case, as I think I've only used girc with znc once. Though, I'd still recommend some reconnect logic here @42wim:

https://github.com/42wim/matterbridge/blob/91db63294ced789fbcd73cad07b592ec03812f1f/bridge/irc/irc.go#L127

The nil return for `Client.Connect()` is really only meant to tell the main application loop (or similar) that some other part of the client (or callback) requested a graceful quit from the server. This may not be desirable, given the type of application this is. May just want to reconnect in the event of _any_ kind of disconnect, graceful or not -- unless matterbridge lets users manually disconnect using commands (e.g. `!quit`).

Will poke znc + girc tomorrow and see if I can replicate with bad network conditions. Can submit a PR too for what I mentioned above as well.

**Comment by 42wim** [comment]
Thanks for looking into this @lrstanley really appreciate it. 👍 
A PR is always welcome of course.

**Comment by lrstanley** [comment]
https://github.com/42wim/matterbridge/pull/445 created to potentially address the odd `QUIT` issues you may be seeing with ZNC. FWIW, I wasn't able to replicate with 100+ connections to ZNC, and attempting to lose network connection, disconnecting ZNC from the IRC server, etc.. but it's possible you have a different ZNC configuration.

Unrelated, ZNC can't seem to keep up with that many girc connections all at the same connection time :stuck_out_tongue:. Took a few minutes for it to even pass girc all the events hah. I have a ZNC instance with over 100 regular network connections, and over 1000 IRC channels across all accounts, but darn..

ZNC connection stats:
![image](https://user-images.githubusercontent.com/1847365/41188948-b4c74612-6b94-11e8-9cbe-f938408d8b7e.png)
ZNC received IRC line stats (ignore huge spikes. metrics were down, so when they came back online, it was a huge spike of data):
![image](https://user-images.githubusercontent.com/1847365/41188951-c03123c4-6b94-11e8-9406-7db91b37566a.png)

**Comment by 42wim** [comment]
@envsh I've merged @lrstanley commit, could you see if this fixes your issue ?

**Comment by 42wim** [comment]
Going to close this because of lack of activity.
