### ISSUE TITLE
Avatar spoofing from Slack to Discord with uppercase in nick doesn't work

### ISSUE THREAD

**Issue by OyyoDams** [42wim/matterbridge#432]
**Describe the bug**
Avatar spoofing from Slack to Discord only works if nick is in lowercase.

**To Reproduce**
1. Make a webhook on Discord to allow nick and avatar spoofing
2. Configure a gateway between Slack and Discord
3. If nick on Slack is in lowercase, no issue. If there is an uppercase in nick, then the avatar is not spoofed.

**Expected behavior**
The avatar should be spoofed even it the nick has uppercases.

**Screenshots/debug logs**
![image](https://user-images.githubusercontent.com/8065973/40472562-15e88f8a-5f3a-11e8-871a-047a497cde08.png)

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: 1.10.0

**Additional context**
not needed

**Comment by 42wim** [comment]
Thanks for reporting and fixing! :)
