### ISSUE TITLE
Allow Slack channels to be specified by channel ID

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#436]
**Is your feature request related to a problem? Please describe.**
Channel IDs are more resilient than channel names when folks unknowingly rename them.

**Describe the solution you'd like**
Use regex pattern for channels (caps and starts with C, etc) to recognize when a channel is being specified, and check that instead of name.

Thanks!

**Comment by 42wim** [comment]
It's a bit more work then just using a regex pattern ;-)
For this feature I've chosen the same pattern as discord. 
So you'll have to specify `channel="ID:C123456"` instead of just `channel="C123456"`

Available in master

**Comment by patcon** [comment]
You're wonderful 42wim. fwiw, I'd been operating under the mistaken assumption for quite some time that the API would take both names and IDs, but realize that this was wrong :)

Thanks again for always being really humble, even when suggestions are silly or simplified!
