### ISSUE TITLE
RocketChat Webhooks on Sandstorm

### ISSUE THREAD

**Issue by spyjoshx** [42wim/matterbridge#438]
**Is your feature request related to a problem? Please describe.**
I'm trying to use this to bridge Discord and a Rocket.Chat grain in sandstorm [Sandstorm](https://sandstorm.io) There doesn't seem to be a way to get into the grain with matterbridge.
**Describe the solution you'd like**
Some kind of support for Sandstorm's WebKey system. [Webkey System](https://docs.sandstorm.io/en/latest/developing/http-apis/)
**Describe alternatives you've considered**
Not sure...
**Additional context**

**Comment by 42wim** [comment]
Sorry out of scope for matterbridge

**Comment by patcon** [comment]
@spyjoshx try generating and converting the sandstorm app webkey of `https://api.sandstorm.com#abcdef1234567890` into basicauth variant of `https://x:abcdef1234567890@api.sandstorm.com`

If this works, pls do update here and consider helping us document this somewhere in our wiki, where the next person in your shoes might find it :)

**Comment by spyjoshx** [comment]
@patcon thanks! I'll let you know if it works.
