### ISSUE TITLE
SSH-Chat <-> Discord: Links posted in discord are duplicated across the bridge back to discord

### ISSUE THREAD

**Issue by kfatehi** [42wim/matterbridge#439]
~~I can't figure out a reliable way to replicate this bug, but~~ it's apparent in the following screenshot (please excuse the foul language) in the red-outlined sections that the bridge is repeating messages in discord which contain links. Not sure how to investigate it further, but happy to assuming the bridge gets used. (Use case is to connect a mining rig OS command to a direct chat with those that would offer support from Discord).

![image](https://user-images.githubusercontent.com/175305/40692853-f330c740-6368-11e8-9a19-6b2668088478.png)

Making the issue in order to track this problem over time... if someone has a clue where to look to debug or diagnose this, please let me know!

**Comment by kfatehi** [comment]
I was able to figure out how to replicate this. It appears any time a link is posted, it causes this duplication... Here's another screenshot showing this:

![image](https://user-images.githubusercontent.com/175305/40692963-b34a1630-6369-11e8-892f-1c59e93b8d60.png)

**Comment by 42wim** [comment]
Cool, someone is actually using ssh-chat 👍

**Comment by 42wim** [comment]
The bug should be now fixed in master.
Can you retry building from master or using the dev build on https://bintray.com/42wim/nightly/Matterbridge/_latestVersion

**Comment by kfatehi** [comment]
![image](https://user-images.githubusercontent.com/175305/41190870-39b91c5a-6b9b-11e8-85d5-2a12b54b0364.png)

Thanks for the quick response, although this version seems to be somewhat buggier. Here is an invite to the discord server if you want to test it out.

The ssh server is 

`ssh -p 2022 app.chosn.run`

the discord room is https://discord.gg/Jd9S3A

**Comment by 42wim** [comment]
Hi, neither the discord invite or ssh works
I can't seem to reproduce the double messages either

**Comment by kfatehi** [comment]
@42wim sorry, bad timing, I'm between hosting providers at the moment. I'll update this thread again as soon as those issues are sorted, with a repro
