### ISSUE TITLE
Bridge should refrain from uploading htm/l files to the media server.

### ISSUE THREAD

**Issue by derram** [42wim/matterbridge#442]
This just seems like a huge security hazard and I didn't see a way to prevent in on the caddy plugin side.

![selection_215](https://user-images.githubusercontent.com/5730335/40881417-c3fc4b22-668b-11e8-942f-12989f3a880a.png)
![selection_216](https://user-images.githubusercontent.com/5730335/40881419-c719dd38-668b-11e8-8d96-68b9775652cc.png)

**Comment by derram** [comment]
Yes, displaying it is the problem because a malicious user could upload something bad enough to get a vps/domain provider to pull an account without appeal.

Using the mime setting would prevent me from setting my own index.html file to hide the file index as well, I believe.

**Comment by 42wim** [comment]
From the caddy docs.
```
By default, file listings are disabled and a request to a directory path (where no index file is present) will result in a 404 for obscurity reasons.
```

So you don't need to put an index file yourself

**Comment by 42wim** [comment]
Could you confirm if this fixes your issue ?
It would be handy to have an extension blacklist filter though.

**Comment by derram** [comment]
Maybe the upload plugin changes something because the file index was definitely visible before I set an index file.

Also I'm just using the caddy file from the media server setup documentation so I don't think it's anything in there.

**Comment by 42wim** [comment]
Oh, I see, if you used the documentation, please remove the `browse` command from your caddy config.
This will disable the index listing

**Comment by 42wim** [comment]
I've added an option to master so you can select which files can be blacklisted

```
#MediaDownloadBlacklist allows you to blacklist specific files from being downloaded.
#Filenames matching these regexp will not be download/uploaded to the mediaserver
#You can use regex for this, see https://regex-golang.appspot.com/assets/html/index.html for more regex info
#OPTIONAL (default empty)
MediaDownloadBlacklist=[".html$",".htm$"]
```

**Comment by derram** [comment]
Thanks again!
