### ISSUE TITLE
Telegram HTML messages should be htlm-escaped before sending

### ISSUE THREAD

**Issue by ValdikSS** [42wim/matterbridge#444]
**Describe the bug**
Matterbridge does not sanitize (escape, encode) relayed messages when HTML mode is activated for Telegram. Relayed message won't be shown if there are any problems with the message.

**To Reproduce**
1. Set `MessageFormat="HTML"`
2. Send the message with invalid HTML, for example just `><a>`
3. No message is sent to Telegram bridge

**Expected behavior**
User-supplied data is HTML-encoded, the message is visible in Telegram.

**Screenshots/debug logs**
`level=error msg="Bad Request"` from Telegram gateway.

**Environment (please complete the following information):**
 - OS: Linux
 - Matterbridge version: 1.10.1-dev

**Comment by 42wim** [comment]
If we HTML-escape the characters they won't be interpreted as actual HTML anymore, so that's an issue for people who actually send correct HTML
`<a href="http://www.example.com/">inline URL</a>` will become `&lt;a href=&#34;http://www.example.com/&#34;&gt;inline URL&lt;/a&gt;`

**Comment by 42wim** [comment]
Is maybe using `MessageFormat="Markdown"` an option? And setting the nick with markdown ?
See https://core.telegram.org/bots/api#markdown-style

**Comment by ValdikSS** [comment]
Yes, I switched to Markdown (it wasn't documented in matterbridge.toml.sample), but still decided to create this feature request.

**Comment by ValdikSS** [comment]
With markdown I can't send links with underscores, Telegram parses them as an italic text.

**Comment by 42wim** [comment]
I've just added support for MessageFormat="HTMLnick" 
Could you let me know if this works for you ?

**Comment by ValdikSS** [comment]
Works great, thanks a lot.
