### ISSUE TITLE
Issue with Mattermost 5.0

### ISSUE THREAD

**Issue by olivierlambert** [42wim/matterbridge#449]
Config worked and unchanged since a while (and Mattermost 4.x)

Just upgraded to Mattermost 5.0, and I got:

```
fatal msg="Starting gateway failed: Bridge mattermost.work failed to start: unsupported mattermost version: 5.0.0.5.0.0.22a75e2cc839d6aa62e1142e343a3a7d.false" prefix=main
```

Updating to the latest Matterbridge version got the same result.

**Comment by 42wim** [comment]
Mattermost 5.0 is just out, haven't got time to test it completely yet.
I've just added support to master, you can build your self or try dev binaries from here https://bintray.com/42wim/nightly/Matterbridge/v1.10.1-14-gec0e6bc#files

Only did the basic test and seems to work, please report back if you have any issues.

**Comment by olivierlambert** [comment]
It seems to work without issues, if any problem occurs, I'll let you know :+1:
