### ISSUE TITLE
Failing build on Debian

### ISSUE THREAD

**Issue by hipio** [42wim/matterbridge#45]
When running the command `go get github.com/42wim/matterbridge` I get the following error message:

``` golang
# golang.org/x/crypto/poly1305
go/src/golang.org/x/crypto/poly1305/poly1305_amd64.s:8 6a: No such file or directory: textflag.h
# github.com/gorilla/websocket
go/src/github.com/gorilla/websocket/client.go:361: unknown tls.Config field 'GetCertificate' in struct literal
# github.com/42wim/matterbridge/bridge/gitter
go/src/github.com/42wim/matterbridge/bridge/gitter/gitter.go:54: not enough arguments in call to b.c.JoinRoom
```

OS: Debian 8.6 
Go: go1.3.3 linux/amd64

---

I ran the same command on OSX and it worked just fine. That sounds like odd behaviour and maybe a problem with my Debian install. Not sure.

**Comment by 42wim** [comment]
You need at least go1.6
The Debian version is too old

**Comment by hipio** [comment]
Noted. Thanks @42wim. Will look into it and close this issue if this resolves my issue.

**Comment by hipio** [comment]
Worked. Thanks!
