### ISSUE TITLE
Matterbridge uses Mattermost usernames instead of nicknames

### ISSUE THREAD

**Issue by 3c7** [42wim/matterbridge#452]
**Is your feature request related to a problem? Please describe.**
Matterbridge uses Mattermost usernames instead of nicknames which is, depending on the user or nickname policy, sometimes confusing for people in the other chats.

**Describe the solution you'd like**
It would be cool if matterbridge uses the mattermost nicknames which can be changed easily through the users if necessary. Also the username could be the login name from different oauth providers.

**Describe alternatives you've considered**
-

**Additional context**
I tried implementing it myself, but I'm not familiar with 1.) Go and 2.) Mattermost internals, so I could not successfully change the username to nickname.
```go
func (m *MMClient) GetUserName(userId string) string {
	user := m.GetUser(userId)
	if user != nil {
		return user.Nickname // This should be correct, based on https://github.com/mattermost/mattermost-server/blob/master/model/user.go
	}
	return ""
}
```
I can provide a PR if someone can point me into the right direction and the change is welcome.

**Comment by 42wim** [comment]
Thanks for reporting and looking into this!
It needed some more changes, so that when a nick or username is changed, it's also updated.

**Comment by 3c7** [comment]
Thanks for implementing it. Now I definitely have to take a look into that commit. Tried so many things, but it didn't worked for me. :D
