### ISSUE TITLE
Discord posts edits as new message when configured with EditSuffix

### ISSUE THREAD

**Issue by Jaykul** [42wim/matterbridge#456]
**Describe the bug**
We set up `EditSuffix=" (edited)"` as a global value, but it broke the discord _output_ in that edits are no longer edits, but are posted as new messages. Before we added the EditSuffix, it was working (albeit a little confusing).

Discord -to> Slack: edits, and appends " (edited)"
Slack -to> Discord: generates new messages with " (edited)"

**To Reproduce**
Bridge Slack and Discord, and configure globally:
EditSuffix=" (edited)"

**Expected behavior**
The text " (edited)" would be appended to messages when they are edited, in addition to the user's message edit. **Exactly the way it already works to Slack**.

**Environment (please complete the following information):**
 - OS: linux (using _your_ docker image)
 - Matterbridge version: 1.10.1 (or newer)

**Comment by 42wim** [comment]
works as expected here, are you sure the message aren't old messages created before matterbridge started? 
Matterbridge can only edit messages it relayed itself

**Comment by Jaykul** [comment]
Yeah, very sure of that. I will re-test -- I see I'm a version behind.

**Comment by Jaykul** [comment]
Yep. My apologies. Restarting to pick up the new version resolved it. Sorry.

**Comment by Jaykul** [comment]
Incidentally, this is still happening. People just got used to it.

Also, we're getting these messages with " (edited)" on the end in IRC -- is there a way to disable sending edits just to IRC?

**Comment by Jaykul** [comment]
Seems to still be happening in 1.11.3 (docker image)

**Comment by 42wim** [comment]
wrt to discord I guess you're using webhooks ? Webhooks don't support editing
See https://github.com/42wim/matterbridge/wiki/FAQ#messages-not-being-edited-but-a-new-message-with-edit-appears-

wrt to IRC, you can only disable edits from the sending bridge
If you want to filter on the receiving bridge you can use `IgnoreMessages` eg `Ignoremessages="(edited)"`

I'm closing this again, if I'm wrong and you're using only a token and no webhook with discord, reopen again :)

**Comment by Jaykul** [comment]
Yeah, it's webhooks. I have both tokens and webhooks set up, but it's using webhooks so the user name can change. Thanks for clearing that up.

**Comment by patcon** [comment]
@jaykul, would you be open to creating a comparison table of of these config options in the wiki? It might help others make decisions :) we have a similar one for slack author options, if you're curious what I mean.

Anyhow regardless, thanks for filing the ticket!
