### ISSUE TITLE
[REQUEST] Share Public Links of files when using MatterHook

### ISSUE THREAD

**Issue by hipio** [42wim/matterbridge#46]
I'm currently able to share uploaded files from Mattermost to IRC through the API (Matterclient, right?), but I prefer using the MatterHook (Websockets) because it allows to me to set custom usernames and I'm able to use the (hopefully soon to be dynamic) `IconURL`-setting.

Is there anyway you guys could implement the public file link stuff in the MatterHook as well? It seems that someone has done it already (github.com/mattermost/platform/issues/2728#issuecomment-212551671), but my Go skills are to basic to do it myself.

I've tried by using the `GetPost` function, but someone I keep messing up and the Matterbridge keeps crashing with a pointer error and I have no idea how to even start debugging that.

**Comment by beuiot** [comment]
I second this. For now I have to choose between fancy usernames with icon or working shared public links, so I'd love to see it work with webhooks too!

**Comment by 42wim** [comment]
Sorry, I'm going to close this, this isn't something matterbridge can fix. 
Must be done at the mattermost side.
