### ISSUE TITLE
Ability to extract nick names from message text

### ISSUE THREAD

**Issue by genotrance** [42wim/matterbridge#466]
**Is your feature request related to a problem? Please describe.**
Some of the channels I'm on already have bridges so a message from user123 shows up as:

`FromGitter: <user123> hello world`

**Describe the solution you'd like**
I'd like to be able to extract user123 from the message and use that in `RemoteNickFormat`. So the message posted by matterbridge will look like this:

`user123: hello world`

Feature should ideally support multiple such manipulations since some of the channels have a Gitter, Discord and Matrix bridge already so the bot names are different.

**Describe alternatives you've considered**
No alternatives at this time. weechat allows some of this mangling via triggers.

**Comment by 42wim** [comment]
Well, you could probably do this with the `ReplaceMessages`

https://github.com/42wim/matterbridge/blob/93307b57aa830b0bfbf052264243f9e047b77089/matterbridge.toml.sample#L110-L120

So something like
`ReplaceMessages=[ ["FromGitter: ",""],["DiscordBot: ",""] ]`

**Comment by genotrance** [comment]
I just tried this and it doesn't work despite multiple tries. I put `ReplaceMessages` under the `[irc]` section since that's where the messages originate. I send them to Slack but nothing changes.

I should note that the irc user nick is `FromGitter` so I'm not sure `ReplaceMessages` really will work unless the nick is part of the message itself. And then too, I'm not sure if it is "FromGitter: message", "FromGitter message" or "FromGitter\tmessage" but i tried all three and none of them worked.

**Comment by 42wim** [comment]
Ok, right, you need `ReplaceNicks`

https://github.com/42wim/matterbridge/blob/51062863a5c34d81e296cf15c61140911037cf3b/matterbridge.toml.sample#L122-L125

`ReplaceNicks=[ ["FromGitter: ",""],["DiscordBot: ",""] ]`

**Comment by genotrance** [comment]
That doesn't work favorably either. Now, the message shows up as from "Slack API Tester". This is because nick is effectively blank after `ReplaceNicks`. The nick name and message are different fields and what we need is the ability to pull the actual nick name from the message and insert into nick field.

**Comment by 42wim** [comment]
https://github.com/42wim/matterbridge/pull/730 has been merged in master, this should fix your issue.

**Comment by genotrance** [comment]
This is working very nicely, thank you for the effort, makes the chat so much cleaner!
