### ISSUE TITLE
Support telegram channel names for public groups

### ISSUE THREAD

**Issue by slimit** [42wim/matterbridge#467]
**Describe the bug**
Telegram API seems to be changed to only support channel names for public groups.

**Expected behavior**
We should be able to mention telegram channel by @channel_name

**Comment by 42wim** [comment]
Do you have any pointers for this ? 
https://core.telegram.org/bots/api#recent-changes doesn't show anything about those changes

**Comment by slimit** [comment]
It may have been changed from a time ago but we just need to get this channel (https://web.telegram.org/#/im?p=@FlectraCommunityGroup) id which was previsouly available on the url in order to use it with the API.

**Comment by 42wim** [comment]
I don't use telegram myself, so could you clarify your problem a bit more?

* you can't find the ID of `@FlectraCommunityGroup`  ? or
* you have the ID, but the ID doesn't work in the matterbridge config ? or
* something else ?

**Comment by slimit** [comment]
I cant find the ID of @FlectraCommunityGroup.

**Comment by 42wim** [comment]
Did you look at https://www.linkedin.com/pulse/telegram-bots-beginners-marco-frau ?

The important part being, (make sure matterbridge isn't running), say something in the channel and go to `https://api.telegram.org/botReplaceThisWithTheBotFatherToken/getUpdates?offset=0` it'll show you the id

You can also just run matterbridge with another channel that you have the ID of and run matterbridge with `-debug` it'll show you the raw message from telegram which also contains the id.
