### ISSUE TITLE
Stickers/Images sent from Telegram don't display in Discord while using a Webhook

### ISSUE THREAD

**Issue by AlohaAloah** [42wim/matterbridge#469]
### Please describe the expected behavior.
Images/Stickers sent from Telegram are displayed by the Webhook in Discord

### Please describe the actual behavior. 
After a user sends a Sticker/Image, the matterbridge console displays:

`[0040] ERROR gateway:      HTTP 400 Bad Request, {"code": 50006, "message": "Cannot send an empty message"}`

And the image/sticker is not displayed in Discord

### Any steps to reproduce the behavior?
Add wenhook url in matterbridge settings.
Run matterbridge.
Send an image or a sticker in Telegram

### Please add your configuration file 
[matterbridgesettings.txt](https://github.com/42wim/matterbridge/files/2211041/matterbridgesettings.txt)

**Comment by 42wim** [comment]
I've just added this to the FAQ on https://github.com/42wim/matterbridge/wiki/FAQ

If you are using the discord webhook and the discord token, the webhook will be used for posting messages. The webhook can't do native upload of files/images to discord.

Possible solutions:

* Disable the webhook and use only the token. (you'll loose the avatar/nick changing)
* Setup a mediaserver this way matterbridge will upload the files/images to the mediaserver and the webhook will post the URL of the files/images on the mediaserver.
