### ISSUE TITLE
Sending images from Telegram to Discord is broken using webhook

### ISSUE THREAD

**Issue by mikroskeem** [42wim/matterbridge#473]
**Describe the bug**
Sending images from Telegram to Discord is broken when Discord's webhook is used

**To Reproduce**
Configure Matterbridge to bridge between Telegram and Discord channel. Use Discord's webhook feature to make chat look less ugly.

**Expected behavior**
Sending a picture from Telegram to Discord works

**Screenshots/debug logs**
I put here only a snippet which is relevant in my opinion, before that there was a Telegram message dump sending an image with completely empty message (message can be empty in Telegram)

```
[0014] DEBUG discord:      Broadcasting using Webhook
[0014] ERROR gateway:      HTTP 400 Bad Request, {"code": 50006, "message": "Cannot send an empty message"}
```

**Environment:**
 - OS: Linux
 - Matterbridge version: `1.10.1 dba259e`

**Additional context**
Configuration: https://paste.wut.ee/ufiwaruxag.bash

**Comment by 42wim** [comment]
Ok, looking at your configuration, am I correct that the problem is that the link to the mediaserver containing the images isn't shown? and not that the images aren't getting uploaded ? Because discord webhook doesn't support native upload of images/files
See https://github.com/42wim/matterbridge/wiki/FAQ#filesimages-not-getting-uploaded- for more info.

**Comment by mikroskeem** [comment]
> problem is that the link to the mediaserver containing the images isn't shown? 

Yep

> and not that the images aren't getting uploaded ? 

Actually this as the problem as well with given version, interesting. I didn't notice that before

> Could you also try the dev build: https://bintray.com/42wim/nightly/Matterbridge/v1.11.0-13-g2597c9b#files and run matterbridge with `-debug`

Fun fact: this version works perfectly for me and given bug cannot be reproduced anymore.

However here's the log: https://paste.wut.ee/abeqexajet.m

**Comment by 42wim** [comment]
Ok great, thanks for the feedback!
In the dev build some stuff regarding the `mediadownloadpath` was fixed, so that was related to your issue.
