### ISSUE TITLE
Mattermost → Slack avatars not synced for samechannelgateway

### ISSUE THREAD

**Issue by ArchangeGabriel** [42wim/matterbridge#477]
**Describe the bug**
Mattermost user avatars are not displayed in Slack when using `samechannelgateway`.

This is a follow-up of #454.

**To Reproduce**

Configure a Mattermost/Slack bridging using `samechannelgateway`:
```
[mattermost]
[mattermost.test]
Server="<url>:443"
Team="test"
Token="<validtoken>"
NoTLS=false
WebhookURL="<validurl>"
ShowJoinPart=true

[slack]
[slack.test]
Token="<validtoken>"
WebhookURL="<validurl>"
ShowJoinPart=true

[general]
RemoteNickFormat="{NICK} [{PROTOCOL}]"
MediaDownloadPath="<whatevervalidconfiguration>"
MediaServerDownload="<whatevervalidconfiguration>"

[[samechannelgateway]]
   name="test"
   enable = true
   accounts = [ "mattermost.test", "slack.test" ]
   channels = [ "town-square" ]
```

Send a message from Mattermost, post something in Slack, resend a message from Mattermost (needed currently because of how MediaUpload works).

**Expected behavior**

User avatar is displayed in Slack.

**Screenshots/debug logs**

No avatar. See #454 for logs.

**Environment (please complete the following information):**

See #454.

**Additional context**

See above or #454.

**Comment by 42wim** [comment]
Samechannelgateway is deprecated
