### ISSUE TITLE
Directly access Mattermost avatars instead of MediaUploading them.

### ISSUE THREAD

**Issue by ArchangeGabriel** [42wim/matterbridge#478]
**Is your feature request related to a problem? Please describe.**

Currenty, when you want to display avatars from Mattermost users in e.g. Slack, you have to setup MediaUpload (which is not very intuitive and might be tricky). Also, because of the way things work currently, the first message sent by each user after the bridge started (which can be often depending on your system update policy) has no avatar.

**Describe the solution you'd like**

Using direct access to avatar through `https://<mattermosturl>/api/v4/users/<userid>/image` instead would solve both points.

It wouldn’t work if behind a firewall, but in that case you also likely have to setup a much more complicated MediaUpload system (chances are high that you cannot serves the files right from the same machine hosting the Mattermost). Eventually, it could be made an option in Mattermost section whether to use MediaUpload or direct access for avatars.

**Additional context**

The above URL is accessible unlogged, even if Public links are disabled.

**Comment by 42wim** [comment]
Hm, I can not reproduce this.

When not logged in, eg incognito browser window, I get this message
```{"id":"api.context.session_expired.app_error","message":"Invalid or expired session, please login again.","detailed_error":"","request_id":"ratn6wwop7885kxyguznenabcd","status_code":401}```

Also looking at the code, it shows that a session is required

https://github.com/mattermost/mattermost-server/blob/97d8470a36db54e4a19b659c3f725743a93a9354/api4/user.go#L30

https://github.com/mattermost/mattermost-server/blob/97d8470a36db54e4a19b659c3f725743a93a9354/api4/handlers.go#L58-L67

**Comment by ArchangeGabriel** [comment]
I had also tried using a incognito browser window from even a different browser. But apparently that browser incognito session kept my cookies from before, when I was logged in, because I got the same message as you. Too bad…

Anyway, thanks for having took a look at it. ;)
