### ISSUE TITLE
Matterbridge does not forward all messages to Mattermost (Auth related?) 

### ISSUE THREAD

**Issue by 3c7** [42wim/matterbridge#486]
**Describe the bug**
Messages are sometimes not forwarded to Mattermost, couldn't find something related to that in the debug logs, the messages was received and it look like it was pushed to mattermost - but it didn't appear there.

**To Reproduce**
Unclear how to reproduce, bridge stopped forwarding them and continued later.

**Expected behavior**
Bridge forwards messages.

**Screenshots/debug logs**
Log on Mattermost side _could_ be:
`{"level":"error","ts":1534925964.771138,"caller":"app/web_conn.go:263","msg":"Invalid session err=GetSession: Invalid session token=[[TOKENHERE]], err=<no value>, "}
`
The token is, of course, valid. Maybe there could be some check, if a message was correctly posted to mattermost? My golang and Mattermost API knowledge are unfortunaltely not good enough to provide a PR - sorry.

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: 1.11.2 release

**Comment by 42wim** [comment]
I guess this only happens when on rather a long-running matterbridge ?

**Comment by 3c7** [comment]
Yes, think that is an expired session or something like that.

**Comment by 42wim** [comment]
Could you try using personal access tokens: https://docs.mattermost.com/developer/personal-access-tokens.html they don't expire.

**Comment by 3c7** [comment]
Currently, personal access tokens are being used. Try to get some info the next time it happens.

**Comment by 42wim** [comment]
I've reworked some code regarding to private tokens and reconnects in mattermost.
The latest stable release should fix your issues. 

If it doesn't, feel free to reopen this ticket.
