### ISSUE TITLE
{USERNAME} placeholder in config

### ISSUE THREAD

**Issue by realrolfje** [42wim/matterbridge#487]
**Is your feature request related to a problem? Please describe.**
After upgrading to mattermost 5.2.1 and the latest matterbridge, we notice that the behavior of {NICK} in the config file is changed.  It used to display the username of the mattermost user, and now it displays the nickname of the mattermost user. This feels like a bugfix and correct, but we'd like to display the username of the mattermost user. 

**Describe the solution you'd like**
For that, I'd like to ask for a {USERNAME} placeholder in the config file so we can reinstate our original setup.

**Comment by realrolfje** [comment]
Possibly related to https://github.com/42wim/matterbridge/issues/441

**Comment by 42wim** [comment]
Related to https://github.com/42wim/matterbridge/issues/452 ;-)
But a `{USERNAME}` placeholder is a good idea
