### ISSUE TITLE
Allow custom NickServ and ChanServ commands

### ISSUE THREAD

**Issue by 3c7** [42wim/matterbridge#490]
**Is your feature request related to a problem? Please describe.**
Some IRCs use functionality like `/msg ChanServe INVITE` to be able to join channels. To allow this automatically, a custom set of login queries (message to nickserv first, after that message chanserv for invitation etc.) is needed.

**Describe the solution you'd like**
A config string that replaces the action that's invoked during connecting to IRC, instead of the bare NickServ auth.

**Describe alternatives you've considered**
None, couldn't find something appropriate in the config.toml 

**Additional context**
None

**Comment by 42wim** [comment]
This is fixed now in master, you can also use the dev binaries

https://github.com/42wim/matterbridge/blob/9f66f93641612028455c43478da2b19e8ee42b8a/matterbridge.toml.sample#L99-L102
