### ISSUE TITLE
Send images through Discord webhooks

### ISSUE THREAD

**Issue by jl91569** [42wim/matterbridge#494]
**Is your feature request related to a problem? Please describe.**
Discord's webhooks support sending files (see [https://discordapp.com/developers/docs/resources/webhook](https://discordapp.com/developers/docs/resources/webhook)), but your FAQ currently states it's impossible.

**Describe the solution you'd like**
Send images through Discord's webhooks instead of forcing users to fall back to "normal" messages.

**Describe alternatives you've considered**
Mediaservers are a clumsy solution to something that looks like it's possible to do natively.

**Additional context**
More info: [https://birdie0.github.io/discord-webhooks-guide/structure/file.html](https://birdie0.github.io/discord-webhooks-guide/structure/file.html)

**Comment by 42wim** [comment]
Yes, I agree, if native is possible this should be used.
Thanks for the pointers, I'll take a look.

**Comment by Helcaraxan** [comment]
I am going through the backlog of open issues and stumbled upon this one. I can't really seem to find what this issue is referring to as it appears to me that the Discord bridge is already posting files / images via the Discord webhook API?

Am I missing something @jl91569, @42wim?

**Comment by 42wim** [comment]
@Helcaraxan well the webhook sends links to files/images but it doesn't actually does a native upload.
If you use the discord token it does.

**Comment by 42wim** [comment]
The discord library I use doesn't seem to support this.
@jl91569 do you care to open an issue at https://github.com/bwmarrin/discordgo regarding uploading files via webhook?

**Comment by jl91569** [comment]
Just double-checking before I open an issue, you've already tried using [this](https://github.com/bwmarrin/discordgo/blob/master/structs.go#L835) right?

**Comment by 42wim** [comment]
Yes, you can set that string but there isn't being done any processing on it, most of the logic for this to work seems to be in ChannelMessageSendComplex (with token) but doesn't seem to be used for the webhook.

**Comment by MOZGIII** [comment]
Bump. As explained [here](https://github.com/bwmarrin/discordgo/issues/617#issuecomment-504788776), we should construct webhook payload ourselves. How difficult is it with the current implementation?

**Comment by MOZGIII** [comment]
Is this code relevant? https://github.com/42wim/matterbridge/blob/79a006c8de311a7bbab540e62bd3fac998d415d5/bridge/discord/discord.go#L358-L378

**Comment by redyoshi49q** [comment]
In light of this Github issue, I edited the Matterbridge wiki FAQ page to link back to this page.

**Comment by 42wim** [comment]
@redyoshi49q hm actually this was implemented in #872 and fixed.
Going to close this now.
