### ISSUE TITLE
Allow specifing the configuration file to load from the command line

### ISSUE THREAD

**Issue by ctron** [42wim/matterbridge#5]
If you want to connect multiple channels with matterbridge it seems that you need to run an instance for each channel.

It would be helpful to be able to specify the configuration file to load from the command line to run multiple instances from the same binary.

Another option would be to be able to specify multiple configuration files for one instance.

**Comment by 42wim** [comment]
About the multiple channels, what is the use case ? 
Multiple mattermost channels to 1 IRC channel or 1:1 mapping ?

**Comment by ctron** [comment]
The use case it https://mattermost-test.eclipse.org

We do have a channel per eclipse project and some projects have IRC channels. So we do want to map IRC channels one to one to mattermost channels. But not all mattermost channels have IRC channels. Also are not all IRC channels on the same IRC server.

**Comment by 42wim** [comment]
Ok, I added a -conf feature and the multiple channel feature to master. 

Depending on the token matterbridge receives it will use the correct IRC channel and viceversa. 
For each token you'll have to specify the mattermost channel and IRC channel.
The channels have to be on the same IRC server though.

```
#multiple channel config
#token you can find in your outgoing webhook
[Token "outgoingwebhooktoken1"] 
IRCChannel="#off-topic"
MMChannel="off-topic"

[Token "outgoingwebhooktoken2"]
IRCChannel="#testing"
MMChannel="testing"
```
If possible could you help testing this ?

**Comment by ctron** [comment]
Wow, that was quick. I am not sure I can test it the next days though. But I try my best. Thanks a lot!

**Comment by 42wim** [comment]
No worries.
I'm gonna close this issue for now.
Feel free to open a new one if it doesn't work as expected :-)

**Comment by ctron** [comment]
Ok, finally I got some time to test this feature.

I don't understand though how to configure this. I do understand the outgoing key, but the incoming key, according to the mattermost UI, is also bound to a channel.

**Comment by 42wim** [comment]
It's bound tot a default channel, but can be overridden. 

Basically you just have to specify an incoming webhook URL (doesn't matter which one) in the ```url``` field of the ```[mattermost]``` section and it should just work.

Private groups/channels will not work though.
