### ISSUE TITLE
env vars 12 factor style

### ISSUE THREAD

**Issue by tomdavidson** [42wim/matterbridge#50]
suggestions on using environment variables in the config?

**Comment by 42wim** [comment]
The config file is quite complicated, so that's not really possible. What is the use-case ?

**Comment by tomdavidson** [comment]
Thanks for the response @42wim . Yes, the config file is complicated and I did not mean to suggestion replacing it all with env vars.  I have not used matterbridge yet because with secrets in the config file would require special handling for us, hence this issue.

In the sample config we have secrets such as:

``` yml
#login/pass of your bot. 
#Use a dedicated user for this and not your own! 
#REQUIRED (when useAPI=true)
Login="yourlogin"
Password="yourpass"
```

My pipelines keep secrets out of artifacts such as docker images or Elastic Beanstalk source bundles and obviously outside of the git repo. Platforms such as Elastic Beanstalk and Heroku has tooling to enable the [12 factor](https://12factor.net/config) style[1] of config management via environment variable.

If matterbridge had the capacity to give parameters set by env vars preference over that in the config then I could have my secrets in env var and the rest of config in git along with source. Alternatively maybe the toml file is parsed with expansions such as:

``` yml
#login/pass of your bot. 
#Use a dedicated user for this and not your own! 
#REQUIRED (when useAPI=true)
Login="${process.env.USERNAME}"
Password="${process.env.PASSWORD}"
```

I did not see these other options in the docs and am asking for clarification, but if the functionality does not exist then maybe we can discuss it as a new feature.

[1] i dont think 12 factor is the end all be all, just one of several legitimate strategies but one that is very convenient with current paas.

**Comment by 42wim** [comment]
Correct there's no functionality for this at the moment. 
I'm open for make it a new feature, but it has to be kept simple.  
So no extra parsing, but getting it from the environment as an override should be possible.

Is this something you're willing to implement yourself?

**Comment by tomdavidson** [comment]
Thank you for confirming.  I have never worked with Golang so it would be quite uphill for me.  What do you think about using https://github.com/spf13/viper for config - not the simplest but it doesn't look overly complicated?

**Comment by 42wim** [comment]
Maybe for 0.8 or later release, but for now not going to refactor for viper.
I'm planning to release 0.7 soon, I'll try to add it (using os.GetEnv()) for release if you're willing to test.

**Comment by tomdavidson** [comment]
Sounds great to me, thank you for your interest in the new functionality.  Yes, I am willing to test. What is your ballpark timeline?

**Comment by 42wim** [comment]
I just committed the change ;-)
See https://github.com/42wim/matterbridge/commit/92d9db5a2d6f568e3c21ecf56cde80b32c342868 for example

**Comment by tomdavidson** [comment]
Hey now... that was pretty quick, I expected at least a week before needing
to provide feedback :D

**Comment by chauffer** [comment]
@tomdavidson FYI, https://github.com/jwilder/dockerize might be a good fit for legacy apps.

**Comment by 42wim** [comment]
I've release v0.7 and v0.8 if it doesn't work, reopen the issue :)

**Comment by bmamlin** [comment]
FYI – documented this feature on wiki [here](../wiki/Gateway-config-%28basic%29).

**Comment by 42wim** [comment]
@bmamlin thank you! much appreciated

**Comment by lindhe** [comment]
@42wim I've been trying for a while now, and I simply _cannot get it to work._ :/ I've tried adding my Telegram Token to `.env` but then my bridge will not start. It gets a 404.

Should I create an issue about it, or is this feature deprecated and is not expected to work anymore?
