### ISSUE TITLE
Discord mentions do not work on webhooks

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#502]
**Describe the bug**

Following the merge of the Discord Mention PR, i discovered that the bridges i was operating that use webhooks on discord were not handling mentions

**To Reproduce**

Set up a standard discord with webhook) to anywhere bridge ad try to mention yourself
(i test with irc)

**Expected behavior**

the webhooks sends proper mentions to the channel

**Additional context**

when running matterbridge in debug i (believe) i did not see any messages about trying out different mentions when parsing messages passing through, so i believe it might not even pass through the same code

**Comment by 42wim** [comment]
Yes, webhooks take another path.
Should be fixed now.
