### ISSUE TITLE
IRC connection timeout should be configurable or at least a bit longer

### ISSUE THREAD

**Issue by gonter** [42wim/matterbridge#503]
**The Problem**
The IRC server that I need to connect to, replies immediately but takes more than 30 seconds to actually complete the connection.  This triggers the timeout in [1].

**Describe the solution you'd like**
It would be helpful, if the timeout can be configured.  As a workaround, I changed the timeout in my copy to 130 seconds which fixes the problem for me.

* [1] https://github.com/42wim/matterbridge/blob/bd3a3b6eaf061a6352f858c983bd0a8d14118252/bridge/irc/irc.go#L137

**Comment by 42wim** [comment]
This should be fixed in master, irc connections will now take as long as needed.
You can also try with the dev binaries here: https://bintray.com/42wim/nightly/Matterbridge/v1.12.0-3-g0795906#files

**Comment by patcon** [comment]
Reference for later:
https://github.com/cenkalti/backoff
https://python-irc.readthedocs.io/en/latest/irc.html#irc.bot.ExponentialBackoff
