### ISSUE TITLE
Move to use Slack's new APIs and tokens?

### ISSUE THREAD

**Issue by Helcaraxan** [42wim/matterbridge#510]
# Context & problem
Somewhat. Almost filed this as a "bug" rather than an FR but thought that as it is not a blocker issue I'd go this way to open up the discussion. I have been in the process of setting up some bridging between, mostly, Discord & Slack. Matterbridge is great for this (love, kudos and many thanks to this great repo and its contributors!).

The Discord-side has been entirely painless, up and running within minutes (if not seconds). However the Slack-side has been (and still is) a painful experience. Everything worked fine on my own test-Slack workspace but when migrating to an Enterprise Slack things got a little bit spicier. The obvious failure in the room was the continuous inability for Matterbridge to forward incoming Discord messages with the error `channel_not_found`.

# Solution
Debugging brought me into the depths of the Slack API and the `nlopes/slack` (which are both old friends o' mine). Long story short, Matterbridge relies (if one follows the documentation) on Slack legacy tokens. There have however been significant changes with regards to how Slack deals with Apps and their bots and it is nowadays perfectly possible to use non-legacy tokens. Another, separate, change has been their ["Conversations API"](https://api.slack.com/docs/conversations-api) which aims at simplifying the management of all things chat.

The easiest, albeit not necessarily best, solution would be to switch entirely to using the new Apps+bot approach and rewrite the code in `bridge/slack/slack.go` accordingly. This would remove the possibility to use legacy tokens. A clean-up of the semantics of the Slack-section in the configuration file could be done at the same time.

# Alternatives
If the removal of legacy tokens is considered to be too much of burden and there is a preference for a more gradual migration there is an alternative:

Maintaining the status quo that is adapted to legacy token and write separate new code-paths for the Apps+bots path. These paths could be auto-chosen based on the specified token value (as the new bot-tokens all start with `xoxb-`, unlike the legacy tokens).

# Further notes
I'd be happy to write the code for this. I'll be writing a variant of it anyway given that I will need to use the new Apps+bot approach myself. However thought I'd ask for input here first to decide which of both ways would be preferred when the time comes for a PR.

**Comment by 42wim** [comment]
Hi, thanks for looking into this!

I've noticed the conversation API changes (matterircd has added support), but haven't got time yet to add this to matterbridge (and I also don't have access to the paid version) so your help and a PR is more than welcome!

I've looked into the bot tokens before and one issue was that matterbridge couldn't join the channels by itself, it needs to be invited (I'm not sure if this is still the case).

It's ok for me to switch to the Apps+bot-only approach as we can't keep holding on on the legacy tokens anyway.  It would be nice though if we could have a simple page on the wiki like https://github.com/42wim/matterbridge/wiki/Slack-bot-setup but for the new setup, so that people can convert easily.

Feel free to @ me if you have any other questions!

**Comment by Helcaraxan** [comment]
Bots can't join conversations indeed because that is something that Slack still [has not made up its mind-up](https://github.com/chingu-voyage5/Bears-Team-6/issues/20#issuecomment-398804599) about, even [after 3+ years](https://github.com/slackapi/node-slack-sdk/issues/26). However, given that Matterbridge requires someone to manually specify Slack channels in its config it is not _too_ much of a requirement to ask someone to add the Matterbridge App/bot to any channel that it needs to deal with.

As much as I would love it myself to be possible for bots to join channels the flow of adding an App to a channel is now the default for any Slack App that needs to use a given channel. I can actually understand that quite well as it is a more secure permission model than allowing a bot access to any channel by default, especially in a corporate setting.

I'll make a PR then that removes the legacy tokens in favour of the new ones. I might submit one or two PRs ahead of the main one that contain some clean-up and refactor if you don't mind. As well as an update of the `nlopes/slack` dependency which just had its [`v0.4.0`](https://github.com/nlopes/slack/tree/v0.4.0) released.

**Comment by patcon** [comment]
This is really great, and I support adding a new possibility, but removing legacy token support is a big -1 from me, with all due respect. I'm working on a setup that would allow configuration of bridges without UI, but through simple channel naming conventions. Having to invite the bot into channel is an extra step beyond the wonderful workflow I'm excitedly working toward. I don't see removing legacy tokens as helpful or needed for my use-case :)

Would it be possible to just add another means of authenticating, without taking away what I perceive as a feature?

**Comment by Helcaraxan** [comment]
Hello @patcon. I understand your point, hence why I also suggested an alternative in my initial proposal of keeping the ability to use legacy tokens.

I do however have some questions / remarks around this:
- As much as a bot joining channels would be a good nice-to-have feature. I am myself very wearisome of the possible weaknesses in a security-model that this might bring (which is why I actually like the fact that they don't allow bots to do so). Manually inviting bots / adding apps or integrations to channels is a sane workflow. What is your perspective on this?

- If we assume the hypothesis that Slack is not going to allow bots to join channels then the legacy tokens are indeed that: _legacy_. As their [documentation states]:
   > You're reading this because you're looking for info on legacy custom integrations - an outdated way for teams to integrate with Slack. These integrations lack newer features and they will be deprecated and possibly removed in the future. We do not recommend their use.

   Which means that you are intrinsically creating something that relies on a feature that is already deprecated and might disappear at relatively short notice. I would urge you to think about alternative ways of improving the deployment workflow that you are envisioning to actually use the modern "Apps" approach that Slack now uses.

Am open-minded about the answers, these are not rhetorical questions. 🙂

**Comment by Helcaraxan** [comment]
> I think I might be of your mindset if we were working on a library or a hosted app, but this feels less relevant for a self-hosted tool that isn't asking for end-users to provide tokens. We're creating new unprivileged users (like literally anyone could on the slack teams I'm using), who are jumping in and out of "public" channels. There are no private DM's, or anything like that.

The point is not really of "creating users" its about them accessing public channels. Public refers to anyone with access to the Slack being able to read them. Matterbridge exports content to other chat providers and depending on your use-case (admittedly being cautious... but that's a preciously good default IMHO) the other chat provider might not have the same visibility which makes it a potential source of data leaks. Example:

_An organisation / company providing user-support on various chat platforms. In order to make life easier for their support team and reduce the monitoring burden they bridge all these public chat (as in accessible to anyone) to separate channels in their corporate Slack. Although it is fine and intended for the content of these particular channels to be mirrored they would not want their Matterbridge to be able to join other unintended channels and leak internal data._

> Basically, I feel that for the UI that I hope for, I need a full user -- token or auth or whatever. If legacy tokens get removed, I'll be investigating how to auth a full user, not use the bot method. But that could be years away or never.

My suggestion would be to rather start here: what is your goal and how can you make it work without using legacy stuff. I'd be happy to help brainstorm if you want to (have also just joined the Matterbridge chat nexus).

**Comment by patcon** [comment]
heh I appreciate the offer, but my goals are:
1. I would like gateway config to be possible (because I still need to write a config auto-generator) solely through renaming channels, and
2. I would like to not spend more time on auth when things are already working and suitable for my purposes

If those two things are satisfied, than I'm entirely fine to see code paths disappear, but otherwise I would request that it not go away :)

**Comment by jheiselman** [comment]
Perhaps a new bridge type (i.e. slack-new) could be created and used for building out the update. Then, at some point in the future, the decision can be made about dropping support for legacy tokens and then the project would also have work completed should Slack HQ actually announce the shut down of those APIs.

**Comment by patcon** [comment]
Some others reasons to allow user/bot takens:

- free accounts only get so many integration slots

- user tokens can be used by non-privileged users by default (unless on a paid slack team that's disabled token generation)

- Bots are a little more restricted (in the good way), and no matter how many bot [tokens] you have, they only take up one integration.

- Slack apps, though they have shiny new features (like event subscriptions), always consume a scarce integration slot.

just ran into this, so it refreshed me :)

**Comment by 42wim** [comment]
Maybe we can rename the current one (which @Helcaraxan already cleaned up a lot) to `slack-legacy`, before the new API gets added (which will then become `slack`)

This way it's clear that is a legacy setup (like the tokens).
Users will have to make a small (and conscious) change to their configuration, but their bridges will keep working like before.

But if we create 2 slack bridges, they both need to be maintained. (I don't want to maintain them both, if anyone is willing to do this, that's fine by me).

**Comment by patcon** [comment]
Sounds good to me!/Most should be possible to be shared anyhow, as I understand

**Comment by Helcaraxan** [comment]
Had not commented on this but I'm fine with keeping both the legacy and the new one. Had suggested as much as a (preferred) alternative in the OP. And as @patcon rightly puts its almost all the code is shared. Only the `Connect()` method differs between the two.

Am about the put in the PR that implements this.

**Comment by Helcaraxan** [comment]
@jheiselman given your comment in this thread I would be very happy if you could also have a brief look at the final PR (#582) for this issue.

**Comment by Helcaraxan** [comment]
With the merge of #582 this is issue is now closed. 🎉 🎊

**Comment by 42wim** [comment]
@Helcaraxan are you also going to do the wiki and documentation about this? Or should I do a quick note about it ?

**Comment by Helcaraxan** [comment]
I will be doing that tonight or, more likely, tomorrow morning.
