### ISSUE TITLE
[Feature] Email support

### ISSUE THREAD

**Issue by TomTheDragon** [42wim/matterbridge#513]
It would be very useful to be able to receive emails over Matterbridge, so that we are able to forward posts from mailing lists over to other networks as well.

**Comment by Helcaraxan** [comment]
@TomTheDragon what would the flow of forwarding / receiving emails look like? As it stands (and with my own, obviously biased imagination) I would rather see that you create another tool that watches a (your?) mailbox and when an email arrives that matches some preset filter it posts it to a chat platform (Slack, etc).

Then if you have Matterbridge running it will automatically propagate that message to all other connected chat platforms following your gateway specifications.

I don't think think Matterbridge should start sprouting an email server and / or client to be able to receive / monitor messages that way.

**Comment by patcon** [comment]
I like this idea! But lots of the smarts in Matterbridge feel very specific to synchronous chat. Might this perhaps best live in a small app that uses the API bridge?

ie. Polls `/api/messages` (if you want messages in slack to send email) and POSTs body of forwarded messages to `/api/message`

**Comment by patcon** [comment]
Came across this project: https://github.com/rodcorsi/mattermail

 Perhaps you could adapt it to pass to matterbridge API instead of directly to mattermost :)

**Comment by 42wim** [comment]
Yes, this is out of scope for mattermost, but could be "easily" implemented using the API

**Comment by lmaddox** [comment]
> Came across this project: https://github.com/rodcorsi/mattermail
> 
> Perhaps you could adapt it to pass to matterbridge API instead of directly to mattermost :)

it's archived. I'm currently looking into [this](https://gitlab.com/etke.cc/postmoogle/-/blob/main/README.md) for centrally aggregating messages from all platforms
