### ISSUE TITLE
List which gateway when reporting error "Bad Gateway"

### ISSUE THREAD

**Issue by danhimalplanet** [42wim/matterbridge#514]
matterbridge will send error message like this:

 2018/10/10 01:20:14 Bad Gateway
 2018/10/10 01:20:14 Failed to get updates, retrying in 3 seconds...

It would be helpful to know which gateway is causing the problem

**Comment by 42wim** [comment]
Yes, unfortunately those log messages come from the underlaying libraries I use, the code would have to change there.

**Comment by Helcaraxan** [comment]
Closing as this is indeed something out of Matterbridge's control. 😞
