### ISSUE TITLE
Allow sending isTyping events to other slack channels

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#516]
Related: https://github.com/nlopes/slack/blob/0afac90b917f77d7c59d638420d5d40fe65eee61/websocket_misc.go#L51-L56

While this would show the "bot" typing, I could be an indicator to show whether a reply might be expected soon.

**Comment by patcon** [comment]
Use case here is when using the Google Translation feature (upcoming) to translate between channels. Would be great to know when someone is writing back. That's one of the only parts that doesn't feel seamless about the experience :)

**Comment by 42wim** [comment]
Fixed in #559
