### ISSUE TITLE
Discord configuration

### ISSUE THREAD

**Issue by jleclanche** [42wim/matterbridge#52]
Initial feedback on Discord configuration:

* `Guild` is super confusing. Although it's the terminology used internally, they're only ever called Servers.
* I'm getting 401 unauthorized after the connection is successfully established. It's unclear why. My initial reactions are: Am I supposed to use the `id` for `Guild`, or its name? What about the channel input/output, id or name? Running with `--debug` didn't output anything extra for discord, other than `&errors.errorString{s:"HTTP 401 Unauthorized, {\"code\": 0, \"message\": \"401: Unauthorized\"}"}  module=discord`, so there's probably a message being sent without it being passed to the debug printer.

**Comment by jleclanche** [comment]
One more issue: prefixing the channel name with `#` only works for `gateway.in`, but not for `gateway.out`. I have no idea why. But if by mistake you have `in` configured to, say `#example` and `out` configured to `example`, you get double messages in the channel.

**Comment by 42wim** [comment]
Thanks for testing and reporting. Renamed ```Guild``` to ```Server```. (I found the whole thing also confusing, the API uses Guild everywhere)
Updated sample conf to mention the Bot prefix for the token and to mention the channel naming conventions. No # for discord.

**Comment by jlsjonas** [comment]
(using the latest go get) this issue seems to have reappeared, and I do have "Bot" in front of my token 
tried both channelname and ID:####

**Comment by 42wim** [comment]
Good point
