### ISSUE TITLE
Upgrade blackfriday markdown-parsing library to v2

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#522]
v1 has the markdown parser as private, but in v2 it's public.

This would allow me to customize the markdown parser for slackdown (slack's simplified flavor of markdown). Parsing slack's messages into HTML with this parser would allow Google Translate to work better (since it can understand and translate HTML, but not markdown). The HTML message can be translated, then rendered back into slackdown format for rendering on the other side of bridge.

I would expect to do this work myself, just hoping to a +1 before I tackle it.

(I will close out #499 first)

Related: https://github.com/42wim/matterbridge/issues/499

**Comment by Helcaraxan** [comment]
@patcon have created the PR for this.
