### ISSUE TITLE
Slack bridge relays ephemeral messages sent to bridge user

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#527]
**Describe the bug**
When using a full user account as the bridging Slack account, some ephemeral messages that are sent to this user (ostensibly by Slackbot) are relayed through the bridge.

**To Reproduce**
1. Create bridge user
2. Create gateway between two slack channels on the same slack team.
3. upload a file to one channel
4. The other channel will get a message that show as from slackbot in the logs

**Expected behavior**
Would expect messages from slackbot to be discarded.

**Screenshots/debug logs**
Sorry, forgot to grab these. Will try to reproduce later

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: `1.11.4-dev`
 - If self compiled: output of `git rev-parse HEAD` Sorry, I am technically way down on my own feature branch. There is a small chance that it's not reproducible, but I don't think I touched any code related to this.

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))

**Comment by Helcaraxan** [comment]
@patcon are you still seeing this happen? Just checking to see whether we should close this.

**Comment by patcon** [comment]
Yep, it addressed perfectly fine with your commit that ignores slackbot by name :)

though I think you use display name instead of more authoritative user ID, which I believe is consistently "USLACKBOT". Also, we should perhaps later investigate if the larger superset of messages that should be ignored are all ephemeral messages from any source, not just slackbot. Some other apps might somehow send the not user an ephemeral message (prob only affects legacy tokens)

So yes good to close and i could reticket those things :)

**Comment by Helcaraxan** [comment]
I'll let you indeed reticket things that you think are worth it. 🙂

**Comment by patcon** [comment]
Oh! Wait. Slackbot does autoreplies, so ignoring all messages from them might be bad. We can check this by setting up an auto-reply in the "Customise Slack" settings page, and see if it gets through the gateway. Will do this before closing
