### ISSUE TITLE
New Hangouts Api Allows for Free bridging

### ISSUE THREAD

**Issue by Warfields** [42wim/matterbridge#528]
**Is your feature request related to a problem? Please describe.**
As mententioned in issue #28 hangouts is notoriously bad to bridge, and issue #409 mentions that Google's go interface is not free. There is another option of the python interface [hangups](https://github.com/tdryer/hangups) for free hangouts interface.

**Describe the solution you'd like**
Hangups was made by reverse engineering the Hangouts network protocol and is at **zero cost to use**. I'd like to interface the current go code to call python scripts at launch to create a bridge to matrix. From this bridge I have gotten matterbridge to replicate to other clients.

**Additional context**
Currently I have a prototype example that is being prepared to face publicly (Removing and squashing commits with hard coded user names and passwords). Being developed as a project under Colorado School of Mines ACM (Some of our members refused to switch to Matrix from Hangouts so I made the horrendous starter code that we are refactoring). I will link to our work once it's ready!

**Comment by 42wim** [comment]
Cool! Looking forward to your project. Are you using the matterbridge API for this?

**Comment by Warfields** [comment]
Not currently, We've been using the Matrix api and then had matter bridge forward. Could you link to the api documentation?

**Comment by patcon** [comment]
Yeah! A little python heroku app bridging the two would be awesome!

Just in case it's helpful to see another implementation of the matterbridge API:
https://github.com/elytra/MatterLink/tree/master/core/src/main/kotlin/matterlink/api

**Comment by jheiselman** [comment]
Given the shutdown of the service next year, perhaps time would be better spent elsewhere. Just a thought.

**Comment by Arinerron** [comment]
@jheiselman I would disagree; as groups from Google Hangouts migrate to other platforms, a bridge between the old and the new would be ideal until Google Hangouts is shutdown.

**Comment by scrthq** [comment]
@jheiselman - Super late reply in case anyone else stumbles upon this, but Classic Hangouts is being sunset this year (or next, per recent Google updates), not Hangouts Chat. Hangouts Chat is the successor to Classic Hangouts and is the service covered by the [API](https://developers.google.com/hangouts/chat/) that supports bots, not Classic Hangouts.

**Comment by jheiselman** [comment]
@scrthq yeah, at the time the discussion above happened, Hangouts Chat was still going to be exclusive to G Suite customers. We don't have any details for what the consumer version will look like, but speculation is that bot integration will still be reserved for paying customers. We'll see what shakes out over time.

**Comment by scrthq** [comment]
Fair! There are still some specifics about the bot integration with Chat that may break the expectation of how a chat bridge should perform:

* Outbound messages from Chat need to either be sent directly to the bot via DM or need to have the bot mentioned from a room that the bot is a member in.  
    * Outbound messages also only work with an HTTPS endpoint, Google Cloud Pub/Sub queue, or Google Apps Script endpoint, so no option like websockets to monitor without rolling your own websockets API.  
* Inbound messages to Chat from another service though would be pretty simple, as it would just need a We hook generated from a Room in Chat to accomplish.  

I'll try and get a PR in to at least enable Hangouts Chat to receive messages from another service via we hook and cover some base documentation around it once I have some time

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by qaisjp** [comment]
> Hangouts Chat was still going to be exclusive to G Suite customers. We don't have any details for what the consumer version will look like, but speculation is that bot integration will still be reserved for paying customers. We'll see what shakes out over time.

[~~Where did you hear this?~~](https://twitter.com/happyinwater/status/1068861340800958466)

Sweet!

**Comment by 42wim** [comment]
hangouts will be replaced with hangouts chat, closing this in favor of #409
