### ISSUE TITLE
MM access tokens shall not be mixed with cookies

### ISSUE THREAD

**Issue by ondras** [42wim/matterbridge#530]
When using Mattermost PATs, the client correctly sets the `Authorization` header but also provides the `MMAUTHTOKEN` cookie: https://github.com/42wim/matterbridge/blob/master/matterclient/matterclient.go#L153

Some Mattermost installations (such as our company's server) do not like this and fail the authentication. I *think*  that PAT-based auth shall not use HTTP cookies at all. They create this weird weird *no single source of truth/auth* duality.

**Comment by ondras** [comment]
Great, thanks! :+1:

**Comment by 42wim** [comment]
Thanks for investigating and reporting this :)
You can use a dev binary on https://bintray.com/42wim/nightly/Matterbridge/v1.11.3-19-g107969c#files to test.

**Comment by ondras** [comment]
@42wim well I am using matterircd... but I will compile a dev version myself, no problem.

**Comment by 42wim** [comment]
matterircd won't work with this fix yet (because it has an old version vendored), I'm in the middle of fixing this also (in regards to https://github.com/42wim/matterircd/issues/208)

**Comment by 42wim** [comment]
If you recompile matterircd you can use the personal tokens, you'll have to use `token=yourtoken` instead of `MMAUTHTOKEN=yourtoken` as the `password` when logging in

**Comment by ondras** [comment]
Right, I will recompile and s/MMAUTHTOKEN/token/.
