### ISSUE TITLE
Add support for a static analysis web service

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#534]
@Helcaraxan's comment on cyclomatic complexity (https://github.com/42wim/matterbridge/pull/533#issue-224835793) made me realize that my own work would benefit from in-flow updates on how my code is affecting quality metrics :)

After some research, Code Climate still seems to be a front-runner. Here's a sample of what we'd get (some is available in issues):
https://codeclimate.com/github/codeclimate/codeclimate

Open to other suggestions. @42wim, if you enabled Code Climate on the repo, I'd be happy to submit a PR with config

**Comment by Helcaraxan** [comment]
Good suggestion @patcon ! I had seen various tools but had never stumbled across CodeClimate. Just set it up for my fork of this repo. You can see the results here:
- Full repo analysis: https://codeclimate.com/github/Helcaraxan/matterbridge
- GitHub PR integration and analysis: https://github.com/Helcaraxan/matterbridge/pull/2

**Comment by 42wim** [comment]
Just looked into it.. codeclimate wants full write and read access to everything on all my repos. That's a bit too greedy.
At first sight it doesn't offer that much more than the standard go linter tools.

**Comment by patcon** [comment]
True, but I feel it has the ske theory of continuous integration: nothing new, just pits it front-and-center and in the middle of conversation.

Re: permissions. I believe you can author, do the setup, and then revoke auth, no? Code climate should keep working, as it just needs that for setting up the hook

**Comment by 42wim** [comment]
Ok, I did this.
https://codeclimate.com/github/42wim/matterbridge

**Comment by patcon** [comment]
Hmmmm realised that revocation prevents commit status, which is how code quality gets into each PR convo...

Would you be open to just transferring the repo to https://github.com/matterbridge (which I believe is yours already) and enabling the permission that concerns you?

Alternatively, github has "requested" vs "granted" scopes, because users can revoke scopes. You should be able to leave the "repo:status" scope active while revoking the "repo" scope that was used to set up the webhook and key: https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#requested-scopes-and-granted-scopes

Details: https://docs.codeclimate.com/docs/setting-github-oauth-permission-levels

**Comment by patcon** [comment]
Regardless, I'll submit a PR to get the code climate score badge in the README :)

**Comment by 42wim** [comment]
Did you add codeclimate to your own repo? And can you revoke specific access? because I can't.
Moving the repo to another organization doesn't solve the problem, it just moves it.

But it should be able to do because travis-ci can do this as an app. Unfortunately the code-climate one doesn't have the free tier option https://github.com/marketplace/code-climate

![image](https://user-images.githubusercontent.com/1810977/48259910-cb3eb580-e419-11e8-8ae9-fbb999d61700.png)

**Comment by patcon** [comment]
Sorry, its not obvious, but they have an app: https://github.com/apps/codeclimate

**Comment by 42wim** [comment]
Wow, how did you find out about this? 
Going to https://github.com/apps redirects to https://github.com/marketplace, but your direct link works

**Comment by 42wim** [comment]
Seems like checks aren't show up on PR changes though

**Comment by patcon** [comment]
Have you had a chance to check out the config instructions yet? https://docs.codeclimate.com/docs/github-pull-requests

It might need some yaml files in the repo to configure, but hopefully it has some sensible defaults without :)

**Comment by 42wim** [comment]
Got it working, nothing to configure though

**Comment by patcon** [comment]
Perhaps useful to track for later: https://twitter.com/patconnolly/status/1075157413894868992
