### ISSUE TITLE
Cleanup old branches

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#535]
Minor, but thoughts on cleaning up old branches? Seems like they're from an old development strategy. (Just in case anyone is pointing at them with build tools, we could add tags as a minor convenience.)

And I see there is maybe some feature branches, which maybe we could turn into PRs if there is discussion to be had about salvaging anything?

**Comment by 42wim** [comment]
Doubt that anyone uses them.  I'll clean them up.
