### ISSUE TITLE
Set up a recurring donation platform

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#543]
You're a really awesome maintainer. I would love it if you had a way that people could express support in a fashion that is sustainable. I see that you have a cryptocurrency tip option. These are great, but as someone who has at times tried to work in open source, one-time times vs recurring payments change the dynamics.

I would love to set up an OpenCollective page for this project. Would you be willing to discuss? (For what it's worth, it's more than about putting money in your pocket, but also about finding small ways to incentivize and show appreciation, in a way that can have a multiplier effect in projects that take it to heart :)

(I promise this is not about my getting anything. I'm much more eager to help, and then give it to others!)

**Comment by 42wim** [comment]
Well, the main thing I need is VPS(es) for running the bot and testing stuff. 
Digitalocean graciously sponsored this project for 1 year for this (about 6 months left).

Getting money for the project probably causes more problem than it's worth, regarding taxes, VAT and other red tape I don't want to worry about.

**Comment by patcon** [comment]
Happy to pass, but fwiw, with OpenCollective, the non-profit entity is essentially virtualized -- they are legally on the hook, but assume responsibility with a very informal ToS-like contract with community members of open source project. You only worry about VAT if you submit an expense for work rendered, like a contractor to the project. They take 10% to handle the rest, and you don't see the other paperwork.

It's OK to not do, but just wanted to clarify

But pls feel
