### ISSUE TITLE
[Telegram] Add channel ID discovery command line parameter

### ISSUE THREAD

**Issue by lenucksi** [42wim/matterbridge#548]
As described in https://github.com/42wim/matterbridge/wiki/Section-Telegram-(basic) Matterbridge can be used to discover one's channel ID directly without having to resort to direct API access.

**Describe the solution you'd like**
I would prefer to be able to
-  start Matterbridge with a specific command line parameter and a configured Telegram API token, 
- add the bot to my desired channel, 
- chat up the bot or create generic traffic on the channel
- and have my channel ID output on the command line without having to use the -debug parameter and extracting the ID from the debug output. After outputting the ID, Matterbridge could terminate itself.

**Comment by patcon** [comment]
What about writing a little helper script in whatever language you prefer, and then it could be kept in `contrib/`? You could write it to parse the proper credentials from the toml config, and read the telegram channels

**Comment by jwflory** [comment]
> What about writing a little helper script in whatever language is preferred, and then it could be kept in `contrib/`?

I was going to suggest this be generalized outside of the project. I manage a few bots and frequently need the IDs, or I am instructing others on how to find the chat ID of a group. If this were its own command-line tool or script, it would be really helpful. The Telegram API does not do an intuitive job of this.

**Comment by patcon** [comment]
That sounds like a rad approach. Pls do come back and share when you do have time to work on it :)

**Comment by Mikaela** [comment]
It would be nice if there was a simple `/id@matterbridge` command at Telegram to get the ID out of a group where Matterbridge is.

I think it wouldn't hurt to have it also work in private and give user ID there instead, while there is no practical use for that yet.

**Comment by Mikaela** [comment]
#1703 seems to add a Telegram command for this

**Comment by 42wim** [comment]
fixed by #1703
