### ISSUE TITLE
Improve the setting of config defaults

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#560]
Reticketed from https://github.com/42wim/matterbridge/pull/559#issuecomment-436509967

Improve the setting of defaults

Right now, was can only easily default to false and empty strings, etc. Sometimes a false or empty string value might not be the most user-friendly default. And altering with the semantics of the key (EnableThing vs DisableThing) to make false _be_ safe is perhaps not ideal.

Here are some settings that could be migrated to a clearer default-setting tactic:
- [`MediaDownloadSize`](https://github.com/42wim/matterbridge/blob/5132d8f097a7eef2cb3d43c1c4cd297bc8254df5/bridge/config/config.go#L206)
- [`Buffer`](https://github.com/42wim/matterbridge/blob/5132d8f097a7eef2cb3d43c1c4cd297bc8254df5/bridge/api/api.go#L37)

**Comment by KrzysztofMadejski** [comment]
+1 

I'd improve the method that is getting the config values to provide defaults. For now we have:

https://github.com/42wim/matterbridge/blob/fb713ed91bfb48c0037e489f80be85c54e69953a/bridge/bridge.go#L99-L105

I'd like to see:
```go
func (b *Bridge) GetStringOrDefault(key string, key string) string {
	val, ok := b.Config.GetString(b.Account + "." + key)
	if !ok {
		val, ok = b.Config.GetString("general." + key)
	}
        if !ok {
                val = default
        }
	return val
}
```

Let me know what you think. It would be 15mins to add such extra methods.

**Comment by KrzysztofMadejski** [comment]
@patcon Now I see that your PR was merged and you addressed something different. Should I create another issue or keep these helper functions here? 
@42wim I wonder what do you think about it.

**Comment by KrzysztofMadejski** [comment]
Also, now I see that I'd like to set default config value for a given bridge (programatically in the bridge). For example, for WhatsApp I'd like to set:
- `PreserveThreading=true` altough the default is false
- `RemoteNickFormat="@{NICK}: "`

**Comment by 42wim** [comment]
I'm not for setting hardcoded defaults in the bridges. 

I'd like to all bridges behave the same with their default settings, which are empty strings and false boolean variables.

This gives a consistent experience for the end-user. (and also makes the troubleshooting easier because stuff needs to be enabled explicitly and will be visible in the configuration)
