### ISSUE TITLE
Add support for nextcloud talk

### ISSUE THREAD

**Issue by hoerup** [42wim/matterbridge#564]
Nextcloud talk is nextclouds take on a chat and voice/video conference system https://nextcloud.com/talk/

It would be nice if matterbridge was able to exchange chat messages with talk

**Comment by patcon** [comment]
Thanks @hoerup! :)

They are apparently planning to [integrate with either Matrix or XMPP](https://github.com/nextcloud/spreed/issues?utf8=%E2%9C%93&q=matrix), so then they'll work with Matterbridge. (They don't seem to have a standard protocol in the meantime.)

There's another thread where the maintainer can add a mention of this for future people who are wondering: https://github.com/42wim/matterbridge/issues/28

**Comment by gary-kim** [comment]
Since https://github.com/pojntfx/nextcloud-talk-bot-framework is now available, I'm gonna put this in my TODO list. I am quite busy at the moment though so if someone else wants to pick it up, feel free!

**Comment by gary-kim** [comment]
Okay, I'm working in this now. The Go library is in progress here: <https://github.com/gary-kim/go-nc-talk>. I'll add the library and open a PR once it's stable.

**Comment by gary-kim** [comment]
This is closed by #1167

**Comment by 42wim** [comment]
Thanks for your work @gary-kim !
