### ISSUE TITLE
(discord) Request: add a way to specify channels/servers by ID rather than name

### ISSUE THREAD

**Issue by jleclanche** [42wim/matterbridge#57]
I have two servers with the same name, it would be good to be able to specify a ServerID rather than Server name.

**Comment by jleclanche** [comment]
Worth noting that channel/server names can change as well which makes this more robust.

**Comment by 42wim** [comment]
Just wondering, what's the use case to have multiple servers with the same name ? Isn't that confusing ?
Also the ID, seems like I can only find it in the URL itself?

**Comment by jleclanche** [comment]
The ID can be found by enabling developer mode and right clicking on channels/servers/messages/etc in discord.

As for the use case, it's because we have both a private and public one, but either way the problem of names changing is more frequent I think.

**Comment by 42wim** [comment]
Still find discord utterly confusing ;-)
You can now use ```channel="ID:12345678"``` to specify the channel ID. 
This also solves the server issue, because it looks like the channel ID's are global unique, as it overrides the selected server.

Could you let me know if this works correctly ?

**Comment by jleclanche** [comment]
Thanks! I won't be able to properly test any time soon unfortunately, I'm off traveling for the next 2 weeks :(

Your latest commits work great though. Thanks a lot. And thanks again for matterbridge itself, I'm so stoked to finally be able to use a reliable multi-gateway system :)

**Comment by 42wim** [comment]
You're welcome, thanks for testing and reporting :)

**Comment by 42wim** [comment]
I've released v0.7 and v0.8 if it doesn't work, reopen the issue :)

**Comment by jlsjonas** [comment]
I'd actually recommend allowing id's for the server too, so that you can still use text-based channel names.
can test within day of update

**Comment by 42wim** [comment]
Don't really get the use for this, if you go to the effort of specifying your server with ID, you can do the same for the channel, right?

**Comment by jlsjonas** [comment]
unless you want to use the "samechannel" config method ;-)
besides... server id is a single right-click & "copy id", you usually know the channel names by heart (or can keep the list visible in the background, without right-clicking)
