### ISSUE TITLE
IRC Message-Split loses about 33 characters in the middle of the split

### ISSUE THREAD

**Issue by DarkSir23** [42wim/matterbridge#584]
**Describe the bug**
When bridging Discord to IRC, Message-Split appears to lose about 33 characters.

Message on Discord Side:
Capheind: Fudge is a generic role-playing game systemfor use in freeform role-playing games.[1] The name "FUDGE" was once an acronym for Freeform Universal Donated (later, Do-it-yourself) Gaming Engine[2] and, though the acronym has since been dropped, that phrase remains a good summation of the game's design goals. Fudge has been nominated for an Origins Award for Best Role-Playing Game System for the Deryni Role-Playing Game

Message on IRC Side:
&lt;Capheind&gt; Fudge is a generic role-playing game systemfor use in freeform role-playing games.[1] The name "FUDGE" was once an acronym for Freeform Universal Donated (later, Do-it-yourself) Gaming Engine[2] and, though the acronym has since been dropped, that phrase remains a good summation of the game's design goals. Fudge has been nominated for an Origins Award for Best Role- <message clipped>
&lt;Capheind&gt; ni Role-Playing Game

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 16.04
 - Matterbridge version: version: 1.11.4-dev

**Comment by Helcaraxan** [comment]
Have confirmed the issue (codewise - don't have an IRC server available for testing). Am creating the PR that should fix it.

**Comment by DarkSir23** [comment]
Awesome, thank you for such a quick response!
