### ISSUE TITLE
Unable to connect to MycroftAI Mattermost instance

### ISSUE THREAD

**Issue by skeledrew** [42wim/matterbridge#599]
**Describe the bug**
Trying to connect to MycroftAI Mattermost gives:
```[0000] FATAL main:         Starting gateway failed: Bridge mattermost.test failed to start: ": Invalid or expired session, please login again., "```
(I have tried using my regular account, which I don't mind never opening in another client again, and a new temp account for testing, with identical results)

**To Reproduce**
1. Go to temp-mail.org to get a temp email.
2. Go to chat.mycroft.ai and sign up with the temp email.
3. Verify the email.
4. Use email to create mattermost test profile:
```[mattermost.test]
Server="chat.mycroft.ai:80"
Team="MycroftAI"
Login="user@example.com"
Password="userpass"
NoTLS=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
PrefixMessagesWithNick=true
```
NB: I disabled TLS due to another error:
```[0000] FATAL main:         Starting gateway failed: Bridge mattermost.test failed to start: "https://chat.mycroft.ai:80/api/v4/users/logout: model.client.connecting.app_error, Post https://chat.mycroft.ai:80/api/v4/users/logout: http: server gave HTTP response to HTTPS client"```

**Expected behavior**
Bridge should connect to Mattermost instance.

**Screenshots/debug logs**
```[0000]  INFO main:         Enabling debug
[0000]  INFO main:         Running version 1.11.3 0bd5a0d
[0000]  INFO gateway:      Parsing gateway mycroftai_general
[0000]  INFO gateway:      Parsing gateway appimage
[0000]  INFO gateway:      Starting bridge: mattermost.test 
[0000]  INFO mattermost:   Connecting using login/password (sending and receiving)
[0000]  INFO mattermost:   Connecting user@example.com (team: MycroftAI) on chat.mycroft.ai:80
[0000] FATAL main:         Starting gateway failed: Bridge mattermost.test failed to start: ": Invalid or expired session, please login again., "
```

**Environment (please complete the following information):**
 - OS: Kubuntu 18.04
 - Matterbridge version: 1.11.3 0bd5a0d

**Additional context**
Gateway:
```[[gateway]]
name="mycroftai_general"
enable=false

[[gateway.inout]]
account="telegram.skeledrew"
channel="-#########"

[[gateway.inout]]
account="mattermost.test"
channel="general"
```

**Comment by 42wim** [comment]
Should be in the URL also should be probably in the mail you received otherwise ask the admins of the server what your team is.

**Comment by skeledrew** [comment]
It seems the the test account wasn't working, possibly because I hadn't actually used it to chat or some other reason. Moving back to my real account the team name showed in the array: `[0001] FATAL main:         Starting gateway failed: Bridge mattermost.skeledrew failed to start: Team 'mycroft' not found in [community]`. Also just a suggestion to make it clear in the wiki that the team name is what comes directly after `example.com/` as I wasn't aware of this; it's only because it showed in the debug that it became clear.

Also is there still any reason to create a dedicated user? So far it's working great and I can send and receive and I'm using it to substitute for having a dedicated client.

**Comment by patcon** [comment]
> Also is there still any reason to create a dedicated user? So far it's working great and I can send and receive and I'm using it to substitute for having a dedicated client.

I believe it's that some messages detected as being sent from the token user are not relayed across bridge -- used to be all messages, but sounds like maybe it's working for you now. It used to be safe to use your own token for the Slack teams you were never actually speaking on (as in, assuming you were actively on the other end of bridge instead). Not sure if this is still the case.

My impression is that if there are issues, there would be ways to make it work, but user tokens are being deprecated, so unlikely to receive much attention unless you have capacity to do so.

I'll make a table on the wiki page taking a stab at comparing usage of each token (they each have their own limitations).
https://github.com/42wim/matterbridge/wiki/Section-Slack-(basic)

**Comment by skeledrew** [comment]
Oh, OK. Thanks. Guess this can be closed now...
