### ISSUE TITLE
Debugging with Docker

### ISSUE THREAD

**Issue by jurgenhaas** [42wim/matterbridge#60]
When building Matterbridge yourselves, I see you can use a CLI flag for debugging. I wonder if there is a way to enable that when using Docker as well.

**Comment by 42wim** [comment]
sure, with docker you can pass the -debug flag
```docker run -ti -v /tmp/matterbridge.toml:/matterbridge.toml 42wim/matterbridge -debug```

**Comment by jurgenhaas** [comment]
Thanks, confirmed.
