### ISSUE TITLE
[IRC] Bridge can't join a channel set to registered nicks only, even when identified.

### ISSUE THREAD

**Issue by derram** [42wim/matterbridge#602]
The Rizon network has had a spam problem recently that has required active channels to set the +R mode which prevents unregistered nicks from joining a channel.

The bridge is identifying for the nick, but it still fails to join the +R channel.

Running it with -debug shows the bridge identifies for the nick as the final step, so that's more than likely why it's unable to join.

**Comment by 42wim** [comment]
Could you try https://github.com/42wim/matterbridge/wiki/Section-IRC-(basic)#sasl-support-on-freenode-when-youre-registered-with-nickserv ? seems like rizon has also SASL support, so should work.

**Comment by derram** [comment]
> [0000]  INFO irc:          Connecting irc.rizon.net:6697
> [0000] DEBUG irc:          "CLIENT_INIT :irc.rizon.net:6697"
> [0000] DEBUG irc:          ":magnet.rizon.net NOTICE * :*** Looking up your hostname..."
> [0000] DEBUG irc:          ":magnet.rizon.net NOTICE * :*** Couldn't look up your hostname"
> [0000] DEBUG irc:          ":magnet.rizon.net CAP * LS :away-notify chghost invite-notify multi-prefix sasl userhost-in-names"
> [0000] DEBUG irc:          ":magnet.rizon.net CAP afb ACK :away-notify chghost invite-notify multi-prefix sasl userhost-in-names"
> [0000] DEBUG irc:          "AUTHENTICATE +"
> [0000] DEBUG irc:          ":magnet.rizon.net 904 afb :SASL authentication failed"
> [0000] DEBUG irc:          "ERROR :closing connection: SASL authentication failed"
> [0000] ERROR irc:          disconnect: error: closing connection: SASL authentication failed
> 

> [irc.afb]
> Server="irc.rizon.net:6697"
> Nick="afb"
> NickServNick="NickServ"
> NickServPassword="*******"
> UseTLS=true
> UseSASL=true
> SkipTLSVerify=false
> RemoteNickFormat="{LABEL} <{NICK}> "
> Label='[i]'
> IgnoreNicks="af-attach"
> ColorNicks=true
> MessageSplit=true

Password is correct, the bridge does identify when I connect it without SASL.

**Comment by 42wim** [comment]
Create a test user also and opened an issue on https://github.com/lrstanley/girc/issues/25 regarding SASL
Could you try master or download a dev build on https://bintray.com/42wim/nightly/Matterbridge/v1.12.0-2-ga2b45bc#files the nickserv issue should be solved. (disable SASL again to test)

**Comment by derram** [comment]
Yep, it joined the channel fine.

Thanks again!
