### ISSUE TITLE
Connection error when firewall up

### ISSUE THREAD

**Issue by jurgenhaas** [42wim/matterbridge#61]
I'm running matterbridge in Docker and I do have a problem to connect to remote bridges when my firewall is up. The debugging shows this error:

```
DEBU[2016-10-26T08:47:27Z] trying login bot@example.com mattermost.example.com  module=matterclient
DEBU[2016-10-26T08:48:27Z] Post https://mattermost.example.com/api/v3/users/login: dial tcp: lookup mattermost.example.com on 1.2.3.4:53: read udp 9.8.7.6:41147->1.2.3.4:53: i/o timeout  module=matterclient
FATA[2016-10-26T08:48:27Z] Bridge mattermost.example failed to start: model.client.connecting.app_error 
```

When I stop the firewall it works fine. I checked for port 53 which is open outgoing for both TCP and UDP, but still no luck with the firewall up and running.

So my question is, which ports are required such that the matterclient can connect?

**Comment by 42wim** [comment]
port 53 is dns, seems like your DNS is not working or unreachable.

**Comment by jurgenhaas** [comment]
That's what it looks like, but for one, the ports 53 outgoing is open anyway and if shutting down the firewall, the connection is working. Then, closing down, starting the firewall and then trying again, it is blocked again. So that makes me wonder if there is something different that the matterclient tries to do at that time.

**Comment by 42wim** [comment]
Matterclient uses port 53 for DNS and http or https or another port, depending on your config.
Especially since it works if you disable the firewall and it stops, there's something wrong with your firewall settings.  I'm afraid your on your own for this, a bit out of scope for this project.

**Comment by jurgenhaas** [comment]
It seems to be a timing issue. And in fact, it's the timing of the docker engine and not the timing of the container.

When rebooting my Ubuntu 16.04 host, the Upstart system launches the docker engine which itself automatically launches the matterbridge container. When looking into the logs I then find out that the matterclient can't connect to the remote Mattermost host.

Killing the container and starting it again, does NOT solve the problem. What does help though is to restart the complete docker engine.

Now, to make that work for reboot as well, I've just included a sleep command into the pre-start script in /etc/init/docker.conf and that solved the problem. Still don't understand what's going wrong here.

**Comment by 42wim** [comment]
Ok, as this is a docker / firewall issue I'm going to close this.
