### ISSUE TITLE
Allow some form of robust templating

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#614]
Handlebar is a templating library that allows simple logic. It might be nice to use it to allow for more robust templating for certain types of messages/strings. 

One benefit of this is that comprehensive format rules could be set at `General` level, rather than setting them at each gateway.

Places to implement:

- `RemoteNickFormat`. Could allow for setting certain format based on protocol or. 
- messages that are unthreaded, re: https://github.com/42wim/matterbridge/pull/557
- message edits that can't be in-place, re: https://github.com/42wim/matterbridge/issues/588#issuecomment-441417020
- translated messages, re: https://github.com/42wim/matterbridge/pull/512
- `InitialComment` template, re: https://github.com/42wim/matterbridge/pull/606#discussion_r236061032

Seems the best library in go: https://github.com/aymerick/raymond

**Comment by patcon** [comment]
We could perhaps also use custom helpers to do away with config like "StripNick", as people could do that via templates: https://github.com/aymerick/raymond#helpers

**Comment by patcon** [comment]
Potential use-cases:
- Allow special avatar for system user.
- Allow messages to have quick-access permalink to original message if they're on the same team, for example, during translation.
- Append prefix if parent message is unthreaded.

**Comment by patcon** [comment]
Defaults here would be helpful, so might be nice to have a more robust default process, rather than simply empty strings or falsey values

**Comment by patcon** [comment]
Not sure whether mustache is the most appropriate engine, so generalizing this issue

**Comment by qaisjp** [comment]
Go has a text templating system in its standard library: [text/template](https://golang.org/pkg/text/template/).

**Comment by patcon** [comment]
Thanks @qaisjp! `text/template`'s looping didn't feel very friendly to the vast number of people more familiar with non-golang template engines -- and feels like templates would be very user-facing :)

**Comment by 42wim** [comment]
I think using tengo is the solution for this instead of templating, much more powerful

**Comment by patcon** [comment]
Good call. Closing out :) Thanks!
