### ISSUE TITLE
Connects to Inspircd IRC server but never joins channel

### ISSUE THREAD

**Issue by centinel** [42wim/matterbridge#62]
We've got a local instance of Inspircd that we'd like mirrored in Mattermost. It looks like Matterbridge can successfully connect to our server but never actually joins the channel specified in matterbridge.toml.

This behavior is the same (not surprisingly) whether I run Matterbridge from the Docker image or locally.

However, if I point Matterbridge to Freenode, it connects, joins a channel, and forwards messages perfectly fine.

This is the sample of debug output I see on the Inspircd server:

Wed Oct 26 12:29:29 2016: CONNECT: Client connecting on port 6667 (class main): matterbridge-bot!matterbridg@hostname.example.com (10.0.10.2) [matterbridge-bot]
Wed Oct 26 12:29:29 2016: BanCache: Adding NEGATIVE hit for 10.0.10.2
Wed Oct 26 12:29:49 2016: HandleEvent for Listensocket 10.0.11.253:6667 nfd=56
Wed Oct 26 12:29:49 2016: classbase::+ @0x899a080
Wed Oct 26 12:29:49 2016: New UUID for user: 2MIAAATWQ
Wed Oct 26 12:29:49 2016: classbase::+ @0x899a1c8
Wed Oct 26 12:29:49 2016: New user fd: 56
Wed Oct 26 12:29:49 2016: Setting connect class for UID 2MIAAATWQ
Wed Oct 26 12:29:49 2016: Checking unnamed-0
Wed Oct 26 12:29:49 2016: No host match (for 3ffe::0/32)
Wed Oct 26 12:29:49 2016: Checking main
Wed Oct 26 12:29:49 2016: New file descriptor: 56
Wed Oct 26 12:29:49 2016: Resolver::Resolver
Wed Oct 26 12:29:49 2016: DNSRequest::SendRequests
Wed Oct 26 12:29:49 2016: Sent OK
Wed Oct 26 12:29:49 2016: DNS request id 17196
Wed Oct 26 12:29:49 2016: AddResolverClass 0x08b582a0
Wed Oct 26 12:29:49 2016: Handle DNS event
Wed Oct 26 12:29:49 2016: Result id 82732
Wed Oct 26 12:29:49 2016: Error on FD 56 - 'Read Error'
Wed Oct 26 12:29:49 2016: QuitUser: 2MIAAATWQ=2MIAAATWQ 'Read Error'
Wed Oct 26 12:29:49 2016: DoWrite on errored or closed socket
Wed Oct 26 12:29:49 2016: Remove file descriptor: 56
Wed Oct 26 12:29:49 2016: Deleting 9LocalUser @0x899a080
Wed Oct 26 12:29:49 2016: InviteBase::ClearInvites 0x899a1b0
Wed Oct 26 12:29:49 2016: classbase::-13UserIOHandler @0x899a1c8
Wed Oct 26 12:29:49 2016: classbase::-9LocalUser @0x899a080
Wed Oct 26 12:29:49 2016: classbase::~ @0x899a1c8
Wed Oct 26 12:29:49 2016: classbase::~ @0x899a080
Wed Oct 26 12:30:00 2016: classbase::+ @0x8aa95f0
Wed Oct 26 12:30:00 2016: SetDefaultModes nt
Wed Oct 26 12:30:00 2016: classbase::+ @0x899aef0

**Comment by 42wim** [comment]
That debug message doesn't give any useful info except the read error. 
What does matterbridge -debug gives as output ?

**Comment by centinel** [comment]
Setting it to join the #mimtesting IRC channel:

INFO[2016-10-28T13:38:31-04:00] Starting bridge: irc.napoleon channel: #mimtesting 
INFO[2016-10-28T13:38:31-04:00] Starting bridge: mattermost.work channel: support 
INFO[2016-10-28T13:38:31-04:00] Connecting napoleon.mimsoftware.com:6667      module=irc
INFO[2016-10-28T13:38:31-04:00] Connection succeeded                          module=irc
INFO[2016-10-28T13:38:31-04:00] irc.napoleon: joining #mimtesting            
INFO[2016-10-28T13:38:31-04:00] Connecting matterbridge (team: mim-software) on mattermost.mimsoftware.com  module=mattermost
DEBU[2016-10-28T13:38:31-04:00] trying login mim-software matterbridge mattermost.mimsoftware.com  module=matterclient
DEBU[2016-10-28T13:38:32-04:00] initUser(): found our team mim-software (id: q1ihnqsitfnf5n4we5ar7os73o)  module=matterclient
DEBU[2016-10-28T13:38:32-04:00] WsClient: making connection                   module=matterclient
INFO[2016-10-28T13:38:32-04:00] Connection succeeded                          module=mattermost
INFO[2016-10-28T13:38:32-04:00] mattermost.work: joining support             
DEBU[2016-10-28T13:38:32-04:00] Not joining cnpx3fi9djfiznofjakbbezpuy already joined.  module=matterclient
DEBU[2016-10-28T13:38:32-04:00] Choosing API based Mattermost connection: true  module=mattermost
DEBU[2016-10-28T13:38:32-04:00] WsReceiver: model.WebSocketEvent{TeamId:"", ChannelId:"", UserId:"g8pgh68w3ifjfe5jfmdhmgu4hr", Event:"hello", Data:map[string]interface {}{"server_version":"3.4.0.3.4.0.7dc5eb6223d14406ee68bc3368fac9bd"}}  module=matterclient
DEBU[2016-10-28T13:38:32-04:00] Registering callbacks                         module=irc
DEBU[2016-10-28T13:38:32-04:00] ":irc.mimsoftware.com 001 matterbridge-bot :Welcome to the MIM IRC Network matterbridge-bot!matterbridg@genghis.mimsoftware.com"  module=irc
DEBU[2016-10-28T13:38:32-04:00] ":irc.mimsoftware.com 042 matterbridge-bot 2MIAAAUE8 :your unique ID"  module=irc
DEBU[2016-10-28T13:38:32-04:00] ":irc.mimsoftware.com NOTICE matterbridge-bot :*** You are connected using SSL cipher \"AES128-SHA\""  module=irc
DEBU[2016-10-28T13:40:38-04:00] PING/PONG                                     module=irc
DEBU[2016-10-28T13:40:38-04:00] "PING :irc.mimsoftware.com"                   module=irc

**Comment by 42wim** [comment]
Ok that looks like the irc connection works, if you join napoleon.mimsoftware.com with your client, does a /whois matterbridge-bot shows the bot ?

**Comment by centinel** [comment]
Yes, it appears if I do a WHOIS.

On October 28, 2016 4:40:21 PM EDT, "@42wim" <notifications@github.com> wrote:
>Ok that looks like the irc connection works, if you join
>napoleon.mimsoftware.com with your client, does a /whois
>matterbridge-bot shows the bot ?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/42wim/matterbridge/issues/62#issuecomment-257022806

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by 42wim** [comment]
Ok, that's good. Maybe it's a timing issue.
Could you add ```time.Sleep(time.Second*2)``` before the joinchannel ? https://github.com/42wim/matterbridge/blob/master/bridge/irc/irc.go#L84

And see if that fixes it ?

**Comment by centinel** [comment]
That did it. Matterbridge was able to successfully connect and join. 

On 2016-10-28 5:46 pm, @42wim wrote:

> Ok, that's good. Maybe it's a timing issue.
> Could you add time.Sleep(time.Second*2) before the joinchannel ? https://github.com/42wim/matterbridge/blob/master/bridge/irc/irc.go#L84 
> 
> And see if that fixes it ? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/42wim/matterbridge/issues/62#issuecomment-257036810
[2]

**Comment by 42wim** [comment]
Thanks for testing.
I'm committing a fix for this, could you rebuild from master and tell me if it works ?

**Comment by centinel** [comment]
Works for me. Thanks for the quick response!
