### ISSUE TITLE
Matterbridge did not join muc

### ISSUE THREAD

**Issue by ischtar** [42wim/matterbridge#63]
Hi
thanks for the good work :)
I've my Prosody and Mattermost running fine on the same server. 
Even when I start my bridge, every comment, written on the mattermostserver, reaches the bridge:
eg
EBU[2016-10-28T18:27:22+02:00] WsReceiver: model.WebSocketEvent{TeamId:"mctec4tqrir6fjrxueg9dupjnc", ChannelId:"7mahzujw3byutmgebxfawuozow", UserId:"qd35iaq7t7yw7g5boqt5s37uxy", Event:"posted", Data:map[string]interface {}{"post":"{\"id\":\"puuk3gmw4byf5e99upm6dbwdhc\",\"create_at\":1477672042028,\"update_at\":1477672042028,\"delete_at\":0,\"user_id\":\"qd35iaq7t7yw7g5boqt5s37uxy\",\"channel_id\":\"7mahzujw3byutmgebxfawuozow\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"miau\",\"type\":\"\",\"props\":{},\"hashtags\":\"\",\"filenames\":[],\"pending_post_id\":\"qd35iaq7t7yw7g5boqt5s37uxy:1477671964297\"}", "sender_name":"carola", "team_id":"mctec4tqrir6fjrxueg9dupjnc", "channel_display_name":"testcase", "channel_type":"O"}}  module=matterclient
DEBU[2016-10-28T18:27:22+02:00] Receiving from matterclient &matterclient.Message{Raw:(_model.WebSocketEvent)(0xc4203f58b0), Post:(_model.Post)(0xc420370700), Team:"nerdbase", Channel:"testcase", Username:"carola", Text:"miau"}  module=mattermost
DEBU[2016-10-28T18:27:22+02:00] Sending message from carola on mattermost.work to gateway  module=mattermost
I've tried to connect my bridge - xmpp User with gajim and it works fine too. 
I've also a Muc open and 2 other clients connected. But the Bridgeuser never joined the conference, and I've tried uncounted settings.

[xmpp]
    [xmpp.jabber]
    Server="myserver.de:5222"
    Jid="myjid@myserver.de"
    Password="mypass"
    Muc="conference@conference.myserver.de" #this is where the other users are waiting for mattermostnews :)
# but I've also tried: Muc="conference.conference.myserver.de"

[mattermost]
    [mattermost.work]
    useAPI=true
    Server="mymattermost.de"
    Team="myteam"
    Login="matteruser"
    Password="matteruserpass"
    PrefixMessagesWithNick=false

[[gateway]]
    name="gateway1"
    enable=true
    [[gateway.in]]
    account="mattermost.work"
    channel="testcase"

```
[[gateway.out]]
account="mattermost.work"
channel="testcase"
```

I hope you can help me, finding out, whats wrong. 
There are no problems shown in the prosody error files.

Thanks and regards
Carola

**Comment by 42wim** [comment]
Did you paste your whole config ? Your gateway.in and gateway.out are the same, you didn't add xmpp.jabber to gateway.in and gateway.out ?

**Comment by ischtar** [comment]
That's it!
Thanks a lot. For your work and your hint!

**Comment by 42wim** [comment]
Great to hear it works :)
