### ISSUE TITLE
Matterbridge stops handling multiple bridged channels on IRC with 1.12.1

### ISSUE THREAD

**Issue by erenfro** [42wim/matterbridge#639]
**Describe the bug**
Since Matterbridge 1.12.1, IRC gateways with multiple channels will connect to one channel, but stall afterwards if there's any other channels configured in gateways. This is working in 1.12.0.

**To Reproduce**
Setup multiple gateways with IRC for two or more channels.

**Expected behavior**
Connect to both IRC channels, and not stall.

**Screenshots/debug logs**
Dec 03 09:58:07 mm matterbridge[38054]: time="2018-12-03T09:58:07-05:00" level=debug msg="":kornbluth.freenode.net 903 linux-help :SASL authentication successful"" prefix=irc                 
Dec 03 09:58:07 mm matterbridge[38054]: time="2018-12-03T09:58:07-05:00" level=debug msg="":kornbluth.freenode.net 001 linux-help :Welcome to the freenode Internet Relay Chat Network linux-he
lp"" prefix=irc                                                                                                                                                                                
Dec 03 09:58:07 mm matterbridge[38054]: time="2018-12-03T09:58:07-05:00" level=debug msg=""CLIENT_GENERAL_UPDATED"" prefix=irc                                                                 
Dec 03 09:58:07 mm matterbridge[38054]: time="2018-12-03T09:58:07-05:00" level=debug msg="Registering callbacks" prefix=irc                                                                    
Dec 03 09:58:07 mm matterbridge[38054]: time="2018-12-03T09:58:07-05:00" level=debug msg=""CLIENT_GENERAL_UPDATED"" prefix=irc
Dec 03 09:58:07 mm matterbridge[38054]: time="2018-12-03T09:58:07-05:00" level=debug msg=""CLIENT_GENERAL_UPDATED"" prefix=irc
Dec 03 09:58:07 mm matterbridge[38054]: time="2018-12-03T09:58:07-05:00" level=debug msg=""CLIENT_GENERAL_UPDATED"" prefix=irc
Dec 03 09:58:07 mm matterbridge[38054]: time="2018-12-03T09:58:07-05:00" level=debug msg=""CLIENT_GENERAL_UPDATED"" prefix=irc
Dec 03 09:58:07 mm matterbridge[38054]: time="2018-12-03T09:58:07-05:00" level=debug msg=""CLIENT_GENERAL_UPDATED"" prefix=irc
Dec 03 09:58:07 mm matterbridge[38054]: time="2018-12-03T09:58:07-05:00" level=debug msg=""CLIENT_GENERAL_UPDATED"" prefix=irc
Dec 03 09:58:08 mm matterbridge[38054]: time="2018-12-03T09:58:08-05:00" level=debug msg=""CLIENT_GENERAL_UPDATED"" prefix=irc
Dec 03 09:58:09 mm matterbridge[38054]: time="2018-12-03T09:58:09-05:00" level=debug msg=""CLIENT_CONNECTED :irc.freenode.net:6697"" prefix=irc
Dec 03 09:58:13 mm matterbridge[38054]: time="2018-12-03T09:58:13-05:00" level=debug msg="":linux-help MODE linux-help :+Zi"" prefix=irc
Dec 03 09:58:13 mm matterbridge[38054]: time="2018-12-03T09:58:13-05:00" level=info msg="Connection succeeded" prefix=irc
Dec 03 09:58:13 mm matterbridge[38054]: time="2018-12-03T09:58:13-05:00" level=info msg="irc.linux-help: joining ##linux-help (ID: ##linux-helpirc.linux-help)" prefix=bridge
Dec 03 09:58:13 mm matterbridge[38054]: time="2018-12-03T09:58:13-05:00" level=info msg="irc.linux-help: joining ##linux-social (ID: ##linux-socialirc.linux-help)" prefix=bridge
Dec 03 09:58:13 mm matterbridge[38054]: time="2018-12-03T09:58:13-05:00" level=debug msg="handle girc.Event{Source:(*girc.Source)(0xc0003bbb60), Tags:girc.Tags(nil), Timestamp:time.Time{wall:0xbef96f014bb31d22, ext:18967369207, loc:(*time.Location)(0x18436a0)}, Command:"JOIN", Params:[]string{"##linux-help", "linux-help"}, Trailing:"linux-help", EmptyTrailing:false, Sensitive:false, Echo:false}" prefix=irc
Dec 03 09:58:13 mm matterbridge[38054]: time="2018-12-03T09:58:13-05:00" level=debug msg="333: Topic set by Psi-Jack [~psi-jack@unaffiliated/psi-jack] [2018-04-02 09:15:02 -0400 EDT]" prefix=irc
Dec 03 09:58:56 mm matterbridge[38054]: time="2018-12-03T09:58:56-05:00" level=debug msg="WS PING" prefix=matterclient
Dec 03 09:58:56 mm matterbridge[38054]: time="2018-12-03T09:58:56-05:00" level=debug msg="sendWsRequest &model.WebSocketRequest{Seq:2, Action:"ping", Data:map[string]interface {}(nil), Session:model.Session{Id:"", Token:"", CreateAt:0, ExpiresAt:0, LastActivityAt:0, UserId:"", DeviceId:"", Roles:"", IsOAuth:false, Props:model.StringMap(nil), TeamMembers:[]*model.TeamMember(nil)}, T:(i18n.TranslateFunc)(nil), Locale:""}" prefix=matterclient
Dec 03 09:58:56 mm matterbridge[38054]: time="2018-12-03T09:58:56-05:00" level=debug msg="WsReceiver response: model.WebSocketResponse{Status:"OK", SeqReply:2, Data:map[string]interface {}{"node_id":"", "server_time":1.543849136332e+12, "text":"pong", "version":"5.5.0"}, Error:(*model.AppError)(nil)}" prefix=matterclient
Dec 03 09:58:56 mm matterbridge[38054]: time="2018-12-03T09:58:56-05:00" level=debug msg="WS PONG received" prefix=matterclient
Dec 03 09:59:56 mm matterbridge[38054]: time="2018-12-03T09:59:56-05:00" level=debug msg="WS PING" prefix=matterclient
Dec 03 09:59:56 mm matterbridge[38054]: time="2018-12-03T09:59:56-05:00" level=debug msg="sendWsRequest &model.WebSocketRequest{Seq:3, Action:"ping", Data:map[string]interface {}(nil), Session:model.Session{Id:"", Token:"", CreateAt:0, ExpiresAt:0, LastActivityAt:0, UserId:"", DeviceId:"", Roles:"", IsOAuth:false, Props:model.StringMap(nil), TeamMembers:[]*model.TeamMember(nil)}, T:(i18n.TranslateFunc)(nil), Locale:""}" prefix=matterclient
Dec 03 09:59:56 mm matterbridge[38054]: time="2018-12-03T09:59:56-05:00" level=debug msg="WsReceiver response: model.WebSocketResponse{Status:"OK", SeqReply:3, Data:map[string]interface {}{"version":"5.5.0", "node_id":"", "server_time":1.543849196335e+12, "text":"pong"}, Error:(*model.AppError)(nil)}" prefix=matterclient
Dec 03 09:59:56 mm matterbridge[38054]: time="2018-12-03T09:59:56-05:00" level=debug msg="WS PONG received" prefix=matterclient

**Environment (please complete the following information):**
 - OS: Linux
 - Matterbridge version: version: 1.12.1 d2cfd23

**Additional context**
This does work in Matterbridge 1.12.0

**Comment by 42wim** [comment]
Thanks a lot for reporting.
Should be fixed in master now, dev binaries are available here: https://bintray.com/42wim/nightly/Matterbridge/v1.12.0-30-g27f5a1a#files

If it doesn't fix your issue, let us know :-)

**Comment by erenfro** [comment]
Looks good.. Tested and works! :+1:
