### ISSUE TITLE
Auto-reconnect to IRC

### ISSUE THREAD

**Issue by jleclanche** [42wim/matterbridge#64]
The IRC gateway I'm running died last night. It's running under supervisorctl and didn't crash, it just disconnected from IRC (which can happen for various reasons).

Once disconnected, it doesn't seem to attempt to reconnect. It also doesn't crash or give any way for a supervisor to restart it.

**Comment by 42wim** [comment]
https://github.com/thoj/go-ircevent, the library that mattermost uses should be doing this.
I'll have a look at it, but it's not high priority for now.

**Comment by jurgenhaas** [comment]
This is not only an issue with being disconnected from IRC, the same problem is when getting disconnected from Mattermost. This can happen for various reasons every now and then but Matterbridge doesn't seem to even try any re-connect, does it?

**Comment by 42wim** [comment]
It does, if it doesn't could you run with debug, try to reproduce it and open a new issue?

**Comment by jurgenhaas** [comment]
Found some more details about my sub-issue and reported that in #69

**Comment by dmendyke** [comment]
We are using version 0.9.2 to connect Mattermost to IRC.  If the network goes down for more than a few minutes, the connect is lost.  Only restarting Matterbridge re-establishes the connection.  Is this the same issue?

**Comment by 42wim** [comment]
I'm making some changes to handle disconnects/reconnects better.
It's in the status branch, https://github.com/42wim/matterbridge/tree/status
Only works for IRC now. Testing is appreciated :-)

**Comment by 42wim** [comment]
Merged in master now, feel free to reopen if issue isn't fixed.

**Comment by jwflory** [comment]
Hi, I am still having this issue as of April 2019. See FOSSRIT/infrastructure#45 for more information. Should I open a new issue for this?

**Comment by 42wim** [comment]
@jwflory I just fixed this in master
Binaries can be found here: https://bintray.com/42wim/nightly/Matterbridge/v1.14.2-10-g380c386#files

**Comment by qaisjp** [comment]
fixed in  380c386
