### ISSUE TITLE
IRC notice handling is highly dangerous

### ISSUE THREAD

**Issue by ishitatsuyuki** [42wim/matterbridge#65]
Not only it doesn't forward /notice, it also doesn't check if the sender is NickServ.
* [x] check integrity
* [x] forward notices

Another thing I noticed, should it forward private queries?

**Comment by 42wim** [comment]
Could you give an example of the problem? 
Private queries shouldn't be forwarded.

**Comment by ishitatsuyuki** [comment]
`NOTICE bot :This nickname is registered` will potentially waste the bot's resource, spamming nickserv, and this is not really a good behavior.
When I queried with the bot, everything is forwarded.

**Comment by 42wim** [comment]
Ok, thanks for reporting this.
Are you using master or 0.6.1 ?

**Comment by ishitatsuyuki** [comment]
I'm on master with a few commits behind.
The problematic code is https://github.com/42wim/matterbridge/blob/master/bridge/irc/irc.go#L148-L152.

**Comment by 42wim** [comment]
The nickserv-only notice and private queries got fixed. 
Not sure yet about whether or not to forward notices to the channel.

**Comment by 42wim** [comment]
Ok, channel notice is now treated the same way as channel messages.
