### ISSUE TITLE
Slack platform sends message with file before file is ready for download

### ISSUE THREAD

**Issue by jheiselman** [42wim/matterbridge#655]
**Description**
When matterbridge is configured with a MediaServer and it receives an event from the Slack platform that indicates a user uploaded a file (File object embedded in a MessageEvent), then the download can fail if matterbridge requests the file too quickly. This results in an HTML page getting downloaded instead (a redirect to the main login page on slack.com).

**To Reproduce**
This is incredibly hard to reproduce. It requires a request be made in well under a second.  

**Expected behavior**
The file should be downloaded properly so that it can be re-hosted/uploaded to the destination platform.

**Screenshots/debug logs**
None

**Environment (please complete the following information):**
 - OS: linux amd64
 - Matterbridge version: 1.12.3-dev

**Additional context**
I have completed a support request with Slack and they say that this is expected behavior. They have no plans to adjust the behavior of the platform. I have filed a formal request to have a new event type emitted (i.e. file_ready), but they aren't committing to adding it. Their only suggestion is to add a delay to the download routine.

I have written an update for the handleDownloadFile that attempts a single retry if the downloaded file size doesn't match what was originally declared in the File object on the MessageEvent and have been using it in my own environment for the last week. I will be submitting a PR to go along with this issue.

**Comment by patcon** [comment]
Ah, I've been seen the same thing on large files, esp images of very skewed dimensions (which presumably need to be queued for resize or something)

**Comment by patcon** [comment]
What if we detected the redirect, and retried X times (maybe with an exponential backoff)?

**Comment by patcon** [comment]
And fwiw, I don't use mediaserver, but still do get this HTML file downloaded fairly often

**Comment by jheiselman** [comment]
Unfortunately, it's an internal redirect. There is no outwardly easy way to detect it. You get a 200 HTTP status code and simply the wrong data.

That's why I went the method of simply checking the size. It's been 100% accurate so far in my testing. And while we can set a higher retry limit, it's not been necessary in my testing. The file is always available within one second. High traffic serversay have other results, but it didn't seem like a good idea to over-engineer before it was really necessary to do so.
