### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by git-sid** [42wim/matterbridge#657]
**Is your feature request related to a problem? Please describe.**
API documentation is afaik (almost) non-existent. I'm trying to switch from our own hacky cross-plattform messaging project to matterbridge. However it's a rather bumpy ride without documentation.
This also applies to code documentation, see #235

**Describe the solution you'd like**
Document the API and code. Services like https://readthedocs.org/ might help.

**Describe alternatives you've considered**
I've tried grasping the basic functionality by reading the code itself and the code of related projects. This however isn't very helpful as the exact functionality of the code is not specified anywhere.

**Comment by 42wim** [comment]
Even more documentation with a walkthrough example with curl is now on the wiki https://github.com/42wim/matterbridge/wiki/Api

This is hopefully enough information about the API now?
