### ISSUE TITLE
Add Cisco Teams support

### ISSUE THREAD

**Issue by shochdoerfer** [42wim/matterbridge#660]
**Is your feature request related to a problem? Please describe.**
I'd love to see a Cisco Teams connector to be able to connect our Mattermost instance to the Cisco Teams instance to exchange messages.

**Comment by 42wim** [comment]
Is it this product ? https://www.webex.com/products/teams/index.html ?
Seems like https://github.com/jbogarin/go-cisco-webex-teams is a good library to use for this. Anyone who want to PR this ? :)

**Comment by shochdoerfer** [comment]
Correct, that's the product

**Comment by 42wim** [comment]
I've been looking through the docs and found this

>  Differences Between Bots and People
One key difference between Webex Teams Bots and regular users is that, in group rooms, bots only have access to messages in which they are mentioned. This means that messages:created webhooks only fire when the bot is mentioned in a room.

https://developer.webex.com/docs/bots/differences-between-bots-and-people

This means that we can't receive messages from cisco teams unless the bot name is specifically mentioned.

I'm not sure if it would be useful to add support for this bridge as it doesn't seem very useful this way.

**Comment by shochdoerfer** [comment]
In that case I'd say skip the implementation until the needed permissions are implemented. We don't use Cisco Webex Teams but a client of ours.
