### ISSUE TITLE
Discord code block with language should cut off language on Slack

### ISSUE THREAD

**Issue by qaisjp** [42wim/matterbridge#668]
**Describe the bug**
Sending this on discord

````
```lua
print("hi")
```
````

Will appear as this on Slack:

```
lua
print("hi")
```

**To Reproduce**
Copy above text on discord, and observe slack.

**Expected behavior**
Only this should be sent to slack:

````
```
print("hi")
```
````

**Comment by 42wim** [comment]
Or it's a bug in slack :-)
Strange that they don't support this

**Comment by 42wim** [comment]
Are you willing to make a PR for this?
You could add another cleanup function for this (eg `stripCodeLanguage`) here https://github.com/42wim/matterbridge/blob/master/bridge/slack/handlers.go#L30-L34 and add it to the https://github.com/42wim/matterbridge/blob/master/bridge/slack/helpers.go file

**Comment by qaisjp** [comment]
Yes, totally willing. Indeed strange they don't support it. Thanks for showing me the files, I wasn't sure where to make the changes
