### ISSUE TITLE
Feature Request: {PROTOCOL} output customization

### ISSUE THREAD

**Issue by Arinerron** [42wim/matterbridge#669]
**Is your feature request related to a problem? Please describe.**
We can't customize the RemoteNickFormats as much as I would like. For example, if the protocol was telegram and I wanted to make `{PROTOCOL}` output a a different protocol than `telegram` like `TELEGRAM` in caps, it wouldn't be possible.

**Describe the solution you'd like**
In the configuration file, it should support a map of `{PROTOCOL}` : `output` or something so that I can customize the output of `{PROTOCOL}`.

**Describe alternatives you've considered**
The reason why I want this is so that on Discord I can make the `RemoteNickFormat` output emojis for the protocol rather than the text. I tried doing `:{PROTOCOL}:` in the `RemoteNickFormat`, but it doesn't work because I need emoji ids which are unique to each emoji.

**Comment by Arinerron** [comment]
Possible duplicate of https://github.com/42wim/matterbridge/issues/614

**Comment by 42wim** [comment]
There is a `label=` option
https://github.com/42wim/matterbridge/blob/015c0763153778779857597178a0aabd7ac1215a/matterbridge.toml.sample#L1249-L1251

which can be used in `RemoteFormatNick`

https://github.com/42wim/matterbridge/blob/015c0763153778779857597178a0aabd7ac1215a/matterbridge.toml.sample#L1268-L1274

**Comment by Arinerron** [comment]
@42wim Thanks for the response! Can the label have dynamic value (based on `{PROTOCOL}`)?

**Comment by 42wim** [comment]
You specify what you want with the label.
So in your `[telegram.name]` config you add `label=TELEGRAM`

**Comment by Arinerron** [comment]
Sweet, thank you very much!

**Comment by patcon** [comment]
Related to dynamic templating: https://github.com/42wim/matterbridge/issues/614
