### ISSUE TITLE
"Error obtaining guild members" in Discord

### ISSUE THREAD

**Issue by nylen** [42wim/matterbridge#672]
**Describe the bug**

It's easy to get the following error "Error obtaining guild members" when trying to configure a bridge with Discord.  I tried a couple of different things before I finally got it working:

- `Server="NUMERIC_ID"`
- `Server="myworkspace"`
- `Server="MyWorkspace"` (This is what finally worked).

**To Reproduce**

Enter the wrong value in the `Server` directive for a Discord server/guild.

**Expected behavior**

A better error message for this case.  Here is some relevant code:

https://github.com/42wim/matterbridge/blob/0365c0786a6bf95b7d598d25402d9a1d28ab8036/bridge/discord/discord.go#L82-L93

Probably, at the end of this block, `b.guildID` is not set.  A little later, we get to here:

https://github.com/42wim/matterbridge/blob/0365c0786a6bf95b7d598d25402d9a1d28ab8036/bridge/discord/discord.go#L107-L111

This error is confusing - I'd suggest instead detecting when no guild ID was found, and displaying a list of the possible values for the `Server` directive based on the available guilds.

Also, the second error message is missing a space:

```diff
-Error obtaining guild membersHTTP 404 Not Found, {"code": 0, "message": "404: Not Found"}
+Error obtaining guild members: HTTP 404 Not Found, {"code": 0, "message": "404: Not Found"}
```

**Comment by 42wim** [comment]
Good points! 👍 
Not sure why the `Server="NUMERIC_ID"` doesn't work for you, it should work (and I've just tested it again and it does).

If you have the time could you submit a PR for a better error message and the typo?
