### ISSUE TITLE
Help setting up Discord username/avatar spoofing?

### ISSUE THREAD

**Issue by nylen** [42wim/matterbridge#679]
I'd like to get matterbridge to send messages with avatars and nicknames in Discord, so that it looks nicer than this:

![2019-01-04t20 22 39-05 00](https://user-images.githubusercontent.com/227022/50749778-371d7e80-120f-11e9-8ecc-6fc5f5c090a0.png)

I see https://github.com/42wim/matterbridge/wiki/Section-Discord-(basic)#usernameavatar-spoofing but this is confusing me.  I've tried setting up a webhook and putting it in a few places in the config file, but no changes.

I have most of the channels set up using a `[[samechannelgateway]]`, which ideally I'd like to keep, but it looks like maybe #674 needs to be solved first?  Here's the relevant part of my config file:

```
[[gateway]]
name="testing"
enable=true

[[gateway.inout]]
account="slack.classicpress"
channel="testing"

[[gateway.inout]]
account="discord.classicpress"
channel="testing"
WebhookURL="https://discordapp.com/api/webhooks/thing1/thing2"
```

Edit: I've also tried putting the `WebhookURL` under the main `[[gateway]]` section, it didn't work that way either.

I am also not sure what a channel-specific webhook for each channel has to do with username/avatar spoofing, or why that's a requirement.  Can someone explain that part?

Hopefully we can feed the answers to these questions back into better documentation on that Discord page.

**Comment by patcon** [comment]
Heyoooo! For the troubleshooting, can you share your logs with `-debug` flag set, during connect (and posting a message, if you can get that far)?

> I am also not sure what a channel-specific webhook for each channel has to do with username/avatar spoofing, or why that's a requirement. Can someone explain that part?

[Creating a message](https://discordapp.com/developers/docs/resources/channel#create-message) via a user's api token only lets the gateway post with the user/avatar that generated the token. But [executing a webhook](https://discordapp.com/developers/docs/resources/webhook#execute-webhook) can set any old username/avatar.

> Hopefully we can feed the answers to these questions back into better documentation on that Discord page.

I LIKE THE WAY YOU THINK. Not to pawn off the task, but if the above explanation makes sense, might you be down to update the wiki with whatever would make sense to nylen-from-the-past?

**Comment by nylen** [comment]
Solved - I was missing the `[gateway.inout.options]` block.

Thanks for the additional info!  I've updated https://github.com/42wim/matterbridge/wiki/Section-Discord-(basic)#usernameavatar-spoofing with what I learned here, so I think this issue is done.

**Comment by poVoq** [comment]
The problem is actually that the documentation is wrong :)
@qaisjp the webhook url needs to be in the guild specific [discord] section if the bot has permissions to edit webhooks, not the [[gateway]].

**Comment by qaisjp** [comment]
Pls can you fix the docs @poVoq

**Comment by poVoq** [comment]
@qaisjp ok I think that is clearer now:
https://github.com/42wim/matterbridge/wiki/Section-Discord-(basic)#usernameavatar-spoofing

**Comment by qaisjp** [comment]
yay
