### ISSUE TITLE
matrix: plain text messages should not have html formatting

### ISSUE THREAD

**Issue by jrick** [42wim/matterbridge#686]
The `formatted_body` field of a matrix message should only be present when the message contains formatting that can not be expressed by the plain text `body` field.  However, this field is now being populated for every single matrix message being created.

[example message](https://matrix.to/#/!VFRvyndKpzcLrVslQD:decred.org/$154707001512568ilRFq:decred.org?via=decred.org&via=matrix.org&via=zettaport.com)

example source:

```
{
  "content": {
    "body": "[slack/dhill] testing bob",
    "format": "org.matrix.custom.html",
    "formatted_body": "[slack/dhill] <p>testing bob</p>\n",
    "msgtype": "m.text"
  },
  "event_id": "$154707001512568ilRFq:decred.org",
  "origin_server_ts": 1547070015547,
  "sender": "@bridge:decred.org",
  "type": "m.room.message",
  "unsigned": {
    "age": 504
  },
  "room_id": "!VFRvyndKpzcLrVslQD:decred.org"
}
```

I would expect the formatted body to only be present if the message contained formatting such as bold, italics, lists (numbered or bullet), etc.

**Comment by 42wim** [comment]
What's the issue with having it for every message ? Is there any impact ?

**Comment by jrick** [comment]
It's an optimization, it doesn't violate the [spec](
https://matrix.org/docs/spec/client_server/r0.4.0.html#m-room-message-msgtype) or break clients, but it's common for clients to perform this operation to reduce the overall message size.

**Comment by groug** [comment]
Hi,

I'm detecting the same thing, but it's more of a problem for me:
The use of the < p > tag makes a new line between RemoteNickFormat and the body.
Contrary to the other bridges, a 1-line message bridged to matrix creates a 2-lines message (but a 1-line message from matrix creates a 1-line message to other bridges.

FYI, I'm using riot (web and mobile client) for the matrix bridge.

NB: I'm only using matrix and xmpp bridges, when I say "other bridges", I can only talk about xmpp, I'm assuming this is the case for all bridges from the screenshots (even though the screenshot about matrix/riot doesn't show this space between the RemoteNickFormat and the rest of the body).

Apart from that, thanks for this great work, with docker, it took me less than 10 min to connect xmpp and matrix :)

**Comment by 42wim** [comment]
Fixed in master or dev build on https://bintray.com/42wim/nightly/Matterbridge/v1.14.0-rc2-3-g67f2c67#files
