### ISSUE TITLE
matrix: <code> elements are not created from properly-parsed markdown

### ISSUE THREAD

**Issue by jrick** [42wim/matterbridge#687]
The markdown parsing being done to create `<code>` elements in matrix html formatted message bodies is not being done correctly.  [For example](https://matrix.to/#/!HEeJkbPRpAqgAwhXWO:decred.org/$154709170912695Dzrms:decred.org?via=decred.org&via=matrix.org&via=zettaport.com):

```
{
  "content": {
    "body": "[slack/github] #19 gulp browser failed\n```$ gulp browser\n[11:41:22] Using gulpfile xxx/gulpfile.js\n[11:41:23] Task 'browser' is not in your gulpfile\n[11:41:23] Please check the documentation for proper gulpfile formatting\n```",
    "format": "org.matrix.custom.html",
    "formatted_body": "[slack/github] <p>#19 gulp browser failed</p>\n<pre><code class=\"language-$\">[11:41:22] Using gulpfile xxx/gulpfile.js\n[11:41:23] Task 'browser' is not in your gulpfile\n[11:41:23] Please check the documentation for proper gulpfile formatting\n</code></pre>\n",
    "msgtype": "m.text"
  },
  "event_id": "$154709170912695Dzrms:decred.org",
  "origin_server_ts": 1547091709272,
  "room_id": "!HEeJkbPRpAqgAwhXWO:decred.org",
  "sender": "@bridge:decred.org",
  "type": "m.room.message",
  "unsigned": {
    "age": 37611714
  },
  "user_id": "@bridge:decred.org",
  "age": 37611714
}
```

Notice how the first line from the beginning of the markdown code section in the plain text body is missing entirely from `<code>` element in the formatted body, with only the $ from the prompt in the first line appearing in the class attribute.  It appears that it is trying to use the first line in the markdown code section as a language class for the html `<code>` element.

This should instead be parsed as:

```
<pre>
<code>
$ gulp browser
[11:41:22] Using gulpfile xxx/gulpfile.js
[11:41:23] Task 'browser' is not in your gulpfile
[11:41:23] Please check the documentation for proper gulpfile formatting
</code>
</pre>
```

**Comment by patcon** [comment]
Isn't this more that riot is not honouring a very common markdown convention of reserving the first line for language type? I'd never heard of code appearing on the same line as the initial triple-backtick, and that being above board.

**Comment by jrick** [comment]
Riot isn't rendering the markdown.  The markdown is coming from other bridged platforms, and matterbridge parses this markdown to create an html message, which riot displays (if it is present, otherwise it uses the plain text body).

**Comment by patcon** [comment]
What platform is that format coming from?

**Comment by jrick** [comment]
It's the GitHub notification bot on slack.

**Comment by 42wim** [comment]
The behaviour is according to the commonmark spec https://spec.commonmark.org/0.28/#fenced-code-blocks. It should have `\n` after ` ``` ` otherwise the first thing is taken as language specification.

You can better open a bug/issue with the Github notification bot.

**Comment by patcon** [comment]
Which GitHub notification bot btw?

Is it the main one (https://github.com/integrations/slack), or a custom one?
