### ISSUE TITLE
Support setting the matterbridge.toml location in docker

### ISSUE THREAD

**Issue by 333fred** [42wim/matterbridge#688]
**Is your feature request related to a problem? Please describe.**
If I'm attempting to simply deploy matterbridge as a docker container to Azure, I can't map individual files like I can when running docker manually. I can only map entire directories, which means I can't put the bridge file in `/matterbridge.toml`.

**Describe the solution you'd like**
It'd be nice to be able to define an environment variable to allow me to tell matterbridge that my config is in a subdirectory, so I don't have to try and create a custom startup script or wrap the matterbridge docker container just to place a config file.

**Comment by 42wim** [comment]
Just put the matterbridge.toml file in a empty directory that you can map and run with:

`docker run -ti -v /adirectorycontainingmatterbridgetoml:/somewhere 42wim/matterbridge -conf /somewhere/matterbridge.toml`

**Comment by 333fred** [comment]
Unfortunately, I don't think that will work either. I may be missing something, but from what I can see of the Azure container docs, there's no way to pass arguments to a docker container.

**Comment by 42wim** [comment]
Don't use azure myself but a quick google shows me that it's possible to specify extra arguments (would be weird if this wasn't possible). 

See https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-create `--command-line`

**Comment by 42wim** [comment]
try `--command-line="/bin/matterbridge -conf /somewhere/matterbridge.toml -debug"` that should work according to their documentation, what output does that give ? ofcourse you have to mount the `/somewhere` also correct.

**Comment by 333fred** [comment]
That did it, thanks @42wim!

**Comment by 333fred** [comment]
I appreciate the patience: Docker is very much outside my normal wheelhouse.

**Comment by KrzysztofMadejski** [comment]
@333fred what Azure's resource did you use? I used `Web App Service` but it is getting killed / disabled and it is not relying messages. I believe because without any external events (page views) it gets shut down. Did you use sth else? `Function App`?

Some of my experiences and findings:
1. I used `Web App Service`
1. In order to provide the config create `Storage Service` and configure it in App's `Application Settings` section `Mount storage`.
2. In `Container settings` point to it setting `Startup File` to `-conf /home/config/matterbridge.toml` (without the binary)
3. It worked for few minutes, but then get stopped. I believe because the process has no public URL and Azure killed it thinking something is not working.. Or the service is not invoked externally so it got down.

**Comment by KrzysztofMadejski** [comment]
@333fred did you find any frontend/portal way to mount the blob rather then [the command line](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-azure-files). If you used command line, do you know is it possible to mount volume to existing container? The examples provided above explain how to do it while *creating* container.

I plan to document the deployment in detail in the wiki if I get this running.

**Comment by KrzysztofMadejski** [comment]
Yes, I managed to start it. Had to use console to mount the drive. I keep the configuration file versioned on Github and set tokens as env variables.

```
az container create \
    --resource-group matterbridge \
    --name matterbridge-container \
    --image 42wim/matterbridge:1.13.0 \
    --os-type Linux \
    --restart-policy OnFailure \
    --command-line "/bin/matterbridge -conf /home/config/matterbridge.toml" \
    --gitrepo-url https://github.com/Code-for-All/matterbridge-config \
    --gitrepo-mount-path /home/config
```

Doc: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-gitrepo

**Comment by KrzysztofMadejski** [comment]
I documented the process here: https://github.com/42wim/matterbridge/wiki/Deploy:-Azure

**Comment by 42wim** [comment]
@KrzysztofMadejski thanks for this, much appreciated! 👍
