### ISSUE TITLE
Re-connecting to Mattermost fails

### ISSUE THREAD

**Issue by jurgenhaas** [42wim/matterbridge#69]
I'm running matterbridge in a Docker container and see a disconnect at night with the following debug output:

```
ERRO[2016-11-02T02:11:49Z] error:websocket: close 1006 (abnormal closure): unexpected EOF  module=matterclient
DEBU[2016-11-02T02:11:49Z] trying login paragon USERNAME mattermost.example.com  module=matterclient
DEBU[2016-11-02T02:11:49Z] Post https://mattermost.example.com/api/v3/users/login: read tcp 1.2.3.4:37640->5.6.7.8:443: read: connection reset by peer  module=matterclient
```

The third line shows that it tries once to reconnect and after that the log output is empty - no more re-tries.

What could be the case is that at that time, Apache - which is the proxy in front of Mattermost - had to be stopped in order to renew SSL certificates. That process takes a few seconds and then Apache gets started again.

If there is a correlation between the two events, I wonder if Matterbridge could re-try more often to establish a broken connection again?

**Comment by jurgenhaas** [comment]
Wow, that was quick :-) Any idea how long it takes until the new image is available?

**Comment by 42wim** [comment]
I just triggered the build, should be available in a few minutes
