### ISSUE TITLE
Regex for Ignore Nicks

### ISSUE THREAD

**Issue by dg01d** [42wim/matterbridge#690]
When used in a popular irc channel, there are certain messages from other users bridges which I would prefer not to bridge to my endpoint. These bridges use a particular methodology to show usernames in the channel - usually by adding non-word chars (such as `[..]` or `^..*`) to the usernames. 

It would be great if matterbridge would allow filtering of messages from usernames based on regex. This would allow removal of those messages quite simply.

This would be fine if other bridges all used the same methods as matterbridge - viz. declaring the message as _from_ a bot, with the remote username in the message content, as you've kindly made regex filtering available on message content. It doesn't help with usernames, though.

**Comment by patcon** [comment]
Yeow! Thanks so much, @dg01d. if you have space to dive in yourself, the relevant code is here :)

https://github.com/42wim/matterbridge/blob/d99eacc2e1b0deadc7368b35adf0818493fd2fb9/gateway/gateway.go#L240-L270

If you don't have time to set up a local env, you can pretty easily test the codepath using golang playground and submit via UI. I've quickly set up a minimal working segment of the code -- just be careful not to copy-paste it wholesale back into PR, as I changed the logging a bit to avoid needing the logrus package :)
https://play.golang.org/p/pOagnaQdBIs
