### ISSUE TITLE
Zulip integration is missing critical error-handling

### ISSUE THREAD

**Issue by timabbott** [42wim/matterbridge#694]
The matterbridge Zulip integration does not follow our API guidelines for the `get_events` request.  See https://zulipchat.com/api/get-events-from-queue.  Specifically, it ignores the `BAD_EVENT_QUEUE_ID` error condition, and thus if the event queue is ever garbage-collected, matterbridge will run in an infinite loop hitting the `GET /events` API with invalid input, which can contribute to server load.

Matterbridge code here: https://github.com/42wim/matterbridge/blob/master/bridge/zulip/zulip.go#L103

The fix is to check the events output as described.  You can see a sample implementation here: https://github.com/zulip/python-zulip-api/blob/master/zulip/zulip/__init__.py#L643

**Comment by 42wim** [comment]
Thanks for reporting and the pointers on how to fix it.
I'll take a more detailed look at it later this week.

**Comment by Helcaraxan** [comment]
From the little I've been able to gather this is actually an issue with the [matterbridge/gozulipbot](https://github.com/matterbridge/gozulipbot) dependency (which hasn't been updated in 2+ years and neither have any forks). It's code does not appear [able to handle](https://github.com/matterbridge/gozulipbot/blob/master/queue.go#L173) the `BAD_EVENT_QUEUE_ID` condition.

**Comment by 42wim** [comment]
@Helcaraxan matterbridge uses the work branch of matterbridge/gozulipbot
I've been adding extra stuff there, also a fix for this now :-)

**Comment by Helcaraxan** [comment]
@42wim good to know. Would be handy if we could document that somewhere in a code-comment or likewise. 🙂
