### ISSUE TITLE
[matrix] Allow formatting in RemoteNickFormat

### ISSUE THREAD

**Issue by gazpachoking** [42wim/matterbridge#696]
**Is your feature request related to a problem? Please describe.**
When a bot is relaying messages to the matrix room, it's hard to differentiate between the remote username and the content of the message.

**Describe the solution you'd like**
I'd like to be able to set up the RemoteNickFormat for matrix to contain some formatting, e.g. `<code>{NICK} ({PROTOCOL})</code> `.

**Additional context**
Here's an example of my goal in a gitter room:
![image](https://user-images.githubusercontent.com/187133/51999433-c45b9800-2488-11e9-85bf-15b07fc5a617.png)

**Comment by Helcaraxan** [comment]
@gazpachoking what are you particularly looking for that is not already possible with the current `RemoteNickFormat`?

The string that you put in this configuration is copied _as is_ modulo the expansion of the described fields like `{NICK}`, etc. You can literally put any-kind of formatting that you would write yourself in a message on Matrix for a given effect and use the same thing in `RemoteNickFormat`.

**Comment by gazpachoking** [comment]
I'm trying to have it formatted as code, I tried surrounding it with backticks, as well as with <code></code>, but they came out literally, rather than formatting the contained nick. I was assuming the `EscapeString` call here is what was preventing my formatting.

https://github.com/42wim/matterbridge/blob/430b38e77078d2b06145d782877c05d1aa18708c/bridge/matrix/matrix.go#L117

Maybe I just don't know the right way to format with matrix?

**Comment by gazpachoking** [comment]
Here's a picture of my attempts, along with comments marked up in orange.
![image](https://user-images.githubusercontent.com/187133/52182697-a4500f80-27cd-11e9-927b-f4116f5da64c.png)

**Comment by Helcaraxan** [comment]
I can't say anything definitive before having had a look at the underlying code but I would categorise this as a bug rather than a feature.

Thank you very much for raising this!

**Comment by 42wim** [comment]
The problem here is that some nicks can contain html stuff which give issues.
For example if you use `RemoteNickFormat="<{NICK}> "` the nick will not show up on the matrix side because it isn't vaild HTML.

**Comment by gazpachoking** [comment]
Yeah, I was suspecting that was the reason for the escaping. It seems like the actual nick should be escaped though, before it gets inserted into the RemoteNickFormat

**Comment by 42wim** [comment]
That doesn't fix the problem if you have `RemoteNickFormat="<{NICK}> "`,
Even if the actual nick (being `{NICK}`) is escaped you still have the `<` and `>` from `RemoteNickFormat`.

**Comment by gazpachoking** [comment]
Hmm, true. I guess in that case it'd be up to the user to escape things in RemoteNickFormat like `&lt;{NICK}&gt;` which isn't so nice either, but at least would allow formatting.

**Comment by gazpachoking** [comment]
Maybe if markdown was allowed in RemoteNickFormat like it is in the message? If the nick itself got escaped before inserting it into the RemoteNickFormat, and the RemoteNickFormat rendered any markdown to html for the html version of the message it might be a nice compromise.

**Comment by 42wim** [comment]
Ok, I've maybe have a solution. 
I can detect if the `RemoteNickFormat` contains a closing html tag, eg `</.*?>` if that's the case I'm not going to htmlescape the nick.

**Comment by LucesEnBabel** [comment]
I'd like to re-open this issue, since I'm having the same problem with the latest version of Matterbridge. It is flat out ignoring any markdown formatting I put in RemoteNickFormat, if I send markdown from Discord to Matrix in the message body, it will format the message correctly. 

Is there an option I forget to check?

**Comment by 42wim** [comment]
@LucesEnBabel this is about HTML formatting, what markdown format are you setting in the RemoteNickFormat ? and can't you set HTML formatting there?
