### ISSUE TITLE
Slack Username/Avatar spoofing?

### ISSUE THREAD

**Issue by laundmo** [42wim/matterbridge#697]
### Environment

Version:
1.13.0

Operating system:
Windows 10 64-bit

### Please describe the expected behavior.
slack username spoofing working like in discord, by adding WebhookURL to the config

### Please describe the actual behavior. 

messages on slack appear to be sent from the bot user

### Any steps to reproduce the behavior?
set up a discord<-->slack bridge with both discord and slack having a webhookurl config value

### Please add your configuration file 

[matterbridge_anonimized.txt](https://github.com/42wim/matterbridge/files/2814990/matterbridge_anonimized.txt)

**Comment by Helcaraxan** [comment]
Hello @laundmo,

I am not entirely sure what you are referring to but the Slack bridge _should_ be replacing the bot's username with a string that follows the `RemoteNickFormat` that you specify in the bridge's configuration.

There will still though be a `bot` marker next to it but that is how Slack Apps and their bots work and has nothing to do with Matterbridge. 🙂 

If I misinterpreted your question do correct me. I would very much like to help you get what you want (in as far as it is technically possible).

**Comment by laundmo** [comment]
im just gonna share some screenshots of me testing it, maybe that will clarify what i meant:

![](https://i.imgur.com/hblmSuc.png)

![](https://i.imgur.com/adL5CK9.png)

i expected slack username to be `laundmo@discord|->`

**Comment by Helcaraxan** [comment]
Ok. I understand better now. This is unfortunately nothing that can be changed as it is due to Slack's permissions model. Webhook based message posting does unfortunately not allow one to modify the name of the poster. For this to work you need to use the Slack App / Token setup described on the wiki.

Let me know if you have any more questions with which I can help. 🙂

**Comment by laundmo** [comment]
figured it out

### fix: remove `PrefixMessagesWithNick=true` from salck config

**Comment by patcon** [comment]
Just so we can file a bug (if this was one), can you share if you also changed to the api token model (instead of slack webhooks)? Would be great if we could improve the docs or defaults and prevent the next person from getting confused by this :)

**Comment by laundmo** [comment]
ah, i was using that from the start (as can be seen from the text file attached to the original issue)

i just added a webhook additionally, like you need to do to make spoffing for discord work.
