### ISSUE TITLE
Unable to build 1.13.0

### ISSUE THREAD

**Issue by ArchangeGabriel** [42wim/matterbridge#698]
**Describe the bug**
During build:
```
go: verifying github.com/labstack/echo@v3.3.5+incompatible: checksum mismatch
	downloaded: h1:Y3vG4kINVWNQN8Y6Jdur8uLat7fSLV5n5yLE8n+JbF4=
	go.sum:     h1:9PfxPUmasKzeJor9uQTaXLT6WUG/r+vSTmvXxvv3JO4=
```

**To Reproduce**
Get the sources, extract them, run `go build -v`.

**Expected behavior**
Building fine.

**Environment (please complete the following information):**
 - OS: ArchLinux
 - Matterbridge version: 1.13.0

**Comment by 42wim** [comment]
Quick search finds: https://github.com/golang/go/issues/29278

Quick fix for you is to do a `go build -mod vendor` that should build.

I'll look later for a better solution.

**Comment by ArchangeGabriel** [comment]
Well a better solution is apparently upgrading the checksum, but this requires everyone to build with go 1.11.4+. Since the issue is known, for now I’ll just sed the corresponding sum locally.

**Comment by 42wim** [comment]
https://github.com/labstack/echo/issues/1272 could also be related instead of an issue with go

**Comment by ArchangeGabriel** [comment]
It definitively is. They moved the tag, so the checksum does not match. Wether they will move it back or not is currently unsure.

**Comment by alexaandru** [comment]
The tags were just restored, I apologize for the inconvenience. Could you please confirm that you can build ok?

**Comment by 42wim** [comment]
@alexaandru race condition here, I've just released a new version using labstack/echo/v4 :-)
Just tested again with v1.13.0 and this release now builds also ok.
Thanks!

**Comment by ArchangeGabriel** [comment]
@alexaandru I can also confirm it builded OK here. :)

@42wim That was the better thing to do anyway. ;)

**Comment by alexaandru** [comment]
Thank you very much! :) Just please make sure that using V4 won't cause any issues, it is a major release after all. Please make sure you do read the release notes to spare you of any trouble: https://github.com/labstack/echo/releases/tag/v4.0.0 and the README: https://github.com/labstack/echo/tree/v4.0.0#supported-go-versions

Have a great day!

**Comment by 42wim** [comment]
@alexaandru thanks, btw regarding to go-versions I can still build matterbridge with go1.9.x because of the fact I'm also still using `go mod vendor` to have the vendor directory available for older versions (which still works fine with the  `/v4` change of echo)

**Comment by alexaandru** [comment]
Very nice, great then! :)
