### ISSUE TITLE
Link unfurling in Slack not working consistently

### ISSUE THREAD

**Issue by KrzysztofMadejski** [42wim/matterbridge#699]
**Is your feature request related to a problem? Please describe.**
Slack unfurls links by default (providing a thumbnail). I have slack-slack bridge and a link was not unfurled in one case (it was in another). The link was not highlighted as a link in the first case.

**Describe the solution you'd like**
It would be great if it would work consistently.

I don't see it as a major issue though.

**Additional context**
Original channel:
![link1](https://user-images.githubusercontent.com/849975/52199295-f6dd0a80-2865-11e9-9134-0b4d11251976.png)

Forwarded:
![link2](https://user-images.githubusercontent.com/849975/52199298-f9d7fb00-2865-11e9-9e4b-e0c95ff6feb0.png)

**Comment by Helcaraxan** [comment]
Have found the probable root-cause of this behaviour:
https://api.slack.com/docs/message-link-unfurling#classic_unfurling

> By default we unfurl all links in any messages posted by users. For messages posted via incoming webhooks, the chat.postMessage API method or chat.postEphemeral, we will unfurl links to media, but not other links.

I'll add the override flags in a PR given that we use the `chat.postMessage` method.
