### ISSUE TITLE
charset trouble when irc to mattermost

### ISSUE THREAD

**Issue by rizys** [42wim/matterbridge#7]
Hi,

The plugin is great !
But i'm french and when there are accents in IRC sentences, mattermost shows strange characters.
Can you make matterbridge converting to the right charset, even if you need to create a new option in the conf file to give you the outgoing charset ?

Thanks,
Rémi

**Comment by 42wim** [comment]
Is it possible to show a screenshot of those strange characters ? And what they should be?

**Comment by it33** [comment]
@rizys, we've had reports of some browsers in Mattermost showing strange characters but we're not able to reproduce the issue. Could you join #matterbridge on freenode and post the characters causing issue? 

They'll show up in the core team's Mattermost instance and we'll have a better chance of tracking down the issue.
