### ISSUE TITLE
Hide some messages from the bridge

### ISSUE THREAD

**Issue by 42wim** [42wim/matterbridge#70]
Do not forward messages to bridges when they started with a specific prefix.

**Comment by NikkyAI** [comment]
would it be possible to specifiy a regex for messages and/or users that has to match before sending it to the bridge?
defaults would be `.*` obviously

**Comment by 42wim** [comment]
IgnoreMessages has been added for each protocol
```
#Messages you want to ignore.
#Messages matching these regexp will be ignored and not sent to other bridges
#See https://regex-golang.appspot.com/assets/html/index.html for more regex info
#OPTIONAL (example below ignores messages starting with ~~ or messages containing badword
IgnoreMessages="^~~ badword"
```
