### ISSUE TITLE
Zulip per gateway Topic configuration

### ISSUE THREAD

**Issue by AJolly** [42wim/matterbridge#701]
I'd like to be able to set Zulips topic per gateway, rather than per bridge. 
Currently, the topic is a bridge setting, and channel (stream in Zulips language) is configured per gateway.   

**Describe the solution you'd like**
Add an ability to override the bridge setting and set Zulips topic per gateway:  
For example:

```
[zulip.streamchat]
Token="Token"
Login="botlogin"
Server="ZulipServerAddress/"

#Topic of the messages matterbridge will use
Topic="defaulttopic"

[[gateway]]
name="chat"
enable=true
	
	[[gateway.inout]]
	account="zulip.streamchat"
	channel="streamname"
	Topic="overridetopic"

```

**Comment by patcon** [comment]
Seems like a good idea! Thoughts @42wim? I think channel options would be the place we'd store this, at least by the conventions we've been using:

https://github.com/42wim/matterbridge/blob/fb713ed91bfb48c0037e489f80be85c54e69953a/bridge/config/config.go#L146-L149

https://github.com/42wim/matterbridge/blob/2cfd880cdb0df29771bf8f31df8d990ab897889d/matterbridge.toml.sample#L1395-L1410

Is this something you'd be curious to take a swing at implementing @AJolly?
