### ISSUE TITLE
irc: IRCCloud editing support

### ISSUE THREAD

**Issue by 54** [42wim/matterbridge#706]
**Is your feature request related to a problem? Please describe.**

Currently, when messages in other chat applications, like Discord, get deleted or edited, they remain as they remain as they were prior to deletion in IRC. This is a little annoying.

**Describe the solution you'd like**

Ideally, it'd be great to get some IRC v3 support to resolve this issue, if possible. This should allow for a more seamless experience when using v3 clients, like IRCCloud.

**Additional context**

https://ircv3.net/faq.html
https://ircv3.net/irc/

**Comment by chotaire** [comment]
I am not aware that IRC v3 would allow to alter message content or delete already sent messages.  You might possibly refer to a custom IRCCloud feature:

`2018-09-27 15:18:00 | james | Add support for deleting messages in private team servers, and slack integrations`

This is not something that could be integrated into matterbridge, it has to be done in an IRC bouncer or hosted client service.
