### ISSUE TITLE
Rewrite messages from other relay bots

### ISSUE THREAD

**Issue by gazpachoking** [42wim/matterbridge#713]
**Is your feature request related to a problem? Please describe.**
Some users connect to our gitter room via the built-in matrix.org gitter bridge. In this case, messages come into the room via `matrixbot`, and when relayed via matterbridge to other services have 2 levels of bots involved.

**Describe the solution you'd like**
A way to configure a rewrite of the messages from certain (bot) users, to separate the username and message from the bot message into native matterbridge username/message fields.

**Describe alternatives you've considered**
- deal with it (I understand if this is out of scope for this project.)
- tell users to stop using the matrix->gitter bridge

**Additional context**
![image](https://user-images.githubusercontent.com/187133/52740762-c7cf4300-2fa1-11e9-85ca-19c1e89c8067.png)

Here's an example. For the gitter user `matrixbot` I'd like to parse the messages and pull out `cvium` as username when relayed via matterbridge.

**Comment by 42wim** [comment]
Going to close this in favor of #466 which is the same feature.

**Comment by 42wim** [comment]
@gazpachoking https://github.com/42wim/matterbridge/pull/730 has been merged in master, this should fix your issue.

**Comment by gazpachoking** [comment]
Awesome, thanks! :)
