### ISSUE TITLE
[telegram] -> [matrix] Answers disappear

### ISSUE THREAD

**Issue by TomTheDragon** [42wim/matterbridge#714]
When someone answers on a message on Telegram, the text/contend gets send over to all the bridges but on Matrix, it just gets ignored.
I am using v1.13.1 atm.

**Comment by 42wim** [comment]
I need a `-debug` log for this.

**Comment by TomTheDragon** [comment]
It got fixed by https://github.com/42wim/matterbridge/commit/3e60cfafd342b0a6d27947d27cc125421b8f028a
