### ISSUE TITLE
ShowJoinPart not working

### ISSUE THREAD

**Issue by whyteks** [42wim/matterbridge#72]
Hi!

I really could not get this working at all with any configuration, so I started looking at the code, and it seemed that even though it's documented it is certainly far from implemented in master and it wasn't clear to me what the intention is in terms of moving code from the old -plus version.

I have a support channel bridged to mattermost, and I found staff responding to IRC after the user left IRC, so it's important that they receive part/join/quit on the mattermost channel.

I was working with master, but then went back to 0.6.1
I hacked something crude as follows:

```go
diff --git a/bridge/irc/irc.go b/bridge/irc/irc.go
index 102efa5..dd07db5 100644
--- a/bridge/irc/irc.go
+++ b/bridge/irc/irc.go
@@ -121,13 +121,16 @@ func (b *Birc) handleNewConnection(event *irc.Event) {
        if b.Config.Mattermost.ShowJoinPart {
                i.AddCallback("JOIN", b.handleJoinPart)
                i.AddCallback("PART", b.handleJoinPart)
+               i.AddCallback("QUIT", b.handleJoinPart)
        }
        i.AddCallback("*", b.handleOther)
        b.setupChannels()
 }
 
 func (b *Birc) handleJoinPart(event *irc.Event) {
-       //b.Send(b.ircNick, b.ircNickFormat(event.Nick)+" "+strings.ToLower(event.Code)+"s"+event.Message(), b.getMMChannel(event.Arguments[0]))
+       flog.irc.Debugf("handleJoinPart: %#v", event)
+       channel := "#soporte"
+       b.Remote <- config.Message{Username: b.ircNick, Text: event.Raw, Channel: channel, Origin: "irc"}
 }
 
 func (b *Birc) handleNotice(event *irc.Event) {
```

There's a problem with QUIT as the channel is not included, I have hard coded it for my use as I only have one. 
Anyone got any ideas what to do there?

**Comment by 42wim** [comment]
Yes, unfortunately this got lost in a previous refactor.
I've added a more generic support back in an upcoming commit, but I'm not going to backport it to 0.7 or 0.8.

This means that if you want to use it in mattermost, you'll have to upgrade mattermost to the upcoming 3.5.0 version (release on 16 november) because master only supports latest version.
