### ISSUE TITLE
[WhatsApp, Telegram] Channel Label

### ISSUE THREAD

**Issue by KrzysztofMadejski** [42wim/matterbridge#725]
**Is your feature request related to a problem? Please describe.**

Example image of the message relayed from WhatsApp to Slack:
![whatsapp](https://user-images.githubusercontent.com/849975/52778536-85137680-3046-11e9-8ce7-65e1b428282d.png)

Channel in case of WhatsApp and Telegram is a complex unique ID string, which doesn't look great when visualized.

I'm using a `RemoteNickFormat="[{LABEL} #{CHANNEL}] @{NICK}"` which results in `[CfP #48111222333-1549986983@g.us] @Virus APP [10:45 AM]` being shown as sender.

Problem is that
1. it looks bad, and 
2. in case of WhatsApp, it reveals the creator's of the group phone number.

**Describe the solution you'd like**

What I'd love to have is an ability to set a channel label that would be used by `{CHANNEL}` instead of channel id when set.

Example config:
```
    [[gateway.inout]]
    account="whatsapp.cfall"
    channel="48111222333-1549986983@g.us"
    channelLabel = "Code for Pakistan"
```
That would result in above `RemoteNickFormat` to be formatted as `[CfP #Code for Pakistan] @Virus APP [10:45 AM]`.

**Describe alternatives you've considered**
Not using `{CHANNEL}` in a `RemoteNickFormat`.

**Additional context**
The idea was born while implementing WhatsApp, see #711.

**Comment by qaisjp** [comment]
The `CHANNEL` could probably just be the name of the WhatsApp group instead?

**Comment by KrzysztofMadejski** [comment]
I don't think so. Group names are not unique in WhatsApp so we need unique channel ID.

**Comment by 42wim** [comment]
@KrzysztofMadejski can you take a look at https://github.com/42wim/matterbridge/pull/793
This allows your own scripting for the `RemoteNickFormat` and could solve this issue.

**Comment by 42wim** [comment]
Can be fixed using tengo

Save below as `myremotenickformat.tengo`

```
if channel == "48111222333-1549986983@g.us" {
        result = "[CfP #Code for Pakistan] @"+nick
}
```
Add `RemoteNickFormat="{TENGO}"` to the specific bridge

and add the following in matterbridge.toml
```
[tengo]
RemoteNickFormat="myremotenickformat.tengo"
```

**Comment by ilmaisin** [comment]
What is that tengo thing? Could there be a some sort of step-by-step instruction on how to extract the channel number?

**Comment by lmaddox** [comment]
> What is that tengo thing? Could there be a some sort of step-by-step instruction on how to extract the channel number?

Idk about tengo, but...

1) open whatsapp web
2a) go to your channel that you want the bridge to join
2b) right click on a message in that channel
2c) click 'Inspect (Q)' (note I think the `(Q)` is firefox-specific) to open the developer tools
2d) copy the outer html, paste it into the editor of your choice, extract the contents of the `data-id` field
3) profit!

[source](https://medium.com/@tomer.klein/streamlining-home-assistant-notifications-with-matterbridge-and-whatsapp-ac1081887039)

1) open telegram web 
2a) go the the channel or group that you want...
2b) copy the `-XXXXX` from the url bar
3) profit!

[source](https://neliosoftware.com/content/help/how-do-i-get-the-channel-id-in-telegram/)
