### ISSUE TITLE
[Slack] context deadline exceeded

### ISSUE THREAD

**Issue by KrzysztofMadejski** [42wim/matterbridge#729]
**Describe the bug**
I'm got a following error in the log. Several identical messages between `23:58:32Z` and  `23:59:35`.

```
time="2019-02-14T23:59:35Z" level=error msg="Connection failed "Post https://slack.com/api/rtm.connect: context deadline exceeded" &url.Error{Op:"Post", URL:"https://slack.com/api/rtm.connect", Err:context.deadlineExceededError{}}" prefix=slack
```

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: `1.13.0`

**Comment by 42wim** [comment]
Seems like a network issue on your or slack's side.
Did the bridge stop working after this message?

**Comment by KrzysztofMadejski** [comment]
I see that one that one gateway stopped being forwarded. Others work. It might be linked to this issue, but I can't guarantee.

**Comment by 42wim** [comment]
This is an issue with the underlying library (slack/nlopes) that I can't fix.
I've just added support for extra slack specific debug which you can enable with `Debug=true`  for the slack bridge. This will give a lot of output, but can be used to debug this issue further.

Also the latest master has an update version of the nlopes/slack lib compared to 1.13.0 you're running. So the issue could be already fixed.

I'm closing this now as I can't really fix this.
