### ISSUE TITLE
Allow mattermost "plus" mode, WITH (incoming) webhook support (for improved formatting)

### ISSUE THREAD

**Issue by jlsjonas** [42wim/matterbridge#74]

**Comment by 42wim** [comment]
This already works, what is the issue ?

**Comment by jlsjonas** [comment]
the request is to allow using the web hook for "out" messages, while still using the api for other tasks

**Comment by jlsjonas** [comment]
example:

`[slack] <[slack] <username> >  <@U037AT2KQ|username> has joined the channel`

is what's posted by the bridge (using master//go get)

**Comment by 42wim** [comment]
Could you give a full example of the "slack's formatting for urls" issue with current output and desired output. Thanks!

**Comment by jlsjonas** [comment]
slack's [message formatting](https://api.slack.com/docs/message-formatting) is always `<URL|name/description>`
