### ISSUE TITLE
IRC: Support for +k channels

### ISSUE THREAD

**Issue by naiaokami** [42wim/matterbridge#755]
**Is your feature request related to a problem? Please describe.**
My use case requires the bot accessing a +k (password/keyworded) IRC channel and linking it to a channel in my RocketChat instance.

**Describe the solution you'd like**
I would like the IRC gateway to support an additional variable in order to provide the channel's keyword so the bot can join the channel.

**Describe alternatives you've considered**
Removing +k, connecting the bot, and then setting +k back. This does not work with channels I do not have operator status on.

**Additional context**
N/A

**Comment by 42wim** [comment]
Is already supported: 
https://github.com/42wim/matterbridge/blob/e955a056e2aa4a07c6375315113886b2ee86138c/matterbridge.toml.sample#L1632-L1635
