### ISSUE TITLE
[discord] Automatically create webhooks

### ISSUE THREAD

**Issue by qaisjp** [42wim/matterbridge#764]
**Is your feature request related to a problem? Please describe.**
":sob: why is it so hard to configure webhooks"

**Describe the solution you'd like**
Automatic creation of webhooks, when the bot has permission to Manage Webhooks.

**Additional context**
See https://github.com/42wim/matterbridge/issues/674#issuecomment-471390958 and that entire issue.

**Comment by Helcaraxan** [comment]
@qaisjp from what I believe this has now been implemented in the most recent versions of Matterbridge. Could you confirm and if OK close this ticket? Thanks!

**Comment by qaisjp** [comment]
Nope, webhooks are automatically edited but not created. I'll try and send a PR for this one soon

**Comment by qaisjp** [comment]
With the removal of global webhook support (in https://github.com/42wim/matterbridge/pull/1296), I've prioritised this work.

This is what I've tested so far, I'll do some more testing later today.

<details><summary>test plan</summary>

----

**With** `AutoWebhooks=true`:

- with global permission:
    1. A single channel has existing webhook picked up
    2. A single channel that has a defined WebhookURL is used, and other channels pick up existing webhooks
    3. Same (2) except, on message send, it creates for channels that don't have a webhook

**Without** `AutoWebhooks=false`:

- with global permission
    1. A single channel, with a defined WebhookURL, works
    2. (1) works, and other channels (without WebhookURL) use regular bot messages

**Todo**: test without global permission

----

</details>

I've pushed my branch up so you can give a preliminary inspection if you want: https://github.com/42wim/matterbridge/compare/master...qaisjp:feature/transmitter.

I will probably squash some commits together before submitting a pull request, I'll likely send the PR today if I don't get sidetracked with other things.
