### ISSUE TITLE
Authenticate to mattermost server with GitLab SSO

### ISSUE THREAD

**Issue by ialokim** [42wim/matterbridge#765]
I've already searched a bit and it seems authentication to a Mattermost server which uses GitLab Single Sign On isn't possible using the Mattermost API (see [here](https://forum.mattermost.org/t/solved-how-to-authenticate-bots-using-the-api/2405) e.g.) and therefore neither for matterbridge. Just wanted to confirm I'm not missing anything.

**Comment by 42wim** [comment]
No, but if you have personal tokens enabled you coud use those.
https://docs.mattermost.com/developer/personal-access-tokens.html

https://github.com/42wim/matterircd/issues/29 has also some info about how you can get the MMtoken from the webapp and use it :-)

**Comment by ialokim** [comment]
Thanks a lot for these hints!

In case someone was looking for the same, the personal access token or MMtoken from the webapp can be specified in `matterbridge.toml` as `Token="<your-token-here>"`.

**Comment by vincent1890** [comment]
same error us use sso
Starting gateway failed: Bridge mattermost.work failed to start:

**Comment by unode** [comment]
@42wim would you be open to include the above `Token` documentation in the [Mattermost wiki section](https://github.com/42wim/matterbridge/wiki/Section-Mattermost-%28basic%29) ?
