### ISSUE TITLE
[Rocketchat Bridge] /me messages from IRC aren't relayed to Rocket.chat via webhooks

### ISSUE THREAD

**Issue by TheMythPT** [42wim/matterbridge#772]
**Describe the bug**
`/me` aka action messages from IRC aren't relayed to Rocket.chat, at least via webhook

**To Reproduce**
Send a `/me` message in a IRC channel linked to Rocket.chat and it won't go through

**Expected behavior**
The message should be sent as `RemoteNick _message_` so it will ne italicized in the Rocket.chat end

**Screenshots/debug logs**

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Matterbridge version: 1.14.0
 - If self compiled: obtained via `go get`

**Comment by 42wim** [comment]
Latest devbuild https://bintray.com/42wim/nightly/Matterbridge/v1.14.2-5-g03332a2#files should fix this.
(or build yourself with https://github.com/42wim/matterbridge/pull/794)

**Comment by chotaire** [comment]
Tested as fixed in master.

**Comment by chotaire** [comment]
Tested with current master, /me actions from IRC are **not** being relayed to Rocketchat.

**Comment by chotaire** [comment]
This is working: /me messages from Rocketchat are sent to IRC.
/me is testing would show as: <Chotaire> _is testing_
