### ISSUE TITLE
[whatsapp] On Azure QR code is shown encrypted in the console

### ISSUE THREAD

**Issue by KrzysztofMadejski** [42wim/matterbridge#776]
**Is your feature request related to a problem? Please describe.**
I need to scan QR code and create session file elsewhere and then upload it to Azure. 

**Describe the solution you'd like**
I'd prefer to scan it while starting Azure service.

**Current situation**
The QR code is visualized as follows:
```
[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m[48;5;7m  [0m
and so on
```

**Comment by 42wim** [comment]
Seems to be an azure ansi console issue?
Is this a linux container?

**Comment by KrzysztofMadejski** [comment]
This is a linux container. And this is an Azure ansi console issue. It would be great to have a detection and another handling or documentation how to change console configuration (if possible).

**Comment by 42wim** [comment]
if still an issue reopen please
