### ISSUE TITLE
[irc] Quit messages replayed over bridge

### ISSUE THREAD

**Issue by elixx** [42wim/matterbridge#781]
**Description**
In a mattermost bridge with multiple IRC channels, quit messages are replayed over the bridge.

**To Reproduce**
I have a bridge with 1 mattermost account, with two mattermost channels bridged to 2 separate irc channels.
For example: Given MM1 / MM2 (Mattermost channels), and #IRC1  #IRC2 (irc channels), all quit messages from IRC users in #IRC1 are broadcast erroneously to MM2 and replayed to the #IRC2 channel.

**Expected behavior**
Quit messages to be output only to the mattermost channel for its associated IRC channel.
In the above scenario, quit messages from #IRC1 should only be output to #MM1 and nowhere else.

**Environment (please complete the following information):**
docker container with latest repo source

**Additional context**
https://github.com/42wim/matterbridge/commit/d76a04bd0a96772cec5b279aaa1ee45235adc707
https://github.com/42wim/matterbridge/commit/240559581a225ff632c00a52e029b3728c61309e

**Comment by 42wim** [comment]
Yes, this keeps being an issue for people, I'm reverting this "enhancement" until we have a better solution.

**Comment by chotaire** [comment]
I hope this is getting fixed. Being able to see quits (and parts) is something really important. Who enjoys to talk to their own hand anyway.  Good luck coming up with an idea. 

I might have one. :)

a) Have matterbridge /WHO a channel constantly to see the names of people currently in a channel and create an array of the nicknames. Make sure this doesn't get confused with nick changes. 
b) When receiving a quit message (or a netsplit message), issue another /WHO and compare the older state with the current state of the monitored channel. If the user existed on this channel but now no longer does, relay the quit message to linked channels.

**Comment by 42wim** [comment]
PART still work. You need to enable it though. 
See https://github.com/42wim/matterbridge/wiki/Settings#showjoinpart

**Comment by chotaire** [comment]
Ah, user tracking. That's what I meant :) 

I just tested, PART does indeed work.
