### ISSUE TITLE
Update WhatsApp fork in this repo

### ISSUE THREAD

**Issue by niansa** [42wim/matterbridge#783]

**Comment by 42wim** [comment]
@KrzysztofMadejski is this something you can test and look into ?

**Comment by KrzysztofMadejski** [comment]
Sure, next week.

czw., 4 kwi 2019, 23:40 użytkownik Wim <notifications@github.com> napisał:

**Comment by KrzysztofMadejski** [comment]
The oroginal repo caught up and moved forward, so I will switch back to the original.

**Comment by 42wim** [comment]
I've made a PR with updated forks and a small fix.
You can test dev binaries on https://bintray.com/42wim/nightly/Matterbridge/v1.14.2-16-g333cf0f#files

**Comment by 42wim** [comment]
Anyone who can test this? I don't use whatsapp myself.

**Comment by 42wim** [comment]
@niansa or @KrzysztofMadejski can you test this please?

**Comment by niansa** [comment]
Yes, I will test, thank you!

**Comment by niansa** [comment]
@42wim startup seems to work, but there is one error: https://hastebin.com/rujepoyuwi.css

**Comment by niansa** [comment]
I just keep this running to see if sending/reciving messages works. It's in the middle of the night (midnight) and nobody in the group would be happy if I send random test messages now. Lol

**Comment by niansa** [comment]
@42wim works fine except these error messages...

**Comment by 42wim** [comment]
@niansa ok, thanks, do you get a lot of those error messages? or only on startup?

**Comment by niansa** [comment]
@42wim  A lot.
