### ISSUE TITLE
Allow custom timestamp variables

### ISSUE THREAD

**Issue by Bluscream** [42wim/matterbridge#784]
**Is your feature request related to a problem? Please describe.**
When not using discord webhooks (which has a lot of downsides according to your docs) discord just merges all messages together with only a timestamp for the first msg.

Example Screenshot:
![image](https://user-images.githubusercontent.com/3318223/55430549-ae547b80-558e-11e9-8df3-61613285818a.png)

**Describe the solution you'd like**
A new variable in the config section like `RemoteNickFormat="[{TIME:HH:MM:SS}] \`{NICK}\`: "` or `RemoteNickFormat="[{HH:MM APM}] \`{NICK}\`: "`

**Describe alternatives you've considered**
The only alternative is a webhook which has a lot of disadvantages

**Comment by 42wim** [comment]
I've added support for a "{TENGO}" variable in #793  which allows you to script whatever you want using tengo, tutorial here: https://github.com/d5/tengo/blob/master/docs/tutorial.md

See an example script for your usecase here: https://github.com/42wim/matterbridge/blob/f-784/contrib/remotenickformat.tengo which adds a timestamp before each message


Basically in your matterbridge.toml config you do:
```
[twitch.yourtwitch]
RemoteNickFormat="{TENGO} {NICK}"

[tengo]
RemoteNickFormat="/home/wherever/remotenickformat.tengo"
```
You can find a binary which contains the PR on https://bintray.com/42wim/nightly/Matterbridge/v1.14.2-4-gf0d6aa1#files

**Comment by Bluscream** [comment]
I will ^^

**Comment by Bluscream** [comment]
![image](https://user-images.githubusercontent.com/3318223/55703617-62646500-59da-11e9-88f0-62362f75a460.png)

**Comment by Bluscream** [comment]
It seems like it's not resolving a time :o

**Comment by 42wim** [comment]
You actually used the script? it's not just the binary

**Comment by Bluscream** [comment]
Yes, I downloaded it and set its path in the config

**Comment by 42wim** [comment]
You have to modify the script, in your case if you want to have the timestamp in discord

```
times := import("times")
if protocol != "discord" { // if remote protocol not is discord show it
   result=times.time_format(times.now(),times.format_kitchen)
}
```

**Comment by Bluscream** [comment]
I have/had it like this
```tengo
/*
This script will return the current time in kitchen format if the protocol (of the remote bridge) isn't irc
See https://github.com/d5/tengo/blob/master/docs/stdlib-times.md
This result can be used in {TENGO} in RemoteNickFormat
*/
times := import("times")
if protocol == "discord" {
   result=times.time_format(times.now(),times.format_kitchen)
}
```

**Comment by 42wim** [comment]
The remote bridge is not discord, it's twitch, so doing `if protocol == "irc"` should also work

**Comment by Bluscream** [comment]
ohh, I thought remote is target not source

**Comment by Bluscream** [comment]
Yes, `== "irc"` works, but how do I tell it to only apply the timestamp when "source == irc **and** target == discord

**Comment by 42wim** [comment]
You only add the `{TENGO}` to the `RemoteNickFormat` in your `[discord.mydiscord]` config.

**Comment by Bluscream** [comment]
Oh lol you're right thank you. Everything done as I wished :)

**Comment by patcon** [comment]
@42wim would it be worth having a whole `contrib/tengo/` dir for scripts like this, so people could upstream examples of how they're using it. Might make it simpler for you to help people in the future, as you can just point to an existing script in that dir to modify from? :)

**Comment by 42wim** [comment]
@patcon if you want to help with this, absolutely :) contrib/tengo is fine, but the wiki or any other external service you think would be better is also fine.

**Comment by patcon** [comment]
Hey @Bluscream, awesome that you figured this out, esp as it looks like your first dive into Go :)

might you be willing to submit a PR to add your commented script to `contrib/tengo/`, to help the next person who's walking a path like yours?
