### ISSUE TITLE
TengoModifyMessage doesn't work with stdlib

### ISSUE THREAD

**Issue by Wedmer** [42wim/matterbridge#789]
**Describe the bug**
Embedded Tengo engine can't find stdlib modules.

**To Reproduce**
Add TengoModifyMessage to [general] section with path to script which uses "text" module

**Expected behavior**
Script will be normally compiled without an error about opening module.

**Screenshots/debug logs**
```
time="2019-04-06T01:25:18+03:00" level=error msg="TengoModifyMessage failed: Compile Error: module file read error: open text.tengo: no such file or directory
        at (main):1:9" prefix=gateway
```
**Environment (please complete the following information):**
 - OS: `3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64 GNU/Linux`
 - Matterbridge version:  1.14.1 858e16d

**Additional context**
Used script with regex rules changed.
```
text := import("text")
if text.re_match(" some constant text ",msgText) {
    msgText=text.re_replace("(.*) some constant text (.*):([0-9]*)", msgText, "**$1:**\n*$2*\n$3")
}
```
stripped config.
```
[matrix.mtx]
Server="https://matrix.somewhere"
Login="login"
Password="pwd"
ShowTopicChange=true
ShowJoinPart=true
RemoteNickFormat="<strong>[{PROTOCOL}]{NICK}:</strong> "
NoHomeServerSuffix=false
PrefixMessagesWithNick=true

[discord.ds]
Token="tkn"
Server="SomeServer"
ShowEmbeds=true
EditSuffix=" (edited)"
ShowTopicChange=true
RemoteNickFormat="[{PROTOCOL}]{NICK}"
#UseUserName=true

[general]
TengoModifyMessage="/home/someuser/somescript.tengo"

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="discord.ds"
channel="main"
    [gateway.inout.options]
     webhookurl="url"

[[gateway.inout]]
account="matrix.mtx"
channel="#channel:matrix.somewhere"

```

**Comment by 42wim** [comment]
Thanks, seems like https://github.com/d5/tengo/commit/c437def4a0fcf155f764eb58fa567c67044f09e7#diff-36c721bce7ebb1590e883b974a287477 is the culprit, should have tested better when updating the vendor.

**Comment by 42wim** [comment]
Fixed in master
