### ISSUE TITLE
Starting Matterbridge at Startup on Ubuntu?

### ISSUE THREAD

**Issue by ylluminate** [42wim/matterbridge#790]
I'm wanting to run Matterbridge on the same server as Mattermost.  I'm running this on Ubuntu 16.04.  Is there a preferred method for making Matterbridge start at system startup so that on reboots it always comes up with Mattermost?

I'm not seeing this covered anywhere in documentation, so perhaps this is simpler than I'm thinking due to something going on with the Go installation process?

**Comment by 42wim** [comment]
There's a systemd unit file example at https://github.com/42wim/matterbridge/blob/master/contrib/matterbridge.service

You could modify this to depend on mattermost starting up.
See systemd manual for more information.
