### ISSUE TITLE
Methodology behind Slack integration?

### ISSUE THREAD

**Issue by ylluminate** [42wim/matterbridge#791]
Sorry for entering this as a ticket here, I just prefer a less realtime option (looked for a Discourse or forum option, but no luck).  I'm no fan of Slack and I'm frankly not entirely familiar with the methodology behind it.  I have several companies that we need to interact with both individually via direct or private messages as well as channels/rooms.  So far [the howto doc](https://github.com/42wim/matterbridge/wiki/Slack-bot-setup) for Slack isn't really clear as far as the initial setup - or perhaps background and concept - goes.  

Let's say we get a domain from a group or organization that we need to chat with like slack.somedomain.tld.  Are we supposed to set up the bot functionality as per this for each organization's own Slack team or channel or whatever it's called?  Subsequently would we need to follow [your steps here](https://github.com/42wim/matterbridge/wiki/Slack-bot-setup) for each of these slack.somedomain.tld instances?

In terms of different kinds of Slack messages such as direct or personal messages and then groups in a room or channel, what are the options for this?  Are we able to have one-to-one messages or does that require a Mattermost channel to be set up that's private and set to allow certain participants?  What options exist for usernames - can we define a map for X username in Mattermost to be Y username in Slack?  This kind of username mapping would also be helpful in IRC... but I digress, `#`1 for me at the moment is to get our team interoperating with some of our Slack using associates so we don't have to keep fighting over wanting them to come over to Mattermost directly... :)

**Comment by patcon** [comment]
I feel for you -- I have a ton of slack teams I'm trying to manage too. The bot instructions feel very onerous for that use-case, and legacy approach is simpler imho:
https://github.com/42wim/matterbridge/wiki/Slack-bot-setup#legacy-setup

can be set up by any unprivileged user (without doing heavy social negotiating with admins on each slack) by visiting:
https://api.slack.com/custom-integrations/legacy-tokens 

Tactic is that you create any old user account on that system, you get the legacy token, you create a new channel or grab an existing one, and you add it to a bridge. If you don't want it shared by all slacks, you'll need one channel in your mattermost per bridged channel in your client's [?] slack.

DMs aren't really supported right now.

I recall, username mapping is more complicated and in flux right now...!



If you have further support questions, I might suggest bending your principles a bit, to enter one of the chat spaces where maintainers prefer to support high-level questions like this <3

Cheers!

**Comment by patcon** [comment]
Also, despite the tone of that warning, I don't expect legacy support will go away in matterbridge unless it goes away in slack proper. Their docs don't make it seem that this will happen anytime soon. but there might be risk of this approach breaking if slack changes things. (My use-case will also be quite inconvenienced if this goes away.)

**Comment by Helcaraxan** [comment]
Hello @ylluminate. Did @patcon's answers provide you with the necessary information? If not, please don't hesitate to follow-up. If you have everything you need though feel free to close this GitHub issue.

I'll pass around at a later point to close it in case there's no further reaction. 🙂
