### ISSUE TITLE
Save the state of open threads between restarts

### ISSUE THREAD

**Issue by KrzysztofMadejski** [42wim/matterbridge#797]
**Is your feature request related to a problem? Please describe.**
When I restart Matterbridge (to update configuration or update Matterbridge) the information about parent matched threads is lost and thread replies are sent as non-threaded messages. 

**Describe the solution you'd like**
I'd like Matterbridge to be (optionally) able to save the state of matching threads. Most likely only recent ones in order not to grow indefinitely. The most simple solution would be to save the state in a file.

**Describe alternatives you've considered**
Hot reloading of configuration file if it changes. But it won't help in case of updating Matterbridge version.

**Comment by patcon** [comment]
Didn't have time to finish, but there's a code-spike here for allowing different backends for cache, including persistent ones :)
https://github.com/42wim/matterbridge/issues/541

**Comment by KrzysztofMadejski** [comment]
Closing as duplicate then. :)
