### ISSUE TITLE
IRC colors should not get stripped when bridged to another IRC channel

### ISSUE THREAD

**Issue by chotaire** [42wim/matterbridge#798]
### Introduction

In an earlier commit IRC colors were stripped so that they are not malformatted on services the messages are being bridged to. 

### Problem

However, if they are bridged to another IRC channel, they should definitely not get stripped as e.g. nagios, check_mk, jenkins and so many more applications use IRC colors for important tags such as **OK** and **FAIL**. 

### Proposal

I am proposing either one of the two: 

a) IRC colors get stripped when not sent to another IRC channel. If sent to an IRC channel however, they are retained.
b) IRC colors do not get stripped if sent to another service that supports color. If this is not another IRC channel, the IRC colors need to be reformatted so they are displayed correctly.

This could be made a configuration parameter. Option b) is a lot of work and testing, but color supporting services that would receive reformatted colors instead of stripped IRC colors could be added over time. 

PR: https://github.com/42wim/matterbridge/pull/801

**Comment by 42wim** [comment]
Good point, I'm going for option a) for now though as this seems the most useful.

**Comment by chotaire** [comment]
I'm on standby once you need testing, my matterbridge is connected to multiple IRC networks.

**Comment by chotaire** [comment]
Here's a quick hack: https://github.com/chotaire/matterbridge/releases/tag/v1.14.3-pre-no-irc-colors

**Comment by qaisjp** [comment]
> I'm going for option a) for now though as this seems the most useful.

@42wim is there a standard way for "message translation"? `b)` here seems like a nicer solution imo as it stays true to original content wherever possible. But it doesn't seem easy to implement this whilst retaining the current decoupled nature of things.

(The reason I ask is so that later I can use the same method to explore "@mention" translation from one platform to another.)

**Comment by 42wim** [comment]
@qaisjp no there isn't a standard way.
Maybe with the tengo scripting support for in and out messages option b becomes easier?

**Comment by 42wim** [comment]
Fixed in https://github.com/42wim/matterbridge/pull/806 with tengo
