### ISSUE TITLE
Mumble bridge?

### ISSUE THREAD

**Issue by poVoq** [42wim/matterbridge#800]
**Describe the solution you'd like**
Has been mentioned before here :https://github.com/42wim/matterbridge/issues/28
A new bridge to the Mumble chat system would be nice and there is a Go library for it:
https://github.com/layeh/gumble/

**Describe alternatives you've considered**
https://github.com/SFTtech/sftmumblebot

**Additional context**
There is a cool new web-client for mumble, so I think this could become more popular again:
https://github.com/Johni0702/mumble-web
Also given that people are not super happy with the privacy nightmare of Discord.

Thanks for considering!

**Comment by Helcaraxan** [comment]
Hello @poVoq, as you suggested it yourself this has already been mentioned in the overall "New bridges" topic and hence this is a duplicate.

The reason why Mumble support has not been added is that there are not many people working on / maintaining Matterbridge and hence there's only limited bandwidth for what can be done.

Any contributions from you or anyone else towards supporting Mumble are however very welcome. Me and others will be more than happy to provide code review for your pull-requests and help you shape the support in the right way. 🙂

Closing this issue for now given that support for Mumble is already tracked in the main bridge topic. Feel free to follow-up / reopen though if you or someone else wants indeed to take on the work of adding Mumble support to Matterbridge.
