### ISSUE TITLE
fsnotify + tengo

### ISSUE THREAD

**Issue by qaisjp** [42wim/matterbridge#808]
**Is your feature request related to a problem? Please describe.**
Scripts are being loaded from disk every time a message in processed.

This could _maybe_ become a problem if there are lots of messages and lots of scripts, or if tengo scripts are on a networked filesystem.

(Realistically it will probably never be a problem, but something about reloading a script every message does not sit right with me.)

**Describe the solution you'd like**
We should instead load all tengo scripts mentioned in the config file at startup, watch (fsnotify) these files, and automatically reload these files when necessary. Editing the main config file should perform a list diff and load/unload scripts as necessary.

**Describe alternatives you've considered**
n/a

**Additional context**
[fsnotify](https://github.com/fsnotify/fsnotify) should continue to be used.

**Comment by 42wim** [comment]
> (Realistically it will probably never be a problem, but something about reloading a script every message does not sit right with me.)

I understand the feeling ;-)
I'm still more or less playing around with the tengo bit, some values have been renamed etc.

If it settles down we can do some optimizations (like the one you propose)

**Comment by 42wim** [comment]
Going to close this as in retrospect it doesn't seem to be that big an issue.
