### ISSUE TITLE
"Delay Send=<number of milliseconds>" variable in customization.

### ISSUE THREAD

**Issue by oregonisaac** [42wim/matterbridge#813]
**Is your feature request related to a problem? Please describe.**
Even with extremely adept spam bots, spam sometimes appears on some platforms (Telegram is our specific headache) for a few milliseconds before anti-spam bots delete it.

**Describe the solution you'd like**
I would like a variable for how long until a message is relayed by matterbridge, so for example you could set to 40ms and the message would only get relayed after 40ms if it still existed.  I could also see a use case for setting the variable to say 5000ms or even 60000ms to reduce the number of "post relay edits" that message sometimes have due to quickly caught spelling errors.

**Describe alternatives you've considered**
We have looked at ways to prevent any posting in our groups until after some kind of non-bot verification is completed, but this is both arduous and only partially effective since most spam is by humans who simply act "bot like"

**Comment by qaisjp** [comment]
Aren't these messages automatically deleted on other platforms when it's deleted on one platform?

**Comment by oregonisaac** [comment]
No, the tools to remove spam and other messages are different between the different environments for a variety of reasons:
1) the userbase is extremely different - while telegram is a sort of "front porch" environment with 1000s of members the federated Matrix servers require setup to access and have only a few 100 active project contributors, and so does not have the same spam issues.  Because there is work happening there the kind of spam blocking (deleting posts with links or a "ref=" content etc...) would be counter productive as these things are a regular part of work.
2) the toolsets being used are different, the telegram rooms for over 100 cryptocurrency projects utilize the same toolsets that are still being developed by early bitcoin chat room and bot developers - as such they are not modified project to project
3) the information passed FROM telegram to other groups (matrix/discord/slack) is sent by "DCR Bridge Bot" as part of matterbridge, and so it is not recognized as coming from a new user.

**Comment by 42wim** [comment]
Adding a delay isn't that difficult. But ..

Telegram doesn't has "deleted messages" metadata, so we don't know which messages are deleted.
Even if it would have this metadata, matterbridge receives every message and relays it, it doesn't stop sending a message because the next messages deletes it.

It's probably possible to do this with a bit of scripting using the matterbridge api as output.
The matterbridge api buffers messages. A script could then do some logic to remove a previous message if the current message has a specific string in it, like `[spam]` and then sent it back through an input matterbridge api.

Another option (long-term) is to move this buffer also in matterbridge itself (instead of only the API) and expose this in the tengo scripting, so this kind of stuff can scripted there.

**Comment by Helcaraxan** [comment]
A little bit late to the party, apologies.

As it stands I concur with @42wim's assessment. And I do not indeed believe that this would be something easily achievable without some major changes to the manner in which Matterbridge processes messages. I'd suggest we close this issue for now as there's no clear action that could be taken at this point to satisfy the request.

**Comment by m4teh** [comment]
Having recently established a telegram - xmpp bridge, I can say this is a necessary feature. Telegram spam is a big problem, bots delete this type of spam content within seconds, but it's already relayed to XMPP before doing so. This creates a significant issue.

Is there any change to the situation now that some years have passed?

**Comment by qaisjp** [comment]
> Aren't these messages automatically deleted on other platforms when it's deleted on one platform?

I think my question here was misunderstood.

1. If a message is bridged from Telegram to e.g. Slack/XMPP/whatever,
2. And then a Telegram bot deletes the spam message on Telegram,
3. That message deletion should get bridged too, so the spam is deleted on Slack.

**Comment by 42wim** [comment]
Closing this as it's not possible to implement
