### ISSUE TITLE
Ignore user_typing events received from Slack by IRC bridge (and others?)

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#814]
**Describe the bug**
Slack's user_typing messages show as blank messages with no `NICK` in IRC.

**To Reproduce**
Connect a Slack and IRC bridge to the same gateway. Enable `ShowUserTyping`. Type some text in slack, without hitting send. blank messages should appear.

**Expected behavior**
I'd expect thee user_typing messages to be passed through the gateway, but stopped at the IRC bridge code, and perhaps in all other bridges.

**Screenshots/debug logs**
![Screen Shot 2019-04-24 at 2 02 28 PM](https://user-images.githubusercontent.com/305339/56682563-d02ab500-6699-11e9-9d06-9248eb5799e3.png)

Logs: https://gist.github.com/patcon/cf4c2fc29dfc188fd320bc43c905d5c2

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: admittedly old fork with changes merged from 53c8670, at `v1.13.0-pre` (due to being on my translation fork). But a quick check seems to indicate it's still an issue.

**Additional context**

`user_typing` messages are exempt from the gateway-level filter for blank messages here:
https://github.com/42wim/matterbridge/blob/f04d360ee2664595c391358506eba060b4df2199/gateway/gateway.go#L265-L267

Wondering thoughts on a best path. For now, I could just add a special-case skip to the IRC bridge, but perhaps we could centrally manage the list of "compatible" protocols that handle user_typing events. For now, it would just be slack, but the bridge-level code could call back to a function that checks if it's compat, and skips these messages if so. Curious for any feedback on this approach :)

**Comment by patcon** [comment]
Alternatively, what might the consequences of adding another skip-check for blank messages in IRC bridge code? Presumably that wasn't done in the past because it was caught in gateway, but now we pass through some action events with no text, so it's not totally consistent...

**Comment by Helcaraxan** [comment]
This should have been resolved now with #832. 🙂
