### ISSUE TITLE
Relaying of Bot created Discord messages to IRC is broken

### ISSUE THREAD

**Issue by tsiren** [42wim/matterbridge#816]
**Describe the bug**
In a Discord <-> IRC setup matterbridge does not detect bot created messages in Discord and therefore does not relay them to IRC. User messages work fine both ways. Name of the bot whose messages are not detected is 'ETF server status'.

**To Reproduce**
Update matterbridge from version: 1.13.0 5d3309f

**Expected behavior**
Message detected and relayed to IRC.

**Screenshots/debug logs**
`matterbridge -debug` doesn't show the event created by the bot

**Environment (please complete the following information):**
 - OS: linux, Debian Stretch
 - Matterbridge version: version: 1.14.4 6d8cccc
 - If self compiled: no

**Comment by 42wim** [comment]
If you downgrade to 1.13.0 the messages get relayed?
Could you paste a `-debug` log when it happens correctly?

**Comment by tsiren** [comment]
[matterbridge_debug.log](https://github.com/42wim/matterbridge/files/3134628/matterbridge_debug.log)

**Comment by tsiren** [comment]
1.13.0 works fine and the log is from that. With e.g. 1.14.4 the line
```[0016] DEBUG discord:      == Receiving event &discordgo.Message{ID:"573137422171373568", ChannelID:"253602720634634240", GuildID:"253600486219972608", Content:"etf.tunk.org, map etf_gotduck, player count 1: [NB]sensei", Timestamp:"2019-05-01T13:23:29.824000+00:00", EditedTimestamp:"", MentionRoles:[]string{}, Tts:false, MentionEveryone:false, Author:(*discordgo.User)(0xc000602f80), Attachments:[]*discordgo.MessageAttachment{}, Embeds:[]*discordgo.MessageEmbed{}, Mentions:[]*discordgo.User{}, Reactions:[]*discordgo.MessageReactions(nil), Type:0, WebhookID:""}``` that is triggered by the bot message is missing and thus all the subsequent related messages.

**Comment by 42wim** [comment]
Thanks, found the issue, introduced in af00c34aaccb3521b8dbf0bd8876a5b38d5d42f4
I think that change was unnecessary, reverting it.

**Comment by 42wim** [comment]
You can build from master or try a dev-build binary from here https://bintray.com/42wim/nightly/Matterbridge/v1.14.2-25-g1829dc3#files
