### ISSUE TITLE
xmpp to matterbridge has unexpected behaviour

### ISSUE THREAD

**Issue by arthurlogilab** [42wim/matterbridge#82]
I'm setting up a bridge between mattermost and xmpp 

The setup is as follows : 

* I have a user arthur on mattermost with email arthur@example.org (and an admin account) and a user arthur on jabber
* I have a matterbridge user on mattermost with email arthur+bot@example.org and a matterbridge user on jabber
* There is a third account that is both on mattermost with bob@example.org and jabber, let's call it bob (not an admin user)

I have the following bug : 

* the jabber bot connects correctly to the jabber channel
* the mattermost bot is visible in the mattermost 
* when as arthur I write something on jabber, it appears as "arthur [bot]" in mattermost, which is what I was expecting
* when arthur writes something in mattermost the bot relays on jabber, which is what is expected
* when bob writes something in mattermost the bot relays on jabber, which is what is expected
* when bob writes something in jabber, it appears as "arthur [bot]" in mattermost, there lies the bug in my view. 

Is this is a bug or an expected behaviour ?

**Comment by 42wim** [comment]
What version of matterbridge ?
If you use mattermost API instead of webhook, you cannot override the username.
You'll have to enable ```PrefixMessagesWithNick``` and use  ```RemoteNickFormat```

**Comment by arthurlogilab** [comment]
```
# ./bin/matterbridge -version
version: 0.9.0-dev
```

am using incoming & outgoing webhooks. 

```
PrefixMessagesWithNick=false
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
```

Is there a setting somewhere on mattermost about "username overrides " ? 


(thanks for the quick response and for matterbridge by the way)

**Comment by 42wim** [comment]
Yes, it's in the small FAQ in https://github.com/42wim/matterbridge/blob/master/README.md ;-)
See https://docs.mattermost.com/developer/webhooks-incoming.html#enabling-incoming-webhooks

**Comment by arthurlogilab** [comment]
oh. I just realized I deployed a 3.2.0 version of mattermost (https://github.com/tjtoml/mattermost-ansible/ is out of date...). Am going to upgrade to 3.5.0 and see with those options. Thanks.
