### ISSUE TITLE
XMPP Offsite Hosting

### ISSUE THREAD

**Issue by kousu** [42wim/matterbridge#820]
**Describe the bug**

Like SMTP with MX records, XMPP servers need not be on the same server as the domain they are hosting. Unlike SMTP, XMPP [uses](https://prosody.im/doc/certificates#which_domain) the *hosted* domain for its TLS certs:
> your certificate simply needs to match whatever you have in your VirtualHost and Component definitions

That is, whereas in SMTP if you have
```
example.net:
  @ MX mail.example.net
```
then mail.example.net needs to have certs for itself: mail.example.net.

In the equivalent setup for XMPP, using [SRV records](https://prosody.im/doc/dns#srv_records), then xmpp.example.net needs to have certs for its parent _example.net_.

Matterbridge does not know how to read SRV records, and does not know this unusual rule about what domain is the valid TLS domain.

**To Reproduce**

Set up an XMPP server "xmpp.example.net" hosting domain "example.net". Set up corresponding DNS with [SRV records](https://prosody.im/doc/dns#srv_records) like so:

```
example.net
  _xmpp-client._tcp.example.net. 18000 IN SRV 0 5 5222 xmpp.example.net.
  _xmpp-server._tcp.example.net. 18000 IN SRV 0 5 5269 xmpp.example.net.
```

Create a test account "botbot@example.net" in the XMPP server (with prosody this is `root@xmpp.example.net# sudo -u prosody prosodyctl adduser botbot@example.net`).

Login as botbot@example.net to verify that the account works. You can use https://movim.eu or Gajim or https://dino.im or any recentish XMPP client.

**Expected behavior**

Matterbridge should behave like a standard XMPP client, following the SRV records and _verifying TLS against the hosted domain_.

Other XMPP clients offer an optional secondary "connect server" field, e.g.:

![](https://wiki.freifunk.net/images/1/17/Pidgin-connect-server.png)

as a manual workaround to issues like this. Adding a config option for that would fix this for me. Additionally implementing SRV lookups would be best.

(_Aside_: as annoying as this is, IMO XMPP is correct in making this design choice; SMTP servers are not really secure because DNS poisoning can redirect the MX for a domain to any other domain, a domain which an attacker could get a cert for and silently MITM mail for ages; if DNSSEC was working reliably and had been invented 20 years earlier maybe we wouldn't be here because a domain could sign off on its tertiary mail/xmpp/etc servers, and then those servers could have their own local certs in their own local names, but we don't get to live in that world).

**Screenshots/debug logs**

I have XMPP hosted on a secondary server. My XMPP vhost is "kousu.ca"; my XMPP server is at:

```
$ dig +short SRV _xmpp-server._tcp.kousu.ca
0 5 5269 comms2.kousu.ca.
```

With Config A (below) which uses my main domain, matterbridge doesn't follow SRV records and fails because my main domain isn't hosting XMPP:

```
$ matterbridge -debug -conf conf.toml 
[0000]  INFO main:         Enabling debug logging.
[0000]  INFO main:         Running version 1.14.4 
[0000]  INFO router:       Parsing gateway bridge1
[0000]  INFO router:       Starting bridge: xmpp.example 
[0000]  INFO xmpp:         Connecting kousu.ca:5222
[0000] DEBUG xmpp:         &net.OpError{Op:"dial", Net:"tcp", Source:net.Addr(nil), Addr:(*net.TCPAddr)(0xc00039d4d0), Err:(*os.SyscallError)(0xc000398960)}
[0000] FATAL main:         Starting gateway failed: Bridge xmpp.example failed to start: dial tcp 108.61.165.176:5222: connect: connection refused
```

With Config B, which uses the real server, matterbridge connects but fails because it doesn't know the TLS cert is correct:

```
$ matterbridge -debug -conf conf.toml 
[0000]  INFO main:         Enabling debug logging.
[0000]  INFO main:         Running version 1.14.4 
[0000]  INFO router:       Parsing gateway bridge1
[0000]  INFO router:       Starting bridge: xmpp.example 
[0000]  INFO xmpp:         Connecting comms2.kousu.ca:5222
[0000] DEBUG xmpp:         &errors.errorString{s:"starttls handshake: x509: certificate is valid for kousu.ca, not comms2.kousu.ca"}
[0000] FATAL main:         Starting gateway failed: Bridge xmpp.example failed to start: starttls handshake: x509: certificate is valid for kousu.ca, not comms2.kousu.ca
```

The only way to get it to work is to use the direct server but disable TLS verification:

```
$ matterbridge -debug -conf conf.toml 
[0000]  INFO main:         Enabling debug logging.
[0000]  INFO main:         Running version 1.14.4 
[0000]  INFO router:       Parsing gateway bridge1
[0000]  INFO router:       Starting bridge: xmpp.example 
[0000]  INFO xmpp:         Connecting comms2.kousu.ca:5222
[0000]  INFO xmpp:         Connection succeeded
[0000]  INFO xmpp:         xmpp.example: joining slack-general (ID: slack-generalxmpp.example)
[0000]  INFO main:         Gateway(s) started succesfully. Now relaying messages
[0000] DEBUG xmpp:         == Receiving xmpp.Chat{Remote:"slack-general@conference.kousu.ca", Type:"groupchat", Text:"", Subject:"", Thread:"", Ooburl:"", Oobdesc:"", ID:"", ReplaceID:"", Roster:xmpp.Roster(nil), Other:[]string{}, OtherElem:[]xmpp.XMLElement(nil), Stamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}
```

**Environment:**
 - OS: ArchLinux.
 - Matterbridge version: 1.14.4 

**Additional context**

Config A:

```
[xmpp]
[xmpp.example]
Server="kousu.ca:5222"
Jid="bot-matterbridge@kousu.ca"
Password="XXXXXXXXXXXXXXXXXXX"
Muc="conference.kousu.ca"
Nick="botbot"


[[gateway]]
name="bridge1"
enable=true
	[[gateway.inout]]
	account="xmpp.example"
	channel="general"
```

Config B:

```
[xmpp]
[xmpp.example]
Server="comms2.kousu.ca:5222"
Jid="bot-matterbridge@kousu.ca"
Password="XXXXXXXXXXXXXXXXXXX"
Muc="conference.kousu.ca"
Nick="botbot"


[[gateway]]
name="bridge1"
enable=true
	[[gateway.inout]]
	account="xmpp.example"
	channel="general"
```

Config C (working..sort of):

```
[xmpp]
[xmpp.example]
Server="comms2.kousu.ca:5222"
Jid="bot-matterbridge@kousu.ca"
Password="XXXXXXXXXXXXXXXXXXX"
Muc="conference.kousu.ca"
Nick="botbot"
SkipTLSVerify=true


[[gateway]]
name="bridge1"
enable=true
	[[gateway.inout]]
	account="xmpp.example"
	channel="general"
```

**Comment by Helcaraxan** [comment]
Hello @kousu. Apologies that it took so long to get to your issue. There are not many collaborators / maintainers on this project hence the delay.

First of all: let me thank you very much for this amazingly detailed report with in-depth details! ❤️ 

I have had the time to take a look at your issue and it seems to me that this is not something of Matterbridge itself but rather with [the third-party library](https://github.com/matterbridge/go-xmpp) on which we depend for managing XMPP connections. The way the library performs [TLS validation](https://github.com/matterbridge/go-xmpp/blob/master/xmpp.go#L212-L233) does not seem to follow the XMPP spec as you describe it in your post. This means that we can't rely fix anything of this within our own code.

Unfortunately it seems that the third-party library has deactivated issues but it should be possible to raise a PR with them that addresses the incorrect behaviour with the appropriate references to XMPP documentation.

Let us know whether this seems like a fair assessment to you or whether you believe that we can still do something inside Matterbridge to address your problem.

**Comment by kousu** [comment]
@Helcaraxan thanks for doing that research.

There's this comment in that file which sounds like someone was thinking about doing SRV records but put it off for later:

https://github.com/matterbridge/go-xmpp/blob/7ec2b8b7def69491528689aeb58253e9421a4b73/xmpp.go#L500-L506

however, they do allow setting the host to connect to separately from

**Comment by kousu** [comment]
There, I've put a patch up for consideration.

Is https://github.com/matterbridge/go-xmpp under the project's control? It's at /matterbridge? I could patch that too (eventually, when I find some time)

**Comment by 42wim** [comment]
@kousu https://github.com/matterbridge/go-xmpp is under my control, I'll take a PR for the SRV issue.
 https://github.com/mattn/go-xmpp/pull/108 seems like the PR that does what you want?
