### ISSUE TITLE
{Protocoll} alias or shortcode?

### ISSUE THREAD

**Issue by poVoq** [42wim/matterbridge#826]
**Is your feature request related to a problem? Please describe.**
Especially on IRC the front of messages can get quite long with the bot name plus "Mattermost" plus <user name>

**Describe the solution you'd like**
Optional shorter codes, like "MM" for Mattermost.

**Describe alternatives you've considered**
Removing protocoll completely, but then it isn't so clear to users that the messages are bridged.

Thanks!

**Comment by qaisjp** [comment]
This can be done with tengo

**Comment by 42wim** [comment]
You can do this like @qaisjp suggest with a tengo remotenickformat file.

Tengo code:
```
if protocol == "mattermost" {
    result = "[MM]<"+nick+"> "
}
```

more info can be found in https://github.com/42wim/matterbridge/wiki/Settings#remotenickformat-2
and my comment in https://github.com/42wim/matterbridge/issues/822#issuecomment-493260864
