### ISSUE TITLE
Media server HTTP_Upload external like XMPP?

### ISSUE THREAD

**Issue by poVoq** [42wim/matterbridge#827]
**Is your feature request related to a problem? Please describe.**
Media server options are quite limited if you do not run a caddy server or on a local setup.

**Describe the solution you'd like**
XMPP servers (Prosody & ejabbered) have a very simple protocol to allow sharing attachments by uploading them to an external server. See:
https://modules.prosody.im/mod_http_upload_external.html

So that might be an easy and well supported way to improve media serving options.

Thanks for considering.

**Comment by 42wim** [comment]
"sharing attachments by uploading them to an external server"
So you need to configure an external server for prosody/ejabberd anyway.
What's the issue with doing this directly from matterbridge instead?

The caddy server is an (easy) example, you can use any webserver you like.

**Comment by poVoq** [comment]
Could be the same one, no?

It has the advantage that it is much easier to host (no need to setup the webserver in a specific way, can easily work in shared hosting with plenty of storage space etc.) and also obfuscates the uploaded files.

**Comment by 42wim** [comment]
Seems I misunderstand the page on https://modules.prosody.im/mod_http_upload_external.html
You don't need to setup an extra webserver, prosody itself will act as webserver when activated?

**Comment by 42wim** [comment]
Thats the same issue as https://github.com/42wim/matterbridge/issues/295

**Comment by poVoq** [comment]
Yeah that's similar, except that I was thinking of non-xmpp exclusive general implementation as it seems a easy to setup solution that doesn't reinvent the wheel.

**Comment by 42wim** [comment]
I'm not sure what you exactly mean?
How do you see this non-xmpp general implementation without reinventing wheels ?

**Comment by poVoq** [comment]
Well, I think matterbridge would benefit from an easy to setup media upload system that works for all bridged systems and does not depend on setting up some custom webserver stuff like it seems to be the case right now. Correct me if I overlooked something though.

**Comment by 42wim** [comment]
@poVoq so that basically means adding a webserver to matterbridge itself you mean? or do you propose another solution?

**Comment by poVoq** [comment]
No, the solution I linked is as easy as dropping a single php file on a shared hosting provider and pointing the xmpp server to it.

**Comment by 42wim** [comment]
Ok, well that's cheating because you're still using a webserver, someone else just set it up for you :-)
If that's what you want you can do the same with the current matterbridge code, you just need to have a php script that accepts basic authentication and file PUTs

Combination of
https://gist.github.com/rchrd2/c94eb4701da57ce9a0ad4d2b00794131 and https://github.com/kriztan/mod_http_upload_external/blob/master/share.php

**Comment by 42wim** [comment]
I'm going to close this, but if you're making such a script as it it's out of scope.
But if you're making such a script, consider making a PR to our contrib directory, would be useful to other people too!

Thanks
