### ISSUE TITLE
[Rocket Chat] RemoteNick is shown instead of bot's username

### ISSUE THREAD

**Issue by cwchristerw** [42wim/matterbridge#828]
**Describe the bug**

I want Rocket Chat to show bots username like Discord does (and still want message to include remotenick).

![Screenshot from 2019-05-24 00-17-42](https://user-images.githubusercontent.com/13464896/58287441-b0320280-7db9-11e9-92b5-cbf5f792632b.png)

![Screenshot from 2019-05-24 00-21-25](https://user-images.githubusercontent.com/13464896/58287525-e7a0af00-7db9-11e9-810b-cca5d9c347ee.png)

**To Reproduce**
Rocket Chat and any other bridge like Discord.

**Expected behavior**

![Screenshot from 2019-05-24 00-18-20](https://user-images.githubusercontent.com/13464896/58287447-b58f4d00-7db9-11e9-8e34-af2782187d67.png)
> This example was made by sending message directly from Rocket Chat to Rocket Chat by using bot user.

**Additional context**
```
[rocketchat]

[rocketchat.cwinfo]
Server="https://rocketchat.cwinfo.org"
Login="no-reply@cwinfo.net"
Password="XXXXXXXXXXXXXXXXXXXXX"
PrefixMessagesWithNick=true
Label="Rocket Chat : CWINFO"
RemoteNickFormat="[{LABEL} : {CHANNEL}]<{NICK}> "

[irc]

[irc.pirateirc]
Server="roubaix-fr.pirateirc.net:6697"
UseTLS=true
UseSASL=false
SkipTLSVerify=true
Charset=""
Nick="GOGO"
MessageDelay=1300
MessageQueue=30
MessageLength=400
MessageSplit=false
RejoinDelay=0
ColorNicks=false
Label="IRC : PirateIRC"
RemoteNickFormat="[{LABEL} : {CHANNEL}]<{NICK}> "
ShowJoinPart=false
NoSendJoinPart=false
StripNick=false
ShowTopicChange=false

[[gateway]]
name="pirateirc"
enable=true

[[gateway.inout]]
account="irc.pirateirc"
channel="#test"

[[gateway.inout]]
account="irc.pirateirc"
channel="#test2"

[[gateway.inout]]
account="rocketchat.cwinfo"
channel="#pirateirc"
```

**Comment by cwchristerw** [comment]
Putting PrefixMessagesWithNick=false
![Screenshot from 2019-05-24 00-36-27](https://user-images.githubusercontent.com/13464896/58288344-fee09c00-7dbb-11e9-82de-c569477e058c.png)

**Comment by cwchristerw** [comment]
This will solve #7549 problem for me

**Comment by 42wim** [comment]
fixed upstream
