### ISSUE TITLE
Keybase support

### ISSUE THREAD

**Issue by Mikaela** [42wim/matterbridge#829]
I would like Matterbridge to support [Keybase.io](https://keybase.io) team/chat. I am not a developer and I don't know what supporting it would include, but Keybase has [keybase/keybase-bot at GitHub](https://github.com/keybase/keybase-bot) which may be helpful. They also have [chat documentation](https://keybase.io/docs/chat/index) and [API documentation with warning on bad docs](https://keybase.io/docs/api/1.0).

Keybase also has a [Slack importer](https://keybase.io/slack-importer) which can possibly increase how used it is.

**Comment by Helcaraxan** [comment]
Hello @Mikaela. Thank you very much for the feature request! I am myself a user of Keybase and love what they do.

From the information that I have been able to collect (thank you very much for the helpful links!) I do not think that it would currently be beneficial to add support to Matterbridge for the Keybase chat. The core reasons are that:
- The documentation is relatively incomplete; not just the API - we would need to decode a lot of the CLI stuff as well.
- There is no existing third-party Go wrapper for their chat functionalities, which means that we would need to implement it ourselves even though we solely rely on third-party libraries for all other chat protocols.
- Things are not yet marked as stable and hence there is likely to be a high maintenance cost even if we were to implement our own wrapper around Keybase's CLI.

**Comment by Mikaela** [comment]
Should I close this or keep it open as a reminder in hope that the situation will change and Keybase bridge becomes possible?

Ref https://github.com/42wim/matterbridge/issues/28 so Ctrl + F for Keybase there will bring this up.

**Comment by pzduniak** [comment]
Keybase dev here, feel free to @ me [on keybase](https://keybase.io/pzduniak) if you'd like some help with the integration / APIs.

>There is no existing third-party Go wrapper for their chat functionalities, which means that we would need to implement it ourselves even though we solely rely on third-party libraries for all other chat protocols.

We have https://github.com/keybase/go-keybase-chat-bot which definitely is not idiomatic Go but works quite well (and has been used by quite a few users without any issues, other than the lack of functionality vs [the JS lib](https://github.com/keybase/keybase-bot)). Most of the relevant documentation can be accessed by `keybase chat api --help`.

**Comment by 42wim** [comment]
Thanks to @hyperobject this is now a reality.
