### ISSUE TITLE
jabber/xmpp bot could use nick to show messages as if they came from mattermost nick

### ISSUE THREAD

**Issue by arthurlogilab** [42wim/matterbridge#83]
This is a follow up of #82 

When matterbridge@jabber.example.org connects to channel@conference.jabber.example.org we can configure the nick to be "xmppbot" (for example).

Then the bot writes messages with RemoteNickFormat="<NICK>" for example, this appears as  

```
xmppbot> <arthur> hello world
```

It would awesome if matterbridge@jabber.example.org could change nick to the mattermost nick when sending messages from those users, thus masking the fact that the message comes from mattermost. 

```
arthur> hello world
```

**Comment by 42wim** [comment]
What version of matterbridge ? 
Because if you set ```RemoteNickFormat=""``` it should show 
```xmppbot> hello world``` (without arthur)
