### ISSUE TITLE
Deleted messages on Telegram are not propagated to Discord

### ISSUE THREAD

**Issue by redyoshi49q** [42wim/matterbridge#840]
I use Matterbridge to bridge Telegram channels with Discord channels (the latter of which are configured to use tokens and /not/ webhooks).

The bridges function bidirectionally for text and media as expected, and changes that are made to text via edits on either platform are successfully propagated to the other.  Text and media sent through Discord that is then deleted will be deleted on the Telegram side, as expected.  However, deleting either text or media that was originally sent on the Telegram side will /not/ delete the copy on the Discord side.

### Environment
Version: 1.14.0-dev

Operating system: Linux Mint 18 Sarah"

go version: go1.10 linux/amd64
git commit hash: 48ba8294653da0c862295b2a6ff0709659fd6b69

### Please describe the expected behavior.
The deletion of messages originally sent through Telegram should propagate to Discord, resulting in the deletion of the corresponding Discord messages.

### Please describe the actual behavior. 
See description above headings.

### Any steps to reproduce the behavior?
The following steps may not necessarily be sufficient, in the case that there's an environment or configuration component to the issue.

* Use Matterbridge to bridge a Telegram and Discord chat together, leaving "UseInsecureURL" disabled on the Telegram side and Webhooks disabled on the Discord side.
* Generate a message on a bridged Telegram chat
* Delete the aforementioned message on the Telegram chat

### Please add your configuration file 
Attached is the matterbridge.toml.
[matterbridge.toml_no_auths.txt](https://github.com/42wim/matterbridge/files/3248261/matterbridge.toml_no_auths.txt)

**Comment by 42wim** [comment]
Hi,

Related to https://github.com/42wim/matterbridge/issues/813#issuecomment-488141332

Telegram doesn't has "deleted messages" metadata, so we don't know which messages are deleted.
Even if it would have this metadata, matterbridge receives every message and relays it, it doesn't stop sending a message because the next messages deletes it.

Going to add this in the FAQ
