### ISSUE TITLE
Syncing one Mattermost with two Slack workspaces

### ISSUE THREAD

**Issue by SvenSchoe** [42wim/matterbridge#841]
### Environment

Version: 1.14.4 6d8cccc

Operating system: Devuan 2.0

### Please describe the expected behavior.

I have two different slack workspaces with a bunch of channels each that I want to sync to one mattermost team. Using samechannelgateway, this works fine for each of the slack workspaces alone - however, I cannot get both of them to work. I tried using an individual bot for each Slack workspace, a dedicated User for each Slack workspace - none of it works for both workspaces at the same time. Can this even be done?

### Please describe the actual behavior. 

root@mattermost:/opt/matterbridge# ./matterbridge -debug -conf matterbridge.toml
[0000]  INFO main:         Enabling debug logging.
[0000]  INFO main:         Running version 1.14.4 6d8cccc
[0000] FATAL config:       Failed to parse the configuration: viper.ConfigParseError{err:(*errors.errorString)(0xc0003af270)}

### Please add your configuration file 

[mattermost.Bot]
#The mattermost hostname. (do not prefix it with http or https)
Server="mattermost.xxxxxxxx"

#the team name as can be seen in the mattermost webinterface URL
#in lowercase, without spaces
Team="testing"

#login/pass of your bot.
#Use a dedicated user for this and not your own!
Login="xxxxxxx"
Password="xxxxxxxl"

RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
PrefixMessagesWithNick=true

[slack]
[slack.blab]
#See https://core.telegram.org/bots#6-botfather
#and https://www.linkedin.com/pulse/telegram-bots-beginners-marco-frau
Token="xxxxxxxx"
RemoteNickFormat="[{BRIDGE}] <{NICK}> "

[slack-legacy]
[slack-legacy.slack]
Token="xxxxxxxx"
RemoteNickFormat="[{BRIDGE}] <{NICK}> "

#this must always be [[gateway]], don't use anything else
#[[gateway]]
#name="gateway1"
#enable=true

[[samechannelgateway]]
   name="samechannel1"
   enable = true
   accounts = [ "mattermost.Bot","slack-legacy.slack"]
   channels = [ "ws2-bot1","ws2-bot2"]

   name="samechannel2"
   enable = true
   accounts = [ "mattermost.Bot","slack.blab"]
   channels = [ "bot-test","bot-test2"]

#each of these two samechannelgateways works on its own. But not together.
#also not working:

    name="samechannel1"
   enable = true
   accounts = [ "mattermost.Bot","slack-legacy.slack","slack-legacy.slack"]
   channels = [ "ws2-bot1","ws2-bot2","bot-test","bot-test2"]

**Comment by 42wim** [comment]
Sorry for the late reply.
The samechannelgateway doesn't get much love, so more advanced stuff could be broken.

Repeating the `[[samechannelgateway]]` again should possibly work. But at the bottom is a solution that will definitely work using the normal `[[gateway]]` option, but a lot more verbose for your setup, although you could script it.

```
[[samechannelgateway]]
name="samechannel1"
enable = true
accounts = [ "mattermost.Bot","slack-legacy.slack"]
channels = [ "ws2-bot1","ws2-bot2"]

[[samechannelgateway]]
name="samechannel2"
enable = true
accounts = [ "mattermost.Bot","slack.blab"]
channels = [ "bot-test","bot-test2"]
```

Using `[[gateway]]`
```
[[gateway]]
name="gw1"
enable=true

[[gateway.inout]]
account="mattermost.Bot"
channel="ws2-bot1"

[[gateway.inout]]
account="slack-legacy.slack"
channel="ws2-bot1"

[[gateway]]
name="gw2"
enable=true

[[gateway.inout]]
account="mattermost.Bot"
channel="ws2-bot2"

[[gateway.inout]]
account="slack-legacy.slack"
channel="ws2-bot2"


[[gateway]]
name="gw3"
enable=true

[[gateway.inout]]
account="mattermost.Bot"
channel="bot-test"

[[gateway.inout]]
account="slack.blab"
channel="bot-test"

[[gateway]]
name="gw4"
enable=true

[[gateway.inout]]
account="mattermost.Bot"
channel="bot-test2"

[[gateway.inout]]
account="slack.blab"
channel="bot-test2"
```
