### ISSUE TITLE
XMPP forwarding broken after code cleaning

### ISSUE THREAD

**Issue by imShara** [42wim/matterbridge#844]
**Describe the bug**
XMPP bridge receives incoming messages, but doesn't forwarding.

**To Reproduce**
Try to send anything from XMPP to TG or Whatsapp with last version

**Expected behavior**
Message should be forwarded to oher protocols

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: version: 1.15.0-dev
 - If self compiled: e610fb3201bb233e68d88c1dfcd30d4206e53f22

**Additional context**
Revert xmpp bridge to 1.14 branch version helps

**Comment by imShara** [comment]
This line makes regular message skipped
```go
return message.Stamp.IsZero()
```

**Comment by 42wim** [comment]
Thanks for debugging this regression.
Fixed in a PR, soon in master
