### ISSUE TITLE
Discord: Messages not relayed when channel and category names are identical

### ISSUE THREAD

**Issue by Souptacular** [42wim/matterbridge#860]
**Describe the bug**
In Discord if the category name (A) is identical to the channel name (B) and you try to set a gateway (C) as the channel name in the Matterbridge config file it will produce an error when sending messages to channel B.

**To Reproduce**
Steps to reproduce the behavior: Create a Discord server with the Category name "GENERAL" and a channel under that category called "general". Create an entry in the matterbridge.toml file that includes a gateway connection to the general channel:

```
##############################################

[[gateway]]
name="test-general"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="general"

[[gateway.inout]]
account="gitter.mygitter"
channel="testing/notgeneral"

##############################################
```

Messages will be relayed from the Discord channel to Gitter, but not the other direction.

**Expected behavior**
Messages would be transmitted between the Gitter channel and the Discord channel.

**Screenshots/debug logs**
Whenever the message send failure to the general channel happens the following error log is displayed:
`ERROR gateway:      SendMessage failed: HTTP 400 Bad Request, {"code": 50008, "message": "Cannot send messages in a non-text channel"}`

**Environment (please complete the following information):**
 - OS: Ubuntu 64bit
 - Matterbridge version: 1.15.0

**Comment by 42wim** [comment]
You can use a workaround for this now by using the channel id instead of specifying the name
`channel="ID:123456789"` (last part of the channel URL)

**Comment by 42wim** [comment]
@qaisjp also made a patch to have this work without the ID (if you don't have multiple channels with the same name). This fix is now in master.

**Comment by Souptacular** [comment]
Thank you!
