### ISSUE TITLE
IRC does not re-use account connection

### ISSUE THREAD

**Issue by JK2gUu-Ny9** [42wim/matterbridge#87]
If I add multiple gateways with the same IRC account (see [example matterbridge.toml](https://github.com/42wim/matterbridge/files/601982/matterbridge.toml.txt)), matterbridge will start multiple IRC connections, resulting in nicknames as `matterbridge_` and `matterbridge__` in some channels.

**Comment by 42wim** [comment]
Yes, this is how it works for now, only inside the same gateway connections are reused. 
Will revise this in the future.

**Comment by JK2gUu-Ny9** [comment]
I understand, but can one work around this limitation? Is it possible somehow to reuse the same IRC connection for bridging in multiple channels?

**Comment by 42wim** [comment]
No that's not possible at the moment.

**Comment by ExTechOp** [comment]
We've just started using Matterbridge, and this is a bit of a pain because we'll need one connection to the irc server per bridged channel. It would scale better if a single connection could be used for all channels, since many irc servers limit how many connections one client can open simultaneously.

**Comment by 42wim** [comment]
@ExTechOp I'm actually working on this (for all protocols), are you willing to test a version the coming days?

**Comment by ExTechOp** [comment]
We are running Mattermost with a corporate test license (for the LDAP integration, such as it is) until the end of April. Feedback from users is so positive that we'll probably get a proper license after that and move to production. I'd gladly try out newer Matterbridge versions, but I'll need fairly comprehensive instructions on what I need to do.

**Comment by 42wim** [comment]
@ExTechOp I've released a beta version which include this fix.
See https://github.com/42wim/matterbridge/releases/tag/v0.11.0-beta1
Let me know how this works for you.

**Comment by ExTechOp** [comment]
We've now installed this beta version and it seems to do pretty much what is wanted: only one irc connection is opened per channel. However, a new "feature" is that irc join/leave messages get copied over to Mattermost (though not to xmpp). Is this intentional, configurable, or unintended?

**Comment by 42wim** [comment]
That's an existing feature ```showjoinpart```, but if this isn't enabled it's a bug.
```
#Enable to show users joins/parts from other bridges (only from irc-bridge at the moment)
#OPTIONAL (default false)
ShowJoinPart=false
```

**Comment by 42wim** [comment]
@ExTechOp try latest beta https://github.com/42wim/matterbridge/releases/tag/v0.11.0-beta2
Fixes the join/leave issue

**Comment by ExTechOp** [comment]
We are currently running this latest beta. The join/leave issue seems to be corrected, while only one irc connection is still opened for all channels. Seems good!

**Comment by 42wim** [comment]
Great!
