### ISSUE TITLE
Picture transparency not retained

### ISSUE THREAD

**Issue by MrBuddyCasino** [42wim/matterbridge#870]
**Describe the bug**

**To Reproduce**
Post a picture/sticker in Telegram. The transparent background in a connected Slack channel has become grey.

**Expected behavior**
Transparency should be retained.

**Screenshots/debug logs**
see screenshots

**Environment (please complete the following information):**
 - OS: Mac
 - Matterbridge version: 1.15.1

**Comment by MrBuddyCasino** [comment]
Slack:
![image](https://user-images.githubusercontent.com/3044875/62615606-e4738480-b90d-11e9-8c59-e47ea0bc4a28.png)
Telegram:
![image](https://user-images.githubusercontent.com/3044875/62615616-e6d5de80-b90d-11e9-961e-5d5a2c3967f9.png)

**Comment by 42wim** [comment]
Can you try dev build https://bintray.com/42wim/nightly/Matterbridge/v1.15.1-9-g9200eb0#files and let me know if this fixes it?

**Comment by 42wim** [comment]
@MrBuddyCasino can you test it?

**Comment by MrBuddyCasino** [comment]
Sorry traveling rn, will take some time until I‘m back home.

**Comment by 42wim** [comment]
Closing because no feedback
