### ISSUE TITLE
[whatsapp] connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by laundmo** [42wim/matterbridge#871]
### This is related/the same as #747 #783 but it still exists although those are closed

**Describe the bug**
After running the bridge for more than 2h i start getting the whatsapp error once and the other one on every message:
```
[2019-08-08T21:20:03+02:00]  INFO main:         Gateway(s) started succesfully. Now relaying messages
[2019-08-08T21:38:16+02:00] ERROR gateway:      SendMessage failed: sending message timed out
[2019-08-08T22:16:10+02:00] ERROR whatsapp:     connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpected EOF
[2019-08-08T22:47:25+02:00] ERROR gateway:      SendMessage failed: could not send proto: failed to write message: error writing to websocket: write tcp 00.00.00.00:9999->00.00.00.00:9999: wsasend: An established connection was aborted by the software in your host machine.
```
i redacted the IP adresses from the error message

**To Reproduce**
just run with the provided configuration
**Expected behavior**
Messages should send

**Screenshots/debug logs**
![](https://i.imgur.com/rGzkKyD.png)
**Environment (please complete the following information):**
 - OS: Windwos 10 64bit
 - Matterbridge version: `1.15.1 87788f3`

**Additional context**
```
[slack]
[slack.myslack]
Token="xoxb-99999999-9999999999999999-qwertzuiopQWERTZUIOP"
RemoteNickFormat=""

[whatsapp.mywhatsapp]
# Number you will use as a relay bot. Tip: Get some disposable sim card, don't rely on 
# your own number.
Number="+999999999"
SessionFile="session-999999999.gob"
RemoteNickFormat=""

[[gateway]]
name="toWhatsapp"
enable=true

[[gateway.in]]
account="slack.myslack"
channel="ID:QWERTZUIOP"

[[gateway.out]]
account="whatsapp.mywhatsapp"
channel="999999999999-99999999999@g.us"```

**Comment by laundmo** [comment]
could this be related to my mobile device closing whatsapp/losign connection, as mentioned here Rhymen/go-whatsapp/issues/106

**Comment by laundmo** [comment]
It seems i found a workaround

i made a shell script to send a webhook to discord (slack would also work)
```
url='https://discordapp.com/api/webhooks/99999999999999999/123456789091234567890qwertzuiop$
curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"keepalive msg\"}" $url
```

then i made a 2 minute cron job for that script, and a gateway to a whatsapp group with only the host number in it. this ensures that whatsapp stays alert and doesn't shut down what seems to be causing the error.

so basically i make matterbridge send a new whatsapp message every 2 minutes.

**Comment by 42wim** [comment]
I've made a PR that has the latest whatsapp code vendored in, you can find test binaries on https://bintray.com/42wim/nightly/Matterbridge/v1.15.1-3-gd0126bf#files

If this doesn't solve it, it's not an issue matterbridge can fix, but you'll have to open an issue at https://github.com/Rhymen/go-whatsapp

Could you let me know if this solves it or not?

**Comment by 42wim** [comment]
Any change?
