### ISSUE TITLE
Telegram: animated stickers

### ISSUE THREAD

**Issue by Oreolek** [42wim/matterbridge#874]
Telegram introduced animated stickers in TGS format. They don't get converted to PNG. And the browsers can't show them either. Maybe convert them to APNG?

**Comment by 42wim** [comment]
Sure, do you know a library that can do that?

**Comment by Oreolek** [comment]
No and we'll have to wait until this will be in the open source Telegram version.

**Comment by TomTheDragon** [comment]
The only tool that could do something like this (right now) is the python package TGS. It could convert those files into video or GIFs.
https://gitlab.com/mattia.basaglia/tgs

**Comment by BenWiederhake** [comment]
There is the python library [lottie](https://pypi.org/project/lottie/), and after a single `pip3 install lottie cairosvg` you can convert stickers like this:

```
$ lottie_convert.py example.tgs example.webp
WebP frame rendering completed
WebP Writing to file...
```

Which results in a webp file (and GitHub can't deal with WebP yet).

Can this plus tengo do this? I hope that the image is already somewhere on the filesystem, in which case Tengo would need to intercept the outgoing message, call `lottie_convert.py --input-format lottie /path/to/the.tgs.webp /path/to/the.webp`, and modify the message to point to the new file instead (`/path/to/the.webp`).

Is there anyone here who knows tengo well enough?

**Comment by 42wim** [comment]
Fixed in #1173

**Comment by Drjacky** [comment]
@BenWiederhake I did exactly what you said but, it doesn't find the `lottie_converter.py`!
<img width="315" alt="Screen Shot 2021-02-27 at 13 31 50" src="https://user-images.githubusercontent.com/2296754/109388622-27d28100-7900-11eb-8ee4-c26646c6c62a.png">

**Comment by BenWiederhake** [comment]
Well, yes, as you observed correctly, it has to be actually installed.

**Comment by Drjacky** [comment]
@BenWiederhake My bad. After installed https://pillow.readthedocs.io/en/stable/installation.html, it worked But, the result wasn't good enough. I've tested this sticker to JSON:
https://t.me/addstickers/RickAndMorty
In a few frames, the picture gets black-white. For sample:
[untitled folder.zip](https://github.com/42wim/matterbridge/files/6060985/untitled.folder.zip)
