### ISSUE TITLE
ColorNicks use the same color as IRC client background

### ISSUE THREAD

**Issue by dannycolin** [42wim/matterbridge#881]
**Describe the bug**
ColorNicks use the same color as the IRC Client (Weechat) background.

**To Reproduce**
1. Set `colornicks` to `true`

**Expected behavior**
ColorNicks shouldn't use the same color as the IRC client background

**Screenshots/debug logs**
https://dannycolin.com/screenshots/matterbridge-colornicks-same-color-as-background.jpg

**Environment (please complete the following information):**
 - OS: Debian 10 (Linux)
 - Matterbridge version: version: 1.15.1 87788f3

**Additional context**
- A solution could be to avoid using color 0,7,8,15 (black/white + light variant) in a 16-colors palette or to add an exclude setting.
- I'm not the administrator of the bridge.

**Comment by 42wim** [comment]
The color avoidance is a possible idea, but it's hard to fix this as people can use any color they want as background :)

Maybe it's possible to create/use a weechat script that strips the colors (seems to exist in https://weechat.org/scripts/stable/tag/color/) or another one that changes the color if it's the same as your background.

**Comment by dannycolin** [comment]
> The color avoidance is a possible idea, but it's hard to fix this as people can use any color they want as background :)

I think having an option to exclude some colors, like the telebot (Telegram/IRC) has, would help resolve at least 90% of the case. I mean the majority of people use color0 or color15 (black and white) as their background color when using a terminal client.

**Comment by 42wim** [comment]
color0 and color15 are already excluded
https://github.com/42wim/matterbridge/blob/f66d5f1e58b25df47d8062481a25dd1522e693b0/bridge/irc/irc.go#L210

But I found a solution to your problem. 

1. Remove the `ColorNicks=true` option from your config.

1. Copy the internally used `outmessage.tengo` somewhere on your system 
https://raw.githubusercontent.com/42wim/matterbridge/master/internal/tengo/outmessage.tengo

1. Append the new `outmessage-irccolornick.tengo` to it https://raw.githubusercontent.com/42wim/matterbridge/master/contrib/outmessage-irccolornick.tengo but remove the 
```
text := import("text")
fmt := import("fmt")
```

1. And add the logic to exclude colors, I've made an example to exclude color14

Resulting file is

```
/*
variables available
read-only:
inAccount, inProtocol, inChannel, inGateway
outAccount, outProtocol, outChannel, outGateway

read-write:
msgText, msgUsername
*/

text := import("text")

// start - strip irc colors
// if we're not sending to an irc bridge we strip the IRC colors
if inProtocol == "irc" {
    re := text.re_compile(`\x03(?:\d{1,2}(?:,\d{1,2})?)?|[[:cntrl:]]`)
    msgText=re.replace(msgText,"")
}
// end - strip irc colors

// See https://github.com/42wim/matterbridge/issues/881
// Generates a colored nick for each msgUsername, with example to filter specific codes

if outProtocol == "irc" {
    // generate a color for a nick, make sure it isn't 0 or 15
    colorCode := len(msgUsername)+bytes(msgUsername)[0]%14 + 2
    // example if we want to use colorCode 3 when we have calculated colorcode 14
    if colorCode == 14 {
        colorCode = 3
    }
    msgUsername=fmt.sprintf("\x03%02d%s\x0F", colorCode, msgUsername)
}
```

1. Now add create a `[tengo]` section in your `matterbridge.toml` 
1. Add `OutMessage="locationofthefile/outmessage.tengo"` to that section

More information about tengo https://github.com/42wim/matterbridge/wiki/Settings#tengo

**Comment by poVoq** [comment]
@42wim this doesn't seem to work anymore No regular irc channels it stops sending colors all together and on RELAYMSG supporting ones it breaks the bridge completely.

**Comment by poVoq** [comment]
![irc_colors](https://user-images.githubusercontent.com/940360/121760818-3b56d000-cb1c-11eb-9840-f2e19af5bd7e.png)
