### ISSUE TITLE
[0001] ERROR irc:          disconnect: error: remote error: tls: handshake failure

### ISSUE THREAD

**Issue by hramrach** [42wim/matterbridge#887]
**Describe the bug**
Connection fails without any explanation whatsoever. Connection with openssl s_client works.

```
openssl s_client -host irc.suse.de -port 6697
CONNECTED(00000003)
depth=3 C = DE, ST = Franconia, L = Nuremberg, O = SUSE Linux Products GmbH, OU = OPS Services, CN = SUSE Trust Root, emailAddress = rd-adm@suse.de
verify return:1
depth=2 C = DE, ST = Franconia, L = Nuremberg, O = SUSE Linux Products GmbH, OU = OPS Services, CN = SUSE CA Root, emailAddress = rd-adm@suse.de
verify return:1
depth=1 C = DE, ST = Franconia, L = Nuremberg, O = SUSE Linux Products GmbH, OU = OPS Services, CN = SUSE CA suse.com, emailAddress = rd-adm@suse.de
verify return:1
depth=0 C = DE, ST = Franconia, L = Nuremberg, O = SUSE Linux Products GmbH, OU = OPS Services, CN = perelman.suse.de, emailAddress = rd-adm@suse.de
verify return:1
---
Certificate chain
 0 s:/C=DE/ST=Franconia/L=Nuremberg/O=SUSE Linux Products GmbH/OU=OPS Services/CN=perelman.suse.de/emailAddress=rd-adm@suse.de
   i:/C=DE/ST=Franconia/L=Nuremberg/O=SUSE Linux Products GmbH/OU=OPS Services/CN=SUSE CA suse.com/emailAddress=rd-adm@suse.de
 1 s:/C=DE/ST=Franconia/L=Nuremberg/O=SUSE Linux Products GmbH/OU=OPS Services/CN=SUSE CA suse.com/emailAddress=rd-adm@suse.de
   i:/C=DE/ST=Franconia/L=Nuremberg/O=SUSE Linux Products GmbH/OU=OPS Services/CN=SUSE CA Root/emailAddress=rd-adm@suse.de
 2 s:/C=DE/ST=Franconia/L=Nuremberg/O=SUSE Linux Products GmbH/OU=OPS Services/CN=SUSE CA Root/emailAddress=rd-adm@suse.de
   i:/C=DE/ST=Franconia/L=Nuremberg/O=SUSE Linux Products GmbH/OU=OPS Services/CN=SUSE Trust Root/emailAddress=rd-adm@suse.de
 3 s:/C=DE/ST=Franconia/L=Nuremberg/O=SUSE Linux Products GmbH/OU=OPS Services/CN=SUSE Trust Root/emailAddress=rd-adm@suse.de
   i:/C=DE/ST=Franconia/L=Nuremberg/O=SUSE Linux Products GmbH/OU=OPS Services/CN=SUSE Trust Root/emailAddress=rd-adm@suse.de
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGYTCCBEmgAwIBAgIJAM2g7C1hQrevMA0GCSqGSIb3DQEBCwUAMIGpMQswCQYD
VQQGEwJERTESMBAGA1UECBMJRnJhbmNvbmlhMRIwEAYDVQQHEwlOdXJlbWJlcmcx
ITAfBgNVBAoTGFNVU0UgTGludXggUHJvZHVjdHMgR21iSDEVMBMGA1UECxMMT1BT
IFNlcnZpY2VzMRkwFwYDVQQDExBTVVNFIENBIHN1c2UuY29tMR0wGwYJKoZIhvcN
AQkBFg5yZC1hZG1Ac3VzZS5kZTAeFw0xOTA2MTkwNTQ2MDBaFw0yMjA2MTkwNTQ2
MDBaMIGpMQswCQYDVQQGEwJERTESMBAGA1UECBMJRnJhbmNvbmlhMRIwEAYDVQQH
EwlOdXJlbWJlcmcxITAfBgNVBAoTGFNVU0UgTGludXggUHJvZHVjdHMgR21iSDEV
MBMGA1UECxMMT1BTIFNlcnZpY2VzMRkwFwYDVQQDExBwZXJlbG1hbi5zdXNlLmRl
MR0wGwYJKoZIhvcNAQkBFg5yZC1hZG1Ac3VzZS5kZTCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBANaoxL+E0w/LV+aENeMprzgDnRjyLa0yrXkDkIyr9QNP
FXiCwzdiqMMcXmhr43H5FaA0R3B9VR33T8GVOmJo/b2tN4Qn73gYitzSo8XkkNGp
FHfQjyg9QyM6uTjJHnQ7sBTjVYiSCnwoJKO19nRoQe6kH+ZYRRIzZUJaREY/LSF5
BzE2azw2B4J7VZa9t4c6DuW1MeLaerVLw5V/FXxlxBG1KzCUbDKmzSF6xfp0gnZ0
gO3bh2mDwoAidxddE16My097JPL5BM51oXip0UZT6E5e9d4vWeoDRGMDi6k3QaKv
Ms/NnnvxbQL/dx9qYKZ0d6hQVWshLRNOJn/Q+6bwWs0CAwEAAaOCAYgwggGEMAwG
A1UdEwEB/wQCMAAwHQYDVR0OBBYEFDm9s0zsKUKsH/B1cQQNhKzfp3wGMIHSBgNV
HSMEgcowgceAFIzvkdfJaRv00r6Xtvjw+G74KH5uoYGrpIGoMIGlMQswCQYDVQQG
EwJERTESMBAGA1UECBMJRnJhbmNvbmlhMRIwEAYDVQQHEwlOdXJlbWJlcmcxITAf
BgNVBAoTGFNVU0UgTGludXggUHJvZHVjdHMgR21iSDEVMBMGA1UECxMMT1BTIFNl
cnZpY2VzMRUwEwYDVQQDEwxTVVNFIENBIFJvb3QxHTAbBgkqhkiG9w0BCQEWDnJk
LWFkbUBzdXNlLmRlggEGMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEF
BQcDAQYIKwYBBQUHAwIwUQYDVR0RBEowSIIVcGVyZWxtYW4ubnVlLnN1c2UuY29t
ghBwZXJlbG1hbi5zdXNlLmRlghBpcmMubnVlLnN1c2UuY29tggtpcmMuc3VzZS5k
ZTANBgkqhkiG9w0BAQsFAAOCAgEALeaj3QVJZCEtZ5J5kQebIobha/6NAEQ83DIb
ZWD0cas8QySYKxH48fwwN9KZ6YyrbCRCURyBnFDrAGeSbK1L4m0LftHGc1AamTrV
rd+mY6h+6n/Y8lpyNfd8W9ZXYLbjf6B3XgQDLd32N6e+P3hqoIZ5gxwVrt8crQVf
gs3HHOKcBv5gy/rCmA7NRIbXZfDytWVHUJBjGQ7SpUkspmc5l851hWn6Tg9q7dyg
gR5mJIfqK5v+FEs6M7pRQTKM3F8LpwZ/kGRcnAOFKDiLCeS2zfmYB1ai3Tmm/pwJ
gyrz3Dd6upqfkG5VJt0BXO+gWYd5IeEHTcVTnOFB/ZTY5k+n2exORb58j8zzWLBB
tIosreHveg7lrHxKMB35itjPMl7wOkxwsRQ/6SPaEJkjF6ri4nWuBBzkLQ361Ew0
ZXa0J//qiA8wWOyzMfFFtLkkXjQi2VSr6RveEXJUg5YE8IwF27L9JCzrHwIuLXeK
zYAfx6dBRTrSEEViAG6TWmGWEvnuQ1UIzYcoyBMl4Vf1dbwK01iaw0JSa8ByvWCs
laOM7rUbQcjaAAE7ZluhJid84lrvaZn442r5gDwL7rLdldQXOY8O3kZ+HsYMsNpp
b35h19eClyhNNfO4vBBJGCSGCE3uf6fmrulFOa8f3MILFlIVJDkDOsa4dE9gbTFE
W7ZrUK0=
-----END CERTIFICATE-----
subject=/C=DE/ST=Franconia/L=Nuremberg/O=SUSE Linux Products GmbH/OU=OPS Services/CN=perelman.suse.de/emailAddress=rd-adm@suse.de
issuer=/C=DE/ST=Franconia/L=Nuremberg/O=SUSE Linux Products GmbH/OU=OPS Services/CN=SUSE CA suse.com/emailAddress=rd-adm@suse.de
---
No client certificate CA names sent
Client Certificate Types: RSA fixed DH, DSS fixed DH, RSA sign, DSA sign, ECDSA sign
Server Temp Key: DH, 2048 bits
---
SSL handshake has read 7931 bytes and written 514 bytes
Verification: OK
---
New, SSLv3, Cipher is DHE-RSA-AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : DHE-RSA-AES256-SHA
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: F0DF1A2B64B500E77F76786ACC839A7EC4D194FD794D89A16ACD2630B6A8D3BD92D02A40DFEA4632C2D9D7C5EC3AC32B
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1568054578
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
:perelman.suse.de NOTICE Auth :*** Looking up your hostname...

```
**To Reproduce**
Include SSL irc server in bridge.

**Expected behavior**
Connects to server or provides enough information to debug issue.

**Screenshots/debug logs**

./matterbridge-1.16.0-linux-64bit -debug
[0000]  INFO main:         Enabling debug logging.
[0000]  INFO main:         Running version 1.16.0 45becd2
[0000] DEBUG rocketchat:   enabling rocketchat
[0000]  INFO router:       Parsing gateway samechannel1
[0000]  INFO router:       Starting bridge: mattermost.test 
[0000]  INFO mattermost:   Connecting using login/password (sending and receiving)
[0000]  INFO mattermost:   Connecting matterbridge (team: suse) on 10.162.187.231
[0000]  INFO matterclient: Found version 5.14.0.5.14.1.1073b8b9957848536ce8a5b3cf5ddfce.false
[0000]  INFO matterclient: found 6 users in team suse
[0001]  INFO mattermost:   Connection succeeded
[0001]  INFO mattermost:   mattermost.test: joining kanal (ID: kanalmattermost.test)
[0001]  INFO router:       Starting bridge: rocketchat.suse 
[0001]  INFO rocketchat:   Connecting using login/password (sending and receiving)
[0001] DEBUG rocketchat:   handling apiLogin()
[0001] DEBUG mattermost:   Choosing login/password based receiving
[0001]  INFO rocketchat:   Connection succeeded
[0001]  INFO rocketchat:   rocketchat.suse: joining kanal (ID: kanalrocketchat.suse)
[0001] DEBUG rocketchat:   Choosing login/password based receiving
[0001]  INFO router:       Starting bridge: irc.suse 
[0001]  INFO irc:          Connecting irc.suse.de:6697
[0001] DEBUG irc:          "CLIENT_INIT irc.suse.de:6697"
[0001] DEBUG irc:          "CLIENT_DISCONNECTED irc.suse.de:6697"
[0001] ERROR irc:          disconnect: error: remote error: tls: handshake failure
[0001] FATAL main:         Starting gateway failed: Bridge irc.suse failed to start: connection failed remote error: tls: handshake failure

**Environment (please complete the following information):**
 - OS: OpenSUSE Leap 15.0
 - Matterbridge version: version: 1.16.0 45becd2 (official build)

**Additional context**
[irc]
[irc.suse]
Server="irc.suse.de:6697"
UseTLS=true
SkipTLSVerify=true
Nick="matterbot"
MessageSplit=true
ShowJoinPart=true
[rocketchat]
[rocketchat.suse]
Server="https://chat.suse.de:443"
Login="<removed>"
Password="<removed>"
[mattermost]
[mattermost.test]
Server="10.162.187.231"
Team="suse"
Login="<removed>"
Password="<removed>"
NoTLS=true
ShowJoinPart=true
[general]
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
[[samechannelgateway]]
name="samechannel1"
enable = true
accounts = [ "mattermost.test","rocketchat.suse","irc.suse" ]
channels = [ "kanal"]

**Comment by 42wim** [comment]
The error you see is the one go itself returns, I can't add more debug because there isn't anything else to enable :(

Possible issue is that your cipher `DHE-RSA-AES256-SHA` doesn't seem to be supported by go https://github.com/golang/go/issues/7758 and/or maybe because SSLv3 is deprecated. 

The server doesn't seem to be accessible from the internet so I can't do any tests myself.

**Comment by hramrach** [comment]
It looks like golang/go#7758 applies here. The returned error is not very nice but not something matterbridge can fix.

**Comment by hramrach** [comment]
FTR using s_client with xinetd as proxy (on the same machine, local only) allows connecting to the problematic irc server (still running Linux 3.0, ugh)

service ssl_irc_proxy
{
	type = UNLISTED
	flags = NODELAY
	protocol = tcp
	disable = no
	wait = no
	user = mbirc
	server = /usr/bin/openssl
	server_args = s_client -host irc.server.name -port 6666 -quiet
	port = 6666
	bind = 127.0.0.1
}
