### ISSUE TITLE
When no accounts are connected on gateway matterbridge sits there doing nothing

### ISSUE THREAD

**Issue by hramrach** [42wim/matterbridge#888]
matterbridge with one gateway configured and no accounts starts but does nothing.

 - gateways without accounts should produce a warning
 - when no accounts are configured on any gateway there is no point running - just exit

**Comment by 42wim** [comment]
Thanks for the feedback 👍 
Changes are now in master.

**Comment by hramrach** [comment]
yes, with master matterbridge no longer starts with configuration broken in this way
