### ISSUE TITLE
Editing message with image causes new message to be insterted

### ISSUE THREAD

**Issue by hramrach** [42wim/matterbridge#890]
**Describe the bug**
Editing works for plaintext messages but not messages containing an image

**To Reproduce**
Configured bridge irc (mediaserver), RocketChat, Mattermost

Message typed on MM is displayed in RC and IRC, editing the message causes message to be updated in RC and new message posted in IRC (expected).

Uploading an image with text as message in MM and editing the text in MM causes two messages with image to appear in RC - one with the original text and one with the updated text.

**Expected behavior**
Text posted together with an image can be edited the same way as text without one.

**Screenshots/debug logs**

![screenshot](https://ibin.co/w800/4uYCkIoe1pAW.png)

**Environment (please complete the following information):**
 - OS: OpenSUSE Leap 15.0
 - Matterbridge version: version: 1.16.0 45becd2 (official build)

**Additional context**
<details><summary>matterbridge.toml</summary><br><pre>
[irc]
[irc.suse]
Server="127.0.0.1:6697"
UseTLS=false
SkipTLSVerify=false
Nick="matterbot"
MessageSplit=true
ShowJoinPart=true
[rocketchat]
[rocketchat.suse]
Server="https://chat.suse.de:443"
Login=""
Password=""
[mattermost]
[mattermost.test]
Server="10.162.187.231"
Team="suse"
Login=""
Password=""
NoTLS=true
ShowJoinPart=true
[general]
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
MediaDownloadPath="/srv/www/htdocs/"
MediaServerDownload="http://10.100.51.69"
[[gateway]]
name="gateway1"
enable = true
[[gateway.inout]]
account="irc.suse"
channel="#kanal"
[[gateway.inout]]
account="rocketchat.suse"
channel="#kanal"
[[gateway.inout]]
account="mattermost.test"
channel="kanal"
</pre></details>

**Comment by hramrach** [comment]
how do you attach a screenshot?

**Comment by hramrach** [comment]
![](https://imagebin.ca/v/4uYCkIoe1pAW)

**Comment by 42wim** [comment]
Unfortunately that's something I can't fix. 
The rocketchat rest API doesn't return an identifier when uploading a file with a message (https://rocket.chat/docs/developer-guides/rest-api/rooms/upload/)

As we don't have an ID we can't edit it, that's why the file is reuploaded so the context of the edited message is still there.

Maybe you can open an issue at the rocketchat project.
