### ISSUE TITLE
make samechennelgateway work across protocols with different channel name requireemnts

### ISSUE THREAD

**Issue by hramrach** [42wim/matterbridge#891]
**Is your feature request related to a problem? Please describe.**
Some protocols have specific naming rules that prevent the channel name to be teh same across protocols. Specifically, some protocol require that channel name starts with a a hash and others that it does not. These rules are not enforced leading to erroneous behavior.

**Describe the solution you'd like**
Where clear naming rule exists adapt the channel name to fit the rule so samechennelgateway can work across more protocols.

**Describe alternatives you've considered**
The alternative is to write gateway configuration for each channel separately. Can be scripted I suppose.

**Comment by qaisjp** [comment]
Do you have specific examples? Maybe support for a tengo hook could be leveraged here.

**Comment by hramrach** [comment]
irc vs mattermost and irc vs rocketchat bridging does not work because irc requires # in channel name and the other two require excluding # from channel name.

**Comment by 42wim** [comment]
samechannelgateway is deprecated
