### ISSUE TITLE
messages from mattermost are not being delivered at IRC side

### ISSUE THREAD

**Issue by syamgk** [42wim/matterbridge#90]
while using the webhooks;
the messages from irc channel is being deliverd to mattermost 
but the reverse **mattermost messages to irc is not working**

**Comment by syamgk** [comment]
i've add a diff like this 
"""
diff --git a/matterhook/matterhook.go b/matterhook/matterhook.go
index 0880884..a12d0c5 100644
--- a/matterhook/matterhook.go
+++ b/matterhook/matterhook.go
@@ -105,6 +105,7 @@ func (c *Client) ServeHTTP(w http.ResponseWriter, r *http.Request) {
        defer r.Body.Close()
        decoder := schema.NewDecoder()
        err = decoder.Decode(&msg, r.PostForm)
+  log.Printf("Listening on http://%v...\n", msg)
        if err != nil {
                log.Println(err)
                http.NotFound(w, r)

"""

to print and see the struct and it is getting proper data.
So it might be something happening after that point

**Comment by syamgk** [comment]
diff --git a/matterhook/matterhook.go b/matterhook/matterhook.go
index 0880884..a12d0c5 100644
--- a/matterhook/matterhook.go
+++ b/matterhook/matterhook.go
@@ -105,6 +105,7 @@ func (c *Client) ServeHTTP(w http.ResponseWriter, r *http.Request) {
        defer r.Body.Close()
        decoder := schema.NewDecoder()
        err = decoder.Decode(&msg, r.PostForm)
+  log.Printf("Listening on http://%v...\n", msg)
        if err != nil {
                log.Println(err)
                http.NotFound(w, r)

**Comment by syamgk** [comment]
i've made a patch to verify whether the ```struct msg``` is properly decoded
```
diff --git a/matterhook/matterhook.go b/matterhook/matterhook.go
index 0880884..a12d0c5 100644
--- a/matterhook/matterhook.go
+++ b/matterhook/matterhook.go
@@ -105,6 +105,7 @@ func (c *Client) ServeHTTP(w http.ResponseWriter, r *http.Request) {
        defer r.Body.Close()
        decoder := schema.NewDecoder()
        err = decoder.Decode(&msg, r.PostForm)
+  log.Printf("Listening on http://%v...\n", msg)
        if err != nil {
                log.Println(err)
                http.NotFound(w, r)
 
```
and found that it is getting the proper data,
So the problem might be happening after that point

**Comment by 42wim** [comment]
Hi could you run matterbridge with ```-debug``` option, reproduce the issue, paste (complete) output here.
Also paste your config file (don't forget to remove private/authentication stuff)

**Comment by syamgk** [comment]
ahh, it was something missing from config file 
seems like we should do more documentation on config file

**Comment by whiskeyneon** [comment]
@syamgk if you don't mind sharing, what was the missing configuration option? I am currently experiencing the same issue.

**Comment by syamgk** [comment]
@whiskeyneon  
```
[mattermost]
[mattermost.test]
Enable=true 
```
i missed the `Enable=true` part
