### ISSUE TITLE
How do I sync Telegram avatars with Slack avatars?

### ISSUE THREAD

**Issue by rubendibattista** [42wim/matterbridge#907]
### Environment

Version:
`version: 1.16.0 45becd2`

Operating system: CentOS 7

### Please describe the expected behavior.
Avatars from Telegram are synced on Slack

### Please describe the actual behavior. 

I don't know how to set it up :)? Currently is clearly using icons from `robohash`. How do I make it using Telegram user avatars?

### Please add your configuration file 

```

[slack]
[slack.skyward]
Token="xoxb-*****"
RemoteNickFormat="@{NICK}"
Debug="false"
IconURL="https://robohash.org/{NICK}.png?size=48x48"

[telegram]
[telegram.skyward]
Token="****"
UseFirstName=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
    name = "skygate"
    enable = true
    [[gateway.inout]]
    account = "slack.skyward"
    channel = "alumni"

    [[gateway.inout]]
    account = "telegram.skyward"
    channel = "***"
```

**Comment by 42wim** [comment]
You can remove the IconURL.
Avatars from telegram shoudl be visible in slack, but not the other way around (telegram has no support for that)

**Comment by rubendibattista** [comment]
Just tried, it's posting the default one. I guess I need the media server running, then?
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/8077364/67634491-fe918300-f8bc-11e9-9d5f-a81e1ebf172a.png">

**Comment by rubendibattista** [comment]
Up? :)

**Comment by 42wim** [comment]
@rubendibattista you need to run mediaserver, because we have to download the avatars and expose them to the other bridges.

See https://github.com/42wim/matterbridge/wiki/Mediaserver-setup-%28advanced%29
