### ISSUE TITLE
[Telegram -> Discord] Media content gets posted twice

### ISSUE THREAD

**Issue by TomTheDragon** [42wim/matterbridge#908]
When someone postes an "GIF" or pictures on Telegram, i can see a link from our media server and also a second time, as it uploads the content to the Discord servers.

![grafik](https://user-images.githubusercontent.com/7361323/65528919-8caccf00-def5-11e9-8983-113594e678b2.png)

And yes we are using Webhooks.

**Comment by 42wim** [comment]
What version of matterbridge ?

**Comment by 42wim** [comment]
Found the issue in v1.16.0, so I guess you're using that one :)

**Comment by TomTheDragon** [comment]
Yes i was running v1.16.0 and yes its fixed now, thanks again! :)

**Comment by Lejo1** [comment]
I've got the same problem for WhatsApp to Discord
