### ISSUE TITLE
Add command to query list of users behind the bridge

### ISSUE THREAD

**Issue by Wuzzy2** [42wim/matterbridge#911]
**Is your feature request related to a problem? Please describe.**
As an IRC user, I see myself unable to see who is behind the bridge. All I see is the bridge user itself, but that's it.

**Describe the solution you'd like**
Add support for a special bot command that, when sent to the bot, replies with a list of all people behind the bridge, and maybe also what system they use.

To avoid polluting the chat, make the bot only accept `/msg` messages.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by qaisjp** [comment]
I am happy to provide a pull request to implement this [for Hacktoberfest :wink:]

**Comment by 42wim** [comment]
This should be part of the larger feature https://github.com/42wim/matterbridge/issues/191
I've worked a bit on this in fb713ed91bfb48c0037e489f80be85c54e69953a but had to revert because of issues with large channels.

**Comment by qaisjp** [comment]
That's okay :)

**Comment by 42wim** [comment]
Going to close this as it is basically a ..
Duplicate of #191
