### ISSUE TITLE
Matterbridge crashes because of Mattermost

### ISSUE THREAD

**Issue by poVoq** [42wim/matterbridge#915]
**Describe the bug**
Bridging IRC to Mattermost and Discord, the bridge regularly crashes because of what seems to be a Mattermost related issue. 

**To Reproduce**
Connect to Mattermost server (Team Edition 0.15.0, but also happend also with previous versions) and wait a few hours/days for it to crash.

**Expected behavior**
Should not crash :)

**Screenshots/debug logs**
```
time="2019-10-03T00:38:05Z" level=error msg="Connection is not alive: &model.AppError{Id:"model.client.connecting.app_error", Message:"model.client.connecting.app_error", DetailedError:"Get https://mattermost.example.com/api/v4/users/me: net/http: request canceled (Client.Timeout exceeded while awaiting headers)", RequestId:"", StatusCode:0, Where:"https://mattermost.example.com/api/v4/users/me", IsOAuth:false, params:map[string]interface {}(nil)}" prefix=matterclient

time="2019-10-03T06:59:39Z" level=error msg="error:read tcp 172.17.0.2:32868->188.68.36.32:443: use of closed network connection" prefix=matterclient

time="2019-10-03T07:12:13Z" level=error msg="SendMessage failed: : Invalid or expired session, please login again., " prefix=gateway
```

**Environment (please complete the following information):**
 - OS: Official Docker images
 - Matterbridge version: 42wim/matterbridge:latest

**Comment by 42wim** [comment]
That's an issue with sessions on the mattermost side. 
Look at https://forum.mattermost.org/t/solved-removing-the-session-timeout/3033 for a solution or use personal tokens, those don't expire. See https://docs.mattermost.com/developer/personal-access-tokens.html

**Comment by poVoq** [comment]
@42wim strangely even after switching to a personal access token this error persists.

**Comment by 42wim** [comment]
@poVoq if you get the `Invalid or expired session, please login again` message when using personal tokens, please open an issue at https://github.com/mattermost/mattermost-server
