### ISSUE TITLE
Bold and Strikethrough not working Slack->Mattermost

### ISSUE THREAD

**Issue by zjoasan** [42wim/matterbridge#918]
**Describe the bug**
Bold text from Slack to Mattermost is represented in mattermost as italics
Strikethrough in Slack just shows as `~text~` in Mattermost

**To Reproduce**
Try this text in Slack: `*bold* ~strikethrough~`

**Expected behavior**
Bold text (`*bold*`) should be translated to `**bold**` and thereby shown as bold in Mattermost.
Strikethrough (`~text~`) should be translated to `~~text~~` and thereby show as strikethrough in MAttermost.

**Screenshots/debug logs**
If needed it will be provided on request.

**Environment (please complete the following information):**
 - OS: Lubuntu 64bit VM
 - Matterbridge version: version: 1.16.0 45becd2

**Additional context**

> [slack]
> [slack.test]
> Token="token"
> PrefixMessagesWithNick=true
> 
> [mattermost]
>     [mattermost.work]
>     Server="127.0.0.1:8065"
>     Team="test"
>     Login="user@email"
>     Password="password"
>     NoTLS=true
>     PrefixMessagesWithNick=true
>     RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
> 
>     [mattermost.notwork]
>     Server="127.0.0.1:8065"
>     Team="test"
>     Login="user2@email"
>     Password="another password"
>     NoTLS=true
>     PrefixMessagesWithNick=false
> 
> 
> [[gateway]]
>     name = "mygateway"
>     enable=true
> 
>     [[gateway.in]]
>     account ="slack.test"
>     channel = "general"
> 
>     [[gateway.out]]
>     account="mattermost.work"
>     channel="off-topic"
> 
>     [[gateway.out]]
>     account="mattermost.notwork"
>     channel="off-topic"
>

**Comment by qaisjp** [comment]
yeah generally formatting stuff isn't converted. there's similar issues with slack and discord. a solution here is to decide on a standard — say (a superset of) GFM or CommonMark, and then translate between Slack and CommonMark, and CommonMark and Mattermost
