### ISSUE TITLE
How to create whatsapp autoresponder? 

### ISSUE THREAD

**Issue by beshoo** [42wim/matterbridge#919]
Dear all. 
I want to create Whatsapp autoresponder, i found that this lib can analyze web whatsapp as

https://github.com/42wim/matterbridge/wiki/Section-WhatsApp-(basic)

But there is no documentation how to do that. 
Is there any documentation regarding send and receive text /media. 

I want to creat such json api for that. 
Please advise. 

And btw dos this lib support http proxy? 

Regard

**Comment by 42wim** [comment]
This is out of scope for matterbridge.
You can better look for this in the library matterbridge uses: https://github.com/Rhymen/go-whatsapp
