### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by 42wim** [42wim/matterbridge#92]
- [ ] more explicit about using a dedicated user for slack / mattermost
- [ ] docker and NoTLS=true
- [ ] mattermost doesn't send avatars with messages

**Comment by Aldian-fr** [comment]
Note: as for developpement head branch, Go 1.6+ requirement from the doc is outdated. It should be updated to 1.7+. With Go 1.6 the go get instruction gets the error 

> unrecognized import path "context"

**Comment by 42wim** [comment]
@Aldian-fr that's strange. 
Just tried myself with go1.6

```
$ go version
go version go1.6 linux/amd64
$ go get github.com/42wim/matterbridge
$ ls -alt bin/
total 19328
drwxr-xr-x 2 wim wim     4096 Jun 18 22:07 .
drwxr-xr-x 5 wim wim     4096 Jun 18 22:07 ..
-rwxr-xr-x 1 wim wim 19783552 Jun 18 22:07 matterbridge
```
What does your ```go version``` show? what distribution ?

**Comment by 42wim** [comment]
https://github.com/42wim/matterbridge/wiki
