### ISSUE TITLE
Error: Failed to read configuration file

### ISSUE THREAD

**Issue by Saylrman64** [42wim/matterbridge#922]
Hello,

On run of matterbridge I am getting the error:
Failed to read configuration file: &os.PathError{Op:"open", Path:"/etc/mattermost/matterbridge.toml", Err:0xd}

The file exists and it is a properly formatted toml file.
I've searched Git and Google and find nothing addressing this type of error.

**Operating system**
Ubuntu 16.04.5 LTS

-----------------------

**Installed using**
# snap install matterbridge
Installed while in sudo -i (as root)
-----------------------

**Describe the expected behavior**
Matterbridge should run

-----------------------

**Describe the actual behavior**
[0000]  INFO main:         Enabling debug logging.
[0000]  INFO main:         Running version 1.16.0
[0000] FATAL config:       Failed to read configuration file: &os.PathError{Op:"open", Path:"/etc/mattermost/matterbridge.toml", Err:0xd}

-----------------------

**Steps to reproduce the behavior**
Running command:
# matterbridge -conf /etc/mattermost/matterbridge.toml

-----------------------

**Configuration file - /etc/mattermost/matterbridge.toml**

[slack]
[slack.myslack]
Token="xoxb-blerg"
RemoteNickFormat="{BRIDGE} - @{NICK}"

[mattermost.mymattermost]
#The mattermost hostname. (do not prefix it with http or https)
Server="server.site.com:xxxx"

#the team name as can be seen in the mattermost webinterface URL
#in lowercase, without spaces
Team="the-a-team"

#login/pass of your bot.
#Use a dedicated user for this and not your own!
Login="user_name"
Password="Password"

#Enable this (set to true) to make a http connection
#(instead of https) to your mattermost.
NoTLS=false
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
PrefixMessagesWithNick=true

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="slack.myslack"
channel="general"

[[gateway.inout]]
account="mattermost.mymattermost"
channel="off-topic"

-----------------------

**File structure permissions**
root@email:~# ll -R /snap/matterbridge/
/snap/matterbridge/:
total 8
drwxr-xr-x 3 root root 4096 Oct 18 16:30 ./
drwxr-xr-x 5 root root 4096 Oct 18 16:30 ../
drwxr-xr-x 5 root root   86 Sep 23 05:01 85/
lrwxrwxrwx 1 root root    2 Oct 18 16:30 current -> 85/

/snap/matterbridge/85:
total 5
drwxr-xr-x 5 root root   86 Sep 23 05:01 ./
drwxr-xr-x 3 root root 4096 Oct 18 16:30 ../
drwxr-xr-x 2 root root   35 Sep 23 05:01 bin/
-rwxr-xr-x 1 root root  164 Sep 23 05:01 command-matterbridge.wrapper*
drwxr-xr-x 3 root root   43 Sep 23 05:01 meta/
drwxr-xr-x 2 root root   58 Sep 23 05:01 snap/

/snap/matterbridge/85/bin:
total 41594
drwxr-xr-x 2 root root       35 Sep 23 05:01 ./
drwxr-xr-x 5 root root       86 Sep 23 05:01 ../
-rwxr-xr-x 1 root root 42591249 Sep 23 05:01 matterbridge*

/snap/matterbridge/85/meta:
total 1
drwxr-xr-x 3 root root  43 Sep 23 05:01 ./
drwxr-xr-x 5 root root  86 Sep 23 05:01 ../
drwxr-xr-x 2 root root   3 Sep 23 05:01 gui/
-rw-r--r-- 1 root root 393 Sep 23 05:01 snap.yaml

/snap/matterbridge/85/meta/gui:
total 0
drwxr-xr-x 2 root root  3 Sep 23 05:01 ./
drwxr-xr-x 3 root root 43 Sep 23 05:01 ../

/snap/matterbridge/85/snap:
total 23
drwxr-xr-x 2 root root    58 Sep 23 05:01 ./
drwxr-xr-x 5 root root    86 Sep 23 05:01 ../
-rw-r--r-- 1 root root 21240 Sep 23 05:01 manifest.yaml
-rw-r--r-- 1 root root  1242 Sep 23 04:58 snapcraft.yaml

**Comment by 42wim** [comment]
I don't know how snap works, but if matterbridge says it can't find the config file the config file isn't there.

Try a release binary: https://github.com/42wim/matterbridge/releases/download/v1.16.0/matterbridge-1.16.0-linux-64bit

And run this binary with `-conf /etc/mattermost/matterbridge.toml`

**Comment by Saylrman64** [comment]
I removed the install using # snap remove matterbridge.
Downloaded the binary using the link you provided.
# chmod +x matterbridge...
It runs using the same config file.

It must be something about the file structure it was built in with snap.
There were several symlinks.

All good !

Thank you!

**Comment by codinghedgehog-python** [comment]
By the way, this is still an issue. I've tried to use the latest stable release and it still throws the above error.
How many people can't get a bot working between different apps ...

**Comment by paulsybrandy** [comment]
Now I have downloaded the binary, and I have run the "-conf /etc/mattermost/matterbridge.toml" with the binary with the same error. At a loss...

$ ./matterbridge-1.26.0-linux-64bit -conf /etc/mattermost/matterbridge.toml

`[0000]  INFO main:         Running version 1.26.0 6dafebc7

[0000] FATAL config:       Failed to read configuration file: &fs.PathError{Op:"open", Path:"/etc/mattermost/matterbridge.toml", Err:0x2} `
