### ISSUE TITLE
Shorter PROTOCOL ident in nicknames

### ISSUE THREAD

**Issue by TheHolyRoger** [42wim/matterbridge#934]
**Is your feature request related to a problem? Please describe.**
The output across bridges can get quite long when including the protocol in each message

**Describe the solution you'd like**
It would be nice to have an option to show only first 1 or X characters of the protocol, e.g.:
`<nick> [irc]: text`
`<nick> [dis]: text`
`<nick> [tel]: text`

**Comment by 42wim** [comment]
This can be solved using tengo, see https://github.com/42wim/matterbridge/issues?q=label%3Atengo+is%3Aclosed for some examples

https://github.com/42wim/matterbridge/issues/826 is more or less an example that maches your question

**Comment by TheHolyRoger** [comment]
Aha thanks @42wim !

https://github.com/42wim/matterbridge/issues/822#issuecomment-493260864

This was helpful too!
