### ISSUE TITLE
[REVIEW REQUEST] Changes in wiki

### ISSUE THREAD

**Issue by ViRb3** [42wim/matterbridge#935]
Since changes to the wiki are saved directly, I wanted to make sure I didn't make any mistakes with my edit. Please take a look here: 
https://github.com/42wim/matterbridge/wiki/Gateway-config-(channel-rules)

Thanks!

**Comment by qaisjp** [comment]
Oh, hi Victor!

Here's the [diff], [old] and [new] pages, for those that want to see it.

[diff]: https://github.com/42wim/matterbridge/wiki/Gateway-config-(channel-rules)/_compare/664cfbd343a68a587d7368a2881fa4f1d79fbba9...bda41b26dc1a4e3f1d5fddff94870f0447e46e0d
[old]: https://github.com/42wim/matterbridge/wiki/Gateway-config-(channel-rules)/bda41b26dc1a4e3f1d5fddff94870f0447e46e0d
[new]: https://github.com/42wim/matterbridge/wiki/Gateway-config-(channel-rules)/bda41b26dc1a4e3f1d5fddff94870f0447e46e0d

**Comment by 42wim** [comment]
@ViRb3 thanks, looks good!
