### ISSUE TITLE
Slack Block Kit API appears to cause issues in nlopes/slack

### ISSUE THREAD

**Issue by jheiselman** [42wim/matterbridge#937]
**Describe the bug**
Some Slack teams are starting to receive Slack event messages using the new Block Kit functionality (a WYSIWYG method for user text styling) that is causing issues in the nlopes/slack library (UnmarshallingErrorEvent). It appears that this may require an API breaking change to nlopes/slack in order to accommodate it. Teams have no control over whether or not their workspace has this feature enabled and so there is no suitable workaround today.

I am submitting this bug report to this repo because this issue is effecting matterbridge users and believe that noting the cause and being able to track the upstream issue may save other people time in troubleshooting.

nlopes/slack issue: https://github.com/nlopes/slack/issues/579

**To Reproduce**
There is currently no method of recreating this behavior on demand. One user (RAF in Discord) is affected and can reproduce at will, however, my own instance seems to be unaffected entirely.

**Expected behavior**
Messages should be relayed properly from Slack to other bridged destinations.

**Screenshots/debug logs**

**Environment (please complete the following information):**
Tested with 1.16.0 and 1.16.1 along with a custom build available at jheiselman/matterbridge which contains just a basic modification that helped to log the raw content of the message causing the issue.

**Additional context**

**Comment by 42wim** [comment]
I've added a branch https://github.com/42wim/matterbridge/tree/f-slackunknown that contains a PR on slack/nlopes that should fix the issue.
