### ISSUE TITLE
Missing documentation for Keybase

### ISSUE THREAD

**Issue by w3bb** [42wim/matterbridge#938]
Currently the documentation for Keybase is non-existent. A section on the wiki for it would be incredibly helpful.

**Comment by geleeroyale** [comment]
I'd like to setup a keybase <-> riot bridge. Can also contribute documentation, but need a pointer on how to start.

**Comment by hyperobject** [comment]
I'll throw together a wiki page real quick, thanks for the ping @geleeroyale!

**Comment by hyperobject** [comment]
Created https://github.com/42wim/matterbridge/wiki/Section-Keybase-(basic) and updated [the gateway config docs](https://github.com/42wim/matterbridge/wiki/Gateway-config-(channel-rules))! Let me know if anything's missing.

**Comment by geleeroyale** [comment]
Thank you very much. It works very well if one goes by the documentation! This issue can be closed in my opinion, right @w3bb ?

**Comment by 42wim** [comment]
Thanks @hyperobject !
I've also added it to https://github.com/42wim/matterbridge/wiki/How-to-create-your-config

**Comment by 42wim** [comment]
I'm going to close this, if you still have problems feel free to reopen
