### ISSUE TITLE
Can matterbridge be used to migrate Mattermost to Matrix?

### ISSUE THREAD

**Issue by hamoid** [42wim/matterbridge#939]
Hi! I would like to migrate from one platform to another, but I don't see a way to export all data and then import it into the new platform.

Since Matterbridge can interact with both platforms, is there a way to move **old** posts and attachments from one to the other? Or is Matterbridge designed in a way that only **new** posts can be bridged?

**Comment by qaisjp** [comment]
as far as i know, matterbridge is only for live syncing (bridging) of chat messages, and not a chat migration service.

you might be able to extend the code or use matterbridge's API to add migration features, but i don't think anything like this is inbuilt

**Comment by 42wim** [comment]
@qaisjp is correct, we don't have support for this and it's not in scope for this project.
