### ISSUE TITLE
SSH-Chat messages not relayed to other protocols

### ISSUE THREAD

**Issue by thefeiter** [42wim/matterbridge#941]
[sshchat.chat]
Server="xxxxxxx.de:22"
Nick="matterbridge"
RemoteNickFormat="[{PROTOCOL}] @{NICK}: "

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="sshchat.chat"

[[gateway.inout]]
account="xxxxxxxxx"

That's part of my config. But somehow SSH-Chat only recieves messages from other protocols, but its messages are not getting relayed...

**Comment by 42wim** [comment]
Hi, apparently I forgot to put in some documentation for sshchat
Now added on https://github.com/42wim/matterbridge/wiki/Section-Sshchat-(basic) and https://github.com/42wim/matterbridge/wiki/Gateway-config-%28channel-rules%29

You forgot to specify channels in your config. For sshchat you need to put `channel="sshchat"`

```
[sshchat.chat]
Server="xxxxxxx.de:22"
Nick="matterbridge"
RemoteNickFormat="[{PROTOCOL}] @{NICK}: "

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="sshchat.chat"
channel="sshchat"

[[gateway.inout]]
account="xxxxxxxxx"
channel="xxxxx"
