### ISSUE TITLE
Skip messages using tengo script

### ISSUE THREAD

**Issue by vladdy-moses** [42wim/matterbridge#942]
**Is your feature request related to a problem? Please describe.**
We need to skip some messages in gateway.
Ex, only "@channel" messages in mattermost should be sent into telegram.

**Describe the solution you'd like**
I'd like to have some feature to manage that filter.
Tengo's OutMessage script is a brilliant choice, because there are many global variables wich can help us to make this message filter.

**Describe alternatives you've considered**
Also another tengo script like `FilterMessage` may be interesting.

**Additional context**
Out team uses mattermost but in some cases we need to send important messages (with "@channel" tag) to special chat in telegram.
I'm not go programmer and can't find solution for now.

**Comment by 42wim** [comment]
The tengo script is the way to go for this.
My current stance is to not add any more features in matterbridge that can be handled by Tengo.
Feel free to ask help if you're stuck with Tengo

**Comment by vladdy-moses** [comment]
Ok. So how can we filter messages by Tengo?

**Comment by 42wim** [comment]
You can find more tengo examples here:
https://github.com/42wim/matterbridge/issues?q=is%3Aissue+tengo+label%3Atengo+is%3Aclosed

here:
https://github.com/42wim/matterbridge/tree/master/internal/tengo

and here:
https://github.com/42wim/matterbridge/tree/master/contrib

The tengo documentation can be found here: 
https://github.com/d5/tengo/tree/master/docs
