### ISSUE TITLE
If it can't connect to a service, the entire bridge stops working.

### ISSUE THREAD

**Issue by LucesEnBabel** [42wim/matterbridge#945]
**Describe the bug**
[There are connection issues](https://status.matrix.org/incident/11) with the matrix.org server which prevents the bridge from connecting, however, our bridge includes more than 2 protocols. 

**To Reproduce**
· Attempt to start Matterbridge with an invalid or unreachable service.

**Expected behavior**
Matterbridge should ignore the faulty service and continue the normal functionality, and attempt to reconnect to the faulty one after a while.

**Screenshots/debug logs**
```
[2019-11-14T17:33:09Z]  INFO matrix:       matrix.mymatrix: joining #(redacted):matrix.org (ID: #(redacted):matrix.orgmatrix.mymatrix)
[2019-11-14T17:33:20Z] FATAL main:         Starting gateway failed: Bridge matrix.mymatrix failed to join channel: (redacted) msg=Failed to POST
JSON to /_matrix/client/r0/join/#(redacted):matrix.org: <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
 code=503 wrapped=
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Matterbridge version: version: 1.16.1 bad1990

**Comment by 42wim** [comment]
There is a setting for it.
See https://github.com/42wim/matterbridge/wiki/Settings#ignorefailureonstart
