### ISSUE TITLE
Prevent mentions for users with the same username

### ISSUE THREAD

**Issue by 2secslater** [42wim/matterbridge#946]
Currently, if you are connected to a room with the same username as someone on one of the bridged channels, you will be mentioned by the bot whenever they speak.

**Describe the solution you'd like**
I would like to see an implementation similar to what is in reactiflux/discord-irc:
```js
if (this.ircPreventMention) {
        // Prevent users of both IRC and Discord from
        // being mentioned in IRC when they talk in Discord.
        displayUsername = `${displayUsername.slice(0, 1)}\u200B${displayUsername.slice(1)}`;
      }
```
where a zero length character (so basically an invisible character) is placed after the first letter of the username. This prevents the chat clients from picking up the username as a mention, since it will not match the actual username.

**Additional context**
![Screenshot](https://i.imgur.com/5TyCcF1.png)

**Comment by 42wim** [comment]
That implementation already exists, see `NOPINGNICK` in https://github.com/42wim/matterbridge/wiki/Settings#remotenickformat 

Or use [tengo scripting](https://github.com/42wim/matterbridge/wiki/Settings#tengo) to use whatever character, filtering you want :)
