### ISSUE TITLE
Could not find Gitter roomID

### ISSUE THREAD

**Issue by and-semakin** [42wim/matterbridge#952]
**Describe the bug**
I try to bridge Telegram chat with Gitter room. Matterbridge successfully connects to Telegram but can't connect to Gitter. User is already in the specified room.

Why can't it find roomID?

**To Reproduce**

**Expected behavior**
Successfully connect to the Gitter room, user already is in the room.

**Screenshots/debug logs**
```
matterbridge_1  | time="2019-11-30T08:56:33Z" level=info msg="Running version 1.16.3-dev 173a38a" prefix=main
matterbridge_1  | time="2019-11-30T08:56:33Z" level=info msg="WARNING: THIS IS A DEVELOPMENT VERSION. Things may break." prefix=main
matterbridge_1  | time="2019-11-30T08:56:33Z" level=info msg="Parsing gateway flask-user" prefix=router
matterbridge_1  | time="2019-11-30T08:56:33Z" level=info msg="Starting bridge: gitter.flask-user-bridge " prefix=router
matterbridge_1  | time="2019-11-30T08:56:33Z" level=info msg=Connecting prefix=gitter
matterbridge_1  | time="2019-11-30T08:56:34Z" level=info msg="Connection succeeded" prefix=gitter
matterbridge_1  | time="2019-11-30T08:56:34Z" level=info msg="gitter.flask-user-bridge: joining Flask-User/community (ID: Flask-User/communitygitter.flask-user-bridge)" prefix=gitter
matterbridge_1  | time="2019-11-30T08:56:34Z" level=fatal msg="Starting gateway failed: Bridge gitter.flask-user-bridge failed to join channel: Could not find roomID for Flask-User/community. Please create the room on gitter.im" prefix=main
```
I can do it if I make request manually using for example Postman:
![image](https://user-images.githubusercontent.com/9129071/69898450-a34f2680-137b-11ea-92e1-d5fa1ba80a69.png)

**Environment (please complete the following information):**
 - OS: Linux, Docker image `42wim/matterbridge:latest` built from [this commit](https://github.com/42wim/matterbridge/tree/173a38a37416045958b33fe7c0f68e26880f6e2b)
 - Matterbridge version: 1.16.3-dev 173a38a

**Additional context**
My config:
```
[telegram]
[telegram.flask_user_bridge_bot]
Token="123:qwertyASnbqnwmejkzxcyuqwe"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
MessageFormat="Markdown"

[gitter]
[gitter.flask-user-bridge]
#You can get your token by going to https://developer.gitter.im/docs/welcome and SIGN IN
Token="qweuxcnqwe129387chk"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="flask-user"
enable=true

[[gateway.inout]]
account="telegram.flask_user_bridge_bot"
channel="-1001192489017"

[[gateway.inout]]
account="gitter.flask-user-bridge"
channel="Flask-User/community"
```

**Comment by 42wim** [comment]
I've looked into the library we use and it uses this call to find the room:`https://api.gitter.im/v1/rooms?q=Flask-User/community` which shows up empty.

Information here: https://developer.gitter.im/docs/rooms-resource
Seems to be a gitter API issue, could you open an issue there?

**Comment by 42wim** [comment]
I'll think about maybe using a workaround so you can add an ID explicitly

**Comment by and-semakin** [comment]
I created an issue in Gitter repo: https://gitlab.com/gitlab-org/gitter/webapp/issues/2384
Let's see what they answer.

**Comment by 42wim** [comment]
@and-semakin seems to be fixed upstream now according to the issue? Can you confirm?

**Comment by and-semakin** [comment]
Confirm. It was a bug in Gitter search subsystem.
