### ISSUE TITLE
XMPP server component support?

### ISSUE THREAD

**Issue by poVoq** [42wim/matterbridge#955]
**Is your feature request related to a problem? Please describe.**
Pure bot bridging isn't really all that great, if a network supports something better, maybe it can be used?

**Describe the solution you'd like**
There is a cool Golang library to enable XMPP server component support:
https://github.com/sheenobu/go-xco
That way Matterbridge gets basically a lot more freedom how to present users etc.

Thanks for considering this as an additional option to connect to XMPP networks.

**Comment by 42wim** [comment]
Closing this in favor #191 
Looking back for this when DM's will be implemented
