### ISSUE TITLE
Feature request : commands to display mattermost users

### ISSUE THREAD

**Issue by valvin1** [42wim/matterbridge#96]
### Which version of matterbridge are you using?
v0.9.1-dev on Mattermost v3.5.1

### Please describe the expected behavior.

Would it be possible to run `!users` on all protocols and displays as a result the currently users on mattermost side ?
 
If there are several protocols it should displays all users from all bridged protocol except the protocol where the command is run. 

And even in the current feature on mattermost side, it should be interesting to split users by status : only / sleep mode ...

**Comment by guakamole** [comment]
More broadly, this feature would be useful from/to all protocols. A simple command (sent as a DM/PM to the bot for instance) that would provide a list of users.

Use case: IRC (inout) ↔ XMPP MUC (inout) bridge. From an IRC channel, being able to get a list of users on a XMPP MUC. From an XMPP MUC, being able to get a list of users on an IRC channel.

**Comment by 42wim** [comment]
@guakamole  Yes indeed, unfortunately it isn't that simple to implement. (needs some redesign)
This will be added to the matterbridge api first and then also added as commands to the bot.

**Comment by guakamole** [comment]
I'm wiling to help but have little experience with Go (willing to learn as well).

Is there anything that could be done to help you (maybe minor tasks that you are wasting time on that could be delegated)?

**Comment by 42wim** [comment]
@guakamole depending on what exactly you want to do, but non-coding stuff is also very much appreciated. 

Like trying to improve the documentation or the wiki, maybe things you experienced that wasn't so simple and could be explained better.

Also be free to answer on other open issues if you think you can solve them or if they haven't given enough information.

Or coming up with new features :)

**Comment by 42wim** [comment]
Going to close this in favor of the generic proposal #361
