### ISSUE TITLE
[irc] ability to send !/. commands over the bridge to irc bots

### ISSUE THREAD

**Issue by dereckhall** [42wim/matterbridge#961]
Would be nice to have the ability to issue !command/.command over the bridge to IRC
This would allow interaction with eggdrop bots etc.

Currently when !command/.commands are issued it simply shows it being relayed through the matterbridge bot via your nick, which is ignored by IRC bots.

discord> NickMe: !weather
irc> <matterbridgebot> <NickMe> !weather
-- what would work
discord> NickMe: !weather
irc> <matterbridgebot> NickMe requested !weather
irc> <matterbridgebot> !weather
irc> <weatherbot> Today's low is xxxxxxx

**Comment by qaisjp** [comment]
i think this can be done via tengo.

**Comment by dereckhall** [comment]
thanks. can you please point me to any decent documentation w/ (hopefully) examples showing how to manipulate outgoing messages to the irc portion of the bridge and well as set a reply from the irc portion to the requester portion of the bridge? 

thanks - sorry for the delay... holidays etc.

**Comment by qaisjp** [comment]
There's a section on tengo in the wiki: https://github.com/42wim/matterbridge/wiki/Settings#tengo

**Comment by cremesk** [comment]
Thanks for the link to the documentation. Could we get another example, please? Unfortunately I still don't know how to use tengo in the matterbridge config.

For example, I would like to send a message to an irc channel from a matrix chat room.

matrix-chat:
```
myNICK: ,w
```
irc-chat:
```
bridge: <myNICK> ,w
```
but i need in the irc-chat:
```
myNICK: ,w
```

Thank you very much for any help!

**Comment by 42wim** [comment]
You can find more tengo examples here:
https://github.com/42wim/matterbridge/issues?q=is%3Aissue+tengo+label%3Atengo+is%3Aclosed

here:
https://github.com/42wim/matterbridge/tree/master/internal/tengo

and here:
https://github.com/42wim/matterbridge/tree/master/contrib

**Comment by dereckhall** [comment]
i figure i'm just going about this all wrong:

text := import("text") #reading all incoming text
if text.re_match(^\..*) { #marching anything beginning with a period
    msgUsername="" # removing the username
}

bad syntax
level=fatal msg="Failed to parse the configuration: While parsing config: (383, 6): was expecting token =, but got keys cannot contain : character instead" prefix=config

**Comment by qaisjp** [comment]
I think `text := import("text")` imports the `text` _library_, and not "reading all incoming text".

You probably want to do ``if text.re_match(msgUsername, `^\..*`) {`` (assuming that tengo supports backticks for strings).

Have you taken a look at [the contrib directory](https://github.com/42wim/matterbridge/tree/master/contrib)?
