### ISSUE TITLE
[Telegram -> Discord] Photo captions don't come through when webhooks are used

### ISSUE THREAD

**Issue by Mikaela** [42wim/matterbridge#962]
**Describe the bug**

When I upload a photo or picture to Telegram, it appears to Discord, but without the caption.

**To Reproduce**

1. Setup a Matterbridge between Telegram and Discord using webhooks.
2. Upload a photo with caption to Telegram.
3. The photo appears at Discord without caption.

**Expected behavior**

The photo sent at Telegram will appear at Discord.

**Screenshots/debug logs**

![Telegram](https://user-images.githubusercontent.com/831184/71109180-61244280-21cd-11ea-8a07-7d9aee1bff3d.png)

![Discord](https://user-images.githubusercontent.com/831184/71109120-43ef7400-21cd-11ea-8e0e-33e8ee58025e.png)

I am unable to provide debug logs at this time as the debug logs are too verbose and the bot is on two very active groups at the moment and I don't know how to grep. I will get back to this later.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Matterbridge version: 1.16.2 214fe50

**Additional context**

The config file contains 756 lines, so I am cutting it to only protocol and gateway configuration.

```
[discord.piraatit]
Token="REDACTED"
Server="381849409643610122"
UseUsername=false
UseDiscriminator=false
Label="D"
RemoteNickFormat="[{LABEL}] {NICK} "

[discord.piraattinuoret]
Token="REDACTED"
Server="374659905333886979"
UseUsername=false
UseDiscriminator=false
Label="D"
RemoteNickFormat="[{LABEL}] {NICK} "

[telegram.ppfimatterbridge]
Token="REDACTED"
Label="T"

[irc.pirateirc]
Nick="MI1"
NickServNick="MI1"
NickServPassword="REDACTED"
Server="roubaix-fr.pirateirc.net:6697"
UseTLS=true
UseSASL=true
SkipTLSVerify=false
ReplaceNicks=[ ["T4","Telegram"] ]
IgnoreNicks="ChanServ Bunny Tails Blackbeard PirateIRC BotServ"
MessageSplit=true
Label="I"

[general]
RemoteNickFormat="[{LABEL}] <{NICK}> "
MediaDownloadPath="/var/www/html/matterbridge"
MediaServerDownload="REDACTED"
MediaDownloadSize=20000000
MediaDownloadBlacklist=[".html$",".htm$"]
IgnoreFailureOnStart=true

[[gateway]]
name="testi"
enable="true"

    [[gateway.inout]]
    account="irc.pirateirc"
    channel="#test"

    [[gateway.inout]]
    account="discord.piraatit"
    channel="ID:591537059781410816"
    [gateway.inout.options]
    WebhookURL="REDACTED"

    [[gateway.inout]]
    account="discord.piraattinuoret"
    channel="ID:375207988459470849"
    [gateway.inout.options]
    #WebhookURL=""

    [[gateway.inout]]
    account="telegram.ppfimatterbridge"
    channel="-1001144715238"
```

**Comment by 42wim** [comment]
Should be fixed in master now, but I don't have telegram so can't test it myself.
