### ISSUE TITLE
Feature request: allow limiting reply/quote size/length

### ISSUE THREAD

**Issue by Mikaela** [42wim/matterbridge#963]
**Is your feature request related to a problem? Please describe.**

When I reply to a message from Telegram, the whole message gets quoted and that can be difficult to users on other protocols.

**Describe the solution you'd like**

[FruitieX/TeleIRC](https://github.com/fruitiex/teleirc) where I migrated to Matterbridge had an option to specify how much of the old message is quoted and I found 46 a good size.

I wish I could make the quote format:

`User-Replied-to [<reply restricted to 46 characters]…], the new message`

The closest to this that I have found is [QuoteDisable/QuoteFormat from the matterbridge.toml.sample](https://github.com/42wim/matterbridge/blob/v1.16.3/matterbridge.toml.sample#L852-L858) but it has no indication on how would I restrict the quote length.

**Comment by Humorhenker** [comment]
We could alter the function handleQuote.
I will propose a modification later

**Comment by Humorhenker** [comment]
a posible solution is proposed under the pull request #985
you can try it out if you want by compiling and running [https://github.com/Humorhenker/matterbridge](https://github.com/Humorhenker/matterbridge)

**Comment by 42wim** [comment]
Thanks to @Humorhenker this is now available in master
