### ISSUE TITLE
ZNC - Ignore buffer playback / large amount of messages on connect

### ISSUE THREAD

**Issue by hashworks** [42wim/matterbridge#965]
I'm using matterbridge as a transparent bridge between IRC and Telegram. From the point of view of others I'm always connected and always using the same nickname. To archive this I use ZNC as an IRC bouncer to which matterbridge connects.

The problem occurs on restarts / reconnects of matterbridge: A large amount of messages (hundreds) are sent by ZNC to the client (matterbridge). This is used by ZNC to deliver the buffer of unread messages to the client, called the playback. Matterbridge however bridges those painfully slow to Telegram, taking multiple minutes before it's "ready" to deliver messages in real time.

So for one I wonder why the delay occurs (any `MessageDelay` for Telegram?). However, there is no need to show those messages, matterbridge could ignore them just fine. Easy solutions would be to ignore the first few seconds of messages or the first X messages from IRC. Another (cleaner) way would be to support the [Playback](https://wiki.znc.in/Playback) ZNC module and tell it not to send any playback.

**Comment by qaisjp** [comment]
In the meantime you turn off the playback module for that account?

**Comment by hashworks** [comment]
I could tell the server to not send any playback, yes – that has nothing to do with the linked module. I'll try that for debugging purposes.

**Comment by 42wim** [comment]
From this page: https://wiki.znc.in/Playback
>The module also allows configuring client specific buffer limits for identified clients, using the following command syntax:
   /msg *playback LIMIT <client> [limit]
A limit of less or equal to 0 clears the limit. Notice that the limit cannot exceed the limit set in the ZNC configuration, but can be used to limit the playback for eg. mobile clients.

You could try to do https://github.com/42wim/matterbridge/wiki/Settings#runcommands

`RunCommands=["PRIVMSG *playback :LIMIT clientid -1"]`

**Comment by 42wim** [comment]
@hashworks did my suggestion help?

**Comment by hashworks** [comment]
Sorry for the delay. I'm now using the [clientbuffer](https://wiki.znc.in/Clientbuffer) plugin, seems to work fine. As you suggested I added an identifier to matterbridge, which allows one to set a negative timelimit:
`/msg *clientbuffer SetClientTimeLimit matterbridge -1`
