### ISSUE TITLE
Feature request - bridge *slash* commands

### ISSUE THREAD

**Issue by varod** [42wim/matterbridge#97]
### Which version of matterbridge are you using?
v0.9.1-dev / Mattermost v3.5.1

### Please describe the expected behavior.
On Mattermost side we can define some *slash commands* which can be useful for all protocols. For example if I've a slash commands `/wiki` it can be interesting to use it on other protocols.

If it is not enought clear let me know i'll detail more

**Comment by 42wim** [comment]
I haven't tested the slash commands yet, isn't the output visible on the other bridges when you execute a slash command ?
