### ISSUE TITLE
Add ability to template out avatar url

### ISSUE THREAD

**Issue by josegonzalez** [42wim/matterbridge#978]
**Is your feature request related to a problem? Please describe.**

When relaying messages from irc to slack, the slack avatar is the generic image for the Slack App. This makes it a bit less clear as to who is speaking for busy channels.

**Describe the solution you'd like**

It would be great if you could specify an image override when sending messages to slack. This could be a "templatable" url that would provide an image. For example,

```toml
AvatarUrl="https://api.adorable.io/avatars/48/{NICK}
```

**Describe alternatives you've considered**

Hardcoded support for adorable avatars would be cool, but I'd imagine others might want to provide their own avatar apis.

**Comment by 42wim** [comment]
Hi, this is already possible, see https://github.com/42wim/matterbridge/wiki/Settings#iconurl-1
and

**Comment by josegonzalez** [comment]
Seems like that works! Thanks for the quick response!
