### ISSUE TITLE
After update of mattermost and bridge, the bridge can't connect to mattermost

### ISSUE THREAD

**Issue by NicolasDorier** [42wim/matterbridge#981]
We updated our infrastructure here:
https://github.com/btcpayserver/btcpayserver-infra/pull/14

This was working fine before.

Now it fails connecting

```
time="2020-01-11T16:00:41Z" level=info msg="Starting bridge: mattermost.btcpay " prefix=router
time="2020-01-11T16:00:41Z" level=info msg="Connecting using login/password (sending and receiving)" prefix=mattermost
time="2020-01-11T16:00:41Z" level=info msg="Connecting btcpay_bot (team: btcpayserver) on chat.btcpayserver.org" prefix=mattermost
time="2020-01-11T16:00:41Z" level=debug msg="trying login btcpayserver btcpay_bot chat.btcpayserver.org" prefix=matterclient
time="2020-01-11T16:00:41Z" level=fatal msg="Starting gateway failed: Bridge mattermost.btcpay failed to start: " prefix=main
```

The error is not so helpful so I am at loss knowing what happen.
We tried to downgrade the bridge, but same issue. I guess the new version of mattermost broke something then?

**Comment by 42wim** [comment]
That's very strange that there is no error listed after "failed to start:"
Is that all the debug info there is from mattermost/matterclient output?

**Comment by 42wim** [comment]
FYI, I upgraded my test setup to 5.18.1, works fine

```
[0018]  INFO router:       Starting bridge: mattermost.testwim
[0018]  INFO mattermost:   Connecting using login/password (sending and receiving)
[0018]  INFO mattermost:   Connecting wim@test (team: wim) on test
[0018]  INFO matterclient: Found version 5.18.0.5.18.1.1b362fc768d984cb23c2f750067c823d.false
```

**Comment by NicolasDorier** [comment]
So yes, I am sure there was no more messages after that. The container just restart.

That said we also have another unrelated issue in mattermost, which may have the same root cause of this bug. (Maybe a mattermost DB issue?)

I will edit around more tomorrow and keep you up to date.

**Comment by NicolasDorier** [comment]
Thanks for checking @42wim .

I updated after I saw that users could not register anymore.
After the update, this bug happened on the bridge. You could not reproduce, so I suspected that both issues were from the same source.

After trying to execute some requests of mattermost by hand, I noticed that a table was corrupted.

I followed the instructions on [this blog post](https://postgresdesk.blogspot.com/2018/11/postgres-corruption-error-invalid-page.html), and this solved the problem.

That said, I think there is a bug in the mattermostbridge concerning the logs:
`"Starting gateway failed: Bridge mattermost.btcpay failed to start: " ` The string after `:` is empty, which seem weird.

Anyway closing this issue as this is unrelated.
