### ISSUE TITLE
Reddit Chat support

### ISSUE THREAD

**Issue by haykam821** [42wim/matterbridge#986]

**Comment by 42wim** [comment]
See https://github.com/bonehurtingjuice/mattereddit

**Comment by haykam821** [comment]
@42win That implementation leaves much to be desired. There is [an API](https://docs.sendbird.com/platform) that could instead be used to provide a built-in bridge to Reddit Chat.

**Comment by 42wim** [comment]
@haykam821, thanks I'll add it to #28
