### ISSUE TITLE
matterbridge-whatsapp not exiting after ERROR

### ISSUE THREAD

**Issue by sistason** [42wim/matterbridge#987]
**Describe the bug**
When the Whatsapp connection goes down (#871 ), the gateway(s) go stuck, as matterbridge does not terminate from that. As all the gateways use this whatsapp-account, matterbridge becomes stuck and unuseable until you detect this issue and restart manually.

`level=error msg="connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpected EOF" prefix=whatsapp`

**To Reproduce**
- Create a config with a Whatsapp account
- wait until Whatsapp crashes/terminates (<2h)
- matterbridge throws the error shown above, but stays active

**Expected behavior**
matterbridge should terminate (Since the EOF happens and is not yet fixed), in order for scripts / docker-compose restart: always to be able to restart it, or monitoring to even notice the connection close without parsing the logs.

**Screenshots/debug logs**
```
$ docker-compose logs
[...]
whatsapp-gateways_1  | [14018] DEBUG gateway:      mID rocketchat.XXX: 0.746153
whatsapp-gateways_1  | [14018] DEBUG rocketchat:   message models.Message{ID:"0.746153"  [...]
whatsapp-gateways_1  | [14018] DEBUG rocketchat:   Skipped message: models.Message{ID:"0.746153" [....]
whatsapp-gateways_1  | [14165] ERROR whatsapp:     connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpected EOF

$ docker-compose ps
              Name                         Command            State   Ports
---------------------------------------------------------------------------
matterbridge_whatsapp-gateways_1   /bin/matterbridge -debug   Up
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 VM, docker 19.3
 - Matterbridge version: latest from dockerhub (1.16.4-dev 4c44515f)

**Additional context**
Whatsapp -> Rocketchat,
2 gateways connecting 2 whatsapp groups with gateway.inout to 2 rocktchat-channels.
Works well, only the error-handling seems off.

**Comment by 42wim** [comment]
@sistason I've added reconnect support into master.
You can also download a dev binary from https://bintray.com/beta/#/42wim/nightly/Matterbridge/v1.16.5-9-g1985873?tab=files

Feel free to reopen if this doesn't fix the issue

**Comment by micw** [comment]
Hi. I had whatsapp hanging today with the following message:
`connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpected EOF`

It tried to reconnect every 5 mins and got no messages. After restarting the service, it worked again. So I think it's better to exit on that error rather than trying to reconnect (or exit after a number of retries)
