### ISSUE TITLE
Go panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by nios34** [42wim/matterbridge#988]
**Describe the bug**
index out of range when Docker container starts

**To Reproduce**
I just pull the "42wim/matterbridge:latest", and run "docker run -v /etc/TG2IRC/matterbridge.toml:/matterbridge.toml 42wim/matterbridge", soon the error happened

**Expected behavior**
I just want to make a TG2IRC bridge.

**Screenshots/debug logs**
```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/42wim/matterbridge/bridge.New(0xc0001bd840, 0xc0001bd840)
        /go/src/github.com/42wim/matterbridge/bridge/bridge.go:45 +0x21c
github.com/42wim/matterbridge/gateway.(*Gateway).AddBridge(0xc000082a80, 0xc0001bd840, 0x2, 0x2)
        /go/src/github.com/42wim/matterbridge/gateway/gateway.go:89 +0x133
github.com/42wim/matterbridge/gateway.(*Gateway).AddConfig(0xc000082a80, 0xc000082a20, 0xc000328570, 0x0)
        /go/src/github.com/42wim/matterbridge/gateway/gateway.go:130 +0x2ab
github.com/42wim/matterbridge/gateway.New(0xc0002e7c70, 0xc000082a20, 0xc0002e4190, 0x7)
        /go/src/github.com/42wim/matterbridge/gateway/gateway.go:58 +0x1dc
github.com/42wim/matterbridge/gateway.NewRouter(0xc0002e7c70, 0x55d025496d20, 0xc000328390, 0xc00003f3b0, 0xc000328390, 0x2, 0x2)
        /go/src/github.com/42wim/matterbridge/gateway/router.go:53 +0x391
main.main()
        /go/src/github.com/42wim/matterbridge/matterbridge.go:53 +0x435
```
*** Sorry I can run the docker container, so I can't get the debug info ***

**Environment (please complete the following information):**
 - OS: Linux
 - Matterbridge version: latest(Commit 4c44515)
 - Docker version 19.03.5, build 633a0ea
 - Linux localhost.localhost 4.9.206-36.el7.x86_64 #1 SMP Mon Dec 9 17:27:42 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
This is my config file.
```
[irc]
    [irc.nios34]
    Server="xxxxx"
    Nick="TG2IRC"

[telegram]
        [telegram.botnios]
        Token="XXXX"

[general]
RemoteNickFormat="<{NICK}> "

[[gateway]]
name="TG2IRC"
enable=true

[[gateway.inout]]
accout="telegram.botnios"
channel=-XXXXXX

[[gateway.inout]]
accout="irc.nios34"
channel="#acgp-chat"
```

**Comment by 42wim** [comment]
You've got a typo in `accout` must be `account`

**Comment by nios34** [comment]
> You've got a typo in `accout` must be `account`

This may caused this poblem?

**Comment by nios34** [comment]
It just gave me "index out of range", No other details.

**Comment by 42wim** [comment]
Fixing the typo will fix the crash.
I'll add an extra check for this.
