### ISSUE TITLE
Certain Links not displaying correctly on Matrix

### ISSUE THREAD

**Issue by frabrunelle** [42wim/matterbridge#989]
When I send a message that contains a link (e.g. https://safenetforum.org/t/safe-network-dev-update-january-30-2020/31006) from Telegram or Discord, the link is not displayed correctly on Matrix.

Only https://safenetforum.org/t/safe-network-dev-update-january-30- is clickable and the rest is displayed as a fraction.

<img width="1213" alt="Screen Shot 2020-01-30 at 12 21 23 PM" src="https://user-images.githubusercontent.com/1114844/73473611-0d278480-435b-11ea-9441-352a147c0949.png">

I'm running the latest version of Matterbridge (commit fc30b1b) using Docker.

**Comment by 42wim** [comment]
Thanks for reporting, fixed in master now
